SELECT  '<Table p="' || TAB.TABLE_NAME || '" n="' || TAB.TABLE_NAME || '"><Properties><Property k="SEQ:I:' || TAB.TABLE_NAME || '" v="' || SEQ.SEQUENCE_NAME || '" /></Properties></Table>' AS OUTPUT
FROM 
(
  SELECT  TABLE_NAME, SUBSTR(TABLE_NAME, INSTR(TABLE_NAME , '_', 1, 1) + 1,  INSTR(TABLE_NAME , '_', 1, 3) - INSTR(TABLE_NAME , '_', 1, 1) - 1) AS PREFIXO_TABLE
  FROM    ALL_TABLES 
  WHERE   OWNER = 'SGS'
) TAB
JOIN
(
  SELECT  SEQUENCE_NAME, SUBSTR(SEQUENCE_NAME, INSTR(SEQUENCE_NAME , '_', 1, 1) + 1,  INSTR(SEQUENCE_NAME , '_', 1, 3) - INSTR(SEQUENCE_NAME , '_', 1, 1) - 1) AS PREFIXO_SEQUENCE
  FROM    ALL_SEQUENCES SEQ
  WHERE   SEQUENCE_OWNER = 'SGS'
) SEQ
ON  TAB.PREFIXO_TABLE = SEQ.PREFIXO_SEQUENCE
WHERE TABLE_NAME NOT LIKE 'TB_TMP%'
AND LENGTH(SEQ.SEQUENCE_NAME) = 14
ORDER BY TAB.TABLE_NAME


