  create or replace function FNC_BUSCAR_ULT_ATD_PS
  (
  pCAD_PES_ID_PESSOA in TB_CAD_PES_PESSOA.CAD_PES_ID_PESSOA%type,
  pDATA_INI in TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%type,
  pDATA_FIM in TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%type,
  pTIS_CBO_CD_CBOS varchar2 default null,
  pCAD_UNI_ID_UNIDADE in TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL
  )
  /*
  Buscar a 1 data int na uti
  */
   return NUMBER is
   Result NUMBER;
  begin

  if (pCAD_PES_ID_PESSOA is not null) THEN

     SELECT
                   MAX(ATD.ATD_ATE_ID)
                    INTO RESULT
               --   ATD.ATD_ATE_DT_ATENDIMENTO, ATD.ATD_ATE_HR_ATENDIMENTO,
              --    FNC_JUNTAR_DATA_HORA(ATD.ATD_ATE_DT_ATENDIMENTO, ATD.ATD_ATE_HR_ATENDIMENTO) DTHR,
               --  PAC.CAD_PES_ID_PESSOA

            FROM TB_ATD_ATE_ATENDIMENTO ATD
            join TB_CAD_PAC_PACIENTE PAC on PAC.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(ATD.ATD_ATE_ID)

            WHERE ATD.ATD_ATE_FL_STATUS = 'A'
             AND ATD.TIS_TAT_CD_TPATENDIMENTO = 4 
            -- AND ATD.CAD_UNI_ID_UNIDADE = 250
             AND ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO IN (30,34)
             AND (pCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
             AND FNC_JUNTAR_DATA_HORA(ATD.ATD_ATE_DT_ATENDIMENTO, ATD.ATD_ATE_HR_ATENDIMENTO) between pDATA_INI and pDATA_FIM
             and PAC.CAD_PES_ID_PESSOA = pCAD_PES_ID_PESSOA
             AND (pTIS_CBO_CD_CBOS  IS NULL OR ATD.TIS_CBO_CD_CBOS IN ( SELECT * FROM TABLE(FNC_SPLIT( pTIS_CBO_CD_CBOS ))))
  --'06132,06110,90052,06105,90053,90028,06155'

  ;
  END if;
    return(Result);
  end FNC_BUSCAR_ULT_ATD_PS;
