create or replace function sgs.FNC_INT_QTD_DIA_ANTERIOR
(
  pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE,
  pATD_ATE_DT_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
  pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO VARCHAR2 DEFAULT NULL--,
)
---retorna a qtd de int vindos do dia anterior, ou seja q continuam internados
return NUMBER is Result NUMBER;
begin

       SELECT   SUM( Count(DISTINCT IML.ATD_ATE_ID))   INTO RESULT
 -- IML.ATD_ATE_ID, IML.ATD_IML_DT_SAIDA, IML.ATD_IML_HR_SAIDA,IML.ATD_IML_DT_ENTRADA,IML.ATD_IML_HR_ENTRADA,
 -- SETOR.CAD_SET_DS_SETOR , ATD.ATD_ATE_DT_ATENDIMENTO
       FROM      TB_ATD_IML_INT_MOV_LEITO  IML
       JOIN      TB_CAD_QLE_QUARTO_LEITO   QLE
       ON        QLE.CAD_QLE_ID          = IML.CAD_CAD_QLE_ID
       JOIN      TB_ATD_ATE_ATENDIMENTO   ATD
       ON        ATD.ATD_ATE_ID         = IML.ATD_ATE_ID
       JOIN      TB_ASS_PAT_PACIEATEND      PAT
       ON        PAT.ATD_ATE_ID           = ATD.ATD_ATE_ID
       JOIN      TB_CAD_PAC_PACIENTE        PAC
       ON        PAC.CAD_PAC_ID_PACIENTE  = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
       JOIN      TB_ATD_AIC_ATE_INT_COMPL AIC
       ON        AIC.ATD_ATE_ID         = ATD.ATD_ATE_ID
       JOIN      TB_CAD_PLA_PLANO          PLA
       ON        PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
       LEFT JOIN (  SELECT    IML3.ATD_ATE_ID, IML3.ATD_IML_DT_SAIDA, IML3.ATD_IML_HR_SAIDA,
                          IML3.ATD_IML_DT_ENTRADA,IML3.ATD_IML_HR_ENTRADA, QLE3.CAD_SET_ID
                 FROM      TB_ATD_IML_INT_MOV_LEITO IML3
                 LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE3
                 ON        QLE3.CAD_QLE_ID  = IML3.CAD_CAD_QLE_ID
                 LEFT JOIN TB_ATD_ATE_ATENDIMENTO ATD3
                 ON        ATD3.ATD_ATE_ID = IML3.ATD_ATE_ID
                 WHERE     ((IML3.ATD_IML_FL_STATUS != 'C') OR (IML3.ATD_IML_FL_STATUS IS NULL))
                 ) DESTINO
        ON       DESTINO.ATD_ATE_ID = IML.ATD_ATE_ID
        AND      (DESTINO.ATD_IML_DT_SAIDA IS NULL OR DESTINO.ATD_IML_DT_SAIDA >= IML.ATD_IML_DT_ENTRADA)
        AND      DESTINO.ATD_IML_HR_ENTRADA = IML.ATD_IML_HR_SAIDA
       WHERE
       IML.ATD_IML_DT_ENTRADA < pATD_ATE_DT_ATENDIMENTO
       AND (IML.ATD_IML_DT_SAIDA = pATD_ATE_DT_ATENDIMENTO OR IML.ATD_IML_DT_SAIDA IS NULL)
       -- SE TIVER DESTINO NO MESMO DIA É PORQUE NÃO ESTA MAIS NO SETOR
       AND (DESTINO.CAD_SET_ID IS NULL OR DESTINO.CAD_SET_ID != QLE.CAD_SET_ID)
       AND QLE.CAD_SET_ID = pCAD_SET_ID
       AND  ((IML.ATD_IML_FL_STATUS != 'C') OR (IML.ATD_IML_FL_STATUS IS NULL))
       AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
       AND  ((pCAD_PLA_CD_TIPOPLANO = 'ACS' AND PLA.CAD_PLA_CD_TIPOPLANO IN ('GB','PL'))
       OR (pCAD_PLA_CD_TIPOPLANO != 'ACS' AND PLA.CAD_PLA_CD_TIPOPLANO = pCAD_PLA_CD_TIPOPLANO)
       OR (pCAD_PLA_CD_TIPOPLANO IS NULL))
       GROUP BY IML.ATD_ATE_ID

;

  return(Result);
end FNC_INT_QTD_DIA_ANTERIOR;
 