create or replace function FNC_FAT_TOTAL_ITEM
(
pFAT_COC_ID IN TB_FAT_COC_CONTA_CONSUMO.FAT_COC_ID%TYPE DEFAULT NULL,
pFAT_CCP_ID IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ID%TYPE DEFAULT NULL,
pCAD_TAP_TP_ATRIBUTO IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
pATD_ATE_ID IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_ID%TYPE DEFAULT NULL,
pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PAC_ID_PACIENTE IN TB_CAD_PAC_PACIENTE.CAD_PAC_ID_PACIENTE%TYPE DEFAULT NULL
)
---RETORNA A QTD. TOTAL R$ DO ATENDIMENTO OU INTERNAÇÃO
return NUMBER is Result NUMBER;
begin

SELECT   DISTINCT      SUM(CCI.FAT_CCI_VL_FATURADO)  INTO RESULT
              
                
 FROM          TB_ATD_ATE_ATENDIMENTO      ATD  
  JOIN          TB_FAT_COC_CONTA_CONSUMO    COC
  ON            COC.ATD_ATE_ID            = ATD.ATD_ATE_ID  
  JOIN          TB_FAT_CCP_CONTA_CONS_PARC  CCP
  ON            CCP.FAT_COC_ID            = COC.FAT_COC_ID
  AND           CCP.ATD_ATE_ID            = COC.ATD_ATE_ID
  AND           CCP.CAD_PAC_ID_PACIENTE   = COC.CAD_PAC_ID_PACIENTE
  JOIN          TB_FAT_CCI_CONTA_CONSU_ITEM CCI
  ON            CCI.FAT_CCP_ID            = CCP.FAT_CCP_ID
  AND           CCI.FAT_COC_ID            = COC.FAT_COC_ID
  AND           CCI.ATD_ATE_ID            = ATD.ATD_ATE_ID
  AND           CCI.CAD_PAC_ID_PACIENTE   = CCP.CAD_PAC_ID_PACIENTE
  JOIN          TB_CAD_PRD_PRODUTO          PRD
  ON            PRD.CAD_PRD_ID            = CCI.CAD_PRD_ID

  WHERE        (pFAT_COC_ID IS NULL OR COC.FAT_COC_ID = pFAT_COC_ID)
  AND          (pCAD_TAP_TP_ATRIBUTO IS NULL OR PRD.CAD_TAP_TP_ATRIBUTO   = pCAD_TAP_TP_ATRIBUTO)
  AND          (pFAT_CCP_ID IS NULL OR CCP.FAT_CCP_ID = pFAT_CCP_ID)
  AND          (pATD_ATE_ID IS NULL OR ATD.ATD_ATE_ID = pATD_ATE_ID)
  AND          (pCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
  AND          (pCAD_PAC_ID_PACIENTE IS NULL OR CCP.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE)
  AND           ((CCI.FAT_CCI_FL_PACOTE IS NULL) OR (CCI.FAT_CCI_FL_PACOTE = 'N')) 
  AND           (PRD.TIS_MED_CD_TABELAMEDICA != 'IP')
  AND           (CCI.FAT_CCI_FL_STATUS     = 'A')

;

return(Result);
end FNC_FAT_TOTAL_ITEM;
/
