create or replace function FNC_AGE_ESM_TIPO_TELEMEDICINA
(
 pAGE_ESM_ID in TB_AGE_ESM_ESCALA_MEDICA.AGE_ESM_ID%TYPE,
 pDATA_INI IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE,
 pDATA_FIM IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE
)
return NUMBER is Result NUMBER;
begin

       SELECT COUNT(AGG.AGE_AGG_DT_AGENDA) INTO Result
       FROM TB_AGE_AGG_AGENDA_GERADA AGG
       JOIN TB_AGE_AGD_AGENDA AGE ON AGE.AGE_AGG_ID = AGG.AGE_AGG_ID AND AGE.AGE_ESM_ID = pAGE_ESM_ID
                   AND AGE.Age_Agd_Fl_Telemedicina = 'S'
       WHERE AGG.AGE_ESM_ID = pAGE_ESM_ID
      -- AND AGG.AGE_AGG_TP_HORARIO IN (1,6)
       AND AGG.AGE_AGG_FL_STATUS_HORARIO = 2
       AND AGG.AGE_AGG_DT_AGENDA BETWEEN pDATA_INI AND pDATA_FIM;

  return(Result);
end FNC_AGE_ESM_TIPO_TELEMEDICINA;