CREATE OR REPLACE FUNCTION FNC_MTMD_REL_RFM_VAL_MES
( pREL_RFM_ANO_FECHAMENTO IN TB_REL_RFM_RESU_FAT_MTMD.REL_RFM_ANO_FECHAMENTO%type,
  pREL_RFM_MES_FECHAMENTO IN TB_REL_RFM_RESU_FAT_MTMD.REL_RFM_MES_FECHAMENTO%type,
  pREL_RFM_COD_ITEM IN TB_REL_RFM_MTMD_ESTRUTURA.REL_RFM_COD_ITEM%type,
  pREL_RMF_SEQ_ITEM IN TB_REL_RFM_MTMD_ESTRUTURA.REL_RMF_SEQ_ITEM%type,
  pREL_RFM_AGRUPAMENTO_ID IN TB_REL_RFM_MTMD_ESTRUTURA.REL_RFM_AGRUPAMENTO_ID%type,
  pTOTAL IN NUMBER, -- 0 ou 1
  pDATA_DE_TOTAL IN DATE DEFAULT NULL,
  pDATA_ATE_TOTAL IN DATE DEFAULT NULL
)
RETURN   NUMBER IS
  /********************************************************************************
  *    Data Criacao: 	 28/03/2014   Por: Andre Souza Monaco
  *    Data Alteracao: 14/04/2015   Por: Andre Souza Monaco
  *         Alteracao: Add. de parametros pDATA_DE_TOTAL e pDATA_ATE_TOTAL
  *
  *    Funcao: Retornar valores para a query da proc PRC_REL_RFM_RESU_FAT_MTMD_R
  *            de acordo com os respectivos parametros
  *********************************************************************************/
nRETORNO NUMBER;
dataRef DATE := TO_DATE(TO_CHAR('01/' || pREL_RFM_MES_FECHAMENTO || '/' || pREL_RFM_ANO_FECHAMENTO), 'DD/MM/YYYY');
BEGIN
IF (NVL(pTOTAL, 0) = 0) THEN
   IF (pREL_RFM_COD_ITEM = 'IECS') THEN
      SELECT ROUND((SELECT R.REL_RMF_VL_ITEM
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                           R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'ESTSP') /
                    (SELECT R.REL_RMF_VL_ITEM
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                            R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'CSSP'), 2)
       INTO nRETORNO FROM DUAL;
   ELSIF (pREL_RFM_COD_ITEM = 'ICSCP') THEN
      SELECT ROUND((SELECT R.REL_RMF_VL_ITEM
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                           R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'CSSP') /
                    (SELECT R.REL_RMF_VL_ITEM
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                            R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'CPSP'), 2)
       INTO nRETORNO FROM DUAL;
    ELSIF (pREL_RFM_COD_ITEM = 'IRTCS') THEN
      SELECT ROUND((SELECT R.REL_RMF_VL_ITEM
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                           R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RTOT') /
                    (SELECT R.REL_RMF_VL_ITEM
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                            R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'CSSP'), 2)
       INTO nRETORNO FROM DUAL;
   ELSIF (pREL_RFM_COD_ITEM = 'IRDSP') THEN
      SELECT ROUND((SELECT R.REL_RMF_VL_ITEM
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                           R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RTOT') /
                    (SELECT R.REL_RMF_VL_ITEM
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                            R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'DSPSP'), 2)
       INTO nRETORNO FROM DUAL;
   ELSIF (pREL_RFM_COD_ITEM = 'IRSPT') THEN
      SELECT ROUND((SELECT R.REL_RMF_VL_ITEM
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                           R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RSP') /
                    (SELECT R.REL_RMF_VL_ITEM
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                            R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'RTOT'), 2)
       INTO nRETORNO FROM DUAL;
   ELSIF (pREL_RFM_COD_ITEM = 'IRACST') THEN
      SELECT ROUND((SELECT R.REL_RMF_VL_ITEM
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                           R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RACS') /
                    (SELECT R.REL_RMF_VL_ITEM
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
                            R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'RTOT'), 2)
       INTO nRETORNO FROM DUAL;
   ELSE
       SELECT ROUND(R.REL_RMF_VL_ITEM) 
         INTO nRETORNO
         FROM TB_REL_RFM_RESU_FAT_MTMD R
        WHERE R.REL_RFM_ANO_FECHAMENTO = pREL_RFM_ANO_FECHAMENTO AND
              R.REL_RFM_MES_FECHAMENTO = pREL_RFM_MES_FECHAMENTO AND
              R.REL_RMF_SEQ_ITEM       = pREL_RMF_SEQ_ITEM;
   END IF;
ELSE
   IF (pREL_RFM_COD_ITEM = 'IECS') THEN
      SELECT ROUND((SELECT SUM(R.REL_RMF_VL_ITEM)
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'ESTSP') /
                    (SELECT SUM(R.REL_RMF_VL_ITEM)
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'CSSP'), 2)
       INTO nRETORNO FROM DUAL;  
   ELSIF (pREL_RFM_COD_ITEM = 'ICSCP') THEN
      SELECT ROUND((SELECT SUM(R.REL_RMF_VL_ITEM)
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'CSSP') /
                    (SELECT SUM(R.REL_RMF_VL_ITEM)
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'CPSP'), 2)
       INTO nRETORNO FROM DUAL;  
    ELSIF (pREL_RFM_COD_ITEM = 'IRTCS') THEN
       SELECT ROUND((SELECT SUM(R.REL_RMF_VL_ITEM)
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RTOT') /
                    (SELECT SUM(R.REL_RMF_VL_ITEM)
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'CSSP'), 2)
       INTO nRETORNO FROM DUAL;   
   ELSIF (pREL_RFM_COD_ITEM = 'IRDSP') THEN      
       SELECT ROUND((SELECT SUM(R.REL_RMF_VL_ITEM)
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RTOT') /
                    (SELECT SUM(R.REL_RMF_VL_ITEM)
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'DSPSP'), 2)
       INTO nRETORNO FROM DUAL;       
   ELSIF (pREL_RFM_COD_ITEM = 'IRSPT') THEN
      SELECT ROUND((SELECT SUM(R.REL_RMF_VL_ITEM)
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RSP') /
                    (SELECT SUM(R.REL_RMF_VL_ITEM)
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'RTOT'), 2)
       INTO nRETORNO FROM DUAL;
   ELSIF (pREL_RFM_COD_ITEM = 'IRACST') THEN
      SELECT ROUND((SELECT SUM(R.REL_RMF_VL_ITEM)
                      FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                     WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                           E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                           E.REL_RFM_COD_ITEM = 'RACS') /
                    (SELECT SUM(R.REL_RMF_VL_ITEM)
                       FROM TB_REL_RFM_RESU_FAT_MTMD R JOIN TB_REL_RFM_MTMD_ESTRUTURA E ON E.REL_RMF_SEQ_ITEM = R.REL_RMF_SEQ_ITEM
                      WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                            BETWEEN 
                            TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY') || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                            TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                            E.REL_RFM_AGRUPAMENTO_ID = pREL_RFM_AGRUPAMENTO_ID AND
                            E.REL_RFM_COD_ITEM = 'RTOT'), 2)
       INTO nRETORNO FROM DUAL;
   ELSE
       SELECT SUM(R.REL_RMF_VL_ITEM)
         INTO nRETORNO
          FROM TB_REL_RFM_RESU_FAT_MTMD R
           WHERE TO_NUMBER(TO_CHAR((R.REL_RFM_ANO_FECHAMENTO || LPad(TO_CHAR(R.REL_RFM_MES_FECHAMENTO), 2, '0'))))
                 BETWEEN 
                 TO_NUMBER(TO_CHAR(pDATA_DE_TOTAL,'YYYY')  || TO_CHAR(pDATA_DE_TOTAL,'MM')) AND
                 TO_NUMBER(TO_CHAR(pDATA_ATE_TOTAL,'YYYY') || TO_CHAR(pDATA_ATE_TOTAL,'MM')) AND
                 R.REL_RMF_SEQ_ITEM = pREL_RMF_SEQ_ITEM;        
   END IF;
END IF;
   RETURN nRETORNO;
EXCEPTION WHEN OTHERS THEN
   RETURN NULL;
END;
 