CREATE OR REPLACE FUNCTION FNC_FORMATAR_CPF_CNPJ(VALOR VARCHAR2)
  RETURN VARCHAR2 IS

  RESULT VARCHAR2(20);
  VALORI VARCHAR2(20);

BEGIN

  VALORI := VALOR;

  IF LENGTH(VALOR) > 11 THEN
    VALORI := LPAD(VALORI, 14, '0');
  
    RESULT := SUBSTR(VALORI, 1, 2) || '.' || SUBSTR(VALORI, 3, 3) || '.' ||
              SUBSTR(VALORI, 6, 3) || '/' || SUBSTR(VALORI, 9, 4) || '-' ||
              SUBSTR(VALORI, 13, 2);
  ELSE
  
    VALORI := LPAD(VALORI, 11, '0');
    RESULT := SUBSTR(VALORI, 1, 3) || '.' || SUBSTR(VALORI, 4, 3) || '.' ||
              SUBSTR(VALORI, 7, 3) || '-' || SUBSTR(VALORI, 10, 2);
  END IF;
  RETURN(RESULT);
END FNC_FORMATAR_CPF_CNPJ;
