create or replace function FNC_AGE_ESM_DIAS_ATENDIDOS
(
 pAGE_ESM_ID in TB_AGE_ESM_ESCALA_MEDICA.AGE_ESM_ID%TYPE,
 pDATA_INI IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE,
 pDATA_FIM IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE
)
return NUMBER is Result NUMBER;
begin

       SELECT COUNT(DISTINCT AGD.AGE_AGD_DT_ATENDIMENTO) INTO Result
       FROM TB_AGE_AGD_AGENDA AGD
       WHERE AGD.AGE_ESM_ID = pAGE_ESM_ID
       AND AGD.AGE_AGD_FL_STATUS IN ('A','F')
       AND AGD.AGE_AGD_DT_ATENDIMENTO BETWEEN pDATA_INI AND pDATA_FIM;

  return(Result);
end FNC_AGE_ESM_DIAS_ATENDIDOS;