CREATE OR REPLACE FUNCTION FNC_MTMD_SOUNDALIKE(PDESCRICAO IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_NOMEFANTASIA%TYPE,
                                               PCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_GRUPO_ID%TYPE) 
RETURN VARCHAR2 IS
V_RETORNO TB_CAD_MTMD_MAT_MED.CAD_MTMD_NOMEFANTASIA%TYPE;
V_SOUNDLIKE TB_CAD_MTMD_SOUND_ALIKE.CAD_MTMD_PALAVRA%TYPE;
V_POSICAO NUMBER;
V_PREFIXO VARCHAR2(30);
V_SUFIXO VARCHAR2(30);
BEGIN
  IF (PCAD_MTMD_GRUPO_ID IN (1)) THEN --Inicialmente so p/ medicamentos
     BEGIN   
        SELECT ALI.CAD_MTMD_PALAVRA
        INTO  V_SOUNDLIKE
        FROM TB_CAD_MTMD_SOUND_ALIKE ALI
        WHERE PDESCRICAO LIKE '%'||ALI.CAD_MTMD_PALAVRA||'%'
        AND   ALI.CAD_MTMD_PREFIXO = 1;
        
        V_POSICAO := INSTR(V_SOUNDLIKE,'%');
        V_PREFIXO := SUBSTR(V_SOUNDLIKE,1,V_POSICAO-1);
        V_SUFIXO := SUBSTR(V_SOUNDLIKE,V_POSICAO+1);
        V_RETORNO := LOWER(PDESCRICAO);
        V_RETORNO := REPLACE(V_RETORNO,LOWER(V_PREFIXO),V_PREFIXO);
        V_RETORNO := REPLACE(V_RETORNO,LOWER(V_SUFIXO),V_SUFIXO);
        
        RETURN V_RETORNO;
     EXCEPTION WHEN NO_DATA_FOUND THEN
        BEGIN   
           SELECT CAD_MTMD_PALAVRA        
             INTO  V_SOUNDLIKE
             FROM (SELECT ALI.CAD_MTMD_PALAVRA        
                    FROM TB_CAD_MTMD_SOUND_ALIKE ALI
                   WHERE PDESCRICAO LIKE '%'||ALI.CAD_MTMD_PALAVRA||'%'
            ORDER BY ALI.CAD_MTMD_PALAVRA DESC)
            WHERE ROWNUM = 1;
           
           V_RETORNO := REPLACE(UPPER(PDESCRICAO),UPPER(V_SOUNDLIKE),LOWER(V_SOUNDLIKE));
           RETURN V_RETORNO;
        EXCEPTION 
           WHEN NO_DATA_FOUND THEN
              RETURN PDESCRICAO;
           --WHEN TOO_MANY_ROWS THEN
              --RETURN PDESCRICAO||' +LINHAS';
        END;
     END;
  ELSE
     RETURN PDESCRICAO;  
  END IF;
END FNC_MTMD_SOUNDALIKE;