create or replace function FNC_INT_ULTIMO_CID
(
  pATD_ATE_ID IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_ID%TYPE,
  pSO_CODIGO VARCHAR2 DEFAULT NULL
)
/****************
*          DATA ALTERAC?O: 7/10/2010
*          Alterado por: Pedro
*
*
*******************/
---retorna o ultimo CID da evoluc?o e se n?o houver registro la, retorno o da ADM.
return VARCHAR2 is Result VARCHAR2(300);
EVOLUCAO VARCHAR2(300) DEFAULT NULL;
CID_EVOLUCAO VARCHAR2(10) DEFAULT NULL;
ADMISSAO VARCHAR2(300) DEFAULT NULL;
CID_ADMISSAO VARCHAR2(10) DEFAULT NULL;
begin

 BEGIN
  SELECT      CID.CAD_CID_DS_CID10, CID.CAD_CID_CD_CID10 INTO EVOLUCAO, CID_EVOLUCAO
  FROM         TB_ATD_ATE_ATENDIMENTO    ATD
  JOIN         TB_ATD_AIC_ATE_INT_COMPL  AIC
  ON           AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
  JOIN         TB_ATD_IEP_INT_EVOL_PACIENTE IEP
  ON           IEP.ATD_ATE_ID          = ATD.ATD_ATE_ID
  JOIN         TB_CAD_CID_CID10          CID
  ON           CID.CAD_CID_CD_CID10    = IEP.CAD_CID_CD_CID10
  WHERE        IEP.ATD_IEP_ID = (SELECT MAX(IEP.ATD_IEP_ID)
                                FROM TB_ATD_IEP_INT_EVOL_PACIENTE IEP
                                WHERE (IEP.ATD_ATE_ID = pATD_ATE_ID));
 EXCEPTION WHEN NO_DATA_FOUND THEN
 EVOLUCAO:= NULL;
 END;

BEGIN
  SELECT      CID.CAD_CID_DS_CID10, CID.CAD_CID_CD_CID10  INTO ADMISSAO, CID_ADMISSAO
  FROM         TB_ATD_ATE_ATENDIMENTO    ATD
  JOIN         TB_ATD_AIC_ATE_INT_COMPL  AIC
  ON           AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
  JOIN         TB_CAD_CID_CID10          CID
  ON           CID.CAD_CID_CD_CID10    = ATD.CAD_CID_CD_CID10
  WHERE
               ATD.ATD_ATE_ID = pATD_ATE_ID;
  EXCEPTION WHEN NO_DATA_FOUND THEN
 ADMISSAO:= NULL;
 END;

  IF EVOLUCAO IS NOT NULL THEN
     Result:= EVOLUCAO;
  ELSE
     Result:= ADMISSAO ;
  END IF;

IF pSO_CODIGO IS NOT NULL AND CID_EVOLUCAO IS NOT NULL THEN
     Result:= CID_EVOLUCAO;
  ELSE IF pSO_CODIGO IS NOT NULL THEN 
     Result:= CID_ADMISSAO ;
  END IF;
  END IF;
  
  return(Result);
end FNC_INT_ULTIMO_CID;
 