create or replace function FNC_INT_QTD_RN_VIVOS
(
  pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE,
  pATD_IML_DT_ENTRADA IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
  pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL
)
--retorna a qtd de nascidos mortos
return NUMBER is Result NUMBER;
begin

   SELECT SUM(IDG.ATD_IDG_QT_NASCIDOS_VIVOS)  INTO RESULT
       FROM      TB_ATD_ATE_ATENDIMENTO   ATD       
       JOIN      TB_ATD_AIC_ATE_INT_COMPL AIC
       ON        AIC.ATD_ATE_ID         = ATD.ATD_ATE_ID
       JOIN      TB_ASS_PAT_PACIEATEND     PAT
       ON        PAT.ATD_ATE_ID          = ATD.ATD_ATE_ID
       JOIN      TB_CAD_PAC_PACIENTE       PAC
       ON        PAC.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(PAT.ATD_ATE_ID)
       JOIN      TB_CAD_PLA_PLANO          PLA
       ON        PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
       JOIN      TB_ATD_IDG_INT_DIAGNOSTICO IDG
       ON        IDG.ATD_ATE_ID          = ATD.ATD_ATE_ID
       JOIN      TB_ATD_IDR_INT_DADOS_RN   IDR
       ON        IDR.ATD_ATE_ID          = ATD.ATD_ATE_ID
       LEFT JOIN  (    SELECT   QLE.CAD_QLE_ID, QLE.CAD_SET_ID , QLE.CAD_QLE_NR_QUARTO, QLE.CAD_QLE_NR_LEITO,
                        IML.ATD_ATE_ID, QLE.TIS_TAC_CD_TIPO_ACOMODACAO, QLE.CAD_QLE_TP_QUARTO_LEITO , IML.ATD_IML_FL_STATUS,
                        IML.ATD_IML_DT_ENTRADA, IML.ATD_IML_HR_ENTRADA
                         FROM      TB_ATD_IML_INT_MOV_LEITO IML
                         LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE
                         ON        QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
                         JOIN      TB_ATD_ATE_ATENDIMENTO ATD2
                         ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                          WHERE       FNC_JUNTAR_DATA_HORA(IML.ATD_IML_DT_ENTRADA,IML.ATD_IML_HR_ENTRADA) = 
                                         (SELECT MAX(FNC_JUNTAR_DATA_HORA(IML3.ATD_IML_DT_ENTRADA,IML3.ATD_IML_HR_ENTRADA)) FROM TB_ATD_IML_INT_MOV_LEITO IML3
                                                       WHERE IML3.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML3.ATD_IML_FL_STATUS = 'A')
      )  IML_QLE
      ON IML_QLE.ATD_ATE_ID = ATD.ATD_ATE_ID

       WHERE
       (IML_QLE.ATD_IML_DT_ENTRADA = ATD.ATD_ATE_DT_ATENDIMENTO)
   AND (IML_QLE.ATD_IML_HR_ENTRADA = ATD.ATD_ATE_HR_ATENDIMENTO)
   AND (TRUNC(IDR.ATD_IDR_DT_NASCIMENTO) = pATD_IML_DT_ENTRADA)
   AND (IML_QLE.CAD_SET_ID         = pCAD_SET_ID)
   AND  ((IML_QLE.ATD_IML_FL_STATUS != 'C') OR (IML_QLE.ATD_IML_FL_STATUS IS NULL))
   AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)

;

  return(Result);
end FNC_INT_QTD_RN_VIVOS;
