create or replace function FNC_INT_QTD_DIA(pCAD_SET_ID           IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
                                           pATD_IML_DT_ENTRADA   IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
                                           pCAD_PLA_ID_PLANO     IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
                                           pCAD_PLA_CD_TIPOPLANO IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
                                           pCAD_UNI_ID_UNIDADE   IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
                                           pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
                                           pSUBGRUPO VARCHAR2 DEFAULT NULL,
                                           pCOM_HOSP_DIA VARCHAR2 DEFAULT NULL,
                                           pCAD_CSE_ID IN TB_CAD_SET_SETOR.CAD_CSE_ID%TYPE DEFAULT NULL
                                           )
---retorna a qtd de int vindos do dia anterior, ou seja q continuam internados

 return NUMBER is
  Result NUMBER;
begin
  SELECT COUNT(DISTINCT IML.ATD_ATE_ID)
    INTO RESULT
    FROM TB_ATD_IML_INT_MOV_LEITO IML
    JOIN TB_ATD_ATE_ATENDIMENTO ATD ON IML.ATD_ATE_ID = ATD.ATD_ATE_ID
    JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PAC_ID_PACIENTE = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
    JOIN TB_CAD_PLA_PLANO PLA ON PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
    JOIN TB_CAD_CNV_CONVENIO CNV ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
    JOIN TB_CAD_QLE_QUARTO_LEITO QLE ON IML.CAD_CAD_QLE_ID = QLE.CAD_QLE_ID
    JOIN TB_CAD_SET_SETOR SETOR ON QLE.CAD_SET_ID = SETOR.CAD_SET_ID
    LEFT JOIN (SELECT IML2.ATD_ATE_ID,
                      IML2.ATD_IML_DT_ENTRADA ATD_DT_ENTRADA,
                      IML2.ATD_IML_HR_ENTRADA ATD_HR_ENTRADA,
                      IML2.ATD_IML_DT_SAIDA   ATD_DT_SAIDA,
                      IML2.ATD_IML_HR_SAIDA   ATD_HR_SAIDA,
                      SETOR2.CAD_SET_CD_SETOR CAD_SET_CD_SETOR,
                      SETOR2.CAD_SET_ID       CAD_SET_ID
                 FROM TB_ATD_IML_INT_MOV_LEITO IML2
                 JOIN TB_CAD_QLE_QUARTO_LEITO QLE2 ON QLE2.CAD_QLE_ID = IML2.CAD_CAD_QLE_ID
                 JOIN TB_ATD_ATE_ATENDIMENTO ATD2 ON ATD2.ATD_ATE_ID = IML2.ATD_ATE_ID
                 JOIN TB_CAD_SET_SETOR SETOR2 ON SETOR2.CAD_SET_ID = QLE2.CAD_SET_ID
                WHERE (IML2.ATD_IML_FL_STATUS = 'A')
                  AND (IML2.ATD_IML_DT_SAIDA = pATD_IML_DT_ENTRADA)
                  AND (ATD2.ATD_ATE_FL_STATUS = 'A')
                  AND (pCAD_UNI_ID_UNIDADE IS NULL OR ATD2.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
               UNION
               SELECT IMS.ATD_ATE_ID,
                      IMS.ATD_IMS_DT_ENTRADA  ATD_DT_ENTRADA,
                      IMS.ATD_IMS_HR_ENTRADA  ATD_HR_ENTRADA,
                      IMS.ATD_IMS_DT_SAIDA    ATD_DT_SAIDA,
                      IMS.ATD_IMS_HR_SAIDA    ATD_HR_SAIDA,
                      SETOR4.CAD_SET_CD_SETOR CAD_SET_CD_SETOR,
                      SETOR4.CAD_SET_ID       CAD_SET_ID
                 FROM TB_ATD_IMS_INT_MOV_SETOR IMS
                 JOIN TB_ATD_ATE_ATENDIMENTO ATD4 ON ATD4.ATD_ATE_ID = IMS.ATD_ATE_ID
                 JOIN TB_CAD_SET_SETOR SETOR4 ON SETOR4.CAD_SET_ID = IMS.CAD_SET_ID_SETOR
                WHERE IMS.ATD_IMS_FL_STATUS = 'A'
                  AND SETOR4.CAD_SET_ID = IMS.CAD_SET_ID_SETOR
                  AND SETOR4.CAD_SET_CD_SETOR IN ('ADM', 'CECI')
                  AND IMS.ATD_IMS_DT_ENTRADA = pATD_IML_DT_ENTRADA
                  AND IMS.ATD_IMS_DT_ENTRADA = ATD4.ATD_ATE_DT_ATENDIMENTO
                  AND IMS.ATD_IMS_HR_ENTRADA = ATD4.ATD_ATE_HR_ATENDIMENTO
                  AND (ATD4.ATD_ATE_FL_STATUS = 'A')
                  AND (pCAD_UNI_ID_UNIDADE IS NULL OR ATD4.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
                ORDER BY 1, 2, 3, 4, 5, 6) ORIGEM
      ON ORIGEM.ATD_ATE_ID = IML.ATD_ATE_ID
    LEFT JOIN (SELECT IML3.ATD_ATE_ID,
                      IML3.ATD_IML_DT_ENTRADA ATD_DT_ENTRADA,
                      IML3.ATD_IML_HR_ENTRADA ATD_HR_ENTRADA,
                      IML3.ATD_IML_DT_SAIDA   ATD_DT_SAIDA,
                      IML3.ATD_IML_HR_SAIDA   ATD_HR_SAIDA,
                      SETOR3.CAD_SET_CD_SETOR,
                      SETOR3.CAD_SET_ID       CAD_SET_ID
                 FROM TB_ATD_IML_INT_MOV_LEITO IML3
                 JOIN TB_CAD_QLE_QUARTO_LEITO QLE3 ON QLE3.CAD_QLE_ID = IML3.CAD_CAD_QLE_ID
                 JOIN TB_ATD_ATE_ATENDIMENTO ATD3 ON ATD3.ATD_ATE_ID = IML3.ATD_ATE_ID
                 JOIN TB_CAD_SET_SETOR SETOR3 ON SETOR3.CAD_SET_ID = QLE3.CAD_SET_ID
                WHERE (IML3.ATD_IML_FL_STATUS = 'A')
                  AND (IML3.ATD_IML_DT_ENTRADA = pATD_IML_DT_ENTRADA)
                  AND (ATD3.ATD_ATE_FL_STATUS = 'A')
                  AND (pCAD_UNI_ID_UNIDADE IS NULL OR ATD3.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
                  AND IML3.ATD_IML_ID = FNC_INT_PRIM_MOV_QUARTO_LEITO(ATD3.ATD_ATE_ID)
               UNION
               SELECT IML4.ATD_ATE_ID,
                      IML4.ATD_IML_DT_ENTRADA ATD_DT_ENTRADA,
                      IML4.ATD_IML_HR_ENTRADA ATD_HR_ENTRADA,
                      IML4.ATD_IML_DT_SAIDA   ATD_DT_SAIDA,
                      IML4.ATD_IML_HR_SAIDA   ATD_HR_SAIDA,
                      SETOR5.CAD_SET_CD_SETOR CAD_SET_CD_SETOR,
                      SETOR5.CAD_SET_ID       CAD_SET_ID
                 FROM TB_ATD_IML_INT_MOV_LEITO IML4
                 JOIN TB_CAD_QLE_QUARTO_LEITO QLE4 ON QLE4.CAD_QLE_ID = IML4.CAD_CAD_QLE_ID
                 JOIN TB_ATD_ATE_ATENDIMENTO ATD4 ON ATD4.ATD_ATE_ID = IML4.ATD_ATE_ID
                 JOIN TB_CAD_SET_SETOR SETOR5 ON SETOR5.CAD_SET_ID = QLE4.CAD_SET_ID
                WHERE (IML4.ATD_IML_FL_STATUS = 'A')
                  AND (IML4.ATD_IML_DT_ENTRADA = pATD_IML_DT_ENTRADA + 1)
                  AND (ATD4.ATD_ATE_FL_STATUS = 'A')
                  AND (pCAD_UNI_ID_UNIDADE IS NULL OR ATD4.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
                  AND IML4.ATD_IML_ID = FNC_INT_PRIM_MOV_QUARTO_LEITO(ATD4.ATD_ATE_ID)
                  AND EXISTS
                (SELECT IMS.ATD_ATE_ID,
                              IMS.ATD_IMS_DT_ENTRADA,
                              IMS.ATD_IMS_HR_ENTRADA,
                              IMS.ATD_IMS_DT_SAIDA,
                              IMS.ATD_IMS_HR_SAIDA,
                              IMS.CAD_SET_ID_SETOR
                         FROM TB_ATD_IMS_INT_MOV_SETOR IMS
                         JOIN TB_CAD_SET_SETOR SETOR4 ON SETOR4.CAD_SET_ID = IMS.CAD_SET_ID_SETOR
                        WHERE IMS.ATD_ATE_ID = IML4.ATD_ATE_ID
                          AND IMS.ATD_IMS_FL_STATUS = 'A'
                          AND IMS.ATD_IMS_DT_SAIDA = IML4.ATD_IML_DT_ENTRADA
                          AND IMS.ATD_IMS_HR_SAIDA = IML4.ATD_IML_HR_ENTRADA
                          AND SETOR4.CAD_SET_ID = IMS.CAD_SET_ID_SETOR
                          AND SETOR4.CAD_SET_CD_SETOR IN ('ADM', 'CECI')
                          AND IMS.ATD_IMS_DT_ENTRADA = pATD_IML_DT_ENTRADA
                          AND IMS.ATD_IMS_DT_ENTRADA = ATD4.ATD_ATE_DT_ATENDIMENTO
                          AND IMS.ATD_IMS_HR_ENTRADA = ATD4.ATD_ATE_HR_ATENDIMENTO)
                ORDER BY 1, 2, 3, 4, 5, 6) DESTINO
      ON DESTINO.ATD_ATE_ID = IML.ATD_ATE_ID
   WHERE (((IML.ATD_IML_DT_ENTRADA = pATD_IML_DT_ENTRADA) AND --SE A INTERNACAO FOI DIRETO NO QUARTO/LEITO
         (IML.ATD_IML_DT_ENTRADA = ATD.ATD_ATE_DT_ATENDIMENTO) AND
         (IML.ATD_IML_HR_ENTRADA = ATD.ATD_ATE_HR_ATENDIMENTO) AND
         (SETOR.CAD_SET_ID = DESTINO.CAD_SET_ID)) OR
         ((ORIGEM.CAD_SET_CD_SETOR in ('ADM', 'CECI') AND ORIGEM.CAD_SET_ID NOT IN (5)) AND -- SE PRIMEIRO FOI PARA ADM OU CC OU ALAD E EM SEGUIDA PARA QL

         (ORIGEM.ATD_DT_ENTRADA = ATD.ATD_ATE_DT_ATENDIMENTO) AND
         (ORIGEM.ATD_HR_ENTRADA = ATD.ATD_ATE_HR_ATENDIMENTO) AND
         (ORIGEM.ATD_DT_SAIDA = IML.ATD_IML_DT_ENTRADA) AND
         (ORIGEM.ATD_HR_SAIDA = IML.ATD_IML_HR_ENTRADA) AND
         (ORIGEM.CAD_SET_ID != DESTINO.CAD_SET_ID) AND
         (SETOR.CAD_SET_ID = DESTINO.CAD_SET_ID) AND
         (IML.ATD_IML_DT_ENTRADA BETWEEN pATD_IML_DT_ENTRADA AND pATD_IML_DT_ENTRADA + 1)) OR
         ((ORIGEM.CAD_SET_CD_SETOR in ('ADM', 'CECI') AND ORIGEM.CAD_SET_ID NOT IN (5)) AND --SE EXISTIRAM VARIAS MOV SETOR ANTES DA PRIMEIRA MOV QL
         (ORIGEM.ATD_DT_ENTRADA = ATD.ATD_ATE_DT_ATENDIMENTO) AND
         (ORIGEM.ATD_HR_ENTRADA = ATD.ATD_ATE_HR_ATENDIMENTO) AND
         (DESTINO.ATD_DT_ENTRADA = IML.ATD_IML_DT_ENTRADA) AND
         (DESTINO.ATD_HR_ENTRADA = IML.ATD_IML_HR_ENTRADA) AND
         ((DESTINO.ATD_DT_SAIDA = IML.ATD_IML_DT_SAIDA) AND
         (DESTINO.ATD_HR_SAIDA = IML.ATD_IML_HR_SAIDA) OR
         (DESTINO.ATD_DT_SAIDA IS NULL) AND
         (DESTINO.ATD_HR_SAIDA IS NULL)) AND
         (DESTINO.CAD_SET_ID = SETOR.CAD_SET_ID) AND
         (ORIGEM.CAD_SET_ID != DESTINO.CAD_SET_ID) AND
         (ORIGEM.CAD_SET_ID != SETOR.CAD_SET_ID) AND
         (IML.ATD_IML_DT_ENTRADA BETWEEN pATD_IML_DT_ENTRADA AND pATD_IML_DT_ENTRADA + 1)))
     AND (pCAD_SET_ID is null or QLE.CAD_SET_ID = pCAD_SET_ID)
     AND (IML.ATD_IML_FL_STATUS = 'A')
     AND (ATD.ATD_ATE_FL_STATUS = 'A')
     AND (SETOR.CAD_SET_ID NOT IN (5))
     AND (SETOR.CAD_SET_ID = DESTINO.CAD_SET_ID)
     AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
AND ((pCOM_HOSP_DIA IS NULL) OR
          (pCOM_HOSP_DIA = '0' AND (PCAD_CSE_ID = '8') AND SETOR.CAD_CSE_ID = 8) OR
(pCOM_HOSP_DIA = '0' AND (PCAD_CSE_ID NOT IN ('8','9') OR PCAD_CSE_ID IS NULL) AND SETOR.CAD_CSE_ID NOT IN ('8','9')) OR
          (pCOM_HOSP_DIA = '1' AND SETOR.CAD_CSE_ID = 8) )

     AND (atd.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
     AND (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
     AND ((pSUBGRUPO = 'ACS' AND CNV.CAD_CNV_ID_CONVENIO = 281) OR
         (pSUBGRUPO = 'AMIL' AND cnv.cad_cgc_id = 1 and cnv.cad_tpe_cd_codigo = 'SP' and cnv.cad_cnv_cd_hac_prestador != 'S077') OR
         (pSUBGRUPO = 'FUNCIONARIO' AND cnv.cad_cnv_cd_hac_prestador in ('GG05', 'HAC', 'NP01', 'NR14', 'S077') ) OR
         (pSUBGRUPO = 'MERCADO' AND CNV.cad_cgc_id = 2 AND cnv.cad_cnv_id_convenio!=282 ) OR
         (pSUBGRUPO = 'PARTICULAR' AND CNV.cad_cgc_id = 2 AND CNV.CAD_CNV_ID_CONVENIO = 282))

           ;
  return(Result);
end FNC_INT_QTD_DIA;
