CREATE OR REPLACE FUNCTION "FNC_AGE_ESM_TOTAL_FALTAS"
(
 pAGE_ESM_ID in TB_AGE_ESM_ESCALA_MEDICA.AGE_ESM_ID%TYPE,
 pDATA_INI IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE,
 pDATA_FIM IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE
)

return NUMBER is Result NUMBER;
HoraPercentual NUMBER;

begin

      -- no SELECT logo abaixo (que e totalmente novo), considera se ha falta parcial para poder 
      -- gerar uma fracao (de 0 a 1) de hora; caso a falta seja integral, a fracao sera igual a 1
      SELECT AVG(DISTINCT 
             (NVL((ESF.AGE_ESF_HR_FIM_FALTA - ESF.AGE_ESF_HR_INI_FALTA), (ESM.AGE_ESM_HR_FIM_ESCALA - ESM.AGE_ESM_HR_INI_ESCALA)) / 
                 (ESM.AGE_ESM_HR_FIM_ESCALA - ESM.AGE_ESM_HR_INI_ESCALA))) INTO HoraPercentual
        FROM TB_AGE_AGG_AGENDA_GERADA AGG
       INNER JOIN TB_AGE_ESF_ESCALA_FALTAS ESF
          ON ESF.AGE_ESM_ID = pAGE_ESM_ID
       INNER JOIN TB_AGE_ESM_ESCALA_MEDICA ESM
          ON ESM.AGE_ESM_ID = pAGE_ESM_ID
         AND AGG.AGE_AGG_DT_AGENDA BETWEEN ESF.AGE_ESF_DT_INI_FALTA AND  ESF.AGE_ESF_DT_FIM_FALTA
       WHERE AGG.AGE_ESM_ID = pAGE_ESM_ID
         AND AGG.AGE_AGG_DT_AGENDA BETWEEN pDATA_INI AND pDATA_FIM
         AND (AGG.AGE_AGG_DT_AGENDA <= ESM.AGE_ESM_DT_FIM_ESCALA 
          OR ESM.AGE_ESM_DT_FIM_ESCALA IS NULL);
          
          
       SELECT (COUNT(DISTINCT AGG.AGE_AGG_DT_AGENDA) * TRUNC(HoraPercentual, 4)) INTO Result
          
--       SELECT COUNT(DISTINCT AGG.AGE_AGG_DT_AGENDA) INTO Result
       FROM TB_AGE_AGG_AGENDA_GERADA AGG
       INNER JOIN TB_AGE_ESF_ESCALA_FALTAS ESF
        ON ESF.AGE_ESM_ID = pAGE_ESM_ID
       INNER JOIN TB_AGE_ESM_ESCALA_MEDICA ESM
       ON ESM.AGE_ESM_ID = pAGE_ESM_ID
   --     AND ESF.AGE_ESF_DT_INI_FALTA BETWEEN pDATA_INI AND pDATA_FIM
   --     AND ESF.AGE_ESF_DT_FIM_FALTA BETWEEN pDATA_INI AND pDATA_FIM
        AND AGG.AGE_AGG_DT_AGENDA BETWEEN ESF.AGE_ESF_DT_INI_FALTA AND  ESF.AGE_ESF_DT_FIM_FALTA
       WHERE AGG.AGE_ESM_ID = pAGE_ESM_ID
       AND AGG.AGE_AGG_DT_AGENDA BETWEEN pDATA_INI AND pDATA_FIM 
        AND (AGG.AGE_AGG_DT_AGENDA <= ESM.AGE_ESM_DT_FIM_ESCALA 
            OR ESM.AGE_ESM_DT_FIM_ESCALA IS NULL);        
              return(Result);
end FNC_AGE_ESM_TOTAL_FALTAS;

 
/
