create or replace function sgs.FNC_AGE_ESM_CAPAC_NORMAL_SP
(
 pAGE_ESM_ID in TB_AGE_ESM_ESCALA_MEDICA.AGE_ESM_ID%TYPE,
 pDATA_INI IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE,
 pDATA_FIM IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_AGENDA%TYPE
)
return NUMBER is Result NUMBER;
begin

      SELECT COUNT(AGG.AGE_AGG_DT_AGENDA) INTO Result
       FROM TB_AGE_AGG_AGENDA_GERADA AGG
       join TB_AGE_ESM_ESCALA_MEDICA ESM on AGG.AGE_ESM_ID=ESM.AGE_ESM_ID
       WHERE AGG.AGE_ESM_ID = pAGE_ESM_ID
       AND AGG.AGE_AGG_DT_AGENDA BETWEEN pDATA_INI AND pDATA_FIM
       AND (AGG.AGE_AGG_DT_AGENDA <= ESM.AGE_ESM_DT_FIM_ESCALA             OR ESM.AGE_ESM_DT_FIM_ESCALA IS NULL)

       AND (AGG.AGE_AGG_TP_HORARIO in (1,5,6) )

;
  return(Result);
end FNC_AGE_ESM_CAPAC_NORMAL_SP;
