CREATE OR REPLACE FUNCTION "FNC_INT_QTD_UTI"
(
 pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pFAIXA_ETARIA_INI           varchar2 default null,
pFAIXA_ETARIA_FIM          varchar2 default null,
pPERMANENCIA_INI          varchar2 default null,
pPERMANENCIA_FIM         varchar2 default null,
pEVOLUCAO                varchar2 default null,
pCAD_UNI_ID_UNIDADE           IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
pCAD_SET_ID              IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
pCAD_SET_NR_ANDAR        IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE     IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pCAD_QLE_TP_QUARTO_LEITO IN TB_CAD_QLE_QUARTO_LEITO.CAD_QLE_TP_QUARTO_LEITO%TYPE DEFAULT NULL,
pTIS_TIN_CD_INTER        IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
pTIS_TRI_CD_TP_REGINT    IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PRD_ID              IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
pCAD_CID_CD_CID10        IN TB_CAD_CID_CID10.CAD_CID_CD_CID10%TYPE DEFAULT NULL,
pTIS_TAC_CD_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%TYPE DEFAULT NULL,
pTIS_CBO_CD_CBOS         IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
pCAD_PRO_ID_PROF_EXEC    IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
pCAD_PES_TP_SEXO         IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL
--pPASSOU_PELA_UTI         varchar2 default null
)
---retorna a qtd de int ----- por varios parametros
return NUMBER is Result NUMBER;
begin
   SELECT      Count(DISTINCT ATD.ATD_ATE_ID) INTO RESULT
        FROM       TB_ATD_ATE_ATENDIMENTO    ATD
        JOIN       TB_CAD_PAC_PACIENTE       PAC    ON PAC.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(ATD.ATD_ATE_ID)
        JOIN       TB_CAD_PES_PESSOA         PES    ON PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA       
        JOIN       TB_CAD_PLA_PLANO          PLA    ON PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
        JOIN       TB_ATD_AIC_ATE_INT_COMPL  AIC    ON AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID      
        JOIN       TB_ATD_IML_INT_MOV_LEITO  IML    ON IML.ATD_ATE_ID          = ATD.ATD_ATE_ID
        JOIN       TB_CAD_QLE_QUARTO_LEITO   QLE    ON QLE.CAD_QLE_ID          = IML.CAD_CAD_QLE_ID
        JOIN       TB_CAD_SET_SETOR          SETOR  ON SETOR.CAD_SET_ID        = QLE.CAD_SET_ID
        
        LEFT JOIN (SELECT IML2.ATD_ATE_ID, IML2.ATD_IML_DT_SAIDA, IML2.ATD_IML_HR_SAIDA, IML2.ATD_IML_DT_ENTRADA, IML2.ATD_IML_HR_ENTRADA, QLE2.CAD_SET_ID
                   
                   FROM TB_ATD_IML_INT_MOV_LEITO IML2
                   JOIN TB_CAD_QLE_QUARTO_LEITO  QLE2 ON QLE2.CAD_QLE_ID   = IML2.CAD_CAD_QLE_ID
                   JOIN TB_CAD_SET_SETOR       SETOR2 ON SETOR2.CAD_SET_ID = QLE2.CAD_SET_ID
                   
                  WHERE (IML2.ATD_IML_FL_STATUS               = 'A') 
                    AND (SETOR2.CAD_UNI_ID_UNIDADE           = pCAD_UNI_ID_UNIDADE)
                    AND (SETOR2.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
                    
                  ) ORIGEM
        ON ORIGEM.ATD_ATE_ID       = IML.ATD_ATE_ID
       AND ORIGEM.ATD_IML_DT_SAIDA = IML.ATD_IML_DT_ENTRADA
       AND ORIGEM.ATD_IML_HR_SAIDA = IML.ATD_IML_HR_ENTRADA
       
        LEFT JOIN     TB_ATD_IEP_INT_EVOL_PACIENTE IEP     ON            IEP.ATD_ATE_ID            = ATD.ATD_ATE_ID
        
         WHERE
             (ATD.ATD_ATE_FL_STATUS = 'A')
         AND (ORIGEM.CAD_SET_ID IS NULL OR ORIGEM.CAD_SET_ID != QLE.CAD_SET_ID) --DESCONSIDERAR TRANSFERENCIA DE MESMO SETOR SOMENTE LEITO
         AND (pCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
         AND (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
         AND (pCAD_SET_ID IS NULL OR QLE.CAD_SET_ID = pCAD_SET_ID)
         AND (pATD_ATE_TP_PACIENTE IS NULL OR ATD.ATD_ATE_TP_PACIENTE = pATD_ATE_TP_PACIENTE)
         AND (pCAD_SET_NR_ANDAR IS NULL OR SETOR.CAD_SET_NR_ANDAR = pCAD_SET_NR_ANDAR)
         AND (pATD_AIC_TP_SITUACAO_PAC IS NULL OR AIC.ATD_AIC_TP_SITUACAO_PAC = pATD_AIC_TP_SITUACAO_PAC)
         AND (pATD_ATE_HR_ATENDIMENTO_INI IS NULL OR IML.ATD_IML_HR_ENTRADA >= pATD_ATE_HR_ATENDIMENTO_INI )
         AND (pATD_ATE_HR_ATENDIMENTO_FIM IS NULL OR IML.ATD_IML_HR_SAIDA <= pATD_ATE_HR_ATENDIMENTO_FIM)
         AND (pTIS_CBO_CD_CBOS IS NULL OR ATD.TIS_CBO_CD_CBOS = pTIS_CBO_CD_CBOS)
         AND (pCAD_PRO_ID_PROF_EXEC IS NULL OR ATD.CAD_PRO_ID_PROF_EXEC = pCAD_PRO_ID_PROF_EXEC)
         AND (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
         AND (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
         AND (pCAD_PRD_ID IS NULL OR AIC.CAD_PRD_ID = pCAD_PRD_ID)
         AND (pCAD_CID_CD_CID10 IS NULL OR IEP.CAD_CID_CD_CID10 = pCAD_CID_CD_CID10)
         AND (pCAD_PES_TP_SEXO IS NULL OR PES.CAD_PES_TP_SEXO = pCAD_PES_TP_SEXO)
         AND (pTIS_TAC_CD_TIPO_ACOMODACAO IS NULL OR QLE.TIS_TAC_CD_TIPO_ACOMODACAO = pTIS_TAC_CD_TIPO_ACOMODACAO)
         AND (pCAD_QLE_TP_QUARTO_LEITO IS NULL OR QLE.CAD_QLE_TP_QUARTO_LEITO = pCAD_QLE_TP_QUARTO_LEITO)
         AND (pTIS_TIN_CD_INTER IS NULL OR AIC.TIS_TIN_CD_INTERNACAO = pTIS_TIN_CD_INTER)
         AND (pTIS_TRI_CD_TP_REGINT IS NULL OR AIC.TIS_TRI_CD_REGINTENNACAO = pTIS_TRI_CD_TP_REGINT)
        -- and atd.atd_ate_id = 24884453 
        ---- AND (pPASSOU_PELA_UTI IS NULL OR fnc_fat_atd_passou_pela_uti(ATD.ATD_ATE_ID,SETOR.CAD_SET_ID) = 1)
         AND (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = 'GB'
           OR pCAD_PLA_CD_TIPOPLANO_PL IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PL'
           OR pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PA'
           OR pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'SP'
           OR pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'FU'
           OR pCAD_PLA_CD_TIPOPLANO_NP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'NP')
         AND (pATD_ATE_FL_CARATER_SOLIC_U IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = 'U'
         OR pATD_ATE_FL_CARATER_SOLIC_E IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = 'E')
       --  AND IML_QLE.CAD_SQL_CD_SIT_QUARTO_LEITO IN (1,2)
         AND (IML.ATD_IML_DT_ENTRADA BETWEEN pATD_ATE_DT_ATENDIMENTO_INI AND pATD_ATE_DT_ATENDIMENTO_FIM)
         AND (pEVOLUCAO IS NULL OR Floor(SYSDATE - IEP.ATD_IEP_DT_EVOLUCAO) >= pEVOLUCAO)
         AND (pFAIXA_ETARIA_INI IS NULL OR (Floor(floor(months_between(SYSDATE, pes.cad_pes_dt_nascimento)) / 12) >= pFAIXA_ETARIA_INI))
         and (pFAIXA_ETARIA_FIM IS NULL OR (Floor(floor(months_between(SYSDATE, pes.cad_pes_dt_nascimento)) / 12) <= pFAIXA_ETARIA_FIM))
         AND  (pPERMANENCIA_INI IS NULL OR
                 ((CASE WHEN IML.ATD_IML_DT_SAIDA IS NOT NULL THEN nvl(Round(IML.ATD_IML_DT_SAIDA - IML.ATD_IML_DT_ENTRADA),0)
                        WHEN IML.ATD_IML_DT_SAIDA IS NULL     THEN nvl(Round(sysdate-IML.ATD_IML_DT_ENTRADA),0)
               END) >=  pPERMANENCIA_INI)
               )
         AND  (pPERMANENCIA_FIM IS NULL OR
               ((CASE WHEN IML.ATD_IML_DT_SAIDA IS NOT NULL THEN nvl(Round(IML.ATD_IML_DT_SAIDA - IML.ATD_IML_DT_ENTRADA),0)
                      WHEN IML.ATD_IML_DT_SAIDA IS NULL     THEN nvl(Round(sysdate-IML.ATD_IML_DT_ENTRADA),0)
                      ELSE  0
              END) <= pPERMANENCIA_FIM)
              )
;
  return(Result);
end FNC_INT_QTD_UTI;
 
