CREATE OR REPLACE FUNCTION FNC_RETORNA_ECO_INI
(
   pECO IN TB_ATS_UME_UNI_MEDIDA_ECOCAR.ATS_UME_CD_ECOCARDIO%TYPE,
   pTPUNIDADE_MEDIDA IN TB_ATS_UME_UNI_MEDIDA_ECOCAR.ATS_UME_TP_UNID_MEDIDA%TYPE,
   pUNIDADE_MEDIDA IN TB_ATS_UME_UNI_MEDIDA_ECOCAR.ATS_UME_CD_UNID_MEDIDA%TYPE
)
return NUMBER is Result NUMBER;
BEGIN
SELECT UME.ATS_UME_QT_UNID_MEDIDA_ECO_INI INTO Result
 FROM TB_ATS_UME_UNI_MEDIDA_ECOCAR UME
 WHERE
     UME.ATS_UME_TP_UNID_MEDIDA = pTPUNIDADE_MEDIDA
 AND UME.ATS_UME_CD_ECOCARDIO = pECO
 AND UME.ATS_UME_CD_UNID_MEDIDA = pUNIDADE_MEDIDA;

return(Result);

END FNC_RETORNA_ECO_INI;
