CREATE OR REPLACE FUNCTION "FNC_INT_QTD_PARTO"
(
 -- pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE,
 -- pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE,
  pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE,
  pDATA IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
  pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
  pATD_IDG_TP_PARTO IN TB_ATD_IDG_INT_DIAGNOSTICO.ATD_IDG_TP_PARTO%TYPE
)
---retorna a qtd de int vindos do dia anterior, ou seja q continuam internados
return NUMBER is Result NUMBER;
begin
   SELECT  COUNT( IDG.ATD_IDG_TP_PARTO)  INTO RESULT
          --  IML.ATD_ATE_ID, IML.ATD_IML_DT_SAIDA, IML.ATD_IML_HR_SAIDA,IML.ATD_IML_DT_ENTRADA,IML.ATD_IML_HR_ENTRADA,
       --     SETOR.CAD_SET_DS_SETOR ,ATD.ATD_ATE_DT_ATENDIMENTO


          FROM          TB_ATD_ATE_ATENDIMENTO    ATD
          JOIN          TB_ASS_PAT_PACIEATEND     PAT
          ON            PAT.ATD_ATE_ID          = ATD.ATD_ATE_ID
          JOIN          TB_CAD_PAC_PACIENTE       PAC
          ON            PAC.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(PAT.ATD_ATE_ID)
          JOIN          TB_CAD_PLA_PLANO          PLA
          ON            PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO

          JOIN          TB_ATD_AIC_ATE_INT_COMPL  AIC
          ON            AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
          LEFT JOIN    TB_ATD_IDR_INT_DADOS_RN      IDR
          ON           IDR.ATD_ATE_ID             = ATD.ATD_ATE_ID
          AND          IDR.ATD_IDR_DT_NASCIMENTO  = pDATA
          LEFT JOIN    TB_ATD_IDG_INT_DIAGNOSTICO   IDG
          ON           IDG.ATD_ATE_ID             = ATD.ATD_ATE_ID
          LEFT JOIN  (    SELECT   QLE.CAD_QLE_ID, QLE.CAD_SET_ID , QLE.CAD_QLE_NR_QUARTO, QLE.CAD_QLE_NR_LEITO,
                          IML.ATD_ATE_ID, QLE.TIS_TAC_CD_TIPO_ACOMODACAO, QLE.CAD_QLE_TP_QUARTO_LEITO , IML.ATD_IML_FL_STATUS,
                          IML.ATD_IML_DT_ENTRADA, IML.ATD_IML_HR_ENTRADA
                           FROM      TB_ATD_IML_INT_MOV_LEITO IML
                           LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE
                           ON        QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
                           JOIN      TB_ATD_ATE_ATENDIMENTO ATD2
                           ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                           WHERE       FNC_JUNTAR_DATA_HORA(IML.ATD_IML_DT_ENTRADA,IML.ATD_IML_HR_ENTRADA) = 
                                         (SELECT MAX(FNC_JUNTAR_DATA_HORA(IML3.ATD_IML_DT_ENTRADA,IML3.ATD_IML_HR_ENTRADA)) FROM TB_ATD_IML_INT_MOV_LEITO IML3
                                                       WHERE IML3.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML3.ATD_IML_FL_STATUS = 'A')
          )  IML_QLE
          ON            IML_QLE.ATD_ATE_ID = ATD.ATD_ATE_ID
          JOIN          TB_CAD_SET_SETOR         SETOR
          ON            SETOR.CAD_SET_ID       = IML_QLE.CAD_SET_ID
          JOIN          TB_CAD_UNI_UNIDADE       UNI
          ON            UNI.CAD_UNI_ID_UNIDADE = SETOR.CAD_UNI_ID_UNIDADE
          JOIN          TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
          ON            LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
       WHERE
       (IDG.ATD_IDG_TP_PARTO = pATD_IDG_TP_PARTO) -- '1' NORMAL  2 CES   3 FOR
  -- AND (UNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
  -- AND (LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
   AND (IML_QLE.CAD_SET_ID         = pCAD_SET_ID)
   AND  ((IML_QLE.ATD_IML_FL_STATUS != 'C') OR (IML_QLE.ATD_IML_FL_STATUS IS NULL))
   AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
;

  return(Result);
end FNC_INT_QTD_PARTO;
 
