//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HacFramework.Communication.Remoting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HacFramework.Communication.Remoting.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurado para carregar os seguintes assembly:.
        /// </summary>
        internal static string AssemblyMessage {
            get {
                return ResourceManager.GetString("AssemblyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...{0}.
        /// </summary>
        internal static string AssemblyToLoad {
            get {
                return ResourceManager.GetString("AssemblyToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal {0} criado com sucesso.
        /// </summary>
        internal static string ChannelCreated {
            get {
                return ResourceManager.GetString("ChannelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criando o canal {0} na porta {1}.
        /// </summary>
        internal static string CreatingChannel {
            get {
                return ResourceManager.GetString("CreatingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... {0}.
        /// </summary>
        internal static string LoadClassOK {
            get {
                return ResourceManager.GetString("LoadClassOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo {0} carregado com sucesso.
        /// </summary>
        internal static string LoadComplete {
            get {
                return ResourceManager.GetString("LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...Carregando a classe {0}.
        /// </summary>
        internal static string LoadingClass {
            get {
                return ResourceManager.GetString("LoadingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando as Classes.
        /// </summary>
        internal static string LoadingClasses {
            get {
                return ResourceManager.GetString("LoadingClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando o arquivo: {0}.
        /// </summary>
        internal static string LoadingFile {
            get {
                return ResourceManager.GetString("LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurado para carregar os seguintes namespaces:.
        /// </summary>
        internal static string NamespaceMessage {
            get {
                return ResourceManager.GetString("NamespaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...{0}.
        /// </summary>
        internal static string NamespaceToLoad {
            get {
                return ResourceManager.GetString("NamespaceToLoad", resourceCulture);
            }
        }
    }
}
