CREATE OR REPLACE TRIGGER "TR1_FCXA"
  AFTER INSERT OR DELETE OR UPDATE OF NUMBANCO, NUMAGENCIA, NROCONTA, ATIVA ON FCXA
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
DECLARE
  V_ASS_BCT_ID                 SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_ID%TYPE;
  V_CAD_BAN_ID                 SGS.TB_ASS_BCT_BANCO_CONTA.CAD_BAN_ID%TYPE;
  V_ASS_BCT_CD_AGENCIA         SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_CD_AGENCIA%TYPE;
  V_ASS_BCT_NR_CONTA           SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_NR_CONTA%TYPE;
  V_ASS_BCT_CD_CTA_CAIXA_RM    SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_CD_CTA_CAIXA_RM%TYPE;
  V_ASS_BCT_FL_ATIVO           SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_FL_ATIVO%TYPE;
  V_ASS_BCT_DV_AGENCIA         SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_DV_AGENCIA%TYPE;
  V_ASS_BCT_DV_CONTA           SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_DV_CONTA%TYPE;
  V_ASS_BCT_DT_CRIACAO         SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_DT_CRIACAO%TYPE;
  V_SEG_USU_ID_USUARIO_CRIACAO SGS.TB_ASS_BCT_BANCO_CONTA.SEG_USU_ID_USUARIO_CRIACAO%TYPE;
  V_ASS_BCT_DT_ULTIMA_ATUALIZA SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_DT_ULTIMA_ATUALIZACAO%TYPE;
  V_SEG_USU_ID_USUARIO_ATUALIZ SGS.TB_ASS_BCT_BANCO_CONTA.SEG_USU_ID_USUARIO_ATUALIZ%TYPE;
  V_ASS_BCT_CD_BANCO_LEG       SGS.TB_ASS_BCT_BANCO_CONTA.ASS_BCT_CD_BANCO_LEG%TYPE;
BEGIN
  IF (INSERTING) THEN
    IF :NEW.NUMBANCO IS NOT NULL AND :NEW.NUMAGENCIA IS NOT NULL AND
       :NEW.NROCONTA IS NOT NULL THEN
      BEGIN
        SELECT DISTINCT BAN.CAD_BAN_ID
          INTO V_CAD_BAN_ID
          FROM SGS.TB_CAD_BAN_BANCO BAN
         WHERE BAN.CAD_BAN_NR_BANCO_RM = :NEW.NUMBANCO;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          NULL;
      END;
    
      SELECT SGS.SEQ_ASS_BCT_01.NEXTVAL INTO V_ASS_BCT_ID FROM DUAL;
      V_ASS_BCT_CD_AGENCIA      := :NEW.NUMAGENCIA;
      V_ASS_BCT_NR_CONTA        := :NEW.NROCONTA;
      V_ASS_BCT_CD_CTA_CAIXA_RM := :NEW.CODCXA;
      V_ASS_BCT_FL_ATIVO        := 'S';
      BEGIN
        SELECT G.DIGAG
          INTO V_ASS_BCT_DV_AGENCIA
          FROM FCONTA F, GAGENCIA G
         WHERE F.NUMBANCO = G.NUMBANCO
           AND F.NUMAGENCIA = G.NUMAGENCIA
           AND G.NUMBANCO = :NEW.NUMBANCO
           AND G.NUMAGENCIA = :NEW.NUMAGENCIA;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          NULL;
      END;
      BEGIN
        SELECT F.DIGCONTA
          INTO V_ASS_BCT_DV_CONTA
          FROM FCONTA F
         WHERE F.NUMBANCO = :NEW.NUMBANCO
           AND F.NUMAGENCIA = :NEW.NUMAGENCIA
           AND F.NROCONTA = :NEW.NROCONTA;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          NULL;
      END;
      V_ASS_BCT_DT_CRIACAO         := SYSDATE;
      V_SEG_USU_ID_USUARIO_CRIACAO := 1;
      V_ASS_BCT_DT_ULTIMA_ATUALIZA := SYSDATE;
      V_SEG_USU_ID_USUARIO_ATUALIZ := 1;
      BEGIN
        SELECT DISTINCT BCT.ASS_BCT_CD_BANCO_LEG
          INTO V_ASS_BCT_CD_BANCO_LEG
          FROM SGS.TB_CAD_BAN_BANCO BAN, SGS.TB_ASS_BCT_BANCO_CONTA BCT
         WHERE BCT.CAD_BAN_ID = BAN.CAD_BAN_ID
           AND BCT.CAD_BAN_ID = V_CAD_BAN_ID
           AND BCT.ASS_BCT_CD_BANCO_LEG IS NOT NULL;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          NULL;
      END;
      INSERT INTO SGS.TB_ASS_BCT_BANCO_CONTA
        (ASS_BCT_ID,
         CAD_BAN_ID,
         ASS_BCT_CD_AGENCIA,
         ASS_BCT_NR_CONTA,
         ASS_BCT_CD_CTA_CAIXA_RM,
         ASS_BCT_FL_ATIVO,
         ASS_BCT_DV_AGENCIA,
         ASS_BCT_DV_CONTA,
         ASS_BCT_DT_CRIACAO,
         SEG_USU_ID_USUARIO_CRIACAO,
         ASS_BCT_DT_ULTIMA_ATUALIZACAO,
         SEG_USU_ID_USUARIO_ATUALIZ,
         ASS_BCT_CD_BANCO_LEG)
      VALUES
        (V_ASS_BCT_ID,
         V_CAD_BAN_ID,
         V_ASS_BCT_CD_AGENCIA,
         V_ASS_BCT_NR_CONTA,
         V_ASS_BCT_CD_CTA_CAIXA_RM,
         V_ASS_BCT_FL_ATIVO,
         V_ASS_BCT_DV_AGENCIA,
         V_ASS_BCT_DV_CONTA,
         V_ASS_BCT_DT_CRIACAO,
         V_SEG_USU_ID_USUARIO_CRIACAO,
         V_ASS_BCT_DT_ULTIMA_ATUALIZA,
         V_SEG_USU_ID_USUARIO_ATUALIZ,
         V_ASS_BCT_CD_BANCO_LEG);
    END IF;
  END IF;
  IF (UPDATING) THEN
    IF :NEW.NUMBANCO IS NOT NULL AND :NEW.NUMAGENCIA IS NOT NULL AND
       :NEW.NROCONTA IS NOT NULL THEN       
      IF (:NEW.NUMBANCO != :OLD.NUMBANCO OR :OLD.NUMBANCO IS NULL) OR
         (:NEW.NUMAGENCIA != :OLD.NUMAGENCIA OR :OLD.NUMAGENCIA IS NULL) OR
         (:NEW.NROCONTA != :OLD.NROCONTA OR :OLD.NROCONTA IS NULL) THEN
        IF (:NEW.NUMBANCO != :OLD.NUMBANCO OR :OLD.NUMBANCO IS NULL) THEN
          SELECT DISTINCT BAN.CAD_BAN_ID
            INTO V_CAD_BAN_ID
            FROM SGS.TB_CAD_BAN_BANCO BAN
           WHERE BAN.CAD_BAN_NR_BANCO_RM = :NEW.NUMBANCO;
        END IF;
        IF (:NEW.NUMAGENCIA != :OLD.NUMAGENCIA OR :OLD.NUMAGENCIA IS NULL) THEN
          V_ASS_BCT_CD_AGENCIA := :NEW.NUMAGENCIA;
        ELSE
          V_ASS_BCT_CD_AGENCIA := :OLD.NUMAGENCIA;
        END IF;
        IF (:NEW.NROCONTA != :OLD.NROCONTA OR :OLD.NROCONTA IS NULL) THEN
          V_ASS_BCT_NR_CONTA := :NEW.NROCONTA;
        ELSE
          V_ASS_BCT_NR_CONTA := :OLD.NROCONTA;
        END IF;
        IF :OLD.NUMBANCO IS NULL OR :OLD.NUMAGENCIA IS NULL OR
           :OLD.NROCONTA IS NULL THEN
          V_ASS_BCT_FL_ATIVO := 'S';
        ELSE
          IF :NEW.ATIVA = 0 THEN
            V_ASS_BCT_FL_ATIVO := 'N';
          ELSE
            V_ASS_BCT_FL_ATIVO := 'S';
          END IF;
        END IF;
        UPDATE SGS.TB_ASS_BCT_BANCO_CONTA BCT
           SET BCT.CAD_BAN_ID                    = V_CAD_BAN_ID,
               BCT.ASS_BCT_CD_AGENCIA            = V_ASS_BCT_CD_AGENCIA,
               BCT.ASS_BCT_NR_CONTA              = V_ASS_BCT_NR_CONTA,
               BCT.ASS_BCT_FL_ATIVO              = V_ASS_BCT_FL_ATIVO,
               BCT.ASS_BCT_DT_ULTIMA_ATUALIZACAO = SYSDATE,
               BCT.SEG_USU_ID_USUARIO_ATUALIZ    = 1
         WHERE BCT.ASS_BCT_CD_CTA_CAIXA_RM = :OLD.CODCXA;
      END IF;
    ELSE
      UPDATE SGS.TB_ASS_BCT_BANCO_CONTA BCT
         SET BCT.ASS_BCT_FL_ATIVO              = 'N',
             BCT.ASS_BCT_DT_ULTIMA_ATUALIZACAO = SYSDATE,
             BCT.SEG_USU_ID_USUARIO_ATUALIZ    = 1
       WHERE BCT.ASS_BCT_CD_CTA_CAIXA_RM = :OLD.CODCXA;
    END IF;
  END IF;
  IF (DELETING) THEN
    UPDATE SGS.TB_ASS_BCT_BANCO_CONTA BCT
       SET BCT.ASS_BCT_FL_ATIVO              = 'N',
           BCT.ASS_BCT_DT_ULTIMA_ATUALIZACAO = SYSDATE,
           BCT.SEG_USU_ID_USUARIO_ATUALIZ    = 1
     WHERE BCT.ASS_BCT_CD_CTA_CAIXA_RM = :OLD.CODCXA;
  END IF;
END TR1_FCXA;
/