CREATE OR REPLACE TRIGGER TR_PRODUTO_DEF_ESTOQUE_SGS
AFTER INSERT OR UPDATE
OF CODFAB
  ,CODUNDCONTROLE
  ,CODTB3FAT
  ,CODTB4FAT
  ,CODUNDCOMPRA
  ,CODUNDVENDA
ON RM.TPRODUTODEF
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
declare
  vCODTB3FAT      TPRODUTODEF.CODTB3FAT%TYPE;
  vCODTB4FAT      TPRODUTODEF.CODTB4FAT%TYPE;
  vCODIGOPRD      TPRODUTO.CODIGOPRD%TYPE;
  vNOMEFANTASIA   TPRODUTO.NOMEFANTASIA%TYPE;
  vDESCRICAO      TPRODUTO.DESCRICAO%TYPE;
  vCONTROLADOPORLOTE TPRODUTO.CONTROLADOPORLOTE%TYPE;
  vFRACIONA       SGS.TB_CAD_MTMD_MAT_MED.CAD_MTMD_FL_FRACIONA@PRODUCAO%TYPE;
  vATIVO          SGS.TB_CAD_MTMD_MAT_MED.CAD_MTMD_FL_ATIVO@PRODUCAO%TYPE;
  vGOTAS          NUMBER;
  --vMATMED         TPRDCOMPL.MATMED%TYPE;
begin

/*
BEGIN
  SELECT MATMED
    INTO vMATMED
    FROM TPRDCOMPL
   WHERE CODCOLIGADA = :NEW.CODCOLIGADA
     AND IDPRD = :NEW.IDPRD;
EXCEPTION
  WHEN OTHERS THEN
    vMATMED := NULL;
END;

IF (vMATMED = 'MA' AND NVL(:NEW.CODTB3FAT,'00') = '01') THEN
  RAISE_APPLICATION_ERROR(-20501, '-  ESTE PRODUTO NAO PODE SER CADASTRADO COM O GRUPO DROGAS E MEDICAMENTOS, POIS ESTA ATRIBUIDO COMO MATERIAL NOS CAMPOS COMPLEMENTARES, FAVOR VERIFICAR. -');
END IF;

IF (vMATMED = 'ME' AND NVL(:NEW.CODTB3FAT,'00') != '01') THEN
  RAISE_APPLICATION_ERROR(-20501, '-  ESTE PRODUTO SO PODE SER CADASTRADO COM O GRUPO DROGAS E MEDICAMENTOS, POIS ESTA ATRIBUIDO COMO MEDICAMENTO NOS CAMPOS COMPLEMENTARES, FAVOR VERIFICAR. -');
END IF;
*/
IF :NEW.CODCOLIGADA = 1 THEN
  IF ( UPDATING OR INSERTING ) THEN
     -- BUSCA GRUPO
     vCODTB3FAT := :NEW.CODTB3FAT;
     -- BUSCA SUB GRUPO
     vCODTB4FAT := :NEW.CODTB4FAT;
     SELECT TRIM(T.CODIGOPRD), T.NOMEFANTASIA, T.DESCRICAO,  DECODE(INATIVO, 1, 0, 1) ATIVO,
           DECODE(UPPER(CAMPOLIVRE2), 'S', 1, 0) FRACIONA, DECODE(UPPER(CAMPOLIVRE3), 'S', 1, NULL) GOTAS, CONTROLADOPORLOTE
      INTO vCODIGOPRD,        vNOMEFANTASIA,  vDESCRICAO,   vATIVO, 
           vFRACIONA,         vGOTAS,         vCONTROLADOPORLOTE
      FROM TPRODUTO T
      WHERE T.CODCOLPRD = 1 AND T.IDPRD = :NEW.IDPRD;
     SGS.PRC_CAD_MTMD_MAT_MED_U@PRODUCAO(vCODTB3FAT,   -- GRUPO
                                         NVL(vCODTB4FAT,0),   -- SUBGRUPO
                                         vNOMEFANTASIA,
                                         vDESCRICAO,
                                         :NEW.CODFAB,
                                         vFRACIONA,
                                         vATIVO,
                                         :NEW.IDPRD,
                                         vCONTROLADOPORLOTE,
                                         :NEW.CODUNDCONTROLE,
                                         :NEW.CODUNDVENDA,
                                         :NEW.CODUNDCOMPRA,
                                         vCODIGOPRD,
                                         vGOTAS);
  END IF;
END IF;
end TR_PRODUTO_DEF_ESTOQUE_SGS;