SET PAGESIZE 50000
SET LINESIZE 500
SET HEADING OFF
SET FEEDBACK OFF

SPOOL F:\AgendaWeb\Internacao\AtualizaInternacao.SQL 

select  ' BEGIN TRY
          BEGIN TRANSACTION' from dual

/

SELECT 'INSERT INTO TB_HIS_INT_HIST_INTERNACAO_WEB 
       (HIS_INT_CD_INTERNACAO, HIS_INT_NM_PACIENTE, HIS_INT_DT_NASCIMENTO, HIS_INT_DS_UNIDADE,
       HIS_INT_DT_INTERNACAO, HIS_INT_DT_SAIDA, HIS_INT_NM_PROF_RESP_INTERN, HIS_INT_DS_ESPEC_PROF_RESP, 
       HIS_INT_NM_PROF_RESP_SAIDA, HIS_INT_NR_PRONTUARIO) VALUES 
       (' || ATE.ATD_ATE_ID || ',' || CHR(39) || PES_PAC.CAD_PES_NM_PESSOA || CHR(39) || ',' || CHR(39) || 
       TO_CHAR(PES_PAC.CAD_PES_DT_NASCIMENTO, 'DD-MM-YYYY') || CHR(39) || ',' || CHR(39) || UNI.CAD_UNI_DS_UNIDADE || CHR(39) || ',' || CHR(39) || 
       TO_CHAR(ATE.ATD_ATE_DT_ATENDIMENTO, 'DD-MM-YYYY') || CHR(39) || ',' || CHR(39) || TO_CHAR(INA.ATD_INA_DT_ALTA_ADM, 'DD-MM-YYYY') || CHR(39) || ',' || CHR(39) || 
       PES_PRO_INT.CAD_PES_NM_PESSOA || CHR(39) || ',' || CHR(39) || CBO.TIS_CBO_DS_CBOS_HAC || CHR(39) || ',' || CHR(39) || 
       PES_PRO_SAIDA.CAD_PES_NM_PESSOA || CHR(39) || ',' || CHR(39) || PAC.CAD_PAC_NR_PRONTUARIO || CHR(39) || ')'
  FROM TB_ATD_ATE_ATENDIMENTO  ATE,
       TB_ASS_PAT_PACIEATEND   PAT,
       TB_CAD_PAC_PACIENTE     PAC,
       TB_CAD_PES_PESSOA       PES_PAC,
       TB_ATD_INA_INT_ALTA     INA,
       TB_CAD_PRO_PROFISSIONAL PRO_INT,
       TB_CAD_PES_PESSOA       PES_PRO_INT,
       TB_TIS_CBO_CBOS         CBO,
       TB_CAD_UNI_UNIDADE      UNI,
       TB_CAD_PRO_PROFISSIONAL PRO_SAIDA,
       TB_CAD_PES_PESSOA       PES_PRO_SAIDA
 WHERE ATE.ATD_ATE_FL_STATUS = 'A' --ATIVOS
   AND ATE.ATD_ATE_TP_PACIENTE = 'I' --INTERNACAO
   AND ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = 29 --SOMENTE LOCAL INTERNADO, DESCONSIDERAREMOS HOME CARE
   AND PAT.ATD_ATE_ID = ATE.ATD_ATE_ID
   AND PAT.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(ATE.ATD_ATE_ID) --PARA NAO REPLICAR SE HOUVE ALTERACAO DE FONTE PAGADORA
   AND PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
   AND PAC.CAD_PES_ID_PESSOA = PES_PAC.CAD_PES_ID_PESSOA
   AND PAC.CAD_CNV_ID_CONVENIO = 281 -- CONVENIO ACS
   AND INA.ATD_ATE_ID = ATE.ATD_ATE_ID
   AND ATE.CAD_PRO_ID_PROF_EXEC = PRO_INT.CAD_PRO_ID_PROFISSIONAL
   AND PRO_INT.CAD_PES_ID_PESSOA = PES_PRO_INT.CAD_PES_ID_PESSOA
   AND ATE.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
   AND ATE.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
   AND INA.CAD_PRO_ID_PROFISSIONAL = PRO_SAIDA.CAD_PRO_ID_PROFISSIONAL
   AND PRO_SAIDA.CAD_PES_ID_PESSOA = PES_PRO_SAIDA.CAD_PES_ID_PESSOA
   AND TRUNC(INA.ATD_INA_DT_ALTA_ADM) = TRUNC(SYSDATE) - 2
ORDER BY ATE.ATD_ATE_DT_ATENDIMENTO, INA.ATD_INA_DT_ALTA_ADM
/

select 'COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION' from dual
	
/
select 'PRINT '|| CHR(39)||'ERRO'||CHR(39)|| ' + ERROR_MESSAGE()' from dual
/

select 	'END CATCH
GO ' from dual
/

SELECT 'DELETE FROM TB_HIS_INT_HIST_INTERNACAO_WEB 
WHERE HIS_INT_DT_SAIDA < GETDATE() - 180' FROM DUAL
/

SPOOL OFF
EXIT
