CREATE OR REPLACE PROCEDURE PRC_BNF_HOMECARE_S
  (
     pBNF_HOMECARE_ID IN TB_BNF_HOMECARE.BNF_HOMECARE_ID%type DEFAULT NULL,
     pBNF_COD_PLANO IN TB_BNF_HOMECARE.BNF_COD_PLANO%type DEFAULT NULL,
     pBNF_LOJA_ID IN TB_BNF_HOMECARE.BNF_LOJA_ID%type DEFAULT NULL,
     pBNF_BEN_ID IN TB_BNF_HOMECARE.BNF_BEN_ID%type DEFAULT NULL,
     pBNF_COD_SEQ IN TB_BNF_HOMECARE.BNF_COD_SEQ%type DEFAULT NULL,
     pBNF_COD_NUM_PLANO IN TB_BNF_HOMECARE.BNF_COD_NUM_PLANO%type DEFAULT NULL,
     pBNF_PLA_ID_PLANO IN TB_BNF_HOMECARE.BNF_PLA_ID_PLANO%type DEFAULT NULL,
     pBNF_FL_ATIVO IN TB_BNF_HOMECARE.BNF_FL_ATIVO%type DEFAULT NULL,
     pBNF_ENDERECO IN TB_BNF_HOMECARE.BNF_ENDERECO%type DEFAULT NULL,
     pBNF_BAIRRO IN TB_BNF_HOMECARE.BNF_BAIRRO%type DEFAULT NULL,
     pBNF_UF IN TB_BNF_HOMECARE.BNF_UF%type DEFAULT NULL,
     pBNF_NUMERO IN TB_BNF_HOMECARE.BNF_NUMERO%type DEFAULT NULL,
     pBNF_CEP IN TB_BNF_HOMECARE.BNF_CEP%type DEFAULT NULL,
     pBNF_DDD IN TB_BNF_HOMECARE.BNF_DDD%type DEFAULT NULL,
     pBNF_TELEFONE IN TB_BNF_HOMECARE.BNF_TELEFONE%type DEFAULT NULL,
     pBNF_DDD2 IN TB_BNF_HOMECARE.BNF_DDD2%type DEFAULT NULL,
     pBNF_TELEFONE2 IN TB_BNF_HOMECARE.BNF_TELEFONE2%type DEFAULT NULL,
     pBNF_DDD3 IN TB_BNF_HOMECARE.BNF_DDD3%type DEFAULT NULL,
     pBNF_TELEFONE3 IN TB_BNF_HOMECARE.BNF_TELEFONE3%type DEFAULT NULL,
     pBNF_COMP IN TB_BNF_HOMECARE.BNF_COMP%type DEFAULT NULL,
     pBNF_TIPO_LOGRADOURO IN TB_BNF_HOMECARE.BNF_TIPO_LOGRADOURO%type DEFAULT NULL,
     pBNF_OBS IN TB_BNF_HOMECARE.BNF_OBS%type DEFAULT NULL,
     pBNF_EMAIL IN TB_BNF_HOMECARE.BNF_EMAIL%type DEFAULT NULL,
     pBNF_MUN_CD_IBGE IN TB_BNF_HOMECARE.BNF_MUN_CD_IBGE%type default NULL,
     pNOMBEN    IN BNF_BENEFICIARIO.nomben%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  ) 
  is
  /********************************************************************
  *    Procedure: PRC_BNF_HOMECARE_S
  * 
  *    Data Criacao: 	data da  criação   Por: Nome do Analista
  *    Data Alteracao:	data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT BNF.NOMBEN,                PLANO.CAD_PLA_NM_NOME_PLANO, IBGE.AUX_MUN_NM_MUNICIPIO,
           HOMECARE.BNF_HOMECARE_ID,  HOMECARE.BNF_COD_PLANO,    HOMECARE.BNF_LOJA_ID,
           HOMECARE.BNF_BEN_ID,       HOMECARE.BNF_COD_SEQ,      HOMECARE.BNF_COD_NUM_PLANO,
           HOMECARE.BNF_PLA_ID_PLANO, HOMECARE.BNF_FL_ATIVO,     HOMECARE.BNF_ENDERECO,
           HOMECARE.BNF_BAIRRO,       HOMECARE.BNF_UF,           HOMECARE.BNF_NUMERO,
           HOMECARE.BNF_CEP,          HOMECARE.BNF_DDD,          HOMECARE.BNF_TELEFONE,
           HOMECARE.BNF_DDD2,         HOMECARE.BNF_TELEFONE2,    HOMECARE.BNF_DDD3,
           HOMECARE.BNF_TELEFONE3,    HOMECARE.BNF_COMP,         HOMECARE.BNF_TIPO_LOGRADOURO,
           HOMECARE.BNF_OBS,          HOMECARE.BNF_EMAIL,        HOMECARE.BNF_MUN_CD_IBGE
    FROM TB_BNF_HOMECARE HOMECARE,
         BNF_BENEFICIARIO BNF,
         TB_CAD_PLA_PLANO PLANO,
         TB_AUX_MUN_MUNICIPIO IBGE
    WHERE (pBNF_HOMECARE_ID is null OR BNF_HOMECARE_ID = pBNF_HOMECARE_ID) 
    AND   (pBNF_COD_PLANO is null OR BNF_COD_PLANO = pBNF_COD_PLANO) 
    AND   (pBNF_LOJA_ID is null OR BNF_LOJA_ID = pBNF_LOJA_ID) 
    AND   (pBNF_BEN_ID is null OR BNF_BEN_ID = pBNF_BEN_ID) 
    AND   (pBNF_COD_SEQ is null OR BNF_COD_SEQ = pBNF_COD_SEQ) 
    AND   (pBNF_COD_NUM_PLANO is null OR BNF_COD_NUM_PLANO = pBNF_COD_NUM_PLANO) 
    AND   (pBNF_PLA_ID_PLANO is null OR BNF_PLA_ID_PLANO = pBNF_PLA_ID_PLANO) 
    AND   (pBNF_FL_ATIVO is null OR BNF_FL_ATIVO = pBNF_FL_ATIVO) 
    AND   (pBNF_ENDERECO is null OR BNF_ENDERECO = pBNF_ENDERECO) 
    AND   (pBNF_BAIRRO is null OR BNF_BAIRRO = pBNF_BAIRRO) 
    AND   (pBNF_UF is null OR BNF_UF = pBNF_UF) 
    AND   (pBNF_NUMERO is null OR BNF_NUMERO = pBNF_NUMERO) 
    AND   (pBNF_CEP is null OR BNF_CEP = pBNF_CEP) 
    AND   (pBNF_DDD is null OR BNF_DDD = pBNF_DDD) 
    AND   (pBNF_TELEFONE is null OR BNF_TELEFONE = pBNF_TELEFONE) 
    AND   (pBNF_DDD2 is null OR BNF_DDD2 = pBNF_DDD2) 
    AND   (pBNF_TELEFONE2 is null OR BNF_TELEFONE2 = pBNF_TELEFONE2) 
    AND   (pBNF_DDD3 is null OR BNF_DDD3 = pBNF_DDD3) 
    AND   (pBNF_TELEFONE3 is null OR BNF_TELEFONE3 = pBNF_TELEFONE3) 
    AND   (pBNF_COMP is null OR BNF_COMP = pBNF_COMP) 
    AND   (pBNF_TIPO_LOGRADOURO is null OR BNF_TIPO_LOGRADOURO = pBNF_TIPO_LOGRADOURO) 
    AND   (pBNF_OBS is null OR BNF_OBS = pBNF_OBS) 
    AND   (pBNF_EMAIL is null OR BNF_EMAIL = pBNF_EMAIL) 
    AND   (pBNF_MUN_CD_IBGE is null OR BNF_MUN_CD_IBGE = pBNF_MUN_CD_IBGE)
    AND   ( pNOMBEN IS NULL OR BNF.nomben LIKE pNOMBEN||'%' )
    AND   HOMECARE.BNF_COD_PLANO = BNF.CODCON 
    AND   HOMECARE.BNF_LOJA_ID = BNF.CODEST 
    AND   HOMECARE.BNF_BEN_ID = BNF.CODBEN 
    AND   HOMECARE.BNF_COD_SEQ = BNF.CODSEQBEN
    AND   PLANO.CAD_PLA_CD_PLANO = BNF.CODCON  
    AND   HOMECARE.bnf_mun_cd_ibge = IBGE.aux_mun_cd_ibge 
    ORDER BY BNF.NOMBEN, BNF.DATNASBEN;
    io_cursor := v_cursor;
  end PRC_BNF_HOMECARE_S;
