
Estas tabelas já estão em produção

ALTER TABLE TB_FAT_NOF_NOTA_FISCAL ADD( FAT_NOF_FL_SITUACAO_ENVIO NUMBER DEFAULT 0 );
ALTER TABLE TB_FAT_NOF_NOTA_FISCAL ADD( FAT_NOF_NR_RPS NUMBER DEFAULT 0 );
ALTER TABLE TB_FAT_NOF_NOTA_FISCAL ADD( FAT_NOF_DS_DESCRICAO VARCHAR2(255) ) ;


Novas tabelas:

CREATE TABLE TB_NFSE_HISTORICO
(
  FAT_NOF_ID                    NUMBER NOT NULL,
  FAT_NOF_FL_SITUACAO_ENVIO     NUMBER DEFAULT 0,
  FAT_NOF_NR_RPS                NUMBER,
  FAT_NOF_NR_LOTE_ENVIO         NUMBER,  
  DATA_HISTORICO                DATE,
  PROTOCOLO                     VARCHAR2(15),
  DESCRICAO                     VARCHAR2(2048)
);


CREATE TABLE TB_NFSE_CONTROLE_XML
(
  FAT_NOF_ID                    NUMBER NOT NULL,
  FAT_NOF_FL_SITUACAO_ENVIO     NUMBER DEFAULT 0,
  FAT_NOF_NR_RPS                NUMBER,
  FAT_NOF_NR_LOTE_ENVIO         NUMBER,
  CAD_UNI_DS_MUNICIPIO          VARCHAR2(50),
  FAT_NOF_NR_NOTAFISCAL         NUMBER,
  CAD_UNI_ID_UNIDADE            NUMBER(10) NOT NULL,
  FAT_NOF_FL_STATUS             CHAR(1) NOT NULL,
  CAD_CNV_ID_CONVENIO           NUMBER(10) NOT NULL,
  CAD_PLA_ID_PLANO              NUMBER(10),
  FAT_NFO_VL_FATURADO           NUMBER(12,2) NOT NULL,
  FAT_NFO_VL_RETENCAO           NUMBER(12,2),
  FAT_NFO_VL_LIQUIDO            NUMBER(12,2) NOT NULL,
  FAT_NOF_VL_IR                 NUMBER(12,2),
  FAT_NOF_PC_IR                 NUMBER(5,2),
  FAT_NOF_VL_ISS                NUMBER(12,2),
  FAT_NOF_VL_ISS_RETIDO         NUMBER(12,2),
  ALIQUOTA                      NUMBER(5,4), -- FAT_NOF_PC_ISS
  FAT_NOF_VL_COFINS             NUMBER(12,2),
  FAT_NOF_PC_COFINS             NUMBER(5,2),
  FAT_NOF_VL_CSLL               NUMBER(12,2),
  FAT_NOF_PC_CSLL               NUMBER(5,2),
  FAT_NOF_VL_PIS                NUMBER(12,2),
  FAT_NOF_PC_PIS                NUMBER(5,2),
  FAT_NOF_VL_DESCONTO           NUMBER(12,2),
  FAT_NOF_DS_DESCONTO           VARCHAR2(100),
  FAT_NOF_FL_JURIDICA           CHAR(1),
  FAT_NOF_DS_DESCRICAO          VARCHAR2(255),
  CAD_UNI_CD_INSCR_MUNIC        VARCHAR2(20),
  NOME_TOMADOR                  VARCHAR2(115),
  CNPJ_CPF_TOMADOR              NUMBER,
  INSCRICAO_MUNICIPAL_TOMADOR   VARCHAR2(11),
  TELEFONE_TOMADOR              VARCHAR2(8),  
  DDD_TOMADOR                   NUMBER,
  LOGRADOURO_TOMADOR            VARCHAR2(120),
  NUMERO_ENDERECO_TOMADOR       VARCHAR2(9),
  COMPLEMENTO_ENDERECO_TOMADOR  VARCHAR2(30),
  TIPO_BAIRRO_TOMADOR           VARCHAR2(10),
  BAIRRO_TOMADOR                VARCHAR2(60),
  TIPO_LOGRADOURO_TOMADOR       VARCHAR2(10),
  MUNICIPIO_TOMADOR_CD          NUMBER,
  MUNICIPIO_TOMADOR_DESC        VARCHAR2(50),
  UF_TOMADOR                    VARCHAR2(2),
  CEP_TOMADOR                   NUMBER,
  EMAIL_TOMADOR                 VARCHAR2(60),  
  CODIGO_ATIDADE                VARCHAR2(9),
  TIPO_RECOLHIMENTO             CHAR(1),
  MUNICIPIO_PRESTACAO_CD        VARCHAR2(10),
  MUNICIPIO_PRESTACAO_DESC      VARCHAR2(30),
  NATUREZA_OPERACAO             CHAR(1),
  -- TRIBUTACAO                    CHAR(1),
  -- DESCRICAO_RPS                 VARCHAR2(1500),
  DDD_PRESTADOR                 VARCHAR2(3),
  TELEFONE_PRESTADOR            VARCHAR2(8),
  MOTIVO_CANCELAMENTO           VARCHAR2(80),
  TIPO_RPS                      VARCHAR2(20),
  SERIE_RPS                     VARCHAR2(2),
  SITUACAO_RPS                  CHAR(1),
  SERIE_RPS_SUBSTITUIDO         VARCHAR2(10),
  NUMERO_NFSE_SUBSTITUIDA       NUMBER,
  NUMERO_RPS_SUBSTITUIDO        NUMBER,
  DATA_EMISSAO_NFSE_SUBSTITUIDA DATE,
  SERIE_PRESTACAO               NUMBER ,
  DATA_RPS_GERADO              DATE,  
  DATA_PREPARO_XML             DATE,
  DATA_GERACAO_XML             DATE,  
  DATA_ENVIO                   DATE,
  DATA_RETORNO                 DATE, -- COMMENT 'RESPOSTA ENVIO', 
  DATA_GERACAO_NOTA            DATE,  
  CAD_TPE_CD_CODIGO            VARCHAR2(4),
  PROTOCOLO                    VARCHAR2(15),
  FAT_NOF_CD_VERIFICACAO       VARCHAR2(10),
  DESCRICAO                    VARCHAR2(2048) -- TEXTO DESCREVENDO PROCESSOS EXECUTADOS
);

CREATE TABLE TB_NFSE_CONTROLE_RPS (
FAT_NOF_NR_RPS                NUMBER,
FAT_NOF_NR_LOTE_ENVIO         NUMBER,
CAD_PES_NR_CNPJ_CPF           NUMBER,
CAD_PES_CD_INSCR_MUNIC        VARCHAR2(20),
CAD_UNI_ID_UNIDADE            NUMBER,
CAD_UNI_DS_MUNICIPIO          VARCHAR2(50),
FAT_NOF_ULTIMO_RPS_ENVIADO    NUMBER,
FAT_NOF_DATA_ULTIMO_ENVIO     DATE,
FAT_NOF_DATA_ULTIMO_ENVIO_OK  DATE,
COD_IBGE_MUNICIPIO            NUMBER,
SERIAL                        VARCHAR2(128),
ALIQUOTA                      NUMBER(5,4),
ITEM_SERVICO_TRIBUTACAO       VARCHAR2(4),
CD_TRIBUTACAO_MUNICIPIO       VARCHAR2(20),
CD_CNAE                       VARCHAR2(20),
SERIE_RPS                     VARCHAR2(5),
TIPO_RPS                      NUMBER,
NATUREZA_OPERACAO             NUMBER,
REGIME_ESPECIAL_TRIBUTACAO    NUMBER,
OPTANTE_SIMPLE_NACIONAL       NUMBER,
INCENTIVADOR_CULTURAL         NUMBER
);