
ALTER TABLE TB_ASS_PAP_PAC_ATEN_PROC
DISABLE CONSTRAINT CK_ASS_PAP_FL_STATUS_AUTOR;
   
ALTER TABLE TB_ASS_PAP_PAC_ATEN_PROC DROP CONSTRAINT CK_ASS_PAP_FL_STATUS_AUTOR;
   
ALTER TABLE TB_ASS_PAP_PAC_ATEN_PROC
 ADD CONSTRAINT CK_ASS_PAP_FL_STATUS_AUTOR CHECK (ASS_PAP_FL_STATUS_AUTOR IN ('A','P','N','C')) ENABLE;
   
ALTER TABLE TB_ASS_PAP_PAC_ATEN_PROC ENABLE CONSTRAINT CK_ASS_PAP_FL_STATUS_AUTOR;
   
