
alter table TB_CAD_CLC_CLINICA_CREDENCIADA 
 add CAD_CLC_FL_LIBERA_AGENDAMENTO CHAR(1);
 
comment on column TB_CAD_CLC_CLINICA_CREDENCIADA.CAD_CLC_FL_LIBERA_AGENDAMENTO
  is 'FlagLiberaAgendamento';

alter table TB_CAD_CLC_CLINICA_CREDENCIADA modify CAD_CLC_FL_LIBERA_AGENDAMENTO default 'N';

alter table TB_CAD_CLC_CLINICA_CREDENCIADA
  add constraint CK_CAD_CLC_FL_LIBER_AGENDA
  check (CAD_CLC_FL_LIBERA_AGENDAMENTO IN ('S','N'));
    
