using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SGS.AgenteService
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     O código foi gerado por uma ferramenta.
    //     Versão de Tempo de Execução:4.0.30319.42000
    //
    //     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
    //     o código for gerado novamente.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Root
    {

        private RootItens[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Itens", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RootItens[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootItens
    {

        private RootItensItem[] itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RootItensItem[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootItensItem
    {

        private string mEDICALRECORDField;

        private string dOCUMENTTYPECODEField;

        private string dOCUMENTNUMBERField;

        private string pATIENTNAMEField;

        private string rESPONSIBLENAMEField;

        private string rESPONSIBLEDOCUMENTTYPECODEField;

        private string rESPONSIBLEDOCUMENTField;

        private string gENDERField;

        private string bIRTHDATEField;

        private string wEIGHTField;

        private string hEIGHTField;

        private string hOSPITALCODEField;

        private string hOSPITALADMISSIONNUMBERField;

        private string hOSPITALADMISSIONDATEField;

        private string uNITCODEField;

        private string uNITADMISSIONNUMBERField;

        private string uNITADMISSIONDATETIMEField;

        private string bEDCODEField;

        private string dISCHARGECAUSEField;

        private string hOSPITALDISCHARGEDATEField;

        private string hOSPITALHEALTHINSURANCECODEField;

        private string mEDICALDISCHARGEDATEField;

        private string cREATEDATEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEDICALRECORD
        {
            get
            {
                return this.mEDICALRECORDField;
            }
            set
            {
                this.mEDICALRECORDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCUMENTTYPECODE
        {
            get
            {
                return this.dOCUMENTTYPECODEField;
            }
            set
            {
                this.dOCUMENTTYPECODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCUMENTNUMBER
        {
            get
            {
                return this.dOCUMENTNUMBERField;
            }
            set
            {
                this.dOCUMENTNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PATIENTNAME
        {
            get
            {
                return this.pATIENTNAMEField;
            }
            set
            {
                this.pATIENTNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESPONSIBLENAME
        {
            get
            {
                return this.rESPONSIBLENAMEField;
            }
            set
            {
                this.rESPONSIBLENAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESPONSIBLEDOCUMENTTYPECODE
        {
            get
            {
                return this.rESPONSIBLEDOCUMENTTYPECODEField;
            }
            set
            {
                this.rESPONSIBLEDOCUMENTTYPECODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESPONSIBLEDOCUMENT
        {
            get
            {
                return this.rESPONSIBLEDOCUMENTField;
            }
            set
            {
                this.rESPONSIBLEDOCUMENTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GENDER
        {
            get
            {
                return this.gENDERField;
            }
            set
            {
                this.gENDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIRTHDATE
        {
            get
            {
                return this.bIRTHDATEField;
            }
            set
            {
                this.bIRTHDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEIGHT
        {
            get
            {
                return this.wEIGHTField;
            }
            set
            {
                this.wEIGHTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HEIGHT
        {
            get
            {
                return this.hEIGHTField;
            }
            set
            {
                this.hEIGHTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOSPITALCODE
        {
            get
            {
                return this.hOSPITALCODEField;
            }
            set
            {
                this.hOSPITALCODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOSPITALADMISSIONNUMBER
        {
            get
            {
                return this.hOSPITALADMISSIONNUMBERField;
            }
            set
            {
                this.hOSPITALADMISSIONNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOSPITALADMISSIONDATE
        {
            get
            {
                return this.hOSPITALADMISSIONDATEField;
            }
            set
            {
                this.hOSPITALADMISSIONDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNITCODE
        {
            get
            {
                return this.uNITCODEField;
            }
            set
            {
                this.uNITCODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNITADMISSIONNUMBER
        {
            get
            {
                return this.uNITADMISSIONNUMBERField;
            }
            set
            {
                this.uNITADMISSIONNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNITADMISSIONDATETIME
        {
            get
            {
                return this.uNITADMISSIONDATETIMEField;
            }
            set
            {
                this.uNITADMISSIONDATETIMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BEDCODE
        {
            get
            {
                return this.bEDCODEField;
            }
            set
            {
                this.bEDCODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISCHARGECAUSE
        {
            get
            {
                return this.dISCHARGECAUSEField;
            }
            set
            {
                this.dISCHARGECAUSEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOSPITALDISCHARGEDATE
        {
            get
            {
                return this.hOSPITALDISCHARGEDATEField;
            }
            set
            {
                this.hOSPITALDISCHARGEDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOSPITALHEALTHINSURANCECODE
        {
            get
            {
                return this.hOSPITALHEALTHINSURANCECODEField;
            }
            set
            {
                this.hOSPITALHEALTHINSURANCECODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEDICALDISCHARGEDATE
        {
            get
            {
                return this.mEDICALDISCHARGEDATEField;
            }
            set
            {
                this.mEDICALDISCHARGEDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATEDATE
        {
            get
            {
                return this.cREATEDATEField;
            }
            set
            {
                this.cREATEDATEField = value;
            }
        }
    }

}
