 CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_NOF_CANCELADAS"
(
    pCAD_UNI_ID_UNIDADE      IN TB_FAT_NOF_NOTA_FISCAL.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    PFAT_CCP_MES_FAT IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_MES_FAT%TYPE DEFAULT NULL,
    PFAT_CCP_ANO_FAT IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_ANO_FAT%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_NOF_CANCELADAS
*
*    Data Criação: 02/03/2012  Por: Eduardo
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
BEGIN
  OPEN v_cursor FOR
  SELECT DISTINCT CNV.CAD_CNV_CD_HAC_PRESTADOR,
          CNV.CAD_CNV_DS_RAZAOSOCIAL,
          NOF.FAT_NOF_NR_NOTAFISCAL,
          NOF.FAT_NFO_VL_LIQUIDO,
          NOF.FAT_NOF_TP_SERIEFISCAL,
          NOF.FAT_NFO_DT_EMISSAO,
          NOF.FAT_NFO_DT_VENCIMENTO,
          NOF.FAT_NFO_VL_RETENCAO,
          NOF.FAT_NOF_VL_ISS,
          NOF.FAT_NOF_FL_STATUS,
          NOF.FAT_NFO_VL_FATURADO,
          NOF.FAT_NOF_MES_FAT,
          NOF.FAT_NOF_ANO_FAT,
          UNI.CAD_UNI_DS_UNIDADE,
          MUN.AUX_MUN_NM_MUNICIPIO,
          NOF.FAT_NOF_ID
  FROM    TB_FAT_NOF_NOTA_FISCAL NOF
  JOIN    TB_CAD_CNV_CONVENIO         CNV
  ON      CNV.CAD_CNV_ID_CONVENIO   = NOF.CAD_CNV_ID_CONVENIO
  JOIN    TB_CAD_UNI_UNIDADE UNI
  ON      UNI.CAD_UNI_ID_UNIDADE = NOF.CAD_UNI_ID_UNIDADE
--  JOIN    TB_ASS_PEE_PESSOA_ENDERECO PES
--  ON      PES.CAD_PES_ID_PESSOA = UNI.CAD_PES_ID_PESSOA
  JOIN    TB_CAD_END_ENDERECO ENDE
  ON      ENDE.CAD_PES_ID_PESSOA = UNI.CAD_PES_ID_PESSOA
  JOIN    TB_AUX_MUN_MUNICIPIO MUN
  ON      MUN.AUX_MUN_CD_IBGE = ENDE.AUX_MUN_CD_IBGE

  WHERE  (pCAD_UNI_ID_UNIDADE IS NULL OR NOF.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
  AND    (pCAD_CNV_ID_CONVENIO IS NULL OR CNV.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
  AND    (PFAT_CCP_MES_FAT IS NULL OR NOF.FAT_NOF_MES_FAT = PFAT_CCP_MES_FAT)
  AND    (PFAT_CCP_ANO_FAT IS NULL OR NOF.FAT_NOF_ANO_FAT = PFAT_CCP_ANO_FAT)
  AND    ENDE.AUX_TTE_CD_TP_TEL_END = 2
  AND    (NOF.FAT_NOF_FL_STATUS = 'C')
  AND    (pATD_ATE_DT_ATENDIMENTO_INI IS NULL OR NOF.FAT_NFO_DT_EMISSAO BETWEEN  pATD_ATE_DT_ATENDIMENTO_INI AND pATD_ATE_DT_ATENDIMENTO_FIM)
  AND (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and CNV.CAD_TPE_CD_CODIGO = 'ACS'
   OR pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'PA'
   OR pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'SP'
   OR pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'FU'
   OR pCAD_PLA_CD_TIPOPLANO_NP IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'NP')
  ORDER BY NOF.FAT_NOF_NR_NOTAFISCAL
;
  io_cursor := v_cursor;
END PRC_FAT_REL_NOF_CANCELADAS;
