CREATE OR REPLACE PROCEDURE PRC_MTMD_REQUISICAO_ITEM_U
  (
     pMTMD_REQ_ID IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQ_ID%type,
     pCAD_MTMD_ID IN TB_MTMD_REQUISICAO_ITEM.CAD_MTMD_ID%type,
     pMTMD_REQITEM_QTD_SOLICITADA IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQITEM_QTD_SOLICITADA%type,
     pMTMD_REQITEM_QTD_FORNECIDA IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQITEM_QTD_FORNECIDA%type default NULL,
     pCAD_MTMD_KIT_ID_ITEM       IN SGS.TB_MTMD_REQUISICAO_ITEM.CAD_MTMD_KIT_ID_ITEM%TYPE DEFAULT NULL,
     pMTMD_REQITEM_CANCEL_JUST   IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQITEM_CANCEL_JUST%TYPE DEFAULT NULL
  )
  is
  /********************************************************************
  CHAMADA DA PROCEDURE: PRC_MTMD_REQ_ITEM_DISP_I
  *******************************************************************/

  begin
    UPDATE TB_MTMD_REQUISICAO_ITEM SET
    MTMD_REQITEM_QTD_SOLICITADA = pMTMD_REQITEM_QTD_SOLICITADA,
    MTMD_REQITEM_QTD_FORNECIDA = pMTMD_REQITEM_QTD_FORNECIDA,
    CAD_MTMD_KIT_ID_ITEM = pCAD_MTMD_KIT_ID_ITEM,
    MTMD_REQITEM_CANCEL_JUST = pMTMD_REQITEM_CANCEL_JUST
    WHERE CAD_MTMD_ID = pCAD_MTMD_ID
    AND   MTMD_REQ_ID = pMTMD_REQ_ID;
    -- COMMIT;
  end PRC_MTMD_REQUISICAO_ITEM_U;