create or replace procedure sgs.PRC_ASS_UCP_UN_LO_CB_PRF_A_S
  (
     pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%type DEFAULT NULL,
     pCAD_PRO_ID_PROFISSIONAL IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
     pASS_UCP_FL_STATUS IN TB_ASS_UCP_UNID_LOC_CBO_PROF.ASS_UCP_FL_STATUS%type DEFAULT NULL,
     pTIS_CPR_CD_CONSELHOPROF IN TB_CAD_PRO_PROFISSIONAL.TIS_CPR_CD_CONSELHOPROF%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
     --,TESTE OUT LONG
  )
  is
  /********************************************************************
  *    Procedure: PRC_ASS_UCP_UN_LO_CB_PRF_A_S
  *
  *    Data Criacao: 02/08/2011  Por: Eduardo Hyppolito
  *
  *    Motivo: Lista Associa??o unidade/Local/Especialidade/Profissional
  *    e traz as descri??es de Unidade e Local.
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
    V_WHERE  varchar2(1000);
    V_SELECT  varchar2(6000);
  begin

    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ASS.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ASS.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO;   END IF;
    IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ASS.TIS_CBO_CD_CBOS = ' ||CHR(39)|| pTIS_CBO_CD_CBOS ||CHR(39); END IF;
    IF pCAD_PRO_ID_PROFISSIONAL IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ASS.CAD_PRO_ID_PROFISSIONAL = ' || pCAD_PRO_ID_PROFISSIONAL;   END IF;
    IF pASS_UCP_FL_STATUS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ASS.ASS_UCP_FL_STATUS = ' ||CHR(39)|| pASS_UCP_FL_STATUS ||CHR(39); END IF;
    IF pTIS_CPR_CD_CONSELHOPROF IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRO.TIS_CPR_CD_CONSELHOPROF = ' ||CHR(39)|| pTIS_CPR_CD_CONSELHOPROF ||CHR(39); END IF;


V_SELECT := '
    SELECT
      ASS.CAD_UNI_ID_UNIDADE,
      ASS.CAD_LAT_ID_LOCAL_ATENDIMENTO,
      ASS.TIS_CBO_CD_CBOS,
      ASS.CAD_PRO_ID_PROFISSIONAL,
      ASS.ASS_UCP_QTD_AGEND_PERM_CBOS,
      ASS.ASS_UCP_FL_STATUS,
      UNI.CAD_UNI_DS_UNIDADE,
      LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
      ASS.ASS_UCP_DS_OBS,
      PES.CAD_PES_NM_PESSOA,
      CBO.TIS_CBO_DS_CBOS,
      CBO.TIS_CBO_DS_CBOS_HAC
    FROM TB_ASS_UCP_UNID_LOC_CBO_PROF ASS
    JOIN TB_CAD_PRO_PROFISSIONAL PRO
    ON   PRO.CAD_PRO_ID_PROFISSIONAL = ASS.CAD_PRO_ID_PROFISSIONAL
    JOIN TB_CAD_UNI_UNIDADE UNI
    ON   UNI.CAD_UNI_ID_UNIDADE = ASS.CAD_UNI_ID_UNIDADE
    JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
    ON   LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ASS.CAD_LAT_ID_LOCAL_ATENDIMENTO
    JOIN TB_CAD_PES_PESSOA PES
    ON   PES.CAD_PES_ID_PESSOA = PRO.CAD_PES_ID_PESSOA
    JOIN TB_TIS_CBO_CBOS CBO
    ON   CBO.TIS_CBO_CD_CBOS = ASS.TIS_CBO_CD_CBOS

    WHERE ASS.CAD_PRO_ID_PROFISSIONAL = PRO.CAD_PRO_ID_PROFISSIONAL
    ' || v_where ;
    --  TESTE :=  V_SELECT ;
  OPEN v_cursor FOR
    V_SELECT ;
   -- select sysdate from dual;
    io_cursor := v_cursor;

  end PRC_ASS_UCP_UN_LO_CB_PRF_A_S;
