--PRC_ASS_USC_UNI_SET_CCUS_CLA_L
create or replace procedure PRC_ASS_USC_UNI_SET_CCUS_CLA_L 
(
     pASS_USC_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_ID%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_SET_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_SET_ID%type DEFAULT NULL,
     pCAD_CEC_ID_CCUSTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_CEC_ID_CCUSTO%type DEFAULT NULL,
     pCAD_CAC_ID_CLASSCONTABIL IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_CAC_ID_CLASSCONTABIL%type DEFAULT NULL,
     pASS_USC_FL_STATUS IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_FL_STATUS%type DEFAULT NULL,
     pASS_USC_DT_ULTIMA_ATUALIZACAO IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ASS_USC_UNI_SET_CCUS_CLA.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_ASS_USC_UNI_SET_CCUS_CLA.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ASS_USC_UNI_SET_CCUS_CLA.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pASS_USC_DT_INICIO_VIGENCIA IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_DT_INICIO_VIGENCIA%type DEFAULT NULL,
     pASS_USC_DT_FIM_VIGENCIA IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pTIS_CBO_CD_CBOS IN TB_ASS_USC_UNI_SET_CCUS_CLA.TIS_CBO_CD_CBOS%type DEFAULT NULL,
     pCAD_TAP_TP_ATRIBUTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_TAP_TP_ATRIBUTO%type DEFAULT NULL,
     pFAT_TCO_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.FAT_TCO_ID%type DEFAULT NULL,
     pCAD_PRD_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_PRD_ID%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
/********************************************************************
*    Procedure: PRC_ASS_USC_UNI_SET_CCUS_CLA_L
* 
*    Data Criacao: 	data da  criação   Por: Nome do Analista
*    Data Alteracao:	data da alteração  Por: Nome do Analista
*
*    Funcao: Descrição da funcionalidade da Stored Procedure
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
begin
  V_WHERE := NULL;
  IF pASS_USC_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_USC_ID = ' || pASS_USC_ID; END IF;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_CEC_ID_CCUSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CEC_ID_CCUSTO = ' || pCAD_CEC_ID_CCUSTO; END IF;
IF pCAD_CAC_ID_CLASSCONTABIL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CAC_ID_CLASSCONTABIL = ' || pCAD_CAC_ID_CLASSCONTABIL; END IF;
IF pASS_USC_FL_STATUS IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_USC_FL_STATUS = ' || CHR(39) || pASS_USC_FL_STATUS || CHR(39); END IF;
IF pASS_USC_DT_ULTIMA_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_USC_DT_ULTIMA_ATUALIZACAO = ' || CHR(39) || pASS_USC_DT_ULTIMA_ATUALIZACAO || CHR(39); END IF;
IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND AUX_EPP_CD_ESPECPROC = ' || CHR(39) || pAUX_EPP_CD_ESPECPROC || CHR(39); END IF;
IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND TIS_MED_CD_TABELAMEDICA = ' || CHR(39) || pTIS_MED_CD_TABELAMEDICA || CHR(39); END IF;
IF pASS_USC_DT_INICIO_VIGENCIA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_USC_DT_INICIO_VIGENCIA = ' || CHR(39) || pASS_USC_DT_INICIO_VIGENCIA || CHR(39); END IF;
IF pASS_USC_DT_FIM_VIGENCIA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_USC_DT_FIM_VIGENCIA = ' || CHR(39) || pASS_USC_DT_FIM_VIGENCIA || CHR(39); END IF;
IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND TIS_CBO_CD_CBOS = ' || CHR(39) || pTIS_CBO_CD_CBOS || CHR(39); END IF;
IF pCAD_TAP_TP_ATRIBUTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_TAP_TP_ATRIBUTO = ' || CHR(39) || pCAD_TAP_TP_ATRIBUTO || CHR(39); END IF;
IF pFAT_TCO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND FAT_TCO_ID = ' || pFAT_TCO_ID; END IF;
IF pCAD_PRD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_PRD_ID = ' || pCAD_PRD_ID; END IF;
 
   V_SELECT := '
SELECT	
       ASS_USC_ID,
       CAD_UNI_ID_UNIDADE,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_SET_ID,
       CAD_CEC_ID_CCUSTO,
       CAD_CAC_ID_CLASSCONTABIL,
       ASS_USC_FL_STATUS,
       ASS_USC_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       AUX_EPP_CD_ESPECPROC,
       TIS_MED_CD_TABELAMEDICA,
       ASS_USC_DT_INICIO_VIGENCIA,
       ASS_USC_DT_FIM_VIGENCIA,
       TIS_CBO_CD_CBOS,
       CAD_TAP_TP_ATRIBUTO,
       FAT_TCO_ID,
       CAD_PRD_ID
FROM TB_ASS_USC_UNI_SET_CCUS_CLA
WHERE null is null  '    ;
       
OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_ASS_USC_UNI_SET_CCUS_CLA_L;
