CREATE OR REPLACE PROCEDURE PRC_INATIVA_CAD_PES_PAC_U IS
  ---
  --- Processo para inativacao de cadastro de pessoa e paciente
  ---
BEGIN
  --
  --INATIVANDO CADASTRO DE PACIENTE DE CONVENIO INATIVO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND EXISTS
             (SELECT *
                      FROM TB_CAD_CNV_CONVENIO CNV
                     WHERE PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
                       AND CNV.CAD_CNV_FL_STATUS = 'I')) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE DE PLANO INATIVO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND EXISTS
             (SELECT *
                      FROM TB_CAD_PLA_PLANO PLA
                     WHERE PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
                       AND PLA.CAD_PLA_FL_SITUACAO_PLANO = 'I')) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE COM O TAMANHO DA CREDENCIAL MENOR QUE 12 - DOS CONVENIOS SD01 E GG05
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND PAC.CAD_CNV_ID_CONVENIO in (281, 283)
               AND PAC.CAD_PAC_FL_PRE_ATENDIMENTO = 0
               AND LENGTH(PAC.CAD_PAC_CD_CREDENCIAL) < 12) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE COM O TAMANHO DA CREDENCIAL MAIOR QUE 12 - DOS CONVENIOS SD01 E GG05
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND PAC.CAD_CNV_ID_CONVENIO in (281, 283)
               AND PAC.CAD_PAC_FL_PRE_ATENDIMENTO = 0
               AND LENGTH(PAC.CAD_PAC_CD_CREDENCIAL) > 12) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE DE RNS COM MAIS DE TRINTA DIAS, INCLUSIVE DOS CONVENIOS BRADESCO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND PAC.CAD_PAC_IDT_RN = 1
               AND EXISTS
             (SELECT *
                      FROM TB_CAD_PES_PESSOA PES
                     WHERE PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
                       AND PES.CAD_PES_DT_NASCIMENTO < (TRUNC(SYSDATE) - 30))) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE SEM CREDENCIAL - DOS CONVENIOS SD01 E GG05 - E SEM NENHUM AGENDAMENTO, PRE-CADASTRO, ATENDIMENTO, INTERNACAO OU LIBERACAO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND PAC.CAD_CNV_ID_CONVENIO IN (281, 283)
               AND TRUNC(PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO) < TRUNC(SYSDATE)
               AND PAC.CAD_PAC_CD_CREDENCIAL is null
               AND NOT EXISTS
             (SELECT *
                      FROM TB_ASS_PAT_PACIEATEND  PAT,
                           TB_ATD_ATE_ATENDIMENTO ATD
                     WHERE PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
                       AND PAT.ATD_ATE_ID = ATD.ATD_ATE_ID)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_ASS_PAP_PAC_ATEN_PROC PAP
                     WHERE PAP.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_AGE_AGD_AGENDA AGD
                     WHERE AGD.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_ATD_IAE_INT_AGE_ELETIVA IAE
                     WHERE IAE.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS (SELECT *
                      FROM TB_ATS_ATE_ATENDIMENTO_SADT ATS
                     WHERE ATS.CAD_PAC_ID_PACIENTE_INT =
                           PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_AGS_AGE_AGENDA_SADT AGS
                     WHERE AGS.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --REATIVANDO COMO PRÉ-ATENDIMENTO O CADASTRO DE PACIENTE SEM CREDENCIAL - SOMENTE SERVICO PRESTADO - E SEM NENHUM AGENDAMENTO, PRE-CADASTRO, ATENDIMENTO, INTERNACAO OU LIBERACAO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC, TB_CAD_CNV_CONVENIO CNV
             WHERE PAC.CAD_PAC_FL_ATIVO_OK = 'N'
               AND PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
               AND CNV.CAD_TPE_CD_CODIGO = 'SP'
               AND TRUNC(PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO) < TRUNC(SYSDATE)
               AND PAC.CAD_PAC_FL_PRE_ATENDIMENTO = 0
               AND PAC.CAD_PAC_CD_CREDENCIAL is null
               AND NOT EXISTS
             (SELECT *
                      FROM TB_ASS_PAT_PACIEATEND  PAT,
                           TB_ATD_ATE_ATENDIMENTO ATD
                     WHERE PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
                       AND PAT.ATD_ATE_ID = ATD.ATD_ATE_ID)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_ASS_PAP_PAC_ATEN_PROC PAP
                     WHERE PAP.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_AGE_AGD_AGENDA AGD
                     WHERE AGD.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_ATD_IAE_INT_AGE_ELETIVA IAE
                     WHERE IAE.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS (SELECT *
                      FROM TB_ATS_ATE_ATENDIMENTO_SADT ATS
                     WHERE ATS.CAD_PAC_ID_PACIENTE_INT =
                           PAC.CAD_PAC_ID_PACIENTE)
               AND NOT EXISTS
             (SELECT *
                      FROM TB_AGS_AGE_AGENDA_SADT AGS
                     WHERE AGS.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE)) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'S',
           PAC.CAD_PAC_FL_PRE_ATENDIMENTO    = 1,
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE DO CONVENIO BRADESCO COM CREDENCIAL MENOR QUE 15 CARACTERES
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND PAC.CAD_PAC_FL_PRE_ATENDIMENTO = 0
               AND PAC.CAD_PAC_CD_CREDENCIAL is not null
               AND LENGTH(PAC.CAD_PAC_CD_CREDENCIAL) < 15
               AND EXISTS
             (SELECT *
                      FROM TB_CAD_CNV_CONVENIO CNV
                     WHERE PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
                       AND CNV.CAD_CNV_CD_MODVALIDADOR = '2')) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE DE BENEFICIARIO EXCLUIDO DOS CONVENIOS SD01 (ACS) E GG05 (FUNCIONARIO HAC)
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC, TB_CAD_PLA_PLANO PLA
             WHERE PAC.CAD_PAC_FL_ATIVO_OK != 'N'
               AND PAC.CAD_CNV_ID_CONVENIO in (281, 283)
               AND PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
               AND EXISTS
             (SELECT *
                      FROM BNF_BENEFICIARIO B
                     WHERE B.CODCON = PLA.CAD_PLA_CD_PLANO_HAC
                       AND LENGTH(PAC.CAD_PAC_CD_CREDENCIAL) = 12
                       AND B.CODEST =
                           TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL, 0, 3))
                       AND B.CODBEN =
                           TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL, 4, 7))
                       AND B.CODSEQBEN =
                           TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL, 11, 2))
                       AND B.CODSITBEN = 5
                       AND B.DATSAICONBEN < TRUNC(SYSDATE))) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --REATIVANDO CADASTRO DE PACIENTE DO CONVENIO ACS DE BENEFICIARIO QUE ESTAVA EXCLUIDO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC, TB_CAD_PLA_PLANO PLA
             WHERE PAC.CAD_PAC_FL_ATIVO_OK = 'N'
               AND PAC.CAD_CNV_ID_CONVENIO in (281)
               AND PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
               AND EXISTS
             (SELECT *
                      FROM BNF_BENEFICIARIO B
                     WHERE B.CODCON = PLA.CAD_PLA_CD_PLANO_HAC
                       AND LENGTH(PAC.CAD_PAC_CD_CREDENCIAL) = 12
                       AND B.CODEST =
                           TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL, 0, 3))
                       AND B.CODBEN =
                           TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL, 4, 7))
                       AND B.CODSEQBEN =
                           TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL, 11, 2))
                       AND B.CODSITBEN = 1
                       AND (B.DATSAICONBEN is null or
                           B.DATSAICONBEN >= TRUNC(SYSDATE)))) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'S',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PESSOA/PACIENTE QUE FOI A ÓBITO
  --
  FOR I IN (SELECT PES.CAD_PES_ID_PESSOA
              FROM TB_CAD_PES_PESSOA PES
             WHERE PES.CAD_PES_FL_ATIVO_OK != 'O'
               AND EXISTS
             (SELECT *
                      FROM TB_ATD_ATE_ATENDIMENTO ATD,
                           TB_ASS_PAT_PACIEATEND  PAT,
                           TB_CAD_PAC_PACIENTE    PAC
                     WHERE PAT.ATD_ATE_ID = ATD.ATD_ATE_ID
                       AND PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
                       AND PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
                       AND ATD.TIS_TSC_CD_TIPOSAIDACONSULTA = 6)) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PES_ID_PESSOA = I.CAD_PES_ID_PESSOA;
    UPDATE TB_CAD_PES_PESSOA PES
       SET PES.CAD_PES_FL_ATIVO_OK           = 'O',
           PES.CAD_PES_DT_ULTIMA_ATUALIZACAO = SYSDATE,
           PES.SEG_USU_ID_USUARIO            = 1
     WHERE PES.CAD_PES_ID_PESSOA = I.CAD_PES_ID_PESSOA;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE DE PLANO QUE NAO PERTENCE AO CONVENIO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE
              FROM TB_CAD_PAC_PACIENTE PAC, TB_CAD_PLA_PLANO PLA
             WHERE PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
               AND PAC.CAD_CNV_ID_CONVENIO != PLA.CAD_CNV_ID_CONVENIO
               AND PAC.CAD_PAC_FL_ATIVO_OK != 'N') LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
  END LOOP;
  --
  --INATIVANDO CADASTRO DE PACIENTE DE RNS COM MAIS DE TRINTA DIAS, INCLUSIVE DOS CONVENIOS BRADESCO
  --
  FOR I IN (SELECT PAC.CAD_PAC_ID_PACIENTE FROM TB_CAD_PAC_PACIENTE PAC WHERE
            PAC.CAD_PAC_FL_ATIVO_OK != 'N' AND PAC.CAD_PAC_IDT_RN = 1 AND
            EXISTS
            (SELECT *
               FROM TB_CAD_PES_PESSOA PES
              WHERE PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
                AND PES.CAD_PES_DT_NASCIMENTO < (TRUNC(SYSDATE) - 30))) LOOP
    UPDATE TB_CAD_PAC_PACIENTE PAC
       SET PAC.CAD_PAC_FL_ATIVO_OK           = 'N',
           PAC.SEG_USU_ID_USUARIO            = 1,
           PAC.CAD_PAC_DT_ULTIMA_ATUALIZACAO = SYSDATE
     WHERE PAC.CAD_PAC_ID_PACIENTE = I.CAD_PAC_ID_PACIENTE;
    COMMIT;
    END LOOP;
      
  END PRC_INATIVA_CAD_PES_PAC_U;
