create or replace procedure PRC_CAD_CVM_L
(
     pCAD_CVM_ID IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_CVM_ID%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pCAD_TIH_TP_INDICE_HOSP IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_TIH_TP_INDICE_HOSP%type DEFAULT NULL,
     pCAD_CVM_VL_MOEDA_HOSPITALAR IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_CVM_VL_MOEDA_HOSPITALAR%type DEFAULT NULL,
     pCAD_CVM_DT_INICIO_VIGENCIA IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_CVM_DT_INICIO_VIGENCIA%type DEFAULT NULL,
     pCAD_CVM_DT_FIM_VIGENCIA IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_CVM_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pCAD_PLA_ID_PLANO IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_PLA_ID_PLANO%type DEFAULT NULL,
     pCAD_CVM_DT_ULTIMA_ATUALIZACAO IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_CVM_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pCAD_TAP_TP_ATRIBUTO IN TB_CAD_CVM_CONV_VLR_MOEDAHOS.CAD_TAP_TP_ATRIBUTO%type default NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
/********************************************************************
*    Procedure: PRC_CAD_CVM_L
* 
*    Data Criacao:   10/12/2009   Por: Pedro
*    Data Alteracao: 10/09/2010   Por: Andre S. Monaco
*         Alteracao: Adicao do campo CAD_TAP_TP_ATRIBUTO
*    Data Alteracao: 29/10/2010   Por: Andre S. Monaco
*         Alteracao: Adicao do campo SEG_USU_DS_LOGIN
*
*    Funcao: Lista valores de indices (com join)
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
begin
OPEN v_cursor FOR
SELECT  
       CVM.CAD_CVM_ID,
       CVM.CAD_CNV_ID_CONVENIO,
       CVM.CAD_TIH_TP_INDICE_HOSP,
       CVM.CAD_CVM_VL_MOEDA_HOSPITALAR,
       CVM.CAD_CVM_DT_INICIO_VIGENCIA,
       CVM.CAD_CVM_DT_FIM_VIGENCIA,
       CVM.CAD_PLA_ID_PLANO,
       CVM.CAD_CVM_DT_ULTIMA_ATUALIZACAO,
       CVM.SEG_USU_ID_USUARIO,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       NVL(PLA.CAD_PLA_CD_PLANO_HAC, 'TODOS') CAD_PLA_CD_PLANO_HAC,
       TIH.CAD_TIH_DS_INDICE_HOSP,
       CVM.CAD_TAP_TP_ATRIBUTO,
       TAP.CAD_TAP_DS_ATRIBUTO,
       USU.SEG_USU_DS_LOGIN
FROM TB_CAD_CVM_CONV_VLR_MOEDAHOS CVM
JOIN TB_CAD_CNV_CONVENIO CNV
ON   CNV.CAD_CNV_ID_CONVENIO = CVM.CAD_CNV_ID_CONVENIO
LEFT JOIN TB_CAD_PLA_PLANO PLA
ON   CVM.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
JOIN TB_CAD_TIH_TP_INDICE_HOSP TIH
ON   TIH.CAD_TIH_TP_INDICE_HOSP = CVM.CAD_TIH_TP_INDICE_HOSP
LEFT JOIN TB_CAD_TAP_TP_ATRIB_PRODUTO TAP
ON   CVM.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
JOIN TB_SEG_USU_USUARIO USU
ON USU.SEG_USU_ID_USUARIO = CVM.SEG_USU_ID_USUARIO
WHERE
        (pCAD_CVM_ID is null OR CVM.CAD_CVM_ID = pCAD_CVM_ID) AND 
        (pCAD_CNV_ID_CONVENIO is null OR CVM.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND 
        (pCAD_TIH_TP_INDICE_HOSP is null OR CVM.CAD_TIH_TP_INDICE_HOSP = pCAD_TIH_TP_INDICE_HOSP) AND 
        (pCAD_CVM_VL_MOEDA_HOSPITALAR is null OR CVM.CAD_CVM_VL_MOEDA_HOSPITALAR = pCAD_CVM_VL_MOEDA_HOSPITALAR) AND 
        (pCAD_CVM_DT_INICIO_VIGENCIA is null OR CVM.CAD_CVM_DT_INICIO_VIGENCIA = pCAD_CVM_DT_INICIO_VIGENCIA) AND 
        (pCAD_CVM_DT_FIM_VIGENCIA is null OR CVM.CAD_CVM_DT_FIM_VIGENCIA = pCAD_CVM_DT_FIM_VIGENCIA) AND 
        (pCAD_PLA_ID_PLANO is null OR CVM.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO) AND 
        (pCAD_CVM_DT_ULTIMA_ATUALIZACAO is null OR CVM.CAD_CVM_DT_ULTIMA_ATUALIZACAO = pCAD_CVM_DT_ULTIMA_ATUALIZACAO) AND 
        (pSEG_USU_ID_USUARIO is null OR CVM.SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND
        (pCAD_TAP_TP_ATRIBUTO is null OR TAP.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO);                
io_cursor := v_cursor;
end PRC_CAD_CVM_L;
 
/
