CREATE OR REPLACE PROCEDURE PRC_MTMD_REQUISICAO_ITEM_I
  (
     pMTMD_REQ_ID IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQ_ID%type,
     pCAD_MTMD_ID IN TB_MTMD_REQUISICAO_ITEM.CAD_MTMD_ID%type,
     pMTMD_REQITEM_QTD_SOLICITADA IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQITEM_QTD_SOLICITADA%type,
     pMTMD_REQITEM_QTD_FORNECIDA IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQITEM_QTD_FORNECIDA%type default NULL,
     pMTMD_ID_ORIGINAL           IN SGS.TB_MTMD_REQUISICAO_ITEM.MTMD_ID_ORIGINAL%TYPE DEFAULT NULL,
     pCAD_MTMD_PRESCRICAO_ID     IN SGS.TB_MTMD_REQUISICAO_ITEM.CAD_MTMD_PRESCRICAO_ID%TYPE DEFAULT NULL,
     pCAD_MTMD_KIT_ID_ITEM       IN SGS.TB_MTMD_REQUISICAO_ITEM.CAD_MTMD_KIT_ID_ITEM%TYPE DEFAULT NULL,
     pMTMD_QTD_KIT_MULTIPLICA    IN SGS.TB_MTMD_REQUISICAO_ITEM.MTMD_QTD_KIT_MULTIPLICA%TYPE DEFAULT NULL,
     pATD_MPM_ID                 IN TB_MTMD_REQUISICAO_ITEM.ATD_MPM_ID%TYPE DEFAULT NULL,
     pATD_PME_ID                 IN TB_MTMD_REQUISICAO_ITEM.ATD_PME_ID%TYPE DEFAULT NULL,
     pMTMD_REQITEM_CANCEL_JUST   IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQITEM_CANCEL_JUST%TYPE DEFAULT NULL,
     pMTMD_REQ_VIA               IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQ_VIA%TYPE DEFAULT NULL,
     pMTMD_FL_GELADEIRA          IN TB_MTMD_REQUISICAO_ITEM.MTMD_FL_GELADEIRA%TYPE DEFAULT NULL
  )
  is
  /********************************************************************
  *    Procedure: PRC_MTMD_REQUISICAO_ITEM_I
  *
  *    Data Criacao:  data da  cria???#o   Por: Nome do Analista
  *    Data Alteracao: data da altera???#o  Por: Nome do Analista
  *
  *    Funcao: Descri???#o da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  vMTM_TIPO_REQUISICAO TB_MTMD_REQ_REQUISICAO.MTM_TIPO_REQUISICAO%TYPE;
  begin
    SELECT REQUISICAO.MTM_TIPO_REQUISICAO
      INTO vMTM_TIPO_REQUISICAO
      FROM TB_MTMD_REQ_REQUISICAO REQUISICAO
      WHERE REQUISICAO.mtmd_req_id = pMTMD_REQ_ID;

    IF (vMTM_TIPO_REQUISICAO = PKG_MTMD_CONSTANTES.REQ_PERSONALIZADA) THEN
       INSERT INTO TB_MTMD_REQUISICAO_ITEM_KIT
        (MTMD_REQ_ID,
         CAD_MTMD_ID_REF,
         MTMD_REQITEM_QTD_SOLICITADA)
        VALUES
        (pMTMD_REQ_ID,
         pCAD_MTMD_ID,
         pMTMD_REQITEM_QTD_SOLICITADA);
    END IF;

    INSERT INTO TB_MTMD_REQUISICAO_ITEM
    (
       MTMD_REQ_ID,
       CAD_MTMD_ID,
       MTMD_REQITEM_QTD_SOLICITADA,
       MTMD_REQITEM_QTD_FORNECIDA,
       MTMD_ID_ORIGINAL,
       CAD_MTMD_PRESCRICAO_ID,
       CAD_MTMD_KIT_ID_ITEM,
       MTMD_QTD_KIT_MULTIPLICA,
       ATD_MPM_ID,
       ATD_PME_ID,
       MTMD_REQITEM_CANCEL_JUST,
       MTMD_REQ_VIA,
       MTMD_FL_GELADEIRA
    )
    VALUES
    (
      pMTMD_REQ_ID,
      pCAD_MTMD_ID,
      pMTMD_REQITEM_QTD_SOLICITADA,
      pMTMD_REQITEM_QTD_FORNECIDA,
      pMTMD_ID_ORIGINAL,
      pCAD_MTMD_PRESCRICAO_ID,
      pCAD_MTMD_KIT_ID_ITEM,
      pMTMD_QTD_KIT_MULTIPLICA,
      pATD_MPM_ID,
      pATD_PME_ID,
      pMTMD_REQITEM_CANCEL_JUST,
      pMTMD_REQ_VIA,
      pMTMD_FL_GELADEIRA
    );

  end PRC_MTMD_REQUISICAO_ITEM_I;