
  --PRC_ASS_PMM_PLANO_MATMED_I
  create or replace procedure PRC_ASS_PMM_PLANO_MATMED_I
  (
     pCAD_CNV_ID_CONVENIO IN TB_ASS_PMM_PLANO_MATMED.CAD_CNV_ID_CONVENIO%type,
     pCAD_PLA_ID_PLANO IN TB_ASS_PMM_PLANO_MATMED.CAD_PLA_ID_PLANO%type,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_PMM_PLANO_MATMED.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pCAD_MTMD_ID IN TB_ASS_PMM_PLANO_MATMED.CAD_MTMD_ID%type,
     pASS_PMM_FL_EXIGE_GUIA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_EXIGE_GUIA%type,
     pASS_PMM_FL_EXIGE_SENHA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_EXIGE_SENHA%type,
     pASS_PMM_FL_AUTORIZATEL IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZATEL%type,
     pASS_PMM_FL_AUTORIZAFAX IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAFAX%type,
     pASS_PMM_FL_AUTORIZAPES IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAPES%type,
     pASS_PMM_FL_AUTORIZAWEB IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAWEB%type,
     pASS_PMM_FL_COBERTURA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_COBERTURA%type,
     pASS_PMM_FL_STATUS IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_STATUS%type,
     pSEG_USU_ID_USUARIO IN TB_ASS_PMM_PLANO_MATMED.SEG_USU_ID_USUARIO%type,
     pASS_PMM_DT_ULTIMA_ATUALIZACAO IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_DT_ULTIMA_ATUALIZACAO%type  
  ) 
  is
  /********************************************************************
  *    Procedure: PRC_ASS_PMM_PLANO_MATMED_I
  * 
  *    Data Criacao:   data da  criação   Por: Nome do Analista
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/  
    
  begin
      
    INSERT INTO TB_ASS_PMM_PLANO_MATMED
    (
       CAD_CNV_ID_CONVENIO,
       CAD_PLA_ID_PLANO,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_MTMD_ID,
       ASS_PMM_FL_EXIGE_GUIA,
       ASS_PMM_FL_EXIGE_SENHA,
       ASS_PMM_FL_AUTORIZATEL,
       ASS_PMM_FL_AUTORIZAFAX,
       ASS_PMM_FL_AUTORIZAPES,
       ASS_PMM_FL_AUTORIZAWEB,
       ASS_PMM_FL_COBERTURA,
       ASS_PMM_FL_STATUS,
       SEG_USU_ID_USUARIO,
       ASS_PMM_DT_ULTIMA_ATUALIZACAO
    )
    VALUES
    (
       pCAD_CNV_ID_CONVENIO,
       pCAD_PLA_ID_PLANO,
       pCAD_LAT_ID_LOCAL_ATENDIMENTO,
       pCAD_MTMD_ID,
       pASS_PMM_FL_EXIGE_GUIA,
       pASS_PMM_FL_EXIGE_SENHA,
       pASS_PMM_FL_AUTORIZATEL,
       pASS_PMM_FL_AUTORIZAFAX,
       pASS_PMM_FL_AUTORIZAPES,
       pASS_PMM_FL_AUTORIZAWEB,
       pASS_PMM_FL_COBERTURA,
       pASS_PMM_FL_STATUS,
       pSEG_USU_ID_USUARIO,
       pASS_PMM_DT_ULTIMA_ATUALIZACAO
    );
  
  end PRC_ASS_PMM_PLANO_MATMED_I;

