CREATE OR REPLACE PROCEDURE PRC_MTMD_MATMED_SETOR_I
   (
     pCAD_LAT_ID_LOCAL_ATENDIMENTO   IN TB_MTMD_MOV_MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pCAD_UNI_ID_UNIDADE             IN TB_MTMD_MOV_MOVIMENTACAO.CAD_UNI_ID_UNIDADE%type,
     pCAD_SET_ID                     IN TB_MTMD_MOV_MOVIMENTACAO.CAD_SET_ID%type,
     pMTMD_ATENDE_PAC_TODOS_SETORES  IN TB_MTMD_MATMED_SETOR.MTMD_ATENDE_PAC_TODOS_SETORES%TYPE,
     pMTMD_IGNORA_ALTA               IN TB_MTMD_MATMED_SETOR.MTMD_IGNORA_ALTA%TYPE,
     pMTMD_CONSOME_CENTRO_CUSTO      IN TB_MTMD_MATMED_SETOR.MTMD_CONSOME_CENTRO_CUSTO%type,
     pMTMD_ATENDE_PAC_TODAS_UNIDADE  IN TB_MTMD_MATMED_SETOR.MTMD_ATENDE_PAC_TODAS_UNIDADES%TYPE,
     pMTMD_CONSOME_DIRETO_PACIENTE   IN TB_MTMD_MATMED_SETOR.MTMD_CONSOME_DIRETO_PACIENTE%TYPE,
     pMTMD_IGNORA_ALTA_HORAS_ATE     IN TB_MTMD_MATMED_SETOR.MTMD_IGNORA_ALTA_HORAS_ATE%TYPE DEFAULT NULL,
     pMTMD_ESTOQUE_UNIFICADO_HAC     IN TB_MTMD_MATMED_SETOR.MTMD_ESTOQUE_UNIFICADO_HAC%TYPE DEFAULT NULL,
     pMTMD_SOLICITA_KIT              IN TB_MTMD_MATMED_SETOR.MTMD_SOLICITA_KIT%TYPE DEFAULT NULL,
     pMTMD_CONTROLA_CONSUMO_PAC      IN TB_MTMD_MATMED_SETOR.MTMD_CONTROLA_CONSUMO_PAC%TYPE DEFAULT NULL,
     pMTMD_CONTROLA_CONS_PAC_DATA      IN TB_MTMD_MATMED_SETOR.MTMD_CONTROLA_CONS_PAC_DATA%TYPE DEFAULT NULL,
     pMTMD_FUN_ID_FUNCIONALIDADE      IN TB_MTMD_MATMED_SETOR.MTMD_FUN_ID_FUNCIONALIDADE%TYPE DEFAULT NULL
   )
   IS
 /***********************************************************************************************
*    Procedure: PRC_MTMD_MATMED_SETOR_I
*
*    Data Criacao:   01/2010         Por: Ricardo Costa
*    Data Alteracao: 14/04/2010       Por: Ricardo Costa
*         Descric?o: Inserido o campo ignora_data_alta
*    Data Alteracao: 27/08/2010   Por: Ricardo Costa
*         Alteracao:  ATUALIZADO MIGRA2
*    Data Alteracao: 27/08/2010   Por: Ricardo Costa
*         Alteracao:  Adicionado campos consumo direto e atende todas unidade
*    Data Alteracao: 05/05/2011   Por: Andre S. Monaco
*         Alteracao:  Adicionado campo MTMD_IGNORA_ALTA_HORAS_ATE
*    Data Alteracao: 19/07/2011   Por: Andre S. Monaco
*         Alteracao:  Adicionado campo MTMD_ESTOQUE_UNIFICADO_HAC
*    Data Alteracao: 30/09/2015   Por: Andre S. Monaco
*         Alteracao:  Adicionado campo MTMD_SOLICITA_KIT
*    Data Alteracao: 4/12/2017   Por: Andre S. Monaco
*         Alteracao:  Adicionado campos MTMD_CONTROLA_CONSUMO_PAC e MTMD_CONTROLA_CONS_PAC_DATA
*
*    Funcao:   Insere ou atualiza informac?es sobre configurac?es do setor
*************************************************************************************************/
BEGIN
   BEGIN
     INSERT INTO TB_MTMD_MATMED_SETOR
     ( CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_UNI_ID_UNIDADE,
       CAD_SET_ID,
       MTMD_ATENDE_PAC_TODOS_SETORES,
       MTMD_IGNORA_ALTA,
       MTMD_CONSOME_CENTRO_CUSTO,
       MTMD_ATENDE_PAC_TODAS_UNIDADES,
       MTMD_CONSOME_DIRETO_PACIENTE,
       MTMD_IGNORA_ALTA_HORAS_ATE,
       MTMD_ESTOQUE_UNIFICADO_HAC,
       MTMD_SOLICITA_KIT,
       MTMD_CONTROLA_CONSUMO_PAC,
       MTMD_CONTROLA_CONS_PAC_DATA,
       MTMD_FUN_ID_FUNCIONALIDADE)
     VALUES
     (pCAD_LAT_ID_LOCAL_ATENDIMENTO,
      pCAD_UNI_ID_UNIDADE,
      pCAD_SET_ID,
      pMTMD_ATENDE_PAC_TODOS_SETORES,
      pMTMD_IGNORA_ALTA,
      pMTMD_CONSOME_CENTRO_CUSTO,
      pMTMD_ATENDE_PAC_TODAS_UNIDADE,
      pMTMD_CONSOME_DIRETO_PACIENTE,
      pMTMD_IGNORA_ALTA_HORAS_ATE,
      pMTMD_ESTOQUE_UNIFICADO_HAC,
      pMTMD_SOLICITA_KIT,
      pMTMD_CONTROLA_CONSUMO_PAC,
      pMTMD_CONTROLA_CONS_PAC_DATA,
      pMTMD_FUN_ID_FUNCIONALIDADE);
   EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
      UPDATE TB_MTMD_MATMED_SETOR SET
      MTMD_ATENDE_PAC_TODOS_SETORES  = pMTMD_ATENDE_PAC_TODOS_SETORES,
      MTMD_IGNORA_ALTA               = pMTMD_IGNORA_ALTA,
      MTMD_CONSOME_CENTRO_CUSTO      = pMTMD_CONSOME_CENTRO_CUSTO,
      MTMD_ATENDE_PAC_TODAS_UNIDADES = pMTMD_ATENDE_PAC_TODAS_UNIDADE,
      --MTMD_CONSOME_DIRETO_PACIENTE   = pMTMD_CONSOME_DIRETO_PACIENTE,
      MTMD_IGNORA_ALTA_HORAS_ATE     = pMTMD_IGNORA_ALTA_HORAS_ATE,
      MTMD_ESTOQUE_UNIFICADO_HAC     = pMTMD_ESTOQUE_UNIFICADO_HAC,
      MTMD_SOLICITA_KIT              = pMTMD_SOLICITA_KIT,
      MTMD_CONTROLA_CONSUMO_PAC      = pMTMD_CONTROLA_CONSUMO_PAC,
      MTMD_CONTROLA_CONS_PAC_DATA    = pMTMD_CONTROLA_CONS_PAC_DATA,
      MTMD_FUN_ID_FUNCIONALIDADE     = pMTMD_FUN_ID_FUNCIONALIDADE
      WHERE CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
      AND   CAD_UNI_ID_UNIDADE           = pCAD_UNI_ID_UNIDADE
      AND   CAD_SET_ID                   = pCAD_SET_ID;
   END;
END PRC_MTMD_MATMED_SETOR_I;