CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_ACUM_RECEITA"
(
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
    pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_MES_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_COMPET%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_COMPET%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_A IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor--,
    --TESTE OU LONG
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_ACUM_RECEITA
*
*    Data Alteracao: 04/09/2013  Por: Pedro
*    Alterac?o: utilizar campos da cci
*
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
 -- V_WHERE2  varchar2(3000);
  V_SELECT  varchar2(15000);
  begin
    V_WHERE := NULL;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO;   END IF;
    IF pCAD_SET_ID IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO; END IF;
    IF pCAD_PLA_ID_PLANO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.cad_pla_id_plano = ' || pCAD_PLA_ID_PLANO; END IF;
    IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT; END IF;
    IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT; END IF;
    IF pFAT_CCP_MES_COMPET IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.FAT_CCP_MES_COMPET = ' || pFAT_CCP_MES_COMPET; END IF;
    IF pFAT_CCP_ANO_COMPET IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.FAT_CCP_ANO_COMPET = ' || pFAT_CCP_ANO_COMPET; END IF;
    IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.TIS_CBO_CD_CBOS = ' ||CHR(39)|| pTIS_CBO_CD_CBOS ||CHR(39); END IF;
    IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.TIS_TAT_CD_TPATENDIMENTO = ' ||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO ||CHR(39);    END IF;
   V_SELECT := 
   '
 SELECT    NVL(SUM(cci.fat_cci_vl_faturado),0) TOTAL, UNI.CAD_UNI_DS_UNIDADE,UNI.CAD_UNI_DS_RESUMIDA, CAC1.CAD_CAC_DS_CLASSCONTABIL
      FROM    TB_FAT_CCP_CONTA_CONS_PARC CCP              
      JOIN    TB_ATD_ATE_ATENDIMENTO       ATE
      ON      ATE.ATD_ATE_ID             = CCP.ATD_ATE_ID 
      JOIN    TB_FAT_CCI_CONTA_CONSU_ITEM CCI
      ON      CCI.ATD_ATE_ID             = CCP.ATD_ATE_ID
      AND     CCI.CAD_PAC_ID_PACIENTE    = CCP.CAD_PAC_ID_PACIENTE
      AND     CCI.FAT_COC_ID             = CCP.FAT_COC_ID
      AND     CCI.FAT_CCP_ID             = CCP.FAT_CCP_ID     
      JOIN    TB_CAD_CAC_CLASSIF_CONTAB    CAC1
      ON      CAC1.CAD_CAC_ID_CLASSCONTABIL = CCI.CAD_CAC_ID_CLASSCONTABIL
      JOIN    TB_CAD_UNI_UNIDADE           UNI
      ON      UNI.CAD_UNI_ID_UNIDADE     = CCI.CAD_UNI_ID_UNIDADE
      WHERE   (CCP.FAT_CCP_FL_FATURADA = '||chr(39)||'S'||chr(39)||')
      AND     (CCP.FAT_CCP_FL_STATUS   = '||chr(39)||'A'||chr(39)||')
      AND     (CCP.FAT_NOF_ID IS NOT NULL)
      AND     (CCI.FAT_CCI_FL_STATUS   = '||chr(39)||'A'||chr(39)||')
      ' || V_WHERE || '
       AND    (' ||chr(39)|| pATD_ATE_TP_PACIENTE_I ||chr(39)|| ' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = ' ||chr(39)|| 'I' ||chr(39)|| '
        OR ' ||chr(39)|| pATD_ATE_TP_PACIENTE_E ||chr(39)|| ' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = ' ||chr(39)|| 'E' ||chr(39)|| '
        OR ' ||chr(39)|| pATD_ATE_TP_PACIENTE_A ||chr(39)|| ' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = ' ||chr(39)|| 'A' ||chr(39)|| '
        OR ' ||chr(39)|| pATD_ATE_TP_PACIENTE_U ||chr(39)|| ' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = ' ||chr(39)|| 'U' ||chr(39)|| ')
  AND    (' ||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)|| ' IS not NULL and CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'ACS'||chr(39)||'
       OR ' ||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'PA'||chr(39)||'
       OR ' ||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'SP'||chr(39)||'
       OR ' ||chr(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'NP'||chr(39)||'
       OR ' ||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'FU'||chr(39)||')
   GROUP BY UNI.CAD_UNI_DS_UNIDADE, UNI.CAD_UNI_DS_RESUMIDA, CAC1.CAD_CAC_DS_CLASSCONTABIL  '
   ;
  OPEN v_cursor FOR
   V_SELECT ;
    io_cursor := v_cursor;
END PRC_FAT_REL_ACUM_RECEITA;
 