create or replace procedure PRC_ASS_CPE_VIGENTES_L
  (    
     pCAD_CNV_ID_CONVENIO IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA_DES IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA_ORI IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
     pCAD_PRD_ID_ORI IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
     pCAD_PRD_ID_DES IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
     pCAD_PRD_CD_CODIGO_ORI IN TB_CAD_PRD_PRODUTO.CAD_PRD_CD_CODIGO%TYPE DEFAULT NULL,
     pCAD_PRD_CD_CODIGO_DES IN TB_CAD_PRD_PRODUTO.CAD_PRD_CD_CODIGO%TYPE DEFAULT NULL,
     
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ASS_CPE_VIGENTES_L
  *
  *    Data Criacao:  07/12/2009   Por: PEDRO
  *    Data Alteracao:  data da alteraÃ§Ã£o  Por: Nome do Analista
  *
  *    Funcao: DescriÃ§Ã£o da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT
         CPE.ASS_CPE_ID,
         CPE.CAD_CNV_ID_CONVENIO,
         CPE.CAD_LAT_ID_LOCAL_ATENDIMENTO,
         CPE.CAD_PRD_ID_ORIGEM,
         CPE.CAD_PRD_ID_DESTINO,
         CPE.CAD_CPE_DT_INICIO_VIGENCIA,
         CPE.CAD_CPE_DT_FIM_VIGENCIA,     
         PRD_ORI.CAD_PRD_DS_DESCRICAO CAD_PRD_DS_DESCRICAO_ORIGEM,
         PRD_DES.CAD_PRD_DS_DESCRICAO CAD_PRD_DS_DESCRICAO_DESTINO
    FROM TB_ASS_CPE_CONV_PROD_EQUIVALE CPE
    JOIN TB_CAD_PRD_PRODUTO            PRD_ORI
    ON   PRD_ORI.CAD_PRD_ID          = CPE.CAD_PRD_ID_ORIGEM
    JOIN TB_CAD_PRD_PRODUTO            PRD_DES
    ON   PRD_DES.CAD_PRD_ID          = CPE.CAD_PRD_ID_DESTINO
    JOIN TB_TIS_MED_TABELAMEDICA       MED_ORI
    ON   MED_ORI.TIS_MED_CD_TABELAMEDICA = PRD_ORI.TIS_MED_CD_TABELAMEDICA
    JOIN TB_TIS_MED_TABELAMEDICA       MED_DES
    ON   MED_DES.TIS_MED_CD_TABELAMEDICA = PRD_ORI.TIS_MED_CD_TABELAMEDICA
    
    WHERE        
        (pCAD_CNV_ID_CONVENIO is null OR CPE.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR CPE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND
        (pTIS_MED_CD_TABELAMEDICA_DES IS NULL OR MED_DES.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA_DES) AND 
        (pTIS_MED_CD_TABELAMEDICA_ORI IS NULL OR MED_ORI.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA_ORI) AND
        (pCAD_PRD_ID_ORI IS NULL OR PRD_ORI.CAD_PRD_ID = pCAD_PRD_ID_ORI) AND
        (pCAD_PRD_ID_DES IS NULL OR PRD_DES.CAD_PRD_ID = pCAD_PRD_ID_DES) AND
        (pCAD_PRD_CD_CODIGO_ORI IS NULL OR PRD_ORI.CAD_PRD_CD_CODIGO = pCAD_PRD_CD_CODIGO_ORI) AND
        (pCAD_PRD_CD_CODIGO_DES IS NULL OR PRD_DES.CAD_PRD_CD_CODIGO = pCAD_PRD_CD_CODIGO_DES) AND
        (trunc(CPE.CAD_CPE_DT_INICIO_VIGENCIA) <= SYSDATE) AND
        (CPE.CAD_CPE_DT_FIM_VIGENCIA is null OR (TRUNC(CPE.CAD_CPE_DT_FIM_VIGENCIA) >= SYSDATE))

        ;
    io_cursor := v_cursor;
  end PRC_ASS_CPE_VIGENTES_L;
