CREATE OR REPLACE PROCEDURE PRC_AGS_AGG_PROX_HORARIOS
(
   pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE,
   pAUX_EPP_CD_ESPECPROCED IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE,
   pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
   io_cursor OUT PKG_CURSOR.t_cursor
)
IS
 v_cursor PKG_CURSOR.t_cursor;
BEGIN
OPEN v_cursor FOR
SELECT UNI.CAD_UNI_ID_UNIDADE,
       PES_UNI.CAD_PES_NM_PESSOA,
       LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       AGG.AGS_AGG_HR_AGENDA_GERADA,
       AGG.AGS_AGG_DT_AGENDA_GERADA,
       ESM.CAD_SET_ID,
       SETOR.CAD_SET_DS_SETOR,
       ESM.AGE_SAU_ID,
       SAU.AGE_SAU_NR_SALA || ' / ' || SAU.AGE_SAU_CD_ANDAR AS SALA_ANDAR,
       ESM.AGS_ESM_NR_DIA_SEMANA
  FROM TB_AGS_AGG_AGE_GERADA_SADT AGG
 INNER JOIN TB_AGS_ESM_ESCALA_SADT ESM
  ON ESM.AGS_ESM_ID = AGG.AGS_ESM_ID
 AND AGG.AGS_AGG_FL_STATUS_HORARIO = 'L'
 AND AGG.AGS_AGG_DT_AGENDA_GERADA >= TRUNC(SYSDATE)
 INNER JOIN TB_CAD_UNI_UNIDADE UNI
  ON UNI.CAD_UNI_ID_UNIDADE = ESM.CAD_UNI_ID_UNIDADE
 AND (pCAD_UNI_ID_UNIDADE IS NULL) OR (UNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
 INNER JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
  ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO
 INNER JOIN TB_CAD_PES_PESSOA PES_UNI
  ON PES_UNI.CAD_PES_ID_PESSOA = UNI.CAD_PES_ID_PESSOA
 INNER JOIN TB_ASS_ULP_UNID_LOCAL_PROCED ULP
  ON  ULP.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
 AND ULP.CAD_LAT_ID_LOCAL_ATENDIMENTO = LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO
 AND ULP.AGE_SAU_ID = ESM.AGE_SAU_ID
 AND ULP.CAD_PRD_ID = pCAD_PRD_ID
 AND ULP.AUX_EPP_CD_ESPECPROCED = pAUX_EPP_CD_ESPECPROCED
 INNER JOIN TB_CAD_SET_SETOR SETOR
  ON SETOR.CAD_SET_ID = ESM.CAD_SET_ID
 INNER JOIN TB_AGE_SAU_SALA_UNID_AND SAU
  ON SAU.AGE_SAU_ID = ESM.AGE_SAU_ID
ORDER BY AGG.AGS_AGG_DT_AGENDA_GERADA, AGG.AGS_AGG_HR_AGENDA_GERADA;
 io_cursor := v_cursor;
END PRC_AGS_AGG_PROX_HORARIOS;
