CREATE OR REPLACE PROCEDURE PRC_CAD_PSO_PRO_R_L
  (
     pTIS_CPR_CD_CONSELHOPROF IN TB_CAD_PSO_PROF_SOLICITANTE.TIS_CPR_CD_CONSELHOPROF%type DEFAULT NULL,
     pCAD_PSO_CD_CONSELHO IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_CD_CONSELHO%type DEFAULT NULL,
     pCAD_PSO_SG_UF_CONSELHO IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_SG_UF_CONSELHO%type DEFAULT NULL,
     pCAD_PSO_FL_ATIVO_OK IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_FL_ATIVO_OK%type DEFAULT NULL,
     pCAD_PSO_NM_PROFISSIONAL IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_NM_PROFISSIONAL%type DEFAULT NULL,
     pCAD_PSO_DT_ULTIMA_ATUALIZACAO IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_PSO_PROF_SOLICITANTE.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_CAD_PSO_PRO_R_L
  *
  *    Data Criacao:  8/11/2010   Por: Pedro
  *    Data Alteracao: 3/01/2011   Por: André Souza Monaco
  *         Alteracao: Adição na query do campo ATIVO
  *    Data Alteracao:  27/06/2014   Por: André Souza Monaco
  *         Alteracao: Verificação de ativo na TB_CAD_PRO_PROFISSIONAL
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(2000);
  V_SELECT  varchar2(4000);
begin
  V_WHERE := NULL;
  IF pTIS_CPR_CD_CONSELHOPROF IS NOT NULL THEN
    V_WHERE := V_WHERE ||
               ' AND PSO.TIS_CPR_CD_CONSELHOPROF = ' || CHR(39) || pTIS_CPR_CD_CONSELHOPROF || CHR(39);
  END IF;
  IF pCAD_PSO_CD_CONSELHO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_CD_CONSELHO = ' || CHR(39) || pCAD_PSO_CD_CONSELHO || CHR(39);
  END IF;
  IF pCAD_PSO_SG_UF_CONSELHO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_SG_UF_CONSELHO = ' || CHR(39) || pCAD_PSO_SG_UF_CONSELHO || CHR(39);
  END IF;
  IF pCAD_PSO_FL_ATIVO_OK IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_FL_ATIVO_OK = ' || CHR(39) || pCAD_PSO_FL_ATIVO_OK || CHR(39);
    V_WHERE := V_WHERE || ' AND PRO.CAD_PRO_FL_ATIVO_OK = ' || CHR(39) || pCAD_PSO_FL_ATIVO_OK || CHR(39);
  END IF;
  IF pCAD_PSO_NM_PROFISSIONAL IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_NM_PROFISSIONAL LIKE ' || CHR(39) || pCAD_PSO_NM_PROFISSIONAL || CHR(39);
  END IF;
   IF pCAD_PSO_DT_ULTIMA_ATUALIZACAO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_DT_ULTIMA_ATUALIZACAO = ' || pCAD_PSO_DT_ULTIMA_ATUALIZACAO;
  END IF;
  IF pSEG_USU_ID_USUARIO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO;
  END IF;
    V_SELECT:= '
    SELECT
       PSO.TIS_CPR_CD_CONSELHOPROF,
       PSO.CAD_PSO_CD_CONSELHO,
       PSO.CAD_PSO_SG_UF_CONSELHO,
       PSO.CAD_PSO_FL_ATIVO_OK,
       PSO.CAD_PSO_NM_PROFISSIONAL,
       PSO.CAD_PSO_DT_ULTIMA_ATUALIZACAO,
       PSO.SEG_USU_ID_USUARIO,
       DECODE(PRO.CAD_PRO_FL_ATIVO_OK, ''S'',  '||CHR(39)||'Corpo Clinico HAC'||CHR(39)||',  '||CHR(39)||''||CHR(39)||') CCHAC
    FROM TB_CAD_PSO_PROF_SOLICITANTE PSO,
         TB_CAD_PRO_PROFISSIONAL PRO
    WHERE 
         PSO.TIS_CPR_CD_CONSELHOPROF = PRO.TIS_CPR_CD_CONSELHOPROF (+) AND
         PSO.CAD_PSO_CD_CONSELHO = PRO.CAD_PRO_NR_CONSELHO (+) AND
         PSO.CAD_PSO_SG_UF_CONSELHO = PRO.CAD_PRO_SG_UF_CONSELHO (+) ' 
         || V_WHERE 
      ;
   OPEN v_cursor FOR
  V_SELECT;
  io_cursor := v_cursor;
  end PRC_CAD_PSO_PRO_R_L;
 
