CREATE OR REPLACE PROCEDURE PRC_CAD_PSO_PCB_R_L
 (
    pTIS_CPR_CD_CONSELHOPROF IN TB_CAD_PSO_PROF_SOLICITANTE.TIS_CPR_CD_CONSELHOPROF%TYPE DEFAULT NULL,
    pCAD_PSO_CD_CONSELHO IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_CD_CONSELHO%TYPE DEFAULT NULL,
    pCAD_PSO_SG_UF_CONSELHO IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_SG_UF_CONSELHO%TYPE DEFAULT NULL,
     pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%type DEFAULT NULL,
     pCAD_PSO_NM_PROFISSIONAL IN TB_CAD_PSO_PROF_SOLICITANTE.CAD_PSO_NM_PROFISSIONAL%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_CAD_PSO_PCB_R_L
  *
  *    Data Criacao:  8/11/2010   Por: PEDRO
  *    Alterac?o: (PSO.CAD_PSO_FL_ATIVO_OK IN (' || CHR(39) ||'A' || CHR(39) ||',' || CHR(39) ||'S' || CHR(39) ||') AND
  *
  *    Funcao: Obtem ou Lista Medicos Solicitantes por Especialidade
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(2000);
  V_SELECT  varchar2(4000);
begin
  V_WHERE := NULL;
  IF pTIS_CPR_CD_CONSELHOPROF IS NOT NULL THEN
    V_WHERE := V_WHERE ||
               ' AND PSO.TIS_CPR_CD_CONSELHOPROF = ' || CHR(39) || pTIS_CPR_CD_CONSELHOPROF || CHR(39);
  END IF;
  IF pCAD_PSO_CD_CONSELHO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_CD_CONSELHO = ' || CHR(39) || pCAD_PSO_CD_CONSELHO || CHR(39);
  END IF;
  IF pCAD_PSO_SG_UF_CONSELHO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_SG_UF_CONSELHO = ' || CHR(39) || pCAD_PSO_SG_UF_CONSELHO || CHR(39);
  END IF;
  IF pTIS_CBO_CD_CBOS IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PCB.TIS_CBO_CD_CBOS = ' || CHR(39) || pTIS_CBO_CD_CBOS || CHR(39);
  END IF;
  IF pCAD_PSO_NM_PROFISSIONAL IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PSO.CAD_PSO_NM_PROFISSIONAL LIKE ' || CHR(39) || pCAD_PSO_NM_PROFISSIONAL || CHR(39);
  END IF;


    V_SELECT:= '
    SELECT
          PSO.TIS_CPR_CD_CONSELHOPROF,
          PSO.CAD_PSO_CD_CONSELHO,
          PSO.CAD_PSO_SG_UF_CONSELHO,
          PSO.CAD_PSO_FL_ATIVO_OK,
          PSO.CAD_PSO_NM_PROFISSIONAL,
          PSO.CAD_PSO_DT_ULTIMA_ATUALIZACAO,
          PSO.SEG_USU_ID_USUARIO
    FROM   TB_CAD_PSO_PROF_SOLICITANTE PSO,
           TB_CAD_PRO_PROFISSIONAL PRO,
           TB_ASS_PCB_PROFISSIONAL_CBOS PCB
    WHERE
           (PSO.CAD_PSO_FL_ATIVO_OK IN (' || CHR(39) ||'A' || CHR(39) ||',' || CHR(39) ||'S' || CHR(39) ||')) AND
            PSO.TIS_CPR_CD_CONSELHOPROF = PRO.TIS_CPR_CD_CONSELHOPROF (+) AND
            PSO.CAD_PSO_CD_CONSELHO = PRO.CAD_PRO_NR_CONSELHO (+) AND
            PSO.CAD_PSO_SG_UF_CONSELHO = PRO.CAD_PRO_SG_UF_CONSELHO (+) AND
            PCB.CAD_PRO_ID_PROFISSIONAL = PRO.CAD_PRO_ID_PROFISSIONAL '
             || V_WHERE
      ;
   OPEN v_cursor FOR
  V_SELECT;
  io_cursor := v_cursor;
  end PRC_CAD_PSO_PCB_R_L;
/
