CREATE OR REPLACE PROCEDURE "PRC_ASS_RPG_REGRA_FECHAR_VIG"(PCAD_REP_DT_FIM_VIGENCIA       IN TB_ASS_RPG_REGRA_PAGTO.CAD_REP_DT_FIM_VIGENCIA%TYPE,
                                                           PCAD_CLC_ID                    IN TB_ASS_CPR_CLINICA_PROF.CAD_CLC_ID%TYPE,
                                                           PCAD_PRO_ID_PROFISSIONAL       IN TB_ASS_CPR_CLINICA_PROF.CAD_PRO_ID_PROFISSIONAL%TYPE,
                                                           PCAD_REP_DT_ULTIMA_ATUALIZACAO IN TB_ASS_RPG_REGRA_PAGTO.CAD_REP_DT_ULTIMA_ATUALIZACAO%TYPE,
                                                           PSEG_USU_ID_USUARIO            IN TB_ASS_RPG_REGRA_PAGTO.SEG_USU_ID_USUARIO%TYPE) IS

BEGIN
  UPDATE (SELECT RPG.*
            FROM TB_ASS_RPG_REGRA_PAGTO RPG
           INNER JOIN TB_ASS_CPR_CLINICA_PROF CPR
              ON CPR.ASS_CPR_ID = RPG.ASS_CPR_ID
           WHERE CPR.CAD_CLC_ID = PCAD_CLC_ID
             AND CPR.CAD_PRO_ID_PROFISSIONAL = PCAD_PRO_ID_PROFISSIONAL
             AND RPG.CAD_REP_DT_FIM_VIGENCIA IS NULL) RPG
     SET RPG.CAD_REP_DT_FIM_VIGENCIA       = PCAD_REP_DT_FIM_VIGENCIA,
         RPG.CAD_REP_DT_ULTIMA_ATUALIZACAO = PCAD_REP_DT_ULTIMA_ATUALIZACAO,
         RPG.SEG_USU_ID_USUARIO            = PSEG_USU_ID_USUARIO;
END PRC_ASS_RPG_REGRA_FECHAR_VIG;
/
