create or replace procedure PRC_ASS_CTU_TCP_L(
   pCAD_CNV_ID_CONVENIO IN TB_ASS_CTU_CNV_TAB_UTILIZA.CAD_CNV_ID_CONVENIO%type,
   pCAD_PRD_CD_CODIGO IN TB_CAD_PRD_PRODUTO.CAD_PRD_CD_CODIGO%type DEFAULT NULL,
   pFAT_TCO_ID IN TB_FAT_TCP_TP_COMANDA_PROD.FAT_TCO_ID%type,
   io_cursor OUT PKG_CURSOR.t_cursor
)
is
v_cursor PKG_CURSOR.t_cursor;
begin

OPEN v_cursor FOR

   SELECT PRD.CAD_PRD_ID,
          PRD.CAD_PRD_CD_CODIGO,
          PRD.CAD_PRD_DS_DESCRICAO,
          FAT_TCO_ID,
          CAD_CNV_ID_CONVENIO
     FROM TB_ASS_CTU_CNV_TAB_UTILIZA CTU,
          TB_CAD_PRD_PRODUTO         PRD,
          TB_FAT_TCP_TP_COMANDA_PROD TCP
    WHERE CTU.TIS_MED_CD_TABELAMEDICA = PRD.TIS_MED_CD_TABELAMEDICA
      AND PRD.CAD_TAP_TP_ATRIBUTO = CTU.CAD_TAP_TP_ATRIBUTO
      AND PRD.CAD_PRD_ID = TCP.CAD_PRD_ID
      AND ((CTU.ASS_CTU_DT_INICIO_VIGENCIA <= TRUNC(sysdate) AND CTU.ASS_CTU_DT_FIM_VIGENCIA IS NULL)
          or (CTU.ASS_CTU_DT_INICIO_VIGENCIA  <= TRUNC(sysdate) AND CTU.ASS_CTU_DT_FIM_VIGENCIA >= TRUNC(sysdate)))
      AND TCP.FAT_TCP_FL_STATUS = 'A'
      AND PRD.CAD_PRD_FL_STATUS = 'A'
      AND CTU.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
      AND TCP.FAT_TCO_ID = pFAT_TCO_ID;
io_cursor := v_cursor;

end PRC_ASS_CTU_TCP_L;
