create or replace procedure PRC_INT_REL_PAC_PROF_ADM
  (
pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pFAIXA_ETARIA_INI varchar2 default null,
pFAIXA_ETARIA_FIM varchar2 default null,
pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
pCAD_SET_NR_ANDAR IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pCAD_QLE_TP_QUARTO_LEITO IN TB_CAD_QLE_QUARTO_LEITO.CAD_QLE_TP_QUARTO_LEITO%TYPE DEFAULT NULL,
pTIS_TIN_CD_INTER IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
pTIS_TRI_CD_TP_REGINT IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
pTIS_TAC_CD_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%TYPE DEFAULT NULL,
pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
pCAD_PES_TP_SEXO IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
pCAD_UNI_ID_UNID_PROC    IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNID_PROC%TYPE DEFAULT NULL,
pCAD_CGC_ID_G IN TB_CAD_CNV_CONVENIO.CAD_CGC_ID%TYPE DEFAULT NULL,
pCAD_CGC_ID_E IN TB_CAD_CNV_CONVENIO.CAD_CGC_ID%TYPE DEFAULT NULL,
   io_cursor              OUT PKG_CURSOR.t_cursor) is
  /********************************************************************
  *    Procedure: PRC_INT_REL_PAC_PROF_ADM
  *
  *    Data Criacao:  7/10/2010      Por: Pedro
  *    Data Alteracao:03/11/2011   Por:Eduardo Hyppolito
  *
  *    Alterai??i??o: Campo Instituto Geriatria (LEFT JOIN BENEFICIARIO)
  *
  *    Funcao: Popula o Relatorio de Pacientes Internados por Prof da Admiss?o com varias possibilidades de filtro
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
begin
  OPEN v_cursor FOR
 SELECT DISTINCT
               IML_QLE.ATD_IML_DT_ENTRADA,
               IML_QLE.ATD_IML_HR_ENTRADA,
               DECODE(IML_QLE.CAD_QLE_TP_QUARTO_LEITO,'I','INTERNO','E','EXTRA') CAD_QLE_TP_QUARTO_LEITO,
               IML_QLE.CAD_QLE_NR_QUARTO,
               IML_QLE.CAD_QLE_NR_LEITO,
               TAC.TIS_TAC_DS_TIPO_ACOMODACAO,
               ATD.ATD_ATE_ID,
               DECODE(ATD.ATD_ATE_FL_CARATER_SOLIC,'U','URGENCIA','E','ELETIVA') ATD_ATE_FL_CARATER_SOLIC,
         --      PES_UNI.CAD_PES_NM_PESSOA UNIDADE,
               UNI.CAD_UNI_DS_UNIDADE UNIDADE,
               UNI.CAD_UNI_ID_UNIDADE,
               LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
               SETOR.CAD_SET_DS_SETOR,
               PAC.CAD_PAC_CD_CREDENCIAL,
               PAC.CAD_PAC_NR_PRONTUARIO,
               PES.CAD_PES_NM_PESSOA PACIENTE,
               PES.CAD_PES_DT_NASCIMENTO,
               PES.CAD_PES_TP_SEXO,
               MUN.AUX_MUN_NM_MUNICIPIO,
               CBOS.TIS_CBO_DS_CBOS_HAC,
               DECODE(AIC.ATD_AIC_TP_SITUACAO_PAC,'I','INTERNADOS','A','SAIDAS') ATD_AIC_TP_SITUACAO_PAC,
               DECODE(ATD_ATE_TP_PACIENTE,'I','INTERNO','E','EXTERNO') ATD_ATE_TP_PACIENTE,
               INA.ATD_INA_DT_ALTA_ADM ATD_INA_DT_ALTA_CLINICA,
               CNV.CAD_CNV_CD_HAC_PRESTADOR,
               PLA.CAD_PLA_CD_TIPOPLANO,
               PLA.CAD_PLA_CD_PLANO_HAC,
               ATD.ATD_ATE_DT_ATENDIMENTO,
               ATD.ATD_ATE_HR_ATENDIMENTO,
            --   PES_PRO.CAD_PES_NM_PESSOA PROFISSIONAL,
               PRO.CAD_PRO_NM_NOME PROFISSIONAL,
               PRO.CAD_PRO_NR_CONSELHO,
               PRO.CAD_PRO_SG_UF_CONSELHO,
               FNC_INT_ULTIMO_CID(ATD.ATD_ATE_ID) CAD_CID_DS_CID10,
               TIN.TIS_TIN_DS_INTERNACAO,
               TRI.TIS_TRI_DS_TP_REGINTERNACAO,
               PRD.CAD_PRD_NM_MNEMONICO,
               PRD.CAD_PRD_DS_DESCRICAO,
               IGE_BNF.GER,
               SETOR.CAD_SET_NR_ANDAR,
               FLOOR(FLOOR(MONTHS_BETWEEN(DECODE(INA.ATD_INA_DT_ALTA_ADM,NULL,ATD.ATD_ATE_DT_ATENDIMENTO,INA.ATD_INA_DT_ALTA_ADM), PES.CAD_PES_DT_NASCIMENTO)) / 12) idade,
               CASE WHEN AIC.ATD_AIC_TP_SITUACAO_PAC = 'A' AND INA.ATD_INA_DT_ALTA_ADM IS NOT NULL THEN
                         nvl(Round(INA.ATD_INA_DT_ALTA_ADM - ATD.ATD_ATE_DT_ATENDIMENTO),0)
                    WHEN AIC.ATD_AIC_TP_SITUACAO_PAC = 'I' THEN
                         nvl(Round(sysdate-ATD.ATD_ATE_DT_ATENDIMENTO),0)
                         ELSE  0
                END PERMANENCIA
  FROM
                TB_ATD_ATE_ATENDIMENTO    ATD
  JOIN          TB_ASS_PAT_PACIEATEND     PAT
  ON            PAT.ATD_ATE_ID          = ATD.ATD_ATE_ID
  JOIN          TB_CAD_PAC_PACIENTE       PAC
  ON            PAC.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(pat.atd_ate_id)
  JOIN          TB_CAD_PES_PESSOA         PES
  ON            PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
  JOIN          TB_CAD_CNV_CONVENIO       CNV
  ON            CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
  JOIN          TB_CAD_PLA_PLANO          PLA
  ON            PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
  LEFT JOIN     TB_ATD_IML_INT_MOV_LEITO  IML
  ON            IML.ATD_ATE_ID          = ATD.ATD_ATE_ID
  JOIN          TB_ATD_AIC_ATE_INT_COMPL  AIC
  ON            AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
  LEFT JOIN    (SELECT BNF_SIT.DESSITBEN, BNF.DATINGCONBEN, BNF.DATSITBEN, BNF.DATALTBEN,PAC.CAD_PAC_ID_PACIENTE,
  DECODE       (FNC_VERIFICA_INSGER(BNF.CODCON, BNF.CODEST, BNF.CODBEN, BNF.CODSEQBEN),0,'',1,'I.GER',2,'I.GER',4,'A.ALTA') GER
  FROM          TB_CAD_PAC_PACIENTE       PAC
  JOIN          TB_CAD_PLA_PLANO          PLA
  ON            PAC.CAD_PLA_ID_PLANO    = PLA.CAD_PLA_ID_PLANO
  JOIN          BNF_BENEFICIARIO          BNF
  ON            TO_CHAR(BNF.CODCON)     = TO_CHAR(PLA.CAD_PLA_CD_PLANO_HAC)
  AND           BNF.CODEST              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,0,3))
  AND           BNF.CODBEN              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,4,7))
  AND           BNF.CODSEQBEN           = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,11,2))
  JOIN          BNF_SITUACAO_BENEF        BNF_SIT
  ON            BNF_SIT.CODSITBEN       = BNF.CODSITBEN

  WHERE         pac.CAD_CNV_ID_CONVENIO = 281

  ) IGE_BNF
  ON           IGE_BNF.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
  LEFT JOIN  (  SELECT     QLE.CAD_QLE_ID, QLE.CAD_SET_ID , QLE.CAD_QLE_NR_QUARTO, QLE.CAD_QLE_NR_LEITO,
                          IML.ATD_ATE_ID, QLE.TIS_TAC_CD_TIPO_ACOMODACAO, QLE.CAD_QLE_TP_QUARTO_LEITO ,
                          IML.ATD_IML_DT_ENTRADA, IML.ATD_IML_HR_ENTRADA
                 FROM      TB_ATD_IML_INT_MOV_LEITO IML
                 LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE
                 ON        QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
                 JOIN      TB_ATD_ATE_ATENDIMENTO ATD2
                 ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                 WHERE     IML.ATD_IML_DT_SAIDA IS NULL AND IML.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML.ATD_IML_FL_STATUS = 'A'
                 UNION
                 SELECT NULL CAD_QLE_ID, IMS.CAD_SET_ID_SETOR, NULL CAD_QLE_NR_QUARTO, NULL CAD_QLE_NR_LEITO,
                        IMS.ATD_ATE_ID, NULL TIS_TAC_CD_TIPO_ACOMODACAO, NULL CAD_QLE_TP_QUARTO_LEITO,
                        IMS.ATD_IMS_DT_ENTRADA ATD_IML_DT_ENTRADA, IMS.ATD_IMS_HR_ENTRADA ATD_IML_HR_ENTRADA
                 FROM      TB_ATD_IMS_INT_MOV_SETOR IMS
                 JOIN      TB_ATD_ATE_ATENDIMENTO ATD2
                 ON        ATD2.ATD_ATE_ID = IMS.ATD_ATE_ID
                 WHERE IMS.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IMS.ATD_IMS_DT_SAIDA IS NULL AND IMS.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IMS.ATD_IMS_FL_STATUS = 'A'
                 AND NOT IMS.ATD_ATE_ID IN (SELECT IML.ATD_ATE_ID
                                               FROM      TB_ATD_IML_INT_MOV_LEITO IML
                                               LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE
                                               ON        QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
                                               JOIN      TB_ATD_ATE_ATENDIMENTO ATD2
                                               ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                                               WHERE     IML.ATD_IML_DT_SAIDA IS NULL AND IML.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML.ATD_IML_FL_STATUS = 'A')
              )  IML_QLE
  ON IML_QLE.ATD_ATE_ID = ATD.ATD_ATE_ID
  LEFT JOIN     TB_ATD_INA_INT_ALTA         INA
  ON            INA.ATD_ATE_ID            = ATD.ATD_ATE_ID
  JOIN     TB_TIS_CBO_CBOS             CBOS
  ON            CBOS.TIS_CBO_CD_CBOS      = ATD.TIS_CBO_CD_CBOS
  LEFT JOIN     TB_TIS_TAC_TIPO_ACOMODACAO  TAC
  ON            TAC.TIS_TAC_CD_TIPO_ACOMODACAO = IML_QLE.TIS_TAC_CD_TIPO_ACOMODACAO
  JOIN          TB_CAD_UNI_UNIDADE          UNI
  ON            UNI.CAD_UNI_ID_UNIDADE    = ATD.CAD_UNI_ID_UNIDADE
  JOIN          TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
  ON            LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO
  LEFT JOIN     TB_CAD_SET_SETOR            SETOR
  ON            SETOR.CAD_SET_ID          = IML_QLE.CAD_SET_ID
  JOIN          TB_CAD_PRO_PROFISSIONAL     PRO
  ON            PRO.CAD_PRO_ID_PROFISSIONAL = ATD.CAD_PRO_ID_PROF_EXEC
  LEFT JOIN     TB_TIS_TIN_TP_INTERNACAO    TIN
  ON            TIN.TIS_TIN_CD_INTERNACAO = AIC.TIS_TIN_CD_INTERNACAO
  LEFT JOIN     TB_TIS_TRI_TP_REGINTERNACAO TRI
  ON            TRI.TIS_TRI_CD_TP_REGINTERNACAO = AIC.TIS_TRI_CD_REGINTENNACAO
  LEFT JOIN     TB_CAD_PRD_PRODUTO          PRD
  ON            PRD.CAD_PRD_ID            = AIC.CAD_PRD_ID
 -- LEFT JOIN     TB_ASS_PEE_PESSOA_ENDERECO  PEE  ON            PEE.CAD_PES_ID_PESSOA     = PES.CAD_PES_ID_PESSOA
  LEFT JOIN     TB_CAD_END_ENDERECO         END
  ON            END.CAD_PES_ID_PESSOA   = pes.CAD_PES_ID_PESSOA AND     END.AUX_TTE_CD_TP_TEL_END = '1'
  LEFT JOIN     TB_AUX_MUN_MUNICIPIO        MUN
  ON            MUN.AUX_MUN_CD_IBGE       = END.AUX_MUN_CD_IBGE
   WHERE
       (pCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
   AND (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
    AND (pCAD_SET_ID IS NULL OR IML_QLE.CAD_SET_ID = pCAD_SET_ID)
   AND (pATD_ATE_HR_ATENDIMENTO_INI IS NULL OR ATD.ATD_ATE_HR_ATENDIMENTO BETWEEN pATD_ATE_HR_ATENDIMENTO_INI AND pATD_ATE_HR_ATENDIMENTO_FIM)
   AND (pFAIXA_ETARIA_INI IS NULL OR FLOOR(FLOOR(MONTHS_BETWEEN(DECODE(INA.ATD_INA_DT_ALTA_ADM,NULL,ATD.ATD_ATE_DT_ATENDIMENTO,INA.ATD_INA_DT_ALTA_ADM), PES.CAD_PES_DT_NASCIMENTO)) / 12) BETWEEN pFAIXA_ETARIA_INI AND pFAIXA_ETARIA_FIM)
   AND (pTIS_CBO_CD_CBOS IS NULL OR ATD.TIS_CBO_CD_CBOS = pTIS_CBO_CD_CBOS)
   AND (pCAD_PRO_ID_PROF_EXEC IS NULL OR ATD.CAD_PRO_ID_PROF_EXEC = pCAD_PRO_ID_PROF_EXEC)
   AND (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
   AND (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
   AND (ATD.ATD_ATE_FL_STATUS = 'A')
   AND (pCAD_PRD_ID IS NULL OR AIC.CAD_PRD_ID = pCAD_PRD_ID)
   AND (pCAD_PES_TP_SEXO IS NULL OR PES.CAD_PES_TP_SEXO = pCAD_PES_TP_SEXO)
   AND (pTIS_TAC_CD_TIPO_ACOMODACAO IS NULL OR TAC.TIS_TAC_CD_TIPO_ACOMODACAO = pTIS_TAC_CD_TIPO_ACOMODACAO)
   AND (pCAD_QLE_TP_QUARTO_LEITO IS NULL OR IML_QLE.CAD_QLE_TP_QUARTO_LEITO = pCAD_QLE_TP_QUARTO_LEITO)
   AND (pTIS_TIN_CD_INTER IS NULL OR TIN.TIS_TIN_CD_INTERNACAO = pTIS_TIN_CD_INTER)
   AND (pTIS_TRI_CD_TP_REGINT IS NULL OR TRI.TIS_TRI_CD_TP_REGINTERNACAO = pTIS_TRI_CD_TP_REGINT)
   AND (pCAD_CGC_ID_G IS NOT NULL AND CNV.CAD_CGC_ID = 1 OR pCAD_CGC_ID_E IS NOT NULL AND CNV.CAD_CGC_ID = 2)
   AND (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = 'GB'
   OR pCAD_PLA_CD_TIPOPLANO_PL IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PL'
   OR pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PA'
   OR pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'SP'
   OR pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'FU')
   AND (pCAD_UNI_ID_UNID_PROC IS NULL OR ATD.CAD_UNI_ID_UNID_PROC = pCAD_UNI_ID_UNID_PROC)
   AND (PLA.CAD_PLA_CD_TIPOPLANO != 'NP')
   AND (pATD_ATE_FL_CARATER_SOLIC_U IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = 'U'
      OR pATD_ATE_FL_CARATER_SOLIC_E IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = 'E')
   AND (pATD_ATE_TP_PACIENTE_I IS NOT NULL AND ATD.ATD_ATE_TP_PACIENTE = 'I'
      OR pATD_ATE_TP_PACIENTE_E IS NOT NULL AND ATD.ATD_ATE_TP_PACIENTE = 'E')
   AND (ATD.ATD_ATE_DT_ATENDIMENTO >= pATD_ATE_DT_ATENDIMENTO_INI)
   AND (ATD.ATD_ATE_DT_ATENDIMENTO <= pATD_ATE_DT_ATENDIMENTO_FIM)
  -- order by PRO.CAD_PRO_NM_NOME
  ;
  io_cursor := v_cursor;
end PRC_INT_REL_PAC_PROF_ADM;