CREATE OR REPLACE PROCEDURE PRC_ATD_REL_ATD_SEM_CRM
(
    pATD_DT_INICIO IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_DT_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO IN Tb_Tis_Tat_Tp_Atendimento.Tis_Tat_CD_Tpatendimento%TYPE DEFAULT NULL,
         pCAD_CGC_ID IN tb_cad_cnv_convenio.cad_cgc_id%TYPE DEFAULT NULL,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR
)
IS
/********************************************************************
*    PROCEDURE: PRC_ATD_REL_ATD_SEM_CRM
*    DATA ALTERACAO: 28/10/2010  POR: Eduardo Hyppolito
*    ALTERAC?O:
*******************************************************************/
V_CURSOR PKG_CURSOR.T_CURSOR;
BEGIN
  OPEN V_CURSOR FOR
    SELECT  ATE.ATD_ATE_ID,
            ATE.ATD_ATE_DT_ATENDIMENTO,
            PES.CAD_PES_NR_RG,
            PES.CAD_PES_NM_PESSOA,
            TAT.TIS_TAT_DS_TPATENDIMENTO,
            CNV.CAD_CNV_CD_HAC_PRESTADOR
    FROM    TB_ATD_ATE_ATENDIMENTO ATE
    JOIN    TB_ASS_PAT_PACIEATEND PAT ON      PAT.ATD_ATE_ID = ATE.ATD_ATE_ID
    JOIN    TB_CAD_PAC_PACIENTE PAC ON      PAC.CAD_PAC_ID_PACIENTE = PAT.CAD_PAC_ID_PACIENTE
    JOIN    TB_CAD_PES_PESSOA PES ON      PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
    JOIN    TB_TIS_TAT_TP_ATENDIMENTO TAT ON      TAT.TIS_TAT_CD_TPATENDIMENTO = ATE.TIS_TAT_CD_TPATENDIMENTO
    JOIN    TB_CAD_CNV_CONVENIO CNV ON      CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
    -- SEM CRM
    WHERE   ATE.CAD_PRO_ID_PROF_EXEC IS NULL
 --  AND    ATE.ATD_ATE_DT_ATENDIMENTO >= '01-JUN-2010'
   AND    (pCAD_UNI_ID_UNIDADE IS NULL OR ATE.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
   AND    (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
   AND    (pCAD_SET_ID IS NULL OR ATE.CAD_SET_ID = pCAD_SET_ID)
   AND    (pTIS_CBO_CD_CBOS IS NULL OR ATE.TIS_CBO_CD_CBOS = pTIS_CBO_CD_CBOS)
   AND    (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
   AND    (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
   AND    (ATE.ATD_ATE_FL_STATUS = 'A')
   AND    (pATD_DT_INICIO IS NULL OR ATE.ATD_ATE_DT_ATENDIMENTO >= pATD_DT_INICIO)
   AND    (pATD_DT_FIM IS NULL OR ATE.ATD_ATE_DT_ATENDIMENTO <= pATD_DT_FIM)
    AND (pCAD_CGC_ID IS NULL OR CNV.CAD_CGC_ID = pCAD_CGC_ID)
   AND    (ATE.TIS_TAT_CD_TPATENDIMENTO = '4')
   ORDER   BY  ATE.ATD_ATE_DT_ATENDIMENTO DESC;
  IO_CURSOR := V_CURSOR;
END PRC_ATD_REL_ATD_SEM_CRM;
 