create or replace procedure PRC_INT_REL_RESUMO
  (
--pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE,
--pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
--pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
pATD_ATE_HR_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pFAIXA_ETARIA_INI varchar2 default null,
pFAIXA_ETARIA_FIM varchar2 default null,
pPERMANENCIA_INI varchar2 default null,
pPERMANENCIA_FIM varchar2 default null,
pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
pCAD_SET_NR_ANDAR IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pCAD_QLE_TP_QUARTO_LEITO IN TB_CAD_QLE_QUARTO_LEITO.CAD_QLE_TP_QUARTO_LEITO%TYPE DEFAULT NULL,
pTIS_TIN_CD_INTER IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
pTIS_TRI_CD_TP_REGINT IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
pCAD_CID_CD_CID10 IN TB_CAD_CID_CID10.CAD_CID_CD_CID10%TYPE DEFAULT NULL,
pTIS_TAC_CD_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%TYPE DEFAULT NULL,
pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
pCAD_PES_TP_SEXO IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
   io_cursor              OUT PKG_CURSOR.t_cursor) is
  /********************************************************************
  *    Procedure: PRC_INT_REL_RESUMO
  *
  *    Data Criacao:  09/09/2009   Por: pedro
  *    Data Alteracao:           Por:
  *
  *    Funcao: Popula o Relatorio de Evolucao dos Pacientes Internados
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
begin
  OPEN v_cursor FOR
      SELECT --DISTINCT
             /*  uni.cad_uni_id_unidade uni,
               DECODE(IML_qle.CAD_QLE_TP_QUARTO_LEITO,'I','INTERNO','E','EXTRA') CAD_QLE_TP_QUARTO_LEITO,
                decode(pla.cad_pla_cd_tipoplano,
                                        'FU', 'FUNCIONARIO',
                                        'PA', 'PA',
                                        'GB', 'GLOBAL',
                                        'PL', 'PESSOA FISICA',
                                        'SP', 'SERVICOS PRESTADOS') cad_pla_cd_tipoplano,
               IML_qle.CAD_SQL_CD_SIT_QUARTO_LEITO CAD_SQL_CD_SIT_QUARTO_LEITO,
               aic.atd_aic_tp_situacao_pac atd_aic_tp_situacao_pac,
               ATD.ATD_ATE_TP_PACIENTE,
               \*SUM( Count(pac.cad_pac_id_paciente))
                   OVER(PARTITION BY
                   UNI.CAD_UNI_ID_UNIDADE||IML_qle.cad_sql_cd_sit_quarto_leito||IML_qle.CAD_QLE_TP_QUARTO_LEITO
                   ||ATD.ATD_ATE_TP_PACIENTE||PLA.CAD_PLA_CD_TIPOPLANO||aic.atd_aic_tp_situacao_pac) TOTAL_LEITO,*\
               SUM( Count(IML_qle.cad_sql_cd_sit_quarto_leito))
                   OVER(PARTITION BY
                   IML_qle.cad_sql_cd_sit_quarto_leito||IML_qle.CAD_QLE_TP_QUARTO_LEITO) total_sit_tp_quarto,*/
            (select   COUNT(QLE.CAD_QLE_ID) TOTAL_
                FROM     TB_CAD_QLE_QUARTO_LEITO  QLE
                JOIN     TB_CAD_SET_SETOR         SETOR
                ON       SETOR.CAD_SET_ID       = QLE.CAD_SET_ID
                        AND SETOR.CAD_CSE_ID NOT IN (8,9)--AND SETOR.CAD_SET_ID NOT IN (2072,2312,5,140)
                        AND SETOR.CAD_SET_FL_PERMITEINTERN_OK = 'S'
                        AND SETOR.CAD_SET_FL_ATIVO_OK = 'S'
                JOIN     TB_CAD_UNI_UNIDADE       UNI
                ON       UNI.CAD_UNI_ID_UNIDADE = SETOR.CAD_UNI_ID_UNIDADE
                WHERE    UNI.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE
                and      qle.CAD_QLE_TP_QUARTO_LEITO = 'I'
                and      qle.cad_sql_cd_sit_quarto_leito != '5'
               ) TOTAL_LEITOS_HOSPITAL,
              (SELECT   COUNT(QLE.CAD_QLE_ID) A
                FROM     TB_CAD_QLE_QUARTO_LEITO          QLE
                JOIN     TB_CAD_SET_SETOR                  SETOR
                ON       SETOR.CAD_SET_ID                = QLE.CAD_SET_ID
                        AND SETOR.CAD_CSE_ID NOT IN (8,9)-- .CAD_SET_ID NOT IN (2072,2312,5,140)
                        AND SETOR.CAD_SET_FL_PERMITEINTERN_OK = 'S'
                        AND SETOR.CAD_SET_FL_ATIVO_OK = 'S'
                JOIN     TB_CAD_UNI_UNIDADE                UNI
                ON       UNI.CAD_UNI_ID_UNIDADE          = SETOR.CAD_UNI_ID_UNIDADE
                WHERE    QLE.CAD_SQL_CD_SIT_QUARTO_LEITO = '2'
                AND      QLE.CAD_QLE_TP_QUARTO_LEITO     = 'I'
                AND      UNI.CAD_UNI_ID_UNIDADE          = PCAD_UNI_ID_UNIDADE
               ) TOTAL_LEITOS_OCUPADOS_INTERNO,
                 (SELECT   COUNT(QLE.CAD_QLE_ID)     TOTAL_LEITO
                FROM     TB_CAD_QLE_QUARTO_LEITO           QLE
                JOIN     TB_CAD_SET_SETOR                  SETOR
                ON       SETOR.CAD_SET_ID                = QLE.CAD_SET_ID
                        AND SETOR.CAD_CSE_ID NOT IN (8,9)-- AND SETOR.CAD_SET_ID NOT IN (2072,2312,5,140)
                        AND SETOR.CAD_SET_FL_PERMITEINTERN_OK = 'S'
                        AND SETOR.CAD_SET_FL_ATIVO_OK = 'S'
                JOIN     TB_CAD_UNI_UNIDADE                UNI
                ON       UNI.CAD_UNI_ID_UNIDADE          = SETOR.CAD_UNI_ID_UNIDADE
                WHERE    QLE.CAD_SQL_CD_SIT_QUARTO_LEITO = '2'
                AND      QLE.CAD_QLE_TP_QUARTO_LEITO     = 'E'
                AND      UNI.CAD_UNI_ID_UNIDADE          = PCAD_UNI_ID_UNIDADE
               ) TOTAL_LEITOS_OCUPADOS_EXTRA,
               (SELECT  COUNT(QLE.CAD_QLE_ID) TOTAL_LEITO
                 FROM     TB_CAD_QLE_QUARTO_LEITO          QLE
                JOIN     TB_CAD_SET_SETOR                  SETOR
                ON       SETOR.CAD_SET_ID                = QLE.CAD_SET_ID
                        AND SETOR.CAD_CSE_ID NOT IN (8,9)-- AND SETOR.CAD_SET_ID NOT IN (2072,2312,5,140)
                        AND SETOR.CAD_SET_FL_PERMITEINTERN_OK = 'S'
                        AND SETOR.CAD_SET_FL_ATIVO_OK = 'S'
                JOIN     TB_CAD_UNI_UNIDADE                UNI
                ON       UNI.CAD_UNI_ID_UNIDADE          = SETOR.CAD_UNI_ID_UNIDADE
                WHERE    QLE.CAD_SQL_CD_SIT_QUARTO_LEITO in ( '1','8')--livre, reservado
                AND      QLE.CAD_QLE_TP_QUARTO_LEITO     = 'I'
                AND      UNI.CAD_UNI_ID_UNIDADE          = PCAD_UNI_ID_UNIDADE
               ) TOTAL_LEITOS_LIVRES_INTERNO,
                (SELECT  COUNT(QLE.CAD_QLE_ID) TOTAL_LEITO
                 FROM     TB_CAD_QLE_QUARTO_LEITO          QLE
                JOIN     TB_CAD_SET_SETOR                  SETOR
                ON       SETOR.CAD_SET_ID                = QLE.CAD_SET_ID
                        AND SETOR.CAD_CSE_ID NOT IN (8,9)-- AND SETOR.CAD_SET_ID NOT IN (2072,2312,5,140)
                        AND SETOR.CAD_SET_FL_PERMITEINTERN_OK = 'S'
                        AND SETOR.CAD_SET_FL_ATIVO_OK = 'S'
                JOIN     TB_CAD_UNI_UNIDADE                UNI
                ON       UNI.CAD_UNI_ID_UNIDADE          = SETOR.CAD_UNI_ID_UNIDADE
                WHERE    QLE.CAD_SQL_CD_SIT_QUARTO_LEITO in ('1','8')
                AND      QLE.CAD_QLE_TP_QUARTO_LEITO     = 'E'
                AND      UNI.CAD_UNI_ID_UNIDADE          = PCAD_UNI_ID_UNIDADE
               ) TOTAL_LEITOS_LIVRES_EXTERNO,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'I', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, null, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,'ACS' )  TOTAL_TIPO_PLANO_ACS_I,

              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'I', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, null, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,'AMIL' )  TOTAL_TIPO_PLANO_AMIL_I,

              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'I', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' )  TOTAL_TIPO_PLANO_FU_I,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'I', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,'PARTICULAR' )  TOTAL_TIPO_PLANO_PA_I,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'I', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' )  TOTAL_TIPO_PLANO_MERCADO_I,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'I', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' )  TOTAL_TIPO_PLANO_NP_I,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'E', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, null, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,'ACS' )  TOTAL_TIPO_PLANO_ACS_E,

                FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'E', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, null, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,'AMIL' )  TOTAL_TIPO_PLANO_AMIL_E,

              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'E', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,'FUNCIONARIO' )  TOTAL_TIPO_PLANO_FU_E,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'E', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' )  TOTAL_TIPO_PLANO_PA_E,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'E', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' )  TOTAL_TIPO_PLANO_MERCADO_E,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, NULL, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              'E', pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' )  TOTAL_TIPO_PLANO_NP_E,
------------

 FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, NULL )  PERMANENCIA_0_3_GERAL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 4, 7,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, NULL )  PERMANENCIA_4_7_GERAL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 8, 10,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, NULL )  PERMANENCIA_8_10_GERAL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 11, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, NULL ) PERMANENCIA_10_MAIS_GERAL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 0,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, NULL ) PERMANENCIA_0_GERAL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 1, 1, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, NULL ) PERMANENCIA_1_GERAL ,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 2, 2, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,NULL ) PERMANENCIA_2_GERAL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 3, 3, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, NULL ) PERMANENCIA_3_GERAL,
 ------------

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' )  PERMANENCIA_0_3_ACS,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 4, 7,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' )  PERMANENCIA_4_7_ACS,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 8, 10,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' )  PERMANENCIA_8_10_ACS,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 11, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' ) PERMANENCIA_10_MAIS_ACS,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 0,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' ) PERMANENCIA_0_ACS,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 1, 1, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' ) PERMANENCIA_1_ACS ,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 2, 2, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' ) PERMANENCIA_2_ACS,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 3, 3, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'ACS' ) PERMANENCIA_3_ACS, ------------




  FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' )  PERMANENCIA_0_3_AMIL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 4, 7,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' )  PERMANENCIA_4_7_AMIL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 8, 10,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' )  PERMANENCIA_8_10_AMIL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 11, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' ) PERMANENCIA_10_MAIS_AMIL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 0,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' ) PERMANENCIA_0_AMIL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 1, 1, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' ) PERMANENCIA_1_AMIL ,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 2, 2, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' ) PERMANENCIA_2_AMIL,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 3, 3, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'AMIL' ) PERMANENCIA_3_AMIL, ------------




              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 3, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' )  PERMANENCIA_0_3_FU,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 4, 7, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' )  PERMANENCIA_4_7_FU,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 8, 10, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' )  PERMANENCIA_8_10_FU,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 11, NULL, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' ) PERMANENCIA_10_MAIS_FU,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 0, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' ) PERMANENCIA_0_FU,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 1, 1, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' ) PERMANENCIA_1_FU ,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 2, 2, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' ) PERMANENCIA_2_FU,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 3, 3, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'FUNCIONARIO' ) PERMANENCIA_3_FU, --------------

              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
               pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' )  PERMANENCIA_0_3_MERCADO,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 4, 7,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
               pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' )  PERMANENCIA_4_7_MERCADO,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 8, 10,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
               pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' )  PERMANENCIA_8_10_MERCADO,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 11, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
               pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' ) PERMANENCIA_10_MAIS_MERCADO,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 0,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
               pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' ) PERMANENCIA_0_MERCADO,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 1, 1,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
               pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' ) PERMANENCIA_1_MERCADO ,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 2, 2,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' ) PERMANENCIA_2_MERCADO,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 3, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'MERCADO' ) PERMANENCIA_3_MERCADO, --------------

              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,'PARTICULAR' )  PERMANENCIA_0_3_PA,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 4, 7,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' )  PERMANENCIA_4_7_PA,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 8, 10,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' )  PERMANENCIA_8_10_PA,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 11, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' ) PERMANENCIA_10_MAIS_PA,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 0,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' ) PERMANENCIA_0_PA,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 1, 1,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' ) PERMANENCIA_1_PA ,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 2, 2,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' ) PERMANENCIA_2_PA,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 3, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'PARTICULAR' ) PERMANENCIA_3_PA, -----------

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 3,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' )  PERMANENCIA_0_3_NP,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 4, 7,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' )  PERMANENCIA_4_7_NP,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 8, 10,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' )  PERMANENCIA_8_10_NP,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 11, NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' ) PERMANENCIA_10_MAIS_NP,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 0, 0,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' ) PERMANENCIA_0_NP,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 1, 1, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' ) PERMANENCIA_1_NP ,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 2, 2, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' ) PERMANENCIA_2_NP,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, NULL, 3, 3, NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, NULL, NULL,
              NULL, NULL, NULL, NULL, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO, 'NAOPAGANTE' ) PERMANENCIA_3_NP, ------------

              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, 14,NULL,NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,NULL ) total_idade_15_menos,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 15, 29,NULL,NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,NULL ) total_idade_15_29,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 30, 44,NULL,NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,NULL ) total_idade_30_44,

               FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 45, 64,NULL,NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,NULL ) total_idade_45_64,

              FNC_INT_QTD_INTERNADOS(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 65, null,NULL,NULL,NULL,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, pCAD_SET_ID, pCAD_SET_NR_ANDAR, 'I', 'I',
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO,NULL ) total_idade_65_mais

  FROM      DUAL ;
  io_cursor := v_cursor;
end PRC_INT_REL_RESUMO;
