create or replace procedure PRC_ASS_CPA_PACOTES_L
(
     pCAD_CNV_ID_CONVENIO IN TB_ASS_CPA_CONVENIO_PACOTE.CAD_CNV_ID_CONVENIO%type,
     pCAD_PLA_ID_PLANO IN TB_ASS_CPA_CONVENIO_PACOTE.CAD_PLA_ID_PLANO%type,
     pDATACONSUMO IN DATE,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
v_cursor PKG_CURSOR.t_cursor;
begin
OPEN v_cursor FOR
SELECT
       CPA.ASS_CPA_ID,
       CPA.CAD_CNV_ID_CONVENIO,
       CPA.CAD_PLA_ID_PLANO,
       CPA.CAD_PRD_ID,
       CPA.ASS_CPA_FL_STATUS,
       CPA.ASS_CPA_DT_INICIO_VIGENCIA,
       CPA.ASS_CPA_DT_FIM_VIGENCIA,
       CPA.ASS_CPA_FL_LANC_PAC_ABERTO,
       CPA.ASS_CPA_DS_OBSERVACAO,
       CPA.ASS_CPA_DT_ULTIMA_ATUALIZACAO,
       CPA.SEG_USU_ID_USUARIO,
       CPA.ASS_CPA_VL_PACOTE_ESPECIAL,
       PRD.CAD_PRD_DS_DESCRICAO,
       PRD.CAD_PRD_VL_PRODUTO,
       PRD.CAD_PRD_CD_CODIGO,
       MED.TIS_MED_DS_TABELAMEDICA
FROM TB_ASS_CPA_CONVENIO_PACOTE CPA,
     TB_CAD_PRD_PRODUTO PRD,
     TB_TIS_MED_TABELAMEDICA MED
WHERE
     CPA.CAD_PRD_ID = PRD.CAD_PRD_ID
     AND PRD.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA
     AND CPA.ASS_CPA_FL_STATUS = 'A'
     AND fnc_validar_vigencia_data(CPA.ASS_CPA_DT_INICIO_VIGENCIA, CPA.ASS_CPA_DT_FIM_VIGENCIA, pDATACONSUMO) = 1
     AND CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
     AND (CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO OR CAD_PLA_ID_PLANO IS NULL);
io_cursor := v_cursor;
end PRC_ASS_CPA_PACOTES_L;
