CREATE OR REPLACE PROCEDURE PRC_COB_REL_01_RECEBIMENTOS
  (
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pDATA_EMISSAO_INI IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pDATA_EMISSAO_FIM IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pDATA_VENCIMENTO_INI IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
    pDATA_VENCIMENTO_FIM IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
    pDATA_PAGTO_INI  IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pDATA_PAGTO_FIM  IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pCAD_BAN_ID IN TB_CAD_BAN_BANCO.CAD_BAN_ID%TYPE DEFAULT NULL,
    pASS_BCT_ID IN TB_COB_MGC_MOV_GUIA_COBRANCA.ASS_BCT_ID%TYPE DEFAULT NULL,
    pPENDETE_CONTABILIDADE   VARCHAR2 DEFAULT NULL,
    pENVIADO_CONTABILIDADE   VARCHAR2 DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_ACS IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pDATA_CONTAB_INI     IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_LIBERACAO_CONTAB%TYPE DEFAULT NULL,
    pDATA_CONTAB_FIM     IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_LIBERACAO_CONTAB%TYPE DEFAULT NULL,
    pDATA_CONTAB_ANTERIOR IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_LIBERACAO_CONTAB%TYPE DEFAULT NULL,
    pDATA_MOVIMENTO_FIM  IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pFAT_NOF_NR_NOTAFISCAL   IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_NR_NOTAFISCAL%TYPE DEFAULT NULL,
    pFAT_NOF_TP_SERIEFISCAL  IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_TP_SERIEFISCAL%TYPE DEFAULT NULL,
    pTABELAS_HISTORICO VARCHAR2 DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
      --  ,TESTE OUT LONG
  )
  is
  /********************************************************************
  *    Procedure: PRC_COB_REL_01_RECEBIMENTOS
  *
  *    Data Criac?o: 18/06/2012  Por: PEDRO
  *    Alteracao:
  *
  * UTILIZADO NOS RELATORIOS 01  05  06  07
  *******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE_NOTA  varchar2(3000);
  V_WHERE_MGC  varchar2(3000);
  V_SELECT  varchar2(30000);
  V_TABELA_MGC  varchar2(500);
  V_TABELA_CCP  varchar2(500);
begin
  V_WHERE_NOTA := NULL;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE_NOTA:= V_WHERE_NOTA || ' AND NOF.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND NOF.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pFAT_NOF_NR_NOTAFISCAL IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND NOF.FAT_NOF_NR_NOTAFISCAL = ' ||CHR(39)|| pFAT_NOF_NR_NOTAFISCAL ||CHR(39);    END IF;
IF pFAT_NOF_TP_SERIEFISCAL IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND NOF.FAT_NOF_TP_SERIEFISCAL = ' ||CHR(39)|| pFAT_NOF_TP_SERIEFISCAL ||CHR(39);    END IF;
IF pDATA_EMISSAO_INI IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_EMISSAO) >= ' ||CHR(39)|| pDATA_EMISSAO_INI ||CHR(39);    END IF;
IF pDATA_EMISSAO_FIM IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_EMISSAO) <= ' ||CHR(39)|| pDATA_EMISSAO_FIM ||CHR(39);    END IF;
IF pDATA_VENCIMENTO_INI IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_VENCIMENTO) >= ' ||CHR(39)|| pDATA_VENCIMENTO_INI ||CHR(39);    END IF;
IF pDATA_VENCIMENTO_FIM IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_VENCIMENTO) <= ' ||CHR(39)|| pDATA_VENCIMENTO_FIM ||CHR(39);    END IF;
V_WHERE_MGC := NULL;
IF pDATA_CONTAB_INI IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_LIBERACAO_CONTAB >= ' ||CHR(39)|| pDATA_CONTAB_INI ||CHR(39);    END IF;
IF pDATA_CONTAB_FIM IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_LIBERACAO_CONTAB <= ' ||CHR(39)|| pDATA_CONTAB_FIM ||CHR(39);    END IF;
IF pDATA_PAGTO_INI IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_MOVIMENTO >= ' ||CHR(39)|| pDATA_PAGTO_INI ||CHR(39);    END IF;
IF pDATA_PAGTO_FIM IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_MOVIMENTO <= ' ||CHR(39)|| pDATA_PAGTO_FIM ||CHR(39);    END IF;
IF pASS_BCT_ID IS NOT NULL THEN V_WHERE_MGC:= V_WHERE_MGC || ' AND MGC.ASS_BCT_ID = ' || pASS_BCT_ID; END IF;
V_TABELA_MGC:=NULL;
IF pTABELAS_HISTORICO IS NULL THEN V_TABELA_MGC:= ' TB_COB_MGC_MOV_GUIA_COBRANCA MGC '; ELSE V_TABELA_MGC:=' TB_COB_MGC_COBRANCA_HISTORICO MGC '; END IF;
V_TABELA_CCP:=NULL;
IF pTABELAS_HISTORICO IS NULL THEN V_TABELA_CCP:= ' TB_COB_CCP_CONTA_CONS_PARC CCP '; ELSE  V_TABELA_CCP:=' TB_COB_CCP_CONTA_HISTORICO CCP '; END IF;
V_SELECT:=
'
SELECT DISTINCT
       BAN.CAD_BAN_CD_BANCO || '' - '' || BAN.CAD_BAN_NM_BANCO CAD_BAN_NM_BANCO,
       BCT.ASS_BCT_CD_AGENCIA || '' / '' || BCT.ASS_BCT_NR_CONTA || '' - '' || BCT.ASS_BCT_CD_CTA_CAIXA_RM ASS_BCT_NR_CONTA,
       UNI.CAD_UNI_ID_UNIDADE,
       UNI.CAD_UNI_DS_RESUMIDA CAD_UNI_DS_UNIDADE,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       CNV.CAD_CNV_NM_FANTASIA,
       PES.CAD_PES_NR_CNPJ_CPF,
       TRUNC(NOF.FAT_NFO_DT_EMISSAO) FAT_NFO_DT_EMISSAO,
       TRUNC(NOF.FAT_NFO_DT_VENCIMENTO) FAT_NFO_DT_VENCIMENTO,
       TRUNC(MGC.COB_MGC_DT_MOVIMENTO) COB_MGC_DT_MOVIMENTO,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.FAT_NFO_VL_FATURADO,
       NOF.FAT_NOF_VL_ISS,
       NOF.FAT_NOF_VL_DESCONTO,
       NOF.FAT_NFO_VL_RETENCAO,
       NVL(NOF.FAT_NFO_VL_LIQUIDO,0) FAT_NFO_VL_LIQUIDO,
       NVL(BAIXA.COB_MGC_VL_ISS,0) COB_MGC_VL_ISS,
       NVL(BAIXA.COB_MGC_VL_IR,0) COB_MGC_VL_IR,
       NVL(BAIXA.COB_MGC_VL_CSLL,0) COB_MGC_VL_CSLL,
       NVL(BAIXA.COB_MGC_VL_PIS,0) COB_MGC_VL_PIS,
       NVL(BAIXA.COB_MGC_VL_COFINS,0) COB_MGC_VL_COFINS,
       NVL(BAIXA.COB_MGC_VL_MOVIMENTO,0) COB_MGC_VL_MOVIMENTO,
       NVL(ANTECIPACAO.VALOR_ANTECIPACAO_DESCONTO,0)VALOR_ANTECIPACAO_DESCONTO,
       NVL(BAIXA.VALOR_DIGITADO,0) VALOR_DIGITADO,
       NVL(BAIXA.TOTAL_RETENCOES,0) TOTAL_RETENCOES,
       NVL(NOTACREDITO.NOTACREDITO,0) NOTACREDITO,
       NVL(DESCONTO.DESCONTO,0) DESCONTO,
       NULL COB_MGC_DT_LIBERACAO_CONTAB,
       NOF.FAT_NOF_ID,
       NVL(ISS.ISS,0) ISS,
       NVL(ISS_RETIDO.ISS_RETIDO,0) ISS_RETIDO,
       NVL(CASE WHEN VL_A_MAIOR.VL_A_MAIOR < 0 THEN 0 ELSE VL_A_MAIOR.VL_A_MAIOR END,0) VL_A_MAIOR,
       (TO_DATE('||CHR(39)|| pDATA_CONTAB_ANTERIOR ||CHR(39)|| ') - NOF.FAT_NFO_DT_VENCIMENTO)+1 QTD_DIAS,
       FNC_COB_PERIODO_VENCIMENTO(NOF.FAT_NFO_DT_VENCIMENTO,TO_DATE('||CHR(39)|| pDATA_CONTAB_ANTERIOR ||CHR(39)||') ,''0'') ORDEM,
       FNC_COB_PERIODO_VENCIMENTO(NOF.FAT_NFO_DT_VENCIMENTO,TO_DATE('||CHR(39)|| pDATA_CONTAB_ANTERIOR ||CHR(39)||') ,''1'') PERIODO
       
FROM      TB_FAT_NOF_NOTA_FISCAL       NOF
JOIN      ' || V_TABELA_CCP  ||'     ON  CCP.FAT_NOF_ID          = NOF.FAT_NOF_ID
JOIN      TB_CAD_CNV_CONVENIO          CNV  ON  CNV.CAD_CNV_ID_CONVENIO = NOF.CAD_CNV_ID_CONVENIO
JOIN      TB_CAD_PES_PESSOA            PES  ON  PES.CAD_PES_ID_PESSOA   = CNV.CAD_PES_ID_PESSOA
JOIN      ' || V_TABELA_MGC  ||'   ON  MGC.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                           AND  MGC.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                           AND  MGC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                           AND  MGC.COB_COC_ID          = CCP.COB_COC_ID
                                           AND  MGC.COB_CCP_ID          = CCP.COB_CCP_ID
                                           AND  MGC.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                           AND  MGC.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
LEFT JOIN  (SELECT  SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0)) COB_MGC_VL_MOVIMENTO,
                    SUM(NVL(MGC.COB_MGC_VL_ISS,0))       COB_MGC_VL_ISS,
                    SUM(NVL(MGC.COB_MGC_VL_IR,0))        COB_MGC_VL_IR,
                    SUM(NVL(MGC.COB_MGC_VL_CSLL,0))      COB_MGC_VL_CSLL,
                    SUM(NVL(MGC.COB_MGC_VL_PIS,0))       COB_MGC_VL_PIS,
                    SUM(NVL(MGC.COB_MGC_VL_COFINS,0))    COB_MGC_VL_COFINS,
                    SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                        NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) VALOR_DIGITADO, --vl calculado na tela
                    SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                        NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) TOTAL_RETENCOES,
                    MGC.FAT_NOF_ID, MGC.COB_MGC_DT_MOVIMENTO,MGC.ASS_BCT_ID
               FROM ' || V_TABELA_MGC  ||' 
            WHERE   MGC.CAD_TMC_ID          NOT IN (2,7,9)
            ' || V_WHERE_MGC || '
                AND (MGC.COB_MGC_VL_MOVIMENTO >= 0 OR MGC.CAD_TMC_ID =15)
           GROUP BY MGC.FAT_NOF_ID, MGC.COB_MGC_DT_MOVIMENTO,MGC.ASS_BCT_ID
         ) BAIXA
         ON  BAIXA.FAT_NOF_ID          = MGC.FAT_NOF_ID
          AND BAIXA.COB_MGC_DT_MOVIMENTO = MGC.COB_MGC_DT_MOVIMENTO
          AND BAIXA.ASS_BCT_ID           = MGC.ASS_BCT_ID
LEFT JOIN (SELECT SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                  NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) VALOR_ANTECIPACAO_DESCONTO,
                  MGC.FAT_NOF_ID,TRUNC(MGC.COB_MGC_DT_MOVIMENTO) COB_MGC_DT_MOVIMENTO
                  --, TRUNC(MGC.COB_MGC_DT_LIBERACAO_CONTAB) DT_CONTAB_DESCONTO
                  FROM TB_FAT_NOF_NOTA_FISCAL       NOF 
                  JOIN ' || V_TABELA_MGC  ||'  ON MGC.FAT_NOF_ID = NOF.FAT_NOF_ID
                  WHERE MGC.CAD_TMC_ID = 8
                  ' || V_WHERE_NOTA || '
                  GROUP BY MGC.FAT_NOF_ID,TRUNC(MGC.COB_MGC_DT_MOVIMENTO)--,TRUNC(MGC.COB_MGC_DT_LIBERACAO_CONTAB) 
     ) ANTECIPACAO ON ANTECIPACAO.FAT_NOF_ID = NOF.FAT_NOF_ID
                AND ANTECIPACAO.COB_MGC_DT_MOVIMENTO = MGC.COB_MGC_DT_MOVIMENTO
LEFT JOIN  (SELECT  SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0)) NOTACREDITO, MGC.FAT_NOF_ID, MGC.COB_MGC_DT_MOVIMENTO,MGC.ASS_BCT_ID
               FROM TB_FAT_NOF_NOTA_FISCAL       NOF 
              JOIN ' || V_TABELA_MGC  ||'  ON MGC.FAT_NOF_ID = NOF.FAT_NOF_ID
            WHERE   MGC.CAD_TMC_ID          = 2            
          ' || V_WHERE_NOTA || '
          ' || V_WHERE_MGC || '          
           GROUP BY MGC.FAT_NOF_ID, MGC.COB_MGC_DT_MOVIMENTO,MGC.ASS_BCT_ID
         ) NOTACREDITO
         ON  NOTACREDITO.FAT_NOF_ID          = MGC.FAT_NOF_ID
          AND NOTACREDITO.COB_MGC_DT_MOVIMENTO = MGC.COB_MGC_DT_MOVIMENTO
          AND NOTACREDITO.ASS_BCT_ID           = MGC.ASS_BCT_ID
LEFT JOIN  (SELECT  SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0)) ISS,  MGC.FAT_NOF_ID--,MGC.COB_MGC_DT_MOVIMENTO
                FROM TB_FAT_NOF_NOTA_FISCAL       NOF 
              JOIN ' || V_TABELA_MGC  ||'  ON MGC.FAT_NOF_ID = NOF.FAT_NOF_ID
            WHERE   MGC.CAD_TMC_ID          = 7
            ' || V_WHERE_NOTA || '
           ' || V_WHERE_MGC || '
           GROUP BY MGC.FAT_NOF_ID
         ) ISS
         ON  ISS.FAT_NOF_ID           = MGC.FAT_NOF_ID
      --   AND ISS.COB_MGC_DT_MOVIMENTO = MGC.COB_MGC_DT_MOVIMENTO
      --   SE TIVER ISS N RETIDO COM DATA DE MOV. QUE N RETORNE NA PRINCIPAL DA PROBLEMA NA SUBQUERY
LEFT JOIN  (SELECT  SUM(NVL(MGC.COB_MGC_VL_ISS,0)) ISS_RETIDO, MGC.COB_MGC_DT_MOVIMENTO,MGC.FAT_NOF_ID
               FROM TB_FAT_NOF_NOTA_FISCAL       NOF 
              JOIN ' || V_TABELA_MGC  ||'  ON MGC.FAT_NOF_ID = NOF.FAT_NOF_ID
            WHERE   MGC.CAD_TMC_ID          = 1
            ' || V_WHERE_NOTA || '
            ' || V_WHERE_MGC || '
           GROUP BY MGC.COB_MGC_DT_MOVIMENTO, MGC.FAT_NOF_ID
          ) ISS_RETIDO
          ON  ISS_RETIDO.FAT_NOF_ID           = MGC.FAT_NOF_ID
          AND ISS_RETIDO.COB_MGC_DT_MOVIMENTO = MGC.COB_MGC_DT_MOVIMENTO
LEFT JOIN  (SELECT MGC.VL_A_MAIOR-SUM(CCP.COB_CCP_VL_TOT_CONTA) VL_A_MAIOR, MGC.FAT_NOF_ID
               FROM ' || V_TABELA_CCP  ||'   
               JOIN TB_FAT_NOF_NOTA_FISCAL       NOF ON NOF.FAT_NOF_ID = CCP.FAT_NOF_ID
               JOIN (SELECT SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0))+SUM(NVL(MGC.COB_MGC_VL_ISS,0))+SUM(NVL(MGC.COB_MGC_VL_IR,0))+SUM(NVL(MGC.COB_MGC_VL_CSLL,0))+ SUM(NVL(MGC.COB_MGC_VL_PIS,0)) +SUM(NVL(MGC.COB_MGC_VL_COFINS,0)) VL_A_MAIOR,
                            MGC.FAT_NOF_ID
                      FROM ' || V_TABELA_MGC  ||' 
                      WHERE MGC.CAD_TMC_ID          != 7
                      ' || V_WHERE_MGC || '
                      GROUP BY MGC.FAT_NOF_ID
                    ) MGC ON  MGC.FAT_NOF_ID          = CCP.FAT_NOF_ID
           WHERE 1=1 ' || V_WHERE_NOTA || '
            GROUP BY MGC.VL_A_MAIOR,MGC.FAT_NOF_ID
         ) VL_A_MAIOR
         ON  VL_A_MAIOR.FAT_NOF_ID          = MGC.FAT_NOF_ID
LEFT JOIN  (SELECT DISTINCT  MGC.FAT_NOF_ID, MGC.COB_MGC_DT_MOVIMENTO,
                   SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0))OVER(PARTITION BY MGC.FAT_NOF_ID,MGC.COB_MGC_DT_MOVIMENTO) DESCONTO
               FROM TB_FAT_NOF_NOTA_FISCAL       NOF 
              JOIN ' || V_TABELA_MGC  ||'  ON MGC.FAT_NOF_ID = NOF.FAT_NOF_ID
               JOIN ' || V_TABELA_CCP  ||' ON  MGC.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                                     AND  MGC.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                                     AND  MGC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                                     AND  MGC.COB_COC_ID          = CCP.COB_COC_ID
                                                     AND  MGC.COB_CCP_ID          = CCP.COB_CCP_ID
                                                     AND  MGC.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                                     AND  MGC.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
           WHERE   MGC.CAD_TMC_ID          = 5
          ' || V_WHERE_NOTA || '
          ' || V_WHERE_MGC || '
         ) DESCONTO
         ON  DESCONTO.FAT_NOF_ID          = MGC.FAT_NOF_ID
         AND DESCONTO.COB_MGC_DT_MOVIMENTO = MGC.COB_MGC_DT_MOVIMENTO
JOIN      TB_CAD_UNI_UNIDADE           UNI  ON  UNI.CAD_UNI_ID_UNIDADE  = NOF.CAD_UNI_ID_UNIDADE
LEFT JOIN TB_CAD_TMC_TIPO_MOV_COBRANCA TMC  ON  TMC.CAD_TMC_ID          = MGC.CAD_TMC_ID
LEFT JOIN TB_ASS_BCT_BANCO_CONTA       BCT  ON  BCT.ASS_BCT_ID          = MGC.ASS_BCT_ID
LEFT JOIN TB_CAD_BAN_BANCO             BAN  ON  BAN.CAD_BAN_ID          = BCT.CAD_BAN_ID
WHERE  CCP.COB_CCP_FL_STATUS   = ''A''
AND    CNV.CAD_CNV_CD_OPCAO_PAGTO = ''1''
AND    MGC.CAD_TMC_ID          NOT IN(7)
' || V_WHERE_NOTA || '
' || V_WHERE_MGC || '' ;
 
  -- TESTE :=  V_SELECT ;
   --dbms_output.put_line(V_SELECT);
  OPEN v_cursor FOR
   -- SELECT 1 FROM DUAL;
    V_SELECT ;
    io_cursor := v_cursor;
  end PRC_COB_REL_01_RECEBIMENTOS;
 