CREATE OR REPLACE PROCEDURE "PRC_AGS_REL_CIRURGIAS"
  (
     PCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
     PCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
     PCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
     PCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
     PCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
     PDT_INI_CONSULTA IN TB_AGS_AGE_AGENDA_SADT.AGS_AGE_DT_ATENDIMENTO%TYPE,
     PDT_FIM_CONSULTA IN TB_AGS_AGE_AGENDA_SADT.AGS_AGE_DT_ATENDIMENTO%TYPE,
     PHR_INI_CONSULTA IN TB_AGS_AGE_AGENDA_SADT.AGS_AGE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
     PHR_FIM_CONSULTA IN TB_AGS_AGE_AGENDA_SADT.AGS_AGE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
     PAGE_SAU_ID IN TB_AGE_SAU_SALA_UNID_AND.AGE_SAU_ID%TYPE DEFAULT NULL,
     PAUX_EPP_CD_ESPECPROC IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE DEFAULT NULL,
     PCAD_PRD_ID  IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
     PCAD_PRO_ID_PROFISSIONAL  IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
     PAGS_AGE_CD_PROF_CIRURGIAO IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
     PAGS_AGE_CD_PROF_ASSISTENTE IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
     PAGS_AGE_CD_PROF_ANESTESIST IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
     IO_CURSOR OUT PKG_CURSOR.T_CURSOR
  )
  IS
  /********************************************************************
  *    PROCEDURE: PRC_AGS_REL_CIRURGIAS
  *
  *    DATA CRIACAO:  06/07/2010   POR: PEDRO
  *    DATA ALTERACAO: DATA DA ALTERACAO  POR: NOME DO ANALISTA
  *
  *    FUNCAO: ALIMENTAR RELATORIO DE PACIENTES AGENDADOS NO SADT CENTRO CIRURGICO
  *
  *    DATA ALTERACAO: 13/09/2010  POR: DAVI SILVESTRE M. DOS REIS
  *    ALTERACAO: ORDENACAO PRIORITARIAMENTE PELA HORA DO AGENDAMENTO
  *
  *******************************************************************/
  V_CURSOR PKG_CURSOR.T_CURSOR;
  BEGIN
OPEN V_CURSOR FOR
 SELECT
          SAU.AGE_SAU_CD_ANDAR ,
           LPAD(TO_CHAR(SAU.AGE_SAU_NR_SALA),2,0) AGE_SAU_NR_SALA ,
           FNC_AGS_ULTIMO_LEITO(AGS.LIB_PRD_ID) ULTIMO_QLE,
           PRD.CAD_PRD_DS_DESCRICAO ,
           PRD.CAD_PRD_NM_MNEMONICO ,
           TO_CHAR(AGS.AGS_AGE_DT_ATENDIMENTO, 'DD/MM/YYYY') DT_AGENDAMENTO,
          -- AGS.AGS_AGE_HR_ATENDIMENTO HR_AGENDAMENTO,
           FNC_AGS_PRIMEIRO_HORARIO(AGS.LIB_PRD_ID,AGS.AGS_AGE_DT_ATENDIMENTO,AGS.CAD_PRD_ID) HR_AGENDAMENTO,
           PES_PAC.CAD_PES_NM_PESSOA NM_PACIENTE,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           PLA.CAD_PLA_CD_PLANO_HAC,
           AGS.AGS_AGE_CD_INTAMB,
           AGS.AGS_AGE_IN_ORIGEM_INTAMB,
           AGS.LIB_PRD_ID ID_LIBERACAO,
           PAC.CAD_PAC_NR_PRONTUARIO ,
           PRO.CAD_PRO_NM_NOME NM_PROFISSIONAL,
           AGS.AGS_AGE_DS_DUR_CIRURGIA,
           AGS.AGS_AGE_CD_PROF_CIRURGIAO,
           PRO_CIRURGIAO.CAD_PRO_NM_NOME CIRURGIAO,
           AGS.AGS_AGE_CD_PROF_ASSISTENTE,
           PRO_ASSISTENTE.CAD_PRO_NM_NOME ASSISTENTE,
           AGS.AGS_AGE_NM_INSTRUMENTADOR,
           AGS.AGS_AGE_CD_PROF_ANESTESIST,
           PRO_ANESTESISTA.CAD_PRO_NM_NOME ANESTESISTA,
           AGS.AGS_AGE_DS_INST_APAR_ESP,
           AGS.AGS_AGE_FL_ANESTESIA_OK,
           AGS.AGS_AGE_FL_TRANSFUSAO_OK,
           AGS.AGS_AGE_FL_CONGELACAO_OK,
           AGS.AGS_AGE_NM_CIRCULANTE,
           AGS.AGS_AGE_NM_ENFERM_CHEFE,
           AGS.CAD_TAN_TP_ANESTESIA,
           TAN.CAD_TAN_DS_ANESTESIA,
           AGS.AGS_AGE_FL_CIRUR_SUSP_OK,
           AGS.AGS_AGE_FL_CIRUR_ADIAD_OK,
           PES_PAC.CAD_PES_DT_NASCIMENTO,
           FLOOR(FLOOR(MONTHS_BETWEEN(SYSDATE, PES_PAC.CAD_PES_DT_NASCIMENTO)) / 12) IDADE,
           DECODE(TAC_IAE.TIS_TAC_DS_TIPO_ACOMODACAO,NULL, A.TIS_TAC_DS_TIPO_ACOMODACAO,TAC_IAE.TIS_TAC_DS_TIPO_ACOMODACAO) TIS_TAC_DS_TIPO_ACOMODACAO,
           DECODE(IAE.ATD_IAE_TP_PACIENTE,NULL, ATE.ATD_ATE_TP_PACIENTE,IAE.ATD_IAE_TP_PACIENTE) ATD_IAE_TP_PACIENTE
           
      FROM TB_AGS_AGE_AGENDA_SADT AGS
     INNER JOIN TB_AGS_ESM_ESCALA_SADT AGSESM ON AGSESM.AGS_ESM_ID = AGS.AGS_ESM_ID
     INNER JOIN TB_AGE_SAU_SALA_UNID_AND SAU ON SAU.AGE_SAU_ID = AGSESM.AGE_SAU_ID
     INNER JOIN TB_CAD_PRD_PRODUTO PRD ON PRD.CAD_PRD_ID = AGS.CAD_PRD_ID
     INNER JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PAC_ID_PACIENTE = AGS.CAD_PAC_ID_PACIENTE
     INNER JOIN TB_CAD_PES_PESSOA PES_PAC ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
     INNER JOIN TB_CAD_CNV_CONVENIO CNV ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
     INNER JOIN TB_CAD_PLA_PLANO PLA ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO

     LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO ON PRO.CAD_PRO_ID_PROFISSIONAL = AGSESM.CAD_PRO_ID_PROFISSIONAL
     LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO_CIRURGIAO ON PRO_CIRURGIAO.CAD_PRO_ID_PROFISSIONAL = AGS.AGS_AGE_CD_PROF_CIRURGIAO
     LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO_ASSISTENTE ON PRO_ASSISTENTE.CAD_PRO_ID_PROFISSIONAL = AGS.AGS_AGE_CD_PROF_ASSISTENTE
     LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO_ANESTESISTA ON PRO_ANESTESISTA.CAD_PRO_ID_PROFISSIONAL = AGS.AGS_AGE_CD_PROF_ANESTESIST

     LEFT JOIN TB_CAD_TAN_TIPO_ANESTESIA TAN ON TAN.CAD_TAN_TP_ANESTESIA = AGS.CAD_TAN_TP_ANESTESIA
     LEFT JOIN TB_ATD_IAE_INT_AGE_ELETIVA IAE ON IAE.ATD_IAE_ID = AGS.AGS_AGE_CD_INTAMB
     LEFT JOIN TB_ATD_ATE_ATENDIMENTO ATE ON ATE.ATD_ATE_ID = AGS.AGS_AGE_CD_INTAMB     
     LEFT JOIN TB_TIS_TAC_TIPO_ACOMODACAO TAC_IAE ON TAC_IAE.TIS_TAC_CD_TIPO_ACOMODACAO = IAE.TIS_TAC_CD_TIPO_ACOMODACAO
     
      LEFT JOIN  (SELECT   TAC_ATE.TIS_TAC_DS_TIPO_ACOMODACAO,ATD2.ATD_ATE_ID
                 FROM      TB_ATD_IML_INT_MOV_LEITO IML
                 JOIN      TB_ATD_ATE_ATENDIMENTO ATD2 ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                 JOIN      TB_TIS_TAC_TIPO_ACOMODACAO TAC_ATE ON TAC_ATE.TIS_TAC_CD_TIPO_ACOMODACAO = IML.TIS_TAC_CD_TIPO_ACOMOD_AUT                      
                 WHERE     IML.ATD_IML_DT_SAIDA IS NULL AND IML.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML.ATD_IML_FL_STATUS = 'A'
                 AND       (ATD2.ATD_ATE_DT_ATENDIMENTO BETWEEN PDT_INI_CONSULTA AND PDT_FIM_CONSULTA)
                 UNION
                 SELECT    TAC_ATE.TIS_TAC_DS_TIPO_ACOMODACAO,ATD2.ATD_ATE_ID
                 FROM      TB_ATD_IMS_INT_MOV_SETOR IMS
                 JOIN      TB_ATD_ATE_ATENDIMENTO ATD2 ON        ATD2.ATD_ATE_ID = IMS.ATD_ATE_ID
                 JOIN      TB_TIS_TAC_TIPO_ACOMODACAO TAC_ATE ON TAC_ATE.TIS_TAC_CD_TIPO_ACOMODACAO = IMS.TIS_TAC_CD_TIPO_ACOMOD_AUT
                 WHERE     IMS.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IMS.ATD_IMS_DT_SAIDA IS NULL AND IMS.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IMS.ATD_IMS_FL_STATUS = 'A'
                 AND       (ATD2.ATD_ATE_DT_ATENDIMENTO BETWEEN PDT_INI_CONSULTA AND PDT_FIM_CONSULTA)
                 AND NOT IMS.ATD_ATE_ID IN (SELECT IML.ATD_ATE_ID
                                               FROM      TB_ATD_IML_INT_MOV_LEITO IML
                                               JOIN      TB_ATD_ATE_ATENDIMENTO ATD2 ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                                               WHERE     IML.ATD_IML_DT_SAIDA IS NULL AND IML.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML.ATD_IML_FL_STATUS = 'A')
              )  A
  ON A.ATD_ATE_ID = ATE.ATD_ATE_ID
     
     
     WHERE
          (PCAD_UNI_ID_UNIDADE IS NULL OR AGSESM.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
      AND (PCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR AGSESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
      AND (PCAD_SET_ID IS NULL OR AGSESM.CAD_SET_ID = PCAD_SET_ID)
      AND (PCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = PCAD_CNV_ID_CONVENIO)
      AND (PCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = PCAD_PLA_ID_PLANO)
      AND (PAGE_SAU_ID IS NULL OR SAU.AGE_SAU_ID = PAGE_SAU_ID)
      AND (AGS.AGS_AGE_DT_ATENDIMENTO BETWEEN PDT_INI_CONSULTA AND PDT_FIM_CONSULTA)
      AND (PHR_INI_CONSULTA IS NULL OR AGS.AGS_AGE_HR_ATENDIMENTO >= PHR_INI_CONSULTA)
      AND (PHR_FIM_CONSULTA IS NULL OR AGS.AGS_AGE_HR_ATENDIMENTO <= PHR_FIM_CONSULTA)
      AND (PAUX_EPP_CD_ESPECPROC IS NULL OR PRD.AUX_EPP_CD_ESPECPROC = PAUX_EPP_CD_ESPECPROC)
      AND (PCAD_PRD_ID  IS NULL OR PRD.CAD_PRD_ID = PCAD_PRD_ID)
      AND (PCAD_PRO_ID_PROFISSIONAL IS NULL OR PRO.CAD_PRO_ID_PROFISSIONAL = PCAD_PRO_ID_PROFISSIONAL)
      AND (PAGS_AGE_CD_PROF_CIRURGIAO IS NULL OR AGS.AGS_AGE_CD_PROF_CIRURGIAO = PAGS_AGE_CD_PROF_CIRURGIAO)
      AND (PAGS_AGE_CD_PROF_ASSISTENTE IS NULL OR AGS.AGS_AGE_CD_PROF_ASSISTENTE = PAGS_AGE_CD_PROF_ASSISTENTE)
      AND (PAGS_AGE_CD_PROF_ANESTESIST IS NULL OR AGS.AGS_AGE_CD_PROF_ANESTESIST = PAGS_AGE_CD_PROF_ANESTESIST)
GROUP BY SAU.AGE_SAU_CD_ANDAR ,
           LPAD(TO_CHAR(SAU.AGE_SAU_NR_SALA),2,0)  ,
           FNC_AGS_ULTIMO_LEITO(AGS.LIB_PRD_ID) ,
           PRD.CAD_PRD_DS_DESCRICAO ,
           PRD.CAD_PRD_NM_MNEMONICO ,
           TO_CHAR(AGS.AGS_AGE_DT_ATENDIMENTO, 'DD/MM/YYYY') ,
          -- AGS.AGS_AGE_HR_ATENDIMENTO HR_AGENDAMENTO,
           FNC_AGS_PRIMEIRO_HORARIO(AGS.LIB_PRD_ID,AGS.AGS_AGE_DT_ATENDIMENTO,AGS.CAD_PRD_ID) ,
           PES_PAC.CAD_PES_NM_PESSOA ,
           FNC_RETORNA_TEL_PAC(PES_PAC.CAD_PES_ID_PESSOA) ,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           PLA.CAD_PLA_CD_PLANO_HAC,
           AGS.AGS_AGE_CD_INTAMB,
           AGS.AGS_AGE_IN_ORIGEM_INTAMB,
           AGS.LIB_PRD_ID ,
           PAC.CAD_PAC_NR_PRONTUARIO ,
           PRO.CAD_PRO_NM_NOME ,
           AGS.AGS_AGE_DS_DUR_CIRURGIA,
           AGS.AGS_AGE_CD_PROF_CIRURGIAO,
           PRO_CIRURGIAO.CAD_PRO_NM_NOME ,
           AGS.AGS_AGE_CD_PROF_ASSISTENTE,
           PRO_ASSISTENTE.CAD_PRO_NM_NOME ,
           AGS.AGS_AGE_NM_INSTRUMENTADOR,
           AGS.AGS_AGE_CD_PROF_ANESTESIST,
           PRO_ANESTESISTA.CAD_PRO_NM_NOME ,
           AGS.AGS_AGE_DS_INST_APAR_ESP,
           AGS.AGS_AGE_FL_ANESTESIA_OK,
           AGS.AGS_AGE_FL_TRANSFUSAO_OK,
           AGS.AGS_AGE_FL_CONGELACAO_OK,
           AGS.AGS_AGE_NM_CIRCULANTE,
           AGS.AGS_AGE_NM_ENFERM_CHEFE,
           AGS.CAD_TAN_TP_ANESTESIA,
           TAN.CAD_TAN_DS_ANESTESIA,
           AGS.AGS_AGE_FL_CIRUR_SUSP_OK,
           AGS.AGS_AGE_FL_CIRUR_ADIAD_OK,
           AGS.AGS_AGE_DT_ATENDIMENTO,
           AGS.CAD_PRD_ID,
           PES_PAC.CAD_PES_DT_NASCIMENTO,
           FLOOR(FLOOR(MONTHS_BETWEEN(SYSDATE, PES_PAC.CAD_PES_DT_NASCIMENTO)) / 12),
           DECODE(TAC_IAE.TIS_TAC_DS_TIPO_ACOMODACAO,NULL, A.TIS_TAC_DS_TIPO_ACOMODACAO,TAC_IAE.TIS_TAC_DS_TIPO_ACOMODACAO) ,
           DECODE(IAE.ATD_IAE_TP_PACIENTE,NULL, ATE.ATD_ATE_TP_PACIENTE,IAE.ATD_IAE_TP_PACIENTE) 
           
  ORDER BY
    -- AGS.AGS_AGE_DT_ATENDIMENTO,
    HR_AGENDAMENTO,
     LPAD(TO_CHAR(SAU.AGE_SAU_NR_SALA),2,0),
      FNC_AGS_PRIMEIRO_HORARIO(AGS.LIB_PRD_ID,AGS.AGS_AGE_DT_ATENDIMENTO,AGS.CAD_PRD_ID,NULL)
  ;
    IO_CURSOR := V_CURSOR;
  END PRC_AGS_REL_CIRURGIAS;
