CREATE OR REPLACE PROCEDURE prc_mtmd_req_item_disp_s
  (
     pMTMD_REQ_ID IN TB_MTMD_REQUISICAO_ITEM.MTMD_REQ_ID%type,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
   IS
  v_cursor PKG_CURSOR.t_cursor;
  /*
  SELECIONA ITENS PARA TELA DE DISPENSAC?O.
  SOMENTE ITENS QUE JA TENHA QTDE FORNECIDA
  */
BEGIN
    OPEN v_cursor FOR
SELECT ITEM.MTMD_REQ_ID,
       ITEM.CAD_MTMD_ID,
       -- SE ID ORIGINAL E NULL N?O E SIMILAR,
       -- RETORNA QTDE DEDUZINDO A QTDE FORNECIDA NOS SIMILARES
       -- SE N?O RETORNA A PRORIA QTDE SOLICITADA
       DECODE( ITEM.MTMD_ID_ORIGINAL, NULL,
               (ITEM.MTMD_REQITEM_QTD_SOLICITADA - FNC_MTMD_REQ_SOMA_SIMILAR( ITEM.CAD_MTMD_ID,
                                                                              ITEM.MTMD_REQ_ID,
                                                                              FNC_MTMD_PRINCIPIO_ATIVO (ITEM.CAD_MTMD_ID))),
               ITEM.MTMD_REQITEM_QTD_SOLICITADA
             ) MTMD_REQITEM_QTD_SOLICITADA,
       (SELECT MTMD.CAD_MTMD_NOMEFANTASIA
        FROM SGS.TB_CAD_MTMD_MAT_MED MTMD
        WHERE MTMD.cad_mtmd_id = ITEM.MTMD_ID_ORIGINAL )  DS_PRODUTO_ORIGINAL,
       ITEM.MTMD_REQITEM_QTD_FORNECIDA,
       ITEM.CAD_MTMD_ID,
       PRODUTO.CAD_MTMD_UNIDADE_VENDA,
       PRODUTO.CAD_MTMD_UNIDADE_CONTROLE,
       FNC_MTMD_SOUNDALIKE(PRODUTO.CAD_MTMD_NOMEFANTASIA,PRODUTO.CAD_MTMD_GRUPO_ID) CAD_MTMD_NOMEFANTASIA,
       PRODUTO.CAD_MTMD_UNID_VENDA_DS,
       FNC_MTMD_PRINCIPIO_ATIVO (ITEM.CAD_MTMD_ID) CAD_MTMD_PRIATI_ID,
       PRODUTO.CAD_MTMD_FL_MAV
    FROM SGS.TB_MTMD_REQUISICAO_ITEM       ITEM,
         SGS.TB_MTMD_REQ_REQUISICAO        REQUISICAO,
         SGS.TB_CAD_MTMD_MAT_MED           PRODUTO
    WHERE ITEM.MTMD_REQ_ID         = pMTMD_REQ_ID
    AND   REQUISICAO.MTMD_REQ_ID   = ITEM.MTMD_REQ_ID
    AND   PRODUTO.CAD_MTMD_ID      = ITEM.CAD_MTMD_ID
    AND   ITEM.mtmd_reqitem_qtd_fornecida > 0
    ORDER BY PRODUTO.CAD_MTMD_NOMEFANTASIA;

    io_cursor := v_cursor;

END; -- Procedure