create or replace procedure PRC_CAD_PAH_PERC_ACRESC_HR_UP
  (
     pCAD_TAP_TP_ATRIBUTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_TAP_TP_ATRIBUTO%type,
     pCAD_PAH_PC_ACRESCIMO_HR IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_PC_ACRESCIMO_HR%type,
     pCAD_PAH_HR_INICIO_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_INICIO_SEMANA%type,
     pCAD_PAH_HR_FIM_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_FIM_SEMANA%type,
     pCAD_PAH_DT_INICIO_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_INICIO_VIGENCIA%type,
     pCAD_PAH_DT_FIM_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_FIM_VIGENCIA%type default NULL,
     pCAD_PAH_DT_ULTIMA_ATUALIZACAO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_ULTIMA_ATUALIZACAO%type,
     pSEG_USU_ID_USUARIO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.SEG_USU_ID_USUARIO%type,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pCAD_PAH_NR_DIA_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_NR_DIA_SEMANA%type,
     pCAD_CNV_ID_CONVENIO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_CNV_ID_CONVENIO%type,
     pCAD_PAH_ID IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_ID%type,
     pCAD_PAH_HR_INICIO_ANTERIOR IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_INICIO_SEMANA%type
  )
  is
  /********************************************************************
  *    Procedure: PRC_CAD_PAH_PERC_ACRESC_HR_UP
  *
  *    Data Criacao:   data da  cria??o   Por: Nome do Analista
  *    Data Alteracao:  27/04/2010  Por: Pedro
  *    Alteracao: a chave mudou.
  *
  *    Funcao: Descri??o da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  begin
    UPDATE TB_CAD_PAH_PERC_ACRESCIMO_HR
    SET
        CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO,
        CAD_PAH_PC_ACRESCIMO_HR = pCAD_PAH_PC_ACRESCIMO_HR,
        CAD_PAH_HR_INICIO_SEMANA = pCAD_PAH_HR_INICIO_SEMANA,
        CAD_PAH_HR_FIM_SEMANA = pCAD_PAH_HR_FIM_SEMANA,
        CAD_PAH_DT_INICIO_VIGENCIA = pCAD_PAH_DT_INICIO_VIGENCIA,
        CAD_PAH_DT_FIM_VIGENCIA = pCAD_PAH_DT_FIM_VIGENCIA,
        CAD_PAH_DT_ULTIMA_ATUALIZACAO = pCAD_PAH_DT_ULTIMA_ATUALIZACAO,
        SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO,
        CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO,
        CAD_PAH_NR_DIA_SEMANA = pCAD_PAH_NR_DIA_SEMANA,
        CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
    WHERE
        CAD_PAH_ID = pCAD_PAH_ID
    AND CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
    AND CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
    AND CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO
    AND CAD_PAH_NR_DIA_SEMANA = pCAD_PAH_NR_DIA_SEMANA
    AND CAD_PAH_HR_INICIO_SEMANA = pCAD_PAH_HR_INICIO_ANTERIOR;
  end PRC_CAD_PAH_PERC_ACRESC_HR_UP;

