CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_PENDENCIAS"
(
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pFAT_FCL_NR_SEQ_LOTE IN TB_FAT_FCL_CONTR_EMI_LOTE.FAT_FCL_NR_SEQ_LOTE%TYPE DEFAULT NULL,
    pATD_ATE_ID IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_ID%TYPE DEFAULT NULL,
    pCAD_MPF_ID varchar2 default null,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_E in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_A in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_U in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
    pTIS_MED_CD_TABELAMEDICA IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
    pAUX_EPP_CD_ESPECPROC IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE DEFAULT NULL,
    pAUX_GPC_CD_GRUPOPROC IN TB_AUX_GPC_GRUPOPROC.AUX_GPC_CD_GRUPOPROC%TYPE DEFAULT NULL,
    pFATURADO   VARCHAR2 DEFAULT NULL,
    pLOTEGERADO VARCHAR2 DEFAULT NULL,
    pAUDITORIA  VARCHAR2 DEFAULT NULL,
    pEMITIDO    VARCHAR2 DEFAULT NULL,
    pDIGITADO   VARCHAR2 DEFAULT NULL,
		pTIS_TAT_CD_TPATENDIMENTO in TB_ATD_ATE_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%type default null,
    pATD_ATE_FL_LIBERA_EMISSAO in TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_LIBERA_EMISSAO%type default null,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_PENDENCIAS
*    DATA ALTERACAO: 09/06/2010  POR: Pedro
*    inclusao do prof, local e setor
*     DATA ALTERACAO: 25/01/2012  POR: Eduardo Hyppolito
*     ALtera¿¿o: Filtrar apenas por atendimentos ativos
*     DATA ALTERACAO: 16/01/2014  POR: André S. Monaco
*     ALtera¿¿o: Adição do parametro pATD_ATE_FL_LIBERA_EMISSAO
*******************************************************************/
V_CURSOR PKG_CURSOR.T_CURSOR;
V_WHERE  varchar2(2000);
  V_SELECT  varchar2(15000);
 begin
    V_WHERE := NULL;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE;
    END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO;
    END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;
    END IF;
    IF pCAD_PLA_ID_PLANO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PAC.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;
    END IF;
    IF pATD_ATE_ID IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.ATD_ATE_ID = ' || pATD_ATE_ID;
    END IF;
    IF pCAD_SET_ID IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID;
    END IF;
    IF pFAT_CCP_MES_FAT IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT;
    END IF;
     IF pFAT_CCP_ANO_FAT IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT;
    END IF;
     IF pCAD_PRD_ID IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.CAD_PRD_ID = ' || pCAD_PRD_ID;
    END IF;
    IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_DT_INICIO_CONSUMO >= ' || chr(39) || pATD_ATE_DT_ATENDIMENTO_INI || chr(39) ;
    END IF;
    IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_DT_FIM_CONSUMO <= ' || chr(39) || pATD_ATE_DT_ATENDIMENTO_FIM || chr(39) ;
    END IF;
    IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PRD.TIS_MED_CD_TABELAMEDICA = ' || chr(39) || pTIS_MED_CD_TABELAMEDICA || chr(39) ;
    END IF;
    IF pAUX_GPC_CD_GRUPOPROC IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PRD.AUX_GPC_CD_GRUPOPROC = ' || chr(39) || pAUX_GPC_CD_GRUPOPROC || chr(39) ;
    END IF;
    IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PRD.AUX_EPP_CD_ESPECPROC = ' || chr(39) || pAUX_EPP_CD_ESPECPROC || chr(39) ;
    END IF;
     IF pCAD_MPF_ID IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND  MPF.CAD_MPF_ID IN (SELECT column_value from table(FNC_SPLIT(' || chr(39) || pCAD_MPF_ID || chr(39) || '))) ';
    END IF;
		IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND  ATE.TIS_TAT_CD_TPATENDIMENTO = ' ||	pTIS_TAT_CD_TPATENDIMENTO;
		END IF;
    IF pATD_ATE_FL_LIBERA_EMISSAO IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND  NVL(ATE.ATD_ATE_FL_LIBERA_EMISSAO, ''N'') = ' ||	chr(39) || pATD_ATE_FL_LIBERA_EMISSAO || chr(39) ;
		END IF;
  IF ( pATD_ATE_ID IS NOT NULL ) THEN
    OPEN V_CURSOR FOR
    SELECT    CNV.CAD_CNV_CD_HAC_PRESTADOR,
              CNV.CAD_CNV_NM_FANTASIA,
              UNI.CAD_UNI_DS_UNIDADE,
              LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
              SETOR.CAD_SET_DS_SETOR,
              CCI.ATD_ATE_ID,
              ATE.ATD_ATE_DT_ATENDIMENTO,
              ATE.ATD_ATE_HR_ATENDIMENTO,
              PES.CAD_PES_NM_PESSOA,
              TAT.TIS_TAT_DS_TPATENDIMENTO,
              MCC.FAT_MCC_ID,
              MPF.CAD_MPF_DS_MOTI_PEND_FATURAR,
              PRD.CAD_PRD_CD_CODIGO,
              PRD.CAD_PRD_DS_DESCRICAO,
              CCP.FAT_CCP_MES_FAT,
              CCP.FAT_CCP_ANO_FAT,
              CCP.FAT_CCP_FL_FATURADA,
              USU.SEG_USU_DS_NOME,
              MPF.CAD_MPF_DT_ULTIMA_ATUALIZACAO,
              CCI.FAT_CCI_DT_ULTIMA_ATUALIZACAO,
              PRO.CAD_PRO_NR_CONSELHO,
              PRO.CAD_PRO_NM_NOME,
              PAC.CAD_PAC_NR_PRONTUARIO PRONTUARIO,             
              CCI.FAT_CCI_DT_ULTIMA_ATUALIZACAO LASTUPDATE
      FROM    TB_FAT_CCI_CONTA_CONSU_ITEM    CCI
      JOIN    TB_FAT_MCC_MOV_COM_CONSUMO     MCC
      ON      MCC.FAT_MCC_ID = CCI.FAT_MCC_ID
      AND     MCC.ATD_ATE_ID = CCI.ATD_ATE_ID
      JOIN    TB_CAD_MPF_MOTI_PEND_FATURAR   MPF
      ON      MPF.CAD_MPF_ID = CCI.CAD_MPF_ID
      JOIN    TB_ATD_ATE_ATENDIMENTO ATE
      ON      ATE.ATD_ATE_ID = CCI.ATD_ATE_ID
      AND     ATE.ATD_ATE_ID = MCC.ATD_ATE_ID
      JOIN    TB_CAD_PAC_PACIENTE PAC
      ON      PAC.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
      JOIN    TB_CAD_CNV_CONVENIO CNV
      ON      CNV.CAD_CNV_ID_CONVENIO = CCI.CAD_CNV_ID_CONVENIO
      JOIN    TB_CAD_PES_PESSOA PES
      ON      PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
      JOIN    TB_TIS_TAT_TP_ATENDIMENTO TAT
      ON      TAT.TIS_TAT_CD_TPATENDIMENTO = ATE.TIS_TAT_CD_TPATENDIMENTO
      JOIN    TB_CAD_UNI_UNIDADE UNI
      ON      UNI.CAD_UNI_ID_UNIDADE = CCI.CAD_UNI_ID_UNIDADE
      JOIN    TB_CAD_PRD_PRODUTO PRD
      ON      CCI.CAD_PRD_ID = PRD.CAD_PRD_ID
      JOIN    TB_SEG_USU_USUARIO USU
      ON      USU.SEG_USU_ID_USUARIO = CCI.SEG_USU_ID_USUARIO
      LEFT JOIN    TB_CAD_PRO_PROFISSIONAL PRO
      ON      PRO.CAD_PRO_ID_PROFISSIONAL = CCI.CAD_PRO_ID_PROFISSIONAL
      JOIN    TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
      ON      LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO  = CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO
      JOIN    TB_CAD_SET_SETOR SETOR
      ON      SETOR.CAD_SET_ID = ATE.CAD_SET_ID
      LEFT    JOIN TB_FAT_CCP_CONTA_CONS_PARC CCP
      ON      CCP.FAT_CCP_ID = CCI.FAT_CCP_ID
      AND     CCP.ATD_ATE_ID = CCI.ATD_ATE_ID
      AND     CCP.FAT_COC_ID = CCI.FAT_COC_ID
      AND     CCP.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
      AND     (CCP.FAT_CCP_FL_STATUS = 'A')
      AND     (CCP.FAT_CCP_FL_FATURADA = 'N')
     WHERE    (CCI.FAT_CCI_FL_STATUS = 'A')
     AND     (MCC.FAT_MCC_FL_STATUS = 'A')
     AND     (CCI.ATD_ATE_ID = pATD_ATE_ID)
     AND     (CCI.FAT_CCI_TP_DESTINO_ITEM <> 'H')
		 and     mpf.cad_mpf_fl_motivo = 'P'
     ORDER   BY  CNV.CAD_CNV_CD_HAC_PRESTADOR, PES.CAD_PES_NM_PESSOA;
  IO_CURSOR := V_CURSOR;
  ELSE
IF ( pFAT_FCL_NR_SEQ_LOTE IS NULL ) THEN
    V_SELECT :=
   ' SELECT  CNV.CAD_CNV_CD_HAC_PRESTADOR,
              CNV.CAD_CNV_NM_FANTASIA,
              UNI.CAD_UNI_DS_UNIDADE,
              LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
              SETOR.CAD_SET_DS_SETOR,
              CCI.ATD_ATE_ID,
              ATE.ATD_ATE_DT_ATENDIMENTO,
              ATE.ATD_ATE_HR_ATENDIMENTO,
              PES.CAD_PES_NM_PESSOA,
              TAT.TIS_TAT_DS_TPATENDIMENTO,
              MCC.FAT_MCC_ID,
              MPF.CAD_MPF_DS_MOTI_PEND_FATURAR,
              PRD.CAD_PRD_CD_CODIGO,
              PRD.CAD_PRD_DS_DESCRICAO,
              CCP.FAT_CCP_MES_FAT,
              CCP.FAT_CCP_ANO_FAT,
              CCP.FAT_CCP_FL_FATURADA,
              USU.SEG_USU_DS_NOME,
              MPF.CAD_MPF_DT_ULTIMA_ATUALIZACAO,
              CCI.FAT_CCI_DT_ULTIMA_ATUALIZACAO,
              PRO.CAD_PRO_NR_CONSELHO,
              PRO.CAD_PRO_NM_NOME,
              CASE WHEN CCP.FAT_NOF_ID IS NOT NULL THEN ' || chr(39) || 'FATURADO' || chr(39) || '
                   WHEN CCP.FAT_CCP_FL_STATUS_AUDIT = ' ||chr(39)||'E' ||chr(39)|| ' THEN ' || chr(39) || 'EM ANALISE' || chr(39) || '
                   WHEN CCP.FAT_CCP_FL_FATURADA = ' ||chr(39)||'S'|| chr(39)|| ' AND CCP.FAT_NOF_ID IS NULL THEN ' || chr(39) || 'LOTE GERADO' || chr(39) || '
                   WHEN CCP.FAT_CCP_FL_EMITIDA = ' || chr(39) || 'S' || chr(39) || ' AND CCP.FAT_CCP_FL_FATURADA = ' || chr(39) || 'N' || chr(39) || ' AND
                   (CCP.FAT_CCP_FL_STATUS_AUDIT = ' || chr(39) || 'A' || chr(39) || ' OR CCP.FAT_CCP_DT_ENVIO_AUDIT IS NULL)  THEN ' || chr(39) || 'EMITIDO' || chr(39) || '
                   WHEN CCI.FAT_CCP_ID IS NULL THEN                                                ' || chr(39) || 'DIGITADO' || chr(39) || '
              END SITUACAO,
              PAC.CAD_PAC_NR_PRONTUARIO PRONTUARIO,             
              CCI.FAT_CCI_DT_ULTIMA_ATUALIZACAO LASTUPDATE
      FROM    TB_FAT_CCI_CONTA_CONSU_ITEM CCI
      JOIN    TB_FAT_MCC_MOV_COM_CONSUMO MCC
      ON      MCC.FAT_MCC_ID = CCI.FAT_MCC_ID
      AND     MCC.ATD_ATE_ID = CCI.ATD_ATE_ID
      JOIN    TB_CAD_MPF_MOTI_PEND_FATURAR MPF
      ON      MPF.CAD_MPF_ID = CCI.CAD_MPF_ID
      JOIN    TB_ATD_ATE_ATENDIMENTO ATE
      ON      ATE.ATD_ATE_ID = CCI.ATD_ATE_ID
      AND     ATE.ATD_ATE_ID = MCC.ATD_ATE_ID
      JOIN    TB_CAD_PAC_PACIENTE PAC
      ON      PAC.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
      JOIN    TB_CAD_CNV_CONVENIO CNV
      ON      CNV.CAD_CNV_ID_CONVENIO = CCI.CAD_CNV_ID_CONVENIO
      JOIN    TB_CAD_PES_PESSOA PES
      ON      PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
      JOIN    TB_TIS_TAT_TP_ATENDIMENTO TAT
      ON      TAT.TIS_TAT_CD_TPATENDIMENTO = ATE.TIS_TAT_CD_TPATENDIMENTO
      JOIN    TB_CAD_UNI_UNIDADE UNI
      ON      UNI.CAD_UNI_ID_UNIDADE = CCI.CAD_UNI_ID_UNIDADE
      JOIN    TB_CAD_PRD_PRODUTO PRD
      ON      CCI.CAD_PRD_ID = PRD.CAD_PRD_ID
      JOIN    TB_SEG_USU_USUARIO USU
      ON      USU.SEG_USU_ID_USUARIO = CCI.SEG_USU_ID_USUARIO
      LEFT JOIN    TB_CAD_PRO_PROFISSIONAL PRO
      ON      PRO.CAD_PRO_ID_PROFISSIONAL = CCI.CAD_PRO_ID_PROFISSIONAL
      JOIN    TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
      ON      LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO  = CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO
      JOIN    TB_CAD_SET_SETOR SETOR
      ON      SETOR.CAD_SET_ID = ATE.CAD_SET_ID
      LEFT    JOIN TB_FAT_CCP_CONTA_CONS_PARC CCP
      ON      CCP.FAT_CCP_ID = CCI.FAT_CCP_ID
      AND     CCP.ATD_ATE_ID = CCI.ATD_ATE_ID
      AND     CCP.FAT_COC_ID = CCI.FAT_COC_ID
      AND     CCP.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
      AND     (CCP.FAT_CCP_FL_STATUS = ' || chr(39) || 'A' || chr(39) || ')
     WHERE    (CCI.FAT_CCI_FL_STATUS = ' || chr(39) || 'A' || chr(39) || ')
      AND     (CCI.FAT_CCI_TP_DESTINO_ITEM <> ' || chr(39) || 'H' || chr(39) || ')
      AND     (MCC.FAT_MCC_FL_STATUS = ' || chr(39)|| 'A' || chr(39) || ')
      AND     (UNI.CAD_UNI_FL_FATURA_UNID_OK = ' ||chr(39)|| 'S' ||chr(39)|| ')
     '
     || V_WHERE ||
     '
               AND     ((' ||chr(39)|| pFATURADO  || chr(39) || ' IS NOT NULL AND CCP.FAT_NOF_ID IS NOT NULL )
              OR  (' || chr(39) || pAUDITORIA  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_STATUS_AUDIT = ' || chr(39) || 'E' || chr(39) || ')
              OR  (' || chr(39) || pLOTEGERADO  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_FATURADA = ' || chr(39) || 'S' || chr(39) || ' AND CCP.FAT_NOF_ID IS NULL)
              OR  (' || chr(39) || pEMITIDO  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_EMITIDA = ' || chr(39) || 'S' || chr(39) || ' AND CCP.FAT_CCP_FL_FATURADA = ' || chr(39) || 'N' || chr(39) || '
                  AND (CCP.FAT_CCP_FL_STATUS_AUDIT = ' || chr(39) || 'A' || chr(39) || ' OR CCP.FAT_CCP_DT_ENVIO_AUDIT IS NULL))
              OR  (' || chr(39) || pDIGITADO  || chr(39) || ' IS NOT NULL AND CCI.FAT_CCP_ID IS NULL))
              AND (' || chr(39) || pATD_ATE_TP_PACIENTE_A  || chr(39) || ' IS not NULL and CCI.ATD_ATE_TP_PACIENTE = ' || chr(39) || 'A' || chr(39) || '
               OR ' || chr(39) || pATD_ATE_TP_PACIENTE_U || chr(39) || ' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = ' || chr(39) || 'U' || chr(39) || '
               OR ' || chr(39) || pATD_ATE_TP_PACIENTE_I || chr(39) || ' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = ' || chr(39) || 'I' || chr(39) || '
               OR ' || chr(39) || pATD_ATE_TP_PACIENTE_E || chr(39) || ' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = ' || chr(39) || 'E' || chr(39) || ')
              AND (' || chr(39) || pCAD_PLA_CD_TIPOPLANO_GB  || chr(39) || ' IS not NULL and CNV.CAD_TPE_CD_CODIGO = ' || chr(39) || 'ACS' || chr(39) || '
               OR ' || chr(39) ||  pCAD_PLA_CD_TIPOPLANO_PA  || chr(39) || ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ' || chr(39) || 'PA' || chr(39) || '
               OR ' || chr(39) ||  pCAD_PLA_CD_TIPOPLANO_SP  || chr(39) || ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ' || chr(39) || 'SP' || chr(39) || '
               OR ' || chr(39) ||  pCAD_PLA_CD_TIPOPLANO_NP  || chr(39) || ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ' || chr(39) || 'NP' || chr(39) || '
               OR ' || chr(39) ||  pCAD_PLA_CD_TIPOPLANO_FU  || chr(39) || ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ' || chr(39) || 'FU' || chr(39) || ')
     ORDER   BY  CNV.CAD_CNV_CD_HAC_PRESTADOR, PES.CAD_PES_NM_PESSOA';
      OPEN V_CURSOR FOR
      V_SELECT;
  IO_CURSOR := V_CURSOR;
ELSE
  OPEN V_CURSOR FOR
     SELECT  CNV.CAD_CNV_CD_HAC_PRESTADOR,
                CNV.CAD_CNV_NM_FANTASIA,
                UNI.CAD_UNI_DS_UNIDADE,
                 LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
              SETOR.CAD_SET_DS_SETOR,
                CCI.ATD_ATE_ID,
                ATE.ATD_ATE_DT_ATENDIMENTO,
                ATE.ATD_ATE_HR_ATENDIMENTO,
                PES.CAD_PES_NM_PESSOA,
                TAT.TIS_TAT_DS_TPATENDIMENTO,
                MCC.FAT_MCC_ID,
                MPF.CAD_MPF_DS_MOTI_PEND_FATURAR,
                PRD.CAD_PRD_CD_CODIGO,
                PRD.CAD_PRD_DS_DESCRICAO,
                CCP.FAT_CCP_MES_FAT,
                CCP.FAT_CCP_ANO_FAT,
                CCP.FAT_CCP_FL_FATURADA,
                USU.SEG_USU_DS_NOME,
                MPF.CAD_MPF_DT_ULTIMA_ATUALIZACAO,
                CCI.FAT_CCI_DT_ULTIMA_ATUALIZACAO,
                PRO.CAD_PRO_NR_CONSELHO,
                PRO.CAD_PRO_NM_NOME,
                FCL.FAT_FCL_NR_SEQ_LOTE,
                PAC.CAD_PAC_NR_PRONTUARIO PRONTUARIO,             
                CCI.FAT_CCI_DT_ULTIMA_ATUALIZACAO LASTUPDATE
        FROM    TB_FAT_CCI_CONTA_CONSU_ITEM CCI
        JOIN    TB_FAT_MCC_MOV_COM_CONSUMO MCC
        ON      MCC.FAT_MCC_ID = CCI.FAT_MCC_ID
        AND     MCC.ATD_ATE_ID = CCI.ATD_ATE_ID
        JOIN    TB_CAD_MPF_MOTI_PEND_FATURAR MPF
        ON      MPF.CAD_MPF_ID = CCI.CAD_MPF_ID
        JOIN    TB_ATD_ATE_ATENDIMENTO ATE
        ON      ATE.ATD_ATE_ID = CCI.ATD_ATE_ID
        AND     ATE.ATD_ATE_ID = MCC.ATD_ATE_ID
        JOIN    TB_CAD_PAC_PACIENTE PAC
        ON      PAC.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
        JOIN    TB_CAD_CNV_CONVENIO CNV
        ON      CNV.CAD_CNV_ID_CONVENIO = CCI.CAD_CNV_ID_CONVENIO
       JOIN    TB_CAD_PES_PESSOA PES
        ON      PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
        JOIN    TB_TIS_TAT_TP_ATENDIMENTO TAT
        ON      TAT.TIS_TAT_CD_TPATENDIMENTO = ATE.TIS_TAT_CD_TPATENDIMENTO
        JOIN    TB_CAD_UNI_UNIDADE UNI
        ON      UNI.CAD_UNI_ID_UNIDADE = CCI.CAD_UNI_ID_UNIDADE
        JOIN    TB_CAD_PRD_PRODUTO PRD
        ON      CCI.CAD_PRD_ID = PRD.CAD_PRD_ID
        JOIN    TB_SEG_USU_USUARIO USU
        ON      USU.SEG_USU_ID_USUARIO = CCI.SEG_USU_ID_USUARIO
        LEFT JOIN    TB_CAD_PRO_PROFISSIONAL PRO
        ON      PRO.CAD_PRO_ID_PROFISSIONAL = CCI.CAD_PRO_ID_PROFISSIONAL
        JOIN    TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
        ON      LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO  = CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO
        JOIN    TB_CAD_SET_SETOR SETOR
        ON      SETOR.CAD_SET_ID = ATE.CAD_SET_ID
       LEFT    JOIN TB_FAT_CCP_CONTA_CONS_PARC CCP
        ON      CCP.FAT_CCP_ID = CCI.FAT_CCP_ID
        AND     CCP.ATD_ATE_ID = CCI.ATD_ATE_ID
        AND     CCP.FAT_COC_ID = CCI.FAT_COC_ID
        AND     CCP.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
        AND     (CCP.FAT_CCP_FL_STATUS = 'A')
        AND     (CCP.FAT_CCP_FL_FATURADA = 'N')
        JOIN    TB_FAT_FCL_CONTR_EMI_LOTE FCL
        ON      FCL.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
        AND     FCL.ATD_ATE_ID          = CCI.ATD_ATE_ID
       WHERE    (CCI.FAT_CCI_FL_STATUS = 'A')
       AND     (MCC.FAT_MCC_FL_STATUS = 'A')
       AND     (CCI.FAT_CCI_TP_DESTINO_ITEM <> 'H')
			 and     mpf.cad_mpf_fl_motivo = 'P'
       AND    (FCL.FAT_FCL_NR_SEQ_LOTE = pFAT_FCL_NR_SEQ_LOTE)
  ;
  IO_CURSOR := V_CURSOR;
END IF;
END IF;
END PRC_FAT_REL_PENDENCIAS;
 