create or replace procedure PRC_FAT_CCI_SEGMENTOSADT
(    
    pATS_ATE_CD_INTLIB IN    TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_CD_INTLIB%TYPE,
    pATS_ATE_IN_INTLIB IN    TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_IN_INTLIB%TYPE,
    pATS_ATE_ID        IN    TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_ID%TYPE,
    pTIS_MED_CD_TABELAMEDICA IN TB_ATS_ATE_ATENDIMENTO_SADT.TIS_MED_CD_TABELAMEDICA%TYPE,
    pAUX_EPP_CD_ESPECPROC IN    TB_ATS_ATE_ATENDIMENTO_SADT.AUX_EPP_CD_ESPECPROC%TYPE,
    pCAD_PRD_ID IN    TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRD_ID%TYPE,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
/*******************************************************************
* Obter Segmento (Marcus Relva 26/10/2010)
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
begin

   OPEN v_cursor FOR
   SELECT COUNT(*) AS QTD,
       ATS.ATS_ATE_ID,
       ATS.ATS_ATE_CD_INTLIB,
       PRD.CAD_PRD_NM_MNEMONICO,
       PRD.CAD_PRD_CD_CODIGO,
       PRD.CAD_PRD_CD_CODIGO_AMB92,
       PRD.CAD_PRD_ID
  FROM TB_ATS_ATE_ATENDIMENTO_SADT   ATS,
       TB_CAD_PRD_PRODUTO            PRD,
       TB_CAD_UNI_UNIDADE            UNI,
       TB_CAD_SET_SETOR              SETOR,
       TB_ATS_APL_ATEN_PROCED_LAUDO  APL,
       TB_ATS_APS_ATEN_PROC_SEGMENTO APS
 WHERE ATS.CAD_SET_ID_ATEN = SETOR.CAD_SET_ID
   AND SETOR.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
   AND ATS.ATS_ATE_ID = APL.ATS_ATE_ID
   AND ATS.AUX_EPP_CD_ESPECPROC = APL.AUX_EPP_CD_ESPECPROC
   AND ATS.ATS_ATE_IN_INTLIB = APL.ATS_ATE_IN_INTLIB
   AND ATS.ATS_ATE_CD_INTLIB = APL.ATS_ATE_CD_INTLIB
   AND ATS.CAD_PRD_ID = APL.CAD_PRD_ID
   -- AND ATS.ATS_ATE_ATU_INTERF_LEGADO IS NULL
   AND ATS.ATS_ATE_FL_STATUS = 'A'
   AND ATS.ATS_ATE_ID = APS.ATS_ATE_ID
   AND ATS.AUX_EPP_CD_ESPECPROC = APS.AUX_EPP_CD_ESPECPROC
   AND ATS.ATS_ATE_IN_INTLIB = APS.ATS_ATE_IN_INTLIB
   AND ATS.ATS_ATE_CD_INTLIB = APS.ATS_ATE_CD_INTLIB
   AND ATS.CAD_PRD_ID = APS.CAD_PRD_ID
   AND APS.CAD_PRD_ID != APS.CAD_PRD_ID_APS
   AND APS.CAD_PRD_ID_APS = PRD.CAD_PRD_ID
   AND ATS.ATS_ATE_CD_INTLIB	   = pATS_ATE_CD_INTLIB
   AND ATS.ATS_ATE_IN_INTLIB       = pATS_ATE_IN_INTLIB
   AND ATS.ATS_ATE_ID              = pATS_ATE_ID
   AND ATS.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA
   AND ATS.AUX_EPP_CD_ESPECPROC    = pAUX_EPP_CD_ESPECPROC
   AND ATS.CAD_PRD_ID              = pCAD_PRD_ID    
 GROUP BY ATS.ATS_ATE_ID,
          ATS.ATS_ATE_CD_INTLIB,
          PRD.CAD_PRD_NM_MNEMONICO,
          PRD.CAD_PRD_CD_CODIGO,
          PRD.CAD_PRD_CD_CODIGO_AMB92,
          PRD.CAD_PRD_ID;               
io_cursor := v_cursor;
end PRC_FAT_CCI_SEGMENTOSADT;
