--PRC_ASS_ULP_UNID_LOCAL_PROCE_L
create or replace procedure PRC_ASS_ULP_UNID_LOCAL_PROCE_L 
(
     pASS_ULP_ID IN TB_ASS_ULP_UNID_LOCAL_PROCED.ASS_ULP_ID%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE IN TB_ASS_ULP_UNID_LOCAL_PROCED.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_ULP_UNID_LOCAL_PROCED.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROCED IN TB_ASS_ULP_UNID_LOCAL_PROCED.AUX_EPP_CD_ESPECPROCED%type DEFAULT NULL,
     pAUX_GPC_CD_GRUPOPROC IN TB_ASS_ULP_UNID_LOCAL_PROCED.AUX_GPC_CD_GRUPOPROC%type DEFAULT NULL,
     pCAD_PRD_CD_CODIGO IN TB_ASS_ULP_UNID_LOCAL_PROCED.CAD_PRD_CD_CODIGO%type DEFAULT NULL,
     pASS_ULP_FL_STATUS IN TB_ASS_ULP_UNID_LOCAL_PROCED.ASS_ULP_FL_STATUS%type DEFAULT NULL,
     pASS_ULP_DT_ULTIMA_ATUALIZACAO IN TB_ASS_ULP_UNID_LOCAL_PROCED.ASS_ULP_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ASS_ULP_UNID_LOCAL_PROCED.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pCAD_SET_ID IN TB_ASS_ULP_UNID_LOCAL_PROCED.CAD_SET_ID%type DEFAULT NULL,
     pAGE_SAU_ID IN TB_ASS_ULP_UNID_LOCAL_PROCED.AGE_SAU_ID%type DEFAULT NULL,
     pASS_ULP_QT_HORA_RESERVADA IN TB_ASS_ULP_UNID_LOCAL_PROCED.ASS_ULP_QT_HORA_RESERVADA%type DEFAULT NULL,
     pASS_ULP_FL_LIB_AGE_SADT IN TB_ASS_ULP_UNID_LOCAL_PROCED.ASS_ULP_FL_LIB_AGE_SADT%type DEFAULT NULL,
     pASS_ULP_FL_EXI_PREP_AGESADT IN TB_ASS_ULP_UNID_LOCAL_PROCED.ASS_ULP_FL_EXI_PREP_AGESADT%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ASS_ULP_UNID_LOCAL_PROCED.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pCAD_PRD_ID IN TB_ASS_ULP_UNID_LOCAL_PROCED.CAD_PRD_ID%type DEFAULT NULL,
     pASS_ULP_HR_LIMITE_AGE_SADT IN TB_ASS_ULP_UNID_LOCAL_PROCED.ASS_ULP_HR_LIMITE_AGE_SADT%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
/********************************************************************
*    Procedure: PRC_ASS_ULP_UNID_LOCAL_PROCE_L
* 
*    Data Criacao: 	data da  criação   Por: Nome do Analista
*    Data Alteracao:	data da alteração  Por: Nome do Analista
*
*    Funcao: Descrição da funcionalidade da Stored Procedure
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
begin
  V_WHERE := NULL;
  IF pASS_ULP_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_ULP_ID = ' || pASS_ULP_ID; END IF;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pAUX_EPP_CD_ESPECPROCED IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND AUX_EPP_CD_ESPECPROCED = ' || CHR(39) || pAUX_EPP_CD_ESPECPROCED || CHR(39); END IF;
IF pAUX_GPC_CD_GRUPOPROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND AUX_GPC_CD_GRUPOPROC = ' || CHR(39) || pAUX_GPC_CD_GRUPOPROC || CHR(39); END IF;
IF pCAD_PRD_CD_CODIGO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_PRD_CD_CODIGO = ' || CHR(39) || pCAD_PRD_CD_CODIGO || CHR(39); END IF;
IF pASS_ULP_FL_STATUS IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_ULP_FL_STATUS = ' || CHR(39) || pASS_ULP_FL_STATUS || CHR(39); END IF;
IF pASS_ULP_DT_ULTIMA_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_ULP_DT_ULTIMA_ATUALIZACAO = ' || CHR(39) || pASS_ULP_DT_ULTIMA_ATUALIZACAO || CHR(39); END IF;
IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pAGE_SAU_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND AGE_SAU_ID = ' || pAGE_SAU_ID; END IF;
IF pASS_ULP_QT_HORA_RESERVADA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_ULP_QT_HORA_RESERVADA = ' || pASS_ULP_QT_HORA_RESERVADA; END IF;
IF pASS_ULP_FL_LIB_AGE_SADT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_ULP_FL_LIB_AGE_SADT = ' || CHR(39) || pASS_ULP_FL_LIB_AGE_SADT || CHR(39); END IF;
IF pASS_ULP_FL_EXI_PREP_AGESADT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_ULP_FL_EXI_PREP_AGESADT = ' || CHR(39) || pASS_ULP_FL_EXI_PREP_AGESADT || CHR(39); END IF;
IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND TIS_MED_CD_TABELAMEDICA = ' || CHR(39) || pTIS_MED_CD_TABELAMEDICA || CHR(39); END IF;
IF pCAD_PRD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_PRD_ID = ' || pCAD_PRD_ID; END IF;
IF pASS_ULP_HR_LIMITE_AGE_SADT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_ULP_HR_LIMITE_AGE_SADT = ' || pASS_ULP_HR_LIMITE_AGE_SADT; END IF;
 
   V_SELECT := '
SELECT	
       ASS_ULP_ID,
       CAD_UNI_ID_UNIDADE,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       AUX_EPP_CD_ESPECPROCED,
       AUX_GPC_CD_GRUPOPROC,
       CAD_PRD_CD_CODIGO,
       ASS_ULP_FL_STATUS,
       ASS_ULP_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       CAD_SET_ID,
       AGE_SAU_ID,
       ASS_ULP_QT_HORA_RESERVADA,
       ASS_ULP_FL_LIB_AGE_SADT,
       ASS_ULP_FL_EXI_PREP_AGESADT,
       TIS_MED_CD_TABELAMEDICA,
       CAD_PRD_ID,
       ASS_ULP_HR_LIMITE_AGE_SADT
FROM TB_ASS_ULP_UNID_LOCAL_PROCED
WHERE null is null  '    ;
       
OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_ASS_ULP_UNID_LOCAL_PROCE_L;
