CREATE OR REPLACE PROCEDURE PRC_AGS_EPP_ESPECPROC_S
(
     pCAD_UNI_ID_UNIDADE IN TB_ASS_ULP_UNID_LOCAL_PROCED.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ASS_ULP_UNID_LOCAL_PROCED.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
     pFL_CECI varchar2 default null,
       io_cursor OUT PKG_CURSOR.t_cursor
)
IS

v_cursor PKG_CURSOR.t_cursor;

  BEGIN
   OPEN v_cursor FOR
   
      SELECT  
            EPP.AUX_EPP_CD_ESPECPROC,
            EPP.AUX_EPP_DS_DESCRICAO 
       FROM TB_ASS_ULP_UNID_LOCAL_PROCED ULP,
            TB_CAD_PRD_PRODUTO PRD,
            TB_CAD_SET_SETOR SETOR,
            TB_AUX_EPP_ESPECPROC EPP
       WHERE
           ULP.CAD_PRD_ID                = PRD.CAD_PRD_ID
      AND  ULP.CAD_SET_ID                = SETOR.CAD_SET_ID
      AND  ULP.AUX_EPP_CD_ESPECPROCED    = EPP.AUX_EPP_CD_ESPECPROC
      AND  (ULP.ASS_ULP_FL_LIB_AGE_SADT  =     'S')
      AND  (ULP.TIS_MED_CD_TABELAMEDICA  = DECODE(pTIS_MED_CD_TABELAMEDICA, NULL, '90', pTIS_MED_CD_TABELAMEDICA))
      AND  (pCAD_UNI_ID_UNIDADE IS NULL OR ULP.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
      AND  (
           (pFL_CECI = 'S' AND SETOR.CAD_SET_DS_SETOR  = 'CENTRO CIRURGICO') OR
           (pFL_CECI = 'N' AND SETOR.CAD_SET_DS_SETOR != 'CENTRO CIRURGICO') OR
           (pFL_CECI IS NULL)
           )
      GROUP BY EPP.AUX_EPP_CD_ESPECPROC, EPP.AUX_EPP_DS_DESCRICAO
      ORDER BY EPP.AUX_EPP_DS_DESCRICAO;

io_cursor := v_cursor;

END PRC_AGS_EPP_ESPECPROC_S;
/
