create or replace procedure PRC_INT_REL_PAC_IMS
(
  pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
  pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
  pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
  pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,  
  pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
  pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
  io_cursor              OUT PKG_CURSOR.t_cursor) is
  /********************************************************************
  *    Procedure: PRC_INT_REL_PAC_IMS
  *
  *    Data Criacao:  04/05/2010   Por: Andre Souza Monaco
  *    Data Alteracao:03/11/2011   Por:Eduardo Hyppolito 
  *    Alteração: Campo Instituto Geriatria (LEFT JOIN BENEFICIARIO)
  *    Funcao: Popula o Relatorio (INT_17_PAC_ADMISSAO) de Pacientes na 
  *            TB_ATD_IMS_INT_MOV_SETOR sem data de saida
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
begin
  OPEN v_cursor FOR
     SELECT DISTINCT
                   ATD.ATD_ATE_ID,
                   PAC.CAD_PAC_CD_CREDENCIAL,
                   PAC.CAD_PAC_NR_PRONTUARIO,
                   PES.CAD_PES_NM_PESSOA PACIENTE,
                   PES.CAD_PES_DT_NASCIMENTO,
                   DECODE(AIC.ATD_AIC_TP_SITUACAO_PAC,'I','INTERNADO','A','ALTA') ATD_AIC_TP_SITUACAO_PAC,
                   DECODE(ATD_ATE_TP_PACIENTE,'I','INTERNO','E','EXTERNO') ATD_ATE_TP_PACIENTE,
                   CNV.CAD_CNV_CD_HAC_PRESTADOR,
                   PLA.CAD_PLA_CD_TIPOPLANO,
                   PLA.CAD_PLA_CD_PLANO_HAC,
                   ATD.ATD_ATE_DT_ATENDIMENTO,
                   ATD.ATD_ATE_HR_ATENDIMENTO,
                   PRO.CAD_PRO_NM_NOME PROFISSIONAL,
                   PRO.CAD_PRO_NR_CONSELHO,
                   IGE_BNF.GER,
                   PRO.CAD_PRO_SG_UF_CONSELHO
                   ,
           DECODE(PES.CAD_PES_FL_CUIDADOINTEGRAL,1,'SAVE1',2,'SAVE2',3,'SAVE3') CAD_PES_FL_CUIDADOINTEGRAL,
                CASE WHEN PES.CAD_PES_FL_ISOLAMENTO = 'S' THEN 'ISOLAMENTO' ELSE NULL END CAD_PES_FL_ISOLAMENTO
      FROM
                    TB_ATD_ATE_ATENDIMENTO    ATD
      JOIN          TB_ASS_PAT_PACIEATEND     PAT
      ON            PAT.ATD_ATE_ID          = ATD.ATD_ATE_ID
      JOIN          TB_CAD_PAC_PACIENTE       PAC
      ON            PAC.CAD_PAC_ID_PACIENTE = PAT.CAD_PAC_ID_PACIENTE
      JOIN          TB_CAD_PES_PESSOA         PES
      ON            PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
      JOIN          TB_CAD_CNV_CONVENIO       CNV
      ON            CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
      JOIN          TB_CAD_PLA_PLANO          PLA
      ON            PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
      LEFT JOIN     TB_ATD_IMS_INT_MOV_SETOR  IMS
      ON            IMS.ATD_ATE_ID          = ATD.ATD_ATE_ID 
      JOIN          TB_ATD_AIC_ATE_INT_COMPL  AIC
      ON            AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
      JOIN          TB_CAD_PRO_PROFISSIONAL     PRO
      ON            PRO.CAD_PRO_ID_PROFISSIONAL = ATD.CAD_PRO_ID_PROF_EXEC
      LEFT JOIN    (SELECT BNF_SIT.DESSITBEN, BNF.DATINGCONBEN, BNF.DATSITBEN, BNF.DATALTBEN,PAC.CAD_PAC_ID_PACIENTE,
      DECODE       (FNC_VERIFICA_INSGER(BNF.CODCON, BNF.CODEST, BNF.CODBEN, BNF.CODSEQBEN),0,'',1,'I.GER',2,'I.GER',4,'A.ALTA') GER
      FROM          TB_CAD_PAC_PACIENTE       PAC
      JOIN          TB_CAD_PLA_PLANO          PLA
      ON            PAC.CAD_PLA_ID_PLANO    = PLA.CAD_PLA_ID_PLANO
      JOIN          BNF_BENEFICIARIO          BNF
      ON            TO_CHAR(BNF.CODCON)     = TO_CHAR(PLA.CAD_PLA_CD_PLANO_HAC)
      AND           BNF.CODEST              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,0,3))
      AND           BNF.CODBEN              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,4,7))
      AND           BNF.CODSEQBEN           = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,11,2))
      JOIN          BNF_SITUACAO_BENEF        BNF_SIT
      ON            BNF_SIT.CODSITBEN       = BNF.CODSITBEN

      WHERE         pac.CAD_CNV_ID_CONVENIO = 281

      ) IGE_BNF
      ON           IGE_BNF.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE 
       WHERE
           (pCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
       AND (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
       AND (pCAD_SET_ID IS NULL OR IMS.CAD_SET_ID_SETOR = pCAD_SET_ID)
       AND (pATD_AIC_TP_SITUACAO_PAC IS NULL OR AIC.ATD_AIC_TP_SITUACAO_PAC = pATD_AIC_TP_SITUACAO_PAC)
       AND (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
       AND (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)   
       AND (IMS.ATD_IMS_DT_SAIDA IS NULL AND IMS.ATD_IMS_FL_STATUS = 'A')
       AND (ATD.ATD_ATE_FL_STATUS = 'A')
       ORDER BY PES.CAD_PES_NM_PESSOA;
  io_cursor := v_cursor;
end PRC_INT_REL_PAC_IMS;
