CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_ALTAS_COM_FATURA"
(
    pATD_INA_DT_ALTA_ADM_INI IN TB_ATD_INA_INT_ALTA.ATD_INA_DT_ALTA_ADM%TYPE DEFAULT NULL,
    pATD_INA_DT_ALTA_ADM_FIM IN TB_ATD_INA_INT_ALTA.ATD_INA_DT_ALTA_ADM%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
    pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pTIS_TIN_CD_INTER IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
    pTIS_TRI_CD_TP_REGINT IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
    pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
    pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNID_PROC    IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNID_PROC%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR
    --, TESTE OUT LONG
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_ALTAS_COM_FATURA
*    DATA ALTERACAO: 04/09/2013  POR: Pedro
*    ALTERAÇÃO: V_SELECT CUSTO
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_SELECT  varchar2(22000);
begin
  V_WHERE := NULL;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pCAD_PLA_ID_PLANO IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND CCP.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;    END IF;

IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRUNC(CCP.FAT_CCP_DT_PARCELA) >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);    END IF;
IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRUNC(CCP.FAT_CCP_DT_PARCELA) <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);    END IF;
IF pCAD_PRO_ID_PROF_EXEC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_PRO_ID_PROF_EXEC = ' || pCAD_PRO_ID_PROF_EXEC; END IF;

IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.TIS_CBO_CD_CBOS = ' || chr(39) || pTIS_CBO_CD_CBOS || chr(39) ;    END IF;
IF pCAD_PRD_ID  IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND AIC.CAD_PRD_ID  = ' || pCAD_PRD_ID ;    END IF;
IF pCAD_UNI_ID_UNID_PROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_UNI_ID_UNID_PROC = ' || pCAD_UNI_ID_UNID_PROC; END IF;
IF pTIS_TIN_CD_INTER IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TIN.TIS_TIN_CD_INTERNACAO = ' || chr(39) || pTIS_TIN_CD_INTER || chr(39) ;    END IF;
IF pTIS_TRI_CD_TP_REGINT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRI.TIS_TRI_CD_TP_REGINTERNACAO = ' || chr(39) || pTIS_TRI_CD_TP_REGINT || chr(39) ;    END IF;
 
   
V_SELECT:=
'
    SELECT  CCP.ATD_ATE_TP_PACIENTE,
            CNV.CAD_CNV_CD_HAC_PRESTADOR,
            CNV.CAD_CNV_NM_FANTASIA,
            UNI.CAD_UNI_CD_UNID_HOSPITALAR,
            UNI.CAD_UNI_DS_UNIDADE,
            PAC.CAD_PAC_NR_PRONTUARIO,
            CCP.ATD_ATE_ID,
            PES.CAD_PES_NM_PESSOA,
            ATE.ATD_ATE_DT_ATENDIMENTO,
            CASE WHEN CCP.ATD_ATE_TP_PACIENTE != '||chr(39)||'I'||chr(39)||' THEN  ATE.ATD_ATE_DT_ATENDIMENTO
                 ELSE NVL(CCP.FAT_CCP_DT_PARCELA,INA.ATD_INA_DT_ALTA_ADM)
            END DT_ALTA,
            CCP.FAT_CCP_ID,
            CCP.FAT_CCP_MES_FAT,
            CCP.FAT_CCP_ANO_FAT,
            CCP.FAT_CCP_VL_TOT_CONTA
    FROM    TB_FAT_CCP_CONTA_CONS_PARC CCP
    JOIN    TB_ATD_ATE_ATENDIMENTO    ATE    ON      ATE.ATD_ATE_ID          = CCP.ATD_ATE_ID
    JOIN    TB_CAD_PAC_PACIENTE       PAC    ON      PAC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
    JOIN    TB_CAD_CNV_CONVENIO       CNV    ON      CNV.CAD_CNV_ID_CONVENIO = CCP.CAD_CNV_ID_CONVENIO
    JOIN    TB_CAD_PES_PESSOA         PES    ON      PAC.CAD_PES_ID_PESSOA   = PES.CAD_PES_ID_PESSOA
    JOIN    TB_TIS_TAT_TP_ATENDIMENTO TAT    ON      TAT.TIS_TAT_CD_TPATENDIMENTO = ATE.TIS_TAT_CD_TPATENDIMENTO
    JOIN    TB_CAD_UNI_UNIDADE        UNI    ON      UNI.CAD_UNI_ID_UNIDADE  = CCP.CAD_UNI_ID_UNIDADE
    LEFT JOIN    TB_ATD_INA_INT_ALTA  INA    ON      INA.ATD_ATE_ID          = CCP.ATD_ATE_ID
    JOIN    TB_CAD_PLA_PLANO          PLA    ON      PLA.CAD_PLA_ID_PLANO    = CCP.CAD_PLA_ID_PLANO
    JOIN    TB_ATD_AIC_ATE_INT_COMPL  AIC    ON      AIC.ATD_ATE_ID          = CCP.ATD_ATE_ID
    JOIN    TB_TIS_TIN_TP_INTERNACAO  TIN    ON      TIN.TIS_TIN_CD_INTERNACAO = AIC.TIS_TIN_CD_INTERNACAO
    JOIN    TB_TIS_TRI_TP_REGINTERNACAO TRI  ON      TRI.TIS_TRI_CD_TP_REGINTERNACAO = AIC.TIS_TRI_CD_REGINTENNACAO
    JOIN    TB_FAT_NOF_NOTA_FISCAL      NOF  ON      NOF.FAT_NOF_ID          = CCP.FAT_NOF_ID
    LEFT JOIN TB_CAD_PRD_PRODUTO        PRD  ON     PRD.CAD_PRD_ID            = AIC.CAD_PRD_ID
   WHERE  (CCP.FAT_CCP_FL_STATUS = '||chr(39)||'A'||chr(39)||')
   AND    (CCP.FAT_CCP_FL_FATURADA = '||chr(39)||'S'||chr(39)||')
   ' || V_WHERE || ' 
   AND    ('||chr(39)|| pATD_ATE_FL_CARATER_SOLIC_U ||chr(39)||' IS NOT NULL AND ATE.ATD_ATE_FL_CARATER_SOLIC = '||chr(39)||'U'||chr(39)||'
            OR '||chr(39)|| pATD_ATE_FL_CARATER_SOLIC_E ||chr(39)||' IS NOT NULL AND ATE.ATD_ATE_FL_CARATER_SOLIC = '||chr(39)||'E'||chr(39)||')
    AND    ('||chr(39)|| pATD_ATE_TP_PACIENTE_I ||chr(39)||' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = '||chr(39)||'I'||chr(39)||'
            OR '||chr(39)|| pATD_ATE_TP_PACIENTE_E ||chr(39)||' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = '||chr(39)||'E'||chr(39)||')
   AND    ('||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)||' IS not NULL and CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'ACS'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'PA'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'SP'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'FU'||chr(39)||')
  
   ORDER   BY  ATE.ATD_ATE_DT_ATENDIMENTO DESC'
  ;
 --   TESTE :=  V_SELECT ;
  OPEN v_cursor FOR
   V_SELECT ;
    io_cursor := v_cursor;
END PRC_FAT_REL_ALTAS_COM_FATURA;
 