CREATE OR REPLACE PROCEDURE PRC_MTMD_REQ_REQUISICAO_S
  (
     pMTMD_REQ_ID                  IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_ID%type DEFAULT NULL,
     pATD_ATE_ID                   IN TB_MTMD_REQ_REQUISICAO.ATD_ATE_ID%type DEFAULT NULL,
     pATD_ATE_TP_PACIENTE          IN TB_MTMD_REQ_REQUISICAO.ATD_ATE_TP_PACIENTE%type DEFAULT NULL,
     pMTMD_REQ_FL_STATUS           IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_FL_STATUS%type DEFAULT NULL,
     pMTM_TIPO_REQUISICAO          IN TB_MTMD_REQ_REQUISICAO.MTM_TIPO_REQUISICAO%type DEFAULT NULL,
     pMTMD_REQ_DT_ATUALIZACAO      IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_DT_ATUALIZACAO%type DEFAULT NULL,
     pCAD_SET_ID                   IN TB_CAD_SET_SETOR.CAD_SET_ID%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE           IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_MTMD_FILIAL_ID           IN TB_MTMD_REQ_REQUISICAO.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
     pMTMD_FL_PENDENTE             IN TB_MTMD_REQ_REQUISICAO.MTMD_FL_PENDENTE%type DEFAULT NULL,
     pMTMD_DATA_REQUISICAO         IN TB_MTMD_REQ_REQUISICAO.MTMD_DATA_REQUISICAO%type DEFAULT NULL,
     pMTMD_DATA_REQUISICAO2        IN TB_MTMD_REQ_REQUISICAO.MTMD_DATA_REQUISICAO%type DEFAULT NULL,
     pCOM_QTD_SOL                  IN NUMBER DEFAULT NULL,
     io_cursor                     OUT PKG_CURSOR.t_cursor
  )
  is
    /********************************************************************
  *    Procedure: PRC_MTMD_REQ_REQUISICAO_S
  *
  *    Data Criacao:   06/2009      Por: RICARDO COSTA
  *    Data Alteracao: 08/02/2010   Por: Andre Souza Monaco
            Alterac?o: Cancelamento de todos os pedidos n?o dispensados com mais de 24 horas
  *    Data Alteracao: 18/06/2010   Por: RICARDO COSTA
            Alterac?o: alterado pesquisa de cancelamento de 24 hr., so cancela pedidos ja impressos pelo almoxarifado ou pendente
  *    Data Alteracao: 09/08/2010   Por: RICARDO COSTA
            Alterac?o: ATUALIZADO MIGRA 2
  *    Data Alteracao:  11/11/2011  Por: Andre Souza Monaco
  *         Alteracao:  Coloquei a query no padr?o de string dinamica
  *    Data Alteracao:  21/10/2015  Por: Andre Souza Monaco
  *         Alteracao:  Add. kit na query
  *    Data Alteracao:  11/04/2016  Por: Andre Souza Monaco
  *         Alteracao:  Nao cancelar pedido com prescricao
  *
  *    Funcao: Select e cancelamento de pedidos
  *
  *******************************************************************/
   v_cursor                       PKG_CURSOR.t_cursor;
   vStatusRecebido                NUMBER DEFAULT NULL;
   vDataIni                       DATE;
   vDataFim                       DATE;
   V_WHERE  varchar2(5000);
   V_SELECT  varchar2(5000);
  BEGIN
    IF ( pMTMD_DATA_REQUISICAO2 IS NOT NULL )  THEN
        vDataIni := TO_DATE(TO_CHAR(pMTMD_DATA_REQUISICAO,'DDMMYYYY')||' 0000','DDMMYYYY HH24MI');
        vDataFim := TO_DATE(TO_CHAR(pMTMD_DATA_REQUISICAO2,'DDMMYYYY')||' 2359','DDMMYYYY HH24MI');
    END IF;
    --Cancela todos os pedidos pendentes n?o dispensados com mais de 24 horas
    IF ( pMTMD_FL_PENDENTE = 1 ) THEN
       BEGIN
          FOR xxx IN
          (
            SELECT MTMD_REQ_ID,
                   TO_CHAR(SYSDATE, 'HH24MI') HORA_ATUAL,
                   TO_CHAR(MTMD_REQ_DT_ATUALIZACAO, 'HH24MI') HORA_REQUISICAO,
                   TRUNC( SYSDATE - MTMD_REQ_DT_ATUALIZACAO ) RESULTADO_DIAS
            FROM SGS.TB_MTMD_REQ_REQUISICAO R
            WHERE MTMD_REQ_FL_STATUS IN (1,2,5)
            AND MTMD_FL_PENDENTE = 1
            AND TRUNC(SYSDATE - MTMD_REQ_DT_ATUALIZACAO) >= 1
            AND MTMD_REQ_ID NOT IN (SELECT DISTINCT MTMD_REQ_ID FROM TB_MTMD_REQUISICAO_ITEM I
                                     WHERE I.CAD_MTMD_PRESCRICAO_ID IS NOT NULL AND
                                           I.MTMD_REQ_ID = R.MTMD_REQ_ID)
          )
          LOOP
             UPDATE TB_MTMD_REQ_REQUISICAO SET
                    MTMD_REQ_FL_STATUS = 0 -- CANCELADA
              WHERE MTMD_REQ_ID = xxx.MTMD_REQ_ID;
          END LOOP;
       END;
    END IF; -- FIM TESTE PENDENTE
    IF ( NOT pMTMD_REQ_FL_STATUS IS NULL ) THEN
       IF ( pMTMD_REQ_FL_STATUS = 3 ) THEN -- Dispensado
          vStatusRecebido := 4;
       END IF;
    END IF;
    V_WHERE := NULL;
    IF pMTMD_REQ_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.MTMD_REQ_ID = ' || pMTMD_REQ_ID; END IF;
    IF pATD_ATE_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.ATD_ATE_ID = ' || pATD_ATE_ID; END IF;
    IF pATD_ATE_TP_PACIENTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.ATD_ATE_TP_PACIENTE = ' || CHR(39) || pATD_ATE_TP_PACIENTE || CHR(39); END IF;
    IF pMTMD_REQ_FL_STATUS IS NOT NULL THEN
       V_WHERE:= V_WHERE || ' AND (REQUISICAO.MTMD_REQ_FL_STATUS = ' || pMTMD_REQ_FL_STATUS;
       IF vStatusRecebido IS NOT NULL THEN V_WHERE:= V_WHERE || ' OR REQUISICAO.MTMD_REQ_FL_STATUS = ' || vStatusRecebido; END IF;
       V_WHERE:= V_WHERE || ') ';
    END IF;
    IF pCAD_MTMD_FILIAL_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.CAD_MTMD_FILIAL_ID = ' || pCAD_MTMD_FILIAL_ID; END IF;
    IF pMTMD_REQ_DT_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.MTMD_REQ_DT_ATUALIZACAO = ' || CHR(39) || pMTMD_REQ_DT_ATUALIZACAO || CHR(39); END IF;
    IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
    IF pMTM_TIPO_REQUISICAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.MTM_TIPO_REQUISICAO = ' || pMTM_TIPO_REQUISICAO; END IF;
    IF pMTMD_FL_PENDENTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND REQUISICAO.MTMD_FL_PENDENTE = ' || pMTMD_FL_PENDENTE; END IF;
    IF pMTMD_DATA_REQUISICAO2 IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND TRUNC(REQUISICAO.MTMD_DATA_REQUISICAO) BETWEEN ' || CHR(39) || TRUNC(vDataIni) || CHR(39) || ' AND '  || CHR(39) || TRUNC(vDataFim) || CHR(39); END IF;
    IF (NVL(pCOM_QTD_SOL,0) = 1) THEN
       V_WHERE:=  V_WHERE || ' AND (SELECT COUNT(MTMD_REQ_ID) 
                                      FROM TB_MTMD_REQUISICAO_ITEM
                                     WHERE MTMD_REQ_ID = REQUISICAO.MTMD_REQ_ID AND
                                           MTMD_REQITEM_QTD_SOLICITADA > 0) > 0 ';
    END IF;
    V_WHERE  := V_WHERE || ' ORDER BY REQUISICAO.MTMD_REQ_DT_ATUALIZACAO DESC';
    V_SELECT := '
    SELECT
       REQUISICAO.MTMD_REQ_ID,
       REQUISICAO.ATD_ATE_ID,
       REQUISICAO.ATD_ATE_TP_PACIENTE,
       REQUISICAO.MTMD_REQ_FL_STATUS,
       REQUISICAO.MTMD_REQ_DT_ATUALIZACAO,
       REQUISICAO.MTM_TIPO_REQUISICAO,
       REQUISICAO.CAD_MTMD_FILIAL_ID,
       SETOR.CAD_SET_ID,
       SETOR.CAD_SET_DS_SETOR,
       UNIDADE.CAD_UNI_ID_UNIDADE,
       UNIDADE.CAD_UNI_DS_UNIDADE,
       LOC.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       LOC.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       USU_REQUISICAO.SEG_USU_DS_NOME DS_USUARIO_REQUISICAO,
       USU_DISPENSACAO.SEG_USU_DS_NOME DS_USUARIO_DISPENSACAO,
       REQUISICAO.MTMD_DATA_REQUISICAO,
       REQUISICAO.MTMD_FL_PENDENTE,
       REQUISICAO.MTMD_DATA_DISPENSACAO,
       REQUISICAO.MTMD_REQ_ID_REF,
       REQUISICAO.CAD_SET_SETOR_FARMACIA,
       TPREQUISICAO.MTMD_DS_TIPO_REQUISICAO,
       KIT.CAD_MTMD_KIT_ID,
       KIT.CAD_MTMD_KIT_DSC,
       REQUISICAO.MTMD_REQ_FL_URGENCIA
    FROM TB_MTMD_REQ_REQUISICAO       REQUISICAO,
         TB_CAD_SET_SETOR             SETOR,
         TB_CAD_UNI_UNIDADE           UNIDADE,
         TB_CAD_LAT_LOCAL_ATENDIMENTO LOC,
         TB_SEG_USU_USUARIO           USU_REQUISICAO,
         TB_SEG_USU_USUARIO           USU_DISPENSACAO,
         TB_MTMD_REQUISICAO_TIPO      TPREQUISICAO,
         TB_CAD_MTMD_KIT              KIT
    WHERE SETOR.CAD_SET_ID                      = REQUISICAO.CAD_SET_ID
    AND   UNIDADE.CAD_UNI_ID_UNIDADE            = REQUISICAO.CAD_UNI_ID_UNIDADE
    AND   LOC.CAD_LAT_ID_LOCAL_ATENDIMENTO      = REQUISICAO.CAD_LAT_ID_LOCAL_ATENDIMENTO
    AND   USU_REQUISICAO.SEG_USU_ID_USUARIO(+)  = REQUISICAO.MTMD_ID_USUARIO_REQUISICAO
    AND   USU_DISPENSACAO.SEG_USU_ID_USUARIO(+) = REQUISICAO.MTMD_ID_USUARIO_DISPENSACAO
    AND   KIT.CAD_MTMD_KIT_ID(+)                = REQUISICAO.CAD_MTMD_KIT_ID
    AND   TPREQUISICAO.MTMD_TIPO_REQ_ID         = REQUISICAO.MTM_TIPO_REQUISICAO ';
    OPEN v_cursor FOR
    V_SELECT || V_WHERE;
    io_cursor := v_cursor;
  end PRC_MTMD_REQ_REQUISICAO_S;