create or replace procedure PRC_INT_REL_SAIDA_ALTA
(
pATD_ATE_DT_ATENDIMENTO_INI          IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_DT_ATENDIMENTO_FIM          IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_INI          IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_FIM          IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_U          IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_E          IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pFAIXA_ETARIA_INI                    VARCHAR2 DEFAULT NULL,
pFAIXA_ETARIA_FIM                    VARCHAR2 DEFAULT NULL,
pCAD_UNI_ID_UNIDADE                  IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
pCAD_LAT_ID_LOCAL_ATENDIMENTO        IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
pCAD_SET_ID                          IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
pCAD_SET_NR_ANDAR                    IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC             IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_I               IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_E               IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pCAD_QLE_TP_QUARTO_LEITO             IN TB_CAD_QLE_QUARTO_LEITO.CAD_QLE_TP_QUARTO_LEITO%TYPE DEFAULT NULL,
pTIS_TIN_CD_INTER                    IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
pTIS_TRI_CD_TP_REGINT                IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_GB             IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_PL             IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_FU             IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_NP             IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_PA             IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_SP             IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PRD_ID                          IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
pTIS_TAC_CD_TIPO_ACOMODACAO          IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%TYPE DEFAULT NULL,
pTIS_CBO_CD_CBOS                     IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
pCAD_PRO_ID_PROF_EXEC                IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
pCAD_PES_TP_SEXO                     IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
pCAD_CNV_ID_CONVENIO                 IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
pCAD_PLA_ID_PLANO                    IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
pCAD_UNI_ID_UNID_PROC                IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNID_PROC%TYPE DEFAULT NULL,
pINCLUI_HOSP_DIA                     VARCHAR2 DEFAULT NULL,
pINCLUI_OBITOS                       VARCHAR2 DEFAULT NULL,
pTIS_TAT_CD_TPATENDIMENTO_AH         VARCHAR2 DEFAULT NULL,
pTIS_TAT_CD_TPATENDIMENTO_IH         VARCHAR2 DEFAULT NULL,
pSOMENTE_DATA_SAIDA_DIF              VARCHAR2 DEFAULT NULL,
pCAD_CGC_ID_G                        IN TB_CAD_CNV_CONVENIO.CAD_CGC_ID%TYPE DEFAULT NULL,
pCAD_CGC_ID_E                        IN TB_CAD_CNV_CONVENIO.CAD_CGC_ID%TYPE DEFAULT NULL,
pSAIDA_ADM_IGUAL_CLINICA             VARCHAR2 DEFAULT NULL,
io_cursor                            OUT PKG_CURSOR.t_cursor
--,TESTE OUT LONG
) is
/********************************************************************
*    Procedure: PRC_INT_REL_SAIDA_ALTA
*
*
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(6000);
  V_SELECT  varchar2(30000);
 begin
    V_WHERE := NULL;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATD.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO;    END IF;
    IF pCAD_SET_ID IS NOT NULL THEN V_WHERE := V_WHERE || ' AND IML_QLE.CAD_SET_ID = ' || pCAD_SET_ID;    END IF;
    IF pCAD_SET_NR_ANDAR IS NOT NULL THEN V_WHERE := V_WHERE || ' AND SETOR.CAD_SET_NR_ANDAR = ' ||CHR(39)|| pCAD_SET_NR_ANDAR ||CHR(39);    END IF;
    IF pFAIXA_ETARIA_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND FLOOR(FLOOR(MONTHS_BETWEEN(DECODE(INA.ATD_INA_DT_ALTA_ADM,NULL,ATD.ATD_ATE_DT_ATENDIMENTO,INA.ATD_INA_DT_ALTA_ADM), PES.CAD_PES_DT_NASCIMENTO)) / 12)  <= ' || pFAIXA_ETARIA_INI;    END IF;
    IF pFAIXA_ETARIA_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND FLOOR(FLOOR(MONTHS_BETWEEN(DECODE(INA.ATD_INA_DT_ALTA_ADM,NULL,ATD.ATD_ATE_DT_ATENDIMENTO,INA.ATD_INA_DT_ALTA_ADM), PES.CAD_PES_DT_NASCIMENTO)) / 12)  <= ' || pFAIXA_ETARIA_FIM;    END IF;
    IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRIM(INA.TIS_CBO_CD_CBOS) = ' ||CHR(39)|| pTIS_CBO_CD_CBOS ||CHR(39);    END IF;
    IF pCAD_PRO_ID_PROF_EXEC IS NOT NULL THEN V_WHERE := V_WHERE || ' AND INA.CAD_PRO_ID_PROFISSIONAL = ' || pCAD_PRO_ID_PROF_EXEC; END IF;
    IF pCAD_PRD_ID IS NOT NULL THEN V_WHERE := V_WHERE || ' AND AIC.CAD_PRD_ID = ' || pCAD_PRD_ID; END IF;
    IF pCAD_PES_TP_SEXO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PES.CAD_PES_TP_SEXO = ' ||CHR(39)|| pCAD_PES_TP_SEXO ||CHR(39); END IF;
    IF pTIS_TAC_CD_TIPO_ACOMODACAO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TAC.TIS_TAC_CD_TIPO_ACOMODACAO = ' ||CHR(39)|| pTIS_TAC_CD_TIPO_ACOMODACAO ||CHR(39); END IF;
    IF pCAD_QLE_TP_QUARTO_LEITO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND IML_QLE.CAD_QLE_TP_QUARTO_LEITO = ' ||CHR(39)|| pCAD_QLE_TP_QUARTO_LEITO ||CHR(39); END IF;
    IF pTIS_TIN_CD_INTER IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TIN.TIS_TIN_CD_INTERNACAO = ' ||CHR(39)|| pTIS_TIN_CD_INTER ||CHR(39); END IF;
    IF pTIS_TRI_CD_TP_REGINT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRI.TIS_TRI_CD_TP_REGINTERNACAO = ' ||CHR(39)|| pTIS_TRI_CD_TP_REGINT ||CHR(39); END IF;
    IF pCAD_UNI_ID_UNID_PROC IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATD.CAD_UNI_ID_UNID_PROC = ' || pCAD_UNI_ID_UNID_PROC; END IF;
    IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND INA.ATD_INA_DT_ALTA_ADM >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);    END IF;
    IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND INA.ATD_INA_DT_ALTA_ADM <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);    END IF;
    IF pATD_ATE_HR_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND INA.ATD_INA_HR_ALTA_ADM >= ' ||CHR(39)|| pATD_ATE_HR_ATENDIMENTO_INI ||CHR(39);    END IF;
    IF pATD_ATE_HR_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND INA.ATD_INA_HR_ALTA_ADM <= ' ||CHR(39)|| pATD_ATE_HR_ATENDIMENTO_FIM ||CHR(39);    END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PAC.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO; END IF;
    IF pCAD_PLA_ID_PLANO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PAC.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO; END IF;
IF pSOMENTE_DATA_SAIDA_DIF IS NOT NULL THEN
  V_WHERE := V_WHERE || ' AND FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_ADM,INA.ATD_INA_HR_ALTA_ADM) -
   FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA) != 0 '; END IF;
V_SELECT :=
 '
 SELECT DISTINCT
        IML_QLE.ATD_IML_DT_ENTRADA,
        IML_QLE.ATD_IML_HR_ENTRADA,
        DECODE(IML_QLE.CAD_QLE_TP_QUARTO_LEITO,''I'',''INTERNO'',''E'',''EXTRA'') CAD_QLE_TP_QUARTO_LEITO,
        IML_QLE.CAD_QLE_NR_QUARTO,
        IML_QLE.CAD_QLE_NR_LEITO,
        CASE WHEN AIC.ATD_AIC_TP_SITUACAO_PAC = ''A'' AND INA.ATD_INA_DT_ALTA_ADM IS NOT NULL THEN
        NVL(ROUND(INA.ATD_INA_DT_ALTA_ADM - ATD.ATD_ATE_DT_ATENDIMENTO),0)
        WHEN AIC.ATD_AIC_TP_SITUACAO_PAC = ''I'' THEN
        NVL(ROUND(SYSDATE-ATD.ATD_ATE_DT_ATENDIMENTO),0)
        ELSE  0
        END PERMANENCIA,
        TAC.TIS_TAC_DS_TIPO_ACOMODACAO,
        ATD.ATD_ATE_ID,
        DECODE(ATD.ATD_ATE_FL_CARATER_SOLIC,''U'',''URGENCIA'',''E'',''ELETIVA'') ATD_ATE_FL_CARATER_SOLIC,
        UNI.CAD_UNI_DS_UNIDADE UNIDADE,
        UNI.CAD_UNI_ID_UNIDADE,
        LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
        SETOR.CAD_SET_DS_SETOR,
        PAC.CAD_PAC_CD_CREDENCIAL,
        PAC.CAD_PAC_NR_PRONTUARIO,
        PES.CAD_PES_NM_PESSOA PACIENTE,
        PES.CAD_PES_DT_NASCIMENTO,
        PES.CAD_PES_TP_SEXO,
        FNC_CAD_PES_MUNICIPIO_S(PES.CAD_PES_ID_PESSOA,1) AUX_MUN_NM_MUNICIPIO,
        FNC_RETORNA_TEL_PAC(PES.CAD_PES_ID_PESSOA) CAD_TEL_NR_NUM_TEL,
        CBOS.TIS_CBO_DS_CBOS_HAC,
        DECODE(AIC.ATD_AIC_TP_SITUACAO_PAC,''I'',''INTERNADO'',''A'',''ALTA'') ATD_AIC_TP_SITUACAO_PAC,
        DECODE(ATD_ATE_TP_PACIENTE,''I'',''INTERNO'',''E'',''EXTERNO'') ATD_ATE_TP_PACIENTE,
        INA.ATD_INA_DT_ALTA_ADM ,
        INA.ATD_INA_HR_ALTA_ADM ,
        INA.ATD_INA_DT_ALTA_CLINICA,
        INA.ATD_INA_HR_ALTA_CLINICA,
        fnc_juntar_data_hora(ATD.ATD_ATE_DT_ATENDIMENTO,ATD.ATD_ATE_HR_ATENDIMENTO) data_INT,        
        fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA) data_clinica,
        fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_ADM,INA.ATD_INA_HR_ALTA_ADM) data_adm,
        MSI.TIS_MSI_DS_MOTIVOSAIDAINT,
        CNV.CAD_CNV_CD_HAC_PRESTADOR,
        PLA.CAD_PLA_CD_TIPOPLANO,
        PLA.CAD_PLA_CD_PLANO_HAC,
        ATD.ATD_ATE_DT_ATENDIMENTO,
        ATD.ATD_ATE_HR_ATENDIMENTO,
        PRO.CAD_PRO_NM_NOME PROFISSIONAL,
        PRO.CAD_PRO_NR_CONSELHO,
        PRO.CAD_PRO_SG_UF_CONSELHO,
        CBOS.TIS_CBO_DS_CBOS ESPECIALIDADE,
        IDG.ATD_IDG_CD_CIDPRINCIPAL,
        CID.CAD_CID_DS_CID10,
        TIN.TIS_TIN_DS_INTERNACAO,
        TRI.TIS_TRI_DS_TP_REGINTERNACAO,
        PRD.CAD_PRD_NM_MNEMONICO,
        PRD.CAD_PRD_DS_DESCRICAO,
        
        SETOR.CAD_SET_NR_ANDAR,
        FLOOR(FLOOR(MONTHS_BETWEEN(DECODE(INA.ATD_INA_DT_ALTA_ADM,NULL,ATD.ATD_ATE_DT_ATENDIMENTO,INA.ATD_INA_DT_ALTA_ADM), PES.CAD_PES_DT_NASCIMENTO)) / 12) IDADE,
        CASE WHEN ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = 46 THEN DECODE(TRIM(ATD.TIS_TAT_CD_TPATENDIMENTO),''6'',''A'',''7'',''I'')
          ELSE NULL
        END TIS_TAT_CD_TPATENDIMENTO,
        USU.SEG_USU_CD_MATRICULA,
        USU.SEG_USU_DS_NOME,
        INA.ATD_INA_DS_OBSERVACAO,
        REPLACE(TO_CHAR(EXTRACT(DAY FROM NUMTODSINTERVAL( FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_ADM,INA.ATD_INA_HR_ALTA_ADM) - FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA), ''DAY'')) * 24
         + EXTRACT(HOUR FROM NUMTODSINTERVAL( FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_ADM,INA.ATD_INA_HR_ALTA_ADM) - FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA), ''DAY'')),''09'') || '':'' ||
         TO_CHAR(EXTRACT(MINUTE FROM NUMTODSINTERVAL( FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_ADM,INA.ATD_INA_HR_ALTA_ADM) - FNC_JUNTAR_DATA_HORA(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA), ''DAY'')),''09''),'' '','''') PERMANENCIA_DIF,
          PESRESP.CAD_PES_NM_PESSOA NOME_RESP,
               PESRESP.CAD_PES_DT_NASCIMENTO DTNASC_RESP,
               fnc_cad_pes_telefone_s(ARE.CAD_PES_ID_PESSOA,1)  TEL_RESP,
               fnc_cad_pes_email_s(ARE.CAD_PES_ID_PESSOA)  EMAIL_RESP
   , DECODE(INA.ATD_INA_CD_MOTIVO_PERM_LEITO,''01'',''AGUARDANDO FAMILIAR'',''02'',''AGUARDANDO AMBULANCIA'',''03'',''AGUARDANDO TERMINO DE MEDICAC?O'',''04'',''AGUARDANDO EXAME (RESULTADO/REALIZAC?O)'',''05'',''ALMOXARIFADO LIBERAR MEDICAC?O'',''10'',''OUTROS'',NULL,'''' ) ATD_INA_DS_MOTIVO_PERM_LEITO
     ,
           DECODE(PES.CAD_PES_FL_CUIDADOINTEGRAL,1,''SAVE1'',2,''SAVE2'',3,''SAVE3'') CAD_PES_FL_CUIDADOINTEGRAL,
                CASE WHEN PES.CAD_PES_FL_ISOLAMENTO = ''S'' THEN ''ISOLAMENTO'' ELSE NULL END CAD_PES_FL_ISOLAMENTO
     
     
     FROM TB_ATD_ATE_ATENDIMENTO    ATD
     JOIN TB_CAD_PAC_PACIENTE       PAC ON PAC.CAD_PAC_ID_PACIENTE = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
     JOIN TB_CAD_PES_PESSOA         PES ON PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
     JOIN TB_CAD_CNV_CONVENIO       CNV ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
     JOIN TB_CAD_PLA_PLANO          PLA ON PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
     JOIN TB_ATD_AIC_ATE_INT_COMPL  AIC ON AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
LEFT JOIN ( SELECT QLE.CAD_QLE_ID, QLE.CAD_SET_ID , QLE.CAD_QLE_NR_QUARTO, QLE.CAD_QLE_NR_LEITO,
                   IML.ATD_ATE_ID, QLE.TIS_TAC_CD_TIPO_ACOMODACAO, QLE.CAD_QLE_TP_QUARTO_LEITO ,
                   IML.ATD_IML_DT_ENTRADA, IML.ATD_IML_HR_ENTRADA
              FROM TB_ATD_IML_INT_MOV_LEITO IML
         LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE
                ON QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
              JOIN TB_ATD_ATE_ATENDIMENTO ATD2
                ON ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
             WHERE FNC_JUNTAR_DATA_HORA(IML.ATD_IML_DT_ENTRADA,IML.ATD_IML_HR_ENTRADA) = ( SELECT MAX(FNC_JUNTAR_DATA_HORA(IML3.ATD_IML_DT_ENTRADA,IML3.ATD_IML_HR_ENTRADA))
                                                                                             FROM TB_ATD_IML_INT_MOV_LEITO IML3
                                                                                            WHERE IML3.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML3.ATD_IML_FL_STATUS = ''A'') )  IML_QLE
       ON IML_QLE.ATD_ATE_ID      = ATD.ATD_ATE_ID

LEFT JOIN TB_CAD_SET_SETOR SETOR ON SETOR.CAD_SET_ID                 = IML_QLE.CAD_SET_ID
LEFT JOIN TB_TIS_TAC_TIPO_ACOMODACAO TAC ON TAC.TIS_TAC_CD_TIPO_ACOMODACAO   = IML_QLE.TIS_TAC_CD_TIPO_ACOMODACAO
     JOIN TB_ATD_INA_INT_ALTA INA ON INA.ATD_ATE_ID                   = ATD.ATD_ATE_ID
LEFT JOIN TB_TIS_CBO_CBOS CBOS ON CBOS.TIS_CBO_CD_CBOS             = INA.TIS_CBO_CD_CBOS
     JOIN TB_CAD_UNI_UNIDADE UNI ON UNI.CAD_UNI_ID_UNIDADE           = ATD.CAD_UNI_ID_UNIDADE
     JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO
LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO ON PRO.CAD_PRO_ID_PROFISSIONAL      = INA.CAD_PRO_ID_PROFISSIONAL
LEFT JOIN TB_ATD_IDG_INT_DIAGNOSTICO IDG ON IDG.ATD_ATE_ID                   = ATD.ATD_ATE_ID
LEFT JOIN TB_CAD_CID_CID10 CID ON CID.CAD_CID_CD_CID10             = IDG.ATD_IDG_CD_CIDPRINCIPAL
LEFT JOIN TB_TIS_TIN_TP_INTERNACAO TIN ON TIN.TIS_TIN_CD_INTERNACAO        = AIC.TIS_TIN_CD_INTERNACAO
LEFT JOIN TB_TIS_TRI_TP_REGINTERNACAO TRI ON TRI.TIS_TRI_CD_TP_REGINTERNACAO  = AIC.TIS_TRI_CD_REGINTENNACAO
LEFT JOIN TB_CAD_PRD_PRODUTO PRD ON PRD.CAD_PRD_ID                   = AIC.CAD_PRD_ID
     JOIN TB_TIS_MSI_MOTIVO_SAIDA_INT MSI ON MSI.TIS_MSI_CD_MOTIVOSAIDAINT    = INA.TIS_MSI_CD_MOTIVOSAIDAINT
     JOIN TB_SEG_USU_USUARIO USU  ON USU.SEG_USU_ID_USUARIO           = INA.SEG_USU_ID_USUARIO
LEFT JOIN tb_ass_are_atd_responsavel ARE ON ARE.ATD_ATE_ID = ATD.ATD_ATE_ID
LEFT JOIN tb_cad_pes_pessoa PESRESP ON PESRESP.CAD_PES_ID_PESSOA = ARE.CAD_PES_ID_PESSOA
WHERE (AIC.ATD_AIC_TP_SITUACAO_PAC = ''A'')
  AND (ATD.ATD_ATE_FL_STATUS = ''A'')
  AND ('||CHR(39)|| pATD_ATE_TP_PACIENTE_I ||CHR(39)||' IS NOT NULL AND ATD.ATD_ATE_TP_PACIENTE = ''I''
   OR  '||CHR(39)|| pATD_ATE_TP_PACIENTE_E ||CHR(39)||' IS NOT NULL AND ATD.ATD_ATE_TP_PACIENTE = ''E'')
  AND ('||CHR(39)|| pCAD_CGC_ID_G ||CHR(39)|| ' IS NOT NULL AND CNV.CAD_CGC_ID = ' ||CHR(39)|| '1' ||CHR(39)|| '
   OR  '||CHR(39)|| pCAD_CGC_ID_E ||CHR(39)|| ' IS NOT NULL AND CNV.CAD_CGC_ID = ' ||CHR(39)|| '2' ||CHR(39)|| ')
  AND ('||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ''GB''
   OR  '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_PL ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ''PL''
   OR  '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ''PA''
   OR  '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ''SP''
   OR  '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ''FU'')
  AND (PLA.CAD_PLA_CD_TIPOPLANO != ''NP'')
  AND ('||CHR(39)|| pATD_ATE_FL_CARATER_SOLIC_U ||CHR(39)|| 'IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = ''U''
   OR  '||CHR(39)|| pATD_ATE_FL_CARATER_SOLIC_E ||CHR(39)|| 'IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = ''E'')
  AND ('||CHR(39)|| pINCLUI_HOSP_DIA ||CHR(39)|| ' IS NOT NULL OR ('||CHR(39)|| pINCLUI_HOSP_DIA ||CHR(39)|| ' IS NULL AND ATD.ATD_ATE_DT_ATENDIMENTO != INA.ATD_INA_DT_ALTA_CLINICA))
  AND ('||CHR(39)|| pINCLUI_OBITOS ||CHR(39)|| ' IS NOT NULL OR ('||CHR(39)|| pINCLUI_OBITOS ||CHR(39)|| 'IS NULL AND MSI.TIS_MSI_CD_TIPOALTA != 4)) ';
 IF pCAD_LAT_ID_LOCAL_ATENDIMENTO = 46 THEN
   V_SELECT := V_SELECT || 'AND ('||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO_AH ||CHR(39)|| 'IS NOT NULL AND ATD.TIS_TAT_CD_TPATENDIMENTO = ''6'' OR '||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO_IH ||CHR(39)|| 'IS NOT NULL AND ATD.TIS_TAT_CD_TPATENDIMENTO = ''7'')';
 END IF;
 IF pSAIDA_ADM_IGUAL_CLINICA = 'S' THEN
   V_SELECT := V_SELECT || 'AND (INA.ATD_INA_DT_ALTA_ADM = INA.ATD_INA_DT_ALTA_CLINICA AND INA.ATD_INA_HR_ALTA_ADM = INA.ATD_INA_HR_ALTA_CLINICA) ';
 END IF;
 V_SELECT := V_SELECT || V_WHERE ;
 --TESTE :=  V_SELECT ;
OPEN v_cursor FOR
   V_SELECT ;
  --  SELECT 1 FROM DUAL;
   dbms_output.put_line(V_SELECT);
   io_cursor := v_cursor;
end PRC_INT_REL_SAIDA_ALTA;
