create or replace procedure PRC_ASS_ULO_RMT_S
  (
      pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_UNI_DS_IMAGEM_ASSOCIADA IN TB_CAD_UNI_UNIDADE.CAD_UNI_DS_IMAGEM_ASSOCIADA%type DEFAULT NULL,
     pCAD_UNI_FL_STATUS IN TB_CAD_UNI_UNIDADE.CAD_UNI_FL_STATUS%type DEFAULT NULL,
     pCAD_UNI_DT_ULTIMO_STATUS IN TB_CAD_UNI_UNIDADE.CAD_UNI_DT_ULTIMO_STATUS%type DEFAULT NULL,
     pCAD_UNI_FL_GRAVA_ATEND_OK IN TB_CAD_UNI_UNIDADE.CAD_UNI_FL_GRAVA_ATEND_OK%type DEFAULT NULL,
     pCAD_UNI_FL_LIBERA_AGENDA_OK IN TB_CAD_UNI_UNIDADE.CAD_UNI_FL_LIBERA_AGENDA_OK%type DEFAULT NULL,
     pCAD_UNI_FL_GRAVA_CD_PAC_OK IN TB_CAD_UNI_UNIDADE.CAD_UNI_FL_GRAVA_CD_PAC_OK%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE_MASTER IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE_MASTER%type DEFAULT NULL,
     pCAD_PES_ID_PESSOA IN TB_CAD_UNI_UNIDADE.CAD_PES_ID_PESSOA%type DEFAULT NULL,
     pCAD_UNI_NR_CNES IN TB_CAD_UNI_UNIDADE.CAD_UNI_NR_CNES%type DEFAULT NULL,
     pCAD_UNI_DT_ULTIMA_ATUALIZACAO IN TB_CAD_UNI_UNIDADE.CAD_UNI_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_UNI_UNIDADE.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pCAD_UNI_CD_HOSPITALAR IN TB_CAD_UNI_UNIDADE.CAD_UNI_CD_HOSPITALAR%type DEFAULT NULL,
     pCAD_UNI_CD_UNID_HOSPITALAR IN TB_CAD_UNI_UNIDADE.CAD_UNI_CD_UNID_HOSPITALAR%type DEFAULT NULL,
     pCAD_UNI_FL_CRONICO_OK IN TB_CAD_UNI_UNIDADE.CAD_UNI_FL_CRONICO_OK%type DEFAULT NULL,
     pCAD_UNI_FL_PRIORIDADE_OK IN TB_CAD_UNI_UNIDADE.CAD_UNI_FL_PRIORIDADE_OK%type DEFAULT NULL,
     pCAD_UNI_DS_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_DS_UNIDADE%type DEFAULT NULL,

     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_ULO_UNID_LOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ASS_ULO_RMT_S
  *
  *    Data Criacao:   05/08/09   Por: Pedro
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Retorna Unidades de Locais ativos com associação ativa
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
     SELECT
       UNI.CAD_UNI_ID_UNIDADE,
       UNI.CAD_UNI_DS_IMAGEM_ASSOCIADA,
       UNI.CAD_UNI_FL_STATUS,
       UNI.CAD_UNI_DT_ULTIMO_STATUS,
       UNI.CAD_UNI_FL_GRAVA_ATEND_OK,
       UNI.CAD_UNI_FL_LIBERA_AGENDA_OK,
       UNI.CAD_UNI_FL_GRAVA_CD_PAC_OK,
       UNI.CAD_UNI_ID_UNIDADE_MASTER,
       UNI.CAD_PES_ID_PESSOA,
       UNI.CAD_UNI_NR_CNES,
       UNI.CAD_UNI_DT_ULTIMA_ATUALIZACAO,
       UNI.SEG_USU_ID_USUARIO,
       UNI.CAD_UNI_CD_HOSPITALAR,
       UNI.CAD_UNI_CD_UNID_HOSPITALAR,
       UNI.CAD_UNI_FL_CRONICO_OK,
       UNI.CAD_UNI_FL_PRIORIDADE_OK,
       UNI.CAD_UNI_DS_UNIDADE
    FROM TB_ASS_ULO_UNID_LOCAL ULO
    INNER JOIN TB_CAD_UNI_UNIDADE UNI
       ON UNI.CAD_UNI_ID_UNIDADE = ULO.CAD_UNI_ID_UNIDADE
    INNER JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
       ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ULO.CAD_LAT_ID_LOCAL_ATENDIMENTO
    INNER JOIN TB_CAD_PES_PESSOA PES_UNI
       ON PES_UNI.CAD_PES_ID_PESSOA = UNI.CAD_PES_ID_PESSOA
    WHERE
        (pCAD_UNI_ID_UNIDADE is null OR UNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE) AND
        (pCAD_UNI_DS_IMAGEM_ASSOCIADA is null OR UNI.CAD_UNI_DS_IMAGEM_ASSOCIADA = pCAD_UNI_DS_IMAGEM_ASSOCIADA) AND
        (pCAD_UNI_FL_STATUS is null OR UNI.CAD_UNI_FL_STATUS = pCAD_UNI_FL_STATUS) AND
        (pCAD_UNI_DT_ULTIMO_STATUS is null OR UNI.CAD_UNI_DT_ULTIMO_STATUS = pCAD_UNI_DT_ULTIMO_STATUS) AND
        (pCAD_UNI_FL_GRAVA_ATEND_OK is null OR UNI.CAD_UNI_FL_GRAVA_ATEND_OK = pCAD_UNI_FL_GRAVA_ATEND_OK) AND
        (pCAD_UNI_FL_LIBERA_AGENDA_OK is null OR UNI.CAD_UNI_FL_LIBERA_AGENDA_OK = pCAD_UNI_FL_LIBERA_AGENDA_OK) AND
        (pCAD_UNI_FL_GRAVA_CD_PAC_OK is null OR UNI.CAD_UNI_FL_GRAVA_CD_PAC_OK = pCAD_UNI_FL_GRAVA_CD_PAC_OK) AND
        (pCAD_UNI_ID_UNIDADE_MASTER is null OR UNI.CAD_UNI_ID_UNIDADE_MASTER = pCAD_UNI_ID_UNIDADE_MASTER) AND
        (pCAD_PES_ID_PESSOA is null OR UNI.CAD_PES_ID_PESSOA = pCAD_PES_ID_PESSOA) AND
        (pCAD_UNI_NR_CNES is null OR UNI.CAD_UNI_NR_CNES = pCAD_UNI_NR_CNES) AND
        (pCAD_UNI_DT_ULTIMA_ATUALIZACAO is null OR UNI.CAD_UNI_DT_ULTIMA_ATUALIZACAO = pCAD_UNI_DT_ULTIMA_ATUALIZACAO) AND
        (pSEG_USU_ID_USUARIO is null OR UNI.SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND
        (pCAD_UNI_CD_HOSPITALAR is null OR UNI.CAD_UNI_CD_HOSPITALAR = pCAD_UNI_CD_HOSPITALAR) AND
        (pCAD_UNI_CD_UNID_HOSPITALAR is null OR UNI.CAD_UNI_CD_UNID_HOSPITALAR = pCAD_UNI_CD_UNID_HOSPITALAR) AND
        (pCAD_UNI_FL_CRONICO_OK is null OR UNI.CAD_UNI_FL_CRONICO_OK = pCAD_UNI_FL_CRONICO_OK) AND
        (pCAD_UNI_FL_PRIORIDADE_OK is null OR UNI.CAD_UNI_FL_PRIORIDADE_OK = pCAD_UNI_FL_PRIORIDADE_OK) AND
        (pCAD_UNI_DS_UNIDADE is null OR UNI.CAD_UNI_DS_UNIDADE = pCAD_UNI_DS_UNIDADE) AND
        (ASS_ULO_FL_STATUS = 'A')       AND
        (LAT.CAD_LAT_FL_ATIVO_OK = 'S') AND
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) 
;
    io_cursor := v_cursor;
  end PRC_ASS_ULO_RMT_S;
