CREATE OR REPLACE PROCEDURE PRC_BNF_VALIDA_SEXO_CBO
(
       pCODCON IN BNF_CARENCIA_BENEFICIARIO.CODCON%TYPE,
       pCODEST IN BNF_BENEFICIARIO.CODEST%TYPE,
       pCODBEN IN BNF_BENEFICIARIO.CODBEN%TYPE,
       pCODSEQBEN IN BNF_BENEFICIARIO.CODSEQBEN%TYPE,
       pCD_ESPECIALIDADE IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE,
       io_cursor OUT PKG_CURSOR.t_cursor
)

IS
       v_cursor PKG_CURSOR.t_cursor;
       vCBOHAC varchar2(3);
       vSexo VARchar2(1);
BEGIN

   SELECT CBO.TIS_CBO_CD_CBOS_HAC INTO vCBOHAC FROM TB_TIS_CBO_CBOS CBO
   WHERE CBO.TIS_CBO_CD_CBOS = pCD_ESPECIALIDADE;

   SELECT BNF.SEXBEN INTO vSexo
   FROM BNF_BENEFICIARIO BNF
   WHERE
       BNF.CODCON = pCODCON
   AND BNF.CODEST = pCODEST
   AND BNF.CODBEN = pCODBEN
   AND BNF.CODSEQBEN = pCODSEQBEN;

   OPEN v_cursor FOR
   SELECT COUNT(*) AS RETORNO
   FROM TB_AUT_ESPEC_SEXO SEXO
   WHERE SEXO.CODESPMED = vCBOHAC
   AND SEXO.SEXBEN = vSexo;


   io_cursor := v_cursor;
END PRC_BNF_VALIDA_SEXO_CBO;
 