create or replace procedure PRC_INT_REL_TERMO_ACOMOD_CNV
  (
     pATD_ATE_ID IN tb_atd_ate_atendimento.atd_ate_id%type,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_INT_REL_TERMO_ACOMOD_CNV
  *
  *    Data Criacao:   04/08/09   Por: Pedro
  *    Data Alteracao:  data da alterai??i??o  Por: Nome do Analista
  *
  *    Funcao: popular Termo de Responsabilidade Acomodai??i??o Diferente
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR

SELECT
    PES_PAC.CAD_PES_NM_PESSOA ,
    PES_PAC.CAD_PES_TP_SEXO ,
    PES_PAC.CAD_PES_DT_NASCIMENTO ,
    PAC.CAD_PAC_NR_PRONTUARIO,
    ATD.ATD_ATE_ID,
    CNV.CAD_CNV_CD_HAC_PRESTADOR,
    CNV.CAD_CNV_NM_FANTASIA,
    PLA.CAD_PLA_CD_PLANO_HAC,
    PLA.CAD_PLA_NM_NOME_PLANO,
    PAC.CAD_PAC_CD_CREDENCIAL,
    PES_PAC.CAD_PES_NR_RG ,

    ATD.ATD_ATE_DT_ATENDIMENTO,
    ATD.ATD_ATE_HR_ATENDIMENTO,
    UNI.CAD_UNI_DS_UNIDADE UNIDADE,
    IML_QLE.CAD_QLE_NR_QUARTO,
    IML_QLE.CAD_QLE_NR_LEITO,
    TIN.TIS_TIN_DS_INTERNACAO,
    DECODE(ATD.ATD_ATE_FL_CARATER_SOLIC,'U','URGENCIA','E','ELETIVA') ATD_ATE_FL_CARATER_SOLIC, --?
    FNC_RETORNA_TEL_PAC(pes_PAC.cad_pes_id_pessoa) NR_TELEFONE,
    --TEL.CAD_TEL_NR_NUM_TEL,
    END.CAD_END_NM_LOGRADOURO,
    END.CAD_END_NM_BAIRRO,
    END.CAD_END_SG_UF,
    END.CAD_END_DS_NUMERO,
    END.CAD_END_DS_COMPLEMENTO,
    END.CAD_END_CD_CEP,
    MUN.AUX_MUN_NM_MUNICIPIO,

    PES.CAD_PES_NM_PESSOA CAD_PES_NM_PESSOA_RESP,
        PES.CAD_PES_DT_NASCIMENTO CAD_PES_DT_NASCIMENTO_RESP,
    PES.CAD_PES_NR_RG CAD_PES_NR_RG_RESP,
    PES.CAD_PES_NR_CNPJ_CPF CAD_PES_NR_CNPJ_CPF_RESP,
    FNC_RETORNA_TEL_PAC(pes.cad_pes_id_pessoa) NR_TELEFONE_RESP,
    END1.CAD_END_NM_LOGRADOURO CAD_END_NM_LOGRADOURO_RESP,
    END1.CAD_END_NM_BAIRRO CAD_END_NM_BAIRRO_RESP,
    END1.CAD_END_SG_UF CAD_END_SG_UF_RESP,
    END1.CAD_END_DS_NUMERO CAD_END_DS_NUMERO_RESP,
    END1.CAD_END_DS_COMPLEMENTO CAD_END_DS_COMPLEMENTO_RESP,
    END1.CAD_END_CD_CEP CAD_END_CD_CEP_RESP,
    MUN1.AUX_MUN_NM_MUNICIPIO AUX_MUN_NM_MUNICIPIO_RESP
    
 FROM TB_ATD_ATE_ATENDIMENTO ATD
 JOIN TB_ATD_AIC_ATE_INT_COMPL AIC ON AIC.ATD_ATE_ID = ATD.ATD_ATE_ID
-- JOIN TB_ASS_ARE_ATD_RESPONSAVEL ARE ON ARE.ATD_ATE_ID = ATD.ATD_ATE_ID
 JOIN TB_CAD_PES_PESSOA PES ON PES.CAD_PES_ID_PESSOA = FNC_BUSCAR_PESSOA_RESP_ATUAL(ATD.ATD_ATE_ID)
 LEFT JOIN TB_CAD_END_ENDERECO END1 ON PES.CAD_PES_ID_PESSOA = END1.CAD_PES_ID_PESSOA
 LEFT JOIN TB_AUX_MUN_MUNICIPIO MUN1 ON MUN1.AUX_MUN_CD_IBGE = END1.AUX_MUN_CD_IBGE

 --JOIN TB_ASS_PAT_PACIEATEND PAT ON   PAT.ATD_ATE_ID = ATD.ATD_ATE_ID
 JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PAC_ID_PACIENTE =  fnc_buscar_paciente_atual(ATD.atd_ate_id)
 JOIN TB_CAD_PES_PESSOA PES_PAC ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
 LEFT JOIN TB_CAD_END_ENDERECO END ON PES_PAC.CAD_PES_ID_PESSOA = END.CAD_PES_ID_PESSOA
 LEFT JOIN TB_AUX_MUN_MUNICIPIO MUN ON MUN.AUX_MUN_CD_IBGE = END.AUX_MUN_CD_IBGE

 LEFT JOIN  (    SELECT   QLE.CAD_QLE_ID, QLE.CAD_SET_ID , QLE.CAD_QLE_NR_QUARTO, QLE.CAD_QLE_NR_LEITO,
                          IML.ATD_ATE_ID, QLE.TIS_TAC_CD_TIPO_ACOMODACAO, QLE.CAD_QLE_TP_QUARTO_LEITO ,
                          IML.ATD_IML_DT_ENTRADA, IML.ATD_IML_HR_ENTRADA
                 FROM      TB_ATD_IML_INT_MOV_LEITO IML
                 LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE
                 ON        QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
                 JOIN      TB_ATD_ATE_ATENDIMENTO ATD2
                 ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                 WHERE     (atd2.atd_ate_id =pATD_ATE_ID)
                   AND    IML.ATD_IML_ID = (SELECT MAX(IML3.ATD_IML_ID) FROM TB_ATD_IML_INT_MOV_LEITO IML3
                                             WHERE IML3.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML3.ATD_IML_FL_STATUS = 'A')
              )  IML_QLE
    ON IML_QLE.ATD_ATE_ID = ATD.ATD_ATE_ID
    JOIN TB_CAD_UNI_UNIDADE UNI ON UNI.CAD_UNI_ID_UNIDADE = ATD.CAD_UNI_ID_UNIDADE
    
    JOIN TB_CAD_CNV_CONVENIO CNV ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
    JOIN TB_CAD_PLA_PLANO PLA ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
    JOIN TB_TIS_TIN_TP_INTERNACAO TIN ON TIN.TIS_TIN_CD_INTERNACAO = AIC.TIS_TIN_CD_INTERNACAO

    WHERE (ATD.ATD_ATE_ID = pATD_ATE_ID)

UNION
SELECT
    PES_PAC.CAD_PES_NM_PESSOA ,
    PES_PAC.CAD_PES_TP_SEXO ,
    PES_PAC.CAD_PES_DT_NASCIMENTO ,
    PAC.CAD_PAC_NR_PRONTUARIO,
    IAE.ATD_IAE_ID,
    CNV.CAD_CNV_CD_HAC_PRESTADOR,
    CNV.CAD_CNV_NM_FANTASIA,
    PLA.CAD_PLA_CD_PLANO_HAC,
    PLA.CAD_PLA_NM_NOME_PLANO,
    PAC.CAD_PAC_CD_CREDENCIAL,
    PES_PAC.CAD_PES_NR_RG ,

    IAE.ATD_IAE_DT_ATENDIMENTO,
    IAE.ATD_IAE_HR_ATENDIMENTO ,
    UNI.CAD_UNI_DS_UNIDADE UNIDADE,
    NULL CAD_QLE_NR_QUARTO,
    NULL CAD_QLE_NR_LEITO,
    TIN.TIS_TIN_DS_INTERNACAO,
    'ELETIVA' ATD_ATE_FL_CARATER_SOLIC, --?
    FNC_RETORNA_TEL_PAC(pes_PAC.cad_pes_id_pessoa) NR_TELEFONE,
    --TEL.CAD_TEL_NR_NUM_TEL,
    END.CAD_END_NM_LOGRADOURO,
    END.CAD_END_NM_BAIRRO,
    END.CAD_END_SG_UF,
    END.CAD_END_DS_NUMERO,
    END.CAD_END_DS_COMPLEMENTO,
    END.CAD_END_CD_CEP,
    MUN.AUX_MUN_NM_MUNICIPIO,

    PES.CAD_PES_NM_PESSOA CAD_PES_NM_PESSOA_RESP,
        PES.CAD_PES_DT_NASCIMENTO CAD_PES_DT_NASCIMENTO_RESP,
    PES.CAD_PES_NR_RG CAD_PES_NR_RG_RESP,
    PES.CAD_PES_NR_CNPJ_CPF CAD_PES_NR_CNPJ_CPF_RESP,
    FNC_RETORNA_TEL_PAC(pes.cad_pes_id_pessoa) NR_TELEFONE_RESP,
    END1.CAD_END_NM_LOGRADOURO CAD_END_NM_LOGRADOURO_RESP,
    END1.CAD_END_NM_BAIRRO CAD_END_NM_BAIRRO_RESP,
    END1.CAD_END_SG_UF CAD_END_SG_UF_RESP,
    END1.CAD_END_DS_NUMERO CAD_END_DS_NUMERO_RESP,
    END1.CAD_END_DS_COMPLEMENTO CAD_END_DS_COMPLEMENTO_RESP,
    END1.CAD_END_CD_CEP CAD_END_CD_CEP_RESP,
    MUN1.AUX_MUN_NM_MUNICIPIO AUX_MUN_NM_MUNICIPIO_RESP
    
 FROM TB_ATD_IAE_INT_AGE_ELETIVA IAE
-- JOIN TB_ASS_ARE_ATD_RESPONSAVEL ARE ON ARE.ATD_ATE_ID = IAE.ATD_IAE_ID  
 JOIN TB_CAD_PES_PESSOA PES ON PES.CAD_PES_ID_PESSOA = FNC_BUSCAR_PESSOA_RESP_ATUAL(IAE.ATD_IAE_ID)
 LEFT JOIN TB_CAD_END_ENDERECO END1 ON PES.CAD_PES_ID_PESSOA = END1.CAD_PES_ID_PESSOA
 LEFT JOIN TB_AUX_MUN_MUNICIPIO MUN1 ON MUN1.AUX_MUN_CD_IBGE = END1.AUX_MUN_CD_IBGE
 JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PAC_ID_PACIENTE =  IAE.CAD_PAC_ID_PACIENTE
 JOIN TB_CAD_PES_PESSOA PES_PAC ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
 LEFT JOIN TB_CAD_END_ENDERECO END ON PES_PAC.CAD_PES_ID_PESSOA = END.CAD_PES_ID_PESSOA
 LEFT JOIN TB_AUX_MUN_MUNICIPIO MUN ON MUN.AUX_MUN_CD_IBGE = END.AUX_MUN_CD_IBGE
 JOIN TB_CAD_UNI_UNIDADE UNI ON UNI.CAD_UNI_ID_UNIDADE = IAE.CAD_UNI_ID_UNIDADE
 JOIN TB_CAD_CNV_CONVENIO CNV ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
 JOIN TB_CAD_PLA_PLANO PLA ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
 LEFT JOIN TB_TIS_TIN_TP_INTERNACAO TIN ON TIN.TIS_TIN_CD_INTERNACAO = IAE.TIS_TIN_CD_INTERNACAO
  
WHERE (IAE.ATD_IAE_ID = pATD_ATE_ID) 
  AND (IAE.ATD_IAE_ID NOT IN (SELECT ATD.ATD_ATE_ID FROM TB_ATD_ATE_ATENDIMENTO ATD WHERE ATD.ATD_ATE_ID = pATD_ATE_ID))
;
    io_cursor := v_cursor;
  end PRC_INT_REL_TERMO_ACOMOD_CNV;
