create or replace procedure PRC_CAD_MTMD_INVENTARIO_L
(
     pCAD_MTMD_ID IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_ID%type DEFAULT NULL,
     pCAD_MTMD_FILIAL_ID IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
     pCAD_SET_ID IN TB_CAD_MTMD_INVENTARIO.CAD_SET_ID%type DEFAULT NULL,
     pCAD_MTMD_DT_INVENTARIO IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_DT_INVENTARIO%type DEFAULT NULL,
     pCAD_MTMD_QTDE_1 IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_QTDE_1%type DEFAULT NULL,
     pCAD_MTMD_QTDE_2 IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_QTDE_2%type DEFAULT NULL,
     pCAD_MTMD_QTDE_3 IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_QTDE_3%type DEFAULT NULL,
     pCAD_MTMD_QTDE_FINAL IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_QTDE_FINAL%type DEFAULT NULL,
     pCAD_MTMD_DT_ATUALIZACAO IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_DT_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_MTMD_INVENTARIO.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pDIVERGENCIA_CONTAGEM_1 NUMBER DEFAULT NULL, -- 0 ou 1
     pDIVERGENCIA_CONTAGEM_2 NUMBER DEFAULT NULL, -- 0 ou 1
     pDIVERGENCIA_CONTAGEM_3 NUMBER DEFAULT NULL, -- 0 ou 1
     pMTMD_COD_LOTE IN TB_CAD_MTMD_INVENTARIO.MTMD_COD_LOTE%type DEFAULT NULL,
     pMTMD_NUM_LOTE IN TB_CAD_MTMD_INVENTARIO.MTMD_NUM_LOTE%type DEFAULT NULL,
     pFL_MEDICAMENTO IN TB_CAD_MTMD_INVENTARIO_FECHA.FL_MEDICAMENTO%type DEFAULT NULL,
     pCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_GRUPO_ID%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_CAD_MTMD_INVENTARIO_L
*
*    Data Criacao:    10/8/11   Por: Andre
*    Data Altera??o: 17/10/2018    Por: Andre Souza Monaco
*         Altera??o: Ordenar CAD_MTMD_ENDERECO_ALMOX_ACS
*                    quando Centro Cirurgico
*
*    Funcao: Lista itens digitados de inventario
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
begin
V_WHERE := NULL;
IF pCAD_MTMD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_ID = ' || pCAD_MTMD_ID; END IF;
IF pCAD_MTMD_FILIAL_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_FILIAL_ID = ' || pCAD_MTMD_FILIAL_ID; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_MTMD_DT_INVENTARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_DT_INVENTARIO = ' || CHR(39) || pCAD_MTMD_DT_INVENTARIO || CHR(39); END IF;
IF pCAD_MTMD_QTDE_1 IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_QTDE_1 = ' || pCAD_MTMD_QTDE_1; END IF;
IF pCAD_MTMD_QTDE_2 IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_QTDE_2 = ' || pCAD_MTMD_QTDE_2; END IF;
IF pCAD_MTMD_QTDE_3 IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_QTDE_3 = ' || pCAD_MTMD_QTDE_3; END IF;
IF pCAD_MTMD_QTDE_FINAL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_QTDE_FINAL = ' || pCAD_MTMD_QTDE_FINAL; END IF;
IF pCAD_MTMD_DT_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.CAD_MTMD_DT_ATUALIZACAO = ' || CHR(39) || pCAD_MTMD_DT_ATUALIZACAO || CHR(39); END IF;
IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
IF pMTMD_COD_LOTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.MTMD_COD_LOTE = ' || pMTMD_COD_LOTE; END IF;
IF pMTMD_NUM_LOTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND INV.MTMD_NUM_LOTE = ' || pMTMD_NUM_LOTE; END IF;
IF pFL_MEDICAMENTO IS NOT NULL THEN
  IF pFL_MEDICAMENTO = 1 THEN
    V_WHERE:= V_WHERE || ' AND PRODUTO.TIS_MED_CD_TABELAMEDICA = 96 ';
  ELSE
    V_WHERE:= V_WHERE || ' AND PRODUTO.TIS_MED_CD_TABELAMEDICA = 95 ';
  END IF;
END IF;
IF pCAD_MTMD_GRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_GRUPO_ID = ' || pCAD_MTMD_GRUPO_ID; END IF;
IF (NVL(pDIVERGENCIA_CONTAGEM_2, 0) = 1) THEN
  V_WHERE:= V_WHERE || ' AND (INV.CAD_MTMD_QTDE_2 IS NOT NULL AND NVL(INV.CAD_MTMD_QTDE_1,0) <> NVL(INV.CAD_MTMD_QTDE_2,0)) ';
  --V_WHERE:= V_WHERE || ' AND NVL(INV.CAD_MTMD_QTDE_1,0) <> NVL(INV.CAD_MTMD_QTDE_ANTERIOR,0) ';
  --V_WHERE:= V_WHERE || ' AND NVL(INV.CAD_MTMD_QTDE_2,0) <> NVL(INV.CAD_MTMD_QTDE_ANTERIOR,0) ';
END IF;
IF (NVL(pDIVERGENCIA_CONTAGEM_3, 0) = 1) THEN
  V_WHERE:= V_WHERE || ' AND (INV.CAD_MTMD_QTDE_3 IS NOT NULL AND NVL(INV.CAD_MTMD_QTDE_2,0) <> NVL(INV.CAD_MTMD_QTDE_3,0)) ';
END IF;
IF (NVL(pDIVERGENCIA_CONTAGEM_1, 0) = 1) THEN
  V_WHERE:= V_WHERE || ' AND NVL(INV.CAD_MTMD_QTDE_1,0) <> NVL(INV.CAD_MTMD_QTDE_ANTERIOR,0) ';
ELSIF (NVL(pDIVERGENCIA_CONTAGEM_2, 0) != 1 AND NVL(pDIVERGENCIA_CONTAGEM_3, 0) != 1) THEN
  V_WHERE:= V_WHERE || ' AND (INV.CAD_MTMD_QTDE_1 IS NOT NULL OR INV.CAD_MTMD_QTDE_2 IS NOT NULL OR INV.CAD_MTMD_QTDE_3 IS NOT NULL) ';
END IF;
V_SELECT := '
SELECT
       INV.CAD_MTMD_ID,
       INV.CAD_MTMD_FILIAL_ID,
       INV.CAD_SET_ID,
       INV.CAD_MTMD_DT_INVENTARIO,
       INV.CAD_MTMD_QTDE_1,
       INV.CAD_MTMD_QTDE_2,
       INV.CAD_MTMD_QTDE_3,
       INV.CAD_MTMD_QTDE_FINAL,
       INV.CAD_MTMD_DT_ATUALIZACAO,
       INV.SEG_USU_ID_USUARIO,
       PRODUTO.CAD_MTMD_NOMEFANTASIA || DECODE(PRODUTO.CAD_MTMD_FL_FRACIONA, 1, '' *'') CAD_MTMD_NOMEFANTASIA,
       PRODUTO.CAD_MTMD_GRUPO_ID,
       PRODUTO.CAD_MTMD_UNID_CONTROLE_DS,
       PRODUTO.CAD_MTMD_UNID_VENDA_DS,
       NVL(DECODE(INV.CAD_SET_ID, 61, PRODUTO.CAD_MTMD_ENDERECO_ALMOX_ACS, PRODUTO.CAD_MTMD_ENDERECO_ALMOX_HAC),999999999) CAD_MTMD_ENDERECO_ALMOX,
       INV.MTMD_COD_LOTE,
       INV.MTMD_NUM_LOTE
FROM TB_CAD_MTMD_INVENTARIO INV,
     TB_CAD_MTMD_MAT_MED    PRODUTO
WHERE PRODUTO.CAD_MTMD_ID = INV.CAD_MTMD_ID ';
OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_CAD_MTMD_INVENTARIO_L;