 
--PRC_ASS_CUI_CONV_UNI_IMPOSTO_L
create or replace procedure PRC_ASS_CUI_CONV_UNI_IMPOSTO_L 
(
     pASS_CUI_ID IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CUI_ID%type DEFAULT NULL,
     pASS_CUI_DT_INI_VIGENCIA IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CUI_DT_INI_VIGENCIA%type DEFAULT NULL,
     pASS_CUI_DT_FIM_VIGENCIA IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CUI_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pASS_CNU_ID IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CNU_ID%type DEFAULT NULL,
     pASS_CUI_PC_IMPOSTO IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CUI_PC_IMPOSTO%type DEFAULT NULL,
     pASS_CUI_DS_MOTIVO_FIM_VIG IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CUI_DS_MOTIVO_FIM_VIGENCIA%type DEFAULT NULL,
     pASS_CUI_DT_ULTIMA_ATUALIZACAO IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CUI_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pCAD_IMP_ID_IMPOSTO IN TB_ASS_CUI_CONV_UNI_IMPOSTO.CAD_IMP_ID_IMPOSTO%type DEFAULT NULL,
     pASS_CUI_VL_MIN_RECOLHIM IN TB_ASS_CUI_CONV_UNI_IMPOSTO.ASS_CUI_VL_MIN_RECOLHIM%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ASS_CUI_CONV_UNI_IMPOSTO.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
/********************************************************************
*    Procedure: PRC_ASS_CUI_CONV_UNI_IMPOSTO_L
* 
*    Data Criacao:   data da  criação   Por: Nome do Analista
*    Data Alteracao:  data da alteração  Por: Nome do Analista
*
*    Funcao: Descrição da funcionalidade da Stored Procedure
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
begin
  V_WHERE := NULL;
  IF pASS_CUI_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CUI_ID = ' || pASS_CUI_ID; END IF;
IF pASS_CUI_DT_INI_VIGENCIA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CUI_DT_INI_VIGENCIA = ' || CHR(39) || pASS_CUI_DT_INI_VIGENCIA || CHR(39); END IF;
IF pASS_CUI_DT_FIM_VIGENCIA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CUI_DT_FIM_VIGENCIA = ' || CHR(39) || pASS_CUI_DT_FIM_VIGENCIA || CHR(39); END IF;
IF pASS_CNU_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CNU_ID = ' || pASS_CNU_ID; END IF;
IF pASS_CUI_PC_IMPOSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CUI_PC_IMPOSTO = ' || pASS_CUI_PC_IMPOSTO; END IF;
IF pASS_CUI_DS_MOTIVO_FIM_VIG IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CUI_DS_MOTIVO_FIM_VIGENCIA = ' || CHR(39) || pASS_CUI_DS_MOTIVO_FIM_VIGENCIA || CHR(39); END IF;
IF pASS_CUI_DT_ULTIMA_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CUI_DT_ULTIMA_ATUALIZACAO = ' || CHR(39) || pASS_CUI_DT_ULTIMA_ATUALIZACAO || CHR(39); END IF;
IF pCAD_IMP_ID_IMPOSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_IMP_ID_IMPOSTO = ' || pCAD_IMP_ID_IMPOSTO; END IF;
IF pASS_CUI_VL_MIN_RECOLHIM IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_CUI_VL_MIN_RECOLHIM = ' || pASS_CUI_VL_MIN_RECOLHIM; END IF;
IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
 
   V_SELECT := '
SELECT  
       ASS_CUI_ID,
       ASS_CUI_DT_INI_VIGENCIA,
       ASS_CUI_DT_FIM_VIGENCIA,
       ASS_CNU_ID,
       ASS_CUI_PC_IMPOSTO,
       ASS_CUI_DS_MOTIVO_FIM_VIGENCIA,
       ASS_CUI_DT_ULTIMA_ATUALIZACAO,
       CAD_IMP_ID_IMPOSTO,
       ASS_CUI_VL_MIN_RECOLHIM,
       SEG_USU_ID_USUARIO
FROM TB_ASS_CUI_CONV_UNI_IMPOSTO
WHERE null is null  '    ;
       
OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_ASS_CUI_CONV_UNI_IMPOSTO_L;
