CREATE OR REPLACE PROCEDURE PRC_MTMD_REQ_REQUISICAO_U
  (
     pMTMD_REQ_ID             IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_ID%type,
     pMTMD_REQ_FL_STATUS      IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_FL_STATUS%type default NULL,
     pSEG_USU_ID_USUARIO      IN TB_MTMD_REQ_REQUISICAO.SEG_USU_ID_USUARIO%TYPE DEFAULT NULL,
     pMTMD_REQ_ID_REF         IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_ID_REF%TYPE DEFAULT NULL,
     pMTMD_REQ_FL_URGENCIA    IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_FL_URGENCIA%TYPE DEFAULT NULL
  )
  is
     pMTMD_DATA_REQUISICAO         TB_MTMD_REQ_REQUISICAO.mtmd_data_requisicao%TYPE DEFAULT NULL;
     pMTMD_ID_USUARIO_REQUISICAO   TB_MTMD_REQ_REQUISICAO.mtmd_id_usuario_requisicao%TYPE DEFAULT NULL;
     pMTMD_DATA_DISPENSACAO        TB_MTMD_REQ_REQUISICAO.mtmd_data_dispensacao%TYPE DEFAULT NULL;
     pMTMD_ID_USUARIO_DISPENSACAO  TB_MTMD_REQ_REQUISICAO.mtmd_id_usuario_dispensacao%TYPE DEFAULT NULL;
     vMTMD_REQ_FL_STATUS           TB_MTMD_REQ_REQUISICAO.MTMD_REQ_FL_STATUS%type default NULL;
     vCAD_SET_ID                   TB_MTMD_REQ_REQUISICAO.CAD_SET_ID%TYPE DEFAULT NULL;
  BEGIN

    -- VERIFICA SE A REQUISICAO FOI FECHADA PARA ENVIO PRO ALMOXARIFADO
    IF ( pMTMD_REQ_FL_STATUS = 2 ) THEN
       SELECT R.MTMD_REQ_FL_STATUS, R.CAD_SET_ID
         INTO vMTMD_REQ_FL_STATUS,  vCAD_SET_ID
         FROM TB_MTMD_REQ_REQUISICAO R WHERE MTMD_REQ_ID = pMTMD_REQ_ID;

       IF (vMTMD_REQ_FL_STATUS = 2) THEN
          RAISE_APPLICATION_ERROR(-20003, 'ESTA REQUISIC?O NAO PODE SER SALVA, POIS JA FOI ENVIADA AO ALMOXARIFADO. FAVOR CANCELAR E INCLUIR UMA NOVA');
       ELSIF (vMTMD_REQ_FL_STATUS = 3 AND vCAD_SET_ID = 2252) THEN --DISPENSADA ATENDIMENTO DOMICILIAR (volta de status devido a estorno, nao atualiza usuario requisicao)

             UPDATE TB_MTMD_REQ_REQUISICAO SET
             MTMD_REQ_FL_STATUS          = pMTMD_REQ_FL_STATUS,
             MTMD_REQ_DT_ATUALIZACAO     = SYSDATE,
             SEG_USU_ID_USUARIO          = pSEG_USU_ID_USUARIO
             WHERE MTMD_REQ_ID = pMTMD_REQ_ID;
       ELSE
             pMTMD_DATA_REQUISICAO       := SYSDATE;
             pMTMD_ID_USUARIO_REQUISICAO := pSEG_USU_ID_USUARIO;

             UPDATE TB_MTMD_REQ_REQUISICAO SET
             MTMD_REQ_FL_STATUS          = pMTMD_REQ_FL_STATUS,
             MTMD_REQ_DT_ATUALIZACAO     = SYSDATE,
             SEG_USU_ID_USUARIO          = pSEG_USU_ID_USUARIO,
             MTMD_DATA_REQUISICAO        = pMTMD_DATA_REQUISICAO,
             MTMD_ID_USUARIO_REQUISICAO  = pMTMD_ID_USUARIO_REQUISICAO
             WHERE MTMD_REQ_ID = pMTMD_REQ_ID;
       END IF;
    ELSIF ( pMTMD_REQ_FL_STATUS IN (3,8) ) THEN -- DISPENSADA ALMOXARIFADO / DEVOLVIDA
       pMTMD_DATA_DISPENSACAO        := SYSDATE;
       pMTMD_ID_USUARIO_DISPENSACAO  :=pSEG_USU_ID_USUARIO;
       --
       UPDATE TB_MTMD_REQ_REQUISICAO SET
       MTMD_REQ_FL_STATUS          = pMTMD_REQ_FL_STATUS,
       MTMD_REQ_DT_ATUALIZACAO     = SYSDATE,
       SEG_USU_ID_USUARIO          = pSEG_USU_ID_USUARIO,
       MTMD_DATA_DISPENSACAO       = pMTMD_DATA_DISPENSACAO,
       MTMD_ID_USUARIO_DISPENSACAO = pMTMD_ID_USUARIO_DISPENSACAO
       WHERE MTMD_REQ_ID = pMTMD_REQ_ID;
    ELSE -- OUTRAS
       IF (pMTMD_REQ_ID_REF IS NULL) THEN
         UPDATE TB_MTMD_REQ_REQUISICAO SET
         MTMD_REQ_FL_STATUS          = pMTMD_REQ_FL_STATUS,
         MTMD_REQ_DT_ATUALIZACAO     = SYSDATE,
         SEG_USU_ID_USUARIO          = pSEG_USU_ID_USUARIO,
         MTMD_REQ_FL_URGENCIA        = pMTMD_REQ_FL_URGENCIA
         WHERE MTMD_REQ_ID = pMTMD_REQ_ID;
       ELSE
         UPDATE TB_MTMD_REQ_REQUISICAO SET
         MTMD_REQ_FL_STATUS          = pMTMD_REQ_FL_STATUS,
         MTMD_REQ_DT_ATUALIZACAO     = SYSDATE,
         SEG_USU_ID_USUARIO          = pSEG_USU_ID_USUARIO,
         MTMD_REQ_ID_REF             = pMTMD_REQ_ID_REF
         WHERE MTMD_REQ_ID = pMTMD_REQ_ID;
       END IF;
    END IF;
  end PRC_MTMD_REQ_REQUISICAO_U;