create or replace procedure PRC_FAT_REL_GUIA_DESPESAS
  (
    pLOTE IN TB_FAT_FCL_CONTR_EMI_LOTE.FAT_FCL_NR_SEQ_LOTE%TYPE DEFAULT NULL,
    pATD_ATE_ID IN TSS_OUTRASDESP_SGS.NR_ATENDIMENTO%TYPE DEFAULT NULL,
    pFAT_CCP_ID IN TSS_OUTRASDESP_SGS.CD_PARCELA%TYPE DEFAULT NULL,
    pCAD_PAC_ID_PACIENTE IN TSS_OUTRASDESP_SGS.IDT_PACIENTE%TYPE DEFAULT NULL,
    pFAT_COC_ID IN TSS_OUTRASDESP_SGS.NR_CONTA%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_FAT_REL_GUIA_DESPESAS
  *
  *    Data Criacao: 18/05/2010  Por: Pedro
  *
  *    Data Alteracao: 04/02/2011  Por: Davi Silvestre M. dos Reis
  *    Alterac?o: Remocao do DECODE que enviava NULL na data,
  *               para os casos de CD_TP_DESPESA igual a 2 ou 3
  *
    *    Data Alteracao: 23/02/2011  Por: Pedro
  *    Alterac?o: if
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
  if pATD_ATE_ID is null then --a diferença é o (IS NULL OR ) dos parametros para reduzir o custo
    OPEN v_cursor FOR
select
  S.CD_CONVENIO,
  S.DS_CONVENIO,
  S.NR_ATENDIMENTO,
  S.CD_PARCELA,
  S.IDT_PACIENTE,
  S.NR_CONTA,
  S.CD_REGISTRO_ANS registroans,
  S.NR_GUIA_REF guiareferenciada,
  S.CD_OPER_CNPJ_CPF_CONT codigooperadora,
  S.NM_CONT nomecontratado,
  S.CD_CNES_CONT codigocnes,
  P.NR_SEQ,
  CEIL(P.NR_SEQ / 13) QUEBRA_EM_13,
  P.CD_TABELAS tabela,
  P.CD_PROC_REAL codigodoitem,
  P.DS_DESPESA descricao,
  REPLACE(TO_CHAR(SUM( P.QT_PROC_REAL)),'.', ',')qtde,
--  DECODE( CD_TP_DESPESA, 2, null, 3, null, P.DT_REAL) Data,
  P.DT_REAL Data,
--  decode(CCP.FAT_CCP_DT_PARCELA_INI,null,CCP.FAT_CCP_DT_PARCELA,CCP.FAT_CCP_DT_PARCELA_INI) Data,
  DECODE(P.HR_INI_PROC,NULL,'', SUBSTR(LPAD(TO_CHAR(P.HR_INI_PROC),4,'0'),1,2) || ':' || SUBSTR(LPAD(TO_CHAR(P.HR_INI_PROC),4,'0'),3,2)) horaINIcial,
  DECODE(P.HR_FIM_PROC,NULL,'', SUBSTR(LPAD(TO_CHAR(P.HR_FIM_PROC),4,'0'),1,2) || ':' || SUBSTR(LPAD(TO_CHAR(P.HR_FIM_PROC),4,'0'),3,2)) horaFInal,
  P.NR_RED_ACR  percentualredacre,
  P.VL_UNIT_PROC valorunitario,
  SUM(P.VL_TOTAL_PROC) valortotal,
  P.CD_TP_DESPESA codigodespesarealizada,
  decode( p.cd_tp_despesa, 2, P.DS_DESPESA, 3, DS_DESPESA, P.CD_PROC_REAL) ordem,
  nvl(GASES.TOTAL,0)  totalgasesmedicinais,
  nvl(MED.TOTAL,0)    totalmedicamento,
  nvl(MAT.TOTAL,0)   totalmateriais,
  nvl(TAX.TOTAL,0)   totaltaxasdiversas,
  nvl(DIA.TOTAL,0)   totaldiarias,
  nvl(ALU.TOTAL,0)   totalalugueis,
  nvl(SUM(P.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P.NR_SEQ / 13) ),0) totalgeral
from TSS_OUTRASDESP_SGS S,
     TSS_OUTRASDESP_PROC_SGS P,
     TB_FAT_CCP_CONTA_CONS_PARC CCP,
     TB_FAT_FCL_CONTR_EMI_LOTE FCL,
  (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '1'   AND (pFAT_CCP_ID IS NULL OR P2.CD_PARCELA = pFAT_CCP_ID)
    and (pATD_ATE_ID IS NULL OR P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (pFAT_COC_ID IS NULL OR P2.NR_CONTA  = pFAT_COC_ID)
    AND (pCAD_PAC_ID_PACIENTE IS NULL OR P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)
   ) GASES,
   (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '2'
    and (pATD_ATE_ID IS NULL OR P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (pFAT_COC_ID IS NULL OR P2.NR_CONTA  = pFAT_COC_ID)
    AND (pCAD_PAC_ID_PACIENTE IS NULL OR P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)
   ) MED,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '3'
    and (pATD_ATE_ID IS NULL OR P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (pFAT_COC_ID IS NULL OR P2.NR_CONTA  = pFAT_COC_ID)
    AND (pCAD_PAC_ID_PACIENTE IS NULL OR P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)
   ) MAT,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '4'
    and (pATD_ATE_ID IS NULL OR P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (pFAT_COC_ID IS NULL OR P2.NR_CONTA  = pFAT_COC_ID)
    AND (pCAD_PAC_ID_PACIENTE IS NULL OR P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)
   ) TAX,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '5'
    and (pATD_ATE_ID IS NULL OR P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (pFAT_COC_ID IS NULL OR P2.NR_CONTA  = pFAT_COC_ID)
    AND (pCAD_PAC_ID_PACIENTE IS NULL OR P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)
   ) DIA,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '6'
    and (pATD_ATE_ID IS NULL OR P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (pFAT_COC_ID IS NULL OR P2.NR_CONTA  = pFAT_COC_ID)
    AND (pCAD_PAC_ID_PACIENTE IS NULL OR P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)
   ) ALU
where
    S.CD_PARCELA               = P.CD_PARCELA
and S.NR_ATENDIMENTO           = P.NR_ATENDIMENTO
AND S.NR_CONTA                 = P.NR_CONTA
AND S.IDT_PACIENTE             = P.IDT_PACIENTE
and S.CD_REGISTRO_ANS          = P.CD_REGISTRO_ANS
and S.NR_GUIA_REF              = P.NR_GUIA_REF
AND GASES.CD_PARCELA        (+)   = P.CD_PARCELA
and GASES.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND GASES.NR_CONTA          (+)   = P.NR_CONTA
AND GASES.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and GASES.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and GASES.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND GASES.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND MED.CD_PARCELA        (+)   = P.CD_PARCELA
and MED.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND MED.NR_CONTA          (+)   = P.NR_CONTA
AND MED.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and MED.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and MED.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND MED.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND MAT.CD_PARCELA        (+)   = P.CD_PARCELA
and MAT.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND MAT.NR_CONTA          (+)   = P.NR_CONTA
AND MAT.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and MAT.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and MAT.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND MAT.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND TAX.CD_PARCELA        (+)   = P.CD_PARCELA
and TAX.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND TAX.NR_CONTA          (+)   = P.NR_CONTA
AND TAX.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and TAX.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and TAX.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND TAX.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND DIA.CD_PARCELA        (+)   = P.CD_PARCELA
and DIA.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND DIA.NR_CONTA          (+)   = P.NR_CONTA
AND DIA.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and DIA.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and DIA.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND DIA.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND ALU.CD_PARCELA        (+)   = P.CD_PARCELA
and ALU.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND ALU.NR_CONTA          (+)   = P.NR_CONTA
AND ALU.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and ALU.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and ALU.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND ALU.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND FCL.FAT_COC_ID            = S.NR_CONTA
AND FCL.FAT_CCP_ID            = S.CD_PARCELA
AND FCL.ATD_ATE_ID            = S.NR_ATENDIMENTO
AND FCL.CAD_PAC_ID_PACIENTE   = S.IDT_PACIENTE
AND CCP.FAT_COC_ID            = S.NR_CONTA
AND CCP.FAT_CCP_ID            = S.CD_PARCELA
AND CCP.ATD_ATE_ID            = S.NR_ATENDIMENTO
AND CCP.CAD_PAC_ID_PACIENTE   = S.IDT_PACIENTE
and (pLOTE is null or FCL.FAT_FCL_NR_SEQ_LOTE  = pLOTE)
AND (pATD_ATE_ID IS NULL OR FCL.ATD_ATE_ID = pATD_ATE_ID)
AND (pFAT_CCP_ID IS NULL OR FCL.FAT_CCP_ID = pFAT_CCP_ID)
AND (pCAD_PAC_ID_PACIENTE IS NULL OR FCL.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE)
AND (pFAT_COC_ID IS NULL OR FCL.FAT_COC_ID = pFAT_COC_ID)
GROUP BY S.CD_CONVENIO,
         S.DS_CONVENIO,
         S.NR_ATENDIMENTO,
         S.CD_PARCELA,
         S.IDT_PACIENTE,
         S.NR_CONTA,
         S.CD_REGISTRO_ANS,
         S.NR_GUIA_REF,
         S.CD_OPER_CNPJ_CPF_CONT,
         S.NM_CONT,
         S.CD_CNES_CONT,
         P.NR_SEQ,
         CEIL(P.NR_SEQ / 13) ,
         P.CD_TABELAS,
         P.CD_PROC_REAL,
         P.DS_DESPESA,
         P.DT_REAL,
     --    decode(CCP.FAT_CCP_DT_PARCELA_INI,null,CCP.FAT_CCP_DT_PARCELA,CCP.FAT_CCP_DT_PARCELA_INI),
         P.HR_INI_PROC,  P.HR_FIM_PROC, P.NR_RED_ACR, P.CD_TP_DESPESA,
         P.VL_UNIT_PROC,
         P.VL_TOTAL_PROC,
         nvl(GASES.TOTAL,0),
        nvl(MED.TOTAL,0) ,
        nvl(MAT.TOTAL,0) ,
        nvl(TAX.TOTAL,0) ,
        nvl(DIA.TOTAL,0) ,
        nvl(ALU.TOTAL,0)
        having SUM(P.VL_TOTAL_PROC) > 0
order by P.NR_SEQ -- P.CD_TP_DESPESA, data, horaINIcial, horafinal, ORDEM
;
             io_cursor := v_cursor;
else
 OPEN v_cursor FOR
select
  S.CD_CONVENIO,
  S.DS_CONVENIO,
  S.NR_ATENDIMENTO,
  S.CD_PARCELA,
  S.IDT_PACIENTE,
  S.NR_CONTA,
  S.CD_REGISTRO_ANS registroans,
  S.NR_GUIA_REF guiareferenciada,
  S.CD_OPER_CNPJ_CPF_CONT codigooperadora,
  S.NM_CONT nomecontratado,
  S.CD_CNES_CONT codigocnes,
  P.NR_SEQ,
  CEIL(P.NR_SEQ / 13) QUEBRA_EM_13,
  P.CD_TABELAS tabela,
  P.CD_PROC_REAL codigodoitem,
  P.DS_DESPESA descricao,
  REPLACE(TO_CHAR(SUM( P.QT_PROC_REAL)),'.', ',')qtde,
--  DECODE( CD_TP_DESPESA, 2, null, 3, null, P.DT_REAL) Data,
  P.DT_REAL Data,
 -- decode(CCP.FAT_CCP_DT_PARCELA_INI,null,CCP.FAT_CCP_DT_PARCELA,CCP.FAT_CCP_DT_PARCELA_INI) Data,
  DECODE(P.HR_INI_PROC,NULL,'', SUBSTR(LPAD(TO_CHAR(P.HR_INI_PROC),4,'0'),1,2) || ':' || SUBSTR(LPAD(TO_CHAR(P.HR_INI_PROC),4,'0'),3,2)) horaINIcial,
  DECODE(P.HR_FIM_PROC,NULL,'', SUBSTR(LPAD(TO_CHAR(P.HR_FIM_PROC),4,'0'),1,2) || ':' || SUBSTR(LPAD(TO_CHAR(P.HR_FIM_PROC),4,'0'),3,2)) horaFInal,
  P.NR_RED_ACR  percentualredacre,
  P.VL_UNIT_PROC valorunitario,
  SUM(P.VL_TOTAL_PROC) valortotal,
  P.CD_TP_DESPESA codigodespesarealizada,
  decode( p.cd_tp_despesa, 2, P.DS_DESPESA, 3, DS_DESPESA, P.CD_PROC_REAL) ordem,
  nvl(GASES.TOTAL,0)  totalgasesmedicinais,
  nvl(MED.TOTAL,0)    totalmedicamento,
  nvl(MAT.TOTAL,0)   totalmateriais,
  nvl(TAX.TOTAL,0)   totaltaxasdiversas,
  nvl(DIA.TOTAL,0)   totaldiarias,
  nvl(ALU.TOTAL,0)   totalalugueis,
  nvl(SUM(P.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P.NR_SEQ / 13) ),0) totalgeral
from TSS_OUTRASDESP_SGS S,
     TSS_OUTRASDESP_PROC_SGS P,
     TB_FAT_CCP_CONTA_CONS_PARC CCP,
     TB_FAT_FCL_CONTR_EMI_LOTE FCL,
  (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '1'   
   AND (P2.CD_PARCELA = pFAT_CCP_ID)  and (P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (P2.NR_CONTA  = pFAT_COC_ID) AND (P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)
   ) GASES,
   (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '2'
   AND (P2.CD_PARCELA = pFAT_CCP_ID)  and (P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (P2.NR_CONTA  = pFAT_COC_ID) AND (P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)  ) MED,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '3'
   AND (P2.CD_PARCELA = pFAT_CCP_ID)  and (P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (P2.NR_CONTA  = pFAT_COC_ID) AND (P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)  ) MAT,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '4'
   AND (P2.CD_PARCELA = pFAT_CCP_ID)  and (P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (P2.NR_CONTA  = pFAT_COC_ID) AND (P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)   ) TAX,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '5'
   AND (P2.CD_PARCELA = pFAT_CCP_ID)  and (P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (P2.NR_CONTA  = pFAT_COC_ID) AND (P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)  ) DIA,
    (SELECT DISTINCT SUM(P2.VL_TOTAL_PROC) OVER (PARTITION BY CEIL(P2.NR_SEQ / 13), P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF)  TOTAL, CEIL(P2.NR_SEQ / 13) QUEBRA_EM_13,
           P2.CD_PARCELA,P2.NR_ATENDIMENTO, P2.NR_CONTA, P2.IDT_PACIENTE, P2.CD_REGISTRO_ANS, P2.NR_GUIA_REF    FROM TSS_OUTRASDESP_PROC_SGS P2
   WHERE   P2.CD_TP_DESPESA            = '6'
   AND (P2.CD_PARCELA = pFAT_CCP_ID)  and (P2.NR_ATENDIMENTO = pATD_ATE_ID) AND (P2.NR_CONTA  = pFAT_COC_ID) AND (P2.IDT_PACIENTE = pCAD_PAC_ID_PACIENTE)  ) ALU
where
    S.CD_PARCELA               = P.CD_PARCELA
and S.NR_ATENDIMENTO           = P.NR_ATENDIMENTO
AND S.NR_CONTA                 = P.NR_CONTA
AND S.IDT_PACIENTE             = P.IDT_PACIENTE
and S.CD_REGISTRO_ANS          = P.CD_REGISTRO_ANS
and S.NR_GUIA_REF              = P.NR_GUIA_REF
AND GASES.CD_PARCELA        (+)   = P.CD_PARCELA
and GASES.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND GASES.NR_CONTA          (+)   = P.NR_CONTA
AND GASES.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and GASES.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and GASES.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND GASES.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND MED.CD_PARCELA        (+)   = P.CD_PARCELA
and MED.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND MED.NR_CONTA          (+)   = P.NR_CONTA
AND MED.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and MED.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and MED.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND MED.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND MAT.CD_PARCELA        (+)   = P.CD_PARCELA
and MAT.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND MAT.NR_CONTA          (+)   = P.NR_CONTA
AND MAT.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and MAT.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and MAT.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND MAT.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND TAX.CD_PARCELA        (+)   = P.CD_PARCELA
and TAX.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND TAX.NR_CONTA          (+)   = P.NR_CONTA
AND TAX.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and TAX.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and TAX.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND TAX.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND DIA.CD_PARCELA        (+)   = P.CD_PARCELA
and DIA.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND DIA.NR_CONTA          (+)   = P.NR_CONTA
AND DIA.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and DIA.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and DIA.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND DIA.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND ALU.CD_PARCELA        (+)   = P.CD_PARCELA
and ALU.NR_ATENDIMENTO    (+)   = P.NR_ATENDIMENTO
AND ALU.NR_CONTA          (+)   = P.NR_CONTA
AND ALU.IDT_PACIENTE      (+)   = P.IDT_PACIENTE
and ALU.CD_REGISTRO_ANS   (+)   = P.CD_REGISTRO_ANS
and ALU.NR_GUIA_REF       (+)   = P.NR_GUIA_REF
AND ALU.QUEBRA_EM_13       (+)  = CEIL(P.NR_SEQ / 13)
AND FCL.FAT_COC_ID            = S.NR_CONTA
AND FCL.FAT_CCP_ID            = S.CD_PARCELA
AND FCL.ATD_ATE_ID            = S.NR_ATENDIMENTO
AND FCL.CAD_PAC_ID_PACIENTE   = S.IDT_PACIENTE
AND CCP.FAT_COC_ID            = S.NR_CONTA
AND CCP.FAT_CCP_ID            = S.CD_PARCELA
AND CCP.ATD_ATE_ID            = S.NR_ATENDIMENTO
AND CCP.CAD_PAC_ID_PACIENTE   = S.IDT_PACIENTE
and (pLOTE is null or FCL.FAT_FCL_NR_SEQ_LOTE  = pLOTE)
AND (pATD_ATE_ID IS NULL OR FCL.ATD_ATE_ID = pATD_ATE_ID)
AND (pFAT_CCP_ID IS NULL OR FCL.FAT_CCP_ID = pFAT_CCP_ID)
AND (pCAD_PAC_ID_PACIENTE IS NULL OR FCL.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE)
AND (pFAT_COC_ID IS NULL OR FCL.FAT_COC_ID = pFAT_COC_ID)
GROUP BY S.CD_CONVENIO,
         S.DS_CONVENIO,
         S.NR_ATENDIMENTO,
         S.CD_PARCELA,
         S.IDT_PACIENTE,
         S.NR_CONTA,
         S.CD_REGISTRO_ANS,
         S.NR_GUIA_REF,
         S.CD_OPER_CNPJ_CPF_CONT,
         S.NM_CONT,
         S.CD_CNES_CONT,
         P.NR_SEQ,
         CEIL(P.NR_SEQ / 13) ,
         P.CD_TABELAS,
         P.CD_PROC_REAL,
         P.DS_DESPESA,
         P.DT_REAL,
       --  decode(CCP.FAT_CCP_DT_PARCELA_INI,null,CCP.FAT_CCP_DT_PARCELA,CCP.FAT_CCP_DT_PARCELA_INI),
         P.HR_INI_PROC,  P.HR_FIM_PROC, P.NR_RED_ACR, P.CD_TP_DESPESA,
         P.VL_UNIT_PROC,
         P.VL_TOTAL_PROC,
         nvl(GASES.TOTAL,0),
        nvl(MED.TOTAL,0) ,
        nvl(MAT.TOTAL,0) ,
        nvl(TAX.TOTAL,0) ,
        nvl(DIA.TOTAL,0) ,
        nvl(ALU.TOTAL,0)
        having SUM(P.VL_TOTAL_PROC) > 0
order by P.NR_SEQ
  ;
             io_cursor := v_cursor;
end if;
  end PRC_FAT_REL_GUIA_DESPESAS;
/
