--PRC_CAD_CEC_CENTRO_CUSTO_L
create or replace procedure PRC_CAD_CEC_CENTRO_CUSTO_L 
(
     pCAD_CEC_ID_CCUSTO IN TB_CAD_CEC_CENTRO_CUSTO.CAD_CEC_ID_CCUSTO%type DEFAULT NULL,
     pCAD_CEC_CD_CCUSTO IN TB_CAD_CEC_CENTRO_CUSTO.CAD_CEC_CD_CCUSTO%type DEFAULT NULL,
     pCAD_CEC_DS_CCUSTO IN TB_CAD_CEC_CENTRO_CUSTO.CAD_CEC_DS_CCUSTO%type DEFAULT NULL,
     pCAD_CEC_FL_CCUSTO IN TB_CAD_CEC_CENTRO_CUSTO.CAD_CEC_FL_CCUSTO%type DEFAULT NULL,
     pCAD_CEC_DT_ULTIMA_ATUALIZACAO IN TB_CAD_CEC_CENTRO_CUSTO.CAD_CEC_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_CEC_CENTRO_CUSTO.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
/********************************************************************
*    Procedure: PRC_CAD_CEC_CENTRO_CUSTO_L
* 
*    Data Criacao: 	data da  criação   Por: Nome do Analista
*    Data Alteracao:	data da alteração  Por: Nome do Analista
*
*    Funcao: Descrição da funcionalidade da Stored Procedure
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
begin
  V_WHERE := NULL;
  IF pCAD_CEC_ID_CCUSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CEC_ID_CCUSTO = ' || pCAD_CEC_ID_CCUSTO; END IF;
IF pCAD_CEC_CD_CCUSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CEC_CD_CCUSTO = ' || CHR(39) || pCAD_CEC_CD_CCUSTO || CHR(39); END IF;
IF pCAD_CEC_DS_CCUSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CEC_DS_CCUSTO = ' || CHR(39) || pCAD_CEC_DS_CCUSTO || CHR(39); END IF;
IF pCAD_CEC_FL_CCUSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CEC_FL_CCUSTO = ' || CHR(39) || pCAD_CEC_FL_CCUSTO || CHR(39); END IF;
IF pCAD_CEC_DT_ULTIMA_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CEC_DT_ULTIMA_ATUALIZACAO = ' || CHR(39) || pCAD_CEC_DT_ULTIMA_ATUALIZACAO || CHR(39); END IF;
IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
 
   V_SELECT := '
SELECT	
       CAD_CEC_ID_CCUSTO,
       CAD_CEC_CD_CCUSTO,
       CAD_CEC_DS_CCUSTO,
       CAD_CEC_FL_CCUSTO,
       CAD_CEC_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO
FROM TB_CAD_CEC_CENTRO_CUSTO
WHERE null is null  '    ;
       
OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_CAD_CEC_CENTRO_CUSTO_L;
