create or replace procedure PRC_CAD_MTMD_SIMILAR_S
(
   pCAD_MTMD_PRIATI_ID IN TB_CAD_MTMD_SIMILAR.CAD_MTMD_PRIATI_ID%type DEFAULT NULL,
   pCAD_MTMD_ID IN TB_CAD_MTMD_SIMILAR.CAD_MTMD_ID%type DEFAULT NULL,
   pCAD_FL_ATIVO IN TB_CAD_MTMD_SIMILAR.CAD_FL_ATIVO%type DEFAULT NULL,
   pCAD_MTMD_DT_ATUALIZACAO IN TB_CAD_MTMD_SIMILAR.CAD_MTMD_DT_ATUALIZACAO%type DEFAULT NULL,
   pSEG_USU_ID_USUARIO IN TB_CAD_MTMD_SIMILAR.SEG_USU_ID_USUARIO%type DEFAULT NULL,
   pCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_GRUPO_ID%type DEFAULT NULL,
   pCAD_MTMD_SUBGRUPO_ID IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_SUBGRUPO_ID%type DEFAULT NULL,
   io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_CAD_MTMD_SIMILAR_S
*
*    Data Criacao:  data da  criac?o   Por: Andre S. Monaco
*    Data Alteracao: 08/06/2016   Por: Andre S. Monaco
*         Alteracao: add. param. GRUPO_ID e SUBGRUPO_ID
*
*    Funcao: Descric?o da funcionalidade da Stored Procedure
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
V_WHERE  varchar2(5000);
V_SELECT  varchar2(5000);
begin   
   V_WHERE := NULL;
   IF pCAD_MTMD_PRIATI_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SIMILAR.CAD_MTMD_PRIATI_ID = ' || pCAD_MTMD_PRIATI_ID; END IF;
   IF pCAD_MTMD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SIMILAR.CAD_MTMD_ID = ' || pCAD_MTMD_ID; END IF;
   IF pCAD_FL_ATIVO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SIMILAR.CAD_FL_ATIVO = ' || pCAD_FL_ATIVO; END IF;
   IF pCAD_MTMD_DT_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SIMILAR.CAD_MTMD_DT_ATUALIZACAO = ' || CHR(39) || pCAD_MTMD_DT_ATUALIZACAO || CHR(39); END IF;
   IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SIMILAR.SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
   IF pCAD_MTMD_GRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MATMED.CAD_MTMD_GRUPO_ID = ' || pCAD_MTMD_GRUPO_ID; END IF;
   IF pCAD_MTMD_SUBGRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MATMED.CAD_MTMD_SUBGRUPO_ID = ' || pCAD_MTMD_SUBGRUPO_ID; END IF;  
    
   V_SELECT := 'SELECT SIMILAR.CAD_MTMD_PRIATI_ID,
                       SIMILAR.CAD_MTMD_ID,
                       SIMILAR.CAD_FL_ATIVO,
                       SIMILAR.CAD_MTMD_DT_ATUALIZACAO,
                       SIMILAR.SEG_USU_ID_USUARIO,
                       MATMED.CAD_MTMD_NOMEFANTASIA,
                       MATMED.CAD_MTMD_GRUPO_ID,
                       MATMED.CAD_MTMD_SUBGRUPO_ID
                    FROM TB_CAD_MTMD_SIMILAR SIMILAR,
                         TB_CAD_MTMD_MAT_MED MATMED
                WHERE SIMILAR.CAD_MTMD_ID = MATMED.CAD_MTMD_ID ';
              
OPEN v_cursor FOR
V_SELECT || V_WHERE ;
io_cursor := v_cursor;

end PRC_CAD_MTMD_SIMILAR_S;
 