CREATE OR REPLACE PROCEDURE "PRC_AGE_REL_ESTAT_ABS_CNV_PLA"
  (
     PDT_INICIO_CONSULTA IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_ATENDIMENTO%TYPE,
     PDT_FIM_CONSULTA IN TB_AGE_AGD_AGENDA.AGE_AGD_DT_ATENDIMENTO%TYPE,
     PCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
     PCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
     PTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
     PCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
     PCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
     PAGE_AGD_FL_STATUS IN TB_AGE_AGD_AGENDA.AGE_AGD_FL_STATUS%TYPE DEFAULT NULL,
     PAGE_ESM_HR_INI_ESCALA IN TB_AGE_ESM_ESCALA_MEDICA.AGE_ESM_HR_INI_ESCALA%TYPE DEFAULT NULL,
     PAGE_ESM_HR_FIM_ESCALA IN TB_AGE_ESM_ESCALA_MEDICA.AGE_ESM_HR_FIM_ESCALA%TYPE DEFAULT NULL,
     PCAD_PLA_CD_TIPOPLANO IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
     IO_CURSOR OUT PKG_CURSOR.T_CURSOR
  )
  IS
  /********************************************************************
  *    PROCEDURE: PRC_AGE_REL_ESTAT_ABS_CNV_PLA
  *
  *    DATA CRIACAO:  20/12/2010   POR: PEDRO
  *    DATA ALTERACAO: DATA DA ALTERAC?O  POR: NOME DO ANALISTA
  *
  *    FUNCAO: ALIMENTAR RELATORIO DE ABSENTEISMO POR CONVENIO E PLANO  ANALITICO
  *
  *******************************************************************/
  V_CURSOR PKG_CURSOR.T_CURSOR;
  BEGIN
    OPEN V_CURSOR FOR
    SELECT
           AGD.AGE_AGD_HR_ATENDIMENTO,
           AGD.AGE_AGD_DT_ATENDIMENTO,
           AGD.AGE_AGD_CD_INTAMB,
           PES.CAD_PES_NM_PESSOA NOME_PACIENTE,
           PAC.CAD_PAC_NR_PRONTUARIO,
           PLA.CAD_PLA_CD_PLANO_HAC,
           PLA.CAD_PLA_NM_NOME_PLANO,
           PAC.CAD_PAC_CD_CREDENCIAL,
          CASE WHEN PAC.CAD_CNV_ID_CONVENIO IN (281,283) THEN BB_TITULAR.NOME_TITULAR
                ELSE NVL(PAC.CAD_PAC_NM_TITULAR, PES.CAD_PES_NM_PESSOA) 
              END  CAD_PAC_NM_TITULAR,
           LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
           CBO.TIS_CBO_DS_CBOS_HAC,
           ESM.AGE_ESM_HR_INI_ESCALA,
           ESM.AGE_ESM_HR_FIM_ESCALA,
           AGD.AGE_AGD_DS_OBSERVACAO,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           CNV.CAD_CNV_NM_FANTASIA,
           UNI.CAD_UNI_DS_UNIDADE
    FROM
           TB_CAD_PES_PESSOA PES,
           TB_CAD_PAC_PACIENTE PAC,
           TB_AGE_AGD_AGENDA AGD,
           TB_AGE_ESM_ESCALA_MEDICA ESM,
           TB_CAD_UNI_UNIDADE UNI,
           TB_CAD_LAT_LOCAL_ATENDIMENTO LAT,
           TB_TIS_CBO_CBOS CBO,
           TB_AGE_AGG_AGENDA_GERADA AGG,
           TB_CAD_PLA_PLANO PLA,
           TB_CAD_CNV_CONVENIO CNV,
           (SELECT PAC.CAD_PAC_ID_PACIENTE,
                     BB_TITULAR.CODCON, BB_TITULAR.CODBEN, BB_TITULAR.CODEST,BB_TITULAR.CODSEQBEN,
                     BB_TITULAR.NOMBEN NOME_TITULAR 
                FROM TB_CAD_PAC_PACIENTE PAC,
                     TB_CAD_PLA_PLANO PLA,
                     BNF_BENEFICIARIO BB_TITULAR 
               WHERE PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
                 AND BB_TITULAR.CODCON = PLA.CAD_PLA_CD_PLANO
                 AND BB_TITULAR.CODEST = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,1,3))
                 AND BB_TITULAR.CODBEN = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,4,7))
                 AND BB_TITULAR.CODINDBEN = 'S'
                 AND LENGTH(PAC.CAD_PAC_CD_CREDENCIAL) = 12
                 AND PAC.CAD_CNV_ID_CONVENIO IN (281,283)
             ) BB_TITULAR
    WHERE
           AGD.AGE_AGD_FL_STATUS IN ( 'F','P')
           AND AGD.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
           AND AGD.AGE_AGG_ID = AGG.AGE_AGG_ID
           AND AGD.AGE_ESM_ID = ESM.AGE_ESM_ID
           AND AGG.AGE_ESM_ID = ESM.AGE_ESM_ID
           AND PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
           AND PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
           AND ESM.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
           AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO
           AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO != 28
           AND ESM.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
           AND PES.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
            AND BB_TITULAR.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE     
           AND AGD.AGE_AGD_DT_ATENDIMENTO BETWEEN PDT_INICIO_CONSULTA AND PDT_FIM_CONSULTA
           AND (PAGE_ESM_HR_INI_ESCALA IS NULL OR AGD.AGE_AGD_HR_ATENDIMENTO BETWEEN PAGE_ESM_HR_INI_ESCALA AND PAGE_ESM_HR_FIM_ESCALA)
           AND (PCAD_PLA_CD_TIPOPLANO IS NULL OR PLA.CAD_PLA_CD_TIPOPLANO = PCAD_PLA_CD_TIPOPLANO)
           AND (PCAD_UNI_ID_UNIDADE IS NULL OR UNI.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
           AND (PCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
           AND (PTIS_CBO_CD_CBOS IS NULL OR CBO.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
           AND (PCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = PCAD_PLA_ID_PLANO)
           AND (PCAD_CNV_ID_CONVENIO IS NULL OR CNV.CAD_CNV_ID_CONVENIO = PCAD_CNV_ID_CONVENIO);
    IO_CURSOR := V_CURSOR;
  END PRC_AGE_REL_ESTAT_ABS_CNV_PLA;
/
