create or replace procedure PRC_ASS_PMM_S
  (
     pCAD_CNV_ID_CONVENIO IN TB_ASS_PMM_PLANO_MATMED.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pCAD_PLA_ID_PLANO IN TB_ASS_PMM_PLANO_MATMED.CAD_PLA_ID_PLANO%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_PMM_PLANO_MATMED.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_MTMD_ID IN TB_ASS_PMM_PLANO_MATMED.CAD_MTMD_ID%type DEFAULT NULL,
     pASS_PMM_FL_EXIGE_GUIA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_EXIGE_GUIA%type DEFAULT NULL,
     pASS_PMM_FL_EXIGE_SENHA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_EXIGE_SENHA%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZATEL IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZATEL%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZAFAX IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAFAX%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZAPES IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAPES%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZAWEB IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAWEB%type DEFAULT NULL,
     pASS_PMM_FL_COBERTURA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_COBERTURA%type DEFAULT NULL,
     pASS_PMM_FL_STATUS IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_STATUS%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ASS_PMM_PLANO_MATMED.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pASS_PMM_DT_ULTIMA_ATUALIZACAO IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ASS_PMM_S
  *
  *    Data Criacao:  30/11/2009   Por: pedro
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT DISTINCT
       PNM.CAD_CNV_ID_CONVENIO,
       PNM.CAD_PLA_ID_PLANO,
       PNM.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       PNM.CAD_MTMD_ID,
       PNM.ASS_PMM_FL_EXIGE_GUIA,
       PNM.ASS_PMM_FL_EXIGE_SENHA,
       PNM.ASS_PMM_FL_AUTORIZATEL,
       PNM.ASS_PMM_FL_AUTORIZAFAX,
       PNM.ASS_PMM_FL_AUTORIZAPES,
       PNM.ASS_PMM_FL_AUTORIZAWEB,
       PNM.ASS_PMM_FL_COBERTURA,
       PNM.ASS_PMM_FL_STATUS,
       PNM.SEG_USU_ID_USUARIO,
       PNM.ASS_PMM_DT_ULTIMA_ATUALIZACAO,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       PLA.CAD_PLA_CD_PLANO_HAC,
       LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       MTMD.CAD_MTMD_CODMNE,
       MTMD.CAD_MTMD_DESCRICAO,
       MTMD.TIS_MED_CD_TABELAMEDICA,
       GRP.CAD_MTMD_GRUPO_ID,
       GRP.CAD_MTMD_GRUPO_DESCRICAO,
       SGR.CAD_MTMD_SUBGRUPO_ID,
       SGR.CAD_MTMD_SUBGRUPO_DESCRICAO
    FROM TB_ASS_PMM_PLANO_MATMED PNM
    JOIN TB_CAD_MTMD_MAT_MED     MTMD
    ON   MTMD.CAD_MTMD_ID      = PNM.CAD_MTMD_ID
    JOIN TB_CAD_CNV_CONVENIO     CNV
    ON   CNV.CAD_CNV_ID_CONVENIO = PNM.CAD_CNV_ID_CONVENIO
    JOIN TB_CAD_PLA_PLANO        PLA
    ON   PLA.CAD_PLA_ID_PLANO  = PNM.CAD_PLA_ID_PLANO
    JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
    ON   LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = PNM.CAD_LAT_ID_LOCAL_ATENDIMENTO
 JOIN TB_CAD_MTMD_GRUPO       GRP
    ON   GRP.CAD_MTMD_GRUPO_ID = MTMD.CAD_MTMD_GRUPO_ID
    JOIN TB_CAD_MTMD_SUBGRUPO    SGR
    ON   SGR.CAD_MTMD_SUBGRUPO_ID = MTMD.CAD_MTMD_SUBGRUPO_ID
    WHERE
        (pCAD_CNV_ID_CONVENIO is null OR PNM.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND
        (pCAD_PLA_ID_PLANO is null OR PNM.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO) AND
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR PNM.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND
        (pCAD_MTMD_ID is null OR PNM.CAD_MTMD_ID = pCAD_MTMD_ID) AND
        (pASS_PMM_FL_EXIGE_GUIA is null OR PNM.ASS_PMM_FL_EXIGE_GUIA = pASS_PMM_FL_EXIGE_GUIA) AND
        (pASS_PMM_FL_EXIGE_SENHA is null OR PNM.ASS_PMM_FL_EXIGE_SENHA = pASS_PMM_FL_EXIGE_SENHA) AND
        (pASS_PMM_FL_AUTORIZATEL is null OR PNM.ASS_PMM_FL_AUTORIZATEL = pASS_PMM_FL_AUTORIZATEL) AND
        (pASS_PMM_FL_AUTORIZAFAX is null OR PNM.ASS_PMM_FL_AUTORIZAFAX = pASS_PMM_FL_AUTORIZAFAX) AND
        (pASS_PMM_FL_AUTORIZAPES is null OR PNM.ASS_PMM_FL_AUTORIZAPES = pASS_PMM_FL_AUTORIZAPES) AND
        (pASS_PMM_FL_AUTORIZAWEB is null OR PNM.ASS_PMM_FL_AUTORIZAWEB = pASS_PMM_FL_AUTORIZAWEB) AND
        (pASS_PMM_FL_COBERTURA is null OR PNM.ASS_PMM_FL_COBERTURA = pASS_PMM_FL_COBERTURA) AND
        (pASS_PMM_FL_STATUS is null OR PNM.ASS_PMM_FL_STATUS = pASS_PMM_FL_STATUS) AND
        (pSEG_USU_ID_USUARIO is null OR PNM.SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND
        (pASS_PMM_DT_ULTIMA_ATUALIZACAO is null OR PNM.ASS_PMM_DT_ULTIMA_ATUALIZACAO = pASS_PMM_DT_ULTIMA_ATUALIZACAO);
    io_cursor := v_cursor;
  end PRC_ASS_PMM_S;