CREATE OR REPLACE PROCEDURE PRC_CAD_SET_SETOR_ALMOX_U(
     pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%type,
     pCAD_SET_UNIDADE_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_UNIDADE_ALMOX%type,
     pCAD_SET_LOCAL_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_LOCAL_ALMOX%type,
     pCAD_SET_SETOR_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_SETOR_ALMOX%type,
     pCAD_SET_SETOR_FARMACIA IN TB_CAD_SET_SETOR.CAD_SET_SETOR_FARMACIA%type DEFAULT NULL,
     pCAD_SET_CE_SETOR_PAI IN TB_CAD_SET_SETOR.CAD_SET_CE_SETOR_PAI%type DEFAULT NULL
     --pSEG_USU_ID_USUARIO  IN TB_CAD_SET_SETOR.SEG_USU_ID_USUARIO%type
  )
  is
-- Atualiza o centro de dispensac?o do setor
begin

    UPDATE TB_CAD_SET_SETOR
    SET
        CAD_SET_UNIDADE_ALMOX = pCAD_SET_UNIDADE_ALMOX,
        CAD_SET_LOCAL_ALMOX = pCAD_SET_LOCAL_ALMOX,
        CAD_SET_SETOR_ALMOX = pCAD_SET_SETOR_ALMOX,
        CAD_SET_SETOR_FARMACIA = pCAD_SET_SETOR_FARMACIA,
        CAD_SET_CE_SETOR_PAI = pCAD_SET_CE_SETOR_PAI
        --SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO
    WHERE
        CAD_SET_ID = pCAD_SET_ID;

end PRC_CAD_SET_SETOR_ALMOX_U;