create or replace procedure PRC_ASS_PFA_PROF_CFM_AA_L 
(
     pASS_PFA_ID_PROF_CFM_AA IN TB_ASS_PFA_PROF_CFM_AA.ASS_PFA_ID_PROF_CFM_AA%type DEFAULT NULL,
     pCAD_PRO_ID_PROFISSIONAL IN TB_ASS_PFA_PROF_CFM_AA.CAD_PRO_ID_PROFISSIONAL%type DEFAULT NULL,
     pCAD_CAA_ID_AREA_ATUACAO IN TB_ASS_PFA_PROF_CFM_AA.CAD_CAA_ID_AREA_ATUACAO%type DEFAULT NULL,
     pCAD_CFM_ID_CFM IN TB_ASS_PFA_PROF_CFM_AA.CAD_CFM_ID_CFM%type DEFAULT NULL,
     pASS_PFA_DT_ULTIMA_ATUALIZACAO IN TB_ASS_PFA_PROF_CFM_AA.ASS_PFA_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ASS_PFA_PROF_CFM_AA.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
/********************************************************************
*    Procedure: PRC_ASS_PFA_PROF_CFM_AA_L
* 
*    Data Criacao: 	16/04/2012   Por: André
*
*    Funcao: Lista associação de Esp. CFM com profissional e área de atuação
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
begin
  V_WHERE := NULL;
  IF pASS_PFA_ID_PROF_CFM_AA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_PFA_ID_PROF_CFM_AA = ' || pASS_PFA_ID_PROF_CFM_AA; END IF;
IF pCAD_PRO_ID_PROFISSIONAL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_PRO_ID_PROFISSIONAL = ' || pCAD_PRO_ID_PROFISSIONAL; END IF;
IF pCAD_CAA_ID_AREA_ATUACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CAA_ID_AREA_ATUACAO = ' || pCAD_CAA_ID_AREA_ATUACAO; END IF;
IF pCAD_CFM_ID_CFM IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CAD_CFM_ID_CFM = ' || pCAD_CFM_ID_CFM; END IF;
IF pASS_PFA_DT_ULTIMA_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ASS_PFA_DT_ULTIMA_ATUALIZACAO = ' || CHR(39) || pASS_PFA_DT_ULTIMA_ATUALIZACAO || CHR(39); END IF;
IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
 
   V_SELECT := '
SELECT	
       ASS_PFA_ID_PROF_CFM_AA,
       CAD_PRO_ID_PROFISSIONAL,
       CAD_CAA_ID_AREA_ATUACAO,
       CAD_CFM_ID_CFM,
       ASS_PFA_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO
FROM TB_ASS_PFA_PROF_CFM_AA
WHERE null is null  '    ;
       
OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_ASS_PFA_PROF_CFM_AA_L;