CREATE OR REPLACE PROCEDURE PRC_INT_REL_REINCIDENTE_UTI(
PCAD_UNI_ID_UNIDADE           IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL, 
PCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
PDT_INICIAL                   IN TB_ATD_IML_INT_MOV_LEITO.ATD_IML_DT_ENTRADA%TYPE DEFAULT NULL,
PDT_FINAL                     IN TB_ATD_IML_INT_MOV_LEITO.ATD_IML_DT_ENTRADA%TYPE DEFAULT NULL,
--PNM_USUARIO VARCHAR2 DEFAULT NULL,
IO_CURSOR                     OUT PKG_CURSOR.T_CURSOR--,
   -- TESTE OUT LONG
) IS
/*
SELECT ATENDIMENTO, NOME, SETOR FROM TB_REL_PAC_REINCIDENTE_UTI
WHERE DATA BETWEEN TO_DATE(:PDATA_INI, 'DD/MM/YYYY') AND TO_DATE (:PDATA_FIM, 'DD/MM/YYYY')
*/
  CURSOR INTERNACOES_UTI IS
    SELECT IML.ATD_ATE_ID,
           IML.TIS_TAC_CD_TIPO_ACOMODACAO,
           PES.CAD_PES_NM_PESSOA,
           COUNT(*)
      FROM TB_ATD_ATE_ATENDIMENTO   ATD
      JOIN TB_ATD_AIC_ATE_INT_COMPL AIC        ON AIC.ATD_ATE_ID = ATD.ATD_ATE_ID
      JOIN TB_ATD_IML_INT_MOV_LEITO IML        ON IML.ATD_ATE_ID = ATD.ATD_ATE_ID
      JOIN TB_CAD_QLE_QUARTO_LEITO  QLE        ON IML.CAD_CAD_QLE_ID = QLE.CAD_QLE_ID
      JOIN TB_CAD_SET_SETOR         SETOR      ON QLE.CAD_SET_ID = SETOR.CAD_SET_ID
      JOIN TB_CAD_PAC_PACIENTE      PAc        ON PAC.CAD_PAC_ID_PACIENTE = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
      JOIN TB_CAD_PES_PESSOA        PES        ON PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
     WHERE ATD.ATD_ATE_FL_STATUS    = 'A'
       AND ATD.ATD_ATE_TP_PACIENTE  = 'I'
       AND ATD.CAD_UNI_ID_UNIDADE   = PCAD_UNI_ID_UNIDADE
       AND ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO
       AND (AIC.ATD_AIC_TP_SITUACAO_PAC = 'I' OR EXISTS
            (SELECT COUNT(*)
               FROM TB_ATD_INA_INT_ALTA INA
              WHERE INA.ATD_ATE_ID = ATD.ATD_ATE_ID
                AND INA.ATD_INA_DT_ALTA_ADM > PDT_INICIAL))
       AND IML.ATD_IML_FL_STATUS = 'A'
       AND (IML.ATD_IML_DT_ENTRADA BETWEEN PDT_INICIAL AND PDT_FINAL)
       AND QLE.TIS_TAC_CD_TIPO_ACOMODACAO IN (3, 51, 52, 53)
     GROUP BY IML.ATD_ATE_ID,
              IML.TIS_TAC_CD_TIPO_ACOMODACAO,
              PES.CAD_PES_NM_PESSOA
     ORDER BY 2, 1, 3;
  V_ATD_IML_DT_ENTRADA_ANT DATE;
  V_ATD_IML_HR_ENTRADA_ANT NUMBER;
  V_ATD_IML_DT_SAIDA_ANT   DATE;
  V_ATD_IML_HR_SAIDA_ANT   NUMBER;
  V_EHREINCIDENTE          NUMBER;
  V_CURSOR                 PKG_CURSOR.T_CURSOR;
  V_WHERE                  VARCHAR2(10000);
  V_SELECT                 VARCHAR2(20000);
BEGIN
  V_WHERE := NULL;
  FOR I IN INTERNACOES_UTI LOOP
    V_ATD_IML_DT_ENTRADA_ANT := NULL;
    V_ATD_IML_HR_ENTRADA_ANT := NULL;
    V_ATD_IML_DT_SAIDA_ANT   := NULL;
    V_ATD_IML_HR_SAIDA_ANT   := NULL;
    V_EHREINCIDENTE          := 0;
    FOR J IN (SELECT IML.ATD_IML_ID,
                     IML.ATD_IML_DT_ENTRADA,
                     IML.ATD_IML_HR_ENTRADA,
                     IML.ATD_IML_DT_SAIDA,
                     IML.ATD_IML_HR_SAIDA,
                     IML.TIS_TAC_CD_TIPO_ACOMODACAO,
                     SETOR.CAD_SET_DS_SETOR
                FROM TB_ATD_IML_INT_MOV_LEITO IML
                JOIN TB_ATD_ATE_ATENDIMENTO   ATD                  ON IML.ATD_ATE_ID = ATD.ATD_ATE_ID
                JOIN TB_CAD_PAC_PACIENTE      PAC                  ON PAC.CAD_PAC_ID_PACIENTE = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
                JOIN TB_CAD_PES_PESSOA        PES                  ON PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
                JOIN TB_CAD_QLE_QUARTO_LEITO  QLE                  ON IML.CAD_CAD_QLE_ID = QLE.CAD_QLE_ID
                JOIN TB_CAD_SET_SETOR         SETOR                ON QLE.CAD_SET_ID = SETOR.CAD_SET_ID
               WHERE IML.ATD_ATE_ID = I.ATD_ATE_ID
                 AND IML.TIS_TAC_CD_TIPO_ACOMODACAO =              I.TIS_TAC_CD_TIPO_ACOMODACAO
                 AND IML.ATD_IML_FL_STATUS = 'A'
                 AND ((IML.ATD_IML_DT_ENTRADA < PDT_INICIAL)OR IML.ATD_IML_DT_ENTRADA BETWEEN PDT_INICIAL AND   PDT_FINAL)
               ORDER BY ATD_IML_DT_ENTRADA,
                        ATD_IML_HR_ENTRADA,
                        ATD_IML_DT_SAIDA,
                        ATD_IML_HR_SAIDA) LOOP
      IF (V_EHREINCIDENTE = 0) THEN
        --NAO EH REINCIDENTE
        IF ((J.ATD_IML_DT_ENTRADA != V_ATD_IML_DT_SAIDA_ANT OR
           J.ATD_IML_HR_ENTRADA != V_ATD_IML_HR_SAIDA_ANT) and j.atd_iml_dt_entrada between  PDT_INICIAL AND   PDT_FINAL)THEN
          V_EHREINCIDENTE := 1;
        ELSE
          V_ATD_IML_DT_ENTRADA_ANT := J.ATD_IML_DT_ENTRADA;
          V_ATD_IML_HR_ENTRADA_ANT := J.ATD_IML_HR_ENTRADA;
          V_ATD_IML_DT_SAIDA_ANT   := J.ATD_IML_DT_SAIDA;
          V_ATD_IML_HR_SAIDA_ANT   := J.ATD_IML_HR_SAIDA;
        END IF;
        IF V_EHREINCIDENTE > 0 THEN --EH REINCIDENTE
          IF V_WHERE IS NULL THEN
            V_WHERE := V_WHERE || TO_CHAR(J.ATD_IML_ID);
          ELSE
            V_WHERE := V_WHERE || ', ' || TO_CHAR(J.ATD_IML_ID);
          END IF;
        END IF;
      END IF;
    END LOOP;
  END LOOP;
  IF V_WHERE IS NULL THEN V_WHERE := '0'; end if;
  V_SELECT := 'SELECT IML.ATD_ATE_ID,
                      PES.CAD_PES_NM_PESSOA,
                      SETOR.CAD_SET_DS_SETOR,
                      PES.CAD_PES_DT_NASCIMENTO
                 FROM TB_ATD_IML_INT_MOV_LEITO IML
                 JOIN TB_ATD_ATE_ATENDIMENTO   ATD       ON IML.ATD_ATE_ID = ATD.ATD_ATE_ID
                 JOIN TB_CAD_PAC_PACIENTE      PAC       ON PAC.CAD_PAC_ID_PACIENTE = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
                 JOIN TB_CAD_PES_PESSOA        PES       ON PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
                 JOIN TB_CAD_QLE_QUARTO_LEITO  QLE       ON IML.CAD_CAD_QLE_ID = QLE.CAD_QLE_ID
                 JOIN TB_CAD_SET_SETOR         SETOR     ON QLE.CAD_SET_ID = SETOR.CAD_SET_ID
                WHERE IML.ATD_IML_ID IN (' || V_WHERE || ')
             ORDER BY SETOR.CAD_SET_DS_SETOR,PES.CAD_PES_NM_PESSOA';
  -- TESTE :=  V_SELECT ;
  OPEN V_CURSOR FOR V_SELECT;
  IO_CURSOR := V_CURSOR;
END PRC_INT_REL_REINCIDENTE_UTI;