CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_REC_CLASS_CONT"
(
    pCAD_UNI_ID_UNIDADE                   IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT                      IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE,
    pFAT_CCP_ANO_FAT                      IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO         IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID                           IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I                IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_A                IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_E                IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_U                IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB              IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PL              IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_FU              IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP              IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA              IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP              IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO                  IN TB_CAD_PAC_PACIENTE.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO                     IN TB_CAD_PAC_PACIENTE.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor
   -- , TESTE OUt LONG
)
IS
/* Marcus Relva - 04/02/2011 */
/*Eduardo - 28/08/2012 - retirar PAC e ATE */
v_cursor PKG_CURSOR.t_cursor;
V_WHERE  varchar2(10000);
V_SELECT  varchar2(30000);
BEGIN
    V_WHERE := NULL;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
    IF pCAD_SET_ID IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ccp.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO; END IF;
    IF pCAD_PLA_ID_PLANO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO; END IF;
    IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT; END IF;
    IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT; END IF; 
   V_SELECT := 
  ' SELECT
       CAC.CAD_CAC_CD_CLASSCONTABIL,
       CAC.CAD_CAC_DS_CLASSCONTABIL,
       SUM(CCI.FAT_CCI_VL_FATURADO) VALOR,
       SUM(CCI.FAT_CCI_QT_CONSUMO) QUANTIDADE
  FROM TB_FAT_CCI_CONTA_CONSU_ITEM CCI,
       TB_CAD_CAC_CLASSIF_CONTAB   CAC,
       TB_FAT_CCP_CONTA_CONS_PARC  CCP
WHERE CCI.CAD_CAC_ID_CLASSCONTABIL = CAC.CAD_CAC_ID_CLASSCONTABIL
   AND CCI.FAT_CCI_FL_STATUS        = '||CHR(39)||'A'||CHR(39)||'
   AND CCI.ATD_ATE_ID               = CCP.ATD_ATE_ID
   AND CCI.CAD_PAC_ID_PACIENTE      = CCP.CAD_PAC_ID_PACIENTE
   AND CCI.FAT_CCP_ID               = CCP.FAT_CCP_ID
   AND CCI.FAT_COC_ID               = CCP.FAT_COC_ID 
   
   AND CCP.FAT_NOF_ID IS NOT NULL
   AND CCI.FAT_CCI_MES_FECHAMENTO = CCP.FAT_CCP_MES_FAT
   AND CCI.FAT_CCI_ANO_FECHAMENTO = CCP.FAT_CCP_ANO_FAT
   AND CCP.FAT_CCP_FL_FATURADA = '||CHR(39)||'S'||CHR(39)||'   
   AND CCP.FAT_CCP_FL_STATUS = '||CHR(39)||'A'||CHR(39)||'
   AND CCI.CAD_TAP_TP_ATRIBUTO <> '||CHR(39)||'PAC'||CHR(39)||
       V_WHERE || '
   AND ('||CHR(39)|| PATD_ATE_TP_PACIENTE_I ||CHR(39)||' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = '||CHR(39)||'I'||CHR(39)||'
      OR '||CHR(39)|| PATD_ATE_TP_PACIENTE_E ||CHR(39)||' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = '||CHR(39)||'E'||CHR(39)||'
      OR '||CHR(39)|| PATD_ATE_TP_PACIENTE_A ||CHR(39)||' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = '||CHR(39)||'A'||CHR(39)||'
      OR '||CHR(39)|| PATD_ATE_TP_PACIENTE_U ||CHR(39)||' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = '||CHR(39)||'U'||CHR(39)||')
    AND (' ||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB  ||chr(39)|| ' IS not NULL and CCP.CAD_TPE_CD_CODIGO = ' ||chr(39)|| 'ACS' ||chr(39)|| '
     OR ' ||chr(39)||  pCAD_PLA_CD_TIPOPLANO_PA  ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = ' ||chr(39)|| 'PA' ||chr(39)|| '
     OR ' ||chr(39)||  pCAD_PLA_CD_TIPOPLANO_SP  ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = ' ||chr(39)|| 'SP' ||chr(39)|| '
     OR ' ||chr(39)||  pCAD_PLA_CD_TIPOPLANO_NP  ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = ' ||chr(39)|| 'NP' ||chr(39)|| '
     OR ' ||chr(39)||  pCAD_PLA_CD_TIPOPLANO_FU  ||chr(39)|| ' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = ' ||chr(39)|| 'FU' ||chr(39)|| ')
               
       GROUP BY CAC.CAD_CAC_DS_CLASSCONTABIL,
          CAC.CAD_CAC_CD_CLASSCONTABIL
          ORDER BY CAC.CAD_CAC_CD_CLASSCONTABIL';
          --TESTE :=  V_SELECT           ;
  OPEN V_CURSOR FOR
   V_SELECT ;
  IO_CURSOR := V_CURSOR;
--  DBMS_OUTPUT.PUT_LINE(V_SELECT);
END PRC_FAT_REL_REC_CLASS_CONT;
 