create or replace procedure PRC_REP_PGM_L
(
     pATD_ATE_ID IN TB_REP_PGM_PAGTO_MEDICO.ATD_ATE_ID%type DEFAULT NULL,
     pCAD_PRD_ID IN TB_REP_PGM_PAGTO_MEDICO.CAD_PRD_ID%type DEFAULT NULL,    
     pREP_DT_INICIO IN TB_REP_PGM_PAGTO_MEDICO.REP_PGM_DT_INICIO_REALIZACAO%type DEFAULT NULL,
     pREP_DT_FIM IN TB_REP_PGM_PAGTO_MEDICO.REP_PGM_DT_INICIO_REALIZACAO%type DEFAULT NULL,
     pCAD_PRO_ID_PROFISSIONAL IN TB_REP_PGM_PAGTO_MEDICO.CAD_PRO_ID_PROFISSIONAL%type DEFAULT NULL,
     pCAD_PAC_ID_PACIENTE IN TB_REP_PGM_PAGTO_MEDICO.CAD_PAC_ID_PACIENTE%type DEFAULT NULL,
     pCAD_CEC_ID_CCUSTO IN TB_REP_PGM_PAGTO_MEDICO.CAD_CEC_ID_CCUSTO%type DEFAULT NULL,
     pCAD_CAC_ID_CLASSCONTABIL IN TB_REP_PGM_PAGTO_MEDICO.CAD_CAC_ID_CLASSCONTABIL%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE %type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_REP_PGM_PAGTO_MEDICO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,    
     pCAD_UNI_ID_UNIDADE_PAGTO IN TB_REP_PGM_PAGTO_MEDICO.CAD_UNI_ID_UNIDADE_PAGTO%type DEFAULT NULL, 
     pREP_PGM_FL_STATUS IN TB_REP_PGM_PAGTO_MEDICO.REP_PGM_FL_STATUS%type DEFAULT NULL,     
     pREP_PGM_ID IN TB_REP_PGM_PAGTO_MEDICO.REP_PGM_ID%type DEFAULT NULL,
     pCAD_SET_ID_REALIZACAO IN TB_REP_PGM_PAGTO_MEDICO.CAD_SET_ID_REALIZACAO%type DEFAULT NULL,
     pCAD_SET_ID_MOVIMENTACAO IN TB_REP_PGM_PAGTO_MEDICO.CAD_SET_ID_MOVIMENTACAO%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO IN TB_REP_PGM_PAGTO_MEDICO.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pCAD_CLC_ID IN TB_REP_PGM_PAGTO_MEDICO.CAD_CLC_ID%type DEFAULT NULL,
     pTIS_TAT_CD_TPATENDIMENTO IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
     pREP_PGM_MES_PAGTO IN TB_REP_PGM_PAGTO_MEDICO.REP_PGM_MES_PAGTO%type DEFAULT NULL,
     pREP_PGM_ANO_PAGTO IN TB_REP_PGM_PAGTO_MEDICO.REP_PGM_ANO_PAGTO%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_REP_PGM_PAGTO_MEDICO.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_REP_PGM_PAGTO_MEDICO.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pREP_PGM_FL_PACOTE IN TB_REP_PGM_PAGTO_MEDICO.REP_PGM_FL_PACOTE%type DEFAULT NULL,
     pCAD_PLA_CD_TIPOPLANO_ACS VARCHAR2 DEFAULT NULL,
     pCAD_PLA_CD_TIPOPLANO_FU VARCHAR2 DEFAULT NULL,
     pCAD_PLA_CD_TIPOPLANO_PA VARCHAR2 DEFAULT NULL,
     pCAD_PLA_CD_TIPOPLANO_SP VARCHAR2 DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_REP_PGM_L
*
*    Data Criacao:   23/11/2011   Por: Pedro
*    Data Alteracao:  data da alteração  Por: Nome do Analista
*
*    Funcao: Descrição da funcionalidade da Stored Procedure
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(10000);
begin 
  V_WHERE := NULL;
  IF pATD_ATE_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.ATD_ATE_ID = ' || pATD_ATE_ID; END IF;
IF pCAD_PRD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_PRD_ID = ' || pCAD_PRD_ID; END IF;
IF pREP_DT_INICIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO >= ' || CHR(39) || pREP_DT_INICIO || CHR(39); END IF;
IF pREP_DT_FIM IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO <= ' || CHR(39) || pREP_DT_FIM || CHR(39); END IF;
IF pCAD_PRO_ID_PROFISSIONAL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_PRO_ID_PROFISSIONAL = ' || pCAD_PRO_ID_PROFISSIONAL; END IF;
IF pCAD_PAC_ID_PACIENTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_PAC_ID_PACIENTE = ' || pCAD_PAC_ID_PACIENTE; END IF;
IF pCAD_CEC_ID_CCUSTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_CEC_ID_CCUSTO = ' || pCAD_CEC_ID_CCUSTO; END IF;
IF pCAD_CAC_ID_CLASSCONTABIL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_CAC_ID_CLASSCONTABIL = ' || pCAD_CAC_ID_CLASSCONTABIL; END IF;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND UNI.CAD_UNI_ID_UNIDADE = ' || CHR(39) || pCAD_UNI_ID_UNIDADE || CHR(39); END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_UNI_ID_UNIDADE_PAGTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_UNI_ID_UNIDADE_PAGTO = ' || pCAD_UNI_ID_UNIDADE_PAGTO; END IF;
IF pREP_PGM_FL_STATUS IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.REP_PGM_FL_STATUS = ' || CHR(39) || pREP_PGM_FL_STATUS || CHR(39); END IF;
IF pREP_PGM_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.REP_PGM_ID = ' || pREP_PGM_ID; END IF;
IF pCAD_SET_ID_REALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_SET_ID_REALIZACAO = ' || pCAD_SET_ID_REALIZACAO; END IF;
IF pCAD_SET_ID_MOVIMENTACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_SET_ID_MOVIMENTACAO = ' || pCAD_SET_ID_MOVIMENTACAO; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO; END IF;
IF pCAD_CLC_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.CAD_CLC_ID = ' || pCAD_CLC_ID; END IF;
IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.TIS_TAT_CD_TPATENDIMENTO = ' || CHR(39) || pTIS_TAT_CD_TPATENDIMENTO || CHR(39); END IF;
IF pREP_PGM_MES_PAGTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.REP_PGM_MES_PAGTO = ' || pREP_PGM_MES_PAGTO; END IF;
IF pREP_PGM_ANO_PAGTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.REP_PGM_ANO_PAGTO = ' || pREP_PGM_ANO_PAGTO; END IF;
IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.AUX_EPP_CD_ESPECPROC = ' || CHR(39) || pAUX_EPP_CD_ESPECPROC || CHR(39); END IF;
IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.TIS_MED_CD_TABELAMEDICA = ' || CHR(39) || pTIS_MED_CD_TABELAMEDICA || CHR(39); END IF;
IF pREP_PGM_FL_PACOTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PGM.REP_PGM_FL_PACOTE = ' || CHR(39) || pREP_PGM_FL_PACOTE || CHR(39); END IF;
   V_SELECT := '

SELECT
       
       PGM.ATD_ATE_ID,
       PGM.FAT_CCP_ID,
       PGM.FAT_COC_ID,
       PGM.CAD_TAP_TP_ATRIBUTO,
       PGM.CAD_PRD_ID,
       PGM.CAD_TIH_TP_INDICE_HOSP,
       PGM.REP_PGM_QT_INDICE,
       PGM.REP_PGM_VL_INDICE,
       PGM.REP_PGM_VL_UNITARIO,
       PGM.REP_PGM_DT_INICIO_REALIZACAO,
       PGM.REP_PGM_HR_INICIO_REALIZACAO,
       PGM.REP_PGM_VL_FATURADO,
       PGM.REP_PGM_QT_CONSUMO,
       PGM.CAD_PRO_ID_PROFISSIONAL,
       PGM.REP_PGM_PC_GRAU_PART_PROF,
       PGM.REP_PGM_DT_ULTIMA_ATUALIZACAO,
       PGM.REP_PGM_VL_CALCULADO,
       PGM.CAD_PAC_ID_PACIENTE,
       PGM.REP_PGM_TP_CREDENCIA_PROF,
       PGM.REP_PGM_FL_PACOTE,
       PGM.CAD_CEC_ID_CCUSTO,
       PGM.CAD_CAC_ID_CLASSCONTABIL,
       PGM.REP_PGM_MES_FECHAMENTO,
       PGM.REP_PGM_ANO_FECHAMENTO,
       PGM.SEG_USU_ID_USUARIO_CRIACAO,
       PGM.REP_PGM_DT_CRIACAO,
       PGM.REP_PGM_MES_PAGTO,
       PGM.REP_PGM_ANO_PAGTO,
       PGM.REP_PGM_FL_PAGO,
       PGM.REP_PGM_DT_PAGAMENTO,
       PGM.CAD_UNI_ID_UNIDADE,
       PGM.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       PGM.CAD_UNI_ID_UNIDADE_PAGTO,
       PGM.REP_PGM_FL_STATUS,
       PGM.REP_PGM_CD_ORIGEM,
       PGM.REP_PGM_ID,
       PGM.CAD_SET_ID_REALIZACAO,
       PGM.CAD_SET_ID_MOVIMENTACAO,
       PGM.FAT_CCI_PC_ACOMODACAO_HM,
       PGM.REP_PGM_CD_JUSTIFICATIVA,
       PGM.SEG_USU_ID_USUARIO_ATUALIZ,
       PGM.CAD_CNV_ID_CONVENIO,
       PGM.CAD_CLC_ID,
       PGM.CAD_PLA_CD_TIPOPLANO,
       PGM.AUX_EPP_CD_ESPECPROC,
       PGM.TIS_MED_CD_TABELAMEDICA,
       PGM.REP_PGM_VL_PAGO,
       ATE.TIS_TAT_CD_TPATENDIMENTO,
       TAT.TIS_TAT_DS_TPATENDIMENTO,
       ATE.ATD_ATE_TP_PACIENTE,
       ATE.ATD_ATE_DT_ATENDIMENTO,
       ATE.ATD_ATE_HR_ATENDIMENTO,
       PAC.CAD_PAC_CD_CREDENCIAL,
       PAC.CAD_PAC_NR_PRONTUARIO,
       PES.CAD_PES_NM_PESSOA,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       CNV.CAD_CNV_NM_FANTASIA,
       --UNI.CAD_UNI_ID_UNIDADE,
       UNI.CAD_UNI_DS_UNIDADE,
       LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       SET_REAL.CAD_SET_DS_SETOR CAD_SET_DS_SETOR_REL,
       SET_MOV.CAD_SET_DS_SETOR CAD_SET_DS_SETOR_MOV,
       CLC.CAD_CLC_DS_RESUMIDA,
       CEC.CAD_CEC_CD_CCUSTO,
       CEC.CAD_CEC_DS_CCUSTO,
       CAC.CAD_CAC_CD_CLASSCONTABIL,
       CAC.CAD_CAC_DS_CLASSCONTABIL,
       MED.TIS_MED_DS_TABELAMEDICA,
       GPC.AUX_GPC_CD_GRUPOPROC,
       GPC.AUX_GPC_DS_DESCRICAO,
       EPP.AUX_EPP_CD_ESPECPROC,
       EPP.AUX_EPP_DS_DESCRICAO,
       PRD.CAD_PRD_CD_CODIGO,
       PRD.CAD_PRD_DS_DESCRICAO,
       PRO.CAD_PRO_NR_CONSELHO,
       PRO.CAD_PRO_SG_UF_CONSELHO,
       PRO.TIS_CPR_CD_CONSELHOPROF,
       PRO.CAD_PRO_NM_NOME,
       TIH.CAD_TIH_DS_INDICE_HOSP,
       CCP.FAT_CCP_DT_PARCELA,
       CCP.FAT_CCP_HR_PARCELA,
       CCP.FAT_CCP_VL_TOT_CONTA,
       CCP.FAT_CCP_DT_PARCELA_INI,
       CCP.FAT_CCP_HR_PARCELA_INI,
       USU_CRIA.SEG_USU_DS_NOME SEG_USU_DS_NOME_CRIACAO,
       USU_ATUA.SEG_USU_DS_NOME SEG_USU_DS_NOME_ATUALIZ,
       PGM.TIS_TAC_CD_TIPO_ACOMOD_AUT,
       TAC.TIS_TAC_DS_TIPO_ACOMODACAO,
       PGM.CAD_REP_VL_PAGTO_EXTRA


FROM TB_REP_PGM_PAGTO_MEDICO        PGM
JOIN TB_ATD_ATE_ATENDIMENTO         ATE      ON      ATE.ATD_ATE_ID                   =  PGM.ATD_ATE_ID
JOIN TB_TIS_TAT_TP_ATENDIMENTO      TAT      ON      TAT.TIS_TAT_CD_TPATENDIMENTO     =  ATE.TIS_TAT_CD_TPATENDIMENTO
JOIN TB_CAD_PAC_PACIENTE            PAC      ON      PAC.CAD_PAC_ID_PACIENTE          =  PGM.CAD_PAC_ID_PACIENTE
JOIN TB_CAD_PLA_PLANO               PLA      ON      PLA.CAD_PLA_ID_PLANO             =  PAC.CAD_PLA_ID_PLANO
JOIN TB_CAD_PES_PESSOA              PES      ON      PES.CAD_PES_ID_PESSOA            =  PAC.CAD_PES_ID_PESSOA
JOIN TB_CAD_CNV_CONVENIO            CNV      ON      CNV.CAD_CNV_ID_CONVENIO          =  PAC.CAD_CNV_ID_CONVENIO
JOIN TB_CAD_UNI_UNIDADE             UNI      ON      UNI.CAD_UNI_ID_UNIDADE           =  PGM.CAD_UNI_ID_UNIDADE
JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO   LAT      ON      LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO =  PGM.CAD_LAT_ID_LOCAL_ATENDIMENTO
JOIN TB_CAD_CLC_CLINICA_CREDENCIADA CLC      ON      CLC.CAD_CLC_ID                   =  PGM.CAD_CLC_ID
LEFT JOIN TB_CAD_SET_SETOR          SET_REAL ON      SET_REAL.CAD_SET_ID              =  PGM.CAD_SET_ID_REALIZACAO
LEFT JOIN TB_CAD_SET_SETOR          SET_MOV  ON      SET_MOV.CAD_SET_ID               =  PGM.CAD_SET_ID_MOVIMENTACAO
LEFT JOIN TB_CAD_CEC_CENTRO_CUSTO   CEC      ON      CEC.CAD_CEC_ID_CCUSTO            =  PGM.CAD_CEC_ID_CCUSTO
LEFT JOIN TB_CAD_CAC_CLASSIF_CONTAB CAC      ON      CAC.CAD_CAC_ID_CLASSCONTABIL     =  PGM.CAD_CAC_ID_CLASSCONTABIL
JOIN TB_CAD_PRD_PRODUTO             PRD      ON      PRD.CAD_PRD_ID                   =  PGM.CAD_PRD_ID
JOIN TB_CAD_PRO_PROFISSIONAL        PRO      ON      PRO.CAD_PRO_ID_PROFISSIONAL      =  PGM.CAD_PRO_ID_PROFISSIONAL
LEFT JOIN TB_CAD_TIH_TP_INDICE_HOSP TIH      ON      TIH.CAD_TIH_TP_INDICE_HOSP       =  PGM.CAD_TIH_TP_INDICE_HOSP
JOIN TB_SEG_USU_USUARIO             USU_CRIA ON      USU_CRIA.SEG_USU_ID_USUARIO      =  PGM.SEG_USU_ID_USUARIO_CRIACAO
LEFT JOIN TB_SEG_USU_USUARIO        USU_ATUA ON      USU_ATUA.SEG_USU_ID_USUARIO      =  PGM.SEG_USU_ID_USUARIO_ATUALIZ
JOIN TB_TIS_MED_TABELAMEDICA        MED      ON      MED.TIS_MED_CD_TABELAMEDICA      =  PRD.TIS_MED_CD_TABELAMEDICA
JOIN TB_AUX_EPP_ESPECPROC           EPP      ON      EPP.AUX_EPP_CD_ESPECPROC         =  PRD.AUX_EPP_CD_ESPECPROC
                                             AND     EPP.TIS_MED_CD_TABELAMEDICA      =  PRD.TIS_MED_CD_TABELAMEDICA
JOIN TB_AUX_GPC_GRUPOPROC           GPC      ON      GPC.AUX_GPC_CD_GRUPOPROC         =  PRD.AUX_GPC_CD_GRUPOPROC
                                             AND     GPC.AUX_EPP_CD_ESPECPROC         =  PRD.AUX_EPP_CD_ESPECPROC
                                             AND     GPC.TIS_MED_CD_TABELAMEDICA      =  PRD.TIS_MED_CD_TABELAMEDICA
JOIN TB_FAT_CCP_CONTA_CONS_PARC     CCP      ON      CCP.FAT_CCP_ID                   =  PGM.FAT_CCP_ID
                                             AND     CCP.ATD_ATE_ID                   =  PGM.ATD_ATE_ID
                                             AND     CCP.CAD_PAC_ID_PACIENTE          =  PGM.CAD_PAC_ID_PACIENTE
                                             AND     CCP.FAT_COC_ID                   =  PGM.FAT_COC_ID
LEFT JOIN TB_TIS_TAC_TIPO_ACOMODACAO TAC     ON      PGM.TIS_TAC_CD_TIPO_ACOMOD_AUT   =  TAC.TIS_TAC_CD_TIPO_ACOMODACAO

WHERE PGM.REP_PGM_FL_STATUS in ('||CHR(39)||'A'||CHR(39)||','||CHR(39)||'E'||CHR(39)||')  
AND (' ||chr(39)|| pCAD_PLA_CD_TIPOPLANO_ACS  ||chr(39)|| ' IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO in (' ||chr(39)|| 'GB' ||chr(39)|| ','
 ||chr(39)|| 'PL' ||chr(39)|| ')
 OR ' ||chr(39)||  pCAD_PLA_CD_TIPOPLANO_PA  ||chr(39)|| ' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ' ||chr(39)|| 'PA' ||chr(39)|| '
 OR ' ||chr(39)||  pCAD_PLA_CD_TIPOPLANO_SP  ||chr(39)|| ' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ' ||chr(39)|| 'SP' ||chr(39)|| '
 OR ' ||chr(39)||  pCAD_PLA_CD_TIPOPLANO_FU  ||chr(39)|| ' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = ' ||chr(39)|| 'FU' ||chr(39)|| ')
             
'    ;

OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_REP_PGM_L;
