CREATE OR REPLACE PROCEDURE "PRC_ASS_CVP_CNV_VLR_PROD_REGRA"
(
     pCAD_CNV_ID_CONVENIO IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_CNV_ID_CONVENIO%type,
     pCAD_TAP_TP_ATRIBUTO IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_TAP_TP_ATRIBUTO%type,
     pCAD_UNI_ID_UNIDADE IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_PLA_ID_PLANO IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_PLA_ID_PLANO%type DEFAULT NULL,
     pCAD_SPL_ID IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_SPL_ID%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ASS_CVP_CONV_VLR_PRODUTO.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_ASS_CVP_CONV_VLR_PRODUTO.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pAUX_GPC_CD_GRUPOPROC IN TB_ASS_CVP_CONV_VLR_PRODUTO.AUX_GPC_CD_GRUPOPROC%type DEFAULT NULL,
     pCAD_PRD_ID IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_PRD_ID%type DEFAULT NULL,
     pASS_CVP_DT_INICIO_VIGENCIA IN TB_ASS_CVP_CONV_VLR_PRODUTO.ASS_CVP_DT_INICIO_VIGENCIA%type DEFAULT NULL,
     pASS_CVP_DT_FIM_VIGENCIA IN TB_ASS_CVP_CONV_VLR_PRODUTO.ASS_CVP_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pCAD_TIH_TP_INDICE_HOSP IN TB_ASS_CVP_CONV_VLR_PRODUTO.Cad_Tih_Tp_Indice_Hosp%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_ASS_CVP_CNV_VLR_PROD_REGRA
*
*      Data Criacao: 20/09/2010  Por: André S. Monaco
*    Data Alteracao: 26/10/2010  Por: André S. Monaco
*         Alteracao: Adição do campo CAD_PRD_ID_TAXA_ADM
*    Data Alteracao: 06/12/2010  Por: André S. Monaco
*         Alteracao: Adição do campo ASS_CVP_TP_PORTE_SALA
*
*    Funcao: Pesquisa pela regra valor de procedimento do convênio
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
begin
OPEN v_cursor FOR
SELECT
       ASS_CVP_ID,
       CAD_CNV_ID_CONVENIO,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_TAP_TP_ATRIBUTO,
       CAD_PRD_ID,
       CAD_TIH_TP_INDICE_HOSP,
       ASS_CVP_QT_INDICE_HOSP,
       ASS_CVP_VL_INDICE_HOSP,
       ASS_CVP_TP_PORTE,
       ASS_CVP_VL_PRODUTO,
       ASS_CVP_QT_MAXIMA_PERM,
       ASS_CVP_QT_MINIMA_PERM,
       ASS_CVP_PC_ACRESCIMO,
       ASS_CVP_PC_DESCONTO,
       ASS_CVP_VL_ACRESCIMO,
       ASS_CVP_VL_DESCONTO,
       ASS_CVP_PC_TAXAADM,
       ASS_CVP_PC_DOPPLER,
       ASS_CVP_DT_INICIO_VIGENCIA,
       ASS_CVP_DT_FIM_VIGENCIA,
       TIS_CDE_CD_CODIGO_DESPESA,
       ASS_CPE_ID,
       ASS_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       ASS_CVP_FL_PC_ACRESCIMOHR,
       ASS_CVP_FL_ISEN_COBRA,
       ASS_CVP_FL_COBERT_ANEST,
       ASS_CVP_TP_UNID_CONSUMO,
       ASS_CVP_PC_ACOMOD_HM,
       CAD_PLA_ID_PLANO,
       CAD_SPL_ID,
       CAD_UNI_ID_UNIDADE,
       TIS_MED_CD_TABELAMEDICA,
       AUX_EPP_CD_ESPECPROC,
       AUX_GPC_CD_GRUPOPROC,
       ASS_CVP_FL_STATUS,
       CAD_PRD_ID_TAXA_ADM,
       ASS_CVP_TP_PORTE_SALA
FROM TB_ASS_CVP_CONV_VLR_PRODUTO
WHERE
        (CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND
        (CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO) AND
        ((pCAD_UNI_ID_UNIDADE IS NULL AND CAD_UNI_ID_UNIDADE IS NULL) OR
         (pCAD_UNI_ID_UNIDADE IS NOT NULL AND CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)) AND
        ((pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL AND CAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL) OR
         (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL AND CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)) AND
        ((pCAD_PLA_ID_PLANO IS NULL AND CAD_PLA_ID_PLANO IS NULL) OR
         (pCAD_PLA_ID_PLANO IS NOT NULL AND CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)) AND
        ((pCAD_SPL_ID IS NULL AND CAD_SPL_ID IS NULL) OR
         (pCAD_SPL_ID IS NOT NULL AND CAD_SPL_ID = pCAD_SPL_ID)) AND
        ((pTIS_MED_CD_TABELAMEDICA IS NULL AND TIS_MED_CD_TABELAMEDICA IS NULL) OR
         (pTIS_MED_CD_TABELAMEDICA IS NOT NULL AND TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA)) AND
        ((pAUX_EPP_CD_ESPECPROC IS NULL AND AUX_EPP_CD_ESPECPROC IS NULL) OR
         (pAUX_EPP_CD_ESPECPROC IS NOT NULL AND AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC)) AND
        ((pAUX_GPC_CD_GRUPOPROC IS NULL AND AUX_GPC_CD_GRUPOPROC IS NULL) OR
         (pAUX_GPC_CD_GRUPOPROC IS NOT NULL AND AUX_GPC_CD_GRUPOPROC = pAUX_GPC_CD_GRUPOPROC)) AND
        ((pCAD_PRD_ID IS NULL AND CAD_PRD_ID IS NULL) OR
         (pCAD_PRD_ID IS NOT NULL AND CAD_PRD_ID = pCAD_PRD_ID)) AND
         ASS_CVP_FL_STATUS = 'A'
				 AND (CAD_TIH_TP_INDICE_HOSP = pCAD_TIH_TP_INDICE_HOSP OR pCAD_TIH_TP_INDICE_HOSP IS NULL)
        /*(ASS_CVP_DT_INICIO_VIGENCIA >= pASS_CVP_DT_INICIO_VIGENCIA AND
         ASS_CVP_DT_FIM_VIGENCIA <= pASS_CVP_DT_FIM_VIGENCIA)*/
         ORDER BY ASS_CVP_DT_INICIO_VIGENCIA;
io_cursor := v_cursor;
end;
 