CREATE OR REPLACE PROCEDURE PRC_BNF_VALIDA_PERMITE_PROCED
(
       pCODCON           IN BNF_CARENCIA_BENEFICIARIO.CODCON%TYPE,
       pCODATOMED        IN TB_AUT_PROCED_CARENCIA.CODATOMED%TYPE,
       io_cursor         OUT PKG_CURSOR.t_cursor
)

 IS
  v_cursor          PKG_CURSOR.t_cursor;
  vCODTIPEMP  EMPRESA.CODTIPEMP%TYPE;
BEGIN

   SELECT CODTIPEMP INTO vCODTIPEMP
   FROM EMPRESA
   WHERE CODCON = pCODCON;

  OPEN v_cursor FOR
    SELECT COUNT(*) AS RETORNO
    FROM TB_AUT_EXC_PROCED
    WHERE CODTIPEMP = vCODTIPEMP
    AND CODATOMED = pCODATOMED;

  io_cursor := v_cursor;

END PRC_BNF_VALIDA_PERMITE_PROCED;
 