create or replace procedure PRC_ASS_CTU_L
(
     pASS_CTU_ID IN TB_ASS_CTU_CNV_TAB_UTILIZA.ASS_CTU_ID%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO IN TB_ASS_CTU_CNV_TAB_UTILIZA.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ASS_CTU_CNV_TAB_UTILIZA.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pASS_CTU_DT_INICIO_VIGENCIA IN TB_ASS_CTU_CNV_TAB_UTILIZA.ASS_CTU_DT_INICIO_VIGENCIA%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ASS_CTU_CNV_TAB_UTILIZA.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pASS_CTU_DT_FIM_VIGENCIA IN TB_ASS_CTU_CNV_TAB_UTILIZA.ASS_CTU_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pASS_CTU_DT_ULTIMA_ATUALIZACAO IN TB_ASS_CTU_CNV_TAB_UTILIZA.ASS_CTU_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pCAD_TAP_TP_ATRIBUTO IN TB_ASS_CTU_CNV_TAB_UTILIZA.CAD_TAP_TP_ATRIBUTO%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA_COBRA IN TB_ASS_CTU_CNV_TAB_UTILIZA.TIS_MED_CD_TABELAMEDICA_COBRA%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_ASS_CTU_L
*
*    Data Criacao: 19/2/2010     Por: Pedro
*    Data Alteracao: 24/08/2010  Por: André S. Monaco
*         Alteracao: Adição do campo TIS_MED_CD_TABELAMEDICA_COBRA
*
*    Funcao: Select de registros de Convenio X Tabela Utilizada
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
begin
OPEN v_cursor FOR
SELECT
       CTU.ASS_CTU_ID,
       CTU.CAD_CNV_ID_CONVENIO,
       CTU.TIS_MED_CD_TABELAMEDICA,
       CTU.ASS_CTU_DT_INICIO_VIGENCIA,
       CTU.SEG_USU_ID_USUARIO,
       CTU.ASS_CTU_DT_FIM_VIGENCIA,
       CTU.ASS_CTU_DT_ULTIMA_ATUALIZACAO,
       CTU.CAD_TAP_TP_ATRIBUTO,
       CTU.TIS_MED_CD_TABELAMEDICA_COBRA,
       CNV.CAD_CNV_CD_HAC_PRESTADOR || ' - ' || PES.CAD_PES_NM_PESSOA CAD_CNV_CD_HAC_PRESTADOR,
       TAP.CAD_TAP_DS_ATRIBUTO,
       MED.TIS_MED_DS_TABELAMEDICA,
       CTU.TIS_MED_CD_TABELAMEDICA || ' - ' || MED.TIS_MED_DS_TABELAMEDICA COD_DESC_TABELA,       
       MED_COB.TIS_MED_DS_TABELAMEDICA,
       CTU.TIS_MED_CD_TABELAMEDICA_COBRA || ' - ' || MED_COB.TIS_MED_DS_TABELAMEDICA COD_DESC_TABELA_COB
FROM      TB_ASS_CTU_CNV_TAB_UTILIZA CTU
JOIN      TB_CAD_CNV_CONVENIO        CNV
ON        CNV.CAD_CNV_ID_CONVENIO  = CTU.CAD_CNV_ID_CONVENIO
JOIN      TB_TIS_MED_TABELAMEDICA    MED
ON        MED.TIS_MED_CD_TABELAMEDICA = CTU.TIS_MED_CD_TABELAMEDICA
LEFT JOIN      TB_TIS_MED_TABELAMEDICA    MED_COB
ON        MED_COB.TIS_MED_CD_TABELAMEDICA = CTU.TIS_MED_CD_TABELAMEDICA_COBRA
LEFT JOIN TB_CAD_TAP_TP_ATRIB_PRODUTO TAP
ON        TAP.CAD_TAP_TP_ATRIBUTO = CTU.CAD_TAP_TP_ATRIBUTO
JOIN      TB_CAD_PES_PESSOA PES
ON        PES.CAD_PES_ID_PESSOA = CNV.CAD_PES_ID_PESSOA
WHERE
        (pASS_CTU_ID is null OR CTU.ASS_CTU_ID = pASS_CTU_ID) AND
        (pCAD_CNV_ID_CONVENIO is null OR CTU.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND
        (pTIS_MED_CD_TABELAMEDICA is null OR CTU.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA) AND
        (pTIS_MED_CD_TABELAMEDICA_COBRA is null OR CTU.TIS_MED_CD_TABELAMEDICA_COBRA = pTIS_MED_CD_TABELAMEDICA_COBRA) AND
        (pCAD_TAP_TP_ATRIBUTO is null OR CTU.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO);
io_cursor := v_cursor;
end PRC_ASS_CTU_L;
