CREATE OR REPLACE PROCEDURE PRC_FAT_REL_CONS_CENTRO_CUSTO
(
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_CEC_ID_CCUSTO IN TB_CAD_CEC_CENTRO_CUSTO.CAD_CEC_ID_CCUSTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,       
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_MAT IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_MED IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_TAX IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_DIA IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_HM IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_GAS IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,    
    io_cursor OUT PKG_CURSOR.t_cursor
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_CONS_CENTRO_CUSTO
*
*    Data Alteracao: 20/07/2010  Por: Caio
*    Alteração:
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;

BEGIN
  
  OPEN v_cursor FOR
  SELECT  UNI.CAD_UNI_DS_UNIDADE,
          CEC.CAD_CEC_CD_CCUSTO,
          CEC.CAD_CEC_DS_CCUSTO,
          PRD.CAD_PRD_CD_CODIGO,
          PRD.CAD_PRD_DS_DESCRICAO,
          PRD.CAD_TAP_TP_ATRIBUTO,
          UMC.CAD_UMC_DS_MEDIDA_CONSUMO,
          CCI.FAT_CCI_VL_UNITARIO,
          CCI.FAT_CCI_FL_FRACIONADO,
          SUM(CCI.FAT_CCI_QT_CONSUMO),
          SUM(CCI.FAT_CCI_VL_FATURADO)          
  FROM    TB_FAT_CCI_CONTA_CONSU_ITEM CCI
  JOIN    TB_CAD_PAC_PACIENTE PAC
  ON      PAC.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
  JOIN    TB_ASS_USC_UNI_SET_CCUS_CLA USC
  ON      CCI.ASS_USC_ID = USC.ASS_USC_ID
  JOIN    TB_CAD_CEC_CENTRO_CUSTO CEC
  ON      CEC.CAD_CEC_ID_CCUSTO = USC.CAD_CEC_ID_CCUSTO
  JOIN    TB_ATD_ATE_ATENDIMENTO ATE
  ON      ATE.ATD_ATE_ID = CCI.ATD_ATE_ID
  JOIN    TB_CAD_UNI_UNIDADE UNI
  ON      UNI.CAD_UNI_ID_UNIDADE = ATE.CAD_UNI_ID_UNIDADE
  JOIN    TB_CAD_PRD_PRODUTO PRD
  ON      PRD.CAD_PRD_ID = CCI.CAD_PRD_ID       
  JOIN    TB_CAD_UMC_UNI_MED_CONSUMO UMC
  ON      UMC.CAD_UMC_CD_MEDIDA_CONSUMO = CCI.CAD_UMC_CD_MEDIDA_CONSUMO
  WHERE   (pCAD_TAP_TP_ATRIBUTO_MAT IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = 'MAT'
          OR pCAD_TAP_TP_ATRIBUTO_MED IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = 'MED'
          OR pCAD_TAP_TP_ATRIBUTO_TAX IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = 'TAX'
          OR pCAD_TAP_TP_ATRIBUTO_DIA IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = 'DIA'
          OR pCAD_TAP_TP_ATRIBUTO_HM IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = 'HM'
          OR pCAD_TAP_TP_ATRIBUTO_GAS IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = 'GAS')
  AND     (pCAD_UNI_ID_UNIDADE IS NULL OR ATE.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
  AND     (pCAD_CEC_ID_CCUSTO IS NULL OR CEC.CAD_CEC_ID_CCUSTO = pCAD_CEC_ID_CCUSTO)        
  AND     (pATD_ATE_DT_ATENDIMENTO_INI IS NULL OR ATE.ATD_ATE_DT_ATENDIMENTO >= pATD_ATE_DT_ATENDIMENTO_INI)
  AND     (pATD_ATE_DT_ATENDIMENTO_FIM IS NULL OR ATE.ATD_ATE_DT_ATENDIMENTO <= pATD_ATE_DT_ATENDIMENTO_FIM)      
  AND     (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
  GROUP   BY UNI.CAD_UNI_DS_UNIDADE,
          CEC.CAD_CEC_CD_CCUSTO,
          CEC.CAD_CEC_DS_CCUSTO,
          PRD.CAD_PRD_CD_CODIGO,
          PRD.CAD_PRD_DS_DESCRICAO,
          PRD.CAD_TAP_TP_ATRIBUTO,
          UMC.CAD_UMC_DS_MEDIDA_CONSUMO,
          CCI.FAT_CCI_VL_UNITARIO,
          CCI.FAT_CCI_FL_FRACIONADO
  ORDER   BY  UNI.CAD_UNI_DS_UNIDADE,
          CEC.CAD_CEC_CD_CCUSTO,
          CEC.CAD_CEC_DS_CCUSTO,
          PRD.CAD_PRD_DS_DESCRICAO;
  io_cursor := v_cursor;
  
END PRC_FAT_REL_CONS_CENTRO_CUSTO;
/
