CREATE OR REPLACE PROCEDURE PRC_CAD_MTMD_INVENT_FECHA_L
(
     pCAD_MTMD_FILIAL_ID IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
     pCAD_SET_ID IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_SET_ID%type DEFAULT NULL,
     pCAD_MTMD_DT_INVENTARIO IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_DT_INVENTARIO%type DEFAULT NULL,
     pCAD_MTMD_ANDAMENTO IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_ANDAMENTO%type DEFAULT NULL,
     pFL_MEDICAMENTO IN TB_CAD_MTMD_INVENTARIO_FECHA.FL_MEDICAMENTO%type DEFAULT NULL,
     pCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_GRUPO_ID%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_CAD_MTMD_INVENT_FECHA_L
*
*    Data Criacao: 10/8/11   Por: Andre
*    Data Alterac?o:  01/12/15  Por: Andre
*         Alterac?o:  Nova opcao de TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_ANDAMENTO = 2
*                   (andamento terceirizado)
*
*    Funcao: Lista fechamento de inventario do setor
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
begin
V_WHERE := NULL;
IF pCAD_MTMD_FILIAL_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND FECHA.CAD_MTMD_FILIAL_ID = ' || pCAD_MTMD_FILIAL_ID; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND FECHA.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_MTMD_DT_INVENTARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND FECHA.CAD_MTMD_DT_INVENTARIO = ' || CHR(39) || pCAD_MTMD_DT_INVENTARIO || CHR(39); END IF;
IF (pCAD_MTMD_ANDAMENTO IS NOT NULL) THEN
  IF (pCAD_MTMD_ANDAMENTO = 0) THEN
    V_WHERE:= V_WHERE || ' AND FECHA.CAD_MTMD_ANDAMENTO = ' || CHR(39) || pCAD_MTMD_ANDAMENTO || CHR(39);
    V_WHERE:= V_WHERE || ' AND FECHA.CAD_MTMD_DT_INVENTARIO >= SYSDATE-90 ';
  ELSE
    V_WHERE:= V_WHERE || ' AND FECHA.CAD_MTMD_ANDAMENTO IN (1,2) ';
  END IF;
END IF;
IF pFL_MEDICAMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND FECHA.FL_MEDICAMENTO = ' || pFL_MEDICAMENTO; END IF;
IF pCAD_MTMD_GRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND FECHA.CAD_MTMD_GRUPO_ID = ' || pCAD_MTMD_GRUPO_ID; END IF;
V_WHERE:= V_WHERE || ' ORDER BY FECHA.CAD_MTMD_DT_INVENTARIO DESC, FECHA.CAD_MTMD_FILIAL_ID, UNI.CAD_UNI_DS_UNIDADE, SETOR.CAD_SET_DS_SETOR ';
V_SELECT := '
SELECT
       FECHA.CAD_MTMD_FILIAL_ID,
       FECHA.CAD_SET_ID,
       FECHA.CAD_MTMD_DT_INVENTARIO,
       FECHA.CAD_MTMD_FECHAMENTO,
       FECHA.CAD_MTMD_ANDAMENTO,
       FECHA.CAD_MTMD_DT_ATUALIZACAO,
       FECHA.SEG_USU_ID_USUARIO,
       UNI.CAD_UNI_ID_UNIDADE,
       UNI.CAD_UNI_DS_UNIDADE,
       LOC.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       LOC.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       SETOR.CAD_SET_DS_SETOR,
       DECODE(FECHA.CAD_MTMD_FILIAL_ID,4,''CE'',2,''ACS'',5,''CONS'',''HAC'') ESTOQUE,
       DECODE(FECHA.CAD_MTMD_FECHAMENTO,0,''-'',FECHA.CAD_MTMD_FECHAMENTO) FECHADO,
       FECHA.FL_MEDICAMENTO,
       FECHA.CAD_MTMD_GRUPO_ID,
       DECODE(FECHA.CAD_MTMD_GRUPO_ID, 0, NULL, GRP.CAD_MTMD_GRUPO_DESCRICAO) CAD_MTMD_GRUPO_DESCRICAO,
       DECODE(FECHA.FL_MEDICAMENTO, 1, ''MED'', ''MAT'') TIPO_ITEM,
       FECHA.CAD_MTMD_DT_INICIO_INV,
       FECHA.MTMD_DT_IMPORT
FROM TB_CAD_MTMD_INVENTARIO_FECHA FECHA,
     TB_CAD_UNI_UNIDADE UNI,
     TB_CAD_SET_SETOR SETOR,
     TB_CAD_LAT_LOCAL_ATENDIMENTO LOC,
     TB_CAD_MTMD_GRUPO GRP
WHERE SETOR.CAD_SET_ID = FECHA.CAD_SET_ID AND
      UNI.CAD_UNI_ID_UNIDADE = SETOR.CAD_UNI_ID_UNIDADE AND
      LOC.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO AND
      GRP.CAD_MTMD_GRUPO_ID (+)= FECHA.CAD_MTMD_GRUPO_ID ';
OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
end PRC_CAD_MTMD_INVENT_FECHA_L;