 create or replace procedure PRC_AUX_EPP_PRD_L
  (
     pAUX_EPP_CD_ESPECPROC IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pAUX_EPP_DS_DESCRICAO IN TB_AUX_EPP_ESPECPROC.AUX_EPP_DS_DESCRICAO%type DEFAULT NULL,
     pAUX_EPP_FL_ATENDSADT IN TB_AUX_EPP_ESPECPROC.AUX_EPP_FL_ATENDSADT%type DEFAULT NULL,
   --  pCAD_MTMD_GRUPO_ID IN TB_AUX_EPP_ESPECPROC.CAD_MTMD_GRUPO_ID%type DEFAULT NULL  ,
   --  pAUX_EPP_FL_STATUS IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE DEFAULT NULL,
     pCAD_TAP_TP_ATRIBUTO IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_AUX_EPP_PRD_L
  *
  *    Data Criacao:  01/03/2010   Por: PEDRO
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Lista Especialidades de determinada tabela e/ou tipo atributo
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT  DISTINCT
       EPP.AUX_EPP_CD_ESPECPROC,
       EPP.AUX_EPP_DS_DESCRICAO,
       EPP.AUX_EPP_FL_ATENDSADT
    FROM TB_AUX_EPP_ESPECPROC EPP
    JOIN TB_CAD_PRD_PRODUTO PRD
    ON   PRD.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC
    WHERE
        (pAUX_EPP_CD_ESPECPROC is null OR EPP.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC) AND
        (pAUX_EPP_DS_DESCRICAO is null OR EPP.AUX_EPP_DS_DESCRICAO = pAUX_EPP_DS_DESCRICAO) AND
        (pAUX_EPP_FL_ATENDSADT is null OR EPP.AUX_EPP_FL_ATENDSADT = pAUX_EPP_FL_ATENDSADT) AND
       (pCAD_TAP_TP_ATRIBUTO IS NULL OR PRD.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO) AND
        (pTIS_MED_CD_TABELAMEDICA IS NULL OR PRD.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA)
        ;
    io_cursor := v_cursor;
  end PRC_AUX_EPP_PRD_L ;
/
