CREATE OR REPLACE PROCEDURE PRC_AGS_AGE_QTD_AGENDAMENTO_SP
(
   pAGS_AGE_DT_ATENDIMENTO IN TB_AGS_AGE_AGENDA_SADT.AGS_AGE_DT_ATENDIMENTO%TYPE,
   pAGS_ESM_ID IN TB_AGS_AGE_AGENDA_SADT.AGS_ESM_ID%TYPE,
   pQUANTIDADE OUT NUMERIC
)

IS 

BEGIN 
 
   SELECT COUNT(CNV.CAD_CNV_ID_CONVENIO) 
   INTO pQUANTIDADE
   FROM TB_AGS_AGE_AGENDA_SADT AGE   
   INNER JOIN TB_CAD_PAC_PACIENTE PAC
     ON PAC.CAD_PAC_ID_PACIENTE = AGE.CAD_PAC_ID_PACIENTE
    AND AGE.AGS_ESM_ID = pAGS_ESM_ID
    AND AGE.AGS_AGE_DT_ATENDIMENTO = pAGS_AGE_DT_ATENDIMENTO
   INNER JOIN TB_CAD_CNV_CONVENIO CNV
     ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
    AND CNV.CAD_CNV_CD_HAC_PRESTADOR != 'SD01' AND CNV.CAD_CNV_CD_HAC_PRESTADOR != 'GG05';
    
END PRC_AGS_AGE_QTD_AGENDAMENTO_SP; 