CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_TP_CONSUMO_MEDICO"
(
     pFAT_CCP_MES_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_COMPET%type DEFAULT NULL,
     pFAT_CCP_ANO_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_COMPET%type DEFAULT NULL,
     pFAT_COC_ID IN TB_FAT_COC_CONTA_CONSUMO.FAT_COC_ID%TYPE DEFAULT NULL,
   pFAT_CCP_ID IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ID%TYPE DEFAULT NULL,
   pATD_ATE_ID IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_ID%TYPE DEFAULT NULL,
   pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
   pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
   pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
   pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
   --pATD_ATE_DT_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
   PATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_INA_INT_ALTA.ATD_INA_DT_ALTA_CLINICA%TYPE DEFAULT NULL,
   PATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_INA_INT_ALTA.ATD_INA_DT_ALTA_CLINICA%TYPE DEFAULT NULL,
   pALTA NUMBER DEFAULT NULL,
   pPASSOU_PELA_UTI NUMBER DEFAULT NULL,
   pFAIXA_INI NUMBER DEFAULT NULL,
   pFAIXA_FIM NUMBER DEFAULT NULL,
  pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
  pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
  pATD_ATE_TP_PACIENTE_A IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
  pATD_ATE_TP_PACIENTE_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
  pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
  pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
  pTIS_TIN_CD_INTER_1_CLI varchar2 default null,
  pTIS_TIN_CD_INTER_2_CIR varchar2 default null,
  pTIS_TIN_CD_INTER_3_OBS varchar2 default null,
  pTIS_TIN_CD_INTER_4_PED varchar2 default null,
  pTIS_TIN_CD_INTER_5_PSI varchar2 default null,
  pTIS_TRI_CD_TP_REGINT_1_HOS IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
  pTIS_TRI_CD_TP_REGINT_2_HOD IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
  pTIS_TRI_CD_TP_REGINT_3_DOM IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
  pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
  pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_UNI_ID_UNID_PROC IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNID_PROC%TYPE DEFAULT NULL,
  pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
  pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
  pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
  pFATURADO   VARCHAR2 DEFAULT NULL,
  pLOTEGERADO VARCHAR2 DEFAULT NULL,
  pAUDITORIA  VARCHAR2 DEFAULT NULL,
  pEMITIDO    VARCHAR2 DEFAULT NULL,
  pDIGITADO   VARCHAR2 DEFAULT NULL,
  pCAD_TAP_TP_ATRIBUTO_PAC IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
  pCAD_TAP_TP_ATRIBUTO_EXA IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
  pCAD_TAP_TP_ATRIBUTO_TAX IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
  pCAD_TAP_TP_ATRIBUTO_DIA IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
  pCAD_TAP_TP_ATRIBUTO_HM IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
  pCAD_TAP_TP_ATRIBUTO_GAS IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
  pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
  pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
  pTIS_TAT_CD_TPATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
  pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
    pTIS_MED_CD_TABELAMEDICA IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
    pAUX_EPP_CD_ESPECPROC IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE DEFAULT NULL,
    pAUX_GPC_CD_GRUPOPROC IN TB_AUX_GPC_GRUPOPROC.AUX_GPC_CD_GRUPOPROC%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
   --  ,TESTE OUT LONG
)
is
/********************************************************************
*    Procedure: PRC_FAT_REL_TP_CONSUMO_MEDICO
*
*    Data Criacao:   05/09/2013  Por: PEDRO
*    Data Alteracao:   CUSTO
*
*    Funcao: Descri??o da funcionalidade da Stored Procedure
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_WHERE2  varchar2(500);
  V_SELECT  varchar2(30000);
begin
  V_WHERE := NULL;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_UNI_ID_UNID_PROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATD.CAD_UNI_ID_UNID_PROC = ' || pCAD_UNI_ID_UNID_PROC; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pCAD_PLA_ID_PLANO IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND PAC.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;    END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT; END IF;
IF pFAT_CCP_MES_COMPET IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_MES_COMPET = ' || pFAT_CCP_MES_COMPET; END IF;
IF pFAT_CCP_ANO_COMPET IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_ANO_COMPET = ' || pFAT_CCP_ANO_COMPET; END IF;

IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATD.TIS_TAT_CD_TPATENDIMENTO = ' ||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO ||CHR(39); END IF;
IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_DT_INICIO_CONSUMO >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);    END IF;
IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_DT_FIM_CONSUMO <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);    END IF;
IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRD.TIS_MED_CD_TABELAMEDICA = ' || chr(39) || pTIS_MED_CD_TABELAMEDICA || chr(39) ;    END IF;
IF pAUX_GPC_CD_GRUPOPROC IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRD.AUX_GPC_CD_GRUPOPROC = ' || chr(39) || pAUX_GPC_CD_GRUPOPROC || chr(39) ;    END IF;
IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRD.AUX_EPP_CD_ESPECPROC = ' || chr(39) || pAUX_EPP_CD_ESPECPROC || chr(39) ;    END IF;
IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATD.TIS_CBO_CD_CBOS = ' || chr(39) || pTIS_CBO_CD_CBOS || chr(39) ;    END IF;
IF pCAD_PRD_ID  IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND CCI.CAD_PRD_ID  = ' || pCAD_PRD_ID ;    END IF;
IF pCAD_PRO_ID_PROF_EXEC  IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND CCI.CAD_PRO_ID_PROFISSIONAL  = ' || pCAD_PRO_ID_PROF_EXEC ;    END IF;
IF pPASSOU_PELA_UTI  IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND FNC_FAT_ATD_PASSOU_PELA_UTI(ATD.ATD_ATE_ID) = 1 ' ;    END IF;
IF pALTA  IS NOT NULL THEN    V_WHERE := V_WHERE || 'AND AIC.ATD_AIC_TP_SITUACAO_PAC = '|| chr(39) ||'A'|| chr(39) ;    END IF;
V_WHERE2 := NULL;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE2:= V_WHERE2 || ' AND CCP.FAT_CCP_MES_FAT = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE2:= V_WHERE2 || ' AND CCP.FAT_CCP_ANO_FAT = ' || pFAT_CCP_ANO_FAT; END IF;

V_SELECT:=
 '       SELECT
         TAP.CAD_TAP_TP_ATRIBUTO,
         TAP.CAD_TAP_DS_ATRIBUTO,
         PES.CAD_PES_NM_PESSOA,
         CNV.CAD_TPE_CD_CODIGO CAD_PLA_CD_TIPOPLANO,
         UNI.CAD_UNI_DS_UNIDADE,
         UNI.CAD_UNI_CD_UNID_HOSPITALAR,
         to_char(CCI.FAT_CCI_DT_INICIO_CONSUMO,'||chr(39)||'DD/MM/YYYY'||chr(39)||') FAT_CCI_DT_INICIO_CONSUMO,
         CCP.FAT_CCP_MES_COMPET,
         CCP.FAT_CCP_ANO_COMPET,
         PRD.CAD_PRD_CD_CODIGO,
         PRD.CAD_PRD_DS_DESCRICAO,
         PRO.CAD_PRO_NR_CONSELHO,
         PRO.CAD_PRO_NM_NOME,
         CCI.ATD_ATE_ID,
         CNV.CAD_CNV_CD_HAC_PRESTADOR,
         SUM(NVL(CCI.FAT_CCI_VL_FATURADO,0)) FAT_CCI_VL_FATURADO,
         SUM(NVL(CCI.FAT_CCI_QT_CONSUMO,0)) FAT_CCI_QT_CONSUMO
        -- NVL(FNC_FAT_TOT_TP_CONSUMO_MEDICO(NULL,NULL,NULL,NULL,ATD.CAD_UNI_ID_UNIDADE,
       --      pla.cad_pla_cd_tipoplano,PRO.CAD_PRO_ID_PROFISSIONAL,PAC.CAD_PAC_ID_PACIENTE),0) TOTAL
    FROM
                  TB_FAT_CCI_CONTA_CONSU_ITEM CCI
    JOIN          TB_ATD_ATE_ATENDIMENTO      ATD    ON            ATD.ATD_ATE_ID            = CCI.ATD_ATE_ID
    LEFT JOIN     TB_FAT_CCP_CONTA_CONS_PARC  CCP
    ON            CCP.FAT_COC_ID            = CCI.FAT_COC_ID
    AND           CCP.ATD_ATE_ID            = CCI.ATD_ATE_ID
    AND           CCP.CAD_PAC_ID_PACIENTE   = CCI.CAD_PAC_ID_PACIENTE
    AND           CCP.FAT_CCP_ID            = CCI.FAT_CCP_ID
    AND           CCP.FAT_CCP_FL_STATUS     = '||chr(39)||'A'||chr(39)||'
    ' || V_WHERE2 || '
    JOIN          TB_CAD_PAC_PACIENTE       PAC    ON            PAC.CAD_PAC_ID_PACIENTE = CCI.CAD_PAC_ID_PACIENTE
    JOIN          TB_CAD_PES_PESSOA         PES    ON            PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
    JOIN          TB_CAD_CNV_CONVENIO       CNV    ON            CNV.CAD_CNV_ID_CONVENIO = CCI.CAD_CNV_ID_CONVENIO
    JOIN          TB_CAD_PRD_PRODUTO        PRD    ON            PRD.CAD_PRD_ID          = CCI.CAD_PRD_ID
    JOIN          TB_CAD_PRO_PROFISSIONAL   PRO    ON            PRO.CAD_PRO_ID_PROFISSIONAL = CCI.CAD_PRO_ID_PROFISSIONAL
    JOIN          TB_CAD_TAP_TP_ATRIB_PRODUTO TAP    ON            TAP.CAD_TAP_TP_ATRIBUTO = CCI.CAD_TAP_TP_ATRIBUTO
    JOIN      TB_CAD_UNI_UNIDADE            UNI    ON        UNI.CAD_UNI_ID_UNIDADE      = CCI.CAD_UNI_ID_UNIDADE
    LEFT JOIN     TB_ATD_AIC_ATE_INT_COMPL  AIC    ON        AIC.ATD_ATE_ID              = CCI.ATD_ATE_ID
    WHERE     (CCI.FAT_CCI_FL_STATUS      = '||chr(39)||'A'||chr(39)||')
    ' ||V_WHERE ||'
     AND     (('||chr(39)||pFATURADO||chr(39)||' IS NOT NULL AND CCP.FAT_NOF_ID IS NOT NULL )
        OR  ('||chr(39)||pAUDITORIA||chr(39)||' IS NOT NULL AND CCP.FAT_CCP_FL_STATUS_AUDIT = '||chr(39)||'E'||chr(39)||')
        OR  ('||chr(39)||pLOTEGERADO||chr(39)||' IS NOT NULL AND CCP.FAT_CCP_FL_FATURADA = '||chr(39)||'S'||chr(39)||' AND CCP.FAT_NOF_ID IS NULL)
        OR  ('||chr(39)||pEMITIDO||chr(39)||' IS NOT NULL AND CCP.FAT_CCP_FL_EMITIDA = '||chr(39)||'S'||chr(39)||' AND CCP.FAT_CCP_FL_FATURADA = '||chr(39)||'N'||chr(39)||'
            AND (CCP.FAT_CCP_FL_STATUS_AUDIT = '||chr(39)||'A'||chr(39)||' OR CCP.FAT_CCP_DT_ENVIO_AUDIT IS NULL))
        OR  ('||chr(39)||pDIGITADO||chr(39)||' IS NOT NULL AND CCI.FAT_CCP_ID IS NULL))

      AND     (('||chr(39)||pFAIXA_INI||chr(39)||' IS NULL AND '||chr(39)||pFAIXA_FIM||chr(39)||' IS NULL) OR
             fnc_fat_total_item(CCI.FAT_COC_ID,CCI.FAT_CCP_ID,CCI.CAD_TAP_TP_ATRIBUTO,
                      CCI.ATD_ATE_ID,NULL,NULL,CCI.CAD_PAC_ID_PACIENTE) >= '||chr(39)||pFAIXA_INI||chr(39)||' AND
             fnc_fat_total_item(CCI.FAT_COC_ID,CCI.FAT_CCP_ID,CCI.CAD_TAP_TP_ATRIBUTO,
                      CCI.ATD_ATE_ID,NULL,NULL,CCI.CAD_PAC_ID_PACIENTE) <= '||chr(39)||pFAIXA_FIM||chr(39)||')

   AND ('||chr(39)||pTIS_TRI_CD_TP_REGINT_1_HOS||chr(39)||' IS NOT NULL AND AIC.TIS_TRI_CD_REGINTENNACAO = 1
   OR '||chr(39)||pTIS_TRI_CD_TP_REGINT_2_HOD||chr(39)||' IS NOT NULL AND AIC.TIS_TRI_CD_REGINTENNACAO = 2
   OR '||chr(39)||pTIS_TRI_CD_TP_REGINT_3_DOM||chr(39)||' IS NOT NULL AND AIC.TIS_TRI_CD_REGINTENNACAO = 3)

  AND    ('||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)||' IS not NULL and CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'ACS'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'PA'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'SP'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'FU'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'NP'||chr(39)||')

        AND ('||chr(39)||pCAD_TAP_TP_ATRIBUTO_PAC||chr(39)||' IS not NULL and CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'PAC'||chr(39)||'
        OR '||chr(39)||pCAD_TAP_TP_ATRIBUTO_EXA||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'EXA'||chr(39)||'
        OR '||chr(39)||pCAD_TAP_TP_ATRIBUTO_TAX||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'TAX'||chr(39)||'
        OR '||chr(39)||pCAD_TAP_TP_ATRIBUTO_DIA||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'DIA'||chr(39)||'
        OR '||chr(39)||pCAD_TAP_TP_ATRIBUTO_HM||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'HM'||chr(39)||'
        OR '||chr(39)||pCAD_TAP_TP_ATRIBUTO_GAS||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'GAS'||chr(39)||')

       AND ('||chr(39)||pATD_ATE_FL_CARATER_SOLIC_U||chr(39)||' IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = '||chr(39)||'U'||chr(39)||'
        OR '||chr(39)||pATD_ATE_FL_CARATER_SOLIC_E||chr(39)||' IS NOT NULL AND ATD.ATD_ATE_FL_CARATER_SOLIC = '||chr(39)||'E'||chr(39)||')

        AND ('||chr(39)||pATD_ATE_TP_PACIENTE_I||chr(39)||' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = '||chr(39)||'I'||chr(39)||'
        OR '||chr(39)||pATD_ATE_TP_PACIENTE_E||chr(39)||' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = '||chr(39)||'E'||chr(39)||'
        OR '||chr(39)||pATD_ATE_TP_PACIENTE_A||chr(39)||' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = '||chr(39)||'A'||chr(39)||'
        OR '||chr(39)||pATD_ATE_TP_PACIENTE_U||chr(39)||' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = '||chr(39)||'U'||chr(39)||')

   GROUP BY
           TAP.CAD_TAP_TP_ATRIBUTO,
           TAP.CAD_TAP_DS_ATRIBUTO,
           PES.CAD_PES_NM_PESSOA,
           CNV.CAD_TPE_CD_CODIGO,
           UNI.CAD_UNI_DS_UNIDADE,
           UNI.CAD_UNI_CD_UNID_HOSPITALAR,
           CCI.FAT_CCI_DT_INICIO_CONSUMO,
           CCP.FAT_CCP_MES_COMPET,
           CCP.FAT_CCP_ANO_COMPET,
           PRD.CAD_PRD_CD_CODIGO,
           PRD.CAD_PRD_DS_DESCRICAO,
           PRO.CAD_PRO_NR_CONSELHO,
           PRO.CAD_PRO_NM_NOME,
           CCI.ATD_ATE_ID,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           CCI.FAT_CCI_VL_FATURADO,
           CCI.FAT_CCI_QT_CONSUMO'
        ;
    --TESTE :=  V_SELECT ;
  OPEN v_cursor FOR
   V_SELECT ;
 --SELECT 1 FROM DUAL;
    io_cursor := v_cursor;
end PRC_FAT_REL_TP_CONSUMO_MEDICO;
