create or replace procedure sgs.PRC_ATS_APL_FLAGLANCTO_U
  (
     pATS_ATE_ID IN TB_ATS_APL_ATEN_PROCED_LAUDO.ATS_ATE_ID%type,
     pAUX_EPP_CD_ESPECPROC IN TB_ATS_APL_ATEN_PROCED_LAUDO.AUX_EPP_CD_ESPECPROC%type,
     pATS_ATE_IN_INTLIB IN TB_ATS_APL_ATEN_PROCED_LAUDO.ATS_ATE_IN_INTLIB%type,
     pATS_ATE_CD_INTLIB IN TB_ATS_APL_ATEN_PROCED_LAUDO.ATS_ATE_CD_INTLIB%type,
     pCAD_PRD_ID IN TB_ATS_APL_ATEN_PROCED_LAUDO.CAD_PRD_ID%type,
     pTIS_MED_CD_TABELAMEDICA IN TB_ATS_APS_ATEN_PROC_SEGMENTO.TIS_MED_CD_TABELAMEDICA%type,
     pATS_ATE_FL_ATUALIZADO_LANCAM IN TB_ATS_APL_ATEN_PROCED_LAUDO.ATS_ATE_FL_ATUALIZADO_LANCAM%type
  )
  is

  begin

       UPDATE TB_ATS_APL_ATEN_PROCED_LAUDO APL
       SET APL.ATS_ATE_FL_ATUALIZADO_LANCAM = pATS_ATE_FL_ATUALIZADO_LANCAM
       --			 ,       APL.ATS_APL_DT_ULTIMA_ATUALIZACAO = SYSDATE
       WHERE APL.ATS_ATE_ID            = pATS_ATE_ID
       AND APL.ATS_ATE_CD_INTLIB       = pATS_ATE_CD_INTLIB
       AND APL.ATS_ATE_IN_INTLIB       = pATS_ATE_IN_INTLIB
       AND APL.AUX_EPP_CD_ESPECPROC    = pAUX_EPP_CD_ESPECPROC
       AND APL.CAD_PRD_ID              = pCAD_PRD_ID
       AND APL.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA;

  end PRC_ATS_APL_FLAGLANCTO_U;
