CREATE OR REPLACE PROCEDURE "PRC_ASS_CPR_CLINICA_PROF_L_GER"
(
  PCAD_REP_ID                 IN VARCHAR2 DEFAULT NULL,
  PCAD_CLC_CD_CLINICA         IN TB_CAD_CLC_CLINICA_CREDENCIADA.CAD_CLC_CD_CLINICA%TYPE DEFAULT NULL,
  PCAD_REP_DT_INICIO_VIGENCIA IN TB_CAD_REP_REGRA_PAGAMENTO.CAD_REP_DT_INICIO_VIGENCIA%TYPE DEFAULT NULL,
  PCAD_REP_DT_FIM_VIGENCIA    IN TB_CAD_REP_REGRA_PAGAMENTO.CAD_REP_DT_FIM_VIGENCIA%TYPE DEFAULT NULL,
  PID_PROFISSIONAL            IN VARCHAR2 DEFAULT NULL,
  PID_ESPECIALIDADE           IN VARCHAR2 DEFAULT NULL,
  PID_UNIDADE                 IN VARCHAR2 DEFAULT NULL,
  PID_LOCAL                   IN VARCHAR2 DEFAULT NULL,
  PID_SETOR                   IN VARCHAR2 DEFAULT NULL,
  PID_TABELA_MEDICA           IN VARCHAR2 DEFAULT NULL,
  PID_CODIGO_GRUPO            IN VARCHAR2 DEFAULT NULL,
  PID_CODIGO_SUBGRUPO         IN VARCHAR2 DEFAULT NULL,
  PID_PROCEDIMENTO            IN VARCHAR2 DEFAULT NULL,
  PID_CONVENIO                IN VARCHAR2 DEFAULT NULL,
  PID_PLANO                   IN VARCHAR2 DEFAULT NULL,
  PID_TIPOEMPRESA             IN VARCHAR2 DEFAULT NULL,
  PVIGENTES                   IN VARCHAR2,
  pCAD_PRD_CD_PACOTE          IN VARCHAR2 DEFAULT NULL,
  pCAD_PRD_CD_ITEM_PACOTE     IN VARCHAR2 DEFAULT NULL,
  pFLAG_FONTE_PAGADORA        IN VARCHAR2 DEFAULT NULL,
  IO_CURSOR                   OUT PKG_CURSOR.T_CURSOR
) IS
  /********************************************************************
  *    Procedure: PRC_CAD_REP_BASE_CALCULO_L
  *
  *    Data Criacao:  data da  criac?o   Por: Nome do Analista
  *    Data Alteracao: 27/03/2015        Por: Nome do Analista
  *
  *    Funcao: Descric?o da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  V_CURSOR PKG_CURSOR.T_CURSOR;
  V_WHERE  VARCHAR2(9000);
  V_SELECT VARCHAR2(9000);
BEGIN
  V_WHERE := ' WHERE CLC.CAD_CLC_CD_CLINICA = ' || PCAD_CLC_CD_CLINICA;
  IF PCAD_REP_ID IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND REP.CAD_REP_ID IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PCAD_REP_ID || ''' ))) ';
  END IF;
  IF (PVIGENTES = 'S') THEN
    V_WHERE := V_WHERE || ' AND (RPG.CAD_REP_DT_FIM_VIGENCIA IS NULL OR TO_DATE(RPG.CAD_REP_DT_FIM_VIGENCIA,''dd/mm/yyyy'') >= TO_DATE((SYSDATE), ''dd/mm/yyyy'')) ';
    V_WHERE := V_WHERE || ' AND (CPR.ASS_CPR_DT_FIM_VIGENCIA IS NULL OR TO_DATE(CPR.ASS_CPR_DT_FIM_VIGENCIA,''dd/mm/yyyy'') >= TO_DATE((SYSDATE), ''dd/mm/yyyy'')) ';
  ELSE
    V_WHERE := V_WHERE || ' AND (TO_DATE(RPG.CAD_REP_DT_FIM_VIGENCIA,''dd/mm/yyyy'') <= TO_DATE((SYSDATE), ''dd/mm/yyyy'')) ';
    V_WHERE := V_WHERE || ' AND (CPR.ASS_CPR_DT_FIM_VIGENCIA IS NULL OR TO_DATE(CPR.ASS_CPR_DT_FIM_VIGENCIA,''dd/mm/yyyy'') <= TO_DATE((SYSDATE), ''dd/mm/yyyy'')) ';
  END IF;
  IF PCAD_REP_DT_INICIO_VIGENCIA IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND REP.CAD_REP_DT_INICIO_VIGENCIA >= ' || PCAD_REP_DT_INICIO_VIGENCIA;
  END IF;
  IF PCAD_REP_DT_FIM_VIGENCIA IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND REP.CAD_REP_DT_FIM_VIGENCIA <= ' || PCAD_REP_DT_FIM_VIGENCIA;
  END IF;
  IF PID_PROFISSIONAL IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_PRO_ID_PROFISSIONAL IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_PROFISSIONAL || ''' ))) ';
  END IF;
  IF PID_ESPECIALIDADE IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.TIS_CBO_CD_CBOS IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_ESPECIALIDADE || ''' ))) ';
  END IF;
  IF PID_UNIDADE IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_UNI_ID_UNIDADE IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_UNIDADE || ''' ))) ';
  END IF;
  IF PID_LOCAL IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_LAT_ID_LOCAL_ATENDIMENTO IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_LOCAL || ''' ))) ';
  END IF;
  IF PID_SETOR IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_SET_ID IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_SETOR || ''' ))) ';
  END IF;
  IF PID_TABELA_MEDICA IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.TIS_MED_CD_TABELAMEDICA IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_TABELA_MEDICA || ''' ))) ';
  END IF;
  IF PID_CODIGO_GRUPO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.AUX_EPP_CD_ESPECPROC IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_CODIGO_GRUPO || ''' ))) ';
  END IF;
  IF PID_CODIGO_SUBGRUPO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.AUX_GPC_CD_GRUPOPROC IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_CODIGO_SUBGRUPO || ''' ))) ';
  END IF;
  IF PID_PROCEDIMENTO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_PRD_ID IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_PROCEDIMENTO || ''' ))) ';
  END IF;
  IF PID_CONVENIO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_CNV_ID_CONVENIO IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_CONVENIO || ''' ))) ';
  END IF;
  IF PID_PLANO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_PLA_ID_PLANO IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_PLANO || ''' ))) ';
  END IF;
  IF PID_TIPOEMPRESA IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_TPE_CD_CODIGO IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || PID_TIPOEMPRESA || ''' ))) ';
  END IF;
  IF pCAD_PRD_CD_PACOTE IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_PRD_CD_PACOTE IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || pCAD_PRD_CD_PACOTE || ''' ))) ';
  END IF;
  IF pCAD_PRD_CD_ITEM_PACOTE IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND CPR.CAD_PRD_CD_ITEM_PACOTE IN ( SELECT * FROM TABLE(FNC_SPLIT(''' || pCAD_PRD_CD_ITEM_PACOTE || ''' ))) ';
  END IF;
  IF pFLAG_FONTE_PAGADORA = 'HAC' THEN
    V_WHERE := V_WHERE || ' AND NVL(RPG.ASS_RPG_PC_HAC, 0) > 0 ';
  END IF;
  IF pFLAG_FONTE_PAGADORA = 'ACS' THEN
    V_WHERE := V_WHERE || ' AND NVL(RPG.ASS_RPG_PC_ACS, 0) > 0 ';
  END IF;

  V_SELECT := 'SELECT DISTINCT
                      CPR.ASS_CPR_ID, REP.CAD_REP_ID, REP.CAD_REP_NM_REGRA, REP.CAD_REP_ID,
                      REP.CAD_REP_TP_BASE_CALCULO,
                      CPR.CAD_UNI_ID_UNIDADE, UNI.CAD_UNI_DS_UNIDADE,
                      CPR.CAD_LAT_ID_LOCAL_ATENDIMENTO, LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
                      CPR.CAD_SET_ID, SETO.CAD_SET_DS_SETOR,
                      CPR.CAD_PRO_ID_PROFISSIONAL, PRO.CAD_PRO_SG_UF_CONSELHO, PRO.CAD_PRO_CD_COD_PRO, PRO.CAD_PRO_NR_CONSELHO, PRO.CAD_PRO_NM_NOME,
                      CPR.TIS_CBO_CD_CBOS, CBO.TIS_CBO_DS_CBOS,
                      CPR.CAD_PRD_ID, PRD.CAD_PRD_CD_CODIGO, PRD.CAD_PRD_DS_DESCRICAO,
                      CPR.TIS_MED_CD_TABELAMEDICA, MED.TIS_MED_DS_TABELAMEDICA,
                      CPR.AUX_GPC_CD_GRUPOPROC, GPC.AUX_GPC_DS_DESCRICAO,
                      CPR.AUX_EPP_CD_ESPECPROC, EPP.AUX_EPP_DS_DESCRICAO,
                      CPR.CAD_CNV_ID_CONVENIO, CNV.CAD_CNV_CD_HAC_PRESTADOR, CNV.CAD_CNV_DS_RAZAOSOCIAL,
                      CPR.CAD_PLA_ID_PLANO, PLA.CAD_PLA_CD_PLANO_HAC, PLA.CAD_PLA_NM_NOME_PLANO,
                      CPR.CAD_TPE_CD_CODIGO, TPE.CAD_TPE_DS_DESCRICAO,
                      CPR.CAD_CLC_ID, CLC.CAD_CLC_DS_DESCRICAO,
                      CPR.ASS_CPR_DT_INICIO_VIGENCIA, CPR.ASS_CPR_DT_FIM_VIGENCIA,
                      RPG.ASS_RPG_PC_HAC, RPG.ASS_RPG_PC_ACS,
                      RPG.CAD_REP_DT_INICIO_VIGENCIA, RPG.CAD_REP_DT_FIM_VIGENCIA,
                      CPR.CAD_PRD_CD_PACOTE,
                      RPG.ASS_RPG_ID,
                      CPR.CAD_PRD_CD_ITEM_PACOTE,
                      PRODUTO_PACOTE.DS_PCT DESCRICAO_PACOTE,
                     (SELECT PRD2.CAD_PRD_DS_DESCRICAO
                        FROM TB_CAD_PRD_PRODUTO PRD2
                       WHERE TRIM(PRD2.CAD_PRD_CD_CODIGO) = TRIM(SUB.CD_ITEM_PCT)
                        AND TO_CHAR(PRD2.CAD_PRD_DT_ULTIMA_ATUALIZACAO, ' || CHR(39) || 'DD/MM/YYYY HH24:MI:SS' || CHR(39) || ') = TO_CHAR(SUB.ULT_DATA, ' || CHR(39) || 'DD/MM/YYYY HH24:MI:SS' || CHR(39) || ')) DESCRICAO_ITEM_PACOTE

                 FROM TB_ASS_RPG_REGRA_PAGTO RPG
               INNER JOIN TB_ASS_CPR_CLINICA_PROF CPR
                   ON RPG.ASS_CPR_ID = CPR.ASS_CPR_ID
               INNER JOIN TB_CAD_CLC_CLINICA_CREDENCIADA CLC
                   ON CPR.CAD_CLC_ID = CLC.CAD_CLC_ID
               INNER JOIN TB_CAD_REP_REGRA_PAGAMENTO REP
                   ON RPG.CAD_REP_ID = REP.CAD_REP_ID
                 LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO
                   ON CPR.CAD_PRO_ID_PROFISSIONAL = PRO.CAD_PRO_ID_PROFISSIONAL
                 LEFT JOIN TB_CAD_PRD_PRODUTO PRD
                   ON CPR.CAD_PRD_ID = PRD.CAD_PRD_ID
                 LEFT JOIN TB_CAD_CNV_CONVENIO CNV
                   ON CPR.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
                 LEFT JOIN TB_CAD_PLA_PLANO PLA
                   ON CPR.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
                 LEFT JOIN TB_CAD_UNI_UNIDADE UNI
                   ON CPR.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
                 LEFT JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
                   ON CPR.CAD_LAT_ID_LOCAL_ATENDIMENTO = LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO
                 LEFT JOIN TB_CAD_SET_SETOR SETO
                   ON CPR.CAD_SET_ID = SETO.CAD_SET_ID
                 LEFT JOIN TB_TIS_CBO_CBOS CBO
                   ON CPR.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
                 LEFT JOIN TB_CAD_TPE_TIPOEMPRESA TPE
                   ON CPR.CAD_TPE_CD_CODIGO = TPE.CAD_TPE_CD_CODIGO
                 LEFT JOIN TB_AUX_EPP_ESPECPROC EPP
                   ON CPR.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC
                  AND CPR.TIS_MED_CD_TABELAMEDICA = EPP.TIS_MED_CD_TABELAMEDICA
                 LEFT JOIN TB_AUX_GPC_GRUPOPROC GPC
                  ON CPR.AUX_GPC_CD_GRUPOPROC = GPC.AUX_GPC_CD_GRUPOPROC
                 AND CPR.TIS_MED_CD_TABELAMEDICA = GPC.TIS_MED_CD_TABELAMEDICA
                 AND CPR.AUX_EPP_CD_ESPECPROC = GPC.AUX_EPP_CD_ESPECPROC
                LEFT JOIN TB_TIS_MED_TABELAMEDICA MED
                  ON CPR.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA
                LEFT JOIN ( SELECT DISTINCT CPR.CAD_PRD_CD_PACOTE CD_PCT, PRD_PCT.CAD_PRD_DS_DESCRICAO DS_PCT
                              FROM TB_ASS_CPR_CLINICA_PROF CPR
                              LEFT JOIN TB_CAD_PRD_PRODUTO PRD_PCT
                                ON CPR.CAD_PRD_CD_PACOTE = TRIM(PRD_PCT.CAD_PRD_CD_CODIGO)) PRODUTO_PACOTE
                ON PRODUTO_PACOTE.CD_PCT = CPR.CAD_PRD_CD_PACOTE
                LEFT JOIN ( SELECT CPR_ITEM.CAD_PRD_CD_PACOTE, CPR_ITEM.CAD_PRD_CD_ITEM_PACOTE CD_ITEM_PCT, MAX(MAX(PRD_ITEM_PCT.CAD_PRD_DT_ULTIMA_ATUALIZACAO)) OVER(PARTITION BY PRD_ITEM_PCT.CAD_PRD_CD_CODIGO) ULT_DATA
                              FROM TB_ASS_CPR_CLINICA_PROF CPR_ITEM
                              JOIN TB_CAD_PRD_PRODUTO PRD_ITEM_PCT
                                ON TRIM(PRD_ITEM_PCT.CAD_PRD_CD_CODIGO) = TRIM(CPR_ITEM.CAD_PRD_CD_ITEM_PACOTE)
                             GROUP BY CPR_ITEM.CAD_PRD_CD_PACOTE, CPR_ITEM.CAD_PRD_CD_ITEM_PACOTE, PRD_ITEM_PCT.CAD_PRD_CD_CODIGO) SUB
                 ON CPR.CAD_PRD_CD_PACOTE = SUB.CAD_PRD_CD_PACOTE
                AND CPR.CAD_PRD_CD_ITEM_PACOTE = SUB.CD_ITEM_PCT ';

  V_SELECT := V_SELECT || V_WHERE;
  OPEN V_CURSOR FOR
    V_SELECT;
    -- DBMS_OUTPUT.put_line(V_SELECT);
    IO_CURSOR := V_CURSOR;
END PRC_ASS_CPR_CLINICA_PROF_L_GER;
