CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_PROC_MED_LOCAL"
(
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_MES_COMPET  VARCHAR2 default null,
    pFAT_CCP_ANO_COMPET  VARCHAR2 default null,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_TAX IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_HM IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_EXA IN TB_FAT_CCI_CONTA_CONSU_ITEM.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
    pTIS_MED_CD_TABELAMEDICA IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
    pAUX_EPP_CD_ESPECPROC IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE DEFAULT NULL,
    pAUX_GPC_CD_GRUPOPROC IN TB_AUX_GPC_GRUPOPROC.AUX_GPC_CD_GRUPOPROC%TYPE DEFAULT NULL,
    --pCAD_MPF_ID in tb_cad_mpf_moti_pend_faturar.cad_mpf_id%type default null,
    pCAD_MPF_ID varchar2 default null,
    pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pFATURADO   VARCHAR2 DEFAULT NULL, 
    pLOTEGERADO VARCHAR2 DEFAULT NULL,
    pAUDITORIA  VARCHAR2 DEFAULT NULL,
    pEMITIDO    VARCHAR2 DEFAULT NULL,
    pDIGITADO   VARCHAR2 DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_E in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_A in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_U in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    io_cursor OUT PKG_CURSOR.t_cursor--,
  --  QUERY OUT  LONG 
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_PROC_MED_LOCAL
*
*    Data Alteracao: 17/6/2011  Por: PEDRO
*    Alterac?o: TUDO
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(4000);
  V_SELECT  varchar2(12000);
begin
  V_WHERE := NULL;
  IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PAC.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO; END IF;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_PLA_ID_PLANO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PAC.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO; END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT; END IF;
IF pCAD_MPF_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' (MPF.CAD_MPF_ID IN (SELECT COLUMN_VALUE FROM TABLE(FNC_SPLIT(' || CHR(39) || pCAD_MPF_ID || CHR(39) || ')))) ' ; END IF;
IF pCAD_PRD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRD.CAD_PRD_ID = ' || PCAD_PRD_ID; END IF;
IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRD.TIS_MED_CD_TABELAMEDICA = ' || CHR(39) || pTIS_MED_CD_TABELAMEDICA || CHR(39); END IF;
IF pAUX_GPC_CD_GRUPOPROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRD.AUX_GPC_CD_GRUPOPROC = '  || CHR(39) || pAUX_GPC_CD_GRUPOPROC || CHR(39); END IF;
IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRD.AUX_EPP_CD_ESPECPROC = ' || CHR(39) || pAUX_EPP_CD_ESPECPROC || CHR(39); END IF;
IF pCAD_PRO_ID_PROF_EXEC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.CAD_PRO_ID_PROFISSIONAL = ' || pCAD_PRO_ID_PROF_EXEC; END IF;
IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.TIS_CBO_CD_CBOS = '  || CHR(39) || pTIS_CBO_CD_CBOS || CHR(39); END IF;
IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO BETWEEN ' || CHR(39) || pATD_ATE_DT_ATENDIMENTO_INI || CHR(39) || ' AND ' || CHR(39) || pATD_ATE_DT_ATENDIMENTO_FIM || CHR(39); END IF;
   V_SELECT := '
 SELECT  PRO.CAD_PRO_NR_CONSELHO,
          PRO.CAD_PRO_NM_NOME,
          CNV.CAD_CNV_CD_HAC_PRESTADOR,
          CNV.CAD_CNV_DS_RAZAOSOCIAL,
          ATE.ATD_ATE_ID,
          ATE.ATD_ATE_DT_ATENDIMENTO,
          UNI.CAD_UNI_CD_UNID_HOSPITALAR,
          PES.CAD_PES_NM_PESSOA,
          PRD.CAD_PRD_CD_CODIGO,
          PRD.CAD_PRD_DS_DESCRICAO,
          SUM(CCI.FAT_CCI_QT_CONSUMO) FAT_CCI_QT_CONSUMO,
          SUM(CCI.FAT_CCI_VL_FATURADO) FAT_CCI_VL_FATURADO,
          SUM(CCI.FAT_CCI_VL_CALCULADO) FAT_CCI_VL_CALCULADO
  FROM    TB_FAT_CCI_CONTA_CONSU_ITEM   CCI
  JOIN    TB_CAD_PRO_PROFISSIONAL       PRO
  ON      CCI.CAD_PRO_ID_PROFISSIONAL = PRO.CAD_PRO_ID_PROFISSIONAL
  JOIN    TB_CAD_PAC_PACIENTE           PAC
  ON      CCI.CAD_PAC_ID_PACIENTE     = PAC.CAD_PAC_ID_PACIENTE
  JOIN    TB_CAD_CNV_CONVENIO           CNV
  ON      CNV.CAD_CNV_ID_CONVENIO     = PAC.CAD_CNV_ID_CONVENIO
  JOIN    TB_CAD_PES_PESSOA             PES
  ON      PES.CAD_PES_ID_PESSOA       = PAC.CAD_PES_ID_PESSOA
  JOIN    TB_ATD_ATE_ATENDIMENTO        ATE
  ON      CCI.ATD_ATE_ID              = ATE.ATD_ATE_ID
  JOIN    TB_CAD_PRD_PRODUTO            PRD
  ON      CCI.CAD_PRD_ID              = PRD.CAD_PRD_ID
  JOIN    TB_CAD_UNI_UNIDADE            UNI
  ON      UNI.CAD_UNI_ID_UNIDADE      = ATE.CAD_UNI_ID_UNIDADE
  LEFT JOIN    TB_CAD_MPF_MOTI_PEND_FATURAR  MPF
  ON      MPF.CAD_MPF_ID              = CCI.CAD_MPF_ID
  JOIN    TB_CAD_PLA_PLANO              PLA
  ON      PAC.CAD_PLA_ID_PLANO        = PLA.CAD_PLA_ID_PLANO
  LEFT JOIN    TB_FAT_CCP_CONTA_CONS_PARC    CCP
  ON      CCI.FAT_CCP_ID              = CCP.FAT_CCP_ID
  AND     CCI.CAD_PAC_ID_PACIENTE     = CCP.CAD_PAC_ID_PACIENTE
  AND     CCI.FAT_COC_ID              = CCP.FAT_COC_ID
  AND     CCI.ATD_ATE_ID              = CCP.ATD_ATE_ID
  AND    (CCP.FAT_CCP_FL_STATUS = '||CHR(39)||'A'||CHR(39)||')
  AND    ( ' ||CHR(39)|| pFAT_CCP_MES_COMPET ||CHR(39)|| ' IS NULL OR CCP.FAT_CCP_MES_COMPET = ' ||CHR(39)|| pFAT_CCP_MES_COMPET ||CHR(39)|| ')
  AND    ( ' ||CHR(39)|| pFAT_CCP_ANO_COMPET ||CHR(39)|| ' IS NULL OR CCP.FAT_CCP_ANO_COMPET = ' ||CHR(39)|| pFAT_CCP_ANO_COMPET ||CHR(39)|| ')
  WHERE  (CCI.FAT_CCI_FL_STATUS = '||CHR(39)||'A'||CHR(39)||')
  AND    (ATE.ATD_ATE_FL_STATUS = '||CHR(39)||'A'||CHR(39)||')
'
|| V_WHERE ||
'         
  AND     (( '||CHR(39)|| pFATURADO ||CHR(39)||' IS NOT NULL AND CCP.FAT_NOF_ID IS NOT NULL )
      OR  ( '||CHR(39)|| pAUDITORIA ||CHR(39)||' IS NOT NULL AND CCP.FAT_CCP_FL_STATUS_AUDIT = '||CHR(39)||'E'||CHR(39)||')
      OR  ( '||CHR(39)|| pLOTEGERADO ||CHR(39)||' IS NOT NULL AND CCP.FAT_CCP_FL_FATURADA = '||CHR(39)||'S'||CHR(39)||' AND CCP.FAT_NOF_ID IS NULL)
      OR  ( '||CHR(39)|| pEMITIDO ||CHR(39)||' IS NOT NULL AND CCP.FAT_CCP_FL_EMITIDA = '||CHR(39)||'S'||CHR(39)||' AND CCP.FAT_CCP_FL_FATURADA = '||CHR(39)||'N'||CHR(39)||'
          AND (CCP.FAT_CCP_FL_STATUS_AUDIT = '||CHR(39)||'A'||CHR(39)||' OR CCP.FAT_CCP_DT_ENVIO_AUDIT IS NULL))
      OR  ( '||CHR(39)|| pDIGITADO ||CHR(39)||' IS NOT NULL AND CCI.FAT_CCP_ID IS NULL)     )
   AND ( '||CHR(39)|| pATD_ATE_TP_PACIENTE_I ||CHR(39)||' IS not NULL and ATE.ATD_ATE_TP_PACIENTE = '||CHR(39)||'I'||CHR(39)||'
       OR '||CHR(39)|| pATD_ATE_TP_PACIENTE_E ||CHR(39)||' IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = '||CHR(39)||'E'||CHR(39)||'
       OR '||CHR(39)|| pATD_ATE_TP_PACIENTE_A ||CHR(39)||' IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = '||CHR(39)||'A'||CHR(39)||'
       OR '||CHR(39)|| pATD_ATE_TP_PACIENTE_U ||CHR(39)||' IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = '||CHR(39)||'U'||CHR(39)||')
  AND    ( '||CHR(39)||pCAD_TAP_TP_ATRIBUTO_TAX ||CHR(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||CHR(39)||'TAX'||CHR(39)||'
          OR '||CHR(39)|| pCAD_TAP_TP_ATRIBUTO_EXA ||CHR(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||CHR(39)||'EXA'||CHR(39)||'
          OR '||CHR(39)|| pCAD_TAP_TP_ATRIBUTO_HM ||CHR(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||CHR(39)||'HM'||CHR(39)||')
  AND    ('||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||CHR(39)||' IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = '||CHR(39)||'GB'||CHR(39)||'
       OR '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_PL ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||CHR(39)||'PL'||CHR(39)||'
       OR '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||CHR(39)||'PA'||CHR(39)||'
       OR '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||CHR(39)||'SP'||CHR(39)||'
       OR '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||CHR(39)||'FU'||CHR(39)||'
       OR '||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||CHR(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||CHR(39)||'NP'||CHR(39)||'
           )
  GROUP   BY PRO.CAD_PRO_NR_CONSELHO,
          PRO.CAD_PRO_NM_NOME,
          CNV.CAD_CNV_CD_HAC_PRESTADOR,
          CNV.CAD_CNV_DS_RAZAOSOCIAL,
          ATE.ATD_ATE_ID,
          ATE.ATD_ATE_DT_ATENDIMENTO,
          UNI.CAD_UNI_CD_UNID_HOSPITALAR,
          PES.CAD_PES_NM_PESSOA,
          PRD.CAD_PRD_CD_CODIGO,
          PRD.CAD_PRD_DS_DESCRICAO
  ORDER   BY PRO.CAD_PRO_NM_NOME,
          CNV.CAD_CNV_DS_RAZAOSOCIAL,
          PES.CAD_PES_NM_PESSOA,
          ATE.ATD_ATE_ID,
          ATE.ATD_ATE_DT_ATENDIMENTO,
          PRD.CAD_PRD_CD_CODIGO,
          PRD.CAD_PRD_DS_DESCRICAO';
 -- QUERY :=  V_SELECT ;
    OPEN v_cursor FOR
  V_SELECT ;
  io_cursor := v_cursor;
END PRC_FAT_REL_PROC_MED_LOCAL;
 