CREATE OR REPLACE PROCEDURE PRC_CAD_MTMD_MAT_MED_S
(
   pCAD_MTMD_ID                  IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_ID%type DEFAULT NULL,
   pCAD_MTMD_PRIATI_ID           IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_PRIATI_ID%type DEFAULT NULL,
   pCAD_MTMD_GRUPO_ID            IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_GRUPO_ID%type DEFAULT NULL,
   pCAD_MTMD_SUBGRUPO_ID         IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_SUBGRUPO_ID%type DEFAULT NULL,
   pTIS_MED_CD_TABELAMEDICA      IN TB_CAD_MTMD_MAT_MED.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
   pCAD_MTMD_NOMEFANTASIA        IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_NOMEFANTASIA%type DEFAULT NULL,
   pCAD_MTMD_DESCRICAO           IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_DESCRICAO%type DEFAULT NULL,
   pCAD_MTMD_UNIDADE_VENDA       IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_UNIDADE_VENDA%type DEFAULT NULL,
   pCAD_MTMD_UNIDADE_COMPRA      IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_UNIDADE_COMPRA%type DEFAULT NULL,
   pCAD_MTMD_UNIDADE_CONTROLE    IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_UNIDADE_CONTROLE%type DEFAULT NULL,
   pCAD_MTMD_CODMNE              IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_CODMNE%type DEFAULT NULL,
   pCAD_MTMD_CURVA_ABC           IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_CURVA_ABC%type DEFAULT NULL,
   pCAD_MTMD_CD_FABRICANTE       IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_CD_FABRICANTE%type DEFAULT NULL,
   pCAD_MTMD_FL_FRACIONA         IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_FL_FRACIONA%type DEFAULT NULL,
   pCAD_MTMD_FL_ATIVO            IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_FL_ATIVO%type DEFAULT NULL,
   pCAD_MTMD_FL_MANTER_ESTOQUE   IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_FL_MANTER_ESTOQUE%type DEFAULT NULL,
   pCAD_MTMD_FL_REUTILIZAVEL     IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_FL_REUTILIZAVEL%type DEFAULT NULL,
   pCAD_MTMD_DT_ATUALIZACAO      IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_DT_ATUALIZACAO%type DEFAULT NULL,
   pCAD_MTMD_CD_RM               IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_CD_RM%type DEFAULT NULL,
   pCAD_MTMD_FILIAL_ID           IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
   pCAD_SET_ID                   IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
   pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_SET_SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
   pCAD_UNI_ID_UNIDADE           IN TB_CAD_SET_SETOR.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
   pTP_PESQUISA                  IN NUMBER,
   pCAD_MTMD_FL_DILUENTE IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_FL_DILUENTE%type DEFAULT NULL,
   io_cursor                     OUT PKG_CURSOR.t_cursor
)
is
V_WHERE  varchar2(5000);
V_SELECT  varchar2(5000);
v_cursor PKG_CURSOR.t_cursor;
--vTP_PESQUISA NUMBER;
  /********************************************************************
  *    Procedure: PRC_CAD_MTMD_MAT_MED_S
  *
  *    Data Criacao: 11/2009   Por: RICARDO COSTA
  *    Data Alteracao:19/03/2010    Por: RICARDO COSTA
  *         Alterac?o: ADICIONADO CAMPO FL_FATURADO RETORNAR PARA DTO
  *    Data Alteracao:  23/07/2012  Por: Andre S. Monaco
  *         Alteracao:  Adic?o do campo CAD_MTMD_CD_ANVISA e padronizac?o de query
  *    Data Alteracao:  26/04/2017  Por: Andre S. Monaco
  *         Alteracao:  Adicao campo CAD_MTMD_CD_GRUPO_ANVISA
  *    Data Alteracao:  24/10/2017  Por: Andre S. Monaco
  *         Alteracao:  Adicao funcao SOUND ALIKE na descricao
  *
  *    Funcao:  Busca informac?es sobre produtos cadastrados
  *******************************************************************/
/*
Busca informac?es sobre produtos cadastrados
TP_PESQUISA: 0= N?O LEVA EM CONSIDERAC?O ESTOQUE DA UNIDADE OU SEU CENTRO DE DISPENSAC?O PARA PESQUISAR PRODUTOS
             1= SO RETORNA PRODUTOS QUE EXISTAM E TENHAM ESTOQUE NA UNIDADE OU NO SEU CENTRO DE DISPENSAC?O
*/
BEGIN
/*  IF ( pTP_PESQUISA IS NULL ) THEN
    vTP_PESQUISA := 0;
  ELSE
    vTP_PESQUISA := pTP_PESQUISA;
  END IF;*/
  IF pCAD_MTMD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_ID = ' || pCAD_MTMD_ID; END IF;
  IF pCAD_MTMD_PRIATI_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_PRIATI_ID = ' || pCAD_MTMD_PRIATI_ID; END IF;
  IF pCAD_MTMD_GRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_GRUPO_ID = ' || pCAD_MTMD_GRUPO_ID; END IF;
  IF pCAD_MTMD_SUBGRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_SUBGRUPO_ID = ' || pCAD_MTMD_SUBGRUPO_ID; END IF;
  IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.TIS_MED_CD_TABELAMEDICA = ' || CHR(39) || pTIS_MED_CD_TABELAMEDICA || CHR(39); END IF;
  IF pCAD_MTMD_NOMEFANTASIA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_NOMEFANTASIA LIKE ' || CHR(39) || pCAD_MTMD_NOMEFANTASIA || CHR(39); END IF;
  IF pCAD_MTMD_DESCRICAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_DESCRICAO = ' || CHR(39) || pCAD_MTMD_DESCRICAO || CHR(39); END IF;
  IF pCAD_MTMD_UNIDADE_VENDA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_UNIDADE_VENDA = ' || pCAD_MTMD_UNIDADE_VENDA; END IF;
  IF pCAD_MTMD_UNIDADE_COMPRA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_UNIDADE_COMPRA = ' || pCAD_MTMD_UNIDADE_COMPRA; END IF;
  IF pCAD_MTMD_UNIDADE_CONTROLE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_UNIDADE_CONTROLE = ' || pCAD_MTMD_UNIDADE_CONTROLE; END IF;
  IF pCAD_MTMD_CODMNE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_CODMNE = ' || CHR(39) || pCAD_MTMD_CODMNE || CHR(39); END IF;
  IF pCAD_MTMD_CURVA_ABC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_CURVA_ABC = ' || CHR(39) || pCAD_MTMD_CURVA_ABC || CHR(39); END IF;
  IF pCAD_MTMD_CD_FABRICANTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_CD_FABRICANTE = ' || CHR(39) || pCAD_MTMD_CD_FABRICANTE || CHR(39); END IF;
  IF pCAD_MTMD_FL_FRACIONA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_FL_FRACIONA = ' || pCAD_MTMD_FL_FRACIONA; END IF;
  IF pCAD_MTMD_FL_MANTER_ESTOQUE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_FL_MANTER_ESTOQUE = ' || pCAD_MTMD_FL_MANTER_ESTOQUE; END IF;
  IF pCAD_MTMD_FL_REUTILIZAVEL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_FL_REUTILIZAVEL = ' || pCAD_MTMD_FL_REUTILIZAVEL; END IF;
  IF pCAD_MTMD_DT_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_DT_ATUALIZACAO = ' || CHR(39) || pCAD_MTMD_DT_ATUALIZACAO || CHR(39); END IF;
  IF pCAD_MTMD_CD_RM IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_CD_RM = ' || CHR(39) || pCAD_MTMD_CD_RM || CHR(39); END IF;
 IF pCAD_MTMD_FL_DILUENTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_FL_DILUENTE = ' || pCAD_MTMD_FL_DILUENTE; END IF;
 V_WHERE  := V_WHERE || ' ORDER BY PRODUTO.CAD_MTMD_NOMEFANTASIA';
  V_SELECT := '
  SELECT
     PRODUTO.CAD_MTMD_ID,
     PRODUTO.CAD_MTMD_FILIAL_ID,
     PRODUTO.CAD_MTMD_PRIATI_ID,
     PRODUTO.CAD_MTMD_GRUPO_ID,
     PRODUTO.CAD_MTMD_SUBGRUPO_ID,
     PRODUTO.TIS_MED_CD_TABELAMEDICA,
     FNC_MTMD_SOUNDALIKE(PRODUTO.CAD_MTMD_NOMEFANTASIA,PRODUTO.CAD_MTMD_GRUPO_ID) CAD_MTMD_NOMEFANTASIA,
     PRODUTO.CAD_MTMD_DESCRICAO,
     PRODUTO.CAD_MTMD_UNIDADE_VENDA,
     PRODUTO.CAD_MTMD_UNIDADE_COMPRA,
     PRODUTO.CAD_MTMD_UNIDADE_CONTROLE,
     PRODUTO.CAD_MTMD_CODMNE,
     PRODUTO.CAD_MTMD_CURVA_ABC,
     PRODUTO.CAD_MTMD_CD_FABRICANTE,
     PRODUTO.CAD_MTMD_FL_FRACIONA,
     PRODUTO.CAD_MTMD_FL_ATIVO,
     PRODUTO.CAD_MTMD_FL_MANTER_ESTOQUE,
     PRODUTO.CAD_MTMD_FL_REUTILIZAVEL,
     PRODUTO.CAD_MTMD_DT_ATUALIZACAO,
     PRODUTO.CAD_MTMD_CD_RM,
     PRODUTO.CAD_MTMD_UNIDADE_CONSUMO,
     PRODUTO.CAD_MTMD_UNID_COMPRA_DS,
     PRODUTO.CAD_MTMD_UNID_CONTROLE_DS,
     PRODUTO.CAD_MTMD_UNID_VENDA_DS,
     PRODUTO.CAD_MTMD_FL_BAIXA_AUTOMATICA,
     PRODUTO.MTMD_TP_FRACAO_ID,
     PRODUTO.CAD_MTMD_FL_FATURADO,
     PRODUTO.CAD_MTMD_CD_ANVISA,
     CASE
         WHEN (PRODUTO.MTMD_TP_FRACAO_ID IS NOT NULL) THEN
            (SELECT MTMD_DS_TP_FRACAO FROM TB_MTMD_TIPO_FRACAO WHERE MTMD_TP_FRACAO_ID = PRODUTO.MTMD_TP_FRACAO_ID)
         ELSE NULL
       END  MTMD_DS_TP_FRACAO,
     PRODUTO.CAD_MTMD_FL_MAV,
     CAD_MTMD_CD_GRUPO_ANVISA,
     CAD_MTMD_FL_CONTROLA_LOTE,
     CAD_MTMD_FL_DILUENTE,
     CAD_MTMD_PRIATI_SAL_DSC,
     CAD_MTMD_FORMA_FARMACEUTICA,
     CAD_MTMD_DOSAGEM_PADRONIZADA,
     CAD_MTMD_FL_GELADEIRA MTMD_FL_GELADEIRA,
     CAD_MTMD_FL_PADRAO
  FROM TB_CAD_MTMD_MAT_MED  PRODUTO
  WHERE PRODUTO.CAD_MTMD_FL_ATIVO = 1 ';
  OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
END PRC_CAD_MTMD_MAT_MED_S;