create or replace procedure PRC_INT_AVISOS
  (
pATD_ATE_ID IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_ID%TYPE DEFAULT NULL,
pCAD_PAC_NR_PRONTUARIO IN TB_CAD_PAC_PACIENTE.CAD_PAC_NR_PRONTUARIO%TYPE DEFAULT NULL,
pCAD_PES_NM_PESSOA IN TB_CAD_PES_PESSOA.CAD_PES_NM_PESSOA%TYPE DEFAULT NULL,
pATD_AIC_FL_PAC_ESTADOGRAVE IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_FL_PAC_ESTADOGRAVE%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC %TYPE DEFAULT NULL,
pCAD_SET_DS_SETOR IN TB_CAD_SET_SETOR.CAD_SET_DS_SETOR%TYPE DEFAULT NULL,
pTIS_MSI_CD_TIPOALTA IN TB_TIS_MSI_MOTIVO_SAIDA_INT.TIS_MSI_CD_TIPOALTA%TYPE DEFAULT NULL,
pNAOESTADOGRAVE IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_FL_PAC_ESTADOGRAVE%TYPE DEFAULT NULL,
pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE,
pRN string default null,

  --teste out long,
   io_cursor              OUT PKG_CURSOR.t_cursor) is
  /********************************************************************
  *    Procedure: PRC_INT_AVISOS
  *
  *    Data Alteracao: 20/6/2011   Por: PEDRO
  *
  *    Alteracao: retirado join com a pat
  *
  *    Funcao: Pesquisar avisos
  *
  *******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_SELECT  varchar2(10000);
begin
  V_WHERE := NULL;
  IF pATD_AIC_TP_SITUACAO_PAC IS NOT NULL and pATD_AIC_TP_SITUACAO_PAC != 'C' THEN
    V_WHERE := V_WHERE ||
               ' AND  (AIC.ATD_AIC_TP_SITUACAO_PAC = ' || CHR(39) || pATD_AIC_TP_SITUACAO_PAC || CHR(39) || ')';
  END IF;
  IF pATD_ATE_ID IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ATD.ATD_ATE_ID = ' || pATD_ATE_ID;
  END IF;
  IF pCAD_PAC_NR_PRONTUARIO IS NOT NULL THEN
    V_WHERE := V_WHERE ||
               ' AND PAC.CAD_PAC_NR_PRONTUARIO = ' || pCAD_PAC_NR_PRONTUARIO;
  END IF;

  IF (pCAD_PES_NM_PESSOA <> '%%%') THEN

        V_WHERE := V_WHERE || ' AND PES.CAD_PES_NM_PESSOA LIKE ''%' || pCAD_PES_NM_PESSOA || '%''';
       /*
        IF(length(replace(pCAD_PES_NM_PESSOA,'%','')) <= 3) then
          raise_application_error (-20000, 'A PESQUISA POR NOME DEVE POSSUIR 3 OU MAIS CARACTERES');
        ELSE
        END IF;
      */
  END IF;
  IF pTIS_MSI_CD_TIPOALTA IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND MSI.TIS_MSI_CD_TIPOALTA = ' ||  pTIS_MSI_CD_TIPOALTA;
  END IF;
  IF pCAD_SET_DS_SETOR IS NOT NULL THEN
    V_WHERE := V_WHERE ||
               ' AND SET_IMS.CAD_SET_DS_SETOR = ' || CHR(39) || 'CENTRO CIRURGICO' || CHR(39);
  END IF;
  IF pATD_AIC_FL_PAC_ESTADOGRAVE = 'S' THEN
    V_WHERE := V_WHERE ||
               ' AND AIC.ATD_AIC_FL_PAC_ESTADOGRAVE  = ' || CHR(39) || 'S' || CHR(39);
  END IF;
  IF pNAOESTADOGRAVE = 'S' THEN
    V_WHERE := V_WHERE ||
               ' AND AIC.ATD_AIC_FL_PAC_ESTADOGRAVE IS NULL OR AIC.ATD_AIC_FL_PAC_ESTADOGRAVE = ' || CHR(39) || 'N' || CHR(39);
  END IF;
  IF pATD_AIC_TP_SITUACAO_PAC = 'A' THEN
    V_WHERE := V_WHERE ||
               ' AND (INA.ATD_INA_DT_ALTA_ADM BETWEEN (SYSDATE - 15) AND SYSDATE )';
  ELSE 
    IF(pATD_AIC_TP_SITUACAO_PAC = 'I' and pATD_ATE_ID IS NULL AND pCAD_PAC_NR_PRONTUARIO IS NULL) THEN
        V_WHERE := V_WHERE ||
               ' AND ((ATD.ATD_ATE_TP_PACIENTE = ''I'' AND (INA.ATD_INA_DT_ALTA_ADM IS NULL OR INA.ATD_INA_DT_ALTA_ADM > SYSDATE -90)) or (ATD.ATD_ATE_TP_PACIENTE = ''E'' AND ATD.ATD_ATE_DT_ATENDIMENTO > SYSDATE -90) )';
    END IF;
    IF pATD_AIC_TP_SITUACAO_PAC = 'C' THEN
       V_WHERE := V_WHERE || ' AND (INA.ATD_INA_DT_ALTA_ADM IS NULL AND INA.ATD_INA_DT_ALTA_CLINICA IS NOT NULL )';
  END IF;
  END IF;
  
  V_SELECT := 'SELECT DISTINCT
               PES.CAD_PES_NM_PESSOA,
               TRUNC(PES.CAD_PES_DT_NASCIMENTO) CAD_PES_DT_NASCIMENTO,
               ATD.ATD_ATE_ID,
               ATD.ATD_ATE_DT_ATENDIMENTO,
               fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA) ALTA_CLI,
               SETOR_IML.CAD_SET_DS_SETOR,
               IML_QLE.CAD_QLE_NR_QUARTO,
               IML_QLE.CAD_QLE_NR_LEITO,

               PAC.CAD_PAC_NR_PRONTUARIO,
               DECODE(PES.CAD_PES_TP_SEXO,'||CHR(39)||'M'||CHR(39)||','||CHR(39)||'MASCULINO'||CHR(39)||','||CHR(39)||'F'||CHR(39)||','||CHR(39)||'FEMININO'||CHR(39)||') CAD_PES_TP_SEXO,
               CNV.CAD_CNV_CD_HAC_PRESTADOR,
               CNV.CAD_CNV_NM_FANTASIA,
               PLA.CAD_PLA_CD_PLANO_HAC,
               PAC.CAD_PAC_CD_CREDENCIAL,
               DECODE(ATD_ATE_TP_PACIENTE,'||CHR(39)||'I'||CHR(39)||','||CHR(39)||'INTERNO'||CHR(39)||','||CHR(39)||'E'||CHR(39)||','||CHR(39)||'EXTERNO'||CHR(39)||') ATD_ATE_TP_PACIENTE,
               MSI.TIS_MSI_DS_MOTIVOSAIDAINT,
               MSI.TIS_MSI_CD_TIPOALTA,
               TRUNC(INA.ATD_INA_DT_ALTA_ADM) ATD_INA_DT_ALTA_ADM,
               INA.ATD_INA_HR_ALTA_ADM,
               fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_ADM,INA.ATD_INA_HR_ALTA_ADM) ALTA_ADM,
               TRUNC(INA.ATD_INA_DT_ALTA_CLINICA) ATD_INA_DT_ALTA_CLINICA,
               INA.ATD_INA_HR_ALTA_CLINICA,

               PRO_ALTA.CAD_PRO_NM_NOME CAD_PRO_NM_NOME_ALTA,
               FLOOR(FLOOR(MONTHS_BETWEEN(DECODE(INA.ATD_INA_DT_ALTA_ADM,NULL,ATD.ATD_ATE_DT_ATENDIMENTO,INA.ATD_INA_DT_ALTA_ADM), PES.CAD_PES_DT_NASCIMENTO)) / 12) idade,
               SET_IMS.CAD_SET_DS_SETOR SETOR_IMS,
               TRUNC(SET_IMS.ATD_IMS_DT_SAIDA) ATD_IMS_DT_SAIDA,
               SET_IMS.ATD_IMS_HR_SAIDA,
               SET_IMS.ATD_IMS_DS_OBSERVACAO,
               CLC_IMC.CAD_PES_NM_PESSOA CLINICA,
                AIC.ATD_AIC_FL_PAC_ESTADOGRAVE,
               AIC.ATD_AIC_TP_SITUACAO_PAC,
               COUNT(IDR.ATD_ATE_ID) TOT_RN
  FROM
                TB_ATD_ATE_ATENDIMENTO    ATD
  JOIN          TB_CAD_PAC_PACIENTE       PAC  ON            PAC.CAD_PAC_ID_PACIENTE = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
  JOIN          TB_CAD_PES_PESSOA         PES  ON            PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
  JOIN          TB_CAD_CNV_CONVENIO       CNV  ON            CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
  JOIN          TB_CAD_PLA_PLANO          PLA  ON            PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
  JOIN          TB_ATD_AIC_ATE_INT_COMPL  AIC  ON            AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
 LEFT JOIN  (    SELECT   QLE.CAD_QLE_ID, QLE.CAD_SET_ID , QLE.CAD_QLE_NR_QUARTO, QLE.CAD_QLE_NR_LEITO,
                          IML.ATD_ATE_ID, QLE.TIS_TAC_CD_TIPO_ACOMODACAO, QLE.CAD_QLE_TP_QUARTO_LEITO ,
                          IML.ATD_IML_DT_ENTRADA, IML.ATD_IML_HR_ENTRADA
                 FROM      TB_ATD_IML_INT_MOV_LEITO IML
                 LEFT JOIN TB_CAD_QLE_QUARTO_LEITO QLE
                 ON        QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
                 JOIN      TB_ATD_ATE_ATENDIMENTO ATD2
                 ON        ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                 WHERE       FNC_JUNTAR_DATA_HORA(IML.ATD_IML_DT_ENTRADA,IML.ATD_IML_HR_ENTRADA) =
                                         (SELECT MAX(FNC_JUNTAR_DATA_HORA(IML3.ATD_IML_DT_ENTRADA,IML3.ATD_IML_HR_ENTRADA)) FROM TB_ATD_IML_INT_MOV_LEITO IML3
                                                       WHERE IML3.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML3.ATD_IML_FL_STATUS = '||CHR(39)||'A'||CHR(39)||')
              )  IML_QLE
  ON IML_QLE.ATD_ATE_ID = ATD.ATD_ATE_ID
  LEFT JOIN     TB_CAD_SET_SETOR          SETOR_IML  ON            SETOR_IML.CAD_SET_ID        = IML_QLE.CAD_SET_ID
  LEFT JOIN     TB_ATD_INA_INT_ALTA       INA  ON INA.ATD_ATE_ID          = ATD.ATD_ATE_ID
  LEFT JOIN     TB_CAD_PRO_PROFISSIONAL PRO_ALTA ON PRO_ALTA.CAD_PRO_ID_PROFISSIONAL = INA.CAD_PRO_ID_PROFISSIONAL
  LEFT JOIN     TB_TIS_MSI_MOTIVO_SAIDA_INT MSI  ON MSI.TIS_MSI_CD_MOTIVOSAIDAINT = INA.TIS_MSI_CD_MOTIVOSAIDAINT
  LEFT JOIN     TB_ATD_IMS_INT_MOV_SETOR IMS     ON IMS.ATD_ATE_ID    = ATD.ATD_ATE_ID
  AND           IMS.ATD_IMS_HR_SAIDA IS NULL
  AND           IMS.ATD_IMS_DT_SAIDA IS NULL
  LEFT JOIN (   SELECT SETORR.CAD_SET_DS_SETOR, ATD2.ATD_ATE_ID,IMS.ATD_IMS_DT_SAIDA, IMS.ATD_IMS_HR_SAIDA, IMS.ATD_IMS_DS_OBSERVACAO
                FROM TB_ATD_IMS_INT_MOV_SETOR IMS
                JOIN TB_ATD_ATE_ATENDIMENTO ATD2                ON ATD2.ATD_ATE_ID = IMS.ATD_ATE_ID
                JOIN TB_CAD_SET_SETOR SETORR                ON SETORR.CAD_SET_ID = IMS.CAD_SET_ID_SETOR
                WHERE
                    ((ATD2.ATD_ATE_TP_PACIENTE = '||CHR(39)||'E'||CHR(39)||' AND ATD2.ATD_ATE_DT_ATENDIMENTO = TRUNC(SYSDATE))
                      OR (IMS.ATD_IMS_DT_SAIDA IS NULL))
                AND IMS.ATD_IMS_FL_STATUS = '||CHR(39)||'A'||CHR(39)||'
                AND (ATD2.CAD_LAT_ID_LOCAL_ATENDIMENTO = 29)
             ) SET_IMS
  ON SET_IMS.ATD_ATE_ID = ATD.ATD_ATE_ID
  LEFT JOIN (   SELECT PES_CLC.CAD_PES_NM_PESSOA, IMC.ATD_ATE_ID
                FROM TB_ATD_IMC_INT_MOV_CLINICA IMC
                JOIN TB_CAD_CLC_CLINICA_CREDENCIADA CLC                ON   CLC.CAD_CLC_ID = IMC.CAD_CLC_ID
                JOIN TB_CAD_PES_PESSOA PES_CLC                ON   PES_CLC.CAD_PES_ID_PESSOA = CLC.CAD_PES_ID_PESSOA
                JOIN TB_ATD_ATE_ATENDIMENTO ATD3                ON ATD3.ATD_ATE_ID = IMC.ATD_ATE_ID
                WHERE
                    IMC.ATD_ATE_ID = ATD3.ATD_ATE_ID
                AND IMC.ATD_IMC_DT_SAIDA IS NULL
                AND IMC.ATD_IMC_HR_SAIDA IS NULL
                AND (ATD3.CAD_LAT_ID_LOCAL_ATENDIMENTO = 29)
             )   CLC_IMC
   ON CLC_IMC.ATD_ATE_ID = ATD.ATD_ATE_ID
   LEFT JOIN    TB_ATD_IDR_INT_DADOS_RN IDR
   ON           IDR.ATD_ATE_ID    = ATD.ATD_ATE_ID
   WHERE
       (ATD.ATD_ATE_TP_PACIENTE IN ('||CHR(39)||'I'||CHR(39)||','||CHR(39)||'E'||CHR(39)||'))
   AND (ATD.ATD_ATE_FL_STATUS = '||CHR(39)||'A'||CHR(39)||')
    AND ((ATD.ATD_ATE_TP_PACIENTE = '||CHR(39)||'E'||CHR(39)||' AND ATD.ATD_ATE_DT_ATENDIMENTO = TRUNC(SYSDATE))
    ';
    IF pCAD_SET_DS_SETOR IS NOT NULL THEN --CENTRO CIRURGICO
       V_SELECT := V_SELECT ||  ' OR (ATD.ATD_ATE_TP_PACIENTE = ' || CHR(39) || 'I' || CHR(39) || ' AND AIC.ATD_AIC_TP_SITUACAO_PAC = ' || CHR(39) || 'I' || CHR(39)|| '))';
               ELSE
       V_SELECT := V_SELECT ||  ' OR (NULL IS NULL))';
  END IF;
  V_SELECT := V_SELECT || '
   AND (ATD.CAD_UNI_ID_UNIDADE = ' ||pCAD_UNI_ID_UNIDADE ||')
   AND (ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = 29)'
       || V_WHERE ||
       ' GROUP BY  PES.CAD_PES_NM_PESSOA,
               TRUNC(PES.CAD_PES_DT_NASCIMENTO) ,
               ATD.ATD_ATE_ID,
               ATD.ATD_ATE_DT_ATENDIMENTO,
               fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA) ,
               SETOR_IML.CAD_SET_DS_SETOR,
               IML_QLE.CAD_QLE_NR_QUARTO,
               IML_QLE.CAD_QLE_NR_LEITO,

               PAC.CAD_PAC_NR_PRONTUARIO,
               DECODE(PES.CAD_PES_TP_SEXO,'||CHR(39)||'M'||CHR(39)||','||CHR(39)||'MASCULINO'||CHR(39)||','||CHR(39)||'F'||CHR(39)||','||CHR(39)||'FEMININO'||CHR(39)||') ,
               CNV.CAD_CNV_CD_HAC_PRESTADOR,
               CNV.CAD_CNV_NM_FANTASIA,
               PLA.CAD_PLA_CD_PLANO_HAC,
               PAC.CAD_PAC_CD_CREDENCIAL,
               DECODE(ATD_ATE_TP_PACIENTE,'||CHR(39)||'I'||CHR(39)||','||CHR(39)||'INTERNO'||CHR(39)||','||CHR(39)||'E'||CHR(39)||','||CHR(39)||'EXTERNO'||CHR(39)||') ,
               MSI.TIS_MSI_DS_MOTIVOSAIDAINT,
               MSI.TIS_MSI_CD_TIPOALTA,
               TRUNC(INA.ATD_INA_DT_ALTA_ADM) ,
               INA.ATD_INA_HR_ALTA_ADM,
               fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_ADM,INA.ATD_INA_HR_ALTA_ADM) ,
               TRUNC(INA.ATD_INA_DT_ALTA_CLINICA) ,
               INA.ATD_INA_HR_ALTA_CLINICA,

               PRO_ALTA.CAD_PRO_NM_NOME ,
               FLOOR(FLOOR(MONTHS_BETWEEN(DECODE(INA.ATD_INA_DT_ALTA_ADM,NULL,ATD.ATD_ATE_DT_ATENDIMENTO,INA.ATD_INA_DT_ALTA_ADM), PES.CAD_PES_DT_NASCIMENTO)) / 12) ,
               SET_IMS.CAD_SET_DS_SETOR ,
               TRUNC(SET_IMS.ATD_IMS_DT_SAIDA) ,
               SET_IMS.ATD_IMS_HR_SAIDA,
               SET_IMS.ATD_IMS_DS_OBSERVACAO,
               CLC_IMC.CAD_PES_NM_PESSOA ,
                AIC.ATD_AIC_FL_PAC_ESTADOGRAVE,
               AIC.ATD_AIC_TP_SITUACAO_PAC
      
  HAVING '||CHR(39)|| pRN || CHR(39) || 'IS NULL OR  COUNT(IDR.ATD_ATE_ID) > 0  ORDER BY SETOR_IML.CAD_SET_DS_SETOR,DECODE(fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA),NULL,ATD.ATD_ATE_DT_ATENDIMENTO,fnc_juntar_data_hora(INA.ATD_INA_DT_ALTA_CLINICA,INA.ATD_INA_HR_ALTA_CLINICA))';
 --  teste:= V_SELECT;
  OPEN v_cursor FOR
    V_SELECT;
  -- select 1 from dual;
  io_cursor := v_cursor;
end PRC_INT_AVISOS;
