CREATE OR REPLACE PROCEDURE PRC_MTMD_MOV_MOVIMENTACAO_S
  (
     pMTMD_MOV_ID                  IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_MOV_ID%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_MTMD_MOV_MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE           IN TB_MTMD_MOV_MOVIMENTACAO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_SET_ID                   IN TB_MTMD_MOV_MOVIMENTACAO.CAD_SET_ID%type DEFAULT NULL,
     pMTMD_LOTEST_ID               IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_LOTEST_ID%type DEFAULT NULL,
     pCAD_MTMD_ID                  IN TB_MTMD_MOV_MOVIMENTACAO.CAD_MTMD_ID%type DEFAULT NULL,
     pCAD_MTMD_TPMOV_ID            IN TB_MTMD_MOV_MOVIMENTACAO.CAD_MTMD_TPMOV_ID%type DEFAULT NULL,
     pCAD_MTMD_SUBTP_ID            IN TB_MTMD_MOV_MOVIMENTACAO.CAD_MTMD_SUBTP_ID%type DEFAULT NULL,
     pMTMD_MOV_DATA                IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_MOV_DATA%type DEFAULT NULL,
     pMTMD_MOV_QTDE                IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_MOV_QTDE%type DEFAULT NULL,
     pMTMD_MOV_FL_FINALIZADO       IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_MOV_FL_FINALIZADO%type DEFAULT NULL,
     pATD_ATE_ID                   IN TB_MTMD_MOV_MOVIMENTACAO.ATD_ATE_ID%type DEFAULT NULL,
     pATD_ATE_TP_PACIENTE          IN TB_MTMD_MOV_MOVIMENTACAO.ATD_ATE_TP_PACIENTE%type DEFAULT NULL,
     pCAD_MTMD_FILIAL_ID           IN TB_MTMD_MOV_MOVIMENTACAO.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
     pMTMD_REQ_ID                  IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_REQ_ID%type DEFAULT NULL,
     pMTMD_MOV_FL_ESTORNO          IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_MOV_FL_ESTORNO%TYPE DEFAULT NULL,
     pCONSUMO_PACIENTE             IN VARCHAR2 DEFAULT NULL,
     pMTMD_MOV_FL_FATURADO         IN TB_MTMD_MOV_MOVIMENTACAO.MTMD_MOV_FL_FATURADO%TYPE DEFAULT NULL,
     io_cursor                     OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_MTMD_MOV_MOVIMENTACAO_S
  *
  *    Data Criacao: 	06/2009   Por: RICARDO COSTA
  *    Data Alteracao:	02/03/2010  Por: RICARDO COSTA
  *         Alterac?o: RETIRADA FUNC?O DATA DE ULTIMO FORNECIMENTO
  *                    RETIRADA PESQUISA USUARIO ESTORNO
  *                    DATA DE PESQUISA LIMITADA A 30 DIAS
  *                    POIS DATA MAIORES QUE ESSAS DEVEM SER PESQUISADAS NA TELA DE MOVIMENTAC?O
  *                    E OS ITENS POSTERIORES A 30 DIAS JA DEVER?O ESTAR FATURADOS
  *    Data Alteracao:	15/03/2010  Por: RICARDO COSTA
  *         Alterac?o: ADICIONADO FLAG DE FATURAMENTO
  *    Data Alteracao:	02/06/2010  Por: RICARDO COSTA
  *         Alterac?o: ALTERADO FORMA DE PESQUISA LIMITADO POR DATA, N?O E QTDE DE DIAS FIXO  E PASSADO POR PARAMETRO
  *    Data Alteracao:	09/06/2010  Por: RICARDO COSTA
  *         Alterac?o: Acrescentado o tipo de movimento 35, para consulta do centro cirurgico
  *    Data Alteracao:	06/07/2011  Por: Andre Souza Monaco
  *         Alterac?o: Padronizac?o dos filtros por string
  *    Data Alteracao:  24/10/2017  Por: Andre S. Monaco
  *         Alteracao:  Adicao funcao SOUND ALIKE na descricao
  *
  *    Funcao: RETORNA MOVIMENTAC?O DE PRODUTOS, ESTA SENDO UTILIZADA SO PARA RETORNA CONSUMO DO PACIENTE/ CENTRO CIRURGICO
  *            POR ISSO **** LIMITA A QUANTIDADE DE DIAS ***** ,
  *            PARA N?O FICAR MUITO LENTA PARA PACIENTES INTERNADO A  MUITO TEMPO
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  /*FRACIONADO     CONSTANT NUMBER := 1;
  NAO_FRACIONADO CONSTANT NUMBER := 0;
  CONVERSAO_INTEIRO_FRACIONADO   CONSTANT NUMBER := 32;
  CONSUMO_FRACIONADO             CONSTANT NUMBER := 14;
  CONSUMO_NAO_FRACIONADO         CONSTANT NUMBER :=11;
  CONSUMO_NAO_FATURADO           CONSTANT NUMBER :=18;
  SIM            CONSTANT NUMBER := 1;
  NAO            CONSTANT NUMBER := 0;
  dData          DATE;*/
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
  begin
  V_WHERE := NULL;
  IF pMTMD_MOV_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND   MOVIMENTACAO.MTMD_MOV_ID = ' || pMTMD_MOV_ID; END IF;
  IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
  IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
  IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
  IF pCAD_MTMD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.CAD_MTMD_ID = ' || pCAD_MTMD_ID; END IF;
  IF pCAD_MTMD_TPMOV_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.CAD_MTMD_TPMOV_ID = ' || pCAD_MTMD_TPMOV_ID; END IF;
  IF pCAD_MTMD_SUBTP_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.CAD_MTMD_SUBTP_ID = ' || pCAD_MTMD_SUBTP_ID; END IF;
  IF pMTMD_MOV_DATA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.MTMD_MOV_DATA = ' || CHR(39) || pMTMD_MOV_DATA || CHR(39); END IF;
  IF pMTMD_MOV_QTDE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.MTMD_MOV_QTDE = ' || pMTMD_MOV_QTDE; END IF;
  IF pMTMD_MOV_FL_FINALIZADO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.MTMD_MOV_FL_FINALIZADO = ' || pMTMD_MOV_FL_FINALIZADO; END IF;
  IF pATD_ATE_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.ATD_ATE_ID = ' || pATD_ATE_ID; END IF;
  IF pATD_ATE_TP_PACIENTE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.ATD_ATE_TP_PACIENTE = ' || CHR(39) || pATD_ATE_TP_PACIENTE || CHR(39); END IF;
  IF pMTMD_REQ_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.MTMD_REQ_ID = ' || pMTMD_REQ_ID; END IF;
  IF pMTMD_MOV_FL_ESTORNO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.MTMD_MOV_FL_ESTORNO = ' || pMTMD_MOV_FL_ESTORNO; END IF;
  IF pMTMD_MOV_FL_FATURADO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.MTMD_MOV_FL_FATURADO = ' || pMTMD_MOV_FL_FATURADO; END IF;
  IF (pCONSUMO_PACIENTE IS NOT NULL AND pCONSUMO_PACIENTE = 'S') THEN V_WHERE:= V_WHERE || ' AND (MOVIMENTACAO.CAD_MTMD_TPMOV_ID = 2 AND MOVIMENTACAO.CAD_MTMD_SUBTP_ID IN (11, 14, 18, 24, 25, 26, 35, 60)) '; END IF;
  IF (pCAD_MTMD_FILIAL_ID IS NOT NULL AND pCONSUMO_PACIENTE IS NULL) THEN V_WHERE:= V_WHERE || ' AND MOVIMENTACAO.CAD_MTMD_FILIAL_ID = ' || pCAD_MTMD_FILIAL_ID; END IF;
  /*AND   ( (pCAD_MTMD_FILIAL_ID         is null OR NOT pCONSUMO_PACIENTE is null)
           OR
          (MOVIMENTACAO.CAD_MTMD_FILIAL_ID = FNC_MTMD_RETORNA_FILIAL( PRODUTO.CAD_MTMD_ID, pCAD_MTMD_FILIAL_ID))
        ) */
  V_WHERE  := V_WHERE || ' ORDER BY MOVIMENTACAO.MTMD_MOV_DATA DESC, PRODUTO.CAD_MTMD_NOMEFANTASIA ASC';
  V_SELECT := '
  SELECT
       MOVIMENTACAO.MTMD_MOV_ID,
       MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       MOVIMENTACAO.CAD_UNI_ID_UNIDADE,
       MOVIMENTACAO.CAD_SET_ID,
       MOVIMENTACAO.MTMD_REQ_ID,
       MOVIMENTACAO.MTMD_LOTEST_ID,
       MOVIMENTACAO.CAD_MTMD_ID,
       MOVIMENTACAO.CAD_MTMD_TPMOV_ID,
       MOVIMENTACAO.CAD_MTMD_SUBTP_ID,
       MOVIMENTACAO.MTMD_MOV_DATA,
       MOVIMENTACAO.MTMD_MOV_QTDE,
       MOVIMENTACAO.MTMD_MOV_FL_FINALIZADO,
       MOVIMENTACAO.ATD_ATE_ID,
       MOVIMENTACAO.ATD_ATE_TP_PACIENTE,
       MOVIMENTACAO.MTMD_MOV_FL_FATURADO,
       MOVIMENTACAO.CAD_MTMD_FILIAL_ID,
       MOVIMENTACAO.MTMD_TP_FRACAO_ID,
       CASE
          WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = 14 AND PRODUTO.CAD_MTMD_FL_FRACIONA = 0 ) THEN FNC_MTMD_SOUNDALIKE(PRODUTO.CAD_MTMD_NOMEFANTASIA,PRODUTO.CAD_MTMD_GRUPO_ID)||'' (1) ''
          ELSE FNC_MTMD_SOUNDALIKE(PRODUTO.CAD_MTMD_NOMEFANTASIA,PRODUTO.CAD_MTMD_GRUPO_ID)
       END CAD_MTMD_NOMEFANTASIA,
       PRODUTO.CAD_MTMD_UNIDADE_VENDA,
       CASE
             WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = 11 AND PRODUTO.CAD_MTMD_FL_FRACIONA = 1 ) THEN (0) -- FRACIONADO PARA INTEIRO
             ELSE ( PRODUTO.CAD_MTMD_FL_FRACIONA  )
       END CAD_MTMD_FL_FRACIONA,
       CASE
         WHEN (MOVIMENTACAO.MTMD_TP_FRACAO_ID IS NOT NULL) THEN
            TO_CHAR(MOVIMENTACAO.MTMD_QTD_CONVERTIDA)||'' ''||(SELECT MTMD_DS_TP_FRACAO FROM TB_MTMD_TIPO_FRACAO WHERE MTMD_TP_FRACAO_ID = MOVIMENTACAO.MTMD_TP_FRACAO_ID)
         WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = 14 AND PRODUTO.CAD_MTMD_FL_FRACIONA = 0 ) THEN ''FRACIONADO''
         WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID IN (11,18,60) AND PRODUTO.CAD_MTMD_FL_FRACIONA = 1 ) THEN ''INTEIRO''
         ELSE NULL
       END  DS_QTDE_CONVERTIDA,
       (CASE
           WHEN PRODUTO.CAD_MTMD_FL_FRACIONA = 1 AND MOVIMENTACAO.CAD_MTMD_SUBTP_ID IN (14, 35) THEN
              TO_CHAR( MOVIMENTACAO.MTMD_MOV_QTDE )||''/''||TO_CHAR( PRODUTO.CAD_MTMD_UNIDADE_VENDA)
           ELSE
              TO_CHAR( MOVIMENTACAO.MTMD_MOV_QTDE )
        END)  DS_QTDE_CONSUMO,
       NULL MTMD_DT_RESSUPRIMENTO,
       SETOR.CAD_SET_DS_SETOR,
       UNIDADE.CAD_UNI_DS_UNIDADE,
       SUBTP.CAD_MTMD_SUBTP_DESCRICAO,
       SUBTP.CAD_MTMD_FL_FATURA,
       USU_MOV.SEG_USU_DS_NOME DS_USUARIO
    FROM TB_MTMD_MOV_MOVIMENTACAO       MOVIMENTACAO,
         TB_CAD_MTMD_MAT_MED            PRODUTO,
         TB_CAD_SET_SETOR               SETOR,
         TB_CAD_UNI_UNIDADE             UNIDADE,
         TB_CAD_MTMD_SUBTP_MOVIMENTACAO SUBTP,
         TB_SEG_USU_USUARIO             USU_MOV
    WHERE MOVIMENTACAO.CAD_MTMD_ID       = PRODUTO.CAD_MTMD_ID
    AND   SETOR.CAD_SET_ID               = MOVIMENTACAO.CAD_SET_ID
    AND   UNIDADE.CAD_UNI_ID_UNIDADE     = MOVIMENTACAO.CAD_UNI_ID_UNIDADE
    AND   SUBTP.CAD_MTMD_SUBTP_ID        = MOVIMENTACAO.CAD_MTMD_SUBTP_ID
    AND   USU_MOV.SEG_USU_ID_USUARIO(+)  = MOVIMENTACAO.SEG_USU_ID_USUARIO
    AND   ( MOVIMENTACAO.CAD_SET_ID = 61 OR  MOVIMENTACAO.mtmd_mov_data >= TRUNC(SYSDATE) - 30) ';
    OPEN v_cursor FOR
    V_SELECT || V_WHERE ;
    io_cursor := v_cursor;
    /*SELECT
       MOVIMENTACAO.MTMD_MOV_ID,
       MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       MOVIMENTACAO.CAD_UNI_ID_UNIDADE,
       MOVIMENTACAO.CAD_SET_ID,
       MOVIMENTACAO.MTMD_REQ_ID,
       MOVIMENTACAO.MTMD_LOTEST_ID,
       MOVIMENTACAO.CAD_MTMD_ID,
       MOVIMENTACAO.CAD_MTMD_TPMOV_ID,
       MOVIMENTACAO.CAD_MTMD_SUBTP_ID,
       MOVIMENTACAO.MTMD_MOV_DATA,
       MOVIMENTACAO.MTMD_MOV_QTDE,
       MOVIMENTACAO.MTMD_MOV_FL_FINALIZADO,
       MOVIMENTACAO.ATD_ATE_ID,
       MOVIMENTACAO.ATD_ATE_TP_PACIENTE,
       MOVIMENTACAO.MTMD_MOV_FL_FATURADO,
       MOVIMENTACAO.CAD_MTMD_FILIAL_ID,
       MOVIMENTACAO.MTMD_TP_FRACAO_ID,
       CASE
          WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = CONSUMO_FRACIONADO AND PRODUTO.CAD_MTMD_FL_FRACIONA = NAO ) THEN PRODUTO.CAD_MTMD_NOMEFANTASIA||' (FRACIONADO) '
          ELSE PRODUTO.CAD_MTMD_NOMEFANTASIA
       END CAD_MTMD_NOMEFANTASIA,
       PRODUTO.CAD_MTMD_UNIDADE_VENDA,
       -- PRODUTO.CAD_MTMD_FL_FRACIONA,
       CASE
             WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = CONSUMO_NAO_FRACIONADO AND PRODUTO.CAD_MTMD_FL_FRACIONA = SIM ) THEN ( NAO_FRACIONADO ) -- FRACIONADO PARA INTEIRO
             ELSE ( PRODUTO.CAD_MTMD_FL_FRACIONA  )
       END CAD_MTMD_FL_FRACIONA,
       CASE
         WHEN (MOVIMENTACAO.MTMD_TP_FRACAO_ID IS NOT NULL) THEN
            TO_CHAR(MOVIMENTACAO.MTMD_QTD_CONVERTIDA)||' '||(SELECT MTMD_DS_TP_FRACAO FROM TB_MTMD_TIPO_FRACAO WHERE MTMD_TP_FRACAO_ID = MOVIMENTACAO.MTMD_TP_FRACAO_ID)
         WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = CONSUMO_FRACIONADO AND PRODUTO.CAD_MTMD_FL_FRACIONA = NAO ) THEN 'FRACIONADO'
         WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = CONSUMO_NAO_FRACIONADO AND PRODUTO.CAD_MTMD_FL_FRACIONA = SIM ) THEN 'INTEIRO'
         WHEN ( MOVIMENTACAO.CAD_MTMD_SUBTP_ID = CONSUMO_NAO_FATURADO   AND PRODUTO.CAD_MTMD_FL_FRACIONA = SIM ) THEN 'INTEIRO'
         ELSE NULL
       END  DS_QTDE_CONVERTIDA,
       (CASE
           WHEN PRODUTO.CAD_MTMD_FL_FRACIONA = SIM AND MOVIMENTACAO.CAD_MTMD_SUBTP_ID IN (14, 35 ) THEN
              TO_CHAR( MOVIMENTACAO.MTMD_MOV_QTDE )||'/'||TO_CHAR( PRODUTO.CAD_MTMD_UNIDADE_VENDA)
           ELSE
              TO_CHAR( MOVIMENTACAO.MTMD_MOV_QTDE )
        END)  DS_QTDE_CONSUMO,
       NULL \*
       FNC_MTMD_DATA_ULT_FORNECIMENTO(MOVIMENTACAO.CAD_MTMD_ID,          MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                                      MOVIMENTACAO.CAD_UNI_ID_UNIDADE,   MOVIMENTACAO.CAD_SET_ID,
                                      MOVIMENTACAO.CAD_MTMD_FILIAL_ID) *\ MTMD_DT_RESSUPRIMENTO,
       SETOR.CAD_SET_DS_SETOR,
       UNIDADE.CAD_UNI_DS_UNIDADE,
       SUBTP.CAD_MTMD_SUBTP_DESCRICAO,
       SUBTP.CAD_MTMD_FL_FATURA,
       USU_MOV.SEG_USU_DS_NOME DS_USUARIO
--       USU_ESTORNO.SEG_USU_DS_NOME DS_USUARIO_ESTORNO
    FROM TB_MTMD_MOV_MOVIMENTACAO       MOVIMENTACAO,
         TB_CAD_MTMD_MAT_MED            PRODUTO,
         TB_CAD_SET_SETOR               SETOR,
         TB_CAD_UNI_UNIDADE             UNIDADE,
         TB_CAD_MTMD_SUBTP_MOVIMENTACAO SUBTP,
         TB_SEG_USU_USUARIO             USU_MOV
--         TB_SEG_USU_USUARIO             USU_ESTORNO
    WHERE (pMTMD_MOV_ID                  is null OR MOVIMENTACAO.MTMD_MOV_ID = pMTMD_MOV_ID)
    AND   (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
    AND   (pCAD_UNI_ID_UNIDADE           is null OR MOVIMENTACAO.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
    AND   (pCAD_SET_ID                   is null OR MOVIMENTACAO.CAD_SET_ID = pCAD_SET_ID)
    AND   (pCAD_MTMD_ID                  is null OR MOVIMENTACAO.CAD_MTMD_ID = pCAD_MTMD_ID)
    AND   (pCAD_MTMD_TPMOV_ID            is null OR MOVIMENTACAO.CAD_MTMD_TPMOV_ID = pCAD_MTMD_TPMOV_ID)
    AND   (pCAD_MTMD_SUBTP_ID            is null OR MOVIMENTACAO.CAD_MTMD_SUBTP_ID = pCAD_MTMD_SUBTP_ID)
    AND   (pMTMD_MOV_DATA                is null OR MOVIMENTACAO.MTMD_MOV_DATA >= pMTMD_MOV_DATA)
    AND   (pMTMD_MOV_QTDE                is null OR MOVIMENTACAO.MTMD_MOV_QTDE = pMTMD_MOV_QTDE)
    AND   (pMTMD_MOV_FL_FINALIZADO       is null OR MOVIMENTACAO.MTMD_MOV_FL_FINALIZADO = pMTMD_MOV_FL_FINALIZADO)
    AND   (pATD_ATE_ID                   is null OR MOVIMENTACAO.ATD_ATE_ID = pATD_ATE_ID)
    AND   (pATD_ATE_TP_PACIENTE          is null OR MOVIMENTACAO.ATD_ATE_TP_PACIENTE = pATD_ATE_TP_PACIENTE)
    AND   (pMTMD_REQ_ID                  is null OR MOVIMENTACAO.MTMD_REQ_ID = pMTMD_REQ_ID)
    -- AND   (pCONSUMO_PACIENTE is null OR (MOVIMENTACAO.CAD_MTMD_FILIAL_ID = FNC_MTMD_RETORNA_FILIAL( PRODUTO.CAD_MTMD_ID, pCAD_MTMD_FILIAL_ID) OR MOVIMENTACAO.CAD_MTMD_FILIAL_ID = 4))
    AND   ( (pCAD_MTMD_FILIAL_ID         is null OR NOT pCONSUMO_PACIENTE is null)
             OR
            (MOVIMENTACAO.CAD_MTMD_FILIAL_ID = FNC_MTMD_RETORNA_FILIAL( PRODUTO.CAD_MTMD_ID, pCAD_MTMD_FILIAL_ID))
          )
    -- subtipo 18, 35 foi colocado para centro cirurgico
    AND   (pCONSUMO_PACIENTE             is null OR (MOVIMENTACAO.CAD_MTMD_TPMOV_ID = 2 AND (MOVIMENTACAO.CAD_MTMD_SUBTP_ID IN (11, 14, 18, 24, 25, 26, 35))))
    AND   (pMTMD_MOV_FL_ESTORNO          IS NULL OR MOVIMENTACAO.mtmd_mov_fl_estorno = pMTMD_MOV_FL_ESTORNO)
    AND   (pMTMD_MOV_FL_FATURADO         IS NULL OR MOVIMENTACAO.mtmd_mov_fl_faturado = pMTMD_MOV_FL_FATURADO)
    AND   MOVIMENTACAO.CAD_MTMD_ID       = PRODUTO.CAD_MTMD_ID
    AND   SETOR.CAD_SET_ID               = MOVIMENTACAO.CAD_SET_ID
    AND   UNIDADE.CAD_UNI_ID_UNIDADE     = MOVIMENTACAO.CAD_UNI_ID_UNIDADE
    AND   SUBTP.CAD_MTMD_SUBTP_ID        = MOVIMENTACAO.CAD_MTMD_SUBTP_ID
    AND   USU_MOV.SEG_USU_ID_USUARIO(+)  = MOVIMENTACAO.SEG_USU_ID_USUARIO
    AND   ( MOVIMENTACAO.CAD_SET_ID = 61 OR  MOVIMENTACAO.mtmd_mov_data     >= TRUNC(SYSDATE) - 30) -- LIMITA DATA DE MOVIMENTACAO/ MENOS PARA O CENTRO CIRURGICO
    -- AND   USU_ESTORNO.SEG_USU_ID_USUARIO(+)     = MOVIMENTACAO.MTMD_ID_USUARIO_ESTORNO NAO EXISTE MAIS USUARIO DE ESTORNO
    ORDER BY MOVIMENTACAO.MTMD_MOV_DATA DESC, PRODUTO.CAD_MTMD_NOMEFANTASIA ASC;*/
    --io_cursor := v_cursor;
  end PRC_MTMD_MOV_MOVIMENTACAO_S;