CREATE OR REPLACE PROCEDURE PRC_MTMD_REQ_REQ_ULTIMAS
  (
     pQtdUltimas            INTEGER,
     pMTMD_REQ_FL_STATUS    IN TB_MTMD_REQ_REQUISICAO.MTMD_REQ_FL_STATUS%type,
     pMTM_TIPO_REQUISICAO   IN TB_MTMD_REQ_REQUISICAO.MTM_TIPO_REQUISICAO%type DEFAULT NULL,
     pMTMD_FL_PENDENTE      IN TB_MTMD_REQ_REQUISICAO.MTMD_FL_PENDENTE%type DEFAULT NULL,
     io_cursor              OUT PKG_CURSOR.t_cursor
  )
  is
   v_cursor                       PKG_CURSOR.t_cursor;
  BEGIN
    OPEN v_cursor FOR
    SELECT * FROM
    (SELECT
           REQUISICAO.MTMD_REQ_ID,
           REQUISICAO.ATD_ATE_ID,
           REQUISICAO.ATD_ATE_TP_PACIENTE,
           REQUISICAO.MTMD_REQ_FL_STATUS,
           REQUISICAO.MTMD_REQ_DT_ATUALIZACAO,
           REQUISICAO.MTM_TIPO_REQUISICAO,
           REQUISICAO.CAD_MTMD_FILIAL_ID,
           SETOR.cad_set_id,
           SETOR.CAD_SET_DS_SETOR,
           UNIDADE.cad_uni_id_unidade,
           UNIDADE.CAD_UNI_DS_UNIDADE,
           LOC.cad_lat_id_local_atendimento,
           LOC.CAD_LAT_DS_LOCAL_ATENDIMENTO,
           USU_REQUISICAO.SEG_USU_DS_NOME DS_USUARIO_REQUISICAO,
           USU_DISPENSACAO.SEG_USU_DS_NOME DS_USUARIO_DISPENSACAO,
           REQUISICAO.MTMD_DATA_REQUISICAO,
           KIT.CAD_MTMD_KIT_ID,
           KIT.CAD_MTMD_KIT_DSC,
           REQUISICAO.CAD_SET_SETOR_FARMACIA,
           REQUISICAO.MTMD_REQ_FL_URGENCIA
        FROM TB_MTMD_REQ_REQUISICAO       REQUISICAO,
             TB_CAD_SET_SETOR             SETOR,
             TB_CAD_UNI_UNIDADE           UNIDADE,
             TB_CAD_LAT_LOCAL_ATENDIMENTO LOC,
             TB_SEG_USU_USUARIO           USU_REQUISICAO,
             TB_SEG_USU_USUARIO           USU_DISPENSACAO,
             TB_CAD_MTMD_KIT              KIT
        WHERE
              SETOR.CAD_SET_ID                      = REQUISICAO.CAD_SET_ID
        AND   UNIDADE.CAD_UNI_ID_UNIDADE            = REQUISICAO.CAD_UNI_ID_UNIDADE
        AND   LOC.CAD_LAT_ID_LOCAL_ATENDIMENTO      = REQUISICAO.CAD_LAT_ID_LOCAL_ATENDIMENTO
        AND   USU_REQUISICAO.SEG_USU_ID_USUARIO  (+)= REQUISICAO.MTMD_ID_USUARIO_REQUISICAO
        AND   USU_DISPENSACAO.SEG_USU_ID_USUARIO (+)= REQUISICAO.MTMD_ID_USUARIO_DISPENSACAO
        AND   KIT.CAD_MTMD_KIT_ID                (+)= REQUISICAO.CAD_MTMD_KIT_ID
        AND   REQUISICAO.MTMD_REQ_FL_STATUS         = pMTMD_REQ_FL_STATUS
        AND   (pMTM_TIPO_REQUISICAO IS NULL OR REQUISICAO.MTM_TIPO_REQUISICAO = pMTM_TIPO_REQUISICAO)
        AND   (pMTMD_FL_PENDENTE IS NULL OR REQUISICAO.MTMD_FL_PENDENTE = pMTMD_FL_PENDENTE)
        ORDER BY REQUISICAO.MTMD_REQ_DT_ATUALIZACAO DESC) WHERE ROWNUM <= pQtdUltimas;
    io_cursor := v_cursor;
END PRC_MTMD_REQ_REQ_ULTIMAS;