create or replace procedure PRC_ASS_CPE_CNV_PRODEQ_JOIN_VL
  (
     pASS_CPE_ID IN TB_ASS_CPE_CONV_PROD_EQUIVALE.ASS_CPE_ID%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_PRD_ID_ORIGEM IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_PRD_ID_ORIGEM%type DEFAULT NULL,
     pCAD_PRD_ID_DESTINO IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_PRD_ID_DESTINO%type DEFAULT NULL,
     pCAD_CPE_DT_INICIO_VIGENCIA IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_CPE_DT_INICIO_VIGENCIA%type DEFAULT NULL,
     pCAD_CPE_DT_FIM_VIGENCIA IN TB_ASS_CPE_CONV_PROD_EQUIVALE.CAD_CPE_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pCAD_TAP_TP_ATRIBUTO IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_TAP_TP_ATRIBUTO%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_CAD_PRD_PRODUTO.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_CAD_PRD_PRODUTO.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pAUX_GPC_CD_GRUPOPROC IN TB_CAD_PRD_PRODUTO.AUX_GPC_CD_GRUPOPROC%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ASS_CPE_CNV_PRODEQ_JOIN_VL
  *
  *    Data Criacao: 	 12/08/2010    Por: André Souza Monaco
  *    Data Alteracao: 16/08/2010    Por: André Souza Monaco
  *         Alteracao: Cálculo do valor (qtd * val. índice)
  *
  *    Funcao: Lista todos os dados vigentes referente a valor,
  *            do produto de destino da equivalência
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin

    OPEN v_cursor FOR

    SELECT
       CPE.ASS_CPE_ID,
       CPE.CAD_CNV_ID_CONVENIO,
       CPE.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CPE.CAD_PRD_ID_ORIGEM,
       CPE.CAD_PRD_ID_DESTINO CAD_PRD_ID,
       CPE.CAD_CPE_DT_INICIO_VIGENCIA ASS_CVP_DT_INICIO_VIGENCIA,
       CPE.CAD_CPE_DT_FIM_VIGENCIA ASS_CVP_DT_FIM_VIGENCIA,

       PRD_ORIGEM.CAD_PRD_CD_CODIGO CAD_PRD_CD_CODIGO,
       PRD_ORIGEM.CAD_PRD_DS_DESCRICAO CAD_PRD_DS_DESCRICAO,

       CVM.CAD_CVM_VL_MOEDA_HOSPITALAR ASS_CVP_VL_INDICE_HOSP,
       (CVM.CAD_CVM_VL_MOEDA_HOSPITALAR * NVL(PRD_DESTINO.CAD_PRD_QT_INDICE_HOSP, 0)) ASS_CVP_VL_PRODUTO,
       PRD_DESTINO.CAD_TIH_TP_INDICE_HOSP CAD_TIH_TP_INDICE_HOSP,
       PRD_DESTINO.CAD_PRD_QT_INDICE_HOSP ASS_CVP_QT_INDICE_HOSP,

       PRD_DESTINO.CAD_PRD_TP_PORTE ASS_CVP_TP_PORTE,
       PRD_DESTINO.CAD_TAP_TP_ATRIBUTO,
       PRD_DESTINO.CAD_PRD_PC_DESCONTO ASS_CVP_PC_DESCONTO,
       PRD_DESTINO.CAD_PRD_PC_ACRESCIMO,
       PRD_DESTINO.CAD_PRD_CD_NAT_DESPESA_TISS TIS_CDE_CD_CODIGO_DESPESA,
       PRD_DESTINO.CAD_PRD_PC_DOPPLER ASS_CVP_PC_DOPPLER,
       PRD_DESTINO.CAD_PRD_QT_MINIMA ASS_CVP_QT_MINIMA_PERM,
       PRD_DESTINO.CAD_PRD_QT_MAXIMA ASS_CVP_QT_MAXIMA_PERM,

       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       CPE.CAD_CNV_ID_CONVENIO CAD_CNV_ID_CONVENIO,
       NVL(LOC.CAD_LAT_DS_LOCAL_ATENDIMENTO, 'TODOS') CAD_LAT_DS_LOCAL_ATENDIMENTO,
       MED.TIS_MED_DS_TABELAMEDICA,
       EPP.AUX_EPP_DS_DESCRICAO,
       GPC.AUX_GPC_DS_DESCRICAO,
       TAP.CAD_TAP_DS_ATRIBUTO,
       TPI.CAD_TIH_DS_INDICE_HOSP
    FROM TB_ASS_CPE_CONV_PROD_EQUIVALE CPE,
         TB_CAD_PRD_PRODUTO PRD_ORIGEM,
         TB_CAD_PRD_PRODUTO PRD_DESTINO,
         TB_CAD_LAT_LOCAL_ATENDIMENTO LOC,
         TB_TIS_MED_TABELAMEDICA MED,
         TB_AUX_EPP_ESPECPROC EPP,
         TB_AUX_GPC_GRUPOPROC GPC,
         TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
         TB_CAD_CNV_CONVENIO CNV,
         TB_CAD_CVM_CONV_VLR_MOEDAHOS CVM,
         TB_CAD_TIH_TP_INDICE_HOSP TPI
    WHERE
        (pASS_CPE_ID is null OR CPE.ASS_CPE_ID = pASS_CPE_ID) AND
        (pCAD_CNV_ID_CONVENIO is null OR CPE.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR CPE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND
        (pCAD_PRD_ID_ORIGEM is null OR CPE.CAD_PRD_ID_ORIGEM = pCAD_PRD_ID_ORIGEM) AND
        (pCAD_PRD_ID_DESTINO is null OR CPE.CAD_PRD_ID_DESTINO = pCAD_PRD_ID_DESTINO) AND
        (pTIS_MED_CD_TABELAMEDICA IS NULL OR PRD_DESTINO.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA) AND
        (pAUX_EPP_CD_ESPECPROC IS NULL OR PRD_DESTINO.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC) AND
        (pAUX_GPC_CD_GRUPOPROC IS NULL OR PRD_DESTINO.AUX_GPC_CD_GRUPOPROC = pAUX_GPC_CD_GRUPOPROC) AND
        (pCAD_TAP_TP_ATRIBUTO IS NULL OR PRD_DESTINO.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO) AND
        (CPE.CAD_CPE_DT_INICIO_VIGENCIA <= SYSDATE AND NVL(CPE.CAD_CPE_DT_FIM_VIGENCIA, SYSDATE) >= SYSDATE) AND
        (CPE.CAD_PRD_ID_ORIGEM = PRD_ORIGEM.CAD_PRD_ID) AND
        (CPE.CAD_PRD_ID_DESTINO = PRD_DESTINO.CAD_PRD_ID) AND
        (CPE.CAD_LAT_ID_LOCAL_ATENDIMENTO = LOC.CAD_LAT_ID_LOCAL_ATENDIMENTO(+)) AND
        (PRD_DESTINO.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA) AND
        (PRD_DESTINO.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC(+) AND PRD_DESTINO.TIS_MED_CD_TABELAMEDICA = EPP.TIS_MED_CD_TABELAMEDICA(+)) AND
        (PRD_DESTINO.AUX_GPC_CD_GRUPOPROC = GPC.AUX_GPC_CD_GRUPOPROC(+) AND PRD_DESTINO.TIS_MED_CD_TABELAMEDICA = GPC.TIS_MED_CD_TABELAMEDICA(+) AND
         PRD_DESTINO.AUX_EPP_CD_ESPECPROC = GPC.AUX_EPP_CD_ESPECPROC(+)) AND
        (TAP.CAD_TAP_TP_ATRIBUTO (+)= PRD_DESTINO.CAD_TAP_TP_ATRIBUTO) AND
        (CNV.CAD_CNV_ID_CONVENIO = CPE.CAD_CNV_ID_CONVENIO) AND
        (TPI.CAD_TIH_TP_INDICE_HOSP (+)= PRD_DESTINO.CAD_TIH_TP_INDICE_HOSP) AND
        (CVM.CAD_CNV_ID_CONVENIO = CPE.CAD_CNV_ID_CONVENIO AND CVM.CAD_TIH_TP_INDICE_HOSP = PRD_DESTINO.CAD_TIH_TP_INDICE_HOSP AND
        (CVM.CAD_CVM_DT_INICIO_VIGENCIA <= SYSDATE AND NVL(CVM.CAD_CVM_DT_FIM_VIGENCIA, SYSDATE) >= SYSDATE) AND CVM.CAD_PLA_ID_PLANO IS NULL)
    ORDER BY PRD_ORIGEM.CAD_PRD_DS_DESCRICAO;

    io_cursor := v_cursor;

  end PRC_ASS_CPE_CNV_PRODEQ_JOIN_VL;

