CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_ATD_NAO_DIGITADOS"
(
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
    pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pTIS_TIN_CD_INTER IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
    pTIS_TRI_CD_TP_REGINT IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
    pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
    pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNID_PROC    IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNID_PROC%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I   in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_E   in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_A   in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_U   in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pFATURADO                     varchar2 default null,
    pLOTEGERADO                   varchar2 default null,
    pEMITIDO                      varchar2 default null,
    pDIGITADO                     varchar2 default null,
    pTIS_MED_CD_TABELAMEDICA      IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
    pAUX_EPP_CD_ESPECPROC         IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE DEFAULT NULL,
    pAUX_GPC_CD_GRUPOPROC         IN TB_AUX_GPC_GRUPOPROC.AUX_GPC_CD_GRUPOPROC%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR--,
    --TESTE OUt LONG
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_ATD_NAO_DIGITADOS
*    DATA ALTERACAO: 19/4/2011  POR: PEDRO
*    ALTERAC?O: CAD_PRO_NR_CONSELHO
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(1000);
  V_WHERE2  varchar2(3000);
  V_SELECT  varchar2(30000);
  begin
    V_WHERE := NULL;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE;
    END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO;
    END IF;
    IF pCAD_SET_ID IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID;
    END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PAC.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;
    END IF;
    IF pCAD_PLA_ID_PLANO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PAC.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;
    END IF;
    /*IF pFAT_CCP_MES_FAT IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT;
    END IF;
    IF pFAT_CCP_ANO_FAT IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT;
    END IF;*/
    IF pTIS_CBO_CD_CBOS IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.TIS_CBO_CD_CBOS = ' ||CHR(39)|| pTIS_CBO_CD_CBOS ||CHR(39);
    END IF;
    IF pCAD_PRO_ID_PROF_EXEC IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.CAD_PRO_ID_PROF_EXEC = ' || pCAD_PRO_ID_PROF_EXEC;
    END IF;
   IF pCAD_PRD_ID IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND AIC.CAD_PRD_ID = ' || pCAD_PRD_ID;
    END IF;
   IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);
    END IF;
    IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);
    END IF;
   IF pTIS_TIN_CD_INTER IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND TIN.TIS_TIN_CD_INTERNACAO = ' ||CHR(39)|| pTIS_TIN_CD_INTER ||CHR(39);
    END IF;
   IF pTIS_TRI_CD_TP_REGINT IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND TRI.TIS_TRI_CD_TP_REGINTERNACAO = ' ||CHR(39)|| pTIS_TRI_CD_TP_REGINT ||CHR(39);
    END IF;
   IF pCAD_UNI_ID_UNID_PROC IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.CAD_UNI_ID_UNID_PROC = ' || pCAD_UNI_ID_UNID_PROC;
    END IF;
   IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PRD.TIS_MED_CD_TABELAMEDICA = ' ||CHR(39)|| pTIS_MED_CD_TABELAMEDICA ||CHR(39);
    END IF;
   IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PRD.AUX_EPP_CD_ESPECPROC = ' ||CHR(39)|| pAUX_EPP_CD_ESPECPROC ||CHR(39);
    END IF;
   IF pAUX_GPC_CD_GRUPOPROC IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND PRD.AUX_GPC_CD_GRUPOPROC = ' ||CHR(39)|| pAUX_GPC_CD_GRUPOPROC ||CHR(39);
    END IF;
   IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND ATE.TIS_TAT_CD_TPATENDIMENTO = ' ||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO ||CHR(39);
    END IF;
   V_SELECT :=
   '
    SELECT  ATE.ATD_ATE_ID,
            ATE.ATD_ATE_DT_ATENDIMENTO,
            PES.CAD_PES_NR_RG,
            PES.CAD_PES_NM_PESSOA,
            TAT.TIS_TAT_DS_TPATENDIMENTO,
            CNV.CAD_CNV_CD_HAC_PRESTADOR,
            CNV.CAD_CNV_NM_FANTASIA,
            PRO.CAD_PRO_NR_CONSELHO,
            PRO.CAD_PRO_NM_NOME,
            CID10.CAD_CID_CD_CID10,
            CID10.CAD_CID_DS_CID10,
            TSC.TIS_TSC_CD_TIPOSAIDACONSULTA,
            TSC.TIS_TSC_DS_TIPOSAIDACONSULTA
    FROM    TB_ATD_ATE_ATENDIMENTO ATE
    -- JOIN    TB_ASS_PAT_PACIEATEND  PAT      ON      PAT.ATD_ATE_ID          = ATE.ATD_ATE_ID
    JOIN    TB_CAD_PAC_PACIENTE    PAC      ON      PAC.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(ate.atd_ate_id)
    JOIN    TB_CAD_CNV_CONVENIO    CNV      ON      PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
    JOIN    TB_CAD_PLA_PLANO       PLA      ON      PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
    JOIN    TB_CAD_PES_PESSOA      PES      ON      PAC.CAD_PES_ID_PESSOA   = PES.CAD_PES_ID_PESSOA
    JOIN    TB_TIS_TAT_TP_ATENDIMENTO TAT   ON      TAT.TIS_TAT_CD_TPATENDIMENTO = ATE.TIS_TAT_CD_TPATENDIMENTO
    LEFT JOIN TB_ATD_AIC_ATE_INT_COMPL  AIC ON      AIC.ATD_ATE_ID          = ATE.ATD_ATE_ID
    LEFT JOIN TB_TIS_TIN_TP_INTERNACAO  TIN ON      TIN.TIS_TIN_CD_INTERNACAO = AIC.TIS_TIN_CD_INTERNACAO
    LEFT JOIN TB_TIS_TRI_TP_REGINTERNACAO TRI  ON   TRI.TIS_TRI_CD_TP_REGINTERNACAO = AIC.TIS_TRI_CD_REGINTENNACAO
    LEFT JOIN TB_CAD_PRD_PRODUTO          PRD  ON   PRD.CAD_PRD_ID            = AIC.CAD_PRD_ID
    LEFT JOIN TB_CAD_CID_CID10            CID10 ON  CID10.CAD_CID_CD_CID10     = ATE.CAD_CID_CD_CID10
    LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO    ON     PRO.CAD_PRO_ID_PROFISSIONAL = ATE.CAD_PRO_ID_PROF_EXEC
    LEFT JOIN TB_TIS_TSC_TIPOSAIDACONSULTA TSC ON   TSC.TIS_TSC_CD_TIPOSAIDACONSULTA = ATE.TIS_TSC_CD_TIPOSAIDACONSULTA
    WHERE (CNV.TIS_TFA_CD_TPFATURAMENTO IS NULL OR CNV.TIS_TFA_CD_TPFATURAMENTO <> '||chr(39)||'n'||chr(39)||') AND  ATE.ATD_ATE_ID NOT IN
    (
            SELECT  CCI.ATD_ATE_ID
            FROM    TB_FAT_CCI_CONTA_CONSU_ITEM CCI
            WHERE   CCI.ATD_ATE_ID = ATE.ATD_ATE_ID
            and cci.fat_cci_fl_status = '||chr(39)|| 'A' ||chr(39)||'
            AND CCI.FAT_CCI_TP_DESTINO_ITEM NOT IN ('||chr(39)|| 'T' ||chr(39)|| ',' ||chr(39)|| 'H' ||chr(39)|| ')
     /****   alterado 12122012 NINA
     --       AND cci.fat_cci_mes_fechamento = '|| chr(39) || pFAT_CCP_MES_FAT || chr(39) ||'
     --       AND cci.fat_cci_ano_fechamento = '|| chr(39) || pFAT_CCP_ANO_FAT || chr(39) ||' ****/
    )
   AND    (ATE.ATD_ATE_FL_STATUS = '||chr(39)||'A'||chr(39)||')
   AND    (ATE.ATD_ATE_FL_INDIC_RN_OK = '||chr(39)||'N'||chr(39)||')
   AND    (ATE.ATD_ATE_FL_RETORNO_OK = '||chr(39)||'N'||chr(39)||' OR ATE.ATD_ATE_FL_RETORNO_OK IS NULL)
   ' || V_WHERE || '
   AND ('||chr(39)|| pATD_ATE_TP_PACIENTE_I ||chr(39)||' IS not NULL and ate.atd_ate_tp_paciente = '||chr(39)||'I'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_E ||chr(39)||' IS NOT NULL AND ate.atd_ate_tp_paciente = '||chr(39)||'E'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_A ||chr(39)||' IS NOT NULL AND ate.atd_ate_tp_paciente = '||chr(39)||'A'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_U ||chr(39)||' IS NOT NULL AND ate.atd_ate_tp_paciente = '||chr(39)||'U'||chr(39)||')
   AND    ('||chr(39)|| pATD_ATE_FL_CARATER_SOLIC_U ||chr(39)||' IS NOT NULL AND ATE.ATD_ATE_FL_CARATER_SOLIC = '||chr(39)||'U'||chr(39)||'
        OR '||chr(39)|| pATD_ATE_FL_CARATER_SOLIC_E ||chr(39)||' IS NOT NULL AND ATE.ATD_ATE_FL_CARATER_SOLIC = '||chr(39)||'E'||chr(39)||')
   AND    ('||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)||' IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'GB'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PL ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'PL'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'PA'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'SP'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'FU'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'NP'||chr(39)||')
   ORDER   BY  ATE.ATD_ATE_DT_ATENDIMENTO DESC';
  -- TESTE :=  V_SELECT ;

	
  OPEN v_cursor FOR
   V_SELECT ;
    io_cursor := v_cursor;
END PRC_FAT_REL_ATD_NAO_DIGITADOS;
 