CREATE OR REPLACE PROCEDURE PRC_FAT_REL_ATO_MED_CLAS_CONT
(
    pATD_ATE_DT_ATENDIMENTO_INI   IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM   IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE           IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID                   IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO          IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO             IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO     IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
    pTIS_TIN_CD_INTER_1_CLI       varchar2 default null,
    pTIS_TIN_CD_INTER_2_CIR       varchar2 default null,
    pTIS_TIN_CD_INTER_3_OBS       varchar2 default null,
    pTIS_TIN_CD_INTER_4_PED       varchar2 default null,
    pTIS_TIN_CD_INTER_5_PSI       varchar2 default null,
    pFAT_CCP_MES_FAT              IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT              IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB      IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PL      IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_FU      IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP      IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA      IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP      IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_TAX      IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_DIA      IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_MAT      IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_MED      IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_HM       IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_EXA      IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_GAS      IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_PAC      IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I        IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_A        IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_E        IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_U        IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pFATURADO   VARCHAR2 DEFAULT NULL, 
    pLOTEGERADO VARCHAR2 DEFAULT NULL,
    pAUDITORIA  VARCHAR2 DEFAULT NULL,
    pEMITIDO    VARCHAR2 DEFAULT NULL,
    pDIGITADO   VARCHAR2 DEFAULT NULL,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR
   -- , teste OUT LONG
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_ATO_MED_CLAS_CONT
*    DATA ALTERACAO: 02/07/2010  POR: CAIO H. B. CHAGAS
*    ALTERAC?O:
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_SELECT  varchar2(20000);
begin
  V_WHERE := NULL;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PAC.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pCAD_PLA_ID_PLANO IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND PAC.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;    END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_MES_FAT = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_ANO_FAT = ' || pFAT_CCP_ANO_FAT; END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT;   END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT;   END IF;
IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.TIS_TAT_CD_TPATENDIMENTO = ' ||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO ||CHR(39); END IF;
IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);    END IF;
IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);    END IF;
V_SELECT:=
'
     SELECT  DISTINCT
            CCI.CAD_CAC_ID_CLASSCONTABIL,
            CAC.CAD_CAC_CD_CLASSCONTABIL,
            CAC.CAD_CAC_DS_CLASSCONTABIL,
            CCI.CAD_PRD_ID,
            PRD.CAD_PRD_CD_CODIGO,
            PRD.CAD_PRD_DS_DESCRICAO,
            PRD.TIS_MED_CD_TABELAMEDICA,
            SUM(CCI.FAT_CCI_QT_CONSUMO)   QTD_PRODUTO,
            COUNT(distinct CCI.ATD_ATE_ID||cci.fat_ccp_id||PAC.CAD_CNV_ID_CONVENIO||CCI.CAD_PRD_ID)        QTD_ATENDIMENTO,     
            SUM(CCI.FAT_CCI_VL_FATURADO)  VALOR_TOTAL,
            round(SUM(CCI.FAT_CCI_VL_FATURADO)  / 
            SUM(CCI.FAT_CCI_QT_CONSUMO) ,2) VALOR_MEDIO
    FROM    TB_FAT_CCI_CONTA_CONSU_ITEM  CCI
    LEFT JOIN TB_FAT_CCP_CONTA_CONS_PARC   CCP
    ON      CCP.FAT_CCP_ID             = CCI.FAT_CCP_ID
    AND     CCP.ATD_ATE_ID             = CCI.ATD_ATE_ID
    AND     CCP.FAT_COC_ID             = CCI.FAT_COC_ID
    AND     CCP.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE
    AND     CCP.FAT_CCP_FL_STATUS      = '||chr(39)||'A'||chr(39)||'
    JOIN    TB_FAT_MCC_MOV_COM_CONSUMO   MCC
    ON      CCI.FAT_MCC_ID             = MCC.FAT_MCC_ID
    AND     CCI.ATD_ATE_ID             = MCC.ATD_ATE_ID
    JOIN    TB_CAD_CAC_CLASSIF_CONTAB    CAC
    ON      CAC.CAD_CAC_ID_CLASSCONTABIL = CCI.CAD_CAC_ID_CLASSCONTABIL
    JOIN    TB_CAD_PRD_PRODUTO           PRD
    ON      PRD.CAD_PRD_ID             = CCI.CAD_PRD_ID
    JOIN    TB_ATD_ATE_ATENDIMENTO       ATE
    ON      ATE.ATD_ATE_ID             = MCC.ATD_ATE_ID
    AND     ATE.ATD_ATE_ID             = CCI.ATD_ATE_ID
    JOIN    TB_CAD_UNI_UNIDADE           UNI
    ON      ATE.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
    JOIN    TB_TIS_TAT_TP_ATENDIMENTO    TAT
    ON      TAT.TIS_TAT_CD_TPATENDIMENTO = ATE.TIS_TAT_CD_TPATENDIMENTO    
    JOIN    TB_CAD_PAC_PACIENTE          PAC
    ON      PAC.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE
    JOIN    TB_CAD_CNV_CONVENIO          CNV
    ON      CNV.CAD_CNV_ID_CONVENIO    = PAC.CAD_CNV_ID_CONVENIO
    JOIN    TB_CAD_PLA_PLANO             PLA
    ON      PLA.CAD_PLA_ID_PLANO       = PAC.CAD_PLA_ID_PLANO
    LEFT    JOIN TB_ATD_AIC_ATE_INT_COMPL AIC
    ON      ATE.ATD_ATE_ID             = AIC.ATD_ATE_ID
    AND     AIC.ATD_ATE_ID             = CCI.ATD_ATE_ID    
    LEFT    JOIN TB_TIS_TIN_TP_INTERNACAO TIN
    ON      TIN.TIS_TIN_CD_INTERNACAO  = AIC.TIS_TIN_CD_INTERNACAO 
    AND    ('||chr(39)|| pTIS_TIN_CD_INTER_1_CLI ||chr(39)||' IS NOT NULL AND TIN.TIS_TIN_CD_INTERNACAO = 1
        OR '||chr(39)|| pTIS_TIN_CD_INTER_2_CIR ||chr(39)||' IS NOT NULL AND TIN.TIS_TIN_CD_INTERNACAO = 2
        OR '||chr(39)|| pTIS_TIN_CD_INTER_3_OBS ||chr(39)||' IS NOT NULL AND TIN.TIS_TIN_CD_INTERNACAO = 3
        OR '||chr(39)|| pTIS_TIN_CD_INTER_4_PED ||chr(39)||' IS NOT NULL AND TIN.TIS_TIN_CD_INTERNACAO = 4
        OR '||chr(39)|| pTIS_TIN_CD_INTER_5_PSI ||chr(39)||' IS NOT NULL AND TIN.TIS_TIN_CD_INTERNACAO = 5)
    WHERE   (CCI.CAD_TAP_TP_ATRIBUTO NOT IN ('||chr(39)||'MAT'||chr(39)||','||chr(39)||'MED'||chr(39)||','||chr(39)||'PAC'||chr(39)||')) 
    AND     CCI.CAD_TIH_TP_INDICE_HOSP <> '||chr(39)||'M2'||chr(39)||'
    AND    (CCI.FAT_CCI_FL_STATUS      = '||chr(39)||'A'||chr(39)||')
    AND    (MCC.FAT_MCC_FL_STATUS      = '||chr(39)||'A'||chr(39)||')
    AND    (ATE.ATD_ATE_FL_STATUS      = '||chr(39)||'A'||chr(39)||')
    AND    (UNI.CAD_UNI_FL_FATURA_UNID_OK = '||chr(39)||'S'||chr(39)||')
   ' || V_WHERE || '
   AND     ((' ||chr(39)|| pFATURADO  || chr(39) || ' IS NOT NULL AND CCP.FAT_NOF_ID IS NOT NULL )
      OR  (' || chr(39) || pAUDITORIA  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_STATUS_AUDIT = ' || chr(39) || 'E' || chr(39) || ')
      OR  (' || chr(39) || pLOTEGERADO  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_FATURADA = ' || chr(39) || 'S' || chr(39) || ' AND CCP.FAT_NOF_ID IS NULL)
      OR  (' || chr(39) || pEMITIDO  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_EMITIDA = ' || chr(39) || 'S' || chr(39) || ' AND CCP.FAT_CCP_FL_FATURADA = ' || chr(39) || 'N' || chr(39) || '
          AND (CCP.FAT_CCP_FL_STATUS_AUDIT = ' || chr(39) || 'A' || chr(39) || ' OR CCP.FAT_CCP_DT_ENVIO_AUDIT IS NULL))
      OR  (' || chr(39) || pDIGITADO  || chr(39) || ' IS NOT NULL AND CCI.FAT_CCP_ID IS NULL))
    AND ('||chr(39)|| pATD_ATE_TP_PACIENTE_I ||chr(39)||' IS not NULL and ate.atd_ate_tp_paciente = '||chr(39)||'I'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_E ||chr(39)||' IS NOT NULL AND ate.atd_ate_tp_paciente = '||chr(39)||'E'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_A ||chr(39)||' IS NOT NULL AND ate.atd_ate_tp_paciente = '||chr(39)||'A'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_U ||chr(39)||' IS NOT NULL AND ate.atd_ate_tp_paciente = '||chr(39)||'U'||chr(39)||')
   AND    ('||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)||' IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'GB'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PL ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'PL'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'PA'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'SP'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'FU'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||chr(39)||' IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = '||chr(39)||'NP'||chr(39)||')
    AND (('||chr(39)|| pCAD_TAP_TP_ATRIBUTO_PAC ||chr(39)||'IS not NULL and (CCI.FAT_CCI_FL_PACOTE = '||chr(39)||'S'||chr(39)||'))
        OR (CCI.FAT_CCI_FL_PACOTE = '||chr(39)||'N'||chr(39)||' OR CCI.FAT_CCI_FL_PACOTE IS NULL))
    AND ( --somente os itens de pacote
       ('||chr(39)|| pCAD_TAP_TP_ATRIBUTO_EXA ||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'EXA'||chr(39)||')
      OR ('||chr(39)|| pCAD_TAP_TP_ATRIBUTO_TAX ||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'TAX'||chr(39)||')
      OR ('||chr(39)|| pCAD_TAP_TP_ATRIBUTO_DIA ||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'DIA'||chr(39)||')
      OR ('||chr(39)|| pCAD_TAP_TP_ATRIBUTO_HM ||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'HM'||chr(39)||')
      OR ('||chr(39)|| pCAD_TAP_TP_ATRIBUTO_GAS ||chr(39)||' IS NOT NULL AND CCI.CAD_TAP_TP_ATRIBUTO = '||chr(39)||'GAS'||chr(39)||'))
    GROUP BY  CCI.CAD_CAC_ID_CLASSCONTABIL,
            CAC.CAD_CAC_CD_CLASSCONTABIL,
            CAC.CAD_CAC_DS_CLASSCONTABIL,
            CCI.CAD_PRD_ID,
            PRD.CAD_PRD_CD_CODIGO,
            PRD.CAD_PRD_DS_DESCRICAO,
            PRD.TIS_MED_CD_TABELAMEDICA   
    ORDER   BY PRD.CAD_PRD_DS_DESCRICAO';   
  --  TESTE :=  V_SELECT ;
  OPEN v_cursor FOR
    V_SELECT ;
   --SELECT 1 FROM dual;
    io_cursor := v_cursor;
END PRC_FAT_REL_ATO_MED_CLAS_CONT;
 