create or replace procedure PRC_ASS_USC_S
  (
     pASS_USC_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_ID%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_SET_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_SET_ID%type DEFAULT NULL,
     pCAD_CEC_ID_CCUSTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_CEC_ID_CCUSTO%type DEFAULT NULL,
     pCAD_CAC_ID_CLASSCONTABIL IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_CAC_ID_CLASSCONTABIL%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_ASS_USC_UNI_SET_CCUS_CLA.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ASS_USC_UNI_SET_CCUS_CLA.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pASS_USC_FL_STATUS IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_FL_STATUS%type DEFAULT NULL,

     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ASS_USC_S
  *
  *    Data Criacao:   02/12/2009   Por: Pedro
  *    Data Alteracao:  03/04/2010 Por: Pedro
  *    Alteração: pAUX_EPP_CD_ESPECPROC e pTIS_MED_CD_TABELAMEDICA
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT
       USC.ASS_USC_ID,
       USC.CAD_UNI_ID_UNIDADE,
       USC.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       USC.CAD_SET_ID,
       USC.CAD_CEC_ID_CCUSTO,
       USC.CAD_CAC_ID_CLASSCONTABIL,
       USC.AUX_EPP_CD_ESPECPROC,
       USC.TIS_MED_CD_TABELAMEDICA,
       USC.ASS_USC_FL_STATUS,
       USC.ASS_USC_DT_ULTIMA_ATUALIZACAO,
       USC.SEG_USU_ID_USUARIO,
       UNI.CAD_UNI_DS_UNIDADE,
       LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       SETOR.CAD_SET_DS_SETOR,
       EPP.AUX_EPP_DS_DESCRICAO,
       CEC.CAD_CEC_DS_CCUSTO,
       CAC.CAD_CAC_DS_CLASSCONTABIL

    FROM TB_ASS_USC_UNI_SET_CCUS_CLA USC
    JOIN TB_CAD_CEC_CENTRO_CUSTO CEC
    ON   CEC.CAD_CEC_ID_CCUSTO = USC.CAD_CEC_ID_CCUSTO
    JOIN TB_CAD_CAC_CLASSIF_CONTAB CAC
    ON   CAC.CAD_CAC_ID_CLASSCONTABIL = USC.CAD_CAC_ID_CLASSCONTABIL
    LEFT JOIN TB_AUX_EPP_ESPECPROC EPP
    ON   EPP.AUX_EPP_CD_ESPECPROC = USC.AUX_EPP_CD_ESPECPROC
    AND  EPP.TIS_MED_CD_TABELAMEDICA = USC.TIS_MED_CD_TABELAMEDICA
    JOIN TB_CAD_UNI_UNIDADE UNI
    ON   UNI.CAD_UNI_ID_UNIDADE = USC.CAD_UNI_ID_UNIDADE
    JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
    ON   LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = USC.CAD_LAT_ID_LOCAL_ATENDIMENTO
    JOIN TB_CAD_SET_SETOR SETOR
    ON   SETOR.CAD_SET_ID = USC.CAD_SET_ID

    WHERE
        (pASS_USC_ID is null OR USC.ASS_USC_ID = pASS_USC_ID) AND
        (pCAD_UNI_ID_UNIDADE is null OR USC.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE) AND
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR USC.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND
        (pCAD_SET_ID is null OR USC.CAD_SET_ID = pCAD_SET_ID) AND
        (pCAD_CEC_ID_CCUSTO is null OR USC.CAD_CEC_ID_CCUSTO = pCAD_CEC_ID_CCUSTO) AND
        (pCAD_CAC_ID_CLASSCONTABIL is null OR USC.CAD_CAC_ID_CLASSCONTABIL = pCAD_CAC_ID_CLASSCONTABIL) AND
        (pAUX_EPP_CD_ESPECPROC is null OR USC.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC) AND
        (pASS_USC_FL_STATUS is null OR USC.ASS_USC_FL_STATUS = pASS_USC_FL_STATUS) 
;
    io_cursor := v_cursor;
  end PRC_ASS_USC_S;

