create or replace procedure PRC_ATS_LAUDO_PACIENTE
 (
     pCAD_UNI_ID_UNIDADE in TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pATS_ATE_IN_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_IN_INTLIB%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_ATS_ATE_ATENDIMENTO_SADT.Aux_Epp_Cd_Especproc%type DEFAULT NULL,
     pCAD_PES_NM_PESSOA in TB_CAD_PES_PESSOA.CAD_PES_NM_PESSOA%TYPE,
     pATS_ATE_CD_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_CD_INTLIB%type DEFAULT NULL,
     pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ATS_ATE_ATENDIMENTO_SADT.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ATS_LAUDO_PACIENTE
  * 
   *    Data Alteracao:  6/4/2011  Por: Pedro
  *    Alteracao: custo
  *
  *    Funcao: Alimentar a pesquisa de Laudos do Paciente
  *
  *******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
  V_ORDERBY varchar2(500);
begin
  V_WHERE := NULL;
  IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND UNI.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
  IF pCAD_PES_NM_PESSOA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES_PAC.CAD_PES_NM_PESSOA LIKE ' || pCAD_PES_NM_PESSOA; END IF;
  IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATS.AUX_EPP_CD_ESPECPROC = ' || CHR(39) || pAUX_EPP_CD_ESPECPROC || CHR(39); END IF;
  IF pATS_ATE_IN_INTLIB IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' || CHR(39) || pATS_ATE_IN_INTLIB || CHR(39); END IF;  
  IF pATS_ATE_CD_INTLIB IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATS.ATS_ATE_CD_INTLIB = ' || CHR(39) || pATS_ATE_CD_INTLIB || CHR(39); END IF;
  IF pCAD_PRD_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATS.CAD_PRD_ID = ' || pCAD_PRD_ID; END IF;
  IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATS.TIS_MED_CD_TABELAMEDICA = ' || CHR(39) || pTIS_MED_CD_TABELAMEDICA || CHR(39); END IF;
  
    
  
   V_SELECT := '
    OPEN v_cursor FOR
        SELECT
      APL.ATS_APL_ID,
      ATS.ATS_ATE_ID,
      ATS.ATS_ATE_CD_INTLIB,
      ATS.ATS_ATE_IN_INTLIB,
      PES_UNI.CAD_PES_NM_PESSOA UNI,
      PRD.CAD_PRD_ID,
      PRD.CAD_PRD_DS_DESCRICAO,
      EPP.AUX_EPP_CD_ESPECPROC,
      EPP.AUX_EPP_DS_DESCRICAO ,
      PES_PAC.CAD_PES_NM_PESSOA NM_PAC,
      PES_PRO.CAD_PES_NM_PESSOA NM_PRO,
      PES_PAC.CAD_PES_NR_RG,
     TO_CHAR(ATS.ATS_ATE_DT_REALIZ_PROCED,'|| CHR(39) ||'DD-MM-YYYY'|| CHR(39) ||') ATS_ATE_DT_REALIZ_PROCED,
     ATS.AGE_SAU_ID,
      UNI.CAD_UNI_ID_UNIDADE,
      LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       DECODE(APL.ATS_APL_STATUS_LAUDO, ' ||CHR(39)|| 'L' ||CHR(39)|| ',' ||CHR(39)|| 'LAUDADO' ||CHR(39)|| ',' ||CHR(39)|| 'I' ||CHR(39)||',
      '|| CHR(39) ||'IMPRESSO'|| CHR(39) ||','|| CHR(39) ||'P'|| CHR(39) ||','|| CHR(39) ||'PROTOCOLADO'|| CHR(39) ||','|| CHR(39) ||'E'|| CHR(39) ||','|| CHR(39) ||'ENTREGUE'|| CHR(39) ||','|| CHR(39) ||''|| CHR(39) ||','|| CHR(39) ||'REALIZADO'|| CHR(39) ||')ATS_APL_STATUS_LAUDO,
       PAC.CAD_PAC_NR_PRONTUARIO,
       ARP.ATS_APR_NR_SEQ_LOTE
FROM TB_ATS_ATE_ATENDIMENTO_SADT ATS
      LEFT JOIN TB_ATS_APL_ATEN_PROCED_LAUDO APL
       ON APL.ATS_ATE_ID = ATS.ATS_ATE_ID
       AND APL.ATS_ATE_CD_INTLIB = ATS.ATS_ATE_CD_INTLIB
       AND APL.ATS_ATE_IN_INTLIB = ATS.ATS_ATE_IN_INTLIB
       AND APL.AUX_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC
       AND APL.CAD_PRD_ID = ATS.CAD_PRD_ID
       AND APL.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA

     LEFT JOIN TB_ATS_ARP_ATEN_RESULT_PROCED ARP
       ON ARP.ATS_ATE_ID = ATS.ATS_ATE_ID
       AND ARP.ATS_ATE_CD_INTLIB = ATS.ATS_ATE_CD_INTLIB
       AND ARP.ATS_ATE_IN_INTLIB = ATS.ATS_ATE_IN_INTLIB
       AND ARP.ATS_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC
       AND ARP.CAD_PRD_ID = ATS.CAD_PRD_ID
       AND ARP.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA

      LEFT JOIN TB_CAD_SET_SETOR SETOR_EXEC
     ON SETOR_EXEC.CAD_SET_ID = ATS.CAD_SET_ID_ATEN
     LEFT JOIN TB_CAD_SET_SETOR SETOR_PROCED
     ON SETOR_PROCED.CAD_SET_ID = ATS.CAD_SET_ID
     LEFT JOIN TB_CAD_UNI_UNIDADE UNI
     ON UNI.CAD_UNI_ID_UNIDADE = SETOR_EXEC.CAD_UNI_ID_UNIDADE
     LEFT JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
     ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR_EXEC.CAD_LAT_ID_LOCAL_ATENDIMENTO
     LEFT JOIN TB_CAD_PES_PESSOA PES_UNI
     ON PES_UNI.CAD_PES_ID_PESSOA = UNI.CAD_PES_ID_PESSOA
     LEFT JOIN TB_CAD_PRD_PRODUTO PRD
     ON PRD.CAD_PRD_ID = ATS.CAD_PRD_ID
     LEFT JOIN TB_AUX_EPP_ESPECPROC EPP
     ON EPP.AUX_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC
     AND EPP.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA
     LEFT JOIN TB_CAD_PAC_PACIENTE PAC
     ON PAC.CAD_PAC_ID_PACIENTE = ATS.CAD_PAC_ID_PACIENTE_INT
     LEFT JOIN TB_CAD_PES_PESSOA PES_PAC
     ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
     LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO
     ON PRO.CAD_PRO_ID_PROFISSIONAL = APL.CAD_PRO_ID_PROF
     LEFT JOIN TB_CAD_PES_PESSOA PES_PRO
     ON PES_PRO.CAD_PES_ID_PESSOA = PRO.CAD_PES_ID_PESSOA
     LEFT JOIN TB_INTERNADO INTERNADO
     ON INTERNADO.NR_SEQINTER = ATS.ATS_ATE_CD_INTLIB
    LEFT JOIN TB_ATS_CSL_CTRL_SEQ_LOTE CSL
     ON CSL.ATS_APR_NR_SEQ_LOTE = ARP.ATS_APR_NR_SEQ_LOTE
     
WHERE  (ATS.ATS_ATE_FL_STATUS <> '|| CHR(39) ||'C'|| CHR(39) ||') 
 AND (NULL = 0 AND APL.ATS_APL_STATUS_LAUDO IS NULL
       or NULL is NULL )
 '    ;

  V_ORDERBY := 'ORDER BY 10,13 DESC';

OPEN v_cursor FOR
  V_SELECT || V_WHERE || V_ORDERBY;
  io_cursor := v_cursor;

  end PRC_ATS_LAUDO_PACIENTE;
/
