CREATE OR REPLACE PROCEDURE PRC_CAD_PAC_PRONTUARIO_RMT_S
(
       pCAD_PAC_NR_PRONTUARIO IN TB_CAD_PAC_PACIENTE.CAD_PAC_NR_PRONTUARIO%TYPE,
       io_cursor OUT PKG_CURSOR.t_cursor
)
IS
v_cursor PKG_CURSOR.t_cursor;
BEGIN
 OPEN v_cursor FOR
SELECT
PAC.CAD_PAC_ID_PACIENTE,
CNV.CAD_CNV_CD_HAC_PRESTADOR,
PLA.CAD_PLA_CD_PLANO_HAC,
PES.CAD_PES_NM_PESSOA,
PES.CAD_PES_DT_NASCIMENTO,
PES.CAD_PES_TP_SEXO,
PES.CAD_PES_NM_NOMEMAE,
PAC.CAD_PAC_NR_PRONTUARIO,
PAC.CAD_PAC_CD_CREDENCIAL,
PES.CAD_PES_FL_ATIVO_OK,
PAC.CAD_PAC_FL_ATIVO_OK
FROM TB_CAD_PAC_PACIENTE PAC
  INNER JOIN TB_CAD_PLA_PLANO PLA
   ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
  INNER JOIN TB_CAD_CNV_CONVENIO CNV
   ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
  INNER JOIN TB_CAD_PES_PESSOA PES
   ON PES.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
WHERE PAC.CAD_PAC_NR_PRONTUARIO = pCAD_PAC_NR_PRONTUARIO;

 io_cursor := v_cursor;
END PRC_CAD_PAC_PRONTUARIO_RMT_S;
 