CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_CONFERENCIA"
(
  pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
  pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
  pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
  pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
  pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
  pTIS_TAT_CD_TPATENDIMENTO IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
  pFAT_CCP_MES_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_COMPET%TYPE DEFAULT NULL,
  pFAT_CCP_ANO_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_COMPET%TYPE DEFAULT NULL,
  pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
  pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
  pATD_ATE_TP_PACIENTE_I in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
  pATD_ATE_TP_PACIENTE_E in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
  pATD_ATE_TP_PACIENTE_A in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
  pATD_ATE_TP_PACIENTE_U in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
  IO_CURSOR OUT PKG_CURSOR.T_CURSOR--,
  -- TESTE OUT LONG 
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_CONFERENCIA
*    DATA ALTERACAO: 04/09/2013  POR: pEDRO
*    Alteracao:  V_SELECT  varchar2(20000);
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_SELECT  varchar2(20000);
begin
  V_WHERE := NULL;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCP.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pCAD_PLA_ID_PLANO IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND CCP.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;    END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_MES_FAT = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_ANO_FAT = ' || pFAT_CCP_ANO_FAT; END IF;
IF pFAT_CCP_MES_COMPET IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_MES_COMPET = ' || pFAT_CCP_MES_COMPET; END IF;
IF pFAT_CCP_ANO_COMPET IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.FAT_CCP_ANO_COMPET = ' || pFAT_CCP_ANO_COMPET; END IF;
IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.TIS_TAT_CD_TPATENDIMENTO = ' ||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO ||CHR(39); END IF;
V_SELECT:=
'
  SELECT  CCP.FAT_CCP_MES_COMPET,
          CCP.FAT_CCP_ANO_COMPET,
          UNI.CAD_UNI_DS_UNIDADE,
          UNI.CAD_UNI_CD_UNID_HOSPITALAR,
          TAT.TIS_TAT_DS_TPATENDIMENTO,
          CNV.CAD_CNV_CD_HAC_PRESTADOR,
          CNV.CAD_CNV_NM_FANTASIA,
          CCP.ATD_ATE_ID,
          CCP.FAT_CCP_ID,
          PES.CAD_PES_NM_PESSOA,
          ATE.ATD_ATE_DT_ATENDIMENTO,
          CCP.FAT_CCP_DT_PARCELA,
          CCP.FAT_CCP_VL_TOT_CONTA,
          CCP.FAT_CCP_MES_FAT,
          CCP.FAT_CCP_ANO_FAT
  FROM    TB_FAT_CCP_CONTA_CONS_PARC CCP
  JOIN    TB_CAD_PAC_PACIENTE        PAC  ON      CCP.CAD_PAC_ID_PACIENTE      = PAC.CAD_PAC_ID_PACIENTE
  JOIN    TB_CAD_PES_PESSOA          PES  ON      PAC.CAD_PES_ID_PESSOA        = PES.CAD_PES_ID_PESSOA
  JOIN    TB_CAD_CNV_CONVENIO        CNV  ON      CNV.CAD_CNV_ID_CONVENIO      = CCP.CAD_CNV_ID_CONVENIO
  JOIN    TB_ATD_ATE_ATENDIMENTO     ATE  ON      ATE.ATD_ATE_ID               = CCP.ATD_ATE_ID
  JOIN    TB_CAD_UNI_UNIDADE         UNI  ON      UNI.CAD_UNI_ID_UNIDADE       = CCP.CAD_UNI_ID_UNIDADE
  JOIN    TB_TIS_TAT_TP_ATENDIMENTO  TAT  ON      ATE.TIS_TAT_CD_TPATENDIMENTO = TAT.TIS_TAT_CD_TPATENDIMENTO  
  --JOIN    TB_CAD_PLA_PLANO           PLA  ON      PLA.CAD_PLA_ID_PLANO         = CCP.CAD_PLA_ID_PLANO 
 WHERE   CCP.FAT_CCP_FL_EMITIDA = '||chr(39)||'S'||chr(39)||' AND CCP.FAT_CCP_FL_FATURADA = '||chr(39)||'S'||chr(39)||'
  AND     ccp.fat_nof_id is not null
  AND    (UNI.CAD_UNI_FL_FATURA_UNID_OK = '||chr(39)||'S'||chr(39)||')
 ' || V_WHERE || '
  AND ('||chr(39)|| pATD_ATE_TP_PACIENTE_I ||chr(39)||' IS not NULL and CCP.atd_ate_tp_paciente = '||chr(39)||'I'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_E ||chr(39)||' IS NOT NULL AND CCP.atd_ate_tp_paciente = '||chr(39)||'E'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_A ||chr(39)||' IS NOT NULL AND CCP.atd_ate_tp_paciente = '||chr(39)||'A'||chr(39)||'
     OR '||chr(39)|| pATD_ATE_TP_PACIENTE_U ||chr(39)||' IS NOT NULL AND CCP.atd_ate_tp_paciente = '||chr(39)||'U'||chr(39)||')
   AND    ('||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)||' IS not NULL and CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'ACS'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'PA'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'SP'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'FU'||chr(39)||'
       OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'NP'||chr(39)||')'
  ;
   -- TESTE :=  V_SELECT ;
  OPEN v_cursor FOR
   V_SELECT ;
    io_cursor := v_cursor;
END PRC_FAT_REL_CONFERENCIA;
 