

 
  --PRC_ASS_PMM_PLANO_MATMED_S
  create or replace procedure PRC_ASS_PMM_PLANO_MATMED_S 
  (
     pCAD_CNV_ID_CONVENIO IN TB_ASS_PMM_PLANO_MATMED.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pCAD_PLA_ID_PLANO IN TB_ASS_PMM_PLANO_MATMED.CAD_PLA_ID_PLANO%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_PMM_PLANO_MATMED.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_MTMD_ID IN TB_ASS_PMM_PLANO_MATMED.CAD_MTMD_ID%type DEFAULT NULL,
     pASS_PMM_FL_EXIGE_GUIA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_EXIGE_GUIA%type DEFAULT NULL,
     pASS_PMM_FL_EXIGE_SENHA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_EXIGE_SENHA%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZATEL IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZATEL%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZAFAX IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAFAX%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZAPES IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAPES%type DEFAULT NULL,
     pASS_PMM_FL_AUTORIZAWEB IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_AUTORIZAWEB%type DEFAULT NULL,
     pASS_PMM_FL_COBERTURA IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_COBERTURA%type DEFAULT NULL,
     pASS_PMM_FL_STATUS IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_FL_STATUS%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ASS_PMM_PLANO_MATMED.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pASS_PMM_DT_ULTIMA_ATUALIZACAO IN TB_ASS_PMM_PLANO_MATMED.ASS_PMM_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  ) 
  is
  /********************************************************************
  *    Procedure: PRC_ASS_PMM_PLANO_MATMED_S
  * 
  *    Data Criacao:   data da  criação   Por: Nome do Analista
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT  
       CAD_CNV_ID_CONVENIO,
       CAD_PLA_ID_PLANO,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_MTMD_ID,
       ASS_PMM_FL_EXIGE_GUIA,
       ASS_PMM_FL_EXIGE_SENHA,
       ASS_PMM_FL_AUTORIZATEL,
       ASS_PMM_FL_AUTORIZAFAX,
       ASS_PMM_FL_AUTORIZAPES,
       ASS_PMM_FL_AUTORIZAWEB,
       ASS_PMM_FL_COBERTURA,
       ASS_PMM_FL_STATUS,
       SEG_USU_ID_USUARIO,
       ASS_PMM_DT_ULTIMA_ATUALIZACAO
    FROM TB_ASS_PMM_PLANO_MATMED
    WHERE
        (pCAD_CNV_ID_CONVENIO is null OR CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND 
        (pCAD_PLA_ID_PLANO is null OR CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO) AND 
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND 
        (pCAD_MTMD_ID is null OR CAD_MTMD_ID = pCAD_MTMD_ID) AND 
        (pASS_PMM_FL_EXIGE_GUIA is null OR ASS_PMM_FL_EXIGE_GUIA = pASS_PMM_FL_EXIGE_GUIA) AND 
        (pASS_PMM_FL_EXIGE_SENHA is null OR ASS_PMM_FL_EXIGE_SENHA = pASS_PMM_FL_EXIGE_SENHA) AND 
        (pASS_PMM_FL_AUTORIZATEL is null OR ASS_PMM_FL_AUTORIZATEL = pASS_PMM_FL_AUTORIZATEL) AND 
        (pASS_PMM_FL_AUTORIZAFAX is null OR ASS_PMM_FL_AUTORIZAFAX = pASS_PMM_FL_AUTORIZAFAX) AND 
        (pASS_PMM_FL_AUTORIZAPES is null OR ASS_PMM_FL_AUTORIZAPES = pASS_PMM_FL_AUTORIZAPES) AND 
        (pASS_PMM_FL_AUTORIZAWEB is null OR ASS_PMM_FL_AUTORIZAWEB = pASS_PMM_FL_AUTORIZAWEB) AND 
        (pASS_PMM_FL_COBERTURA is null OR ASS_PMM_FL_COBERTURA = pASS_PMM_FL_COBERTURA) AND 
        (pASS_PMM_FL_STATUS is null OR ASS_PMM_FL_STATUS = pASS_PMM_FL_STATUS) AND 
        (pSEG_USU_ID_USUARIO is null OR SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND 
        (pASS_PMM_DT_ULTIMA_ATUALIZACAO is null OR ASS_PMM_DT_ULTIMA_ATUALIZACAO = pASS_PMM_DT_ULTIMA_ATUALIZACAO);          
    io_cursor := v_cursor;
  end PRC_ASS_PMM_PLANO_MATMED_S;

