create or replace procedure PRC_CAD_PAH_PERC_ACRESC_HR_I
  (
     pNewIdt OUT integer,
     pCAD_TAP_TP_ATRIBUTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_TAP_TP_ATRIBUTO%type,
     pCAD_PAH_PC_ACRESCIMO_HR IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_PC_ACRESCIMO_HR%type,
     pCAD_PAH_HR_INICIO_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_INICIO_SEMANA%type,
     pCAD_PAH_HR_FIM_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_FIM_SEMANA%type,
     pCAD_PAH_DT_INICIO_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_INICIO_VIGENCIA%type,
     pCAD_PAH_DT_FIM_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_FIM_VIGENCIA%type default NULL,
     pCAD_PAH_DT_ULTIMA_ATUALIZACAO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_ULTIMA_ATUALIZACAO%type,
     pSEG_USU_ID_USUARIO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.SEG_USU_ID_USUARIO%type,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pCAD_PAH_NR_DIA_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_NR_DIA_SEMANA%type,
     pCAD_CNV_ID_CONVENIO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_CNV_ID_CONVENIO%type,
     pCAD_PAH_ID IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_ID%type
  )
  is
  /********************************************************************
  *    Procedure: PRC_CAD_PAH_PERC_ACRESC_HR_I
  *
  *    Data Criacao:   data da  cria??o   Por: Nome do Analista
  *    Data Alteracao:  data da altera??o  Por: Nome do Analista
  *
  *    Funcao: Descri??o da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  lIdtRetornoSEQ integer;
  lIdtRetorno integer;
begin

    BEGIN
          SELECT A.CAD_PAH_ID INTO lIdtRetorno FROM TB_CAD_PAH_PERC_ACRESCIMO_HR A
          WHERE
           A.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO AND
           A.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO AND
           A.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO AND           
           A.CAD_PAH_NR_DIA_SEMANA = pCAD_PAH_NR_DIA_SEMANA;
     EXCEPTION
     WHEN OTHERS THEN
          lIdtRetorno := 0;
     END;

     IF lIdtRetorno > 0 THEN

    INSERT INTO TB_CAD_PAH_PERC_ACRESCIMO_HR
    (
       CAD_TAP_TP_ATRIBUTO,
       CAD_PAH_PC_ACRESCIMO_HR,
       CAD_PAH_HR_INICIO_SEMANA,
       CAD_PAH_HR_FIM_SEMANA,
       CAD_PAH_DT_INICIO_VIGENCIA,
       CAD_PAH_DT_FIM_VIGENCIA,
       CAD_PAH_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_PAH_NR_DIA_SEMANA,
       CAD_CNV_ID_CONVENIO,
       CAD_PAH_ID
    )
    VALUES
    (
       pCAD_TAP_TP_ATRIBUTO,
       pCAD_PAH_PC_ACRESCIMO_HR,
       pCAD_PAH_HR_INICIO_SEMANA,
       pCAD_PAH_HR_FIM_SEMANA,
       pCAD_PAH_DT_INICIO_VIGENCIA,
       pCAD_PAH_DT_FIM_VIGENCIA,
       pCAD_PAH_DT_ULTIMA_ATUALIZACAO,
       pSEG_USU_ID_USUARIO,
       pCAD_LAT_ID_LOCAL_ATENDIMENTO,
       pCAD_PAH_NR_DIA_SEMANA,
       pCAD_CNV_ID_CONVENIO,
       lIdtRetorno
    );
    pNewIdt := lIdtRetorno;
    ELSE
     SELECT SEQ_CAD_PAH_01.NextVal INTO lIdtRetornoSEQ FROM DUAL;

     INSERT INTO TB_CAD_PAH_PERC_ACRESCIMO_HR
    (
       CAD_TAP_TP_ATRIBUTO,
       CAD_PAH_PC_ACRESCIMO_HR,
       CAD_PAH_HR_INICIO_SEMANA,
       CAD_PAH_HR_FIM_SEMANA,
       CAD_PAH_DT_INICIO_VIGENCIA,
       CAD_PAH_DT_FIM_VIGENCIA,
       CAD_PAH_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_PAH_NR_DIA_SEMANA,
       CAD_CNV_ID_CONVENIO,
       CAD_PAH_ID
    )
    VALUES
    (
       pCAD_TAP_TP_ATRIBUTO,
       pCAD_PAH_PC_ACRESCIMO_HR,
       pCAD_PAH_HR_INICIO_SEMANA,
       pCAD_PAH_HR_FIM_SEMANA,
       pCAD_PAH_DT_INICIO_VIGENCIA,
       pCAD_PAH_DT_FIM_VIGENCIA,
       pCAD_PAH_DT_ULTIMA_ATUALIZACAO,
       pSEG_USU_ID_USUARIO,
       pCAD_LAT_ID_LOCAL_ATENDIMENTO,
       pCAD_PAH_NR_DIA_SEMANA,
       pCAD_CNV_ID_CONVENIO,
       lIdtRetornoSEQ
    );
    pNewIdt := lIdtRetorno;
  end if;

end PRC_CAD_PAH_PERC_ACRESC_HR_I;