

--PRC_ASS_USC_UNI_SET_CCUS_CLA_I
create or replace procedure PRC_ASS_USC_UNI_SET_CCUS_CLA_I
(
     pNewIdt OUT integer,
     pASS_USC_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_ID%type default NULL,
     pCAD_UNI_ID_UNIDADE IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_UNI_ID_UNIDADE%type,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pCAD_SET_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_SET_ID%type default NULL,
     pCAD_CEC_ID_CCUSTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_CEC_ID_CCUSTO%type default NULL,
     pCAD_CAC_ID_CLASSCONTABIL IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_CAC_ID_CLASSCONTABIL%type default NULL,
     pASS_USC_FL_STATUS IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_FL_STATUS%type,
     pASS_USC_DT_ULTIMA_ATUALIZACAO IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_DT_ULTIMA_ATUALIZACAO%type,
     pSEG_USU_ID_USUARIO IN TB_ASS_USC_UNI_SET_CCUS_CLA.SEG_USU_ID_USUARIO%type,
     pAUX_EPP_CD_ESPECPROC IN TB_ASS_USC_UNI_SET_CCUS_CLA.AUX_EPP_CD_ESPECPROC%type default NULL,
     pTIS_MED_CD_TABELAMEDICA IN TB_ASS_USC_UNI_SET_CCUS_CLA.TIS_MED_CD_TABELAMEDICA%type default NULL,
     pASS_USC_DT_INICIO_VIGENCIA IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_DT_INICIO_VIGENCIA%type,
     pASS_USC_DT_FIM_VIGENCIA IN TB_ASS_USC_UNI_SET_CCUS_CLA.ASS_USC_DT_FIM_VIGENCIA%type default NULL,
     pTIS_CBO_CD_CBOS IN TB_ASS_USC_UNI_SET_CCUS_CLA.TIS_CBO_CD_CBOS%type default NULL,
     pCAD_TAP_TP_ATRIBUTO IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_TAP_TP_ATRIBUTO%type default NULL,
     pFAT_TCO_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.FAT_TCO_ID%type default NULL,
     pCAD_PRD_ID IN TB_ASS_USC_UNI_SET_CCUS_CLA.CAD_PRD_ID%type default NULL	
) 
is
/********************************************************************
*    Procedure: PRC_ASS_USC_UNI_SET_CCUS_CLA_I
* 
*	 Data Criacao: 	 12/2009    Por: Pedro
*    Data Alteracao: 06/09/2010 Por: André Souza Monaco
*         Alteração: Adição do campo FAT_TCO_ID
*
*    Data Alteracao: 24/09/2010 Por: Rafael Coimbra
*         Alteração: Adição do campo CAD_PRD_ID
*
*******************************************************************/  
    lIdtRetorno integer;
	  
begin
    SELECT SEQ_ASS_USC_01.NextVal INTO lIdtRetorno FROM DUAL;
	    
INSERT INTO TB_ASS_USC_UNI_SET_CCUS_CLA
(
       ASS_USC_ID,
       CAD_UNI_ID_UNIDADE,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_SET_ID,
       CAD_CEC_ID_CCUSTO,
       CAD_CAC_ID_CLASSCONTABIL,
       ASS_USC_FL_STATUS,
       ASS_USC_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       AUX_EPP_CD_ESPECPROC,
       TIS_MED_CD_TABELAMEDICA,
       ASS_USC_DT_INICIO_VIGENCIA,
       ASS_USC_DT_FIM_VIGENCIA,
       TIS_CBO_CD_CBOS,
       CAD_TAP_TP_ATRIBUTO,
       FAT_TCO_ID,
       CAD_PRD_ID
)
VALUES
(
      lIdtRetorno,
	     pCAD_UNI_ID_UNIDADE,
	     pCAD_LAT_ID_LOCAL_ATENDIMENTO,
	     pCAD_SET_ID,
	     pCAD_CEC_ID_CCUSTO,
	     pCAD_CAC_ID_CLASSCONTABIL,
	     pASS_USC_FL_STATUS,
	     pASS_USC_DT_ULTIMA_ATUALIZACAO,
	     pSEG_USU_ID_USUARIO,
	     pAUX_EPP_CD_ESPECPROC,
	     pTIS_MED_CD_TABELAMEDICA,
	     pASS_USC_DT_INICIO_VIGENCIA,
	     pASS_USC_DT_FIM_VIGENCIA,
	     pTIS_CBO_CD_CBOS,
	     pCAD_TAP_TP_ATRIBUTO,
	     pFAT_TCO_ID,
	     pCAD_PRD_ID
);
    pNewIdt := lIdtRetorno;	
end PRC_ASS_USC_UNI_SET_CCUS_CLA_I;

