create or replace procedure PRC_ASS_IPA_ITEMPACOTE_L
(    
     pCAD_PRD_ID_PACOTE IN TB_CAD_IPA_ITEM_PACOTE.CAD_PRD_ID_PACOTE%type,
     io_cursor OUT PKG_CURSOR.t_cursor
) 
is
v_cursor PKG_CURSOR.t_cursor;
begin
OPEN v_cursor FOR

SELECT IPA.CAD_IPA_ID,
       IPA.CAD_PRD_ID_PACOTE,
       IPA.CAD_IPA_VL_ITEM_PACOTE,
       IPA.CAD_IPA_PC_RATEIO,
       IPA.CAD_IPA_DT_INICIO_VIGENCIA,
       IPA.CAD_IPA_DT_FIM_VIGENCIA,
       IPA.SEG_USU_ID_USUARIO,
       IPA.CAD_IPA_FL_STATUS,
       IPA.CAD_IPA_PC_DESCONTO,
       IPA.CAD_IPA_PC_ACRESCIMO,
       IPA.CAD_IPA_DS_OBSERVACAO,
       IPA.CAD_IPA_DT_ULTIMA_ATUALIZACAO,
       IPA.CAD_PRD_ID_ITEM_PACOTE,
       IPA.CAD_IPA_VL_ORIG_ITEM_PRODUTO,
       IPA.CAD_IPA_VL_ACRESCIMO,
       IPA.CAD_IPA_VL_DESCONTO,
       IPA.CAD_IPA_VL_FINAL_PACOTE,
       IPA.CAD_IPA_QT_ITEM_PACOTE,
       IPA.CAD_IPA_NR_DIVISOR_PACOTE,
       IPA.CAD_IPA_VL_PROPORCIONAL,
       PRD.CAD_PRD_CD_CODIGO,
       PRD.CAD_PRD_DS_DESCRICAO
  FROM TB_CAD_IPA_ITEM_PACOTE IPA,
       TB_CAD_PRD_PRODUTO PRD     
WHERE
     IPA.CAD_PRD_ID_ITEM_PACOTE = PRD.CAD_PRD_ID               
     AND IPA.CAD_IPA_FL_STATUS = 'A'
     AND FNC_VALIDAR_VIGENCIA(IPA.CAD_IPA_DT_INICIO_VIGENCIA, IPA.CAD_IPA_DT_FIM_VIGENCIA) = 1
     AND IPA.CAD_PRD_ID_PACOTE = pCAD_PRD_ID_PACOTE;
io_cursor := v_cursor;
end PRC_ASS_IPA_ITEMPACOTE_L;