CREATE OR REPLACE PROCEDURE PRC_AGS_AGE_INFO_PAC
(
       pATD_ATE_ID IN TB_ASS_PAP_PAC_ATEN_PROC.ATD_ATE_ID%TYPE,
       io_cursor OUT PKG_CURSOR.t_cursor
)
IS
       v_cursor PKG_CURSOR.t_cursor;
idtPreCadastro INT;
idtLiberacao INT;
idtInternacao INT;
BEGIN
SELECT COUNT(*) INTO idtPreCadastro FROM TB_ATD_IAE_INT_AGE_ELETIVA IAE WHERE IAE.ATD_IAE_ID = pATD_ATE_ID;
SELECT COUNT(*) INTO idtLiberacao FROM TB_ASS_PAP_PAC_ATEN_PROC PAP WHERE PAP.ATD_ATE_ID = pATD_ATE_ID;
SELECT COUNT(*) INTO idtInternacao FROM TB_ATD_ATE_ATENDIMENTO ATD
                                   JOIN TB_ATD_AIC_ATE_INT_COMPL AIC
                                   ON   AIC.ATD_ATE_ID = ATD.ATD_ATE_ID
                                   WHERE ATD.ATD_ATE_ID = pATD_ATE_ID;
 if idtLiberacao > 0 THEN
  OPEN v_cursor FOR
    SELECT DISTINCT
           PAC.CAD_PAC_ID_PACIENTE,
           PAC.CAD_CNV_ID_CONVENIO,
           PAC.CAD_PLA_ID_PLANO,
           PAC.CAD_PAC_CD_CREDENCIAL,
           PES_PAC.CAD_PES_NM_PESSOA,
           PLA.CAD_PLA_CD_PLANO,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           PAP.CAD_UNI_ID_UNIDADE,
           PAP.CAD_LAT_ID_LOCAL_ATENDIMENTO,
           PAC.CAD_PAC_NR_PRONTUARIO,
           PES_PAC.CAD_PES_NR_RG,
           PES_PAC.CAD_PES_DT_NASCIMENTO,
           PES_PAC.CAD_PES_TP_SEXO,
           PAC.CAD_PAC_NM_TITULAR,
           PAC.CAD_PAC_CD_SUBPLANO,
           PAP.ASS_PAP_FL_CARATER_SOLIC
      FROM TB_ASS_PAP_PAC_ATEN_PROC PAP
INNER JOIN TB_CAD_PAC_PACIENTE      PAC
        ON PAC.CAD_PAC_ID_PACIENTE = PAP.CAD_PAC_ID_PACIENTE
INNER JOIN TB_CAD_PES_PESSOA        PES_PAC
        ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
INNER JOIN TB_CAD_PLA_PLANO         PLA
        ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
INNER JOIN TB_CAD_CNV_CONVENIO      CNV
        ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
     WHERE PAP.ATD_ATE_ID = pATD_ATE_ID;
io_cursor := v_cursor;
END IF;
IF idtPreCadastro > 0 THEN
  OPEN v_cursor FOR
    SELECT DISTINCT
           PAC.CAD_PAC_ID_PACIENTE,
           PAC.CAD_CNV_ID_CONVENIO,
           PAC.CAD_PLA_ID_PLANO,
           PAC.CAD_PAC_CD_CREDENCIAL,
           PES_PAC.CAD_PES_NM_PESSOA,
           PLA.CAD_PLA_CD_PLANO,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           IAE.CAD_UNI_ID_UNIDADE,
           IAE.CAD_LAT_ID_LOCAL_ATENDIMENTO,
           PAC.CAD_PAC_NR_PRONTUARIO,
           PES_PAC.CAD_PES_NR_RG,
           PES_PAC.CAD_PES_DT_NASCIMENTO,
           PES_PAC.CAD_PES_TP_SEXO,
           PAC.CAD_PAC_NM_TITULAR,
           PAC.CAD_PAC_CD_SUBPLANO,
           '' ASS_PAP_FL_CARATER_SOLIC
      FROM TB_ATD_IAE_INT_AGE_ELETIVA IAE
INNER JOIN TB_CAD_PAC_PACIENTE PAC
        ON PAC.CAD_PAC_ID_PACIENTE = IAE.CAD_PAC_ID_PACIENTE
INNER JOIN TB_CAD_PES_PESSOA PES_PAC
        ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
INNER JOIN TB_CAD_PLA_PLANO PLA
        ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
INNER JOIN TB_CAD_CNV_CONVENIO CNV
        ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
     WHERE IAE.ATD_IAE_ID = pATD_ATE_ID;
io_cursor := v_cursor;
end if;
IF idtInternacao > 0 THEN
  OPEN v_cursor FOR
    SELECT DISTINCT
           PAC.CAD_PAC_ID_PACIENTE,
           PAC.CAD_CNV_ID_CONVENIO,
           PAC.CAD_PLA_ID_PLANO,
           PAC.CAD_PAC_CD_CREDENCIAL,
           PES_PAC.CAD_PES_NM_PESSOA,
           PLA.CAD_PLA_CD_PLANO,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           ATD.CAD_UNI_ID_UNIDADE,
           ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO,
           PAC.CAD_PAC_NR_PRONTUARIO,
           PES_PAC.CAD_PES_NR_RG,
           PES_PAC.CAD_PES_DT_NASCIMENTO,
           PES_PAC.CAD_PES_TP_SEXO,
           PAC.CAD_PAC_NM_TITULAR,
           PAC.CAD_PAC_CD_SUBPLANO,
           '' ASS_PAP_FL_CARATER_SOLIC
      FROM TB_ATD_ATE_ATENDIMENTO   ATD
INNER JOIN TB_ATD_AIC_ATE_INT_COMPL AIC
        ON AIC.ATD_ATE_ID = ATD.ATD_ATE_ID
INNER JOIN TB_ASS_PAT_PACIEATEND    PAT
        ON PAT.ATD_ATE_ID = ATD.ATD_ATE_ID
INNER JOIN TB_CAD_PAC_PACIENTE      PAC
        ON PAC.CAD_PAC_ID_PACIENTE = fnc_buscar_paciente_atual(PAT.ATD_ATE_ID)
INNER JOIN TB_CAD_PES_PESSOA        PES_PAC
        ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
INNER JOIN TB_CAD_PLA_PLANO         PLA
        ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
INNER JOIN TB_CAD_CNV_CONVENIO      CNV
        ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
     WHERE ATD.ATD_ATE_ID = pATD_ATE_ID;
io_cursor := v_cursor;
END IF;
--
IF (idtInternacao = 0 and idtLiberacao = 0 and idtPreCadastro = 0) THEN
dbms_output.put_line ('fitas');
  OPEN v_cursor FOR
 SELECT DISTINCT
           PAC.CAD_PAC_ID_PACIENTE,
           PAC.CAD_CNV_ID_CONVENIO,
           PAC.CAD_PLA_ID_PLANO,
           PAC.CAD_PAC_CD_CREDENCIAL,
           PES_PAC.CAD_PES_NM_PESSOA,
           PLA.CAD_PLA_CD_PLANO,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           SETOR.CAD_UNI_ID_UNIDADE,
           SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO,
           PAC.CAD_PAC_NR_PRONTUARIO,
           PES_PAC.CAD_PES_NR_RG,
           PES_PAC.CAD_PES_DT_NASCIMENTO,
           PES_PAC.CAD_PES_TP_SEXO,
           PAC.CAD_PAC_NM_TITULAR,
           PAC.CAD_PAC_CD_SUBPLANO,
           '' ASS_PAP_FL_CARATER_SOLIC
      FROM TB_ATS_ATE_ATENDIMENTO_SADT   ATS
INNER JOIN TB_CAD_PAC_PACIENTE      PAC
        ON PAC.CAD_PAC_ID_PACIENTE = ATS.CAD_PAC_ID_PACIENTE_INT
INNER JOIN TB_CAD_PES_PESSOA        PES_PAC
        ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
INNER JOIN TB_CAD_PLA_PLANO         PLA
        ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
INNER JOIN TB_CAD_CNV_CONVENIO      CNV
        ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
LEFT JOIN  TB_CAD_SET_SETOR SETOR
        ON SETOR.CAD_SET_ID = ATS.CAD_SET_ID
     WHERE ATS.ATS_ATE_CD_INTLIB = pATD_ATE_ID
     and rownum =1;
io_cursor := v_cursor;

END IF;


END PRC_AGS_AGE_INFO_PAC;
/
