create or replace procedure PRC_ATS_ATE_ATENDSADT_ANEST_U
  (
     pATS_ATE_CD_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_CD_INTLIB%type,
     pATS_ATE_IN_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_IN_INTLIB%type,
     pATS_ATE_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_ID%type,
     pCAD_PRD_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRD_ID%type,
   pATS_ATE_DT_ULTIMA_ATUALIZACAO IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DT_ULTIMA_ATUALIZACAO%type,
     pSEG_USU_ID_USUARIO IN TB_ATS_ATE_ATENDIMENTO_SADT.SEG_USU_ID_USUARIO%type,
     pAUX_EPP_CD_ESPECPROC IN TB_ATS_ATE_ATENDIMENTO_SADT.AUX_EPP_CD_ESPECPROC%type,
        pATS_ATE_FL_ANESTESIA IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_ANESTESIA%type,
     pCAD_PRO_ID_PROF_ANEST IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRO_ID_PROF_ANEST%type,
     pTIS_MED_CD_TABELAMEDICA IN TB_ATS_ATE_ATENDIMENTO_SADT.TIS_MED_CD_TABELAMEDICA%TYPE
  
     
  ) 
  is
  /********************************************************************
  *    Procedure: PRC_ATS_ATE_ATENDSADT_ANEST_U
  * 
  *    Data Criacao:   data da  criação   Por: Nome do Analista
 *    Data Alteracao:  04/02/2010  Por: Pedro
  *    Alteracao: 3 campos novos
  *
  *    Data Alteracao:  29/03/2010  Por: Pedro
  *    Alteracao: pTIS_MED_CD_TABELAMEDICA
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/  
  begin
    UPDATE TB_ATS_ATE_ATENDIMENTO_SADT
    SET     
         ATS_ATE_DT_ULTIMA_ATUALIZACAO = pATS_ATE_DT_ULTIMA_ATUALIZACAO,
        SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO,
         ATS_ATE_FL_ANESTESIA = pATS_ATE_FL_ANESTESIA,
       CAD_PRO_ID_PROF_ANEST = pCAD_PRO_ID_PROF_ANEST
        
    WHERE
        ATS_ATE_CD_INTLIB = pATS_ATE_CD_INTLIB
    AND ATS_ATE_ID = pATS_ATE_ID
    AND ATS_ATE_IN_INTLIB = pATS_ATE_IN_INTLIB
    AND AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC
    AND CAD_PRD_ID = pCAD_PRD_ID
    AND TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA;  
  end PRC_ATS_ATE_ATENDSADT_ANEST_U;
/
