CREATE OR REPLACE PROCEDURE PRC_INT_REL_PRE_CADASTRO
(
pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pFAIXA_ETARIA_INI varchar2 default null,
pFAIXA_ETARIA_FIM varchar2 default null,
pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
pCAD_SET_NR_ANDAR IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pCAD_QLE_TP_QUARTO_LEITO IN TB_CAD_QLE_QUARTO_LEITO.CAD_QLE_TP_QUARTO_LEITO%TYPE DEFAULT NULL,
pTIS_TIN_CD_INTER IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
pTIS_TRI_CD_TP_REGINT IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
pTIS_TAC_CD_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%TYPE DEFAULT NULL,
pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
pATD_IAE_CD_UFCONSELHO_SOLIC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_SG_UF_CONSELHO%TYPE DEFAULT NULL,
pATD_IAE_NR_CONSELHO_SOLIC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_NR_CONSELHO%TYPE DEFAULT NULL,
pTIS_CPR_CD_CONSELHOPROF_SOLIC IN TB_CAD_PRO_PROFISSIONAL.TIS_CPR_CD_CONSELHOPROF%TYPE DEFAULT NULL,
pCAD_PES_TP_SEXO IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
pCAD_UNI_ID_UNID_PROC    IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNID_PROC%TYPE DEFAULT NULL,
pADMITIDOS_S varchar2 default null,
pADMITIDOS_N varchar2 default null,
pCAD_CGC_ID_G IN TB_CAD_CNV_CONVENIO.CAD_CGC_ID%TYPE DEFAULT NULL,
pCAD_CGC_ID_E IN TB_CAD_CNV_CONVENIO.CAD_CGC_ID%TYPE DEFAULT NULL,
   io_cursor              OUT PKG_CURSOR.t_cursor) is
  /********************************************************************
  *    Procedure: PRC_INT_REL_PRE_CADASTRO
  *
  *    Data Alteracao: 20/06/2011   Por: PEDRO
  *    Alteracao: add IAE.ATD_IAE_DT_AGENDA,     IAE.ATD_IAE_HR_AGENDA, pADMITIDOS_S e pADMITIDOS_N
  *    Data Alteracao:03/11/2011   Por:Eduardo Hyppolito
  *    Alteração: Campo Instituto Geriatria (LEFT JOIN BENEFICIARIO)
  *    Funcao: Popula o Relatorio de Pre Cadastrados
  *    Alterado em 07/03/2012 Por Eduardo Hyppolito Para: apresentar CNS
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
begin
  OPEN v_cursor FOR
 SELECT DISTINCT
               IAE.ATD_IAE_ID ATD_ATE_ID,
               UNI.CAD_UNI_DS_UNIDADE UNIDADE,
               UNI.CAD_UNI_ID_UNIDADE,
               LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
               PAC.CAD_PAC_CD_CREDENCIAL,
               PAC.CAD_PAC_NR_PRONTUARIO,
               PES.CAD_PES_NM_PESSOA PACIENTE,
               PES.CAD_PES_DT_NASCIMENTO,
               PES.CAD_PES_TP_SEXO,
               fnc_cad_pes_municipio_s(pes.cad_pes_id_pessoa,1) AUX_MUN_NM_MUNICIPIO,
               CBOS.TIS_CBO_DS_CBOS_HAC,
               CNV.CAD_CNV_CD_HAC_PRESTADOR,
               PLA.CAD_PLA_CD_TIPOPLANO,
               PLA.CAD_PLA_CD_PLANO_HAC,
               IAE.ATD_IAE_DT_ATENDIMENTO ATD_ATE_DT_ATENDIMENTO,
               IAE.ATD_IAE_HR_ATENDIMENTO ATD_ATE_HR_ATENDIMENTO,
               IAE.ATD_IAE_DT_AGENDA,
               IAE.ATD_IAE_HR_AGENDA,
            --   PES_PRO.CAD_PES_NM_PESSOA PROFISSIONAL,
               DECODE(PRO.CAD_PRO_NM_NOME,'',PSO.CAD_PSO_NM_PROFISSIONAL,PRO.CAD_PRO_NM_NOME) PROFISSIONAL,
               DECODE(PRO.CAD_PRO_NR_CONSELHO,'',PSO.CAD_PSO_CD_CONSELHO,PRO.CAD_PRO_NR_CONSELHO) CAD_PRO_NR_CONSELHO,
               DECODE(PRO.CAD_PRO_SG_UF_CONSELHO,'',PSO.CAD_PSO_SG_UF_CONSELHO,PRO.CAD_PRO_SG_UF_CONSELHO) CAD_PRO_SG_UF_CONSELHO,
               CID.CAD_CID_DS_CID10,
               TIN.TIS_TIN_DS_INTERNACAO,
               TRI.TIS_TRI_DS_TP_REGINTERNACAO,
               PRD.CAD_PRD_NM_MNEMONICO,
               PRD.CAD_PRD_CD_CODIGO,
               PRD.CAD_PRD_DS_DESCRICAO,
               PES.CAD_PES_CD_CNS_SUS,
               IGE_BNF.GER,
               Floor(floor(months_between(SYSDATE, pes.cad_pes_dt_nascimento)) / 12) idade
  FROM
                TB_ATD_IAE_INT_AGE_ELETIVA    IAE
  JOIN          TB_CAD_PAC_PACIENTE       PAC
  ON            PAC.CAD_PAC_ID_PACIENTE = IAE.CAD_PAC_ID_PACIENTE
  JOIN          TB_CAD_PES_PESSOA         PES
  ON            PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
  JOIN          TB_CAD_CNV_CONVENIO       CNV
  ON            CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
  JOIN          TB_CAD_PLA_PLANO          PLA
  ON            PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
  JOIN          TB_TIS_CBO_CBOS             CBOS
  ON            CBOS.TIS_CBO_CD_CBOS      = IAE.TIS_CBO_CD_CBOS
  JOIN          TB_CAD_UNI_UNIDADE          UNI
  ON            UNI.CAD_UNI_ID_UNIDADE    = IAE.CAD_UNI_ID_UNIDADE
  JOIN          TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
  ON            LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = IAE.CAD_LAT_ID_LOCAL_ATENDIMENTO
  LEFT JOIN     TB_CAD_PRO_PROFISSIONAL PRO
  ON            PRO.TIS_CPR_CD_CONSELHOPROF = IAE.TIS_CPR_CD_CONSELHOPROF_SOLIC
  and           PRO.CAD_PRO_NR_CONSELHO    = IAE.ATD_IAE_NR_CONSELHO_SOLIC
  AND           PRO.CAD_PRO_SG_UF_CONSELHO = IAE.ATD_IAE_CD_UFCONSELHO_SOLIC
  LEFT JOIN     TB_CAD_PSO_PROF_SOLICITANTE PSO
  ON            PSO.TIS_CPR_CD_CONSELHOPROF = IAE.TIS_CPR_CD_CONSELHOPROF_SOLIC
  and           PSO.CAD_PSO_CD_CONSELHO    = IAE.ATD_IAE_NR_CONSELHO_SOLIC
  AND           PSO.CAD_PSO_SG_UF_CONSELHO = IAE.ATD_IAE_CD_UFCONSELHO_SOLIC
  LEFT JOIN     TB_CAD_CID_CID10            CID
  ON            CID.CAD_CID_CD_CID10      = IAE.CAD_CID_CD_CID10
  LEFT JOIN     TB_TIS_TIN_TP_INTERNACAO    TIN
  ON            TIN.TIS_TIN_CD_INTERNACAO = IAE.TIS_TIN_CD_INTERNACAO
  LEFT JOIN     TB_TIS_TRI_TP_REGINTERNACAO TRI
  ON            TRI.TIS_TRI_CD_TP_REGINTERNACAO = IAE.TIS_TRI_CD_REGINTERNACAO
  LEFT JOIN    (SELECT BNF_SIT.DESSITBEN, BNF.DATINGCONBEN, BNF.DATSITBEN, BNF.DATALTBEN,PAC.CAD_PAC_ID_PACIENTE,
                DECODE       (FNC_VERIFICA_INSGER(BNF.CODCON, BNF.CODEST, BNF.CODBEN, BNF.CODSEQBEN),0,'',1,'I.GER',2,'I.GER',4,'A.ALTA') GER
                FROM          TB_CAD_PAC_PACIENTE       PAC
                JOIN          TB_CAD_PLA_PLANO          PLA
                ON            PAC.CAD_PLA_ID_PLANO    = PLA.CAD_PLA_ID_PLANO
                JOIN          BNF_BENEFICIARIO          BNF
                ON            TO_CHAR(BNF.CODCON)     = TO_CHAR(PLA.CAD_PLA_CD_PLANO_HAC)
                AND           BNF.CODEST              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,0,3))
                AND           BNF.CODBEN              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,4,7))
                AND           BNF.CODSEQBEN           = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,11,2))
                JOIN          BNF_SITUACAO_BENEF        BNF_SIT
                ON            BNF_SIT.CODSITBEN       = BNF.CODSITBEN
                WHERE         pac.CAD_CNV_ID_CONVENIO = 281
  ) IGE_BNF
  ON           IGE_BNF.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
  LEFT JOIN     TB_CAD_PRD_PRODUTO          PRD
  ON            PRD.CAD_PRD_ID            = IAE.CAD_PRD_ID
   WHERE
       (pCAD_UNI_ID_UNIDADE IS NULL OR IAE.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
   AND (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR IAE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
    --AND (pCAD_SET_ID IS NULL OR IML_QLE.CAD_SET_ID = pCAD_SET_ID)
   AND (pATD_ATE_HR_ATENDIMENTO_INI IS NULL OR IAE.ATD_IAE_HR_ATENDIMENTO BETWEEN pATD_ATE_HR_ATENDIMENTO_INI AND pATD_ATE_HR_ATENDIMENTO_FIM)
   AND (pFAIXA_ETARIA_INI IS NULL OR FLOOR(FLOOR(MONTHS_BETWEEN(SYSDATE, PES.CAD_PES_DT_NASCIMENTO)) / 12) BETWEEN pFAIXA_ETARIA_INI AND pFAIXA_ETARIA_FIM)
   AND (pTIS_CBO_CD_CBOS IS NULL OR IAE.TIS_CBO_CD_CBOS = pTIS_CBO_CD_CBOS)
   AND (pTIS_CPR_CD_CONSELHOPROF_SOLIC IS NULL OR IAE.TIS_CPR_CD_CONSELHOPROF_SOLIC = pTIS_CPR_CD_CONSELHOPROF_SOLIC)
   AND (pATD_IAE_NR_CONSELHO_SOLIC IS NULL OR IAE.ATD_IAE_NR_CONSELHO_SOLIC = pATD_IAE_NR_CONSELHO_SOLIC)
   AND (pATD_IAE_CD_UFCONSELHO_SOLIC IS NULL OR IAE.ATD_IAE_CD_UFCONSELHO_SOLIC = pATD_IAE_CD_UFCONSELHO_SOLIC)
   AND (pATD_ATE_TP_PACIENTE_I IS NOT NULL AND IAE.ATD_IAE_TP_PACIENTE = 'I'
    OR pATD_ATE_TP_PACIENTE_E IS NOT NULL AND IAE.ATD_IAE_TP_PACIENTE = 'E')
   AND (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
   AND (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
   AND (pCAD_PRD_ID IS NULL OR IAE.CAD_PRD_ID = pCAD_PRD_ID)
   AND (pCAD_PES_TP_SEXO IS NULL OR PES.CAD_PES_TP_SEXO = pCAD_PES_TP_SEXO)
   AND (pTIS_TIN_CD_INTER IS NULL OR TIN.TIS_TIN_CD_INTERNACAO = pTIS_TIN_CD_INTER)
   AND (pTIS_TRI_CD_TP_REGINT IS NULL OR TRI.TIS_TRI_CD_TP_REGINTERNACAO = pTIS_TRI_CD_TP_REGINT)
   AND (pCAD_CGC_ID_G IS NOT NULL AND CNV.CAD_CGC_ID = 1 OR pCAD_CGC_ID_E IS NOT NULL AND CNV.CAD_CGC_ID = 2)
   AND (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = 'GB'
   OR pCAD_PLA_CD_TIPOPLANO_PL IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PL'
   OR pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PA'
   OR pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'SP'
   OR pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'FU')
   AND (PLA.CAD_PLA_CD_TIPOPLANO != 'NP')
   AND (pCAD_UNI_ID_UNID_PROC IS NULL OR IAE.CAD_UNI_ID_UNID_PROC = pCAD_UNI_ID_UNID_PROC)
   AND (pADMITIDOS_S IS not NULL and exists (select aic.atd_ate_id from tb_atd_aic_ate_int_compl aic where aic.atd_ate_id = iae.atd_iae_id)
   OR pADMITIDOS_N IS NOT NULL AND not exists (select aic.atd_ate_id from tb_atd_aic_ate_int_compl aic where aic.atd_ate_id = iae.atd_iae_id))
  -- AND (pADMITIDOS_N is null or
   --    not exists (select aic.atd_ate_id from tb_atd_aic_ate_int_compl aic where aic.atd_ate_id = iae.atd_iae_id)
    --    )
   AND (IAE.ATD_IAE_FL_STATUS = 'A')
  AND ((pATD_ATE_DT_ATENDIMENTO_INI IS NULL) OR (IAE.ATD_IAE_DT_ATENDIMENTO >= pATD_ATE_DT_ATENDIMENTO_INI ))
  AND ((pATD_ATE_DT_ATENDIMENTO_FIM IS NULL) OR (IAE.ATD_IAE_DT_ATENDIMENTO <= pATD_ATE_DT_ATENDIMENTO_FIM))
  --AND ((pATD_ATE_DT_ATENDIMENTO_INI IS NULL) OR (IAE.ATD_IAE_DT_AGENDA >= pATD_ATE_DT_ATENDIMENTO_INI ))
  --AND ((pATD_ATE_DT_ATENDIMENTO_FIM IS NULL) OR (IAE.ATD_IAE_DT_AGENDA <= pATD_ATE_DT_ATENDIMENTO_FIM))
  -- AND ((pATD_ATE_DT_ATENDIMENTO_INI IS NULL) OR (ATD.ATD_ATE_DT_ATENDIMENTO >= pATD_ATE_DT_ATENDIMENTO_INI ))
  -- AND ((pATD_ATE_DT_ATENDIMENTO_FIM IS NULL) OR (ATD.ATD_ATE_DT_ATENDIMENTO <= pATD_ATE_DT_ATENDIMENTO_FIM))
  ;
  io_cursor := v_cursor;
end PRC_INT_REL_PRE_CADASTRO;