CREATE OR REPLACE PROCEDURE SGS.PRC_COB_INADIMPLENTES_L
  (
    pDATA_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pDATA_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_PAC_NR_PRONTUARIO IN TB_CAD_PAC_PACIENTE.CAD_PAC_NR_PRONTUARIO%TYPE DEFAULT NULL,
    pCAD_PES_NM_PESSOA IN TB_CAD_PES_PESSOA.CAD_PES_NM_PESSOA%TYPE DEFAULT NULL,
    pCAD_PES_DT_NASCIMENTO IN TB_CAD_PES_PESSOA.CAD_PES_DT_NASCIMENTO%TYPE DEFAULT NULL,
    pCAD_PES_TP_SEXO IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
    pATD_ATE_ID IN TB_COB_CCP_CONTA_CONS_PARC.ATD_ATE_ID%TYPE DEFAULT NULL,
    pCOB_CCP_ID IN TB_COB_CCP_CONTA_CONS_PARC.COB_CCP_ID%TYPE DEFAULT NULL,
    pFAT_NOF_NR_NOTAFISCAL IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_NR_NOTAFISCAL%TYPE DEFAULT NULL,
    pFAT_NOF_TP_SERIEFISCAL IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_TP_SERIEFISCAL%TYPE DEFAULT NULL,
    pPES_PAC_RESP NUMBER,
    pINCLUSAO NUMBER,
  --  TESTE OUT LONG,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_COB_INADIMPLENTES_L
  *
  *    Data Criação: 05/09/2012  Por: PEDRO
  *    Alteracao:
  *
  *
  *******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_SELECT  varchar2(5000);
begin
  V_WHERE := NULL;
IF pDATA_INI IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO >= TO_DATE('||CHR(39)||TO_CHAR(pDATA_INI,'DDMMYYYY')||CHR(39)||','||CHR(39)||'DDMMYYYY'||CHR(39)|| ')' ; END IF;
IF pDATA_FIM IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.ATD_ATE_DT_ATENDIMENTO <= TO_DATE('||CHR(39)||TO_CHAR(pDATA_FIM,'DDMMYYYY')||CHR(39)||','||CHR(39)||'DDMMYYYY'||CHR(39)|| ')' ; END IF;
IF pATD_ATE_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCP.ATD_ATE_ID = ' || pATD_ATE_ID; END IF;
IF pFAT_NOF_NR_NOTAFISCAL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND NOF.FAT_NOF_NR_NOTAFISCAL = ' ||CHR(39)|| pFAT_NOF_NR_NOTAFISCAL ||CHR(39); END IF;
IF pFAT_NOF_TP_SERIEFISCAL IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND NOF.FAT_NOF_TP_SERIEFISCAL = ' ||CHR(39)|| pFAT_NOF_TP_SERIEFISCAL ||CHR(39); END IF;
IF pCOB_CCP_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ARE.FAT_CCP_ID = ' || pCOB_CCP_ID; END IF;
IF pINCLUSAO = '1' THEN V_WHERE:= V_WHERE || ' AND REA.ATD_ATE_ID IS NULL ';
   ELSE V_WHERE:= V_WHERE || ' AND REA.ATD_ATE_ID IS NOT NULL ';
END IF;

IF pPES_PAC_RESP = '0' THEN
  BEGIN
  IF pCAD_PES_NM_PESSOA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES.CAD_PES_NM_PESSOA LIKE ' || CHR(39) || '%' || pCAD_PES_NM_PESSOA || '%' || CHR(39); END IF;
  IF pCAD_PES_DT_NASCIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES.CAD_PES_DT_NASCIMENTO = TO_DATE('||CHR(39)||TO_CHAR(pCAD_PES_DT_NASCIMENTO,'DDMMYYYY')||CHR(39)||','||CHR(39)||'DDMMYYYY'||CHR(39)|| ')' ; END IF;
  IF pCAD_PES_TP_SEXO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES.CAD_PES_TP_SEXO = ' || CHR(39) || pCAD_PES_TP_SEXO || CHR(39); END IF;
  END;
END IF;
IF pPES_PAC_RESP = '1' THEN
  BEGIN
  IF pCAD_PES_NM_PESSOA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES_RESP.CAD_PES_NM_PESSOA LIKE ' || CHR(39) || '%' || pCAD_PES_NM_PESSOA || '%' || CHR(39); END IF;
  IF pCAD_PES_DT_NASCIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES_RESP.CAD_PES_DT_NASCIMENTO = TO_DATE('||CHR(39)||TO_CHAR(pCAD_PES_DT_NASCIMENTO,'DDMMYYYY')||CHR(39)||','||CHR(39)||'DDMMYYYY'||CHR(39)|| ')' ; END IF;
  IF pCAD_PES_TP_SEXO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES_RESP.CAD_PES_TP_SEXO = ' || CHR(39) || pCAD_PES_TP_SEXO || CHR(39); END IF;
  END;
END IF;
--IF pCAD_PES_NM_PESSOA_RESP IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES_RESP.CAD_PES_NM_PESSOA LIKE ' || CHR(39) || '%' || pCAD_PES_NM_PESSOA || '%' || CHR(39); END IF;
--IF pCAD_PES_DT_NASCIMENTO_RESP IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES_RESP.CAD_PES_DT_NASCIMENTO = TO_DATE('||CHR(39)||TO_CHAR(pCAD_PES_DT_NASCIMENTO,'DDMMYYYY')||CHR(39)||','||CHR(39)||'DDMMYYYY'||CHR(39)|| ')' ; END IF;
--IF pCAD_PES_TP_SEXO_RESP IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PES_RESP.CAD_PES_TP_SEXO = ' || CHR(39) || pCAD_PES_TP_SEXO || CHR(39); END IF;
IF pCAD_PAC_NR_PRONTUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PAC.CAD_PAC_NR_PRONTUARIO = ' || pCAD_PAC_NR_PRONTUARIO; END IF;
V_SELECT := '
            SELECT PAC.CAD_PAC_ID_PACIENTE,
                   PAC.CAD_PES_ID_PESSOA,
                   NOF.FAT_NOF_NR_NOTAFISCAL,
                   NOF.FAT_NOF_TP_SERIEFISCAL,
                   ATE.ATD_ATE_ID,
                   ARE.FAT_CCP_ID,
                   PES.CAD_PES_NM_PESSOA ,
                   PES.CAD_PES_DT_NASCIMENTO ,
                   PES.CAD_PES_TP_SEXO ,
                   PES.CAD_PES_NR_CNPJ_CPF ,
                   PES.CAD_PES_NR_RG  ,
                   PES.CAD_PES_CD_ORGAOEMISSORRG ,
                   PES.CAD_PES_NM_NOMEMAE ,
                   PES.CAD_PES_NM_NOMEPAI ,
                   PAC.CAD_PAC_NR_PRONTUARIO,
                   CASE WHEN REA.CAD_REA_DT_FIM_VIGENCIA IS NULL OR REA.CAD_REA_DT_FIM_VIGENCIA < SYSDATE THEN '||CHR(39)||'N'||CHR(39)||' ELSE '||CHR(39)||'S'||CHR(39)||' END FL_INADIMPLENTE,
                 --  CASE WHEN PAC.CAD_PAC_FL_RESTRICAO_PA_OK IS NULL THEN '||CHR(39)||'N'||CHR(39)||' ELSE PAC.CAD_PAC_FL_RESTRICAO_PA_OK END CAD_PAC_FL_RESTRICAO_PA_OK,
                   
                   DECODE(ATE.ATD_ATE_TP_PACIENTE,'||CHR(39)||'I'||CHR(39)||','||CHR(39)||'INTERNADO'||CHR(39)||','||CHR(39)||'E'||CHR(39)||','||CHR(39)||'EXTERNO'||CHR(39)||','||CHR(39)||'A'||CHR(39)||','||CHR(39)||'AMBULATORIO'||CHR(39)||','||CHR(39)||'U'||CHR(39)||','||CHR(39)||'PRONTO SOCORRO'||CHR(39)||') ATD_ATE_TP_PACIENTE,
                   UNI.CAD_UNI_DS_UNIDADE,
                   NULL CONTROLE_SALVAR,
                   PES_RESP.CAD_PES_ID_PESSOA CAD_PES_ID_PESSOA_RESPONSAVEL,
                   PES_RESP.CAD_PES_NM_PESSOA CAD_PES_NM_PESSOA_RESP,
                   PES_RESP.CAD_PES_DT_NASCIMENTO CAD_PES_DT_NASCIMENTO_RESP,
                   PES_RESP.CAD_PES_TP_SEXO CAD_PES_TP_SEXO_RESP,
                   PES_RESP.CAD_PES_NR_CNPJ_CPF CAD_PES_NR_CNPJ_CPF_RESP,
                   PES_RESP.CAD_PES_NR_RG  CAD_PES_NR_RG_RESP,
                   PES_RESP.CAD_PES_CD_ORGAOEMISSORRG CAD_PES_CD_ORGAOEMISSORRG_RESP,
                   PES_RESP.CAD_PES_NM_NOMEMAE CAD_PES_NM_NOMEMAE_RESP,
                   PES_RESP.CAD_PES_NM_NOMEPAI CAD_PES_NM_NOMEPAI_RESP,
                   REA.CAD_REA_DT_INICIO_VIGENCIA,
                   REA.CAD_REA_DT_FIM_VIGENCIA,
                   REA.SEG_USU_ID_USUARIO_CRIACAO,
                   USU_CRI.SEG_USU_DS_NOME SEG_USU_DS_NOME_CRIACAO,
                   REA.CAD_REA_DT_CRIACAO,
                   REA.SEG_USU_ID_USUARIO_ATUALIZ,
                   USU_ATU.SEG_USU_DS_NOME SEG_USU_DS_NOME_ATUALIZACAO,
                   REA.CAD_REA_DT_ULTIMA_ATUALIZ,
                   NOF.FAT_NOF_ID,
                   NOF.FAT_NFO_DT_EMISSAO,
                   REA.CAD_REA_DS_OBSERVACAO
            FROM      TB_ASS_ARE_ATD_RESPONSAVEL ARE 
            JOIN      TB_FAT_CCP_CONTA_CONS_PARC CCP      ON  CCP.ATD_ATE_ID          = ARE.ATD_ATE_ID
                                                          AND CCP.FAT_CCP_ID          = ARE.FAT_CCP_ID
            JOIN      TB_ATD_ATE_ATENDIMENTO     ATE      ON  ATE.ATD_ATE_ID          = ARE.ATD_ATE_ID
            JOIN      TB_CAD_UNI_UNIDADE         UNI      ON  UNI.CAD_UNI_ID_UNIDADE  = ATE.CAD_UNI_ID_UNIDADE
            JOIN      TB_CAD_PAC_PACIENTE        PAC      ON  PAC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
            JOIN      TB_CAD_PES_PESSOA          PES      ON  PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
            JOIN      TB_CAD_PES_PESSOA          PES_RESP ON  PES_RESP.CAD_PES_ID_PESSOA   = ARE.CAD_PES_ID_PESSOA
            JOIN      TB_FAT_NOF_NOTA_FISCAL     NOF      ON  NOF.FAT_NOF_ID          = CCP.FAT_NOF_ID
            LEFT JOIN TB_CAD_REA_RESTRICAO_ATEND REA      ON  REA.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                                          AND REA.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                                          AND REA.FAT_CCP_ID          = CCP.FAT_CCP_ID
         --   LEFT JOIN TB_CAD_PES_PESSOA          PES_RESP ON  PES.CAD_PES_ID_PESSOA   = REA.CAD_PES_ID_PESSOA_RESPONSAVEL
            LEFT JOIN TB_SEG_USU_USUARIO         USU_CRI  ON  USU_CRI.SEG_USU_ID_USUARIO = REA.SEG_USU_ID_USUARIO_CRIACAO
            LEFT JOIN TB_SEG_USU_USUARIO         USU_ATU  ON  USU_ATU.SEG_USU_ID_USUARIO = REA.SEG_USU_ID_USUARIO_ATUALIZ
            WHERE  PAC.CAD_CNV_ID_CONVENIO = 282 '
||  V_WHERE || '
            ORDER BY PES.CAD_PES_NM_PESSOA, PES.CAD_PES_DT_NASCIMENTO '   ;
 -- TESTE :=   V_SELECT  ;
OPEN v_cursor FOR
  V_SELECT  ;
  io_cursor := v_cursor;
 end PRC_COB_INADIMPLENTES_L;
