CREATE OR REPLACE PROCEDURE "PRC_BENEF_TRANSF_S"
(
     pCODBEN    IN BNF_BENEFICIARIO.CODBEN%type,
     pCODCON    IN BNF_BENEFICIARIO.CODCON%type,
     pCODEST    IN BNF_BENEFICIARIO.CODEST%type,
     pCODSEQBEN IN BNF_BENEFICIARIO.CODSEQBEN%type,
     io_cursor OUT PKG_CURSOR.t_cursor
)
IS

  v_cursor PKG_CURSOR.t_cursor;

BEGIN

   OPEN v_cursor FOR

SELECT
BENEF.CODCON,
BENEF.CODEST,
BENEF.CODBEN,
BENEF.CODSEQBEN,
BENEF.NOMBEN,
BENEF.CODPADATEBEN,
BENEF.CODPADCOBBEN,
BENEF.CODINDBEN,
BENEF.SEXBEN,
BENEF.CODGRAPAR,
BENEF.ESTCIVBEN,
BENEF.DATNASBEN,
BENEF.DATINGCONBEN,
BENEF.DATADMEMP,
BENEF.DATSAICONBEN,
BENEF.OCUEMPBEN,
BENEF.CARPROBEN,
BENEF.CODSITBEN,
BENEF.DATLIMBEN,
BENEF.DATSITBEN,
BENEF.CPFBEN,
BENEF.RGBEN,
BENEF.CODACO,
BENEF.CODPLA,
BENEF.VALCOB,
BENEF.CODTIPPAD,
BENEF.DATEMIEXC,
BENEF.SITATI,
BENEF.CODTIPCARBEN,
BENEF.INDPAG,
BENEF.DT_ATU_INDPAG,
BENEF.IND_NEGOCIACAO,
BENEF.DATFATOD,
BENEF.IDADEBEN,
BENEF.MAEBEN,
BENEF.CANC_ANS,
BENEF.ID_AUTORIZACAO_ANS,
BENEF.VLPERC,
BENEF.CODPRO,
BENEF.DATALTBEN,
BENEF.CD_EMPRESA,
BENEF.ID_COPART_EXAME,
BENEF.ID_COPART_CONSULTA,
BENEF.ID_CRONICO,
BENEF.CO_PART,
BENEF.ID_EMISSAO_CARTEIRINHA,
BENEF.VL_COBRANCA_ATUAL,
BENEF.DT_COBRANCA_ATUAL,
BENEF.DT_REF_COBRANCA_ATUAL,
BENEF.DT_EMISSAO_CARTEIRINHA,
BENEF.ID_CONTENCIOSO,
BENEF.DS_CONTENCIOSO,
BENEF.ID_SUSPENSAO_BOLETO,
BENEF.ID_DOENTE_CRONICO,
BENEF.CD_CID_CRONICO,
BENEF.ID_REPASSE,
BENEF.DT_EXCLUSAO_FATURA,
BENEF.CD_LOCAL_REPASSE,
BENEF.ID_PAC,
BENEF.ID_CURATIVO,
BENEF.DT_INI_CURATIVO,
BENEF.ID_HOMECARE,
BENEF.DT_INI_HOMECARE,
BENEF.ID_MEDFAMILIA,
BENEF.DT_INI_MEDFAMILIA,
BENEF.ID_SEGURO_REMISSAO,
BENEF.ID_PLANO_BEM,
BENEF.DT_INI_CRONICO,
BENEF.DT_INI_PLANO_BEM,
BENEF.DT_INICIO_REPASSE,
BENEF.DT_FINAL_REPASSE,
BENEF.CD_EMPRESA_REPASSE,
BENEF.DS_LOCALIDADE,
BENEF.ID_EMPRESA_REPASSADA,
BENEF.DT_FIM_PLANO_BEM,
BENEF.CD_PLANO_BEM,
BENEF.ID_ACESSORIO,
BENEF.CODNAC,
BENEF.CODPAIS,
BENEF.ORGAO_EMISSOR_RG,
BENEF.PAIS_EMISSOR_RG,
BENEF.PISPASEP,
BENEF.IND_ACIDENTE_TRABALHO,
BENEF.CODPAC,
BENEF.DOCBEN,
BENEF.COD_NATDOC,
BENEF.DT_EXPEDOC,
BENEF.COD_ATIVPRINC,
BENEF.IDOPER,
BENEF.ID_CARTAO_AUTORIZADOR,
BENEF.DT_CARTAO_AUTORIZADOR,
BENEF.NM_REDUZIDO,
BENEF.DS_LOGIN,
BENEF.CD_CCO,
BENEF.DV_CCO,
BENEF.CDPLANOANS_ORIGEM,
BENEF.DATMOVHAC,
BENEF.NR_DN,
BENEF.DATLIMCONTRATO,
BENEF.NR_CNS

FROM
(SELECT
TRANSF.CODCON,
TRANSF.CODEST,
TRANSF.CODBEN,
TRANSF.CODSEQBEN
FROM BNF_BENEFICIARIO BNF
INNER JOIN BNF_HIST_TRANSF TRANSF ON
       BNF.CODCON     = TRANSF.CODCON
AND    BNF.CODEST     = TRANSF.CODEST
AND    BNF.CODBEN     = TRANSF.CODBEN
AND    BNF.CODSEQBEN  = TRANSF.CODSEQBEN
WHERE
       TRANSF.CODBENANT    =  pCODBEN
AND    TRANSF.CODCONANT    =  pCODCON
AND    TRANSF.CODESTANT    =  pCODEST
AND    TRANSF.CODSEQBENANT =  pCODSEQBEN) TRANSFERIDO, BNF_BENEFICIARIO BENEF
WHERE
      BENEF.CODCON         = TRANSFERIDO.CODCON
  AND BENEF.CODEST         = TRANSFERIDO.CODEST
  AND BENEF.CODBEN         = TRANSFERIDO.CODBEN
  AND BENEF.CODSEQBEN      = TRANSFERIDO.CODSEQBEN;

io_cursor := v_cursor;

END PRC_BENEF_TRANSF_S;
 