create or replace procedure PRC_CAD_PAH_S
  (
     pCAD_TAP_TP_ATRIBUTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_TAP_TP_ATRIBUTO%type DEFAULT NULL,
     pCAD_PAH_PC_ACRESCIMO_HR IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_PC_ACRESCIMO_HR%type DEFAULT NULL,
     pCAD_PAH_HR_INICIO_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_INICIO_SEMANA%type DEFAULT NULL,
     pCAD_PAH_HR_FIM_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_FIM_SEMANA%type DEFAULT NULL,
     pCAD_PAH_DT_INICIO_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_INICIO_VIGENCIA%type DEFAULT NULL,
     pCAD_PAH_DT_FIM_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_PAH_NR_DIA_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_NR_DIA_SEMANA%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_SEG_USU_USUARIO.SEG_USU_ID_USUARIO%TYPE DEFAULT NULL,
     pCAD_PAH_DT_ULTIMA_ATUALIZACAO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_ULTIMA_ATUALIZACAO%TYPE DEFAULT NULL,
     pCAD_PAH_ID IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_ID%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_CAD_PAH_S
  *
  *    Data Criacao:   25/11/2009   Por: Pedro
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;

  begin
    OPEN v_cursor FOR
    SELECT
       PAH.CAD_TAP_TP_ATRIBUTO,
       PAH.CAD_PAH_PC_ACRESCIMO_HR,
       PAH.CAD_PAH_HR_INICIO_SEMANA,
       PAH.CAD_PAH_HR_FIM_SEMANA,
       PAH.CAD_PAH_DT_INICIO_VIGENCIA,
       PAH.CAD_PAH_DT_FIM_VIGENCIA,
       PAH.CAD_PAH_DT_ULTIMA_ATUALIZACAO,
       PAH.SEG_USU_ID_USUARIO,
       PAH.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       PAH.CAD_PAH_NR_DIA_SEMANA,
       PAH.CAD_CNV_ID_CONVENIO,
       PAH.CAD_PAH_ID,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       TAP.CAD_TAP_DS_ATRIBUTO,
       DECODE(PAH.CAD_PAH_NR_DIA_SEMANA,'1','SEGUNDA-FEIRA','2','TERÇA-FEIRA','3','QUARTA-FEIRA',
       '4','QUINTA-FEIRA','5','SEXTA-FEIRA','6','SÁBADO','7','DOMINGO') DIA_SEMANA
    FROM TB_CAD_PAH_PERC_ACRESCIMO_HR PAH
    JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
    ON   LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = PAH.CAD_LAT_ID_LOCAL_ATENDIMENTO
    JOIN TB_CAD_TAP_TP_ATRIB_PRODUTO TAP
    ON   TAP.CAD_TAP_TP_ATRIBUTO = PAH.CAD_TAP_TP_ATRIBUTO
    JOIN TB_CAD_CNV_CONVENIO CNV
    ON   CNV.CAD_CNV_ID_CONVENIO = PAH.CAD_CNV_ID_CONVENIO
    WHERE
        (pCAD_TAP_TP_ATRIBUTO is null OR PAH.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO) AND
        (pCAD_PAH_PC_ACRESCIMO_HR is null OR PAH.CAD_PAH_PC_ACRESCIMO_HR = pCAD_PAH_PC_ACRESCIMO_HR) AND
        (pCAD_PAH_HR_INICIO_SEMANA is null OR PAH.CAD_PAH_HR_INICIO_SEMANA = pCAD_PAH_HR_INICIO_SEMANA) AND
        (pCAD_PAH_HR_FIM_SEMANA is null OR PAH.CAD_PAH_HR_FIM_SEMANA = pCAD_PAH_HR_FIM_SEMANA) AND
        (pCAD_PAH_DT_INICIO_VIGENCIA is null OR PAH.CAD_PAH_DT_INICIO_VIGENCIA = pCAD_PAH_DT_INICIO_VIGENCIA) AND
        (pCAD_PAH_DT_FIM_VIGENCIA is null OR PAH.CAD_PAH_DT_FIM_VIGENCIA = pCAD_PAH_DT_FIM_VIGENCIA) AND
        (pCAD_PAH_DT_ULTIMA_ATUALIZACAO is null OR PAH.CAD_PAH_DT_ULTIMA_ATUALIZACAO = pCAD_PAH_DT_ULTIMA_ATUALIZACAO) AND
        (pSEG_USU_ID_USUARIO is null OR PAH.SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR PAH.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND
        (pCAD_PAH_NR_DIA_SEMANA is null OR PAH.CAD_PAH_NR_DIA_SEMANA = pCAD_PAH_NR_DIA_SEMANA) AND
        (pCAD_CNV_ID_CONVENIO is null OR PAH.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND
        (pCAD_PAH_ID is null OR PAH.CAD_PAH_ID = pCAD_PAH_ID);
    io_cursor := v_cursor;
  end PRC_CAD_PAH_S;
