CREATE OR REPLACE PROCEDURE PRC_MTMD_ESTOQUE_ON_LINE
(
     pCAD_MTMD_ID                  IN TB_MTMD_ESTOQUE_LOCAL.CAD_MTMD_ID%type,
     pCAD_MTMD_FILIAL_ID           IN TB_MTMD_ESTOQUE_LOCAL.CAD_MTMD_FILIAL_ID%TYPE,
     pCAD_SET_ID                   IN TB_MTMD_ESTOQUE_LOCAL.CAD_SET_ID%type,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_MTMD_ESTOQUE_LOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pCAD_UNI_ID_UNIDADE           IN TB_MTMD_ESTOQUE_LOCAL.CAD_UNI_ID_UNIDADE%type,
     io_cursor                     OUT PKG_CURSOR.t_cursor
 )IS
    v_cursor PKG_CURSOR.t_cursor;
    vOrigem NUMBER;
    vAlmoxCentral NUMBER := 0;
   vUNIDADE_ESTOQUE_CONSUMO   TB_MTMD_MOV_MOVIMENTACAO.CAD_UNI_ID_UNIDADE%type;
   vLOCAL_ESTOQUE_CONSUMO     TB_MTMD_MOV_MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type;
   vSETOR_ESTOQUE_CONSUMO     TB_MTMD_MOV_MOVIMENTACAO.CAD_SET_ID%type;
    -- PROCEDURE PARA RETORNAR INFORMAC?ES E QUANTIDADE DO ESTOQUE LOCAL DO PRODUTO
    -- SE FOR PRODUTO DO ESTOQUE FIXO, TBM RETORNA PERCENTUAL DE CONSUMO
  /********************************************************************
  *    Procedure: PRC_MTMD_MOV_ESTOQUE_ENTRADA
  *
  *    Data Criacao: 	11/2009   Por: RICARDO COSTA
  *    Data Alteracao:	22/03/2010    Por: RICARDO COSTA
  *         Alterac?o: adicionar retorno da coluna ativo/inativo
  *    Data Alteracao:	10/06/2010    Por: RICARDO COSTA
  *         Alterac?o: adicionar coluna reutilizavel
  *    Data Alteracao:  24/10/2017  Por: Andre S. Monaco
  *         Alteracao:  Adicao funcao SOUND ALIKE na descricao
  *
  *    Funcao:  RETORNAR INFORMAC?ES E QUANTIDADE DO ESTOQUE LOCAL DO PRODUTO
  *
  *******************************************************************/
BEGIN
   PRC_MTMD_ESTOQUE_DE_CONSUMO(pCAD_UNI_ID_UNIDADE,
                                pCAD_LAT_ID_LOCAL_ATENDIMENTO,
                                pCAD_SET_ID,
                                pCAD_MTMD_FILIAL_ID,
                                vUNIDADE_ESTOQUE_CONSUMO,
                                vLOCAL_ESTOQUE_CONSUMO,
                                vSETOR_ESTOQUE_CONSUMO
                               );
   OPEN v_cursor FOR
   SELECT ESTLOCAL.CAD_MTMD_ID,
          PRODUTO.CAD_MTMD_FL_ATIVO,
          ESTLOCAL.MTMD_LOTEST_ID,
          ESTLOCAL.CAD_MTMD_FILIAL_ID,
          ESTLOCAL.CAD_UNI_ID_UNIDADE,
          ESTLOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO,
          ESTLOCAL.CAD_SET_ID,
          ESTLOCAL.MTMD_ESTLOC_QTDE_FRACIONADA,
          ESTLOCAL.MTMD_ESTLOC_FL_PADRAO,
          FNC_MTMD_SOUNDALIKE(PRODUTO.CAD_MTMD_NOMEFANTASIA,PRODUTO.CAD_MTMD_GRUPO_ID) CAD_MTMD_NOMEFANTASIA,
          PRODUTO.CAD_MTMD_UNID_VENDA_DS,
          DECODE( PRODUTO.tis_med_cd_tabelamedica, '95', 'MA', 96, 'ME') TIS_MED_CD_TABELAMEDICA,
          PRODUTO.CAD_MTMD_FL_FRACIONA,
          PRODUTO.CAD_MTMD_FL_FATURADO,
          PRODUTO.CAD_MTMD_FL_REUTILIZAVEL,
          ESTLOCAL.MTMD_ESTLOC_QTDE,
          ESTLOCAL.MTMD_MOV_CONSUMO         QTDE_CONSUMIDA,
          ESTLOCAL.MTMD_MOV_CONSUMO_OUTROS OUTROS_CONSUMOS,   -- RETORNA TRANSFERENCIAS E PERDAS DESDE O ULTIMO FORNECIMENTO
          ESTLOCAL.MTMD_MOV_CONSUMO_PERC    PERCENTUAL_CONSUMIDO, -- RETORNA PERCENTUAL DE CONSUMO
          ESTLOCAL.MTMD_PEDPAD_QTDE
          MTMD_PEDPAD_QTDE ,   -- RETORNA QTDE SE PRODUTO FIZER PARTE DO ESTOQUE PADRAO DA UNIDADE
          ESTLOCAL.MTMD_MOV_ESTOQUE_ATUAL,  -- RETORNO SALDO NA DATA DO FORNECIMENTO DO PRODUTO
          ESTLOCAL.MTMD_MOV_DT_FORNECIMENTO MTMD_DT_RESSUPRIMENTO, -- DATA FORNECIMENTO
          UNIDADE.CAD_UNI_DS_UNIDADE,
          SETOR.CAD_SET_DS_SETOR,
          FILIAL.CAD_MTMD_FILIAL_DESCRICAO,
          PRODUTO.CAD_MTMD_FL_BAIXA_AUTOMATICA,
          ESTLOCAL.MTMD_ID_ORIGINAL,
          FNC_MTMD_PRINCIPIO_ATIVO( ESTLOCAL.CAD_MTMD_ID ) CAD_MTMD_PRIATI_ID,
          (SELECT CAD_MTMD_NOMEFANTASIA
           FROM TB_CAD_MTMD_MAT_MED
           WHERE CAD_MTMD_ID =  ESTLOCAL.MTMD_ID_ORIGINAL) DS_PRODUTO_ORIGINAL,  -- RETORNA DESCRICAO DO PRODUTO ORIGINAL
          (SELECT NVL(ITEM.MTMD_PEDPAD_PERCENT_RESSUP,0)
           FROM TB_MTMD_PEDIDO_PADRAO       PADRAO,
                 TB_MTMD_PEDIDO_PADRAO_ITENS ITEM
           -- WHERE PADRAO.CAD_MTMD_FILIAL_ID            = FNC_MTMD_RETORNA_FILIAL( ESTLOCAL.CAD_MTMD_ID, pCAD_MTMD_FILIAL_ID )
           WHERE PADRAO.CAD_MTMD_FILIAL_ID            = pCAD_MTMD_FILIAL_ID
           AND   PADRAO.cad_uni_id_unidade            = vUNIDADE_ESTOQUE_CONSUMO
           AND   PADRAO.cad_lat_id_local_atendimento  = vLOCAL_ESTOQUE_CONSUMO
           AND   PADRAO.cad_set_id                    = vSETOR_ESTOQUE_CONSUMO
           AND   ITEM.mtmd_pedpad_id                  = PADRAO.MTMD_PEDPAD_ID
           AND   ITEM.cad_mtmd_id                     = ESTLOCAL.CAD_MTMD_ID) MTMD_PEDPAD_PERCENT_RESSUP
           ,
           CASE
            WHEN pCAD_MTMD_FILIAL_ID = 1 THEN
            NVL(( SELECT MTMD_ESTLOC_QTDE
              FROM TB_MTMD_ESTOQUE_LOCAL
              WHERE CAD_MTMD_ID                  = ESTLOCAL.CAD_MTMD_ID
              AND   CAD_UNI_ID_UNIDADE           = ESTLOCAL.CAD_UNI_ID_UNIDADE
              AND   CAD_LAT_ID_LOCAL_ATENDIMENTO = ESTLOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO
              AND   CAD_SET_ID                   = ESTLOCAL.CAD_SET_ID
              AND   CAD_MTMD_FILIAL_ID           = 4 ),0)
            ELSE 0
           END QTDE_CE,
           PRODUTO.CAD_MTMD_GRUPO_ID,
           PRODUTO.CAD_MTMD_FL_MAV,
           PRODUTO.CAD_MTMD_ENDERECO_ALMOX_HAC
   FROM TB_MTMD_ESTOQUE_LOCAL      ESTLOCAL,
        TB_CAD_MTMD_MAT_MED        PRODUTO,
        TB_CAD_UNI_UNIDADE         UNIDADE,
        TB_CAD_SET_SETOR           SETOR,
        TB_CAD_MTMD_FILIAL         FILIAL
   WHERE (pCAD_MTMD_ID                  IS NULL OR ESTLOCAL.CAD_MTMD_ID                  = pCAD_MTMD_ID)
   AND   (pCAD_UNI_ID_UNIDADE           IS NULL OR ESTLOCAL.CAD_UNI_ID_UNIDADE           = vUNIDADE_ESTOQUE_CONSUMO)
   AND   (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ESTLOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO = vLOCAL_ESTOQUE_CONSUMO)
   AND   (pCAD_SET_ID                   IS NULL OR ESTLOCAL.CAD_SET_ID                   = vSETOR_ESTOQUE_CONSUMO)
   AND   (pCAD_MTMD_FILIAL_ID           IS NULL OR ESTLOCAL.CAD_MTMD_FILIAL_ID           =  pCAD_MTMD_FILIAL_ID)
   AND   ESTLOCAL.CAD_MTMD_ID        = PRODUTO.CAD_MTMD_ID
   AND   UNIDADE.CAD_UNI_ID_UNIDADE(+)  = ESTLOCAL.CAD_UNI_ID_UNIDADE
   AND   SETOR.CAD_SET_ID(+)            = ESTLOCAL.CAD_SET_ID
   AND   ESTLOCAL.CAD_MTMD_FILIAL_ID = FILIAL.CAD_MTMD_FILIAL_ID
   UNION
   SELECT ESTLOCAL.CAD_MTMD_ID,
      PRODUTO.CAD_MTMD_FL_ATIVO,
      ESTLOCAL.MTMD_LOTEST_ID,
      1 CAD_MTMD_FILIAL_ID, -- APENAS HAC quando pCAD_MTMD_FILIAL_ID = 1
      ESTLOCAL.CAD_UNI_ID_UNIDADE,
      ESTLOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO,
      ESTLOCAL.CAD_SET_ID,
      ESTLOCAL.MTMD_ESTLOC_QTDE_FRACIONADA,
      ESTLOCAL.MTMD_ESTLOC_FL_PADRAO,
      PRODUTO.CAD_MTMD_NOMEFANTASIA,
      PRODUTO.CAD_MTMD_UNID_VENDA_DS,
      DECODE( PRODUTO.tis_med_cd_tabelamedica, '95', 'MA', 96, 'ME') TIS_MED_CD_TABELAMEDICA,
      PRODUTO.CAD_MTMD_FL_FRACIONA,
      PRODUTO.CAD_MTMD_FL_FATURADO,
      PRODUTO.CAD_MTMD_FL_REUTILIZAVEL,
      0 MTMD_ESTLOC_QTDE, -- N?O TRAZER NESTE UNION (POIS SO TRAZ CE QUE N?O TEM NO HAC)
      NULL QTDE_CONSUMIDA,
      NULL OUTROS_CONSUMOS,   -- RETORNA TRANSFERENCIAS E PERDAS DESDE O ULTIMO FORNECIMENTO
      NULL PERCENTUAL_CONSUMIDO, -- RETORNA PERCENTUAL DE CONSUMO
      NULL MTMD_PEDPAD_QTDE ,   -- RETORNA QTDE SE PRODUTO FIZER PARTE DO ESTOQUE PADRAO DA UNIDADE
      NULL MTMD_MOV_ESTOQUE_ATUAL,  -- RETORNO SALDO NA DATA DO FORNECIMENTO DO PRODUTO
      NULL MTMD_DT_RESSUPRIMENTO, -- DATA FORNECIMENTO
      UNIDADE.CAD_UNI_DS_UNIDADE,
      SETOR.CAD_SET_DS_SETOR,
      FILIAL.CAD_MTMD_FILIAL_DESCRICAO,
      PRODUTO.CAD_MTMD_FL_BAIXA_AUTOMATICA,
      ESTLOCAL.MTMD_ID_ORIGINAL,
      FNC_MTMD_PRINCIPIO_ATIVO( ESTLOCAL.CAD_MTMD_ID ) CAD_MTMD_PRIATI_ID,
      (SELECT CAD_MTMD_NOMEFANTASIA
       FROM TB_CAD_MTMD_MAT_MED
       WHERE CAD_MTMD_ID =  ESTLOCAL.MTMD_ID_ORIGINAL) DS_PRODUTO_ORIGINAL,  -- RETORNA DESCRICAO DO PRODUTO ORIGINAL
      NULL MTMD_PEDPAD_PERCENT_RESSUP,
       CASE
        WHEN 1 = 1 THEN -- APENAS HAC quando pCAD_MTMD_FILIAL_ID = 1
        NVL(( SELECT MTMD_ESTLOC_QTDE
          FROM TB_MTMD_ESTOQUE_LOCAL
          WHERE CAD_MTMD_ID                  = ESTLOCAL.CAD_MTMD_ID
          AND   CAD_UNI_ID_UNIDADE           = ESTLOCAL.CAD_UNI_ID_UNIDADE
          AND   CAD_LAT_ID_LOCAL_ATENDIMENTO = ESTLOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO
          AND   CAD_SET_ID                   = ESTLOCAL.CAD_SET_ID
          AND   CAD_MTMD_FILIAL_ID           = 4 ),0)
        ELSE 0
       END QTDE_CE,
       PRODUTO.CAD_MTMD_GRUPO_ID,
       PRODUTO.CAD_MTMD_FL_MAV,
       PRODUTO.CAD_MTMD_ENDERECO_ALMOX_HAC
   FROM TB_MTMD_ESTOQUE_LOCAL      ESTLOCAL,
        TB_CAD_MTMD_MAT_MED        PRODUTO,
        TB_CAD_UNI_UNIDADE         UNIDADE,
        TB_CAD_SET_SETOR           SETOR,
        TB_CAD_MTMD_FILIAL         FILIAL
   WHERE (pCAD_MTMD_ID                  IS NULL OR ESTLOCAL.CAD_MTMD_ID                  = pCAD_MTMD_ID)
   AND   (pCAD_UNI_ID_UNIDADE           IS NULL OR ESTLOCAL.CAD_UNI_ID_UNIDADE           = vUNIDADE_ESTOQUE_CONSUMO)
   AND   (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ESTLOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO = vLOCAL_ESTOQUE_CONSUMO)
   AND   (pCAD_SET_ID                   IS NULL OR ESTLOCAL.CAD_SET_ID                   = vSETOR_ESTOQUE_CONSUMO)
   -- QUANDO HAC (pCAD_MTMD_FILIAL_ID = 1) TRAZER PRODUTO DO CE QUE N?O TENHA NO SETOR DO HAC
   AND   (pCAD_MTMD_FILIAL_ID <> 1 OR ESTLOCAL.CAD_MTMD_FILIAL_ID = 4 ) -- 4 = CE
   -- QUANDO DIFERENTE de HAC (pCAD_MTMD_FILIAL_ID = 1) N?O TRAZER NADA NESTE UNION
   AND   (pCAD_MTMD_FILIAL_ID = 1 OR ESTLOCAL.CAD_MTMD_FILIAL_ID = 0)
   AND   ESTLOCAL.CAD_MTMD_ID        = PRODUTO.CAD_MTMD_ID
   AND   UNIDADE.CAD_UNI_ID_UNIDADE(+)  = ESTLOCAL.CAD_UNI_ID_UNIDADE
   AND   SETOR.CAD_SET_ID(+)            = ESTLOCAL.CAD_SET_ID
   AND   1 = FILIAL.CAD_MTMD_FILIAL_ID -- APENAS HAC quando pCAD_MTMD_FILIAL_ID = 1
   -- QUANDO DIFERENTE de HAC (pCAD_MTMD_FILIAL_ID = 1) N?O TRAZER NADA NESTE UNION
   AND   ESTLOCAL.CAD_MTMD_ID NOT IN (SELECT CAD_MTMD_ID FROM TB_MTMD_ESTOQUE_LOCAL
                                        WHERE CAD_MTMD_FILIAL_ID = 1 AND -- APENAS HAC quando pCAD_MTMD_FILIAL_ID = 1
                                              CAD_MTMD_ID = ESTLOCAL.CAD_MTMD_ID AND
                                              CAD_SET_ID = ESTLOCAL.CAD_SET_ID)
   ORDER BY 10, 24, 26, 25;
   --ORDER BY PRODUTO.CAD_MTMD_NOMEFANTASIA, UNIDADE.Cad_Uni_Ds_Unidade, FILIAL.CAD_MTMD_FILIAL_DESCRICAO, SETOR.CAD_SET_DS_SETOR;
    io_cursor := v_cursor;
    -- close v_cursor;
END PRC_MTMD_ESTOQUE_ON_LINE;