CREATE OR REPLACE PROCEDURE "PRC_ATS_REL_LAUDO_PROTOCOLADO"
 (
     pCAD_UNI_ID_UNIDADE in TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO in TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type default null,
     pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO in TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%type default null,
     pCAD_PLA_ID_PLANO in TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%type default null,
     PCAD_PLA_CD_TIPOPLANO IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
     pATS_APR_FL_STATUS IN TB_ATS_ARP_ATEN_RESULT_PROCED.ATS_APR_FL_STATUS%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_ATS_ARP_ATEN_RESULT_PROCED.ATS_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pCAD_PRD_ID IN TB_ATS_ARP_ATEN_RESULT_PROCED.CAD_PRD_ID%type DEFAULT NULL,
     pCAD_PRO_ID_PROF_EXECUTANTE IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
     PDT_INI_CONSULTA in TB_ATS_ARP_ATEN_RESULT_PROCED.ATS_APR_DT_PROTOCOLO%type default null,
     PDT_FIM_CONSULTA in TB_ATS_ARP_ATEN_RESULT_PROCED.ATS_APR_DT_PROTOCOLO%type default null,
     PHR_INI_CONSULTA in TB_ATS_ARP_ATEN_RESULT_PROCED.ATS_APR_HR_PROTOCOLO%type default null,
     PHR_FIM_CONSULTA in TB_ATS_ARP_ATEN_RESULT_PROCED.ATS_APR_HR_PROTOCOLO%type default null,
     PATS_ATE_IN_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_IN_INTLIB%TYPE DEFAULT NULL,
     pALTA NUMBER DEFAULT NULL,
     pATS_ATE_FL_REPETICAO IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_REPETICAO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ATS_REL_LAUDO_PROTOCOLADO
  *
  *    Data Alteracao:  21/08/2009  Por: Pedro
  *     ALteracao: correc?o do parametro PCAD_PLA_CD_TIPOPLANO
  *
  *    Funcao:
  *
  *******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_ORDERBY  varchar2(1000);
  V_SELECT  varchar2(28000);
  begin
    V_WHERE := NULL;
    V_ORDERBY := NULL;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ARP.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
    IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
    IF pCAD_PRD_ID IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRD.CAD_PRD_ID = ' || pCAD_PRD_ID; END IF;
    IF pCAD_SET_ID IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATS.CAD_SET_ID_ATEN = ' || pCAD_SET_ID; END IF;
    IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ARP.ATS_EPP_CD_ESPECPROC = ' ||CHR(39)|| pAUX_EPP_CD_ESPECPROC ||CHR(39); END IF;
    IF pCAD_PRO_ID_PROF_EXECUTANTE IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATS.CAD_PRO_ID_PROF_EXECUTANTE = ' || pCAD_PRO_ID_PROF_EXECUTANTE; END IF;
    IF pCAD_PLA_CD_TIPOPLANO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PLA.CAD_PLA_CD_TIPOPLANO = ' ||CHR(39)|| pCAD_PLA_CD_TIPOPLANO ||CHR(39); END IF;
    IF pATS_ATE_IN_INTLIB IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' ||CHR(39)|| pATS_ATE_IN_INTLIB ||CHR(39); END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CNV.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO; END IF;
    IF pCAD_PLA_ID_PLANO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PLA.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO; END IF;
    IF pCAD_PLA_CD_TIPOPLANO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PLA.CAD_PLA_CD_TIPOPLANO = ' ||CHR(39)|| pCAD_PLA_CD_TIPOPLANO ||CHR(39); END IF;
    IF pATS_ATE_FL_REPETICAO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_FL_REPETICAO = ' ||CHR(39)|| pATS_ATE_FL_REPETICAO ||CHR(39); END IF;
    IF pATS_APR_FL_STATUS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATS.ATS_APR_FL_STATUS = ' ||CHR(39)|| pATS_APR_FL_STATUS ||CHR(39); END IF;
    IF pDT_INI_CONSULTA IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRUNC(ARP.ATS_APR_DT_PROTOCOLO) >= ' ||CHR(39)|| pDT_INI_CONSULTA ||CHR(39);    END IF;
    IF pDT_FIM_CONSULTA IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRUNC(ARP.ATS_APR_DT_PROTOCOLO) <= ' ||CHR(39)|| pDT_FIM_CONSULTA ||CHR(39);    END IF;
    IF pHR_INI_CONSULTA IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ARP.ATS_APR_HR_PROTOCOLO >= ' || pHR_INI_CONSULTA; end if;
    IF pHR_FIM_CONSULTA IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ARP.ATS_APR_HR_PROTOCOLO <= ' || pHR_FIM_CONSULTA; end if;
IF pALTA IS NOT NULL THEN
IF pALTA = '0' THEN V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' ||CHR(39)||'I'||CHR(39)||' AND AIC.ATD_AIC_TP_SITUACAO_PAC = ' ||CHR(39)||'I'||CHR(39); END IF;
IF pALTA = '1' THEN V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' ||CHR(39)||'I'||CHR(39)||' AND AIC.ATD_AIC_TP_SITUACAO_PAC = ' ||CHR(39)||'A'||CHR(39); END IF;
END IF;
 V_SELECT :=
   '
SELECT
      ARP.ATS_ATE_ID NUMERO_EXAME,
      ARP.ATS_ATE_CD_INTLIB,
      DECODE(ARP.ATS_ATE_IN_INTLIB, ''I'',''INTERNADO'', ''L'',''AMBULATORIO'') ATS_ATE_IN_INTLIB,
      ARP.ATS_APR_FL_STATUS,
      ARP.ATS_APR_DT_PROTOCOLO,
      ARP.ATS_APR_HR_PROTOCOLO,
      UNI.CAD_UNI_DS_UNIDADE,
      LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
      SETOR.CAD_SET_DS_SETOR,
      SETOR_ENTREGA.CAD_SET_DS_SETOR SETOR_ENTREGA,
      PRD.CAD_PRD_CD_CODIGO,
      PRD.CAD_PRD_DS_DESCRICAO,
      EPP.AUX_EPP_DS_DESCRICAO ,
      CNV.CAD_CNV_CD_HAC_PRESTADOR ,
      PLA.CAD_PLA_CD_PLANO_HAC ,
      DECODE(PLA.CAD_PLA_CD_TIPOPLANO, ''48'', ''48'', ''FU'', ''FUNCIONARIO'', ''PA'', ''PA'', ''GB'', ''GLOBAL'', ''PL'', ''PESSOA FISICA'', ''SP'', ''SERVICOS PRESTADOS'', ''TODOS'') TIPO_EMPRESA,
      case when ATS.ATS_ATE_FL_RN = ''S'' then IDR.ATD_IDR_NM_NOME
            ELSE PES_PAC.CAD_PES_NM_PESSOA
        END CAD_PES_NM_PESSOA,
       case when ATS.ATS_ATE_FL_RN = ''S'' then IDR.ATD_IDR_DT_NASCIMENTO
            ELSE PES_PAC.CAD_PES_DT_NASCIMENTO
        END CAD_PES_DT_NASCIMENTO,  
      PRO.CAD_PRO_NM_NOME,
      ARP.ATS_APR_NR_SEQ_LOTE,
      ATS.ATS_ATE_FL_REPETICAO,
      apl.ats_apl_id
FROM TB_ATS_ARP_ATEN_RESULT_PROCED ARP
     JOIN TB_ATS_ATE_ATENDIMENTO_SADT ATS
     ON ATS.ATS_ATE_ID = ARP.ATS_ATE_ID
     AND ATS.ATS_ATE_CD_INTLIB = ARP.ATS_ATE_CD_INTLIB
     AND ATS.ATS_ATE_IN_INTLIB = ARP.ATS_ATE_IN_INTLIB
     AND ATS.CAD_PRD_ID = ARP.CAD_PRD_ID
     AND ATS.AUX_EPP_CD_ESPECPROC = ARP.ATS_EPP_CD_ESPECPROC
     AND ATS.TIS_MED_CD_TABELAMEDICA = ARP.TIS_MED_CD_TABELAMEDICA
     join tb_ats_apl_aten_proced_laudo apl
     on apl.ats_ate_id = ats.ats_ate_id
     and apl.cad_prd_id = ats.cad_prd_id
     JOIN TB_CAD_SET_SETOR SETOR ON SETOR.CAD_SET_ID = ATS.CAD_SET_ID_ATEN
     LEFT JOIN TB_CAD_SET_SETOR SETOR_ENTREGA ON SETOR.CAD_SET_ID = ARP.CAD_SET_ID_SETOR
     JOIN TB_CAD_PRD_PRODUTO PRD ON PRD.CAD_PRD_ID = ARP.CAD_PRD_ID
     JOIN TB_AUX_EPP_ESPECPROC EPP ON EPP.AUX_EPP_CD_ESPECPROC = ARP.ATS_EPP_CD_ESPECPROC and EPP.TIS_MED_CD_TABELAMEDICA = ARP.TIS_MED_CD_TABELAMEDICA
     JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PAC_ID_PACIENTE = ATS.CAD_PAC_ID_PACIENTE_INT
     JOIN TB_CAD_PES_PESSOA PES_PAC ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
     JOIN TB_CAD_CNV_CONVENIO CNV ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
     JOIN TB_CAD_PLA_PLANO PLA ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
     LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO ON PRO.CAD_PRO_ID_PROFISSIONAL = ATS.CAD_PRO_ID_PROF_EXECUTANTE
     JOIN TB_CAD_UNI_UNIDADE UNI ON UNI.CAD_UNI_ID_UNIDADE = setor.CAD_UNI_ID_UNIDADE
     JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
     LEFT JOIN TB_ATD_AIC_ATE_INT_COMPL AIC ON AIC.ATD_ATE_ID = ATS.ATS_ATE_CD_INTLIB
     LEFT JOIN TB_ATS_CSL_CTRL_SEQ_LOTE CSL ON CSL.ATS_APR_NR_SEQ_LOTE = ARP.ATS_APR_NR_SEQ_LOTE
   LEFT JOIN TB_ATD_IDR_INT_DADOS_RN IDR ON IDR.ATD_IDR_ID = ATS.ATS_ATE_ID_RN     
 WHERE (ARP.ATS_APR_FL_STATUS = ''P'') ' || V_WHERE
 ;

 -- TESTE :=  V_SELECT ;
OPEN v_cursor FOR
   V_SELECT ;
   -- SELECT 1 FROM DUAL;
    io_cursor := v_cursor;
  end PRC_ATS_REL_LAUDO_PROTOCOLADO;
