CREATE OR REPLACE PROCEDURE "PRC_ASS_CPR_CLINICA_FECHAR_VIG"(PASS_CPR_DT_FIM_VIGENCIA       IN TB_ASS_CPR_CLINICA_PROF.ASS_CPR_DT_FIM_VIGENCIA%TYPE,
                                                             PCAD_CLC_ID                    IN TB_ASS_CPR_CLINICA_PROF.CAD_CLC_ID%TYPE,
                                                             PCAD_PRO_ID_PROFISSIONAL       IN TB_ASS_CPR_CLINICA_PROF.CAD_PRO_ID_PROFISSIONAL%TYPE,
                                                             PASS_CPR_DT_ULTIMA_ATUALIZACAO IN TB_ASS_CPR_CLINICA_PROF.ASS_CPR_DT_ULTIMA_ATUALIZACAO%TYPE,
                                                             PSEG_USU_ID_USUARIO            IN TB_ASS_CPR_CLINICA_PROF.SEG_USU_ID_USUARIO%TYPE) IS

BEGIN
  UPDATE TB_ASS_CPR_CLINICA_PROF CPR
     SET CPR.ASS_CPR_DT_FIM_VIGENCIA       = PASS_CPR_DT_FIM_VIGENCIA,
         CPR.ASS_CPR_DT_ULTIMA_ATUALIZACAO = PASS_CPR_DT_ULTIMA_ATUALIZACAO,
         CPR.SEG_USU_ID_USUARIO            = PSEG_USU_ID_USUARIO
   WHERE CPR.CAD_CLC_ID = PCAD_CLC_ID
     AND CPR.CAD_PRO_ID_PROFISSIONAL = PCAD_PRO_ID_PROFISSIONAL
     AND CPR.ASS_CPR_DT_FIM_VIGENCIA IS NULL;
END PRC_ASS_CPR_CLINICA_FECHAR_VIG;