create or replace procedure PRC_INT_REL_CENSO_DIARIO
     -- (
   --  pDATA IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE
      -- io_cursor              OUT PKG_CURSOR.t_cursor)
   --    )
    is
      /********************************************************************
      *    Procedure: PRC_INT_REL_CENSO_DIARIO
      *
      *    Data Criacao:  01/10/09   Por: pedro
      *    Data Alteracao:  31/08/2010         Por: PEDRO
      *    Alteração: retira
      *
      *    Funcao: Grava historico do censo do dia
      *
      *******************************************************************/
    begin
   FOR LINHAS IN
        (
      SELECT  dt_atualizacao,
        dt_CENSO,
        CAD_PLA_ID_PLANO,
        CAD_SET_ID, 
        CAD_SET_DS_SETOR,
        QTD_MOV_ENVIADAS,
        QTD_MOV_RECEBIDAS,
        QTD_INT_NO_DIA ,
        QTD_INT_VINDOS_DIA_ANTERIOR,         
        QTD_PACIENTE_DIA,
        QTD_SAIDAS_OBITO,
        QTD_SAIDAS_SEM_OBITO,
        ALTA_OBITO_MAIS48,
        ALTA_OBITO_MENOS48,
        TOTAL_PARTO_NORMAL,
        TOTAL_PARTO_CESARIA,
        TOTAL_PARTO_FORCEPS,
        TOTAL_RN, --VIVOS
        TOTAL_RN_MORTO,
        TOTAL_PARTO_GEMELAR

  FROM ( SELECT 
          trunc(sysdate-1) dt_atualizacao,
          TO_CHAR(sysdate-1,'dd/MM/yyyy') dt_CENSO,
          PLA.CAD_PLA_ID_PLANO,
          SETOR.CAD_SET_ID, SETOR.CAD_SET_DS_SETOR,
          NVL(FNC_INT_QTD_MOV_ENVIADAS(SETOR.CAD_SET_ID, TRUNC(SYSDATE-1), PLA.CAD_PLA_ID_PLANO),0)    QTD_MOV_ENVIADAS,
          NVL(FNC_INT_QTD_MOV_RECEBIDAS(SETOR.CAD_SET_ID, TRUNC(SYSDATE-1), PLA.CAD_PLA_ID_PLANO),0)   QTD_MOV_RECEBIDAS,
          NVL(FNC_INT_QTD_DIA(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)               QTD_INT_NO_DIA ,
          NVL(FNC_INT_QTD_DIA_ANTERIOR(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO,NULL),0) QTD_INT_VINDOS_DIA_ANTERIOR,
          NVL(FNC_INT_QTD_DIA(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0) +
          NVL(FNC_INT_QTD_DIA_ANTERIOR(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO,NULL),0) +
          NVL(FNC_INT_QTD_MOV_RECEBIDAS(SETOR.CAD_SET_ID, TRUNC(SYSDATE-1), PLA.CAD_PLA_ID_PLANO),0) -
          NVL(FNC_INT_SAIDAS_OBITO(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0) -
          NVL(FNC_INT_SAIDAS(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0) -
          NVL(FNC_INT_QTD_MOV_ENVIADAS(SETOR.CAD_SET_ID, TRUNC(SYSDATE-1), PLA.CAD_PLA_ID_PLANO),0)    QTD_PACIENTE_DIA,
          NVL(FNC_INT_SAIDAS_OBITO(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)          QTD_SAIDAS_OBITO,
          NVL(FNC_INT_SAIDAS(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)                QTD_SAIDAS_SEM_OBITO,
          nvl( FNC_INT_QTD_SAIDA_48MAIS(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)     ALTA_OBITO_MAIS48,
          nvl( FNC_INT_QTD_SAIDA_48MENOS(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)    ALTA_OBITO_MENOS48,
          FNC_INT_QTD_PARTO(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO,1)                  TOTAL_PARTO_NORMAL,
          FNC_INT_QTD_PARTO(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO,2)                  TOTAL_PARTO_CESARIA,
          FNC_INT_QTD_PARTO(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO,3)                  TOTAL_PARTO_FORCEPS,
          NVL(FNC_INT_QTD_RN_VIVOS(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)         TOTAL_RN, --VIVOS
          NVL(FNC_INT_QTD_RN_MORTOS(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)        TOTAL_RN_MORTO,
          nvl(FNC_INT_QTD_PARTO_GEMELAR(SETOR.CAD_SET_ID,TRUNC(SYSDATE-1),PLA.CAD_PLA_ID_PLANO),0)    TOTAL_PARTO_GEMELAR
          
          FROM          TB_CAD_SET_SETOR           SETOR
          JOIN          TB_CAD_UNI_UNIDADE         UNI   ON UNI.CAD_UNI_ID_UNIDADE = SETOR.CAD_UNI_ID_UNIDADE
          JOIN          TB_CAD_LAT_LOCAL_ATENDIMENTO LAT ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
          JOIN          ( -- SOMENTE OS PLANOS UTILIZADOS NO MOMENTO
                        SELECT DISTINCT PLA.CAD_PLA_ID_PLANO FROM TB_CAD_PLA_PLANO PLA
                        JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
                        JOIN TB_ASS_PAT_PACIEATEND PAT ON PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
                        JOIN TB_ATD_ATE_ATENDIMENTO ATD ON ATD.ATD_ATE_ID = PAT.ATD_ATE_ID 
                        JOIN TB_ATD_AIC_ATE_INT_COMPL AIC ON ATD.ATD_ATE_ID = AIC.ATD_ATE_ID
                        WHERE AIC.ATD_AIC_TP_SITUACAO_PAC ='I'
                        UNION
                        SELECT DISTINCT PLA.CAD_PLA_ID_PLANO FROM TB_CAD_PLA_PLANO PLA
                        JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
                        JOIN TB_ASS_PAT_PACIEATEND PAT ON PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
                        JOIN TB_ATD_ATE_ATENDIMENTO ATD ON ATD.ATD_ATE_ID = PAT.ATD_ATE_ID 
                        JOIN TB_ATD_AIC_ATE_INT_COMPL AIC ON ATD.ATD_ATE_ID = AIC.ATD_ATE_ID
                        JOIN TB_ATD_INA_INT_ALTA INA ON INA.ATD_ATE_ID = ATD.ATD_ATE_ID
                        WHERE AIC.ATD_AIC_TP_SITUACAO_PAC ='A' AND INA.ATD_INA_DT_ALTA_ADM BETWEEN TRUNC(SYSDATE-2) AND TRUNC(SYSDATE)
                        -- ATD.ATD_ATE_DT_ATENDIMENTO BETWEEN TRUNC(SYSDATE-100) AND TRUNC(SYSDATE) 
                        ) PLA ON 1=1
          WHERE         (LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO = 'INTERNADO')
          AND           (SETOR.CAD_SET_ID IN (12,14,51,45,200,140,20,17,151,141,18,19,150,201,149,6,7,8,203,1,202,5,63)
          AND           (SETOR.CAD_SET_FL_ATIVO_OK = 'S'))
     )
     WHERE
            (QTD_MOV_ENVIADAS > 0 OR
                QTD_MOV_RECEBIDAS > 0 OR
                QTD_INT_NO_DIA  > 0 OR
                QTD_INT_VINDOS_DIA_ANTERIOR > 0 OR
                QTD_PACIENTE_DIA > 0 OR
                QTD_SAIDAS_OBITO > 0 OR
                QTD_SAIDAS_SEM_OBITO > 0 OR
                ALTA_OBITO_MAIS48 > 0 OR
                ALTA_OBITO_MENOS48 > 0 OR
                TOTAL_PARTO_NORMAL > 0 OR
                TOTAL_PARTO_CESARIA > 0 OR
                TOTAL_PARTO_FORCEPS > 0 OR
                TOTAL_RN > 0 OR
                TOTAL_RN_MORTO > 0 OR
                TOTAL_PARTO_GEMELAR > 0 )
        )
    LOOP
            INSERT INTO TB_ATD_ICD_INT_CENSODIARIO  VALUES
             (TRUNC(SYSDATE-1) ,LINHAS.CAD_SET_ID , LINHAS.CAD_PLA_ID_PLANO , LINHAS.QTD_INT_NO_DIA ,
             LINHAS.QTD_SAIDAS_SEM_OBITO, LINHAS.ALTA_OBITO_MAIS48, LINHAS.ALTA_OBITO_MENOS48,
              LINHAS.QTD_MOV_RECEBIDAS, LINHAS.QTD_MOV_ENVIADAS, LINHAS.QTD_PACIENTE_DIA, 1, TRUNC(SYSDATE-1),
             LINHAS.TOTAL_RN, LINHAS.TOTAL_PARTO_NORMAL,LINHAS.TOTAL_PARTO_CESARIA, LINHAS.TOTAL_PARTO_FORCEPS,
             LINHAS.TOTAL_RN_MORTO,LINHAS.TOTAL_PARTO_GEMELAR
              );
    END LOOP;
COMMIT;
  --    io_cursor := v_cursor;
    end PRC_INT_REL_CENSO_DIARIO;
/
