CREATE OR REPLACE PROCEDURE PRC_BNF_ACIDENTE_TRABALHO
(
       pCODCON IN BNF_CARENCIA_BENEFICIARIO.CODCON%TYPE,
       pCODEST IN BNF_BENEFICIARIO.CODEST%TYPE,
       pCODBEN IN BNF_BENEFICIARIO.CODBEN%TYPE,
       pCODSEQBEN IN BNF_BENEFICIARIO.CODSEQBEN%TYPE,
       io_cursor OUT PKG_CURSOR.t_cursor
)
IS 
 v_cursor PKG_CURSOR.t_cursor;
BEGIN
       OPEN v_cursor FOR
        SELECT count(*) as RETORNO
        FROM BNF_BENEFICIARIO A, BENEFICIARIO.BNF_ACIDENTE_TRABALHO B
        WHERE A.CODCON = pCODCON
        AND A.CODEST = pCODEST                                           
        AND A.CODBEN = pCODBEN
        AND A.CODSEQBEN = pCODSEQBEN
        AND A.CODCON = B.CODCON
        AND A.CODGRAPAR = B.CODGRAPAR
        AND ((TRUNC(SYSDATE) BETWEEN TRUNC(B.DAT_INI_VIG) AND TRUNC(B.DAT_FIM_VIG))
    	OR (B.DAT_FIM_VIG IS NULL));
    	
io_cursor := v_cursor;

END PRC_BNF_ACIDENTE_TRABALHO;