CREATE OR REPLACE PROCEDURE "PRC_CAD_FEX_NOF_L"
  (
    pCAD_FEX_ID             IN TB_FAT_NOF_NOTA_FISCAL.CAD_FEX_ID%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO    IN TB_FAT_NOF_NOTA_FISCAL.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pFAT_NOF_NR_NOTAFISCAL  IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_NR_NOTAFISCAL%TYPE DEFAULT NULL,
    pFAT_NOF_TP_SERIEFISCAL IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_TP_SERIEFISCAL%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE     IN TB_FAT_NOF_NOTA_FISCAL.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pDATA_INI               IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pDATA_FIM               IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pPROTOCOLO_LIBERADO_S   VARCHAR2 DEFAULT NULL,
    pPROTOCOLO_LIBERADO_N   VARCHAR2 DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_CAD_FEX_L
  *
  *    Data Criação: 05/12/2012  Por: PEDRO
  *    Alteracao:
  *
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
SELECT NULL SELECIONADO,
       
       FEX.CAD_FEX_RAZAO_SOCIAL,
       FEX.CAD_FEX_PESSOA_CONTATO,
       FEX.CAD_FEX_TELEFONE,
       FEX.CAD_FEX_EMAIL,
       FEX.CAD_FEX_NUMERO_FORMULARIO,
       FEX.SEG_USU_ID_USUARIO_CRIACAO,
       FEX.CAD_FEX_DT_CRIACAO,
       FEX.SEG_USU_ID_USUARIO_ATUALIZ,
       FEX.CAD_FEX_DT_ULTIMA_ATUALIZ,
       FEX.CAD_FEX_DS_OBSERVACAO,
       FEX.CAD_FEX_INICIO_VIGENCIA,
       FEX.CAD_FEX_FIM_VIGENCIA,
       USU_CRI.SEG_USU_DS_NOME SEG_USU_DS_NOME_CRIACAO,
       USU_ATU.SEG_USU_DS_NOME SEG_USU_DS_NOME_ATUALIZ,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.FAT_NFO_VL_FATURADO,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_FL_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_DT_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_OBS_PROTOCOLO,
       FEX.CAD_FEX_NOME_FANTASIA,
       NOF.CAD_FEX_NUMERO_FORMULARIO CAD_FEX_NUMERO_FORMULARIO_NOF,
       NOF.CAD_UNI_ID_UNIDADE,
       NOF.SEG_USU_ID_USUARIO_LIB_PROTOC,
       FEX.CAD_FEX_ID,
       NOF.FAT_NOF_ID,
       USU_LIB.SEG_USU_DS_NOME SEG_USU_DS_NOME_lLIB,
       UNI.CAD_UNI_CD_UNID_HOSPITALAR,
       UNI.CAD_UNI_DS_UNIDADE,
       CNV.CAD_CNV_ID_CONVENIO,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       CNV.CAD_CNV_DS_RAZAOSOCIAL
FROM      TB_FAT_NOF_NOTA_FISCAL          NOF
JOIN      TB_CAD_UNI_UNIDADE              UNI ON UNI.CAD_UNI_ID_UNIDADE       = NOF.CAD_UNI_ID_UNIDADE
JOIN      TB_CAD_CNV_CONVENIO             CNV ON CNV.CAD_CNV_ID_CONVENIO      = NOF.CAD_CNV_ID_CONVENIO
LEFT JOIN TB_CAD_FEX_FORMULARIO_EXPED     FEX ON FEX.CAD_FEX_ID               = NOF.CAD_FEX_ID
LEFT JOIN TB_SEG_USU_USUARIO          USU_LIB ON USU_LIB.SEG_USU_ID_USUARIO   = NOF.SEG_USU_ID_USUARIO_LIB_PROTOC
LEFT JOIN TB_SEG_USU_USUARIO          USU_CRI ON USU_CRI.SEG_USU_ID_USUARIO   = FEX.SEG_USU_ID_USUARIO_CRIACAO
LEFT JOIN TB_SEG_USU_USUARIO          USU_ATU ON USU_ATU.SEG_USU_ID_USUARIO   = FEX.SEG_USU_ID_USUARIO_ATUALIZ
WHERE     NOF.FAT_NOF_FL_STATUS = 'A'
AND       NOF.FAT_NFO_DT_EMISSAO >= pDATA_INI
AND       NOF.FAT_NFO_DT_EMISSAO <= pDATA_FIM
AND       (pCAD_UNI_ID_UNIDADE IS NULL OR NOF.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
AND       (pCAD_CNV_ID_CONVENIO IS NULL OR CNV.CAD_CNV_ID_CONVENIO IN  (SELECT CNC.CAD_CNV_ID_CONVENIO_DE  FROM TB_CAD_CNC_CONV_ENVIO_CORRESP CNC 
                                        WHERE CNC.CAD_CNE_FL_STATUS = 'A' AND CNC.CAD_CNV_ID_CONVENIO_PARA = pCAD_CNV_ID_CONVENIO
                                        UNION 
                                       SELECT CNV.CAD_CNV_ID_CONVENIO FROM TB_CAD_CNV_CONVENIO CNV
                                        WHERE CNV.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
                                       ))

AND       (pFAT_NOF_NR_NOTAFISCAL IS NULL OR NOF.FAT_NOF_NR_NOTAFISCAL = pFAT_NOF_NR_NOTAFISCAL)
AND       (pFAT_NOF_TP_SERIEFISCAL IS NULL OR NOF.FAT_NOF_TP_SERIEFISCAL = pFAT_NOF_TP_SERIEFISCAL)
AND       (
          (pPROTOCOLO_LIBERADO_S IS NOT NULL AND NOF.FAT_NOF_FL_LIBERA_PROTOCOLO = 'S') OR
          (pPROTOCOLO_LIBERADO_N IS NOT NULL AND (NOF.FAT_NOF_FL_LIBERA_PROTOCOLO = 'N' OR NOF.FAT_NOF_FL_LIBERA_PROTOCOLO IS NULL))
          )
AND       (pCAD_FEX_ID IS NULL OR FEX.CAD_FEX_ID = pCAD_FEX_ID)
ORDER BY  NOF.FAT_NFO_DT_EMISSAO,CNV.CAD_CNV_CD_HAC_PRESTADOR,TO_NUMBER(NOF.CAD_FEX_NUMERO_FORMULARIO),TO_NUMBER(NOF.FAT_NOF_NR_NOTAFISCAL)
;
io_cursor := v_cursor;
end PRC_CAD_FEX_NOF_L;
 