--PRC_CAD_PAH_PERC_ACRESCIMO_HR_S
  create or replace procedure PRC_CAD_PAH_PERC_ACRESC_HR_S 
  (
     pCAD_TAP_TP_ATRIBUTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_TAP_TP_ATRIBUTO%type DEFAULT NULL,
     pCAD_PAH_PC_ACRESCIMO_HR IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_PC_ACRESCIMO_HR%type DEFAULT NULL,
     pCAD_PAH_HR_INICIO_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_INICIO_SEMANA%type DEFAULT NULL,
     pCAD_PAH_HR_FIM_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_HR_FIM_SEMANA%type DEFAULT NULL,
     pCAD_PAH_DT_INICIO_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_INICIO_VIGENCIA%type DEFAULT NULL,
     pCAD_PAH_DT_FIM_VIGENCIA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pCAD_PAH_DT_ULTIMA_ATUALIZACAO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_PAH_NR_DIA_SEMANA IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_NR_DIA_SEMANA%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pCAD_PAH_ID IN TB_CAD_PAH_PERC_ACRESCIMO_HR.CAD_PAH_ID%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  ) 
  is
  /********************************************************************
  *    Procedure: PRC_CAD_PAH_PERC_ACRESC_HR_S
  * 
  *    Data Criacao:   data da  criação   Por: Nome do Analista
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT  
       CAD_TAP_TP_ATRIBUTO,
       CAD_PAH_PC_ACRESCIMO_HR,
       CAD_PAH_HR_INICIO_SEMANA,
       CAD_PAH_HR_FIM_SEMANA,
       CAD_PAH_DT_INICIO_VIGENCIA,
       CAD_PAH_DT_FIM_VIGENCIA,
       CAD_PAH_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_PAH_NR_DIA_SEMANA,
       CAD_CNV_ID_CONVENIO,
       CAD_PAH_ID
    FROM TB_CAD_PAH_PERC_ACRESCIMO_HR
    WHERE
        (pCAD_TAP_TP_ATRIBUTO is null OR CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO) AND 
        (pCAD_PAH_PC_ACRESCIMO_HR is null OR CAD_PAH_PC_ACRESCIMO_HR = pCAD_PAH_PC_ACRESCIMO_HR) AND 
        (pCAD_PAH_HR_INICIO_SEMANA is null OR CAD_PAH_HR_INICIO_SEMANA = pCAD_PAH_HR_INICIO_SEMANA) AND 
        (pCAD_PAH_HR_FIM_SEMANA is null OR CAD_PAH_HR_FIM_SEMANA = pCAD_PAH_HR_FIM_SEMANA) AND 
        (pCAD_PAH_DT_INICIO_VIGENCIA is null OR CAD_PAH_DT_INICIO_VIGENCIA = pCAD_PAH_DT_INICIO_VIGENCIA) AND 
        (pCAD_PAH_DT_FIM_VIGENCIA is null OR CAD_PAH_DT_FIM_VIGENCIA = pCAD_PAH_DT_FIM_VIGENCIA) AND 
        (pCAD_PAH_DT_ULTIMA_ATUALIZACAO is null OR CAD_PAH_DT_ULTIMA_ATUALIZACAO = pCAD_PAH_DT_ULTIMA_ATUALIZACAO) AND 
        (pSEG_USU_ID_USUARIO is null OR SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND 
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO is null OR CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND 
        (pCAD_PAH_NR_DIA_SEMANA is null OR CAD_PAH_NR_DIA_SEMANA = pCAD_PAH_NR_DIA_SEMANA) AND 
        (pCAD_CNV_ID_CONVENIO is null OR CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO) AND 
        (pCAD_PAH_ID is null OR CAD_PAH_ID = pCAD_PAH_ID);          
    io_cursor := v_cursor;
  end PRC_CAD_PAH_PERC_ACRESC_HR_S;

