CREATE OR REPLACE PROCEDURE PRC_CAD_LOCAL_ATENDIMENTO_S 
  (
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_LAT_DS_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_DS_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_LAT_FL_ATIVO_OK IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_FL_ATIVO_OK%type DEFAULT NULL,
     pCAD_LAT_DT_ULTIMA_ATUALIZACAO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pCAD_LAT_CD_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_CD_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  ) 
  is
  /********************************************************************
  Retorna Lista de Locais de Atendimento para component Combo
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT	 CAD_LAT_ID_LOCAL_ATENDIMENTO,
             CAD_LAT_DS_LOCAL_ATENDIMENTO,
             CAD_LAT_FL_ATIVO_OK,
             CAD_LAT_DT_ULTIMA_ATUALIZACAO,
             SEG_USU_ID_USUARIO,
             CAD_LAT_CD_LOCAL_ATENDIMENTO
    FROM TB_CAD_LAT_LOCAL_ATENDIMENTO
    WHERE
        (pCAD_LAT_ID_LOCAL_ATENDIMENTO  is null OR CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO) AND 
        (pCAD_LAT_DS_LOCAL_ATENDIMENTO  is null OR CAD_LAT_DS_LOCAL_ATENDIMENTO = pCAD_LAT_DS_LOCAL_ATENDIMENTO) AND 
        (pCAD_LAT_FL_ATIVO_OK           is null OR CAD_LAT_FL_ATIVO_OK = pCAD_LAT_FL_ATIVO_OK) AND 
        (pCAD_LAT_DT_ULTIMA_ATUALIZACAO is null OR CAD_LAT_DT_ULTIMA_ATUALIZACAO = pCAD_LAT_DT_ULTIMA_ATUALIZACAO) AND 
        (pSEG_USU_ID_USUARIO            is null OR SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND 
        (pCAD_LAT_CD_LOCAL_ATENDIMENTO  is null OR CAD_LAT_CD_LOCAL_ATENDIMENTO = pCAD_LAT_CD_LOCAL_ATENDIMENTO);          
    io_cursor := v_cursor;
  end PRC_CAD_LOCAL_ATENDIMENTO_S; 
