CREATE OR REPLACE PROCEDURE "PRC_COB_NOF_L"
(
     pFAT_NOF_ID IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_ID%type DEFAULT NULL,
     pFAT_NOF_NR_NOTAFISCAL IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_NR_NOTAFISCAL%type DEFAULT NULL,
     pFAT_NOF_TP_SERIEFISCAL IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_TP_SERIEFISCAL%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE IN TB_FAT_NOF_NOTA_FISCAL.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO IN TB_FAT_NOF_NOTA_FISCAL.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_COB_NOF_L
*
*    Data Criacao:   22/05/2012    Por: PEDRO
*    Data Alteracao: 
*
*    Funcao: Lista NF
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  idtNotaFiscal NUMBER;
  isHistorico number;
/*
select * from tb_cad_cnv_convenio cnv where cnv.cad_cnv_nm_fantasia LIKE '%PETROB%' 783,892,335,502,370,731
select * from tb_cad_cnv_convenio cnv where cnv.cad_cnv_nm_fantasia LIKE '%BRAD%' 740,876
select * from tb_cad_cnv_convenio cnv where cnv.cad_cnv_nm_fantasia LIKE '%SUL%' 556,1002,922,921,1001
private const Int32 IdtPessoa_Petrobras  = 3521;
private const Int32 IdtPessoa_SulAmerica = 353011;
private const Int32 IdtPessoa_Bradesco   = 3572;
*/
begin
  IF (pFAT_NOF_ID IS NULL) THEN 
    BEGIN
      /*
      IF pCAD_CNV_ID_CONVENIO = 731 then
        SELECT NVL(NOF.FAT_NOF_ID,0) INTO idtNotaFiscal FROM TB_FAT_NOF_NOTA_FISCAL NOF 
        WHERE  NOF.FAT_NFO_DT_EMISSAO  > '27/02/2010' 
        AND    NOF.FAT_NOF_FL_STATUS   = 'A' 
        AND    NOF.FAT_NOF_NR_NOTAFISCAL  = pFAT_NOF_NR_NOTAFISCAL
        AND    NOF.FAT_NOF_TP_SERIEFISCAL = pFAT_NOF_TP_SERIEFISCAL
        AND    NOF.CAD_UNI_ID_UNIDADE     = pCAD_UNI_ID_UNIDADE
        AND    NOF.CAD_CNV_ID_CONVENIO   IN (783,892,335,502,370,731);
      ELSE IF  pCAD_CNV_ID_CONVENIO = 1001 then
        SELECT NVL(NOF.FAT_NOF_ID,0) INTO idtNotaFiscal FROM TB_FAT_NOF_NOTA_FISCAL NOF 
        WHERE  NOF.FAT_NFO_DT_EMISSAO  > '27/02/2010' 
        AND    NOF.FAT_NOF_FL_STATUS   = 'A' 
        AND    NOF.FAT_NOF_NR_NOTAFISCAL  = pFAT_NOF_NR_NOTAFISCAL
        AND    NOF.FAT_NOF_TP_SERIEFISCAL = pFAT_NOF_TP_SERIEFISCAL
        AND    NOF.CAD_UNI_ID_UNIDADE     = pCAD_UNI_ID_UNIDADE
        AND    NOF.CAD_CNV_ID_CONVENIO    in (740,876);
      ELSE IF  pCAD_CNV_ID_CONVENIO = 740 then
        SELECT NVL(NOF.FAT_NOF_ID,0) INTO idtNotaFiscal FROM TB_FAT_NOF_NOTA_FISCAL NOF 
        WHERE  NOF.FAT_NFO_DT_EMISSAO  > '27/02/2010' 
        AND    NOF.FAT_NOF_FL_STATUS   = 'A' 
        AND    NOF.FAT_NOF_NR_NOTAFISCAL  = pFAT_NOF_NR_NOTAFISCAL
        AND    NOF.FAT_NOF_TP_SERIEFISCAL = pFAT_NOF_TP_SERIEFISCAL
        AND    NOF.CAD_UNI_ID_UNIDADE     = pCAD_UNI_ID_UNIDADE
        AND    NOF.CAD_CNV_ID_CONVENIO    in (556,1002,922,921,1001);
      END IF;
      END IF;
      END IF;*/
       SELECT NVL(NOF.FAT_NOF_ID,0) INTO idtNotaFiscal FROM TB_FAT_NOF_NOTA_FISCAL NOF 
        WHERE  NOF.FAT_NFO_DT_EMISSAO  > to_date('01/02/2010','dd/MM/yyyy' )
        AND    NOF.FAT_NOF_FL_STATUS   = 'A' 
        AND    NOF.FAT_NOF_NR_NOTAFISCAL  = pFAT_NOF_NR_NOTAFISCAL
        AND    NOF.FAT_NOF_TP_SERIEFISCAL = pFAT_NOF_TP_SERIEFISCAL
        AND    NOF.CAD_UNI_ID_UNIDADE     = pCAD_UNI_ID_UNIDADE
        AND    NOF.CAD_CNV_ID_CONVENIO    = pCAD_CNV_ID_CONVENIO;
    EXCEPTION  WHEN NO_DATA_FOUND THEN idtNotaFiscal := 0;
    END;
  END IF;
  
  BEGIN
  SELECT COUNT(MGCH.COB_MGC_ID) A INTO isHistorico from TB_COB_MGC_COBRANCA_HISTORICO MGCH WHERE MGCH.FAT_NOF_ID = idtNotaFiscal;
  EXCEPTION  WHEN NO_DATA_FOUND THEN isHistorico := 0;
  END;
  
--idtNotaFiscal :=14982;
IF (isHistorico = 0) THEN
OPEN v_cursor FOR
SELECT
       CCP.ATD_GUI_CD_CODIGO,
       CCP.ATD_GUI_CD_SENHA,
       CCP.CAD_PAC_CD_CREDENCIAL,
       CCP.CAD_PES_NM_PESSOA,
       CCP.ATD_ATE_ID,
       CCP.COB_CCP_ID,
       CCP.COB_CCP_VL_TOT_CONTA,       
       NVL(MGC.COB_MGC_VL_MOVIMENTO,0) COB_MGC_VL_MOVIMENTO,
       NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                                     NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0) VALOR_DIGITADO, --vl calculado na tela
       NVL(MGC.COB_MGC_PC_ISS,0) COB_MGC_PC_ISS,
       NVL(MGC.COB_MGC_VL_ISS,0) COB_MGC_VL_ISS,
       NVL(MGC.COB_MGC_PC_IR,0) COB_MGC_PC_IR,
       NVL(MGC.COB_MGC_VL_IR,0) COB_MGC_VL_IR,
       NVL(MGC.COB_MGC_PC_CSLL,0) COB_MGC_PC_CSLL,
       NVL(MGC.COB_MGC_VL_CSLL,0) COB_MGC_VL_CSLL,
       NVL(MGC.COB_MGC_PC_PIS,0) COB_MGC_PC_PIS,
       NVL(MGC.COB_MGC_VL_PIS,0) COB_MGC_VL_PIS,
       NVL(MGC.COB_MGC_PC_COFINS,0) COB_MGC_PC_COFINS,
       NVL(MGC.COB_MGC_VL_COFINS,0) COB_MGC_VL_COFINS,
       BAN.CAD_BAN_CD_BANCO || ' - ' || BAN.CAD_BAN_NM_BANCO CAD_BAN_NM_BANCO,       
       BCT.ASS_BCT_CD_AGENCIA || ' / ' || BCT.ASS_BCT_NR_CONTA ASS_BCT_NR_CONTA,
       MGC.COB_MGC_DT_MOVIMENTO,
       TMC.CAD_TMC_DS_DESCRICAO,
       MGC.COB_MGC_DS_MOTIVO_BAIXA,
       CCP.COB_CCP_DT_PARCELA,
       CCP.ATD_GUI_DT_VALIDADE,
       MGC.COB_MGC_NR_NOTA_CREDITO,
       MGC.COB_MGC_NR_PROT_PROTESTO,
       MGC.CAD_MGC_DT_REGISTRO,       
       MGC.SEG_USU_ID_USUARIO_REG,
       USU1.SEG_USU_DS_NOME SEG_USU_DS_NOME_REG,
       MGC.COB_MGC_DT_ULTIMA_ATUALIZACAO,
        MGC.SEG_USU_ID_USUARIO_ATUALIZ,
       USU2.SEG_USU_DS_NOME SEG_USU_DS_NOME_ATUALIZ,
       NVL(SUM(MGC.COB_MGC_VL_MOVIMENTO) OVER (),0) TOTAL_VL_MOVIMENTO,
       SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                                     NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) OVER () TOTAL_VALOR_DIGITADO,
       SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                  NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) OVER () TOTAL_RETENCOES,
       SUM(NVL(MGC.COB_MGC_VL_ISS,0)) OVER () TOTAL_VALOR_ISS,
       SUM(NVL(MGC.COB_MGC_VL_IR,0)) OVER () TOTAL_VALOR_IRRF,
       SUM(NVL(MGC.COB_MGC_VL_CSLL,0)) OVER () TOTAL_VALOR_CSLL,
       SUM(NVL(MGC.COB_MGC_VL_PIS,0)) OVER () TOTAL_VALOR_PIS,
       SUM(NVL(MGC.COB_MGC_VL_COFINS,0)) OVER () TOTAL_VALOR_COFINS,
       NVL(ANTECIPACAO_DESCONTO.TOTAL_ANTECIPACAO_DESCONTO,0) TOTAL_ANTECIPACAO_DESCONTO,
       NVL(ANTECIPACAO_ACERTO.TOTAL_ANTECIPACAO_ACERTO,0) TOTAL_ANTECIPACAO_ACERTO,
       NOF.FAT_NOF_ID,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.CAD_UNI_ID_UNIDADE,
       NOF.FAT_NOF_FL_STATUS,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_MES_FAT,
       NOF.FAT_NOF_ANO_FAT,
       NOF.CAD_CNV_ID_CONVENIO,
       NOF.CAD_PLA_ID_PLANO,
       NVL(NOF.FAT_NFO_VL_FATURADO,0) FAT_NFO_VL_FATURADO,
       NVL(NOF.FAT_NFO_VL_RETENCAO,0) FAT_NFO_VL_RETENCAO,
       NVL(NOF.FAT_NFO_VL_LIQUIDO,0) FAT_NFO_VL_LIQUIDO,
       NVL(NOF.FAT_NOF_VL_IR,0) FAT_NOF_VL_IR,
       NVL(NOF.FAT_NOF_PC_IR,0) FAT_NOF_PC_IR,
       NVL(NOF.FAT_NOF_VL_ISS,0) FAT_NOF_VL_ISS,
       NVL(NOF.FAT_NOF_PC_ISS,0) FAT_NOF_PC_ISS,
       NVL(NOF.FAT_NOF_VL_COFINS,0) FAT_NOF_VL_COFINS,
       NVL(NOF.FAT_NOF_PC_COFINS,0) FAT_NOF_PC_COFINS,
       NVL(NOF.FAT_NOF_VL_CSLL,0) FAT_NOF_VL_CSLL,
       NVL(NOF.FAT_NOF_PC_CSLL,0) FAT_NOF_PC_CSLL,
       NVL(NOF.FAT_NOF_VL_PIS,0) FAT_NOF_VL_PIS,
       NVL(NOF.FAT_NOF_PC_PIS,0)FAT_NOF_PC_PIS,
       NOF.CAD_MCN_ID,
       NVL(NOF.FAT_NOF_VL_DESCONTO,0) FAT_NOF_VL_DESCONTO,
       NOF.FAT_NOF_DS_DESCONTO,
       NOF.FAT_NOF_FL_JURIDICA,
       NOF.FAT_NOF_NR_DOCUMENTO,
       NOF.FAT_NFO_FL_LIBERADO_COB,
       NOF.FAT_NOF_DT_LIBERA_COBRANCA,
       NOF.FAT_NOF_FL_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_DT_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_FL_ENVIO_ELET_REALIZ,
       NOF.FAT_NOF_DT_ENVIO_ELETR_REALIZ,
       CCP.COB_COC_ID,
       CCP.CAD_PAC_ID_PACIENTE,
       CCP.COB_CCP_HR_PARCELA,       
       CCP.COB_CCP_VL_TOT_DESCONTO,
       CCP.COB_CCP_PC_TOT_DESCONTO,
       CCP.COB_CCP_MES_FAT,
       CCP.COB_CCP_ANO_FAT,
       CCP.COB_CCP_FL_STATUS,
       MGC.COB_MGC_ID,
       MGC.CAD_TMC_ID,
       MGC.COB_MGC_DT_LIBERACAO_CONTAB,
       MGC.ASS_BCT_ID,
       BCT.CAD_BAN_ID,       
       BCT.ASS_BCT_CD_CTA_CAIXA_RM,
       NULL CAD_PAC_NR_PRONTUARIO,
       NULL CAD_PES_DT_NASCIMENTO,
       NULL CAD_PES_TP_SEXO,
       CASE WHEN ROUND(TOTAL_GUIA.SOMA_VL_MOVIMENTO - NC_GUIA.SOMA_VL_MOVIMENTO,2) >= CCP.COB_CCP_VL_TOT_CONTA THEN 'BAIXA'
            WHEN ROUND(TOTAL_GUIA.SOMA_VL_MOVIMENTO - NC_GUIA.SOMA_VL_MOVIMENTO,2) > 0 THEN 'BAIXA PARCIAL'
            ELSE 'PENDENTE' END TIPO_PAGAMENTO
FROM      TB_FAT_NOF_NOTA_FISCAL       NOF
JOIN      TB_COB_CCP_CONTA_CONS_PARC   CCP  ON  CCP.FAT_NOF_ID          = NOF.FAT_NOF_ID
--JOIN      TB_CAD_PAC_PACIENTE          PAC  ON  PAC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
--JOIN      TB_CAD_PES_PESSOA            PES  ON  PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
LEFT JOIN TB_COB_MGC_MOV_GUIA_COBRANCA MGC  ON  MGC.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                           AND  MGC.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                           AND  MGC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                           AND  MGC.COB_COC_ID          = CCP.COB_COC_ID
                                           AND  MGC.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                           AND  MGC.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
                                           AND  MGC.COB_CCP_ID          = CCP.COB_CCP_ID
LEFT JOIN TB_CAD_TMC_TIPO_MOV_COBRANCA TMC  ON  TMC.CAD_TMC_ID          = MGC.CAD_TMC_ID
LEFT JOIN TB_ASS_BCT_BANCO_CONTA       BCT  ON  BCT.ASS_BCT_ID          = MGC.ASS_BCT_ID
LEFT JOIN TB_CAD_BAN_BANCO             BAN  ON  BAN.CAD_BAN_ID          = BCT.CAD_BAN_ID
LEFT JOIN TB_SEG_USU_USUARIO           USU1 ON  USU1.SEG_USU_ID_USUARIO = MGC.SEG_USU_ID_USUARIO_REG
LEFT JOIN TB_SEG_USU_USUARIO           USU2 ON  USU2.SEG_USU_ID_USUARIO = MGC.SEG_USU_ID_USUARIO_ATUALIZ
LEFT JOIN (SELECT SUM(MGC.COB_MGC_VL_MOVIMENTO) SOMA_VL_MOVIMENTO,MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,
          MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE--,MGC.CAD_TMC_ID,MGC.COB_MGC_DT_MOVIMENTO
          FROM TB_COB_MGC_MOV_GUIA_COBRANCA MGC WHERE MGC.CAD_TMC_ID != 2 AND MGC.FAT_NOF_ID = idtNotaFiscal
          GROUP BY MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE
          ) TOTAL_GUIA                      ON  TOTAL_GUIA.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                            AND TOTAL_GUIA.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                            AND TOTAL_GUIA.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                            AND TOTAL_GUIA.COB_COC_ID          = CCP.COB_COC_ID
                                            AND TOTAL_GUIA.COB_CCP_ID          = CCP.COB_CCP_ID
                                            AND TOTAL_GUIA.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                            AND TOTAL_GUIA.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
LEFT JOIN (SELECT SUM(MGC.COB_MGC_VL_MOVIMENTO) SOMA_VL_MOVIMENTO,MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,
          MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE--,MGC.CAD_TMC_ID,MGC.COB_MGC_DT_MOVIMENTO
          FROM TB_COB_MGC_MOV_GUIA_COBRANCA MGC WHERE MGC.CAD_TMC_ID = 2 AND MGC.FAT_NOF_ID = idtNotaFiscal
          GROUP BY MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE
          ) NC_GUIA                         ON  NC_GUIA.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                            AND NC_GUIA.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                            AND NC_GUIA.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                            AND NC_GUIA.COB_COC_ID          = CCP.COB_COC_ID
                                            AND NC_GUIA.COB_CCP_ID          = CCP.COB_CCP_ID
                                            AND NC_GUIA.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                            AND NC_GUIA.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
LEFT JOIN (SELECT SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                  NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) TOTAL_ANTECIPACAO_DESCONTO
                  FROM TB_COB_MGC_MOV_GUIA_COBRANCA MGC 
                  WHERE MGC.FAT_NOF_ID = idtNotaFiscal
                  AND   MGC.CAD_TMC_ID = 8
                  GROUP BY MGC.FAT_NOF_ID
     ) ANTECIPACAO_DESCONTO ON 1=1
LEFT JOIN (SELECT SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                  NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) TOTAL_ANTECIPACAO_ACERTO
                  FROM TB_COB_MGC_MOV_GUIA_COBRANCA MGC 
                  WHERE MGC.FAT_NOF_ID = idtNotaFiscal
                  AND   MGC.CAD_TMC_ID = 9
                  GROUP BY MGC.FAT_NOF_ID
     ) ANTECIPACAO_ACERTO     ON 1=1
WHERE  CCP.COB_CCP_FL_STATUS   = 'A' 
AND    NOF.FAT_NOF_ID = idtNotaFiscal
--AND    CCP.ATD_ATE_ID = 21134755
ORDER BY CCP.CAD_PES_NM_PESSOA,MGC.COB_MGC_DT_MOVIMENTO,TMC.CAD_TMC_DS_DESCRICAO
;
  io_cursor := v_cursor;
ELSE
  OPEN v_cursor FOR
SELECT
       CCP.ATD_GUI_CD_CODIGO,
       CCP.ATD_GUI_CD_SENHA,
       CCP.CAD_PAC_CD_CREDENCIAL,
       CCP.CAD_PES_NM_PESSOA,
       CCP.ATD_ATE_ID,
       CCP.COB_CCP_ID,
       CCP.COB_CCP_VL_TOT_CONTA,       
       NVL(MGC.COB_MGC_VL_MOVIMENTO,0) COB_MGC_VL_MOVIMENTO,
       NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                                     NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0) VALOR_DIGITADO, --vl calculado na tela
       NVL(MGC.COB_MGC_PC_ISS,0) COB_MGC_PC_ISS,
       NVL(MGC.COB_MGC_VL_ISS,0) COB_MGC_VL_ISS,
       NVL(MGC.COB_MGC_PC_IR,0) COB_MGC_PC_IR,
       NVL(MGC.COB_MGC_VL_IR,0) COB_MGC_VL_IR,
       NVL(MGC.COB_MGC_PC_CSLL,0) COB_MGC_PC_CSLL,
       NVL(MGC.COB_MGC_VL_CSLL,0) COB_MGC_VL_CSLL,
       NVL(MGC.COB_MGC_PC_PIS,0) COB_MGC_PC_PIS,
       NVL(MGC.COB_MGC_VL_PIS,0) COB_MGC_VL_PIS,
       NVL(MGC.COB_MGC_PC_COFINS,0) COB_MGC_PC_COFINS,
       NVL(MGC.COB_MGC_VL_COFINS,0) COB_MGC_VL_COFINS,
       BAN.CAD_BAN_CD_BANCO || ' - ' || BAN.CAD_BAN_NM_BANCO CAD_BAN_NM_BANCO,       
       BCT.ASS_BCT_CD_AGENCIA || ' / ' || BCT.ASS_BCT_NR_CONTA ASS_BCT_NR_CONTA,
       MGC.COB_MGC_DT_MOVIMENTO,
       TMC.CAD_TMC_DS_DESCRICAO,
       MGC.COB_MGC_DS_MOTIVO_BAIXA,
       CCP.COB_CCP_DT_PARCELA,
       CCP.ATD_GUI_DT_VALIDADE,
       MGC.COB_MGC_NR_NOTA_CREDITO,
       MGC.COB_MGC_NR_PROT_PROTESTO,
       MGC.CAD_MGC_DT_REGISTRO,       
       MGC.SEG_USU_ID_USUARIO_REG,
       USU1.SEG_USU_DS_NOME SEG_USU_DS_NOME_REG,
       MGC.COB_MGC_DT_ULTIMA_ATUALIZACAO,
        MGC.SEG_USU_ID_USUARIO_ATUALIZ,
       USU2.SEG_USU_DS_NOME SEG_USU_DS_NOME_ATUALIZ,
       NVL(SUM(MGC.COB_MGC_VL_MOVIMENTO) OVER (),0) TOTAL_VL_MOVIMENTO,
       SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                                     NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) OVER () TOTAL_VALOR_DIGITADO,
       SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                  NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) OVER () TOTAL_RETENCOES,
       SUM(NVL(MGC.COB_MGC_VL_ISS,0)) OVER () TOTAL_VALOR_ISS,
       SUM(NVL(MGC.COB_MGC_VL_IR,0)) OVER () TOTAL_VALOR_IRRF,
       SUM(NVL(MGC.COB_MGC_VL_CSLL,0)) OVER () TOTAL_VALOR_CSLL,
       SUM(NVL(MGC.COB_MGC_VL_PIS,0)) OVER () TOTAL_VALOR_PIS,
       SUM(NVL(MGC.COB_MGC_VL_COFINS,0)) OVER () TOTAL_VALOR_COFINS,
       NVL(ANTECIPACAO_DESCONTO.TOTAL_ANTECIPACAO_DESCONTO,0) TOTAL_ANTECIPACAO_DESCONTO,
       NVL(ANTECIPACAO_ACERTO.TOTAL_ANTECIPACAO_ACERTO,0) TOTAL_ANTECIPACAO_ACERTO,
       NOF.FAT_NOF_ID,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.CAD_UNI_ID_UNIDADE,
       NOF.FAT_NOF_FL_STATUS,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_MES_FAT,
       NOF.FAT_NOF_ANO_FAT,
       NOF.CAD_CNV_ID_CONVENIO,
       NOF.CAD_PLA_ID_PLANO,
       NVL(NOF.FAT_NFO_VL_FATURADO,0) FAT_NFO_VL_FATURADO,
       NVL(NOF.FAT_NFO_VL_RETENCAO,0) FAT_NFO_VL_RETENCAO,
       NVL(NOF.FAT_NFO_VL_LIQUIDO,0) FAT_NFO_VL_LIQUIDO,
       NVL(NOF.FAT_NOF_VL_IR,0) FAT_NOF_VL_IR,
       NVL(NOF.FAT_NOF_PC_IR,0) FAT_NOF_PC_IR,
       NVL(NOF.FAT_NOF_VL_ISS,0) FAT_NOF_VL_ISS,
       NVL(NOF.FAT_NOF_PC_ISS,0) FAT_NOF_PC_ISS,
       NVL(NOF.FAT_NOF_VL_COFINS,0) FAT_NOF_VL_COFINS,
       NVL(NOF.FAT_NOF_PC_COFINS,0) FAT_NOF_PC_COFINS,
       NVL(NOF.FAT_NOF_VL_CSLL,0) FAT_NOF_VL_CSLL,
       NVL(NOF.FAT_NOF_PC_CSLL,0) FAT_NOF_PC_CSLL,
       NVL(NOF.FAT_NOF_VL_PIS,0) FAT_NOF_VL_PIS,
       NVL(NOF.FAT_NOF_PC_PIS,0)FAT_NOF_PC_PIS,
       NOF.CAD_MCN_ID,
       NVL(NOF.FAT_NOF_VL_DESCONTO,0) FAT_NOF_VL_DESCONTO,
       NOF.FAT_NOF_DS_DESCONTO,
       NOF.FAT_NOF_FL_JURIDICA,
       NOF.FAT_NOF_NR_DOCUMENTO,
       NOF.FAT_NFO_FL_LIBERADO_COB,
       NOF.FAT_NOF_DT_LIBERA_COBRANCA,
       NOF.FAT_NOF_FL_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_DT_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_FL_ENVIO_ELET_REALIZ,
       NOF.FAT_NOF_DT_ENVIO_ELETR_REALIZ,
       CCP.COB_COC_ID,
       CCP.CAD_PAC_ID_PACIENTE,
       CCP.COB_CCP_HR_PARCELA,       
       CCP.COB_CCP_VL_TOT_DESCONTO,
       CCP.COB_CCP_PC_TOT_DESCONTO,
       CCP.COB_CCP_MES_FAT,
       CCP.COB_CCP_ANO_FAT,
       CCP.COB_CCP_FL_STATUS,
       MGC.COB_MGC_ID,
       MGC.CAD_TMC_ID,
       MGC.COB_MGC_DT_LIBERACAO_CONTAB,
       MGC.ASS_BCT_ID,
       BCT.CAD_BAN_ID,       
       BCT.ASS_BCT_CD_CTA_CAIXA_RM,
       NULL CAD_PAC_NR_PRONTUARIO,
       NULL CAD_PES_DT_NASCIMENTO,
       NULL CAD_PES_TP_SEXO,
       CASE WHEN ROUND(TOTAL_GUIA.SOMA_VL_MOVIMENTO - NC_GUIA.SOMA_VL_MOVIMENTO,2) >= CCP.COB_CCP_VL_TOT_CONTA THEN 'BAIXA'
            WHEN ROUND(TOTAL_GUIA.SOMA_VL_MOVIMENTO - NC_GUIA.SOMA_VL_MOVIMENTO,2) > 0 THEN 'BAIXA PARCIAL'
            ELSE 'PENDENTE' END TIPO_PAGAMENTO
FROM      TB_FAT_NOF_NOTA_FISCAL       NOF
JOIN      TB_COB_CCP_CONTA_HISTORICO   CCP  ON  CCP.FAT_NOF_ID          = NOF.FAT_NOF_ID
--JOIN      TB_CAD_PAC_PACIENTE          PAC  ON  PAC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
--JOIN      TB_CAD_PES_PESSOA            PES  ON  PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
LEFT JOIN TB_COB_MGC_COBRANCA_HISTORICO MGC  ON  MGC.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                           AND  MGC.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                           AND  MGC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                           AND  MGC.COB_COC_ID          = CCP.COB_COC_ID
                                           AND  MGC.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                           AND  MGC.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
                                           AND  MGC.COB_CCP_ID          = CCP.COB_CCP_ID
LEFT JOIN TB_CAD_TMC_TIPO_MOV_COBRANCA TMC  ON  TMC.CAD_TMC_ID          = MGC.CAD_TMC_ID
LEFT JOIN TB_ASS_BCT_BANCO_CONTA       BCT  ON  BCT.ASS_BCT_ID          = MGC.ASS_BCT_ID
LEFT JOIN TB_CAD_BAN_BANCO             BAN  ON  BAN.CAD_BAN_ID          = BCT.CAD_BAN_ID
LEFT JOIN TB_SEG_USU_USUARIO           USU1 ON  USU1.SEG_USU_ID_USUARIO = MGC.SEG_USU_ID_USUARIO_REG
LEFT JOIN TB_SEG_USU_USUARIO           USU2 ON  USU2.SEG_USU_ID_USUARIO = MGC.SEG_USU_ID_USUARIO_ATUALIZ
LEFT JOIN (SELECT SUM(MGC.COB_MGC_VL_MOVIMENTO) SOMA_VL_MOVIMENTO,MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,
          MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE--,MGC.CAD_TMC_ID,MGC.COB_MGC_DT_MOVIMENTO
          FROM TB_COB_MGC_COBRANCA_HISTORICO MGC WHERE MGC.CAD_TMC_ID != 2 AND MGC.FAT_NOF_ID = idtNotaFiscal
          GROUP BY MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE
          ) TOTAL_GUIA                      ON  TOTAL_GUIA.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                            AND TOTAL_GUIA.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                            AND TOTAL_GUIA.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                            AND TOTAL_GUIA.COB_COC_ID          = CCP.COB_COC_ID
                                            AND TOTAL_GUIA.COB_CCP_ID          = CCP.COB_CCP_ID
                                            AND TOTAL_GUIA.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                            AND TOTAL_GUIA.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
LEFT JOIN (SELECT SUM(MGC.COB_MGC_VL_MOVIMENTO) SOMA_VL_MOVIMENTO,MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,
          MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE--,MGC.CAD_TMC_ID,MGC.COB_MGC_DT_MOVIMENTO
          FROM TB_COB_MGC_COBRANCA_HISTORICO MGC WHERE MGC.CAD_TMC_ID = 2 AND MGC.FAT_NOF_ID = idtNotaFiscal
          GROUP BY MGC.FAT_NOF_ID,MGC.ATD_ATE_ID,MGC.CAD_PAC_ID_PACIENTE,MGC.COB_COC_ID,MGC.COB_CCP_ID,MGC.ATD_GUI_CD_CODIGO,MGC.ATD_GUI_DT_VALIDADE
          ) NC_GUIA                         ON  NC_GUIA.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                            AND NC_GUIA.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                            AND NC_GUIA.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                            AND NC_GUIA.COB_COC_ID          = CCP.COB_COC_ID
                                            AND NC_GUIA.COB_CCP_ID          = CCP.COB_CCP_ID
                                            AND NC_GUIA.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                            AND NC_GUIA.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
LEFT JOIN (SELECT SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                  NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) TOTAL_ANTECIPACAO_DESCONTO
                  FROM TB_COB_MGC_COBRANCA_HISTORICO MGC 
                  WHERE MGC.FAT_NOF_ID = idtNotaFiscal
                  AND   MGC.CAD_TMC_ID = 8
                  GROUP BY MGC.FAT_NOF_ID
     ) ANTECIPACAO_DESCONTO ON 1=1
LEFT JOIN (SELECT SUM(NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                  NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) TOTAL_ANTECIPACAO_ACERTO
                  FROM TB_COB_MGC_COBRANCA_HISTORICO MGC 
                  WHERE MGC.FAT_NOF_ID = idtNotaFiscal
                  AND   MGC.CAD_TMC_ID = 9
                  GROUP BY MGC.FAT_NOF_ID
     ) ANTECIPACAO_ACERTO     ON 1=1
WHERE  CCP.COB_CCP_FL_STATUS   = 'A' 
AND    NOF.FAT_NOF_ID = idtNotaFiscal
--AND    CCP.ATD_ATE_ID = 21134755
ORDER BY CCP.CAD_PES_NM_PESSOA,MGC.COB_MGC_DT_MOVIMENTO,TMC.CAD_TMC_DS_DESCRICAO
;
  io_cursor := v_cursor;
  END IF;  
end PRC_COB_NOF_L;
 