CREATE OR REPLACE PROCEDURE PRC_ASS_PCB_CBOS_PRO_RMT_S
(
  PCAD_PRO_ID_PROFISSIONAL IN TB_ASS_PCB_PROFISSIONAL_CBOS.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
  IO_CURSOR OUT PKG_CURSOR.T_CURSOR
)
IS
/**************************************************************************
*    PROCEDURE: PRC_ASS_PCB_CBOS_PRO_RMT_S
*
*    DATA CRIACAO:   15/07/2009   POR: Caio
*    DATA ALTERACAO:              POR: 
*
*    FUNCAO: Listar as especialidades de um profissional do corpo clínico
*
**************************************************************************/
V_CURSOR PKG_CURSOR.T_CURSOR;
BEGIN
  OPEN    V_CURSOR FOR
  SELECT  CBO.TIS_CBO_CD_CBOS,
          CBO.TIS_CBO_DS_CBOS,
          CBO.TIS_CBO_FL_STATUS_ENCAMINHA,
          CBO.TIS_CBO_CD_CBOS_HAC,
          CBO.TIS_CBO_DS_CBOS_HAC,
          CBO.TIS_CBO_FL_QTD_ATE_LIMITADA,
          CBO.TIS_CBO_QT_ATEND_PERM_ANO,
          CBO.TIS_CBO_VL_IDADE_LIMITE_ESP
  FROM    TB_ASS_PCB_PROFISSIONAL_CBOS PCB
  JOIN    TB_TIS_CBO_CBOS              CBO
  ON      PCB.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
  JOIN    TB_CAD_PRO_PROFISSIONAL      PRO
  ON      PCB.CAD_PRO_ID_PROFISSIONAL = PRO.CAD_PRO_ID_PROFISSIONAL
  WHERE   PRO.CAD_PRO_ID_PROFISSIONAL = PCAD_PRO_ID_PROFISSIONAL
  AND     PCB.ASS_PCB_FL_STATUS = 'A'
  --AND     PRO.CAD_PRO_FL_ATIVO_OK = 'S';

        IO_CURSOR := V_CURSOR;
END     PRC_ASS_PCB_CBOS_PRO_RMT_S;
