CREATE OR REPLACE PROCEDURE PRC_CAD_MTMD_INVENTARIO_FECHAR
(
     pCAD_MTMD_FILIAL_ID IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_FILIAL_ID%type,
     pCAD_SET_ID IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_SET_ID%type,
     pCAD_MTMD_DT_INVENTARIO IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_DT_INVENTARIO%type,
     pSEG_USU_ID_USUARIO IN TB_CAD_MTMD_INVENTARIO_FECHA.SEG_USU_ID_USUARIO%type,
     pFL_MEDICAMENTO IN TB_CAD_MTMD_INVENTARIO_FECHA.FL_MEDICAMENTO%type DEFAULT NULL,
     pCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_GRUPO_ID%type DEFAULT NULL
)
is
vCAD_MTMD_FECHAMENTO     TB_CAD_MTMD_INVENTARIO_FECHA.CAD_MTMD_FECHAMENTO%type;
vCAD_MTMD_DT_FECHA_CONT1 DATE;
vCAD_MTMD_DT_FECHA_CONT2 DATE;
vCAD_MTMD_DT_FECHA_CONT3 DATE;
/********************************************************************
*    Procedure: PRC_CAD_MTMD_INVENTARIO_FECHAR_DIG
*
*    Data Criacao:  10/8/11   Por: Andre
*    Data Alteracao: 18/05/16   Por: Andre
*         Alteracao: Add. campos CAD_MTMD_DT_FECHA_CONTX
*
*    Funcao: Fecha digitac?o do inventario
*
*******************************************************************/
begin

SELECT CAD_MTMD_FECHAMENTO+1
  INTO vCAD_MTMD_FECHAMENTO
  FROM TB_CAD_MTMD_INVENTARIO_FECHA
WHERE CAD_MTMD_DT_INVENTARIO = TRUNC(pCAD_MTMD_DT_INVENTARIO)
  AND CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID
  AND CAD_SET_ID = pCAD_SET_ID
  AND (pCAD_MTMD_GRUPO_ID IS NULL OR CAD_MTMD_GRUPO_ID = pCAD_MTMD_GRUPO_ID)
  AND (pCAD_MTMD_GRUPO_ID IS NOT NULL OR CAD_MTMD_GRUPO_ID = 0)
  AND FL_MEDICAMENTO = pFL_MEDICAMENTO;

IF (vCAD_MTMD_FECHAMENTO = 1) THEN vCAD_MTMD_DT_FECHA_CONT1 := SYSDATE; END IF;
IF (vCAD_MTMD_FECHAMENTO = 2) THEN vCAD_MTMD_DT_FECHA_CONT2 := SYSDATE; END IF;
IF (vCAD_MTMD_FECHAMENTO = 3) THEN vCAD_MTMD_DT_FECHA_CONT3 := SYSDATE; END IF;

UPDATE TB_CAD_MTMD_INVENTARIO_FECHA
  SET
            CAD_MTMD_FECHAMENTO = vCAD_MTMD_FECHAMENTO,
            CAD_MTMD_DT_ATUALIZACAO = SYSDATE,
            SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO,
            CAD_MTMD_DT_FECHA_CONT1 = NVL(vCAD_MTMD_DT_FECHA_CONT1,CAD_MTMD_DT_FECHA_CONT1),
            CAD_MTMD_DT_FECHA_CONT2 = NVL(vCAD_MTMD_DT_FECHA_CONT2,CAD_MTMD_DT_FECHA_CONT2),
            CAD_MTMD_DT_FECHA_CONT3 = NVL(vCAD_MTMD_DT_FECHA_CONT3,CAD_MTMD_DT_FECHA_CONT3)
WHERE
        CAD_MTMD_DT_INVENTARIO = TRUNC(pCAD_MTMD_DT_INVENTARIO)
    AND CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID
    AND CAD_SET_ID = pCAD_SET_ID
    AND (pCAD_MTMD_GRUPO_ID IS NULL OR CAD_MTMD_GRUPO_ID = pCAD_MTMD_GRUPO_ID)
    AND (pCAD_MTMD_GRUPO_ID IS NOT NULL OR CAD_MTMD_GRUPO_ID = 0)
    AND FL_MEDICAMENTO = pFL_MEDICAMENTO;

end PRC_CAD_MTMD_INVENTARIO_FECHAR;