CREATE OR REPLACE PROCEDURE PRC_MTMD_MATMED_PERMIS_SETOR
(
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_MTMD_MOV_MOVIMENTACAO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE IN TB_MTMD_MOV_MOVIMENTACAO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_SET_ID IN TB_MTMD_MOV_MOVIMENTACAO.CAD_SET_ID%type DEFAULT NULL,
     pCAD_MTMD_NOMEFANTASIA IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_NOMEFANTASIA%type DEFAULT NULL,
     pCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_GRUPO_ID%type DEFAULT NULL,
     pCOM_ESTOQUE NUMBER DEFAULT NULL, -- 0 ou 1
     pCAD_MTMD_FILIAL_ID IN TB_MTMD_MOV_MOVIMENTACAO.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
) is
 /********************************************************************
  *    Procedure: PRC_MTMD_MATMED_PERMIS_SETOR
  *
  *    Data Criacao:    09/11/2010  Por: Ricardo Costa
  *    Data Alteracao:  11/11/2010  Por: Andre S. Monaco
  *         Alteracao:  Adic?o do parametro pCAD_MTMD_NOMEFANTASIA e pCAD_MTMD_GRUPO_ID
  *    Data Alteracao:  23/07/2012  Por: Andre S. Monaco
  *         Alteracao:  Adic?o do campo CAD_MTMD_CD_ANVISA
  *    Data Alteracao:  20/07/2015  Por: Andre S. Monaco
  *         Alteracao:  Volta do campo CAD_MTMD_PRIATI_ID
  *    Data Alteracao:  25/07/2016  Por: Andre S. Monaco
  *         Alteracao:  Adicao do param. pCOM_ESTOQUE
  *    Data Alteracao:  05/04/2017  Por: Andre S. Monaco
  *         Alteracao:  Adicao do param. pCAD_MTMD_FILIAL_ID
  *    Data Alteracao:  26/04/2017  Por: Andre S. Monaco
  *         Alteracao:  Adicao campo CAD_MTMD_CD_GRUPO_ANVISA
  *    Data Alteracao:  24/10/2017  Por: Andre S. Monaco
  *         Alteracao:  Adicao funcao SOUND ALIKE na descricao
  *
  *    Funcao: Recupera Produto que setor term acesso
  *******************************************************************/
  V_WHERE  varchar2(5000);
  V_SELECT  varchar2(5000);
  v_cursor PKG_CURSOR.t_cursor;
BEGIN

  IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CONFIG.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
  IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CONFIG.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
  IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CONFIG.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
  IF pCAD_MTMD_NOMEFANTASIA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_NOMEFANTASIA LIKE ' || CHR(39) || pCAD_MTMD_NOMEFANTASIA || CHR(39); END IF;
  IF pCAD_MTMD_GRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND PRODUTO.CAD_MTMD_GRUPO_ID = ' || pCAD_MTMD_GRUPO_ID; END IF;
  IF (NVL(pCOM_ESTOQUE,0) = 1 AND NVL(pCAD_MTMD_FILIAL_ID,0) = 0) THEN
    V_WHERE:= V_WHERE || ' AND (SELECT NVL(SUM(MTMD_ESTLOC_QTDE),0)+ NVL(SUM(MTMD_ESTLOC_QTDE_FRACIONADA),0)
                                  FROM TB_MTMD_ESTOQUE_LOCAL EL JOIN
                                       TB_CAD_SET_SETOR SETOR ON SETOR.CAD_SET_ID = EL.CAD_SET_ID
                                 WHERE CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                                       NVL(SETOR.CAD_SET_ALMOX_CENTRAL,0) = 1) > 0 ';
  ELSIF (NVL(pCOM_ESTOQUE,0) = 1 AND NVL(pCAD_MTMD_FILIAL_ID,0) > 0) THEN
    V_WHERE:= V_WHERE || ' AND (SELECT NVL(SUM(MTMD_ESTLOC_QTDE),0)+ NVL(SUM(MTMD_ESTLOC_QTDE_FRACIONADA),0)
                                  FROM TB_MTMD_ESTOQUE_LOCAL EL JOIN
                                       TB_CAD_SET_SETOR SETOR ON SETOR.CAD_SET_ID = EL.CAD_SET_ID JOIN
                                       TB_CAD_MTMD_MAT_MED PROD ON PROD.CAD_MTMD_ID = EL.CAD_MTMD_ID
                                 WHERE EL.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                                       NVL(SETOR.CAD_SET_ALMOX_CENTRAL,0) = 1 AND
                                           ((EL.CAD_MTMD_FILIAL_ID = DECODE(' || pCAD_MTMD_FILIAL_ID || ',2,2,1) AND PROD.CAD_MTMD_GRUPO_ID = 1 AND PROD.CAD_MTMD_FL_FRACIONA = 0) OR
                                            (EL.CAD_MTMD_FILIAL_ID = 1 AND (PROD.CAD_MTMD_GRUPO_ID != 1 OR PROD.CAD_MTMD_FL_FRACIONA = 1)))) > 0 ';
  END IF;
  V_WHERE  := V_WHERE || ' ORDER BY PRODUTO.CAD_MTMD_NOMEFANTASIA';

  V_SELECT := '
    SELECT PRODUTO.CAD_MTMD_ID,
         PRODUTO.CAD_MTMD_FILIAL_ID,
         PRODUTO.CAD_MTMD_PRIATI_ID,
         PRODUTO.CAD_MTMD_GRUPO_ID,
         PRODUTO.CAD_MTMD_SUBGRUPO_ID,
         PRODUTO.TIS_MED_CD_TABELAMEDICA,
         FNC_MTMD_SOUNDALIKE(PRODUTO.CAD_MTMD_NOMEFANTASIA,PRODUTO.CAD_MTMD_GRUPO_ID) CAD_MTMD_NOMEFANTASIA,
         PRODUTO.CAD_MTMD_DESCRICAO,
         PRODUTO.CAD_MTMD_UNIDADE_VENDA,
         PRODUTO.CAD_MTMD_UNIDADE_COMPRA,
         PRODUTO.CAD_MTMD_UNIDADE_CONTROLE,
         PRODUTO.CAD_MTMD_CODMNE,
         PRODUTO.CAD_MTMD_CURVA_ABC,
         PRODUTO.CAD_MTMD_CD_FABRICANTE,
         PRODUTO.CAD_MTMD_FL_FRACIONA,
         PRODUTO.CAD_MTMD_FL_ATIVO,
         PRODUTO.CAD_MTMD_FL_MANTER_ESTOQUE,
         PRODUTO.CAD_MTMD_FL_REUTILIZAVEL,
         PRODUTO.CAD_MTMD_DT_ATUALIZACAO,
         PRODUTO.CAD_MTMD_CD_RM,
         PRODUTO.CAD_MTMD_UNIDADE_CONSUMO,
         PRODUTO.CAD_MTMD_UNID_COMPRA_DS,
         PRODUTO.CAD_MTMD_UNID_CONTROLE_DS,
         PRODUTO.CAD_MTMD_UNID_VENDA_DS,
         PRODUTO.CAD_MTMD_FL_BAIXA_AUTOMATICA,
         PRODUTO.mtmd_tp_fracao_id,
         PRODUTO.CAD_MTMD_FL_FATURADO,
         PRODUTO.CAD_MTMD_CD_ANVISA,
         CASE
             WHEN (PRODUTO.MTMD_TP_FRACAO_ID IS NOT NULL) THEN
                (SELECT MTMD_DS_TP_FRACAO FROM TB_MTMD_TIPO_FRACAO WHERE MTMD_TP_FRACAO_ID = PRODUTO.MTMD_TP_FRACAO_ID)
             ELSE NULL
           END  MTMD_DS_TP_FRACAO,
         PRODUTO.CAD_MTMD_FL_MAV,
         CAD_MTMD_CD_GRUPO_ANVISA,
         CAD_MTMD_FL_DILUENTE,
         CAD_MTMD_PRIATI_SAL_DSC,
         CAD_MTMD_FORMA_FARMACEUTICA,
         CAD_MTMD_DOSAGEM_PADRONIZADA
    FROM TB_CAD_MTMD_MAT_MED   PRODUTO,
         TB_MTMD_MATMED_CONFIG CONFIG
    WHERE PRODUTO.CAD_MTMD_GRUPO_ID           = CONFIG.CAD_MTMD_GRUPO_ID
    AND   PRODUTO.CAD_MTMD_SUBGRUPO_ID        = CONFIG.CAD_MTMD_SUBGRUPO_ID
    AND   PRODUTO.CAD_MTMD_FL_ATIVO           = 1 ';

    OPEN v_cursor FOR
    V_SELECT || V_WHERE ;
    io_cursor := v_cursor;
end PRC_MTMD_MATMED_PERMIS_SETOR;