CREATE OR REPLACE PROCEDURE "PRC_COB_NOF_HISTORICO_L"
(
     pFAT_NOF_NR_NOTAFISCAL  IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_NR_NOTAFISCAL%type DEFAULT NULL,
     pFAT_NOF_TP_SERIEFISCAL IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_TP_SERIEFISCAL%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE     IN TB_FAT_NOF_NOTA_FISCAL.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_CNV_ID_CONVENIO    IN TB_FAT_NOF_NOTA_FISCAL.CAD_CNV_ID_CONVENIO%type DEFAULT NULL,
     pDATA_EMISSAO_INI       IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
     pDATA_EMISSAO_FIM       IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
     pDATA_VENCIMENTO_INI    IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
     pDATA_VENCIMENTO_FIM    IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
     pATD_GUI_CD_CODIGO      IN TB_COB_CCP_CONTA_CONS_PARC.ATD_GUI_CD_CODIGO%TYPE DEFAULT NULL,
     pATD_GUI_CD_SENHA       IN TB_COB_CCP_CONTA_CONS_PARC.ATD_GUI_CD_SENHA%TYPE DEFAULT NULL,
     pATD_ATE_ID             IN TB_COB_CCP_CONTA_CONS_PARC.ATD_ATE_ID%TYPE DEFAULT NULL,
     pCAD_PAC_CD_CREDENCIAL  IN TB_COB_CCP_CONTA_CONS_PARC.CAD_PAC_CD_CREDENCIAL%TYPE DEFAULT NULL,
     pCAD_PES_NM_PESSOA      IN TB_COB_CCP_CONTA_CONS_PARC.CAD_PES_NM_PESSOA%TYPE DEFAULT NULL,
     io_cursor               OUT PKG_CURSOR.t_cursor--,
   -- TESTE OUT  LONG 
)
is
/********************************************************************
*    Procedure: PRC_COB_NOF_HISTORICO_L
*
*    Data Criacao:   23/10/2012    Por: PEDRO
*    Data Alteracao:
*
*    Funcao: Lista NFs
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(2000);
  V_SELECT  varchar2(20000);
  begin
    V_WHERE := NULL;
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE;
    END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;
    END IF;
    IF pATD_ATE_ID IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCP.ATD_ATE_ID = ' || pATD_ATE_ID;
    END IF;
    IF pATD_GUI_CD_CODIGO IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCP.ATD_GUI_CD_CODIGO LIKE ' ||CHR(39)|| pATD_GUI_CD_CODIGO ||CHR(39);
    END IF;
    IF pATD_GUI_CD_SENHA IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCP.ATD_GUI_CD_SENHA LIKE ' ||CHR(39)|| pATD_GUI_CD_SENHA ||CHR(39);
    END IF;
    IF pCAD_PAC_CD_CREDENCIAL IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCP.CAD_PAC_CD_CREDENCIAL = ' ||CHR(39)|| pCAD_PAC_CD_CREDENCIAL ||CHR(39);
    END IF;
    IF pCAD_PES_NM_PESSOA IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND CCP.CAD_PES_NM_PESSOA LIKE ' ||CHR(39)|| pCAD_PES_NM_PESSOA ||CHR(39);
    END IF;
     IF pDATA_EMISSAO_INI IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.FAT_NFO_DT_EMISSAO >= ' ||CHR(39)|| pDATA_EMISSAO_INI ||CHR(39);
    END IF;
    IF pDATA_EMISSAO_FIM IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.FAT_NFO_DT_EMISSAO <= ' ||CHR(39)|| pDATA_EMISSAO_FIM ||CHR(39);
    END IF;
     IF pDATA_VENCIMENTO_INI IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.FAT_NFO_DT_VENCIMENTO >= ' ||CHR(39)|| pDATA_VENCIMENTO_INI ||CHR(39);
    END IF;
    IF pDATA_VENCIMENTO_FIM IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.FAT_NFO_DT_VENCIMENTO <= ' ||CHR(39)|| pDATA_VENCIMENTO_FIM ||CHR(39);
    END IF;
    IF pFAT_NOF_NR_NOTAFISCAL IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.FAT_NOF_NR_NOTAFISCAL = ' ||CHR(39)|| pFAT_NOF_NR_NOTAFISCAL ||CHR(39);
    END IF;
    IF pFAT_NOF_TP_SERIEFISCAL IS NOT NULL THEN
       V_WHERE := V_WHERE || ' AND NOF.FAT_NOF_TP_SERIEFISCAL = ' ||CHR(39)|| pFAT_NOF_TP_SERIEFISCAL ||CHR(39);
    END IF;
    V_SELECT :='
SELECT
       CCP.ATD_GUI_CD_CODIGO,
       CCP.ATD_GUI_CD_SENHA,
       CCP.CAD_PAC_CD_CREDENCIAL,
       CCP.CAD_PES_NM_PESSOA,
       CCP.ATD_ATE_ID,
       CCP.COB_CCP_ID,
       CCP.COB_CCP_VL_TOT_CONTA,
       CCP.COB_CCP_DT_PARCELA,
       CCP.ATD_GUI_DT_VALIDADE,
       NOF.FAT_NOF_ID,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.CAD_UNI_ID_UNIDADE,
       NOF.FAT_NOF_FL_STATUS,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_MES_FAT,
       NOF.FAT_NOF_ANO_FAT,
       NOF.CAD_CNV_ID_CONVENIO,
       NOF.CAD_PLA_ID_PLANO,
       NVL(NOF.FAT_NFO_VL_FATURADO,0) FAT_NFO_VL_FATURADO,
       NVL(NOF.FAT_NFO_VL_RETENCAO,0) FAT_NFO_VL_RETENCAO,
       NVL(NOF.FAT_NFO_VL_LIQUIDO,0) FAT_NFO_VL_LIQUIDO,
       NVL(NOF.FAT_NOF_PC_IR,0) FAT_NOF_PC_IR,
       NVL(NOF.FAT_NOF_VL_IR,0) FAT_NOF_VL_IR,
       NVL(NOF.FAT_NOF_PC_ISS,0) FAT_NOF_PC_ISS,
       NVL(NOF.FAT_NOF_VL_ISS,0) FAT_NOF_VL_ISS,
       NVL(NOF.FAT_NOF_PC_COFINS,0) FAT_NOF_PC_COFINS,
       NVL(NOF.FAT_NOF_VL_COFINS,0) FAT_NOF_VL_COFINS,
       NVL(NOF.FAT_NOF_PC_CSLL,0) FAT_NOF_PC_CSLL,
       NVL(NOF.FAT_NOF_VL_CSLL,0) FAT_NOF_VL_CSLL,
       NVL(NOF.FAT_NOF_PC_PIS,0)FAT_NOF_PC_PIS,
       NVL(NOF.FAT_NOF_VL_PIS,0) FAT_NOF_VL_PIS,
       NOF.CAD_MCN_ID,
       NOF.FAT_NOF_VL_DESCONTO,
       NOF.FAT_NOF_DS_DESCONTO,
       NOF.FAT_NOF_FL_JURIDICA,
       NOF.FAT_NOF_NR_DOCUMENTO,
       NOF.FAT_NFO_FL_LIBERADO_COB,
       NOF.FAT_NOF_DT_LIBERA_COBRANCA,
       NOF.FAT_NOF_FL_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_DT_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_FL_ENVIO_ELET_REALIZ,
       NOF.FAT_NOF_DT_ENVIO_ELETR_REALIZ,
       CCP.COB_COC_ID,
       CCP.CAD_PAC_ID_PACIENTE,
       CCP.COB_CCP_HR_PARCELA,
       CCP.COB_CCP_VL_TOT_DESCONTO,
       CCP.COB_CCP_PC_TOT_DESCONTO,
       CCP.COB_CCP_MES_FAT,
       CCP.COB_CCP_ANO_FAT,
       CCP.COB_CCP_FL_STATUS,
       NULL CAD_PAC_NR_PRONTUARIO,
       NULL CAD_PES_DT_NASCIMENTO,
       NULL CAD_PES_TP_SEXO,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       CNV.CAD_CNV_NM_FANTASIA,
       UNI.CAD_UNI_DS_UNIDADE,
       ''false'' historico
FROM      TB_FAT_NOF_NOTA_FISCAL       NOF
JOIN      TB_COB_CCP_CONTA_CONS_PARC   CCP  ON  CCP.FAT_NOF_ID          = NOF.FAT_NOF_ID
JOIN      TB_CAD_CNV_CONVENIO          CNV  ON  CNV.CAD_CNV_ID_CONVENIO = NOF.CAD_CNV_ID_CONVENIO
JOIN      TB_CAD_UNI_UNIDADE           UNI  ON  UNI.CAD_UNI_ID_UNIDADE  = NOF.CAD_UNI_ID_UNIDADE
WHERE  CNV.CAD_CNV_CD_OPCAO_PAGTO = ''1''
' || V_WHERE || '

UNION ALL

SELECT
       CCP.ATD_GUI_CD_CODIGO,
       CCP.ATD_GUI_CD_SENHA,
       CCP.CAD_PAC_CD_CREDENCIAL,
       CCP.CAD_PES_NM_PESSOA,
       CCP.ATD_ATE_ID,
       CCP.COB_CCP_ID,
       CCP.COB_CCP_VL_TOT_CONTA,
       CCP.COB_CCP_DT_PARCELA,
       CCP.ATD_GUI_DT_VALIDADE,
       NOF.FAT_NOF_ID,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.CAD_UNI_ID_UNIDADE,
       NOF.FAT_NOF_FL_STATUS,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_MES_FAT,
       NOF.FAT_NOF_ANO_FAT,
       NOF.CAD_CNV_ID_CONVENIO,
       NOF.CAD_PLA_ID_PLANO,
       NVL(NOF.FAT_NFO_VL_FATURADO,0) FAT_NFO_VL_FATURADO,
       NVL(NOF.FAT_NFO_VL_RETENCAO,0) FAT_NFO_VL_RETENCAO,
       NVL(NOF.FAT_NFO_VL_LIQUIDO,0) FAT_NFO_VL_LIQUIDO,
       NVL(NOF.FAT_NOF_PC_IR,0) FAT_NOF_PC_IR,
       NVL(NOF.FAT_NOF_VL_IR,0) FAT_NOF_VL_IR,
       NVL(NOF.FAT_NOF_PC_ISS,0) FAT_NOF_PC_ISS,
       NVL(NOF.FAT_NOF_VL_ISS,0) FAT_NOF_VL_ISS,
       NVL(NOF.FAT_NOF_PC_COFINS,0) FAT_NOF_PC_COFINS,
       NVL(NOF.FAT_NOF_VL_COFINS,0) FAT_NOF_VL_COFINS,
       NVL(NOF.FAT_NOF_PC_CSLL,0) FAT_NOF_PC_CSLL,
       NVL(NOF.FAT_NOF_VL_CSLL,0) FAT_NOF_VL_CSLL,
       NVL(NOF.FAT_NOF_PC_PIS,0)FAT_NOF_PC_PIS,
       NVL(NOF.FAT_NOF_VL_PIS,0) FAT_NOF_VL_PIS,
       NOF.CAD_MCN_ID,
       NOF.FAT_NOF_VL_DESCONTO,
       NOF.FAT_NOF_DS_DESCONTO,
       NOF.FAT_NOF_FL_JURIDICA,
       NOF.FAT_NOF_NR_DOCUMENTO,
       NOF.FAT_NFO_FL_LIBERADO_COB,
       NOF.FAT_NOF_DT_LIBERA_COBRANCA,
       NOF.FAT_NOF_FL_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_DT_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_FL_ENVIO_ELET_REALIZ,
       NOF.FAT_NOF_DT_ENVIO_ELETR_REALIZ,
       CCP.COB_COC_ID,
       CCP.CAD_PAC_ID_PACIENTE,
       CCP.COB_CCP_HR_PARCELA,
       CCP.COB_CCP_VL_TOT_DESCONTO,
       CCP.COB_CCP_PC_TOT_DESCONTO,
       CCP.COB_CCP_MES_FAT,
       CCP.COB_CCP_ANO_FAT,
       CCP.COB_CCP_FL_STATUS,
       NULL CAD_PAC_NR_PRONTUARIO,
       NULL CAD_PES_DT_NASCIMENTO,
       NULL CAD_PES_TP_SEXO,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       CNV.CAD_CNV_NM_FANTASIA,
       UNI.CAD_UNI_DS_UNIDADE,
       ''true'' historico
FROM      TB_FAT_NOF_NOTA_FISCAL       NOF
JOIN      TB_COB_CCP_CONTA_HISTORICO   CCP  ON  CCP.FAT_NOF_ID          = NOF.FAT_NOF_ID
JOIN      TB_CAD_CNV_CONVENIO          CNV  ON  CNV.CAD_CNV_ID_CONVENIO = NOF.CAD_CNV_ID_CONVENIO
JOIN      TB_CAD_UNI_UNIDADE           UNI  ON  UNI.CAD_UNI_ID_UNIDADE  = NOF.CAD_UNI_ID_UNIDADE
WHERE  CNV.CAD_CNV_CD_OPCAO_PAGTO = ''1''
' || V_WHERE || '

ORDER BY 4 --CCP.CAD_PES_NM_PESSOA'
;
 -- TESTE :=  V_SELECT ;
OPEN v_cursor FOR
   V_SELECT ;
    io_cursor := v_cursor;
end PRC_COB_NOF_HISTORICO_L;
 