CREATE OR REPLACE PROCEDURE PRC_CAD_MTMD_INVENTARIO_D
(
     pCAD_MTMD_DT_INVENTARIO IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_DT_INVENTARIO%type,
     pCAD_MTMD_FILIAL_ID IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_FILIAL_ID%type,
     pCAD_MTMD_ID IN TB_CAD_MTMD_INVENTARIO.CAD_MTMD_ID%type,
     pCAD_SET_ID IN TB_CAD_MTMD_INVENTARIO.CAD_SET_ID%type,
     pMTMD_COD_LOTE IN TB_CAD_MTMD_INVENTARIO.MTMD_COD_LOTE%type DEFAULT NULL
)
is
/********************************************************************
*    Procedure: PRC_CAD_MTMD_INVENTARIO_D
*
*    Data Criacao: 	10/8/11   Por: Andre
*
*    Funcao: Exclui item digitado de inventario
*
*******************************************************************/
qtdAnterior NUMBER;
begin
  SELECT INV.CAD_MTMD_QTDE_ANTERIOR INTO qtdAnterior
    FROM TB_CAD_MTMD_INVENTARIO INV
   WHERE CAD_MTMD_DT_INVENTARIO = pCAD_MTMD_DT_INVENTARIO
     AND CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID
     AND CAD_MTMD_ID = pCAD_MTMD_ID
     AND CAD_SET_ID = pCAD_SET_ID
     AND NVL(MTMD_COD_LOTE,'0') = NVL(pMTMD_COD_LOTE,'0');
  -- SO DELETA FISICAMENTE SE N?O TIVER ESTOQUE ANTERIOR REGISTRADO
  IF (qtdAnterior IS NULL) THEN
    DELETE TB_CAD_MTMD_INVENTARIO
    WHERE   CAD_MTMD_DT_INVENTARIO = pCAD_MTMD_DT_INVENTARIO
        AND CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID
        AND CAD_MTMD_ID = pCAD_MTMD_ID
        AND CAD_SET_ID = pCAD_SET_ID
        AND NVL(MTMD_COD_LOTE,'0') = NVL(pMTMD_COD_LOTE,'0');
  ELSE
    UPDATE TB_CAD_MTMD_INVENTARIO
    SET CAD_MTMD_QTDE_1 = NULL,
        CAD_MTMD_QTDE_2 = NULL,
        CAD_MTMD_QTDE_3 = NULL,
        CAD_MTMD_QTDE_FINAL = NULL,
        CAD_MTMD_DT_ATUALIZACAO = SYSDATE
    WHERE   CAD_MTMD_DT_INVENTARIO = pCAD_MTMD_DT_INVENTARIO
        AND CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID
        AND CAD_MTMD_ID = pCAD_MTMD_ID
        AND CAD_SET_ID = pCAD_SET_ID
        AND NVL(MTMD_COD_LOTE,'0') = NVL(pMTMD_COD_LOTE,'0');
  END IF;
end PRC_CAD_MTMD_INVENTARIO_D;