CREATE OR REPLACE PROCEDURE PRC_MTMD_BAIXAS_SETOR_R
(
  pCAD_UNI_ID_UNIDADE IN TB_MTMD_ESTOQUE_LOCAL.CAD_UNI_ID_UNIDADE%type,
  pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_MTMD_ESTOQUE_LOCAL.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
  pCAD_SET_ID IN TB_MTMD_ESTOQUE_LOCAL.CAD_SET_ID%type,
  pCAD_MTMD_FILIAL_ID IN TB_MTMD_ESTOQUE_LOCAL.CAD_MTMD_FILIAL_ID%type,
  pCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_GRUPO_ID%type,
  --pCAD_MTMD_SUBGRUPO_ID IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_SUBGRUPO_ID%type DEFAULT NULL,
  pDATA_DE IN DATE,
  pDATA_ATE IN DATE,
  io_cursor OUT PKG_CURSOR.t_cursor
)
IS

 /********************************************************************
  *    Procedure: PRC_MTMD_BAIXAS_SETOR_R
  *
  *    Data Criacao: 16/04/2013    Por: Andre Souza Monaco
  *
  *    Funcao: Query de relatorio de baixas por setor
  *******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
BEGIN
    OPEN v_cursor FOR
    SELECT M.CAD_MTMD_ID ID,
           P.CAD_MTMD_NOMEFANTASIA PRODUTO,
           TRUNC(M.MTMD_MOV_DATA) DATA_BAIXA,
           SUM(M.MTMD_MOV_QTDE) QTDE_BAIXA
      FROM TB_MTMD_MOV_MOVIMENTACAO M INNER JOIN TB_CAD_MTMD_MAT_MED P ON P.CAD_MTMD_ID = M.CAD_MTMD_ID
      WHERE M.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID AND
            M.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE AND
            M.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO AND
            M.CAD_SET_ID = pCAD_SET_ID AND
            M.CAD_MTMD_TPMOV_ID = 2 AND
            M.CAD_MTMD_SUBTP_ID IN (11, 18, 19, 24, 25, 60) AND
            M.MTMD_MOV_FL_ESTORNO = 0 AND
            M.CAD_MTMD_GRUPO_ID = pCAD_MTMD_GRUPO_ID AND
            TRUNC(M.MTMD_MOV_DATA) BETWEEN pDATA_DE AND pDATA_ATE
      GROUP BY TRUNC(M.MTMD_MOV_DATA), M.CAD_MTMD_ID, P.CAD_MTMD_NOMEFANTASIA
      ORDER BY P.CAD_MTMD_NOMEFANTASIA, TRUNC(M.MTMD_MOV_DATA);
    io_cursor := v_cursor;
END;