CREATE OR REPLACE PROCEDURE "PRC_FAT_CCI_DESMARCAR_LOTE_U"
(
    pATD_ATE_ID IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_ID%TYPE,
    pCAD_PAC_ID_PACIENTE IN TB_CAD_PAC_PACIENTE.CAD_PAC_ID_PACIENTE%TYPE,
    pFAT_CCP_ID IN TB_FAT_CCI_CONTA_CONSU_ITEM.FAT_CCP_ID%TYPE,
    pFAT_COC_ID IN TB_FAT_CCI_CONTA_CONSU_ITEM.FAT_COC_ID%TYPE,
    pFAT_CCI_FL_FATURADO in TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_FL_FATURADA%TYPE,
    pSEG_USU_ID_USUARIO in TB_SEG_USU_USUARIO.SEG_USU_ID_USUARIO%type
)
IS
/********************************************************************
*    Procedure: PRC_FAT_CCI_DESMARCAR_LOTE_U
*******************************************************************/
BEGIN
/*
  FOR ITENS IN ( SELECT CCI.FAT_CCI_ID FROM TB_FAT_CCI_CONTA_CONSU_ITEM CCI
    WHERE CCI.FAT_CCP_ID = pFAT_CCP_ID
    AND CCI.FAT_COC_ID = pFAT_COC_ID
    AND CCI.ATD_ATE_ID = pATD_ATE_ID
    AND CCI.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE
    AND CCI.FAT_CCI_FL_STATUS = 'A')
  LOOP
    UPDATE TB_FAT_CCI_CONTA_CONSU_ITEM CCI
    SET CCI.FAT_CCI_FL_FATURADO = pFAT_CCI_FL_FATURADO
    WHERE CCI.FAT_CCI_ID = ITENS.FAT_CCI_ID;
  END LOOP;
	*/

IF(pFAT_CCI_FL_FATURADO = 'N') THEN
  -- Desmarcar Parcelas
  UPDATE TB_FAT_CCP_CONTA_CONS_PARC CCP
  SET CCP.FAT_CCP_FL_FATURADA = 'N',
  CCP.FAT_CCP_DT_FATURAMENTO = NULL,
  CCP.FAT_LNF_ID = NULL,
 CCP.FAT_NOF_ID = NULL
  WHERE CCP.FAT_CCP_ID = pFAT_CCP_ID
  AND CCP.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE
  AND CCP.ATD_ATE_ID = pATD_ATE_ID
  AND CCP.FAT_COC_ID = pFAT_COC_ID;
END IF;
END PRC_FAT_CCI_DESMARCAR_LOTE_U;
 