create or replace procedure PRC_CAD_SETOR_RMT_I
  (
     pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%type,
     pCAD_SET_CD_SETOR IN TB_CAD_SET_SETOR.CAD_SET_CD_SETOR%type,
     pCAD_SET_DS_SETOR IN TB_CAD_SET_SETOR.CAD_SET_DS_SETOR%type,
     pCAD_SET_NR_TELEFONE IN TB_CAD_SET_SETOR.CAD_SET_NR_TELEFONE%type default NULL,
     pCAD_SET_FL_SUBSTALMOX_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_SUBSTALMOX_OK%type,
     pCAD_SET_FL_ESTQPROPRIO_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_ESTQPROPRIO_OK%type,
     pCAD_SET_FL_ATIVO_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_ATIVO_OK%type,
     pCAD_SET_FL_GRAVAATEND_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_GRAVAATEND_OK%type,
     pSEG_USU_ID_USUARIO IN TB_CAD_SET_SETOR.SEG_USU_ID_USUARIO%type,
     pCAD_SET_NR_ANDAR IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%type default NULL,
     pCAD_SET_DT_ULTIMA_ATUALIZACAO IN TB_CAD_SET_SETOR.CAD_SET_DT_ULTIMA_ATUALIZACAO%type,
     pCAD_UNI_ID_UNIDADE IN TB_CAD_SET_SETOR.CAD_UNI_ID_UNIDADE%type,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_SET_SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pCAD_SET_NR_RAMAL IN TB_CAD_SET_SETOR.CAD_SET_NR_RAMAL%type default NULL,
     pCAD_SET_DS_PROCEDENCIA IN TB_CAD_SET_SETOR.CAD_SET_DS_PROCEDENCIA%type default NULL,
     pCAD_SET_FL_ATENDSERVMUL_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_ATENDSERVMUL_OK%type,
     pCAD_SET_UNIDADE_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_UNIDADE_ALMOX%type default NULL,
     pCAD_SET_LOCAL_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_LOCAL_ALMOX%type default NULL,
     pCAD_SET_SETOR_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_SETOR_ALMOX%type default NULL,
     pCAD_SET_ALMOX_CENTRAL IN TB_CAD_SET_SETOR.CAD_SET_ALMOX_CENTRAL%type default NULL,
     pCAD_SET_FL_PERMITEINTERN_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_PERMITEINTERN_OK%type,
     pCAD_SET_FL_PREFERENC_ACS_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_PREFERENC_ACS_OK%type default NULL,
     pCAD_SET_FL_MOVIMENTAPACINT_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_MOVIMENTAPACINT_OK%type,
     pCAD_SET_FL_PERMITELIBLEITO_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_PERMITELIBLEITO_OK%type default NULL,
     pCAD_SET_FL_LANCATXAUTPORT_OK IN TB_CAD_SET_SETOR.CAD_SET_FL_LANCATXAUTPORT_OK%type default NULL		
  )
  is
  /********************************************************************
  *    Procedure: PRC_CAD_SETOR_RMT_I  --CADASTRO REMOTING
  *
  *    Data Criacao:   20/07/09   Por: pEDRO
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
 lIdtRetorno integer;
begin
    SELECT SEQ_CAD_SET_01.NextVal INTO lIdtRetorno FROM DUAL;

    INSERT INTO TB_CAD_SET_SETOR
    (
       CAD_SET_ID,
       CAD_SET_CD_SETOR,
       CAD_SET_DS_SETOR,
       CAD_SET_NR_TELEFONE,
       CAD_SET_FL_SUBSTALMOX_OK,
       CAD_SET_FL_ESTQPROPRIO_OK,
       CAD_SET_FL_ATIVO_OK,
       CAD_SET_FL_GRAVAATEND_OK,
       SEG_USU_ID_USUARIO,
       CAD_SET_NR_ANDAR,
       CAD_SET_DT_ULTIMA_ATUALIZACAO,
       CAD_UNI_ID_UNIDADE,
       CAD_LAT_ID_LOCAL_ATENDIMENTO,
       CAD_SET_NR_RAMAL,
       CAD_SET_DS_PROCEDENCIA,
       CAD_SET_FL_ATENDSERVMUL_OK,
       CAD_SET_UNIDADE_ALMOX,
       CAD_SET_LOCAL_ALMOX,
       CAD_SET_SETOR_ALMOX,
       CAD_SET_ALMOX_CENTRAL,
       CAD_SET_FL_PERMITEINTERN_OK,
       CAD_SET_FL_PREFERENC_ACS_OK,
       CAD_SET_FL_MOVIMENTAPACINT_OK,
       CAD_SET_FL_PERMITELIBLEITO_OK,
       CAD_SET_FL_LANCATXAUTPORT_OK
    )
    VALUES
    (
       lIdtRetorno,
       pCAD_SET_CD_SETOR,
       pCAD_SET_DS_SETOR,
       pCAD_SET_NR_TELEFONE,
       pCAD_SET_FL_SUBSTALMOX_OK,
       pCAD_SET_FL_ESTQPROPRIO_OK,
       pCAD_SET_FL_ATIVO_OK,
       pCAD_SET_FL_GRAVAATEND_OK,
       pSEG_USU_ID_USUARIO,
       pCAD_SET_NR_ANDAR,
       pCAD_SET_DT_ULTIMA_ATUALIZACAO,
       pCAD_UNI_ID_UNIDADE,
       pCAD_LAT_ID_LOCAL_ATENDIMENTO,
       pCAD_SET_NR_RAMAL,
       pCAD_SET_DS_PROCEDENCIA,
       pCAD_SET_FL_ATENDSERVMUL_OK,
       pCAD_SET_UNIDADE_ALMOX,
       pCAD_SET_LOCAL_ALMOX,
       pCAD_SET_SETOR_ALMOX,
       pCAD_SET_ALMOX_CENTRAL,
       pCAD_SET_FL_PERMITEINTERN_OK,
       pCAD_SET_FL_PREFERENC_ACS_OK,
	   pCAD_SET_FL_MOVIMENTAPACINT_OK,
	   pCAD_SET_FL_PERMITELIBLEITO_OK,
		pCAD_SET_FL_LANCATXAUTPORT_OK
    );

  end PRC_CAD_SETOR_RMT_I;
