CREATE OR REPLACE PROCEDURE "PRC_COB_TXT_L"
(
     pCOB_TXT_ID IN TB_COB_TXT_COBRANCA.COB_TXT_ID %type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_COB_TXT_L
*
*    Data Criacao:   16/07/2012    Por: PEDRO
*    Data Alteracao:
*
*    Funcao: Lista MGC
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
begin
OPEN v_cursor FOR
SELECT
       TXT.COB_TXT_NR_GUIA,
       CCP.ATD_GUI_CD_SENHA,
       CCP.CAD_PAC_CD_CREDENCIAL,
       TXT.COB_TXT_CD_BENEF,
       CCP.ATD_ATE_ID,
       CCP.COB_CCP_ID,
       TXT.COB_TXT_NM_BENEF,
       TXT.COB_TXT_NM_BENEF CAD_PES_NM_PESSOA,
       CCP.COB_CCP_VL_TOT_CONTA,
       NVL(TXT.COB_TXT_VL_MOVIMENTO,0) COB_TXT_VL_MOVIMENTO,
       NVL(TXT.COB_TXT_VL_MOVIMENTO,0) + NVL(TXT.COB_TXT_VL_ISS,0) + NVL(TXT.COB_TXT_VL_IR,0) + NVL(TXT.COB_TXT_VL_CSLL,0) + 
                                      NVL(TXT.COB_TXT_VL_PIS,0) + NVL(TXT.COB_TXT_VL_COFINS,0) VALOR_DIGITADO, --vl calculado na tela
       NVL(TXT.COB_TXT_PC_ISS,0) COB_TXT_PC_ISS,
       NVL(TXT.COB_TXT_VL_ISS,0) COB_TXT_VL_ISS,
       NVL(TXT.COB_TXT_PC_IR,0) COB_TXT_PC_IR,
       NVL(TXT.COB_TXT_VL_IR,0) COB_TXT_VL_IR,
       NVL(TXT.COB_TXT_PC_CSLL,0) COB_TXT_PC_CSLL,
       NVL(TXT.COB_TXT_VL_CSLL,0) COB_TXT_VL_CSLL,
       NVL(TXT.COB_TXT_PC_PIS,0) COB_TXT_PC_PIS,
       NVL(TXT.COB_TXT_VL_PIS,0) COB_TXT_VL_PIS,
       NVL(TXT.COB_TXT_PC_COFINS,0) COB_TXT_PC_COFINS,
       NVL(TXT.COB_TXT_VL_COFINS,0) COB_TXT_VL_COFINS,
       BAN.CAD_BAN_CD_BANCO || ' - ' || BAN.CAD_BAN_NM_BANCO CAD_BAN_NM_BANCO,
       BCT.ASS_BCT_CD_AGENCIA || ' / ' || BCT.ASS_BCT_NR_CONTA ASS_BCT_NR_CONTA,
       TXT.COB_TXT_DT_PAGTO ,
       null CAD_TMC_DS_DESCRICAO,
       CCP.COB_CCP_DT_PARCELA,
       CCP.COB_CCP_HR_PARCELA,
       TXT.ATD_GUI_CD_CODIGO,
       TRUNC(CCP.ATD_GUI_DT_VALIDADE) ATD_GUI_DT_VALIDADE,
       TXT.COB_TXT_CD_GLOSA,
       TXT.COB_TXT_VL_GLOSA,
       TXT.COB_TXT_CD_ITEM,
       TXT.COB_TXT_VL_ITEM,
       TXT.COB_TXT_NR_ANEXO,
       TXT.COB_TXT_NR_GUIA_ORIGEM,
       NVL(TXT.COB_TXT_VL_MOVIMENTO_ORIGEM,0) COB_TXT_VL_MOVIMENTO_ORIGEM,
       TXT.COB_TXT_QT_SEPAG,
       TXT.COB_TXT_SEQ_GERAL,
       TXT.COB_TXT_NR_SEQ_PAGTO,
       TXT.COB_TXT_NR_LOTE_TISS,
       TXT.COB_TXT_DT_ATEND,
       TXT.COB_TXT_CD_SERVICO,
       TXT.COB_TXT_DS_SERVICO,
       TXT.COB_TXT_DT_CRIACAO,
       TXT.COB_TXT_DT_ATUALIZA_MGC,
       TXT.COB_TXT_FL_STATUS,
       TXT.COB_TXT_ID,
       SUM(NVL(TXT.COB_TXT_VL_MOVIMENTO,0)) OVER () TOTAL_VL_MOVIMENTO,       
       SUM(NVL(TXT.COB_TXT_VL_MOVIMENTO_ORIGEM,0)) OVER () TOTAL_VL_MOVIMENTO_ORIGEM,
       SUM(NVL(TXT.COB_TXT_VL_MOVIMENTO,0) + NVL(TXT.COB_TXT_VL_ISS,0) + NVL(TXT.COB_TXT_VL_IR,0) + NVL(TXT.COB_TXT_VL_CSLL,0) +
                                     NVL(TXT.COB_TXT_VL_PIS,0) + NVL(TXT.COB_TXT_VL_COFINS,0)) OVER () TOTAL_VALOR_DIGITADO,
       SUM(NVL(TXT.COB_TXT_VL_MOVIMENTO,0) + NVL(TXT.COB_TXT_VL_ISS,0) + NVL(TXT.COB_TXT_VL_IR,0) + NVL(TXT.COB_TXT_VL_CSLL,0) +
                                     NVL(TXT.COB_TXT_VL_PIS,0) + NVL(TXT.COB_TXT_VL_COFINS,0)) OVER ()
                                      -  NVL(SUM(TXT.COB_TXT_VL_MOVIMENTO) OVER (),0) TOTAL_RETENCOES,
       SUM(NVL(TXT.COB_TXT_VL_ISS,0)) OVER () TOTAL_VALOR_ISS,
       SUM(NVL(TXT.COB_TXT_VL_IR,0)) OVER () TOTAL_VALOR_IRRF,
       SUM(NVL(TXT.COB_TXT_VL_CSLL,0)) OVER () TOTAL_VALOR_CSLL,
       SUM(NVL(TXT.COB_TXT_VL_PIS,0)) OVER () TOTAL_VALOR_PIS,
       SUM(NVL(TXT.COB_TXT_VL_COFINS,0)) OVER () TOTAL_VALOR_COFINS,
       NOF.FAT_NOF_ID,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       TXT.CAD_PAC_ID_PACIENTE,
       TXT.CAD_PES_ID_PESSOA,
       TXT.ASS_BCT_ID,
       TXT.COB_COC_ID,
       NOF.CAD_UNI_ID_UNIDADE,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_MES_FAT,
       NOF.FAT_NOF_ANO_FAT,
       NOF.CAD_CNV_ID_CONVENIO,
       NOF.CAD_PLA_ID_PLANO,
       NOF.FAT_NFO_VL_FATURADO,
       NOF.FAT_NFO_VL_RETENCAO,
       NOF.FAT_NFO_VL_LIQUIDO,
       NOF.FAT_NOF_VL_IR,
       NOF.FAT_NOF_PC_IR,
       NOF.FAT_NOF_VL_ISS,
       NOF.FAT_NOF_PC_ISS,
       NOF.FAT_NOF_VL_COFINS,
       NOF.FAT_NOF_PC_COFINS,
       NOF.FAT_NOF_VL_CSLL,
       NOF.FAT_NOF_PC_CSLL,
       NOF.FAT_NOF_VL_PIS,
       NOF.FAT_NOF_PC_PIS,
       NOF.CAD_MCN_ID,
       NOF.FAT_NOF_VL_DESCONTO,
       NOF.FAT_NOF_DS_DESCONTO,
       NOF.FAT_NOF_FL_JURIDICA,
       NOF.FAT_NOF_NR_DOCUMENTO,
       NOF.FAT_NFO_FL_LIBERADO_COB,
       NOF.FAT_NOF_DT_LIBERA_COBRANCA,
       NOF.FAT_NOF_FL_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_DT_LIBERA_PROTOCOLO,
       NOF.FAT_NOF_FL_ENVIO_ELET_REALIZ,
       NOF.FAT_NOF_DT_ENVIO_ELETR_REALIZ,
       NULL COB_CCP_VL_TOT_ORIGINAL,
       ccp.COB_CCP_VL_TOT_DESCONTO,
       CCP.COB_CCP_PC_TOT_DESCONTO,
       CCP.COB_CCP_MES_FAT,
       CCP.COB_CCP_ANO_FAT,
       CCP.COB_CCP_FL_STATUS,
       MGC.COB_MGC_ID,
       CASE WHEN NVL(TXT.COB_TXT_VL_MOVIMENTO,0) < 0 THEN 2 ELSE 1 END CAD_TMC_ID,
       TXT.COB_TXT_DT_PAGTO COB_MGC_DT_MOVIMENTO,
       TXT.COB_TXT_VL_MOVIMENTO COB_MGC_VL_MOVIMENTO,
       NULL COB_MGC_NR_NOTA_CREDITO,
       TRUNC(SYSDATE) CAD_MGC_DT_REGISTRO,
       NULL SEG_USU_ID_USUARIO_REG,
       SYSDATE COB_MGC_DT_ULTIMA_ATUALIZACAO,
       NULL SEG_USU_ID_USUARIO_ATUALIZ,
       NULL COB_MGC_NR_PROT_PROTESTO,
       NULL COB_MGC_DS_MOTIVO_BAIXA,
       NULL COB_MGC_DT_LIBERACAO_CONTAB,
       NVL(TXT.COB_TXT_PC_ISS,0) COB_MGC_PC_ISS,
       NVL(TXT.COB_TXT_VL_ISS,0) COB_MGC_VL_ISS,
       NVL(TXT.COB_TXT_PC_IR,0) COB_MGC_PC_IR,
       NVL(TXT.COB_TXT_VL_IR,0) COB_MGC_VL_IR,
       NVL(TXT.COB_TXT_PC_CSLL,0) COB_MGC_PC_CSLL,
       NVL(TXT.COB_TXT_VL_CSLL,0) COB_MGC_VL_CSLL,
       NVL(TXT.COB_TXT_PC_PIS,0) COB_MGC_PC_PIS,
       NVL(TXT.COB_TXT_VL_PIS,0) COB_MGC_VL_PIS,
       NVL(TXT.COB_TXT_PC_COFINS,0) COB_MGC_PC_COFINS,
       NVL(TXT.COB_TXT_VL_COFINS,0) COB_MGC_VL_COFINS,
       BCT.CAD_BAN_ID,
       BCT.ASS_BCT_CD_CTA_CAIXA_RM,
       NULL CAD_PAC_NR_PRONTUARIO,
       NULL TIPO_PAGAMENTO,
       SUM(NVL(TXT.COB_TXT_VL_MOVIMENTO,0) + NVL(TXT.COB_TXT_VL_ISS,0) + NVL(TXT.COB_TXT_VL_IR,0) + NVL(TXT.COB_TXT_VL_CSLL,0) +
                                     NVL(TXT.COB_TXT_VL_PIS,0) + NVL(TXT.COB_TXT_VL_COFINS,0)) OVER (PARTITION BY NOF.FAT_NOF_ID) TOTAL_VALOR_DIGITADO_NOTA,
       SUM(NVL(TXT.COB_TXT_VL_MOVIMENTO,0) + NVL(TXT.COB_TXT_VL_ISS,0) + NVL(TXT.COB_TXT_VL_IR,0) + NVL(TXT.COB_TXT_VL_CSLL,0) +
                                     NVL(TXT.COB_TXT_VL_PIS,0) + NVL(TXT.COB_TXT_VL_COFINS,0)) OVER (PARTITION BY NOF.FAT_NOF_ID)
                                      -  NVL(SUM(TXT.COB_TXT_VL_MOVIMENTO) OVER (PARTITION BY NOF.FAT_NOF_ID),0) TOTAL_RETENCOES_NOTA,
       SUM(NVL(TXT.COB_TXT_VL_ISS,0)) OVER (PARTITION BY NOF.FAT_NOF_ID) TOTAL_VALOR_ISS_NOTA,
       SUM(NVL(TXT.COB_TXT_VL_IR,0)) OVER (PARTITION BY NOF.FAT_NOF_ID) TOTAL_VALOR_IRRF_NOTA,
       SUM(NVL(TXT.COB_TXT_VL_CSLL,0)) OVER (PARTITION BY NOF.FAT_NOF_ID) TOTAL_VALOR_CSLL_NOTA,
       SUM(NVL(TXT.COB_TXT_VL_PIS,0)) OVER (PARTITION BY NOF.FAT_NOF_ID) TOTAL_VALOR_PIS_NOTA,
       SUM(NVL(TXT.COB_TXT_VL_COFINS,0)) OVER (PARTITION BY NOF.FAT_NOF_ID) TOTAL_VALOR_COFINS_NOTA,
       TXT.COB_TXT_FL_PROCESSAR,
       NVL((SELECT 'S' FROM TB_COB_CCP_CONTA_HISTORICO CCPH WHERE CCPH.FAT_NOF_ID = TXT.FAT_NOF_ID AND ROWNUM = 1),'N') historico,
       NVL((SELECT 'S' FROM TB_COB_MGC_MOV_GUIA_COBRANCA MGC WHERE MGC.CAD_TMC_ID=12 AND MGC.FAT_NOF_ID = TXT.FAT_NOF_ID AND ROWNUM = 1
            UNION
            SELECT 'S' FROM TB_COB_MGC_COBRANCA_HISTORICO MGCH WHERE MGCH.CAD_TMC_ID=12 AND MGCH.FAT_NOF_ID = TXT.FAT_NOF_ID AND ROWNUM = 1),'N') existebaixaautorizada
FROM      TB_COB_TXT_COBRANCA          TXT
LEFT JOIN TB_FAT_NOF_NOTA_FISCAL       NOF  ON  NOF.FAT_NOF_ID          = TXT.FAT_NOF_ID
LEFT JOIN TB_COB_CCP_CONTA_CONS_PARC   CCP  ON  CCP.FAT_NOF_ID          = TXT.FAT_NOF_ID
                                            AND CCP.ATD_ATE_ID          = TXT.ATD_ATE_ID
                                            AND CCP.COB_CCP_ID          = TXT.COB_CCP_ID
                                            AND CCP.CAD_PAC_ID_PACIENTE = TXT.CAD_PAC_ID_PACIENTE
                                            AND CCP.COB_COC_ID          = TXT.COB_COC_ID
                                            AND CCP.ATD_GUI_CD_CODIGO   = TXT.ATD_GUI_CD_CODIGO
                                            AND TRUNC(CCP.ATD_GUI_DT_VALIDADE) = TRUNC(TXT.ATD_GUI_DT_VALIDADE)
                                            AND CCP.COB_CCP_FL_STATUS   = 'A'
--/* DESCOMENTAR
LEFT JOIN TB_COB_MGC_MOV_GUIA_COBRANCA MGC  ON  MGC.FAT_NOF_ID          = TXT.FAT_NOF_ID
                                            AND MGC.ATD_ATE_ID          = TXT.ATD_ATE_ID
                                            AND MGC.COB_CCP_ID          = TXT.COB_CCP_ID
                                            AND MGC.CAD_PAC_ID_PACIENTE = TXT.CAD_PAC_ID_PACIENTE
                                            AND MGC.COB_COC_ID          = TXT.COB_COC_ID
                                            AND MGC.ATD_GUI_CD_CODIGO   = TXT.ATD_GUI_CD_CODIGO
                                            AND TRUNC(MGC.ATD_GUI_DT_VALIDADE) = TRUNC(TXT.ATD_GUI_DT_VALIDADE)
                                            AND MGC.COB_MGC_DT_MOVIMENTO = TXT.COB_TXT_DT_PAGTO
                                            AND MGC.ASS_BCT_ID          = TXT.ASS_BCT_ID
--*/
--LEFT JOIN TB_CAD_PAC_PACIENTE          PAC  ON  PAC.CAD_PAC_ID_PACIENTE = TXT.CAD_PAC_ID_PACIENTE
--LEFT JOIN TB_CAD_PES_PESSOA            PES  ON  PES.CAD_PES_ID_PESSOA   = TXT.CAD_PES_ID_PESSOA
--LEFT JOIN TB_CAD_TMC_TIPO_MOV_COBRANCA TMC  ON  TMC.CAD_TMC_ID          = CASE WHEN NVL(TXT.COB_TXT_VL_MOVIMENTO,0) < 0 THEN 2 ELSE 1 END
JOIN      TB_ASS_BCT_BANCO_CONTA       BCT  ON  BCT.ASS_BCT_ID          = TXT.ASS_BCT_ID
JOIN      TB_CAD_BAN_BANCO             BAN  ON  BAN.CAD_BAN_ID          = BCT.CAD_BAN_ID

WHERE  TXT.COB_TXT_ID          = pCOB_TXT_ID
ORDER BY TXT.COB_TXT_SEQ_GERAL
                                  --SELECT * FROM TB_COB_TXT_COBRANCA
;
  io_cursor := v_cursor;
end PRC_COB_TXT_L;
 