CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_CIRUR_ESPEC"
(
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
    pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE,
    pATD_ATE_TP_PACIENTE_I in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_E in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pAUX_GPC_CD_GRUPOPROC in tb_aux_gpc_grupoproc.aux_gpc_cd_grupoproc%type default null,
    pAUX_EPP_CD_ESPECPROC in tb_aux_epp_especproc.aux_epp_cd_especproc%type default null,
    pCAD_PRO_ID_PROF_EXEC in tb_cad_pro_profissional.cad_pro_id_profissional%type default null,
    pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
    pTIS_MED_CD_TABELAMEDICA IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR
    --, TESTE OUT LONG
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_CIRUR_ESPEC
*    DATA ALTERACAO: 03/2/2011  POR: PEDRO
*    ALTERAC?O:
*    DATA ALTERACAO: 23/09/2011  POR: Eduardo Hyppolito
*    Alteração: Inclusão do filtro TipoPaciente_I ou _E
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;

  V_WHERE2  varchar2(3000);
  V_SELECT  varchar2(30000);
begin
  V_WHERE2 := NULL;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND CCI.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pCAD_PLA_ID_PLANO IS NOT NULL THEN    V_WHERE2 := V_WHERE2 || ' AND CCP.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;    END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE2:= V_WHERE2 || ' AND CCP.FAT_CCP_MES_FAT = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE2:= V_WHERE2 || ' AND CCP.FAT_CCP_ANO_FAT = ' || pFAT_CCP_ANO_FAT; END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE2:= V_WHERE2 || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE2:= V_WHERE2 || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT; END IF;
IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND ATE.TIS_TAT_CD_TPATENDIMENTO = ' ||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO ||CHR(39); END IF;
IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND ATE.ATD_ATE_DT_ATENDIMENTO >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);    END IF;
IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND ATE.ATD_ATE_DT_ATENDIMENTO <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);    END IF;
IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND PRD.TIS_MED_CD_TABELAMEDICA = ' || chr(39) || pTIS_MED_CD_TABELAMEDICA || chr(39) ;    END IF;
IF pAUX_GPC_CD_GRUPOPROC IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND PRD.AUX_GPC_CD_GRUPOPROC = ' || chr(39) || pAUX_GPC_CD_GRUPOPROC || chr(39) ;    END IF;
IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND PRD.AUX_EPP_CD_ESPECPROC = ' || chr(39) || pAUX_EPP_CD_ESPECPROC || chr(39) ;    END IF;
IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE2 := V_WHERE2 || ' AND ATE.TIS_CBO_CD_CBOS = ' || chr(39) || pTIS_CBO_CD_CBOS || chr(39) ;    END IF;
IF pCAD_PRD_ID  IS NOT NULL THEN    V_WHERE2 := V_WHERE2 || ' AND CCI.CAD_PRD_ID_COBRADO  = ' || pCAD_PRD_ID ;    END IF;
IF pCAD_PRO_ID_PROF_EXEC  IS NOT NULL THEN    V_WHERE2 := V_WHERE2 || ' AND ATE.CAD_PRO_ID_PROF_EXEC  = ' || pCAD_PRO_ID_PROF_EXEC ;    END IF;
--Este relatorio da diferença com o de cirurgias executadas pois quebra por profissional e aqui é só
--lote gerado e com nota fiscal.
----Nina:"porque tem exames que estao marcados como cirurgia no produto"
V_SELECT:=
'
SELECT  DISTINCT
              PRD.CAD_PRD_CD_CODIGO,
              PRD.CAD_PRD_DS_DESCRICAO,
              PRO.CAD_PRO_NM_NOME,
              PRO.CAD_PRO_NR_CONSELHO,
              CCI.FAT_CCI_TP_PORTEANESTESICO ,             
              CCI.FAT_CCI_MES_FECHAMENTO FAT_CCP_MES_FAT,
              CCI.FAT_CCI_ANO_FECHAMENTO FAT_CCP_ANO_FAT,
              CBOS.TIS_CBO_CD_CBOS_HAC,
              CBOS.TIS_CBO_DS_CBOS_HAC,
              PRO_RESP.CAD_PRO_NM_NOME CAD_PRO_NM_NOME_RESP,
              PRO_RESP.CAD_PRO_NR_CONSELHO CAD_PRO_NR_CONSELHO_RESP,
              NVL(COUNT(CASE WHEN CCI.CAD_UNI_ID_UNIDADE = 244 THEN CCI.FAT_CCI_ID ELSE NULL END) OVER (PARTITION BY  PRD.CAD_PRD_CD_CODIGO,
              PRD.CAD_PRD_DS_DESCRICAO, PRO.CAD_PRO_NM_NOME, PRO.CAD_PRO_NR_CONSELHO, CCI.FAT_CCI_TP_PORTEANESTESICO ,             
              CCI.FAT_CCI_MES_FECHAMENTO , CCI.FAT_CCI_ANO_FECHAMENTO , CBOS.TIS_CBO_CD_CBOS_HAC,
              CBOS.TIS_CBO_DS_CBOS_HAC, PRO_RESP.CAD_PRO_NM_NOME , PRO_RESP.CAD_PRO_NR_CONSELHO),0) TOTAL_SANTOS,
              NVL(0,0) TOTAL_GUARUJA, --guaruja comentado
             NVL(COUNT(CASE WHEN CCI.CAD_UNI_ID_UNIDADE = 247 THEN CCI.FAT_CCI_ID ELSE NULL END) OVER (PARTITION BY  PRD.CAD_PRD_CD_CODIGO,
              PRD.CAD_PRD_DS_DESCRICAO, PRO.CAD_PRO_NM_NOME, PRO.CAD_PRO_NR_CONSELHO, CCI.FAT_CCI_TP_PORTEANESTESICO ,             
              CCI.FAT_CCI_MES_FECHAMENTO , CCI.FAT_CCI_ANO_FECHAMENTO , CBOS.TIS_CBO_CD_CBOS_HAC,
              CBOS.TIS_CBO_DS_CBOS_HAC, PRO_RESP.CAD_PRO_NM_NOME , PRO_RESP.CAD_PRO_NR_CONSELHO),0)  TOTAL_SAO_VICENTE
              FROM    TB_FAT_CCI_CONTA_CONSU_ITEM  CCI
              JOIN    TB_FAT_CCP_CONTA_CONS_PARC   CCP
              ON      CCP.FAT_CCP_ID             = CCI.FAT_CCP_ID
              AND     CCP.ATD_ATE_ID             = CCI.ATD_ATE_ID
              AND     CCP.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE
              AND     CCP.FAT_COC_ID             = CCI.FAT_COC_ID
              JOIN    TB_CAD_PRD_PRODUTO           PRD      ON PRD.CAD_PRD_ID              = CCI.CAD_PRD_ID_COBRADO
              JOIN    TB_ATD_ATE_ATENDIMENTO       ATE      ON ATE.ATD_ATE_ID              = CCI.ATD_ATE_ID
              JOIN    TB_CAD_PRO_PROFISSIONAL      PRO      ON PRO.CAD_PRO_ID_PROFISSIONAL = CCI.CAD_PRO_ID_PROFISSIONAL
              JOIN    TB_TIS_CBO_CBOS              CBOS     ON CBOS.TIS_CBO_CD_CBOS        = ATE.TIS_CBO_CD_CBOS
              JOIN    TB_CAD_PRO_PROFISSIONAL      PRO_RESP ON PRO_RESP.CAD_PRO_ID_PROFISSIONAL = ATE.CAD_PRO_ID_PROF_EXEC
              JOIN    TB_FAT_MCC_MOV_COM_CONSUMO   MCC
              ON      MCC.FAT_MCC_ID             = CCI.FAT_MCC_ID
              AND     MCC.ATD_ATE_ID             = CCI.ATD_ATE_ID
              WHERE CCI.CAD_UNI_ID_UNIDADE IN (244,247)
              AND (CCP.FAT_CCP_FL_FATURADA = '||chr(39)||'S'||chr(39)||')
              AND ('||chr(39)|| pATD_ATE_TP_PACIENTE_I ||chr(39)||' IS not NULL and CCI.ATD_ATE_TP_PACIENTE = '||chr(39)||'I'||chr(39)||'
              OR '||chr(39)|| pATD_ATE_TP_PACIENTE_E ||chr(39)||' IS NOT NULL AND CCI.ATD_ATE_TP_PACIENTE = '||chr(39)||'E'||chr(39)||')
              AND     (CCP.FAT_CCP_FL_STATUS = '||chr(39)||'A'||chr(39)||')
              AND     (CCI.FAT_CCI_FL_STATUS = '||chr(39)||'A'||chr(39)||')
            --  AND     (CCI.FAT_CCI_TP_PORTEANESTESICO IS NOT NULL)
              AND     CCI.FAT_CCI_TP_PORTEANESTESICO IN (0,1,2,3,4,5,6,7)
              AND     (PRD.CAD_PRD_FL_CIRURGIA = '||chr(39)||'S'||chr(39)||')
              AND     (CCI.TIS_GPP_CD_GRAU_PART_PROF = '||chr(39)||'0'||chr(39)||')
              AND     (CCI.CAD_TAP_TP_ATRIBUTO IN ('||chr(39)||'HM'||chr(39)||'))
              AND     MCC.FAT_MCC_FL_STATUS   = '||chr(39)||'A'||chr(39)||'
               ' || V_WHERE2 || '
            AND    ('||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)||' IS not NULL and CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'ACS'||chr(39)||'
               OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'PA'||chr(39)||'
               OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'SP'||chr(39)||'
               OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'FU'||chr(39)||'
               OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||chr(39)||' IS NOT NULL AND CCP.CAD_TPE_CD_CODIGO = '||chr(39)||'NP'||chr(39)||')'

  ;
  --TESTE := V_SELECT;
  OPEN v_cursor FOR
   V_SELECT ;
  --SELECT 1 FROM DUAL;
    io_cursor := v_cursor;
END PRC_FAT_REL_CIRUR_ESPEC;
