CREATE OR REPLACE PROCEDURE PRC_USP_SPL_SUBPLANO_S
(
   pCAD_UNI_ID_UNIDADE IN TB_ASS_USP_UNI_LAT_SUB_PLANO.CAD_UNI_ID_UNIDADE%type,
   pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_USP_UNI_LAT_SUB_PLANO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
   pCAD_CNV_ID_CONVENIO IN TB_CAD_SPL_SUB_PLANO.CAD_CNV_ID_CONVENIO%type,
   pCAD_PLA_ID_PLANO IN TB_ASS_USP_UNI_LAT_SUB_PLANO.CAD_PLA_ID_PLANO%type DEFAULT NULL,         
   IO_CURSOR OUT PKG_CURSOR.T_CURSOR
)
is
/********************************************************************
*    Procedure: PRC_USP_SPL_SUBPLANO_S
*
*    Data Criacao:   27/08/2009   Por: Caio H. B. Chagas
*    Data Alteracao:  data da alteração  Por: Nome do Analista
*
*    Funcao: Selecionar os sub planos por unidade, local, convenio 
*            plano opcional. 
*
*******************************************************************/
V_CURSOR PKG_CURSOR.T_CURSOR;
BEGIN
  OPEN V_CURSOR FOR
  SELECT  SPL.CAD_SPL_ID,
		  SPL.CAD_SPL_CD_SUB_PLANO,
		  SPL.CAD_SPL_DS_SUB_PLANO,
		  SPL.CAD_SPL_FL_STATUS,
	      SPL.CAD_CNV_ID_CONVENIO
  FROM    TB_ASS_USP_UNI_LAT_SUB_PLANO USP
  JOIN    TB_CAD_SPL_SUB_PLANO SPL
  ON      USP.CAD_SPL_ID = SPL.CAD_SPL_ID
  WHERE   USP.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE
  AND     USP.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
  AND     SPL.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
  AND     (pCAD_PLA_ID_PLANO IS NULL OR USP.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
  AND     USP.ASS_USP_FL_STATUS = 'A';
  IO_CURSOR := V_CURSOR;
END PRC_USP_SPL_SUBPLANO_S;

