CREATE OR REPLACE PROCEDURE PRC_ATE_REL_ESTAT_LOCAL_ESPEC(PCAD_UNI_ID_UNIDADE           IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
                                                          PCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
                                                          PCAD_SET_ID                   IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
                                                          PTIS_CBO_CD_CBOS              IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
                                                          PATD_DT_INICIO                IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
                                                          PATD_DT_FIM                   IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
                                                          pCAD_CGC_ID                   IN tb_cad_cnv_convenio.cad_cgc_id%TYPE DEFAULT NULL,
                                                          IO_CURSOR                     OUT PKG_CURSOR.T_CURSOR) IS
  /********************************************************************
  *    PROCEDURE: PRC_ATE_REL_ESTAT_LOCAL_ESPEC
  *
  *    DT. ALTERAC?O: 03/05/2011  POR: EDUARDO
  *    ALTERACAO: CAPACIDADE
  *
  *    FUNCAO: ALIMENTAR RELATORIO DAS ESTATISTICAS DO ATENDIMENTO POR LOCAL E ESPECIALIDADE
  *
  *      AGG_TP_HORARIO
  *     ? NORMAL = 1
  *     ? ENCAIXE = 2
  *     ? ENCAIXE ESPECIAL = 3
  *     ? RETORNO = 4
  *     ? SERVICO PRESTADO = 5
  *
  *******************************************************************/
  V_CURSOR PKG_CURSOR.T_CURSOR;
BEGIN
  OPEN V_CURSOR FOR
    SELECT ATD.CAD_UNI_ID_UNIDADE ID_UNIDADE,
           UNI.CAD_UNI_DS_UNIDADE DS_UNIDADE,
           ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO ID_LOCAL,
           LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO DS_LOCAL,
           CBO.TIS_CBO_CD_CBOS ID_ESPEC,
           CBO.TIS_CBO_DS_CBOS_HAC DS_ESPEC,
           NVL(FALTAS.TOTAL_FALTA, 0) TOTAL_FALTA,
           NVL(ATENDIDOS.TOTAL_ATEND, 0) TOTAL_ATEND,
           PCT.TOTAL_UNIDADE,
           CAPACIDADE.TOTAL_CAP,
           NVL(AGENDADOS.TOTAL_AGEND, 0) TOTAL_AGEND,
           NVL(ROUND((SUM(FALTAS.TOTAL_FALTA) * 100) / (SUM(AGENDADOS.TOTAL_AGEND)), 2), 0) ABSENTEISMO,
           NVL(RETORNO.TOTAL_RETORNO, 0) TOTAL_RETORNO
      FROM  ------------------
            (SELECT ESM.CAD_UNI_ID_UNIDADE,
                    ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                    ESM.TIS_CBO_CD_CBOS TIS_CBO_CD_CBOS,
                    COUNT(AGD.AGE_AGD_CD_INTAMB) TOTAL_FALTA
               FROM TB_AGE_AGD_AGENDA            AGD,
                    TB_AGE_ESM_ESCALA_MEDICA     ESM,
                    TB_CAD_UNI_UNIDADE           UNI,
                    TB_CAD_LAT_LOCAL_ATENDIMENTO LAT,
                    TB_TIS_CBO_CBOS              CBO
              WHERE (AGD.AGE_AGD_DT_ATENDIMENTO BETWEEN PATD_DT_INICIO AND PATD_DT_FIM)
                AND AGD.AGE_AGD_FL_STATUS = 'F'
                AND ESM.AGE_ESM_ID = AGD.AGE_ESM_ID
                AND ESM.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
                AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO
                AND ESM.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
                AND (PCAD_UNI_ID_UNIDADE IS NULL OR ESM.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
                AND (ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
                AND (PTIS_CBO_CD_CBOS IS NULL OR ESM.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
              GROUP BY ESM.CAD_UNI_ID_UNIDADE,
                       ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                       ESM.TIS_CBO_CD_CBOS)                            FALTAS,
           ------------------
           (SELECT ESM.CAD_UNI_ID_UNIDADE,
                   ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                   ESM.TIS_CBO_CD_CBOS TIS_CBO_CD_CBOS,
                   COUNT(AGD.AGE_AGD_CD_INTAMB) TOTAL_AGEND
              FROM TB_AGE_AGD_AGENDA            AGD,
                   TB_AGE_ESM_ESCALA_MEDICA     ESM,
                   TB_CAD_UNI_UNIDADE           UNI,
                   TB_CAD_LAT_LOCAL_ATENDIMENTO LAT,
                   TB_TIS_CBO_CBOS              CBO
             WHERE (AGD.AGE_AGD_DT_ATENDIMENTO BETWEEN PATD_DT_INICIO AND PATD_DT_FIM)
               AND ESM.AGE_ESM_ID = AGD.AGE_ESM_ID
               AND ESM.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
               AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO
               AND ESM.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
               AND (PCAD_UNI_ID_UNIDADE IS NULL OR ESM.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
               AND (ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
               AND (PTIS_CBO_CD_CBOS IS NULL OR ESM.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
             GROUP BY ESM.CAD_UNI_ID_UNIDADE,
                      ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                      ESM.TIS_CBO_CD_CBOS)                            AGENDADOS,
           ------------------
           (SELECT ATD.CAD_UNI_ID_UNIDADE,
                   ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                   ATD.TIS_CBO_CD_CBOS,
                   COUNT(ATD.ATD_ATE_ID) TOTAL_ATEND,
                   COUNT(ATD.CAD_UNI_ID_UNIDADE) OVER() TOTAL_UNIDADE,
                   ROUND((COUNT(ATD.ATD_ATE_ID) * 100) / COUNT(ATD.CAD_UNI_ID_UNIDADE) OVER(), 2) PERCENTUAL
              FROM TB_ATD_ATE_ATENDIMENTO ATD
             WHERE (ATD.ATD_ATE_DT_ATENDIMENTO BETWEEN PATD_DT_INICIO AND PATD_DT_FIM)
               AND ATD.ATD_ATE_FL_STATUS = 'A'
               AND (PCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
               AND (ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
               AND (PTIS_CBO_CD_CBOS IS NULL OR ATD.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
               AND ATD.TIS_TAT_CD_TPATENDIMENTO = 4
             GROUP BY ATD.CAD_UNI_ID_UNIDADE,
                      ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                      ATD.TIS_CBO_CD_CBOS)                            ATENDIDOS,
           ------------------
           (SELECT ATD.CAD_UNI_ID_UNIDADE,
                   COUNT(ATD.ATD_ATE_ID) TOTAL_UNIDADE
              FROM TB_ATD_ATE_ATENDIMENTO ATD
             WHERE (ATD.ATD_ATE_DT_ATENDIMENTO BETWEEN PATD_DT_INICIO AND PATD_DT_FIM)
               AND ATD.ATD_ATE_FL_STATUS = 'A'
               AND (PCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
               AND ATD.TIS_TAT_CD_TPATENDIMENTO = 4
               AND (ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
               AND (PTIS_CBO_CD_CBOS IS NULL OR ATD.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
             GROUP BY ATD.CAD_UNI_ID_UNIDADE)                         PCT,
           ------------------
           (SELECT ATD.CAD_UNI_ID_UNIDADE,
                   ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                   ATD.TIS_CBO_CD_CBOS,
                   COUNT(ATD.ATD_ATE_ID) TOTAL_RETORNO
              FROM TB_ATD_ATE_ATENDIMENTO ATD
             WHERE (ATD.ATD_ATE_DT_ATENDIMENTO BETWEEN PATD_DT_INICIO AND PATD_DT_FIM)
               AND ATD.ATD_ATE_FL_STATUS = 'A'
               AND ATD.ATD_ATE_FL_RETORNO_OK = 'S'
               AND (PCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
               AND (ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
               AND (PTIS_CBO_CD_CBOS IS NULL OR ATD.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
               AND ATD.TIS_TAT_CD_TPATENDIMENTO = 4
             GROUP BY ATD.CAD_UNI_ID_UNIDADE,
                      ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                      ATD.TIS_CBO_CD_CBOS)                            RETORNO,
           ------------------
           (SELECT ESM.CAD_UNI_ID_UNIDADE CAD_UNI_ID_UNIDADE,
                   ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO CAD_LAT_ID_LOCAL_ATENDIMENTO,
                   ESM.TIS_CBO_CD_CBOS TIS_CBO_CD_CBOS,
                   COUNT(AGG.AGE_AGG_HR_AGENDA) TOTAL_CAP
              FROM TB_AGE_AGG_AGENDA_GERADA AGG,
                   TB_AGE_ESM_ESCALA_MEDICA ESM
             WHERE AGG.AGE_AGG_DT_AGENDA BETWEEN PATD_DT_INICIO AND PATD_DT_FIM
               AND ESM.AGE_ESM_ID = AGG.AGE_ESM_ID
               AND (PCAD_UNI_ID_UNIDADE IS NULL OR ESM.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
               AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO
               AND AGG.AGE_AGG_TP_HORARIO != 3
               AND ESM.AGE_ESM_FL_SITUACAO = 'A'
               AND (PTIS_CBO_CD_CBOS IS NULL OR ESM.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
             GROUP BY ESM.CAD_UNI_ID_UNIDADE,
                      ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO,
                      ESM.TIS_CBO_CD_CBOS)                            CAPACIDADE,
           ------------------
           TB_ATD_ATE_ATENDIMENTO       ATD,
           TB_CAD_UNI_UNIDADE           UNI,
           TB_CAD_LAT_LOCAL_ATENDIMENTO LAT,
           TB_TIS_CBO_CBOS              CBO,
           TB_ASS_PAT_PACIEATEND        PAT,
           TB_CAD_PAC_PACIENTE          PAC,
           TB_CAD_CNV_CONVENIO          CNV
     WHERE (ATD.ATD_ATE_DT_ATENDIMENTO BETWEEN PATD_DT_INICIO AND PATD_DT_FIM)
       AND (PCAD_UNI_ID_UNIDADE IS NULL OR ATD.CAD_UNI_ID_UNIDADE = PCAD_UNI_ID_UNIDADE)
       AND (ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = PCAD_LAT_ID_LOCAL_ATENDIMENTO)
       AND (PTIS_CBO_CD_CBOS IS NULL OR ATD.TIS_CBO_CD_CBOS = PTIS_CBO_CD_CBOS)
       AND ATD.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
       AND ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO
       AND ATD.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
       AND PAT.ATD_ATE_ID = ATD.ATD_ATE_ID
       AND PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
       AND (pCAD_CGC_ID IS NULL OR CNV.CAD_CGC_ID = pCAD_CGC_ID)
       AND FALTAS.CAD_UNI_ID_UNIDADE(+) = ATD.CAD_UNI_ID_UNIDADE
       AND FALTAS.CAD_LAT_ID_LOCAL_ATENDIMENTO(+) = ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO
       AND FALTAS.TIS_CBO_CD_CBOS(+) = ATD.TIS_CBO_CD_CBOS
       AND ATENDIDOS.CAD_UNI_ID_UNIDADE(+) = ATD.CAD_UNI_ID_UNIDADE
       AND ATENDIDOS.CAD_LAT_ID_LOCAL_ATENDIMENTO(+) = ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO
       AND ATENDIDOS.TIS_CBO_CD_CBOS(+) = ATD.TIS_CBO_CD_CBOS
       AND PCT.CAD_UNI_ID_UNIDADE(+) = ATD.CAD_UNI_ID_UNIDADE
       AND AGENDADOS.CAD_UNI_ID_UNIDADE(+) = ATD.CAD_UNI_ID_UNIDADE
       AND AGENDADOS.CAD_LAT_ID_LOCAL_ATENDIMENTO(+) = ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO
       AND AGENDADOS.TIS_CBO_CD_CBOS(+) = ATD.TIS_CBO_CD_CBOS
       AND RETORNO.CAD_UNI_ID_UNIDADE(+) = ATD.CAD_UNI_ID_UNIDADE
       AND RETORNO.CAD_LAT_ID_LOCAL_ATENDIMENTO(+) = ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO
       AND RETORNO.TIS_CBO_CD_CBOS(+) = ATD.TIS_CBO_CD_CBOS
       AND CAPACIDADE.CAD_UNI_ID_UNIDADE(+) = ATD.CAD_UNI_ID_UNIDADE
       AND CAPACIDADE.CAD_LAT_ID_LOCAL_ATENDIMENTO(+) = ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO
       AND CAPACIDADE.TIS_CBO_CD_CBOS(+) = ATD.TIS_CBO_CD_CBOS
     GROUP BY (ATD.CAD_UNI_ID_UNIDADE,
               UNI.CAD_UNI_DS_UNIDADE,
               ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO,
               LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
               CBO.TIS_CBO_CD_CBOS,
               CBO.TIS_CBO_DS_CBOS_HAC,
               FALTAS.TOTAL_FALTA,
               ATENDIDOS.TOTAL_ATEND,
               PCT.TOTAL_UNIDADE,
               AGENDADOS.TOTAL_AGEND,
               RETORNO.TOTAL_RETORNO,
               CAPACIDADE.TOTAL_CAP)
    HAVING(TOTAL_FALTA > 0) OR (TOTAL_ATEND > 0) OR (TOTAL_AGEND > 0) OR (TOTAL_RETORNO > 0)
     ORDER BY ATENDIDOS.TOTAL_ATEND DESC;
  IO_CURSOR := V_CURSOR;
END PRC_ATE_REL_ESTAT_LOCAL_ESPEC;
