CREATE OR REPLACE PROCEDURE "PRC_COB_REL_10_CONF_INTERF"
(
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pDATA_EMISSAO_INI IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pDATA_EMISSAO_FIM IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pDATA_VENCIMENTO_INI IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
    pDATA_VENCIMENTO_FIM IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
    pDATA_PAGTO_INI  IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pDATA_PAGTO_FIM  IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,

    pCAD_BAN_ID IN TB_CAD_BAN_BANCO.CAD_BAN_ID%TYPE DEFAULT NULL,
    pASS_BCT_ID IN TB_COB_MGC_MOV_GUIA_COBRANCA.ASS_BCT_ID%TYPE DEFAULT NULL,
    pPENDETE_CONTABILIDADE   VARCHAR2 DEFAULT NULL,
    pENVIADO_CONTABILIDADE   VARCHAR2 DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_ACS IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
     pDATA_CONTAB_INI     IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_LIBERACAO_CONTAB%TYPE DEFAULT NULL,
    pDATA_CONTAB_FIM     IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_LIBERACAO_CONTAB%TYPE DEFAULT NULL,
    pDATA_MOVIMENTO_FIM  IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pFAT_NOF_NR_NOTAFISCAL   IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_NR_NOTAFISCAL%TYPE DEFAULT NULL,
    pFAT_NOF_TP_SERIEFISCAL  IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_TP_SERIEFISCAL%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/*****************************************************************************
*    Procedure: PRC_COB_REL_10_CONF_INTERF
*
*    Data Criacao:   29/10/2012    Por: PEDRO
*    Data Alteracao:
*
*    Funcao: Lista NOTAS CONFERENCIA INTERFACE FAT COB
*******************************************************************************/
v_cursor PKG_CURSOR.t_cursor;

begin
  OPEN v_cursor FOR

SELECT CNV.CAD_CNV_CD_HAC_PRESTADOR,
       NOF.FAT_NOF_ID ,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_NR_NOTAFISCAL ,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.CAD_UNI_ID_UNIDADE ,
       NOF.FAT_NFO_VL_FATURADO  ,
       UNI.CAD_UNI_DS_UNIDADE,
       SUM( nvl(COB.COB_CCP_VL_TOT_CONTA,0) ) VALGUIA,
       NOF.FAT_NFO_VL_FATURADO -  SUM( nvl(COB.COB_CCP_VL_TOT_CONTA,0) ) DIFERENCA
FROM  TB_FAT_NOF_NOTA_FISCAL     NOF,
      TB_CAD_CNV_CONVENIO        CNV,
      TB_COB_CCP_CONTA_CONS_PARC COB,
      TB_CAD_UNI_UNIDADE         UNI
WHERE NOF.FAT_NOF_FL_STATUS      = 'A'
AND   NOF.FAT_NOF_ANO_FAT        >= 2011
AND   NOF.CAD_CNV_ID_CONVENIO    = CNV.CAD_CNV_ID_CONVENIO
AND   CNV.CAD_CNV_CD_OPCAO_PAGTO = 1
AND   NOF.FAT_NOF_ID             = COB.FAT_NOF_ID (+)
AND   NOF.CAD_UNI_ID_UNIDADE     = UNI.CAD_UNI_ID_UNIDADE
AND   NOF.FAT_NFO_DT_EMISSAO >= pDATA_EMISSAO_INI
AND   NOF.FAT_NFO_DT_EMISSAO <= pDATA_EMISSAO_FIM
AND   (pCAD_CNV_ID_CONVENIO IS NULL OR NOF.CAD_CNV_ID_CONVENIO    = pCAD_CNV_ID_CONVENIO)
GROUP BY CNV.CAD_CNV_CD_HAC_PRESTADOR,
       NOF.FAT_NOF_ID ,
       NOF.FAT_NFO_DT_EMISSAO,
       NOF.FAT_NFO_DT_VENCIMENTO,
       NOF.FAT_NOF_NR_NOTAFISCAL ,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.CAD_UNI_ID_UNIDADE ,
       NOF.FAT_NFO_VL_FATURADO  ,
       NOF.FAT_NFO_VL_FATURADO,
       UNI.CAD_UNI_DS_UNIDADE
--HAVING  NOF.FAT_NFO_VL_FATURADO -  SUM( nvl(COB.COB_CCP_VL_TOT_CONTA,0) ) > 0
--order by 4, 3
 ;

     io_cursor := v_cursor;
end PRC_COB_REL_10_CONF_INTERF;
