CREATE OR REPLACE PROCEDURE PRC_ATS_APE_ATEN_S_VALORES
(
     pATS_ATE_CD_INTLIB IN TB_ATS_APE_ATEN_PROCED_ECOCAR.ATS_ATE_CD_INTLIB%type,
     pATS_ATE_IN_INTLIB IN TB_ATS_APE_ATEN_PROCED_ECOCAR.ATS_ATE_IN_INTLIB%type,
     pAUX_EPP_CDESPECPROC IN TB_ATS_APE_ATEN_PROCED_ECOCAR.AUX_EPP_CDESPECPROC%type,
     pATS_ATE_ID IN TB_ATS_APE_ATEN_PROCED_ECOCAR.ATS_ATE_ID%type,
     pCAD_PRD_ID IN TB_ATS_APE_ATEN_PROCED_ECOCAR.CAD_PRD_ID%type,
     pTIS_MED_CD_TABELAMEDICA IN TB_ATS_APS_ATEN_PROC_SEGMENTO.TIS_MED_CD_TABELAMEDICA%type	,
     io_cursor OUT PKG_CURSOR.t_cursor
)
IS
  v_cursor PKG_CURSOR.t_cursor;
BEGIN

OPEN v_cursor FOR
SELECT
APE.ATS_UME_CD_ECOCAR,
FNC_RETORNA_ECO_INI(APE.ATS_UME_CD_ECOCAR, APE.ATS_UME_TP_UNID_MEDIDA, APE.ATS_UME_CD_UNID_MEDIDA) AS INICIO,
FNC_RETORNA_ECO_FIM(APE.ATS_UME_CD_ECOCAR, APE.ATS_UME_TP_UNID_MEDIDA, APE.ATS_UME_CD_UNID_MEDIDA) AS FIM
FROM TB_ATS_APE_ATEN_PROCED_ECOCAR APE
 WHERE
     APE.ATS_ATE_CD_INTLIB = pATS_ATE_CD_INTLIB
 AND APE.ATS_ATE_IN_INTLIB = pATS_ATE_IN_INTLIB
 AND APE.AUX_EPP_CDESPECPROC = pAUX_EPP_CDESPECPROC
 AND APE.ATS_ATE_ID = pATS_ATE_ID
 AND APE.CAD_PRD_ID = pCAD_PRD_ID
 AND APE.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA;

 io_cursor := v_cursor;

END PRC_ATS_APE_ATEN_S_VALORES;
/
