CREATE OR REPLACE PROCEDURE "PRC_ATS_REL_ATENDIMENTO_SADT"(pCAD_PRD_ID                   IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRD_ID%type DEFAULT NULL,
                                                               pCAD_UNI_ID_UNIDADE           in TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
                                                               pCAD_LAT_ID_LOCAL_ATENDIMENTO in TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type default null,
                                                               pCAD_SET_ID                   IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_SET_ID_ATEN%type DEFAULT NULL,
                                                               pAUX_EPP_CD_ESPECPROC         IN TB_ATS_ATE_ATENDIMENTO_SADT.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
                                                               pCAD_PRO_ID_PROF_EXECUTANTE   IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRO_ID_PROF_EXECUTANTE%type DEFAULT NULL,
                                                               pDT_INI_CONSULTA              IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DT_REALIZ_PROCED%type DEFAULT NULL,
                                                               pDT_FIM_CONSULTA              IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DT_REALIZ_PROCED%type DEFAULT NULL,
                                                               pHR_INI_CONSULTA              IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_HR_REALIZ_PROCED%type DEFAULT NULL,
                                                               pHR_FIM_CONSULTA              IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_HR_REALIZ_PROCED%type DEFAULT NULL,
                                                               pATS_ATE_IN_INTLIB            IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_IN_INTLIB%TYPE DEFAULT NULL,
                                                               pCAD_PLA_CD_TIPOPLANO         IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
                                                               pALTA                         NUMBER DEFAULT NULL,
                                                               pORDERBY                      NUMBER DEFAULT NULL,
                                                               pATS_ATE_FL_REPETICAO         IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_REPETICAO%type DEFAULT NULL,
                                                               pCAD_UNI_ID_UNIDADE_ENTREGA   in TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
                                                               pFLAGDATAREALIZACAOENTREGA    IN STRING DEFAULT NULL,
                                                               pFLAGSOMENTE_INT              varchar2 DEFAULT NULL,                                                               
                                                               io_cursor                     OUT PKG_CURSOR.t_cursor
                                                              --  , TESTE OUT LONG
                                                               ) is
  /********************************************************************
   *    Procedure: PRC_ATS_REL_ATENDIMENTO_SADT
   *
  *
   *    Funcao: Alimenta o Relatorio de Atendimentos SADT
   *******************************************************************/
  v_cursor  PKG_CURSOR.t_cursor;
  V_WHERE   varchar2(3000);

  V_ORDERBY varchar2(1000);
  V_SELECT  varchar2(28000);
begin
  V_WHERE   := NULL;
  V_ORDERBY := NULL;

  IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND UNI.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE;
  END IF;

  IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO;
  END IF;

  IF pCAD_PRD_ID IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ATS.CAD_PRD_ID = ' || pCAD_PRD_ID;
  END IF;

  IF pCAD_SET_ID IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ATS.CAD_SET_ID_ATEN = ' || pCAD_SET_ID;
  END IF;

  IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND EPP.AUX_EPP_CD_ESPECPROC = ' || CHR(39) || pAUX_EPP_CD_ESPECPROC || CHR(39);
  END IF;

  IF pCAD_PRO_ID_PROF_EXECUTANTE IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ATS.CAD_PRO_ID_PROF_EXECUTANTE = ' || pCAD_PRO_ID_PROF_EXECUTANTE;
  END IF;

  IF pCAD_PLA_CD_TIPOPLANO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND PLA.CAD_PLA_CD_TIPOPLANO = ' || CHR(39) || pCAD_PLA_CD_TIPOPLANO || CHR(39);
  END IF;

  IF pATS_ATE_IN_INTLIB IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' || CHR(39) || pATS_ATE_IN_INTLIB || CHR(39);
  END IF;

  IF pATS_ATE_FL_REPETICAO IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_FL_REPETICAO = ' || CHR(39) || pATS_ATE_FL_REPETICAO || CHR(39);
  END IF;

  IF pCAD_UNI_ID_UNIDADE_ENTREGA IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ARP.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE_ENTREGA;
  END IF;




  IF pFLAGDATAREALIZACAOENTREGA = 'R' THEN
    IF (((pHR_INI_CONSULTA IS NULL) AND (pHR_FIM_CONSULTA IS NULL)) OR (pHR_INI_CONSULTA < pHR_FIM_CONSULTA)) THEN
      IF pDT_INI_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND TRUNC(ATS.ATS_ATE_DT_REALIZ_PROCED) >= ' || CHR(39) || pDT_INI_CONSULTA || CHR(39);
      END IF;
      IF pDT_FIM_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND TRUNC(ATS.ATS_ATE_DT_REALIZ_PROCED) <= ' || CHR(39) || pDT_FIM_CONSULTA || CHR(39);
      END IF;
      IF pHR_INI_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_HR_REALIZ_PROCED >= ' || pHR_INI_CONSULTA;
      END IF;
      IF pHR_FIM_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_HR_REALIZ_PROCED <= ' || pHR_FIM_CONSULTA;
      END IF;
    END IF;

    IF ((pHR_INI_CONSULTA IS NOT NULL) AND (pHR_FIM_CONSULTA IS NOT NULL)) AND (pHR_INI_CONSULTA > pHR_FIM_CONSULTA) THEN
      IF pDT_INI_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND FNC_JUNTAR_DATA_HORA(ATS.ATS_ATE_DT_REALIZ_PROCED, ATS.ATS_ATE_HR_REALIZ_PROCED) >= ' || CHR(39) || FNC_JUNTAR_DATA_HORA(pDT_INI_CONSULTA, pHR_INI_CONSULTA) || CHR(39);
      END IF;
      IF pDT_FIM_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND FNC_JUNTAR_DATA_HORA(ATS.ATS_ATE_DT_REALIZ_PROCED, ATS.ATS_ATE_HR_REALIZ_PROCED) <= ' || CHR(39) || FNC_JUNTAR_DATA_HORA(pDT_FIM_CONSULTA, pHR_FIM_CONSULTA) || CHR(39);
      END IF;
    END IF;
  END IF;

  IF pFLAGDATAREALIZACAOENTREGA = 'E' THEN
      IF pDT_INI_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND TRUNC(ARP.ATS_ARP_DT_RESULTADO) >= ' || CHR(39) || pDT_INI_CONSULTA || CHR(39);
      END IF;
      IF pDT_FIM_CONSULTA IS NOT NULL THEN
        V_WHERE := V_WHERE || ' AND TRUNC(ARP.ATS_ARP_DT_RESULTADO) <= ' || CHR(39) || pDT_FIM_CONSULTA || CHR(39);
      END IF;
  END IF;



 IF pFLAGSOMENTE_INT IS NOT NULL THEN
    V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' || CHR(39) || 'I' || CHR(39) || ' and AIC.ATD_ATE_ID IS NOT NULL ';
  END IF;



  IF pALTA IS NOT NULL THEN
    IF pALTA = '0' THEN
      V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' || CHR(39) || 'I' || CHR(39) || ' AND AIC.ATD_AIC_TP_SITUACAO_PAC = ' || CHR(39) || 'I' || CHR(39);
    END IF;
    IF pALTA = '1' THEN
      V_WHERE := V_WHERE || ' AND ATS.ATS_ATE_IN_INTLIB = ' || CHR(39) || 'I' || CHR(39) || ' AND AIC.ATD_AIC_TP_SITUACAO_PAC = ' || CHR(39) || 'A' || CHR(39);
    END IF;
  END IF;

  IF pORDERBY IS NULL OR pORDERBY = '0' THEN
    V_ORDERBY := V_ORDERBY || ' ATS.ATS_ATE_DT_REALIZ_PROCED,EPP.AUX_EPP_DS_DESCRICAO,ATS.ATS_ATE_ID ';
  END IF;

  IF pORDERBY = '1' THEN
    V_ORDERBY := V_ORDERBY || ' ATS.ATS_ATE_DT_REALIZ_PROCED,EPP.AUX_EPP_DS_DESCRICAO,PES_PAC.CAD_PES_NM_PESSOA ';
  END IF;


  
  V_SELECT := '
 SELECT 
        ATS.ATS_ATE_DT_REALIZ_PROCED,
        ATS.ATS_ATE_HR_REALIZ_PROCED,
        ATS.ATS_ATE_CD_INTLIB,
        ATS.ATS_ATE_IN_INTLIB,
        ATS.ATS_ATE_ID,
        PRD.CAD_PRD_DS_DESCRICAO,
        EPP.AUX_EPP_DS_DESCRICAO,
        SETOR_PROCED.CAD_SET_DS_SETOR SETOR,
        SETOR_EXEC.CAD_SET_DS_SETOR SETOR_EXEC,
        ATS.ATS_ATE_FL_STATUS,
        DECODE(PLA.CAD_PLA_CD_TIPOPLANO, ''FU'', ''FUNCIONARIO'',
                                         ''PA'', ''PA'',
                                         ''GB'', ''GLOBAL'',
                                         ''PL'', ''PESSOA FISICA'',
                                         ''SP'', ''SERVICOS PRESTADOS'',
                                         ''TODOS'') tipo_empresa,
        PES_PAC.CAD_PES_NM_PESSOA NM_PACIENTE,
        PES_PAC.CAD_PES_DT_NASCIMENTO,
        PRO.CAD_PRO_NM_NOME NM_PROFISSIONAL,
     --   GUIA.ATE_GUI_CD_CODIGO,
        CNV.CAD_CNV_CD_HAC_PRESTADOR,
        CNV.CAD_CNV_NM_FANTASIA,
        PLA.CAD_PLA_CD_PLANO_HAC,
        PAC.CAD_PAC_NR_PRONTUARIO,
        AGS.AGS_AGE_DT_AGENDAMENTO,
        AGS.AGS_AGE_HR_AGENDAMENTO,
        ATS.ATS_ATE_FL_REPETICAO,
        MIN(AGS.AGS_AGE_HR_ATENDIMENTO) AGS_AGE_HR_ATENDIMENTO,
        APL.ATS_APL_ID,
        UNI_E.CAD_UNI_DS_UNIDADE CAD_UNI_DS_UNIDADE_E,
        UNI_E.CAD_UNI_DS_RESUMIDA CAD_UNI_DS_RESUMIDA_E,
        ATS.ATS_INCIDENCIAS,
        ATS.ATS_NUM_CONTROLE
   FROM TB_ATS_ATE_ATENDIMENTO_SADT ATS
   LEFT JOIN TB_ATS_APL_ATEN_PROCED_LAUDO APL   ON APL.ATS_ATE_CD_INTLIB = ATS.ATS_ATE_CD_INTLIB
        AND APL.ATS_ATE_ID = ATS.ATS_ATE_ID
        AND APL.CAD_PRD_ID = ATS.CAD_PRD_ID
        AND APL.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA
        AND APL.AUX_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC
        AND APL.ATS_ATE_IN_INTLIB = ATS.ATS_ATE_IN_INTLIB
    JOIN TB_ATS_ARP_ATEN_RESULT_PROCED ARP   ON ARP.ATS_ATE_CD_INTLIB = ATS.ATS_ATE_CD_INTLIB
        AND ARP.ATS_ATE_ID = ATS.ATS_ATE_ID
        AND ARP.CAD_PRD_ID = ATS.CAD_PRD_ID
        AND ARP.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA
        AND ARP.ATS_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC
        AND ARP.ATS_ATE_IN_INTLIB = ATS.ATS_ATE_IN_INTLIB
   LEFT JOIN TB_AGS_AGE_AGENDA_SADT AGS         ON AGS.LIB_PRD_ID = ATS.ATS_ATE_CD_INTLIB AND AGS.CAD_PRD_ID = ATS.CAD_PRD_ID  AND TRUNC(AGS.AGS_AGE_DT_ATENDIMENTO) = TRUNC(ATS.ATS_ATE_DT_REALIZ_PROCED) AND AGS.AGS_AGE_FL_STATUS != ''C''
   LEFT JOIN TB_CAD_SET_SETOR SETOR_EXEC        ON SETOR_EXEC.CAD_SET_ID = ATS.CAD_SET_ID_ATEN
   LEFT JOIN TB_CAD_SET_SETOR SETOR_PROCED      ON SETOR_PROCED.CAD_SET_ID = ATS.CAD_SET_ID
   LEFT JOIN TB_CAD_UNI_UNIDADE UNI             ON UNI.CAD_UNI_ID_UNIDADE = SETOR_EXEC.CAD_UNI_ID_UNIDADE
   LEFT JOIN TB_CAD_UNI_UNIDADE UNI_E           ON UNI_E.CAD_UNI_ID_UNIDADE = ARP.CAD_UNI_ID_UNIDADE
   LEFT JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT   ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR_EXEC.CAD_LAT_ID_LOCAL_ATENDIMENTO
   JOIN TB_CAD_PRD_PRODUTO PRD                  ON PRD.CAD_PRD_ID = ATS.CAD_PRD_ID
   JOIN TB_AUX_EPP_ESPECPROC EPP                ON EPP.AUX_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC AND EPP.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA
   JOIN TB_CAD_PAC_PACIENTE PAC                 ON PAC.CAD_PAC_ID_PACIENTE = ATS.CAD_PAC_ID_PACIENTE_INT
   JOIN TB_CAD_PES_PESSOA PES_PAC               ON PES_PAC.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
   LEFT JOIN TB_CAD_PRO_PROFISSIONAL PRO        ON PRO.CAD_PRO_ID_PROFISSIONAL = APL.CAD_PRO_ID_PROF
   LEFT JOIN TB_ATD_AIC_ATE_INT_COMPL AIC       ON AIC.ATD_ATE_ID = ATS.ATS_ATE_CD_INTLIB
   JOIN TB_CAD_PLA_PLANO PLA                    ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO
   JOIN TB_CAD_CNV_CONVENIO CNV                 ON CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
 --  LEFT JOIN TB_ASS_PPG_PAC_ATE_PROC_GUIA GUIA  ON GUIA.ATD_ATE_ID = ATS.ATS_ATE_CD_INTLIB
    WHERE
    (ATS.ATS_ATE_FL_STATUS <> ''C'')
    
    ' || V_WHERE || 
    
    ' GROUP BY ATS.ATS_ATE_DT_REALIZ_PROCED,
        ATS.ATS_ATE_HR_REALIZ_PROCED,
        ATS.ATS_ATE_CD_INTLIB,
        ATS.ATS_ATE_IN_INTLIB,
        ATS.ATS_ATE_ID,
        PRD.CAD_PRD_DS_DESCRICAO,
        EPP.AUX_EPP_DS_DESCRICAO,
        SETOR_PROCED.CAD_SET_DS_SETOR ,
        SETOR_EXEC.CAD_SET_DS_SETOR ,
        ATS.ATS_ATE_FL_STATUS,
        DECODE(PLA.CAD_PLA_CD_TIPOPLANO, ''FU'', ''FUNCIONARIO'',
                                         ''PA'', ''PA'',
                                         ''GB'', ''GLOBAL'',
                                         ''PL'', ''PESSOA FISICA'',
                                         ''SP'', ''SERVICOS PRESTADOS'',
                                         ''TODOS'') ,
        PES_PAC.CAD_PES_NM_PESSOA ,
        PES_PAC.CAD_PES_DT_NASCIMENTO,
        PRO.CAD_PRO_NM_NOME ,
       -- GUIA.ATE_GUI_CD_CODIGO,
        CNV.CAD_CNV_CD_HAC_PRESTADOR,
                CNV.CAD_CNV_NM_FANTASIA,
        PLA.CAD_PLA_CD_PLANO_HAC,
        PAC.CAD_PAC_NR_PRONTUARIO,
        AGS.AGS_AGE_DT_AGENDAMENTO,
        AGS.AGS_AGE_HR_AGENDAMENTO,
        ATS.ATS_ATE_FL_REPETICAO,
        APL.ATS_APL_ID,
        UNI_E.CAD_UNI_DS_UNIDADE ,
        UNI_E.CAD_UNI_DS_RESUMIDA ,
        ATS.ATS_INCIDENCIAS,
        ATS.ATS_NUM_CONTROLE
     ORDER BY ' || V_ORDERBY;
  -- ORDER BY 1,7,5
  --  TESTE :=  V_SELECT ;
  OPEN v_cursor FOR
   V_SELECT;
  -- SELECT 1 FROM DUAL;
  io_cursor := v_cursor;
END PRC_ATS_REL_ATENDIMENTO_SADT;
