CREATE OR REPLACE PROCEDURE PRC_FAT_MCC_CCI_RESUMO
(
  pATD_ATE_ID IN TB_FAT_MCC_MOV_COM_CONSUMO.ATD_ATE_ID%TYPE,
  IO_CURSOR   OUT PKG_CURSOR.T_CURSOR) IS
  /********************************************************************
  *    Procedure: PRC_FAT_MCC_CCI_RESUMO
  * 
  *    Data Criacao: 03/02/2010      Por: Marcus Relva
  *
  *    Data Alteracao: 19/04/2010    por: Pedro
  *    Alteracao: não retornava registros para Pronto Socorro, Amb.
  *
  *    Data Alteracao: 08/07/2010    Por: Fabiola
  *    Alteracao: inclui quantidade, valor calculado e valor faturado e somar os ativos
  *    
  *    Funcao: Tela Faturamento - Resumo de Atendimento
  *
  *******************************************************************/
  V_CURSOR PKG_CURSOR.T_CURSOR;

BEGIN

  OPEN V_CURSOR FOR
   
    /*CONVENIOS*/
    SELECT PAT.ATD_ATE_ID,
           PES.CAD_PES_NM_PESSOA,
           MIN(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_INICIO_CONSUMO,
                                    CCI.FAT_CCI_HR_INICIO_CONSUMO)) AS FAT_CCI_DT_INICIO_CONSUMO,
           MAX(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_FIM_CONSUMO,
                                    CCI.FAT_CCI_HR_FIM_CONSUMO)) AS FAT_CCI_DT_FIM_CONSUMO,
           CCI.FAT_CCI_TP_DESTINO_ITEM,
           TAP.CAD_TAP_DS_ATRIBUTO,
           PLA.CAD_PLA_CD_PLANO_HAC,
           PLA.CAD_PLA_NM_NOME_PLANO,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           CNV.CAD_CNV_NM_FANTASIA,
           COUNT(CCI.FAT_CCI_ID) AS QUANTIDADE,
           SUM(CCI.FAT_CCI_VL_FATURADO) AS FAT_CCI_VL_FATURADO,
           SUM(CCI.FAT_CCI_VL_CALCULADO) AS FAT_CCI_VL_CALCULADO
      FROM TB_FAT_MCC_MOV_COM_CONSUMO  MCC,
           TB_ASS_PAT_PACIEATEND       PAT,
           TB_FAT_CCI_CONTA_CONSU_ITEM CCI,
           TB_CAD_PAC_PACIENTE         PAC,
           TB_CAD_PES_PESSOA           PES,
           TB_CAD_CNV_CONVENIO         CNV,
           TB_CAD_PLA_PLANO            PLA,
           TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
           TB_ATD_ATE_ATENDIMENTO      ATD
     WHERE PAT.ATD_ATE_ID = pATD_ATE_ID
       AND CCI.FAT_CCI_TP_DESTINO_ITEM = 'C'
       AND PAT.ATD_ATE_ID = MCC.ATD_ATE_ID
       AND CCI.FAT_MCC_ID = MCC.FAT_MCC_ID
       AND PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
       AND PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
       AND PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
       AND CCI.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
       AND ATD.ATD_ATE_ID = PAT.ATD_ATE_ID
       AND ATD.ATD_ATE_TP_PACIENTE IN ('I', 'E')
       AND CCI.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND CCI.FAT_CCI_FL_STATUS = 'A'
     GROUP BY PAT.ATD_ATE_ID,
              PES.CAD_PES_NM_PESSOA,
              CCI.FAT_CCI_TP_DESTINO_ITEM,
              PLA.CAD_PLA_CD_PLANO_HAC,
              PLA.CAD_PLA_NM_NOME_PLANO,
              CNV.CAD_CNV_CD_HAC_PRESTADOR,
              CNV.CAD_CNV_NM_FANTASIA,
              TAP.CAD_TAP_DS_ATRIBUTO

    UNION
    
    /*PARTICULAR E HOSPITAL*/
    SELECT PAT.ATD_ATE_ID,
           PES.CAD_PES_NM_PESSOA,
           MIN(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_INICIO_CONSUMO,
                                    CCI.FAT_CCI_HR_INICIO_CONSUMO)) AS FAT_CCI_DT_INICIO_CONSUMO,
           MAX(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_FIM_CONSUMO,
                                    CCI.FAT_CCI_HR_FIM_CONSUMO)) AS FAT_CCI_DT_FIM_CONSUMO,
           CCI.FAT_CCI_TP_DESTINO_ITEM,
           TAP.CAD_TAP_DS_ATRIBUTO,
           NULL,
           NULL,
           NULL,
           NULL,
           COUNT(CCI.FAT_CCI_ID) AS QUANTIDADE,
           SUM(CCI.FAT_CCI_VL_FATURADO) AS FAT_CCI_VL_FATURADO,
           SUM(CCI.FAT_CCI_VL_CALCULADO) AS FAT_CCI_VL_CALCULADO
      FROM TB_FAT_MCC_MOV_COM_CONSUMO  MCC,
           TB_ASS_PAT_PACIEATEND       PAT,
           TB_FAT_CCI_CONTA_CONSU_ITEM CCI,
           TB_CAD_PAC_PACIENTE         PAC,
           TB_CAD_PES_PESSOA           PES,
           TB_CAD_CNV_CONVENIO         CNV,
           TB_CAD_PLA_PLANO            PLA,
           TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
           TB_ATD_ATE_ATENDIMENTO      ATD
     WHERE PAT.ATD_ATE_ID = pATD_ATE_ID
       AND CCI.FAT_CCI_TP_DESTINO_ITEM IN ('H', 'P')
       AND ATD.ATD_ATE_ID = PAT.ATD_ATE_ID
       AND ATD.ATD_ATE_TP_PACIENTE IN ('I', 'E')
       AND CCI.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND CCI.FAT_CCI_FL_STATUS = 'A'
       AND PAT.ATD_ATE_ID = MCC.ATD_ATE_ID
       AND CCI.FAT_MCC_ID = MCC.FAT_MCC_ID
       AND PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
       AND PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
       AND PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
       AND CCI.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
     GROUP BY PAT.ATD_ATE_ID,
              PES.CAD_PES_NM_PESSOA,
              CCI.FAT_CCI_TP_DESTINO_ITEM,
              TAP.CAD_TAP_DS_ATRIBUTO

    UNION

    SELECT PAT.ATD_ATE_ID,
           PES.CAD_PES_NM_PESSOA,
           MIN(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_INICIO_CONSUMO,
                                    CCI.FAT_CCI_HR_INICIO_CONSUMO)) AS FAT_CCI_DT_INICIO_CONSUMO,
           MAX(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_FIM_CONSUMO,
                                    CCI.FAT_CCI_HR_FIM_CONSUMO)) AS FAT_CCI_DT_FIM_CONSUMO,
           CCI.FAT_CCI_TP_DESTINO_ITEM,
           TAP.CAD_TAP_DS_ATRIBUTO,
           PLA.CAD_PLA_CD_PLANO_HAC,
           PLA.CAD_PLA_NM_NOME_PLANO,
           CNV.CAD_CNV_CD_HAC_PRESTADOR,
           CNV.CAD_CNV_NM_FANTASIA,
           COUNT(CCI.FAT_CCI_ID) AS QUANTIDADE,
           SUM(CCI.FAT_CCI_VL_FATURADO) AS FAT_CCI_VL_FATURADO,
           SUM(CCI.FAT_CCI_VL_CALCULADO) AS FAT_CCI_VL_CALCULADO
      FROM TB_FAT_MCC_MOV_COM_CONSUMO  MCC,
           TB_ASS_PAT_PACIEATEND       PAT,
           TB_FAT_CCI_CONTA_CONSU_ITEM CCI,
           TB_CAD_PAC_PACIENTE         PAC,
           TB_CAD_PES_PESSOA           PES,
           TB_CAD_CNV_CONVENIO         CNV,
           TB_CAD_PLA_PLANO            PLA,
           TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
           TB_ATD_ATE_ATENDIMENTO      ATD
     WHERE PAT.ATD_ATE_ID = pATD_ATE_ID
       AND CCI.FAT_CCI_TP_DESTINO_ITEM = 'C'
       AND PAT.ATD_ATE_ID = MCC.ATD_ATE_ID
       AND CCI.FAT_MCC_ID = MCC.FAT_MCC_ID
       AND PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
       AND PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
       AND PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
       AND CCI.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
       AND ATD.ATD_ATE_ID = PAT.ATD_ATE_ID
       AND ATD.ATD_ATE_TP_PACIENTE IN ('A', 'U')
       AND CCI.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND CCI.FAT_CCI_FL_STATUS = 'A'
     GROUP BY PAT.ATD_ATE_ID,
              PES.CAD_PES_NM_PESSOA,
              CCI.FAT_CCI_TP_DESTINO_ITEM,
              PLA.CAD_PLA_CD_PLANO_HAC,
              PLA.CAD_PLA_NM_NOME_PLANO,
              CNV.CAD_CNV_CD_HAC_PRESTADOR,
              CNV.CAD_CNV_NM_FANTASIA,
              TAP.CAD_TAP_DS_ATRIBUTO

    UNION

    /*PARTICULAR E HOSPITAL*/
    SELECT PAT.ATD_ATE_ID,
           PES.CAD_PES_NM_PESSOA,
           MIN(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_INICIO_CONSUMO,
                                    CCI.FAT_CCI_HR_INICIO_CONSUMO)) AS FAT_CCI_DT_INICIO_CONSUMO,
           MAX(FNC_JUNTAR_DATA_HORA(CCI.FAT_CCI_DT_FIM_CONSUMO,
                                    CCI.FAT_CCI_HR_FIM_CONSUMO)) AS FAT_CCI_DT_FIM_CONSUMO,
           CCI.FAT_CCI_TP_DESTINO_ITEM,
           TAP.CAD_TAP_DS_ATRIBUTO,
           NULL,
           NULL,
           NULL,
           NULL,
           COUNT(CCI.FAT_CCI_ID) AS QUANTIDADE,
           SUM(CCI.FAT_CCI_VL_FATURADO) AS FAT_CCI_VL_FATURADO,
           SUM(CCI.FAT_CCI_VL_CALCULADO) AS FAT_CCI_VL_CALCULADO
      FROM TB_FAT_MCC_MOV_COM_CONSUMO  MCC,
           TB_ASS_PAT_PACIEATEND       PAT,
           TB_FAT_CCI_CONTA_CONSU_ITEM CCI,
           TB_CAD_PAC_PACIENTE         PAC,
           TB_CAD_PES_PESSOA           PES,
           TB_CAD_CNV_CONVENIO         CNV,
           TB_CAD_PLA_PLANO            PLA,
           TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
           TB_ATD_ATE_ATENDIMENTO      ATD
     WHERE PAT.ATD_ATE_ID = pATD_ATE_ID
       AND CCI.FAT_CCI_TP_DESTINO_ITEM IN ('H', 'P')
       AND ATD.ATD_ATE_ID = PAT.ATD_ATE_ID
       AND ATD.ATD_ATE_TP_PACIENTE IN ('A', 'U')
       AND PAT.ATD_ATE_ID = MCC.ATD_ATE_ID
       AND CCI.FAT_MCC_ID = MCC.FAT_MCC_ID
       AND PAT.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND PAC.CAD_PES_ID_PESSOA = PES.CAD_PES_ID_PESSOA
       AND PAC.CAD_PLA_ID_PLANO = PLA.CAD_PLA_ID_PLANO
       AND PAC.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
       AND CCI.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
       AND CCI.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
       AND CCI.FAT_CCI_FL_STATUS = 'A'
     GROUP BY PAT.ATD_ATE_ID,
              PES.CAD_PES_NM_PESSOA,
              CCI.FAT_CCI_TP_DESTINO_ITEM,
              TAP.CAD_TAP_DS_ATRIBUTO;

  IO_CURSOR := V_CURSOR;

END PRC_FAT_MCC_CCI_RESUMO;
