CREATE OR REPLACE PROCEDURE "PRC_FAT_COC_UPD_PARC_VALOR_U"
(
    pATD_ATE_ID IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_ID%TYPE DEFAULT NULL,
    pCAD_PAC_ID_PACIENTE IN TB_CAD_PAC_PACIENTE.CAD_PAC_ID_PACIENTE%TYPE DEFAULT NULL,
    pFAT_CCP_ID IN TB_FAT_CCI_CONTA_CONSU_ITEM.FAT_CCP_ID%TYPE DEFAULT NULL,
    pFAT_COC_ID IN TB_FAT_CCI_CONTA_CONSU_ITEM.FAT_COC_ID%TYPE DEFAULT NULL
)
IS
/********************************************************************
*    Procedure: PRC_FAT_COC_UPD_PARC_VALOR_U
*    Data Criac?o: 04/08/2010  Por: Caio
*
*    Task 10119 - N?o somar os itens que compoem um pacote
*    Data Alterac?o: 06/08/2010  Por: Caio
*******************************************************************/
BEGIN
  UPDATE  TB_FAT_COC_CONTA_CONSUMO COC
  SET     (COC.FAT_COC_VL_TOTAL_ORIGINAL, COC.FAT_COC_VL_TOTAL_CONTA) =
            (SELECT   SUM(CCI.FAT_CCI_VL_CALCULADO) FAT_CCI_VL_PRODUTO,
                      SUM(CCI.FAT_CCI_VL_FATURADO) FAT_CCI_VL_FATURADO
            FROM      TB_FAT_CCI_CONTA_CONSU_ITEM CCI
            WHERE   CCI.ATD_ATE_ID = pATD_ATE_ID
						AND     CCI.FAT_CCI_TP_DESTINO_ITEM not in ('H','T')
            AND     CCI.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE
            AND     CCI.FAT_COC_ID = pFAT_COC_ID
            AND     CCI.FAT_CCI_FL_STATUS = 'A'
            --Task 10119
            AND     (CCI.FAT_CCI_FL_PACOTE IS NULL OR CCI.FAT_CCI_FL_PACOTE = 'N'))
  WHERE   COC.ATD_ATE_ID = pATD_ATE_ID
  AND     COC.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE
  AND     COC.FAT_COC_ID = pFAT_COC_ID;
  UPDATE  TB_FAT_CCP_CONTA_CONS_PARC CCP
  SET     (CCP.FAT_CCP_VL_TOT_ORIGINAL, CCP.FAT_CCP_VL_TOT_CONTA) =
            (SELECT   SUM(CCI.FAT_CCI_VL_CALCULADO) FAT_CCI_VL_PRODUTO,
                      SUM(CCI.FAT_CCI_VL_FATURADO) FAT_CCI_VL_FATURADO
            FROM      TB_FAT_CCI_CONTA_CONSU_ITEM CCI
            WHERE   CCI.ATD_ATE_ID = pATD_ATE_ID
            AND     CCI.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE
						AND     CCI.FAT_CCI_TP_DESTINO_ITEM not in ('H','T')
            AND     CCI.FAT_COC_ID = pFAT_COC_ID
            AND     CCI.FAT_CCP_ID = pFAT_CCP_ID
            AND     CCI.FAT_CCI_FL_STATUS = 'A'
            --Task 10119
            AND     (CCI.FAT_CCI_FL_PACOTE IS NULL OR CCI.FAT_CCI_FL_PACOTE = 'N'))
  WHERE   CCP.ATD_ATE_ID = pATD_ATE_ID
  AND     CCP.CAD_PAC_ID_PACIENTE = pCAD_PAC_ID_PACIENTE
  AND     CCP.FAT_COC_ID = pFAT_COC_ID
  AND     CCP.FAT_CCP_ID = pFAT_CCP_ID;
END PRC_FAT_COC_UPD_PARC_VALOR_U;
 