create or replace procedure PRC_FAT_COP_CONTROLE_PRONT_I
(
     pNewIdt OUT integer,
     --pFAT_COP_ID IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_COP_ID%type,
     pCAD_PAC_NR_PRONTUARIO IN TB_FAT_COP_CONTROLE_PRONTUARIO.CAD_PAC_NR_PRONTUARIO%type,
     pCAD_SET_ID IN TB_FAT_COP_CONTROLE_PRONTUARIO.CAD_SET_ID%type default NULL,
     pATD_ATE_ID IN TB_FAT_COP_CONTROLE_PRONTUARIO.ATD_ATE_ID%type,
     pFAT_COC_ID IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_COC_ID%type,
     pCAD_PAC_ID_PACIENTE IN TB_FAT_COP_CONTROLE_PRONTUARIO.CAD_PAC_ID_PACIENTE%type,
     pFAT_COP_DT_CHEGADA IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_COP_DT_CHEGADA%type,
     pFAT_COP_DT_LIBERACAO IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_COP_DT_LIBERACAO%type,
     pFAT_COP_FL_FALTA_GUIA IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_COP_FL_FALTA_GUIA%type default NULL,
     pFAT_COP_DT_ULTIMA_ATUALIZACAO IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_COP_DT_ULTIMA_ATUALIZACAO%type,
     pSEG_USU_ID_USUARIO IN TB_FAT_COP_CONTROLE_PRONTUARIO.SEG_USU_ID_USUARIO%type,
     pFAT_COP_DS_OBSERVACAO IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_COP_DS_OBSERVACAO%type default NULL,
     pATD_INA_DT_ALTA IN TB_FAT_COP_CONTROLE_PRONTUARIO.ATD_INA_DT_ALTA%type,
     pFAT_CCP_ID IN TB_FAT_COP_CONTROLE_PRONTUARIO.FAT_CCP_ID%type default NULL,
     pCAD_SET_ID_CHEGADA IN TB_FAT_COP_CONTROLE_PRONTUARIO.CAD_SET_ID_CHEGADA%type default NULL	
)
is
/********************************************************************
*    Procedure: PRC_FAT_COP_CONTROLE_PRONT_I
*
*    Data Criacao:  5/12/2012   Por: Andre
*
*    Funcao: Insere Registro de Controle de Prontuario
*******************************************************************/
     lIdtRetorno integer;
begin

SELECT MAX(FAT_COP_ID)+1 INTO lIdtRetorno FROM TB_FAT_COP_CONTROLE_PRONTUARIO;

INSERT INTO TB_FAT_COP_CONTROLE_PRONTUARIO
(
       FAT_COP_ID,
       CAD_PAC_NR_PRONTUARIO,
       CAD_SET_ID,
       ATD_ATE_ID,
       FAT_COC_ID,
       CAD_PAC_ID_PACIENTE,
       FAT_COP_DT_CHEGADA,
       FAT_COP_DT_LIBERACAO,
       FAT_COP_FL_FALTA_GUIA,
       FAT_COP_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       FAT_COP_DS_OBSERVACAO,
       ATD_INA_DT_ALTA,
       FAT_CCP_ID,
       CAD_SET_ID_CHEGADA
)
VALUES
(
      lIdtRetorno,
      pCAD_PAC_NR_PRONTUARIO,
      pCAD_SET_ID,
      pATD_ATE_ID,
      pFAT_COC_ID,
      pCAD_PAC_ID_PACIENTE,
      pFAT_COP_DT_CHEGADA,
      pFAT_COP_DT_LIBERACAO,
      pFAT_COP_FL_FALTA_GUIA,
      SYSDATE,
      pSEG_USU_ID_USUARIO,
      pFAT_COP_DS_OBSERVACAO,
      pATD_INA_DT_ALTA,
       pFAT_CCP_ID,
       pCAD_SET_ID_CHEGADA
);

pNewIdt := lIdtRetorno;

end PRC_FAT_COP_CONTROLE_PRONT_I;
 