CREATE OR REPLACE PROCEDURE "PRC_ATS_REL_ESTATISTICA"
  (

     pCAD_UNI_ID_UNIDADE in TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%type DEFAULT NULL,
     pCAD_SET_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_SET_ID%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_ATS_ATE_ATENDIMENTO_SADT.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pDT_INI_CONSULTA IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DT_REALIZ_PROCED%type DEFAULT NULL,
     pDT_FIM_CONSULTA IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DT_REALIZ_PROCED%type DEFAULT NULL,
     pATS_ATE_IN_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_IN_INTLIB%TYPE DEFAULT NULL,
     pCAD_PLA_CD_TIPOPLANO IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_CAD_LAT_LOCAL_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
     pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
     pCAD_PRO_ID_PROFISSIONAL IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,

     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ATS_REL_ESTATISTICA
  *
  *    Data Criacao:   26/03/2009   Por: Pedro H.A.C.
  *    Data Alteracao:	27/03/2010  Por: Pedro
  *    Alterac?o: JOIN ATS.TIS_MED_CD_TABELAMEDICA
  *
  *    Funcao: Alimenta o Relatorio de ESTATISTICA de Atendimentos SADT
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
   begin

OPEN v_cursor FOR
  select

       case when pla.cad_pla_cd_tipoplano in ('GB','PL') then 'GLOBAL + PSAC'
       WHEN PLA.CAD_PLA_CD_TIPOPLANO = 'FU' THEN 'FUNCIONARIO HAC'
       WHEN pla.cad_pla_cd_tipoplano = 'SP' THEN 'S.PRESTADO'
       ELSE 'PARTICULAR'
       END TIPOPLANO,
       EPP.AUX_EPP_DS_DESCRICAO,
       DECODE(ATS.ATS_ATE_IN_INTLIB,'I','INTERNADO','L','LIBERADO') ATS_ATE_IN_INTLIB,

     SUM( Count(ATS.ATS_ATE_DT_REALIZ_PROCED))
       OVER(PARTITION BY case when pla.cad_pla_cd_tipoplano in ('GB','PL') then 'GLOBAL + PSAC'
       WHEN PLA.CAD_PLA_CD_TIPOPLANO = 'FU' THEN 'FUNCIONARIO HAC'
       WHEN pla.cad_pla_cd_tipoplano = 'SP' THEN 'S.PRESTADO'
       ELSE 'PARTICULAR'
       END||ATS.ATS_ATE_IN_INTLIB) TOTAL_PERIODO,

       SUM( Count(ATS.ATS_ATE_CD_INTLIB))
       OVER() TOTAL_GERAL,


       Round((SUM( Count(ATS.ATS_ATE_DT_REALIZ_PROCED))
       OVER(PARTITION BY case when pla.cad_pla_cd_tipoplano in ('GB','PL') then 'GLOBAL + PSAC'
       WHEN PLA.CAD_PLA_CD_TIPOPLANO = 'FU' THEN 'FUNCIONARIO HAC'
       WHEN pla.cad_pla_cd_tipoplano = 'SP' THEN 'S.PRESTADO'
       ELSE 'PARTICULAR'
       END||ATS.ATS_ATE_IN_INTLIB) *100)/ SUM( Count(ATS.ATS_ATE_DT_REALIZ_PROCED))
       OVER(),2) PERCENTUAL

         FROM TB_ATS_ATE_ATENDIMENTO_SADT ATS

        LEFT JOIN TB_ATS_APL_ATEN_PROCED_LAUDO APL
       ON APL.ATS_ATE_ID = ATS.ATS_ATE_ID
       AND APL.ATS_ATE_CD_INTLIB = ATS.ATS_ATE_CD_INTLIB
       AND APL.ATS_ATE_IN_INTLIB = ATS.ATS_ATE_IN_INTLIB
       AND APL.AUX_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC
       AND APL.CAD_PRD_ID = ATS.CAD_PRD_ID
       AND APL.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA

       LEFT JOIN TB_CAD_SET_SETOR SETOR_EXEC ON SETOR_EXEC.CAD_SET_ID = ATS.CAD_SET_ID_ATEN

       LEFT JOIN TB_CAD_UNI_UNIDADE UNI ON UNI.CAD_UNI_ID_UNIDADE = SETOR_EXEC.CAD_UNI_ID_UNIDADE

       LEFT JOIN TB_CAD_LAT_LOCAL_ATENDIMENTO LAT ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR_EXEC.CAD_LAT_ID_LOCAL_ATENDIMENTO

       LEFT JOIN TB_AUX_EPP_ESPECPROC EPP
       ON EPP.AUX_EPP_CD_ESPECPROC = ATS.AUX_EPP_CD_ESPECPROC
       AND EPP.TIS_MED_CD_TABELAMEDICA = ATS.TIS_MED_CD_TABELAMEDICA

       LEFT JOIN TB_CAD_PAC_PACIENTE PAC ON PAC.CAD_PAC_ID_PACIENTE = ATS.CAD_PAC_ID_PACIENTE_INT

       LEFT JOIN TB_CAD_PLA_PLANO PLA ON PLA.CAD_PLA_ID_PLANO = PAC.CAD_PLA_ID_PLANO

  WHERE   ATS.ATS_ATE_DT_REALIZ_PROCED BETWEEN pDT_INI_CONSULTA AND pDT_FIM_CONSULTA
       AND (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
       AND (pCAD_UNI_ID_UNIDADE IS NULL OR UNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
       AND (pCAD_SET_ID IS NULL OR SETOR_EXEC.CAD_SET_ID = pCAD_SET_ID)
       AND (pAUX_EPP_CD_ESPECPROC IS NULL OR ATS.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC)
       AND (pCAD_PRD_ID IS NULL OR ATS.CAD_PRD_ID = pCAD_PRD_ID)
       AND (pCAD_PRO_ID_PROFISSIONAL IS NULL OR ATS.CAD_PRO_ID_PROF_EXECUTANTE = pCAD_PRO_ID_PROFISSIONAL)
       AND (pCAD_PLA_CD_TIPOPLANO IS NULL OR pla.CAD_PLA_CD_TIPOPLANO = pCAD_PLA_CD_TIPOPLANO)
       AND (ATS.ATS_ATE_FL_STATUS <> 'C')

          group by
          case when pla.cad_pla_cd_tipoplano in ('GB','PL') then 'GLOBAL + PSAC'
           WHEN PLA.CAD_PLA_CD_TIPOPLANO = 'FU' THEN 'FUNCIONARIO HAC'
            WHEN pla.cad_pla_cd_tipoplano = 'SP' THEN 'S.PRESTADO'
             ELSE 'PARTICULAR'
              END
              ,

                EPP.AUX_EPP_DS_DESCRICAO,
                ATS.ATS_ATE_IN_INTLIB
                ;

     io_cursor := v_cursor;
  end PRC_ATS_REL_ESTATISTICA;


