create or replace procedure PRC_FAT_KMM_KIT_MAT_MED_S
  (
     pFAT_KMM_ID IN TB_FAT_KMM_KIT_MAT_MED.FAT_KMM_ID%type DEFAULT NULL,
     pCAD_PRD_ID_KIT IN TB_FAT_KMM_KIT_MAT_MED.CAD_PRD_ID_KIT%type DEFAULT NULL,
     pFAT_KMM_DT_INI_VIGENCIA IN TB_FAT_KMM_KIT_MAT_MED.FAT_KMM_DT_INI_VIGENCIA%type DEFAULT NULL,
     pFAT_KMM_DT_FIM_VIGENCIA IN TB_FAT_KMM_KIT_MAT_MED.FAT_KMM_DT_FIM_VIGENCIA%type DEFAULT NULL,
     pFAT_KMM_FL_STATUS IN TB_FAT_KMM_KIT_MAT_MED.FAT_KMM_FL_STATUS%type DEFAULT NULL,
     pCAD_PRD_ID_ITEM IN TB_FAT_KMM_KIT_MAT_MED.CAD_PRD_ID_ITEM%type DEFAULT NULL,
     pFAT_KMM_QT_ITEM IN TB_FAT_KMM_KIT_MAT_MED.FAT_KMM_QT_ITEM%type DEFAULT NULL,
     pFAT_KMM_DT_ULTIMA_ATUALIZACAO IN TB_FAT_KMM_KIT_MAT_MED.FAT_KMM_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_FAT_KMM_KIT_MAT_MED.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_FAT_KMM_KIT_MAT_MED_S
  *
  *    Data Criacao: 	14/01/2010   Por: André Souza Monaco
  *    Data Alteracao:	--  Por: --
  *
  *    Funcao: Seleção de registros de acordo com os parâmetros
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT
       KIT.FAT_KMM_ID,
       KIT.CAD_PRD_ID_KIT,
       KIT.FAT_KMM_DT_INI_VIGENCIA,
       KIT.FAT_KMM_DT_FIM_VIGENCIA,
       KIT.FAT_KMM_FL_STATUS,
       KIT.CAD_PRD_ID_ITEM,
       KIT.FAT_KMM_QT_ITEM,
       KIT.FAT_KMM_DT_ULTIMA_ATUALIZACAO,
       KIT.SEG_USU_ID_USUARIO,
       DECODE (FAT_KMM_FL_STATUS, 'A', 'ATIVO', 'INATIVO') STATUS,
       PRODUTO_ITEM.CAD_PRD_DS_DESCRICAO ITEM_DESCRICAO,
       PRODUTO_ITEM.CAD_CMM_CD_CARACMATMED,
       TABELA.TIS_MED_CD_TABELAMEDICA CD_TABELAMEDICA,
       TABELA.TIS_MED_DS_TABELAMEDICA DS_TABELAMEDICA       
    FROM TB_FAT_KMM_KIT_MAT_MED KIT,
         TB_CAD_PRD_PRODUTO PRODUTO_ITEM,
         TB_TIS_MED_TABELAMEDICA TABELA
    WHERE
         KIT.CAD_PRD_ID_ITEM = PRODUTO_ITEM.CAD_PRD_ID AND
         PRODUTO_ITEM.TIS_MED_CD_TABELAMEDICA = TABELA.TIS_MED_CD_TABELAMEDICA AND
        (pFAT_KMM_ID is null OR KIT.FAT_KMM_ID = pFAT_KMM_ID) AND
        (pCAD_PRD_ID_KIT is null OR KIT.CAD_PRD_ID_KIT = pCAD_PRD_ID_KIT) AND
        (pFAT_KMM_DT_INI_VIGENCIA is null OR KIT.FAT_KMM_DT_INI_VIGENCIA = pFAT_KMM_DT_INI_VIGENCIA) AND
        (pFAT_KMM_DT_FIM_VIGENCIA is null OR KIT.FAT_KMM_DT_FIM_VIGENCIA = pFAT_KMM_DT_FIM_VIGENCIA) AND
        (pFAT_KMM_FL_STATUS is null OR KIT.FAT_KMM_FL_STATUS = pFAT_KMM_FL_STATUS) AND
        (pCAD_PRD_ID_ITEM is null OR KIT.CAD_PRD_ID_ITEM = pCAD_PRD_ID_ITEM) AND
        (pFAT_KMM_QT_ITEM is null OR KIT.FAT_KMM_QT_ITEM = pFAT_KMM_QT_ITEM) AND
        (pFAT_KMM_DT_ULTIMA_ATUALIZACAO is null OR KIT.FAT_KMM_DT_ULTIMA_ATUALIZACAO = pFAT_KMM_DT_ULTIMA_ATUALIZACAO) AND
        (pSEG_USU_ID_USUARIO is null OR KIT.SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO);
    io_cursor := v_cursor;
  end PRC_FAT_KMM_KIT_MAT_MED_S;
