CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_CIRUR_EXEC"
(
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE         IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE default null,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE default null,
    pCAD_SET_ID                   IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO          IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO             IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO     IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
    pTIS_CBO_CD_CBOS              IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT         IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT         IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I   in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_E   in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pFATURADO   VARCHAR2 DEFAULT NULL, 
    pLOTEGERADO VARCHAR2 DEFAULT NULL,
    pAUDITORIA  VARCHAR2 DEFAULT NULL,
    pEMITIDO    VARCHAR2 DEFAULT NULL,
    pDIGITADO   VARCHAR2 DEFAULT NULL,
    pCAD_PRD_ID                   IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
    pTIS_MED_CD_TABELAMEDICA      IN TB_TIS_MED_TABELAMEDICA.TIS_MED_CD_TABELAMEDICA%TYPE DEFAULT NULL,
    pAUX_EPP_CD_ESPECPROC         IN TB_AUX_EPP_ESPECPROC.AUX_EPP_CD_ESPECPROC%TYPE DEFAULT NULL,
    pAUX_GPC_CD_GRUPOPROC         IN TB_AUX_GPC_GRUPOPROC.AUX_GPC_CD_GRUPOPROC%TYPE DEFAULT NULL,
    pCAD_PRO_ID_PROF_EXEC         IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR--,
  --  TESTE OUT LONG
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_CIRUR_EXEC
*    DATA ALTERACAO: 04/09/2013  POR: PEDRO
*    ALTERAC?O: add params
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(3000);
  V_WHERE2  varchar2(500);
  V_SELECT  varchar2(30000);
begin
  V_WHERE := NULL;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO = ' || pCAD_LAT_ID_LOCAL_ATENDIMENTO; END IF;
IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND ATE.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pCAD_PLA_ID_PLANO IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND PAC.CAD_PLA_ID_PLANO = ' || pCAD_PLA_ID_PLANO;    END IF;
IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.FAT_CCI_MES_FECHAMENTO = ' || pFAT_CCP_MES_FAT; END IF;
IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCI.FAT_CCI_ANO_FECHAMENTO = ' || pFAT_CCP_ANO_FAT; END IF;
IF pTIS_TAT_CD_TPATENDIMENTO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.TIS_TAT_CD_TPATENDIMENTO = ' ||CHR(39)|| pTIS_TAT_CD_TPATENDIMENTO ||CHR(39); END IF;
IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_DT_INICIO_CONSUMO >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);    END IF;
IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CCI.FAT_CCI_DT_FIM_CONSUMO <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);    END IF;
IF pTIS_MED_CD_TABELAMEDICA IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRD.TIS_MED_CD_TABELAMEDICA = ' || chr(39) || pTIS_MED_CD_TABELAMEDICA || chr(39) ;    END IF;
IF pAUX_GPC_CD_GRUPOPROC IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRD.AUX_GPC_CD_GRUPOPROC = ' || chr(39) || pAUX_GPC_CD_GRUPOPROC || chr(39) ;    END IF;
IF pAUX_EPP_CD_ESPECPROC IS NOT NULL THEN V_WHERE := V_WHERE || ' AND PRD.AUX_EPP_CD_ESPECPROC = ' || chr(39) || pAUX_EPP_CD_ESPECPROC || chr(39) ;    END IF;
IF pTIS_CBO_CD_CBOS IS NOT NULL THEN V_WHERE := V_WHERE || ' AND ATE.TIS_CBO_CD_CBOS = ' || chr(39) || pTIS_CBO_CD_CBOS || chr(39) ;    END IF;
IF pCAD_PRD_ID  IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND CCI.CAD_PRD_ID_COBRADO  = ' || pCAD_PRD_ID ;    END IF;
IF pCAD_PRO_ID_PROF_EXEC  IS NOT NULL THEN    V_WHERE := V_WHERE || ' AND CCI.CAD_PRO_ID_PROFISSIONAL  = ' || pCAD_PRO_ID_PROF_EXEC ;    END IF;

 V_WHERE2 := NULL;    
    IF pFAT_CCP_MES_FAT IS NOT NULL THEN       V_WHERE2 := V_WHERE2 || ' AND CCP.FAT_CCP_MES_FAT = ' || pFAT_CCP_MES_FAT;    END IF;
    IF pFAT_CCP_ANO_FAT IS NOT NULL THEN       V_WHERE2 := V_WHERE2 || ' AND CCP.FAT_CCP_ANO_FAT = ' || pFAT_CCP_ANO_FAT;    END IF;
    
----Nina:"só HM porque tem exames que estao marcados como cirurgia no produto"
V_SELECT:=
'
 SELECT   DISTINCT
              PRD.CAD_PRD_DS_DESCRICAO,
              PRO.CAD_PRO_NM_NOME,
              to_number(CCI.TIS_GPP_CD_GRAU_PART_PROF) TIS_GPP_CD_GRAU_PART_PROF,
              GPP.TIS_GPP_DS_GRAU_PART_PROF,
              CCI.FAT_CCI_PC_GRAU_PART_PROF,
              CASE WHEN  CCI.FAT_CCI_TP_PORTEANESTESICO IN (0,1,2) THEN '||chr(39)||'PORTE PEQUENO'||chr(39)||'
                   WHEN  CCI.FAT_CCI_TP_PORTEANESTESICO IN (3,4) THEN '||chr(39)||'PORTE MEDIO'||chr(39)||'
                   WHEN  CCI.FAT_CCI_TP_PORTEANESTESICO IN (5,6,7) THEN '||chr(39)||'PORTE GRANDE'||chr(39)||'
              END DS_PORTE,
          --    CASE WHEN CCI.FAT_CCI_ID_PRINCIPAL IS NOT NULL THEN CCI.FAT_CCI_VL_FATURADO
           --        ELSE 0
           --   END FAT_CCI_VL_FATURADO,
              CCI.FAT_CCI_DT_INICIO_CONSUMO,
              CCI.FAT_CCI_HR_INICIO_CONSUMO,
              CNV.CAD_CNV_CD_HAC_PRESTADOR,
              CNV.CAD_CNV_NM_FANTASIA,
              PLA.CAD_PLA_CD_PLANO_HAC,
              PLA.CAD_PLA_NM_NOME_PLANO,
              PAC.CAD_PAC_NR_PRONTUARIO,
              PES.CAD_PES_NM_PESSOA,
              UNI.CAD_UNI_DS_UNIDADE,
              CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO,
              SET_QLE.CAD_SET_DS_SETOR,
              QLE.CAD_QLE_NR_QUARTO,
              QLE.CAD_QLE_NR_LEITO,
              CCI.CAD_TAP_TP_ATRIBUTO,
              CCI.ATD_ATE_ID,
              CCI.FAT_CCP_ID,
              CCI.FAT_COC_ID,
              CCI.CAD_PAC_ID_PACIENTE,
              COUNT(distinct cci.atd_ate_id||cci.CAD_PRD_ID_COBRADO||CCI.FAT_CCI_DT_INICIO_CONSUMO||CCI.FAT_CCI_HR_INICIO_CONSUMO||
              CASE WHEN CCI.FAT_CCI_ID_PRINCIPAL IS NULL THEN CCI.FAT_CCI_ID ELSE CCI.FAT_CCI_ID_PRINCIPAL END) OVER() TOTAL
              FROM    TB_FAT_CCI_CONTA_CONSU_ITEM  CCI
              LEFT JOIN    TB_FAT_CCP_CONTA_CONS_PARC   CCP
              ON      CCP.FAT_CCP_ID             = CCI.FAT_CCP_ID
              AND     CCP.ATD_ATE_ID             = CCI.ATD_ATE_ID
              AND     CCP.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE
              AND     CCP.FAT_COC_ID             = CCI.FAT_COC_ID
              AND     (CCP.FAT_CCP_FL_STATUS = '||chr(39)||'A'||chr(39)||')
              ' || V_WHERE2 || '
              JOIN    TB_CAD_PRD_PRODUTO           PRD
              ON      PRD.CAD_PRD_ID             = CCI.CAD_PRD_ID_COBRADO
              JOIN    TB_ATD_ATE_ATENDIMENTO       ATE
              ON      ATE.ATD_ATE_ID             = CCI.ATD_ATE_ID
              JOIN    TB_CAD_UNI_UNIDADE           UNI
              ON      UNI.CAD_UNI_ID_UNIDADE     = CCI.CAD_UNI_ID_UNIDADE
              JOIN    TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
              ON      LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = CCI.CAD_LAT_ID_LOCAL_ATENDIMENTO
              JOIN    TB_CAD_PAC_PACIENTE          PAC
              ON      PAC.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE
              JOIN    TB_CAD_PLA_PLANO             PLA
              ON      PLA.CAD_PLA_ID_PLANO       = PAC.CAD_PLA_ID_PLANO
              JOIN    TB_CAD_CNV_CONVENIO          CNV
              ON      CNV.CAD_CNV_ID_CONVENIO    = CCI.CAD_CNV_ID_CONVENIO
              JOIN    TB_CAD_PES_PESSOA            PES
              ON      PES.CAD_PES_ID_PESSOA      = PAC.CAD_PES_ID_PESSOA
              JOIN    TB_CAD_PRO_PROFISSIONAL      PRO
              ON      PRO.CAD_PRO_ID_PROFISSIONAL = CCI.CAD_PRO_ID_PROFISSIONAL
              JOIN    TB_TIS_GPP_GRAU_PART_PROF    GPP
              ON      GPP.TIS_GPP_CD_GRAU_PART_PROF = CCI.TIS_GPP_CD_GRAU_PART_PROF
              LEFT JOIN    TB_ATD_IML_INT_MOV_LEITO     IML
              ON      IML.ATD_ATE_ID             = CCI.ATD_ATE_ID
              AND     IML.ATD_IML_FL_STATUS      = '||chr(39)||'A'||chr(39)||'
              AND     TO_DATE(TO_CHAR(CCI.FAT_CCI_DT_INICIO_CONSUMO,'||chr(39)||'dd-MM-yyyy'||chr(39)||')||TO_CHAR(CCI.FAT_CCI_HR_INICIO_CONSUMO,'||chr(39)||'0000'||chr(39)||'),'||chr(39)||'dd-MM-yyyy HH24MI'||chr(39)||')
                      BETWEEN TO_DATE(TO_CHAR(IML.ATD_IML_DT_ENTRADA,'||chr(39)||'dd-MM-yyyy'||chr(39)||')||TO_CHAR(IML.ATD_IML_HR_ENTRADA,'||chr(39)||'0000'||chr(39)||'),'||chr(39)||'dd-MM-yyyy HH24MI'||chr(39)||')
                      AND TO_DATE(TO_CHAR(IML.ATD_IML_DT_SAIDA,'||chr(39)||'dd-MM-yyyy'||chr(39)||')||TO_CHAR(IML.ATD_IML_HR_SAIDA,'||chr(39)||'0000'||chr(39)||'),'||chr(39)||'dd-MM-yyyy HH24MI'||chr(39)||')
              LEFT JOIN    TB_CAD_QLE_QUARTO_LEITO      QLE
              ON      QLE.CAD_QLE_ID             = IML.CAD_CAD_QLE_ID
              LEFT JOIN    TB_CAD_SET_SETOR             SET_QLE
              ON      SET_QLE.CAD_SET_ID         = QLE.CAD_SET_ID
              WHERE   (CCI.ATD_ATE_TP_PACIENTE IN ('||chr(39)||'I'||chr(39)||','||chr(39)||'E'||chr(39)||'))
              AND     (CCI.FAT_CCI_FL_STATUS = '||chr(39)||'A'||chr(39)||')
              AND     (CCI.CAD_TAP_TP_ATRIBUTO IN ('||chr(39)||'HM'||chr(39)||'))
              AND     (CCI.FAT_CCI_TP_PORTEANESTESICO IS NOT NULL)
              AND     (PRD.CAD_PRD_FL_CIRURGIA = '||chr(39)||'S'||chr(39)||')
              AND    (UNI.CAD_UNI_FL_FATURA_UNID_OK = '||chr(39)||'S'||chr(39)||')
             ' || V_WHERE || '
            AND     ((' ||chr(39)|| pFATURADO  || chr(39) || ' IS NOT NULL AND CCP.FAT_NOF_ID IS NOT NULL )
            OR  (' || chr(39) || pAUDITORIA  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_STATUS_AUDIT = ' || chr(39) || 'E' || chr(39) || ')
            OR  (' || chr(39) || pLOTEGERADO  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_FATURADA = ' || chr(39) || 'S' || chr(39) || ' AND CCP.FAT_NOF_ID IS NULL)
            OR  (' || chr(39) || pEMITIDO  || chr(39) || ' IS NOT NULL AND CCP.FAT_CCP_FL_EMITIDA = ' || chr(39) || 'S' || chr(39) || ' AND CCP.FAT_CCP_FL_FATURADA = ' || chr(39) || 'N' || chr(39) || '
                AND (CCP.FAT_CCP_FL_STATUS_AUDIT = ' || chr(39) || 'A' || chr(39) || ' OR CCP.FAT_CCP_DT_ENVIO_AUDIT IS NULL))
            OR  (' || chr(39) || pDIGITADO  || chr(39) || ' IS NOT NULL AND CCI.FAT_CCP_ID IS NULL))
            AND ('||chr(39)|| pATD_ATE_TP_PACIENTE_I ||chr(39)||' IS not NULL and CCI.atd_ate_tp_paciente = '||chr(39)||'I'||chr(39)||'
             OR '||chr(39)|| pATD_ATE_TP_PACIENTE_E ||chr(39)||' IS NOT NULL AND CCI.atd_ate_tp_paciente = '||chr(39)||'E'||chr(39)||')
          AND    ('||chr(39)|| pCAD_PLA_CD_TIPOPLANO_GB ||chr(39)||' IS not NULL and CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'ACS'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_PA ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'PA'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_SP ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'SP'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_FU ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'FU'||chr(39)||'
             OR '||chr(39)|| pCAD_PLA_CD_TIPOPLANO_NP ||chr(39)||' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = '||chr(39)||'NP'||chr(39)||')'
  ;
 --   TESTE :=  V_SELECT ;
  OPEN v_cursor FOR
   V_SELECT ;
    io_cursor := v_cursor;
END PRC_FAT_REL_CIRUR_EXEC;
 