CREATE OR REPLACE PROCEDURE PRC_FAT_REL_RECEITA_VALOR_ACUM
(
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_A IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_RECEITA_VALOR_ACUM
*
*    Data Alteracao: 21/10/2011  Por: PEDRO
*    Alterac?o:
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
BEGIN
  OPEN v_cursor FOR
 SELECT 
            FAT_CCP_MES_FAT,
            FAT_CCP_ANO_FAT,
            CAD_CNV_ID_CONVENIO,
            CAD_CNV_CD_HAC_PRESTADOR,
            CAD_CNV_NM_FANTASIA,
            SERVICOS_ADM_ANO,
            SERVICOS_ADM_MES,
            ESTAGIO_ANO,
            ESTAGIO_MES,
            CURSOS_ANO,
            CURSOS_MES,
            SUM(QT_ATEND_ANUAL)    QT_ATEND_ANUAL,
            SUM(VALOR_TOTAL_ANUAL) VALOR_TOTAL_ANUAL,
            SUM(QT_ATEND_MES)      QT_ATEND_MES,
            SUM(VALOR_TOTAL_MES)   VALOR_TOTAL_MES
  FROM (
 SELECT 
            MES.FAT_CCP_MES_FAT,
            CNV.CAD_CNV_ID_CONVENIO,
            CCP.FAT_CCP_ANO_FAT,
            CNV.CAD_CNV_CD_HAC_PRESTADOR,
            CNV.CAD_CNV_NM_FANTASIA,
            COUNT(DISTINCT CCP.ATD_ATE_ID||CCP.FAT_CCP_ID||CNV.CAD_CNV_CD_HAC_PRESTADOR||CCP.FAT_CCP_ANO_FAT) QT_ATEND_ANUAL,             
            SUM(CCP.FAT_CCP_VL_TOT_CONTA)  VALOR_TOTAL_ANUAL,
            NVL(MES.QT_ATEND,0)            QT_ATEND_MES,
            NVL(MES.VALOR_TOTAL,0)         VALOR_TOTAL_MES,
            null SERVICOS_ADM_ANO,
            null SERVICOS_ADM_MES,
            null ESTAGIO_ANO,
            null ESTAGIO_MES,
            NULL CURSOS_ANO,
            NULL CURSOS_MES
    FROM    TB_FAT_CCP_CONTA_CONS_PARC   CCP
    JOIN    TB_ATD_ATE_ATENDIMENTO       ATE    ON      ATE.ATD_ATE_ID             = CCP.ATD_ATE_ID   
    JOIN    TB_CAD_PAC_PACIENTE          PAC    ON      PAC.CAD_PAC_ID_PACIENTE    = CCP.CAD_PAC_ID_PACIENTE
    JOIN    TB_CAD_CNV_CONVENIO          CNV    ON      CNV.CAD_CNV_ID_CONVENIO    = PAC.CAD_CNV_ID_CONVENIO
    JOIN    TB_CAD_PLA_PLANO             PLA    ON      PLA.CAD_PLA_ID_PLANO       = PAC.CAD_PLA_ID_PLANO
     LEFT JOIN    (                
             SELECT 
                CCP.FAT_CCP_MES_FAT,
                CCP.FAT_CCP_ANO_FAT,
                CNV.CAD_CNV_ID_CONVENIO,
                CNV.CAD_CNV_CD_HAC_PRESTADOR,
                CNV.CAD_CNV_NM_FANTASIA,
                COUNT(DISTINCT CCP.ATD_ATE_ID||CCP.FAT_CCP_ID||CNV.CAD_CNV_CD_HAC_PRESTADOR||CCP.FAT_CCP_MES_FAT||CCP.FAT_CCP_ANO_FAT) QT_ATEND,
                SUM(CCP.FAT_CCP_VL_TOT_CONTA)   VALOR_TOTAL
        FROM    TB_FAT_CCP_CONTA_CONS_PARC   CCP
        JOIN    TB_ATD_ATE_ATENDIMENTO       ATE        ON      ATE.ATD_ATE_ID             = CCP.ATD_ATE_ID   
        JOIN    TB_CAD_PAC_PACIENTE          PAC        ON      PAC.CAD_PAC_ID_PACIENTE    = CCP.CAD_PAC_ID_PACIENTE
        JOIN    TB_CAD_CNV_CONVENIO          CNV        ON      CNV.CAD_CNV_ID_CONVENIO    = PAC.CAD_CNV_ID_CONVENIO
        JOIN    TB_CAD_PLA_PLANO             PLA        ON      PLA.CAD_PLA_ID_PLANO       = PAC.CAD_PLA_ID_PLANO
        WHERE   (CCP.FAT_CCP_FL_STATUS = 'A')  
        AND     (CCP.FAT_NOF_ID IS NOT NULL)
        AND     (CCP.FAT_CCP_MES_FAT = pFAT_CCP_MES_FAT)
        AND     (CCP.FAT_CCP_ANO_FAT = pFAT_CCP_ANO_FAT)
        AND     (pCAD_UNI_ID_UNIDADE IS NULL OR ATE.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
        AND     (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
        AND     (pCAD_SET_ID IS NULL OR ATE.CAD_SET_ID = pCAD_SET_ID)
        AND     (pTIS_TAT_CD_TPATENDIMENTO IS NULL OR ATE.TIS_TAT_CD_TPATENDIMENTO = pTIS_TAT_CD_TPATENDIMENTO)
        AND     (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
        AND     (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
        AND  (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = 'GB'
         OR  pCAD_PLA_CD_TIPOPLANO_PL IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PL'
         OR  pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PA'
         OR  pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'SP'
         OR  pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'FU'
         OR  pCAD_PLA_CD_TIPOPLANO_NP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'NP')
    AND     (pATD_ATE_TP_PACIENTE_I IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'I'
         OR pATD_ATE_TP_PACIENTE_E IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'E'
         OR pATD_ATE_TP_PACIENTE_A IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'A'
         OR pATD_ATE_TP_PACIENTE_U IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'U')
        GROUP BY CCP.FAT_CCP_MES_FAT,
                CCP.FAT_CCP_ANO_FAT,
                CNV.CAD_CNV_ID_CONVENIO,
                CNV.CAD_CNV_CD_HAC_PRESTADOR,
                CNV.CAD_CNV_NM_FANTASIA
     ) MES
     ON MES.CAD_CNV_ID_CONVENIO = CNV.CAD_CNV_ID_CONVENIO
    WHERE   (CCP.FAT_CCP_FL_STATUS = 'A')  
    AND     (CCP.FAT_NOF_ID IS NOT NULL)
    AND     (pCAD_UNI_ID_UNIDADE IS NULL OR ATE.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
    AND     (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
    AND     (pCAD_SET_ID IS NULL OR ATE.CAD_SET_ID = pCAD_SET_ID)
    AND     (pTIS_TAT_CD_TPATENDIMENTO IS NULL OR ATE.TIS_TAT_CD_TPATENDIMENTO = pTIS_TAT_CD_TPATENDIMENTO)
    AND     (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
    AND     (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
    AND     (CCP.FAT_CCP_MES_FAT <= pFAT_CCP_MES_FAT)
    AND     (CCP.FAT_CCP_ANO_FAT = pFAT_CCP_ANO_FAT)
    AND  (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = 'GB'
     OR  pCAD_PLA_CD_TIPOPLANO_PL IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PL'
     OR  pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PA'
     OR  pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'SP'
     OR  pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'FU'
     OR  pCAD_PLA_CD_TIPOPLANO_NP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'NP')
    AND     (pATD_ATE_TP_PACIENTE_I IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'I'
         OR pATD_ATE_TP_PACIENTE_E IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'E'
         OR pATD_ATE_TP_PACIENTE_A IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'A'
         OR pATD_ATE_TP_PACIENTE_U IS NOT NULL AND ATE.ATD_ATE_TP_PACIENTE = 'U')
    GROUP BY MES.FAT_CCP_MES_FAT,
            CNV.CAD_CNV_ID_CONVENIO,
            CCP.FAT_CCP_ANO_FAT,
            CNV.CAD_CNV_CD_HAC_PRESTADOR,
            CNV.CAD_CNV_NM_FANTASIA,
            NVL(MES.QT_ATEND,0), 
            NVL(MES.VALOR_TOTAL,0) 
    UNION
   
 SELECT
            null FAT_CCP_MES_FAT,
            null CAD_CNV_ID_CONVENIO,
            null FAT_CCP_ANO_FAT,
            null CAD_CNV_CD_HAC_PRESTADOR,
            'SERVICOS ADMINISTRATIVOS' CAD_CNV_NM_FANTASIA,
            null QT_ATEND_ANUAL,             
            null VALOR_TOTAL_ANUAL,
            null QT_ATEND_MES,
            null VALOR_TOTAL_MES,
            NVL(SUM(NOF.FAT_NFO_VL_FATURADO),0) SERVICOS_ADM_ANO,
            NVL(MES.SERVICOS_ADM,0) SERVICOS_ADM_MES,
            NULL ESTAGIOS_ANO,
            NULL ESTAGIOS_MES,
            NULL CURSOS_ANO,
            NULL CURSOS_MES
      FROM TB_CAD_PLA_PLANO PLA, TB_CAD_CNV_CONVENIO CNV, TB_FAT_NOF_NOTA_FISCAL NOF, 
           TB_CAD_UNI_UNIDADE UNI,
           ( SELECT
             nofb.FAT_NOF_MES_FAT,
             nofb.CAD_CNV_ID_CONVENIO,
             nofb.FAT_NOF_ANO_FAT,
            null CAD_CNV_CD_HAC_PRESTADOR,
            null CAD_CNV_NM_FANTASIA,
            null QT_ATEND_ANUAL,             
            null VALOR_TOTAL_ANUAL,
            null QT_ATEND_MES,
            null VALOR_TOTAL_MES,
            NVL(SUM(nofb.FAT_NFO_VL_FATURADO),0) SERVICOS_ADM      
            FROM TB_CAD_PLA_PLANO PLA, TB_CAD_CNV_CONVENIO CNV, TB_FAT_NOF_NOTA_FISCAL NOFb, 
                 TB_CAD_UNI_UNIDADE UNI
            WHERE 
                nofb.FAT_NOF_MES_FAT     = pFAT_CCP_MES_FAT
            AND nofb.FAT_NOF_ANO_FAT     = pFAT_CCP_ANO_FAT
            AND nofb.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
            AND CNV.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
            AND nofb.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
            AND nofb.FAT_NOF_FL_STATUS = 'A'
            AND (CNV.CAD_CNV_CD_HAC_PRESTADOR = 'S186')
            AND (pCAD_UNI_ID_UNIDADE IS NULL OR uNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
            AND (pCAD_CNV_ID_CONVENIO IS NULL OR CNV.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
            AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO) 
            group by nofb.FAT_NOF_MES_FAT, nofb.CAD_CNV_ID_CONVENIO, nofb.FAT_NOF_ANO_FAT
      ) MES
      WHERE 
       mes.FAT_NOF_MES_FAT = NOF.FAT_NOF_ANO_FAT 
      and mes.CAD_CNV_ID_CONVENIO = nof.cad_cnv_id_convenio
      and mes.FAT_NOF_ANO_FAT = nof.fat_nof_ano_fat           
      and NOF.FAT_NOF_ANO_FAT     = pFAT_CCP_ANO_FAT
      AND NOF.FAT_NOF_MES_FAT    <= pFAT_CCP_MES_FAT
      AND NOF.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
      AND CNV.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
      AND (CNV.CAD_CNV_CD_HAC_PRESTADOR = 'S186')
      AND NOF.CAD_UNI_ID_UNIDADE  = UNI.CAD_UNI_ID_UNIDADE
      AND NOF.FAT_NOF_FL_STATUS = 'A'
      AND (pCAD_UNI_ID_UNIDADE IS NULL OR uNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
      AND (pCAD_CNV_ID_CONVENIO IS NULL OR CNV.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
      AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO) 
       GROUP BY MES.SERVICOS_ADM
UNION
 SELECT
            null FAT_CCP_MES_FAT,
            null CAD_CNV_ID_CONVENIO,
            null FAT_CCP_ANO_FAT,
            null CAD_CNV_CD_HAC_PRESTADOR,
            'CURSOS' CAD_CNV_NM_FANTASIA,
            null QT_ATEND_ANUAL,             
            null VALOR_TOTAL_ANUAL,
            null QT_ATEND_MES,
            null VALOR_TOTAL_MES,
            NULL,
            NULL, 
            NULL ESTAGIOS_ANO,
            NULL ESTAGIOS_MES,
            NVL(SUM(NF.Valtotnf),0) CURSOS_ANO,
            NVL(MES.CURSOS,0)CURSOS_MES
            
      FROM tb_nota_fiscal nf, 
           TB_CAD_UNI_UNIDADE UNI,
           ( SELECT
            null FAT_CCP_MES_FAT,
            null CAD_CNV_ID_CONVENIO,
            null FAT_CCP_ANO_FAT,
            null CAD_CNV_CD_HAC_PRESTADOR,
            null CAD_CNV_NM_FANTASIA,
            null QT_ATEND_ANUAL,             
            null VALOR_TOTAL_ANUAL,
            null QT_ATEND_MES,
            null VALOR_TOTAL_MES,
             NVL(SUM(NF.Valtotnf),0) CURSOS      
            FROM tb_nota_fiscal nf, 
           TB_CAD_UNI_UNIDADE UNI
            WHERE 
                nF.Codunihos = UNI.CAD_UNI_CD_UNID_HOSPITALAR
            AND TO_CHAR(nf.datnf,'MM') = pFAT_CCP_MES_FAT
            AND TO_CHAR(nf.datnf,'yyyy') = pFAT_CCP_ANO_FAT
            AND nf.tiponf = 'TXC'
            AND NF.SITNF != 'C'
            AND (pCAD_UNI_ID_UNIDADE IS NULL OR uNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
      ) MES
      WHERE 
         nF.Codunihos = UNI.CAD_UNI_CD_UNID_HOSPITALAR
      AND TO_CHAR(nf.datnf,'yyyy') = pFAT_CCP_ANO_FAT
      AND TO_CHAR(nf.datnf,'MM')    <= pFAT_CCP_MES_FAT      
      AND nf.tiponf = 'TXC'
      AND NF.SITNF != 'C'
      AND (pCAD_UNI_ID_UNIDADE IS NULL OR uNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
       GROUP BY MES.CURSOS
     UNION
      SELECT
            null FAT_CCP_MES_FAT,
            null CAD_CNV_ID_CONVENIO,
            null FAT_CCP_ANO_FAT,
            null CAD_CNV_CD_HAC_PRESTADOR,
            'ESTAGIOS' CAD_CNV_NM_FANTASIA,
            null QT_ATEND_ANUAL,             
            null VALOR_TOTAL_ANUAL,
            null QT_ATEND_MES,
            null VALOR_TOTAL_MES,
            NULL SERVICOS_ADM_ANO,
            NULL SERVICOS_ADM_MES,
            NVL(SUM(NOF.FAT_NFO_VL_FATURADO),0) ESTAGIOS_ANO,
            NVL(MES.ESTAGIOS,0) ESTAGIOS_MES,
            NULL CURSOS_ANO,
            NULL CURSOS_MES
      FROM TB_CAD_PLA_PLANO PLA, TB_CAD_CNV_CONVENIO CNV, TB_FAT_NOF_NOTA_FISCAL NOF, 
           TB_CAD_UNI_UNIDADE UNI,
           ( SELECT
       nofb.FAT_NOF_MES_FAT,
             nofb.CAD_CNV_ID_CONVENIO,
             nofb.FAT_NOF_ANO_FAT,
            null CAD_CNV_CD_HAC_PRESTADOR,
            null CAD_CNV_NM_FANTASIA,
            null QT_ATEND_ANUAL,             
            null VALOR_TOTAL_ANUAL,
            null QT_ATEND_MES,
            null VALOR_TOTAL_MES,
            NVL(SUM(nofb.FAT_NFO_VL_FATURADO),0) ESTAGIOS
            FROM TB_CAD_PLA_PLANO PLA, TB_CAD_CNV_CONVENIO CNV, TB_FAT_NOF_NOTA_FISCAL NOFb, 
                 TB_CAD_UNI_UNIDADE UNI
            WHERE 
                nofb.FAT_NOF_MES_FAT     = pFAT_CCP_MES_FAT
            AND nofb.FAT_NOF_ANO_FAT     = pFAT_CCP_ANO_FAT
            AND nofb.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
            AND CNV.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
            AND nofb.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
            AND nofb.FAT_NOF_FL_STATUS = 'A'
            AND (CNV.CAD_CNV_CD_HAC_PRESTADOR in ('FESS','VALE','FUL1'))
            AND (pCAD_UNI_ID_UNIDADE IS NULL OR uNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
           AND (pCAD_CNV_ID_CONVENIO IS NULL OR CNV.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
            AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO) 
                        group by nofb.FAT_NOF_MES_FAT, nofb.CAD_CNV_ID_CONVENIO, nofb.FAT_NOF_ANO_FAT
      ) MES
      WHERE 
          NOF.FAT_NOF_ANO_FAT     = pFAT_CCP_ANO_FAT
      AND NOF.FAT_NOF_MES_FAT    <= pFAT_CCP_MES_FAT       
      AND NOF.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
      AND CNV.CAD_CNV_ID_CONVENIO = PLA.CAD_CNV_ID_CONVENIO
      AND NOF.CAD_UNI_ID_UNIDADE  = UNI.CAD_UNI_ID_UNIDADE
      AND (CNV.CAD_CNV_CD_HAC_PRESTADOR in ('FESS','VALE','FUL1'))
      AND NOF.FAT_NOF_FL_STATUS = 'A'
      AND (pCAD_UNI_ID_UNIDADE IS NULL OR uNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
      AND (pCAD_CNV_ID_CONVENIO IS NULL OR CNV.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
      AND (pCAD_PLA_ID_PLANO IS NULL OR PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO) 
       GROUP BY MES.ESTAGIOS
      ) 
      GROUP BY  FAT_CCP_MES_FAT,
                CAD_CNV_ID_CONVENIO,
                FAT_CCP_ANO_FAT,
                CAD_CNV_CD_HAC_PRESTADOR,
                CAD_CNV_NM_FANTASIA,
               SERVICOS_ADM_ANO,
            SERVICOS_ADM_MES,
            ESTAGIO_ANO,
            ESTAGIO_MES,
            CURSOS_ANO,
            CURSOS_MES
     HAVING SUM(QT_ATEND_MES) > 0  OR SERVICOS_ADM_MES > 0 OR ESTAGIO_ANO > 0 OR CURSOS_MES >0
    ;
  io_cursor := v_cursor;
END PRC_FAT_REL_RECEITA_VALOR_ACUM;
