CREATE OR REPLACE PROCEDURE PRC_AGS_AGE_AGENDA_DIA
(
   pEscalas IN varchar2,
   pAGS_AGG_DT_AGENDA_GERADA IN TB_AGS_AGG_AGE_GERADA_SADT.AGS_AGG_DT_AGENDA_GERADA%TYPE,
   io_cursor OUT PKG_CURSOR.t_cursor
)
IS
 v_cursor PKG_CURSOR.t_cursor;
 BEGIN
  OPEN v_cursor FOR
    SELECT
    AGG.AGS_AGG_ID,
    AGG.AGS_AGG_TP_HORARIO,
    AGG.AGS_AGG_DT_AGENDA_GERADA,
    AGG.AGS_AGG_HR_AGENDA_GERADA,
    AGG.AGS_AGG_FL_STATUS_HORARIO,
    PES.CAD_PES_NM_PESSOA,
    PRD.CAD_PRD_DS_DESCRICAO,
    AGG.AGS_ESM_ID,
    AGG.ASS_EHR_ID
    FROM
     TB_AGS_AGG_AGE_GERADA_SADT AGG
     LEFT JOIN TB_AGS_AGE_AGENDA_SADT  AGE
      ON AGE.AGS_AGG_ID = AGG.AGS_AGG_ID
     LEFT JOIN TB_CAD_PAC_PACIENTE PAC
      ON AGE.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
     LEFT JOIN TB_CAD_PES_PESSOA PES
      ON PES.CAD_PES_ID_PESSOA = PAC.CAD_PES_ID_PESSOA
     LEFT JOIN TB_CAD_PRD_PRODUTO PRD
      ON PRD.CAD_PRD_ID = AGE.CAD_PRD_ID
      WHERE AGG.AGS_ESM_ID IN pEscalas
      AND AGG.AGS_AGG_DT_AGENDA_GERADA = pAGS_AGG_DT_AGENDA_GERADA
    ORDER BY AGG.AGS_AGG_DT_AGENDA_GERADA, AGG.AGS_AGG_HR_AGENDA_GERADA;

    io_cursor := v_cursor;

 END PRC_AGS_AGE_AGENDA_DIA;
