CREATE OR REPLACE PROCEDURE SGS."PRC_AGS_ESM_SEGURANCA_ESCALA"
(
       pCAD_UNI_ID_UNIDADE IN TB_AGE_ESM_ESCALA_MEDICA.CAD_UNI_ID_UNIDADE%TYPE,
       pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_AGE_ESM_ESCALA_MEDICA.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE,
       pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE,
       pAGE_SAU_ID IN TB_AGE_SAU_SALA_UNID_AND.AGE_SAU_ID%TYPE,
       pAGS_ESM_HR_INI_ESCALA IN TB_AGS_ESM_ESCALA_SADT.AGS_ESM_HR_INI_ESCALA%TYPE,
       pAGS_ESM_HR_FIM_ESCALA IN TB_AGS_ESM_ESCALA_SADT.AGS_ESM_HR_FIM_ESCALA%TYPE,
       pAGS_ESM_DT_INI_ESCALA IN TB_AGS_ESM_ESCALA_SADT.AGS_ESM_DT_INI_ESCALA%TYPE,
       pAGS_ESM_DT_FIM_ESCALA IN TB_AGS_ESM_ESCALA_SADT.AGS_ESM_DT_FIM_ESCALA%TYPE,
       pAGS_ESM_NR_DIA_SEMANA IN TB_AGS_ESM_ESCALA_SADT.AGS_ESM_NR_DIA_SEMANA%TYPE,
       pAGS_ESM_ID IN TB_AGS_ESM_ESCALA_SADT.AGS_ESM_ID%TYPE DEFAULT NULL,
       io_cursor OUT PKG_CURSOR.t_cursor
)
IS
/**********************************************************************
    *   Data de Alteracao: 10/10/2014 por: Pedro
    *   Alteracao:  AND (ESM.AGS_ESM_QT_DIAS_INTERVALO = 7 
        OR (ESM.AGS_ESM_QT_DIAS_INTERVALO != 7 AND (AGG.AGS_AGG_DT_AGENDA_GERADA = pAGS_ESM_DT_INI_ESCALA
                                                OR (pAGS_ESM_DT_INI_ESCALA > V_DATA_MAXIMA_AGG))
           ))    
    *    
*/
V_DATA_MAXIMA_AGG DATE;
v_cursor PKG_CURSOR.t_cursor;
BEGIN  
      SELECT MAX(AGG.AGS_AGG_DT_AGENDA_GERADA) INTO V_DATA_MAXIMA_AGG
           FROM TB_AGS_ESM_ESCALA_SADT     ESM
           JOIN TB_AGS_AGG_AGE_GERADA_SADT AGG ON AGG.AGS_ESM_ID = ESM.AGS_ESM_ID
          WHERE ESM.AGS_ESM_FL_STATUS IN ('A', 'P', 'S')
            AND ESM.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE
            AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
            AND ESM.CAD_SET_ID = pCAD_SET_ID
            AND ESM.AGE_SAU_ID = pAGE_SAU_ID
            AND ESM.AGS_ESM_NR_DIA_SEMANA = pAGS_ESM_NR_DIA_SEMANA
            AND (pAGS_ESM_ID IS NULL OR ESM.AGS_ESM_ID != pAGS_ESM_ID);
OPEN v_cursor FOR
SELECT ESM.AGS_ESM_ID
     FROM TB_AGS_ESM_ESCALA_SADT     ESM
LEFT JOIN TB_AGS_AGG_AGE_GERADA_SADT AGG ON AGG.AGS_ESM_ID = ESM.AGS_ESM_ID
    WHERE ESM.AGS_ESM_FL_STATUS IN ('A', 'P', 'S')
      AND ESM.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE
      AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
      AND ESM.CAD_SET_ID = pCAD_SET_ID
      AND ESM.AGE_SAU_ID = pAGE_SAU_ID
      AND ESM.AGS_ESM_NR_DIA_SEMANA = pAGS_ESM_NR_DIA_SEMANA
      AND (pAGS_ESM_ID IS NULL OR ESM.AGS_ESM_ID != pAGS_ESM_ID)
      AND (                  
          ((pAGS_ESM_HR_INI_ESCALA+1) between ESM.AGS_ESM_HR_INI_ESCALA and ESM.AGS_ESM_HR_FIM_ESCALA 
       OR (pAGS_ESM_HR_FIM_ESCALA-1) between ESM.AGS_ESM_HR_INI_ESCALA and ESM.AGS_ESM_HR_FIM_ESCALA)
          OR  
          ( ((pAGS_ESM_HR_INI_ESCALA+1) < ESM.AGS_ESM_HR_INI_ESCALA AND (pAGS_ESM_HR_FIM_ESCALA-1) > ESM.AGS_ESM_HR_FIM_ESCALA)
      AND (ESM.AGS_ESM_HR_INI_ESCALA BETWEEN (pAGS_ESM_HR_INI_ESCALA+1) AND ESM.AGS_ESM_HR_FIM_ESCALA
       OR ESM.AGS_ESM_HR_FIM_ESCALA BETWEEN AGS_ESM_HR_INI_ESCALA AND (pAGS_ESM_HR_FIM_ESCALA+1))
          )
          )         
      AND pAGS_ESM_DT_INI_ESCALA >= ESM.AGS_ESM_DT_INI_ESCALA --salvando ESCALA POSTEIOR
      AND (ESM.AGS_ESM_DT_FIM_ESCALA IS NULL OR pAGS_ESM_DT_INI_ESCALA <= ESM.AGS_ESM_DT_FIM_ESCALA)    
      AND pAGS_ESM_DT_INI_ESCALA >= TRUNC(SYSDATE)
      AND (ESM.AGS_ESM_QT_DIAS_INTERVALO = 7 
        OR (ESM.AGS_ESM_QT_DIAS_INTERVALO != 7 AND (AGG.AGS_AGG_DT_AGENDA_GERADA = pAGS_ESM_DT_INI_ESCALA
                                                OR (pAGS_ESM_DT_INI_ESCALA > V_DATA_MAXIMA_AGG))
           ))    
UNION  ------------------------------------------------------------------------------
   SELECT ESM.AGS_ESM_ID
     FROM TB_AGS_ESM_ESCALA_SADT     ESM
LEFT JOIN TB_AGS_AGG_AGE_GERADA_SADT AGG ON AGG.AGS_ESM_ID = ESM.AGS_ESM_ID
    WHERE ESM.AGS_ESM_FL_STATUS IN ('A', 'P', 'S')
      AND ESM.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE
      AND ESM.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
      AND ESM.CAD_SET_ID = pCAD_SET_ID
      AND ESM.AGE_SAU_ID = pAGE_SAU_ID
      AND ESM.AGS_ESM_NR_DIA_SEMANA = pAGS_ESM_NR_DIA_SEMANA
      AND (pAGS_ESM_ID IS NULL OR ESM.AGS_ESM_ID != pAGS_ESM_ID)
      AND (                  
          ((pAGS_ESM_HR_INI_ESCALA+1) between ESM.AGS_ESM_HR_INI_ESCALA and ESM.AGS_ESM_HR_FIM_ESCALA 
       OR (pAGS_ESM_HR_FIM_ESCALA-1) between ESM.AGS_ESM_HR_INI_ESCALA and ESM.AGS_ESM_HR_FIM_ESCALA)
          OR  
          ( ((pAGS_ESM_HR_INI_ESCALA+1) < ESM.AGS_ESM_HR_INI_ESCALA AND (pAGS_ESM_HR_FIM_ESCALA-1) > ESM.AGS_ESM_HR_FIM_ESCALA)
      AND (ESM.AGS_ESM_HR_INI_ESCALA BETWEEN (pAGS_ESM_HR_INI_ESCALA+1) AND ESM.AGS_ESM_HR_FIM_ESCALA
       OR ESM.AGS_ESM_HR_FIM_ESCALA BETWEEN AGS_ESM_HR_INI_ESCALA AND (pAGS_ESM_HR_FIM_ESCALA+1))
          )
          )  
      AND pAGS_ESM_DT_INI_ESCALA < ESM.AGS_ESM_DT_INI_ESCALA     --salvando ESCALA Anterior
      AND (pAGS_ESM_DT_FIM_ESCALA IS NULL OR pAGS_ESM_DT_FIM_ESCALA >= ESM.AGS_ESM_DT_INI_ESCALA)
      
      
     -- AND (ESM.AGS_ESM_DT_FIM_ESCALA IS NULL OR pAGS_ESM_DT_FIM_ESCALA >= ESM.AGS_ESM_DT_INI_ESCALA)
    --  AND (ESM.AGS_ESM_DT_FIM_ESCALA IS NULL OR pAGS_ESM_DT_FIM_ESCALA <= ESM.AGS_ESM_DT_FIM_ESCALA)   
    ----  AND ((pAGS_ESM_DT_FIM_ESCALA IS NULL) OR null >= TRUNC(SYSDATE))    
      AND (ESM.AGS_ESM_QT_DIAS_INTERVALO = 7 
        OR (ESM.AGS_ESM_QT_DIAS_INTERVALO != 7 AND (AGG.AGS_AGG_DT_AGENDA_GERADA = pAGS_ESM_DT_INI_ESCALA
                                                OR (pAGS_ESM_DT_INI_ESCALA > V_DATA_MAXIMA_AGG))
           ))
    ;
 io_cursor := v_cursor;
END PRC_AGS_ESM_SEGURANCA_ESCALA;
