CREATE OR REPLACE PROCEDURE SGS."PRC_FAT_REL_PAC_FAT_CONV_ANAL"
(
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_E in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_A in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_U in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pFATURADO varchar2 default null,
    pLOTEGERADO varchar2 default null,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_PAC_FAT_CONV_ANAL
*
*    Data Alteracao: 04/11/2010  Por: Pedro
*    Alterac?o:
*    Data Alteraá∆o:: 08/4/2011  Por: Eduardo
*    Alteraá∆o: Inclus∆o do Tipo Paciente
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
BEGIN
  OPEN v_cursor FOR
  SELECT  CNV.CAD_CNV_CD_HAC_PRESTADOR,
          CNV.CAD_CNV_DS_RAZAOSOCIAL,
          ATE.ATD_ATE_ID,
          ATE.ATD_ATE_DT_ATENDIMENTO,
          PES.CAD_PES_NM_PESSOA,
          NVL(INA.ATD_INA_DT_ALTA_ADM, CCP.FAT_CCP_DT_FATURAMENTO) FAT_CCP_DT_FATURAMENTO,
          CCP.FAT_CCP_ID,
          CCP.FAT_CCP_DT_PARCELA,
          CCP.FAT_CCP_VL_TOT_CONTA,
          ATE.ATD_ATE_FL_STATUS,
          NOF.FAT_NOF_NR_NOTAFISCAL,
          NOF.FAT_NOF_TP_SERIEFISCAL,
          ate.atd_ate_tp_paciente
  FROM    TB_FAT_CCP_CONTA_CONS_PARC  CCP
  JOIN    TB_ATD_ATE_ATENDIMENTO      ATE
  ON      ATE.ATD_ATE_ID            = CCP.ATD_ATE_ID
  JOIN    TB_FAT_COC_CONTA_CONSUMO    COC
  ON      COC.FAT_COC_ID            = CCP.FAT_COC_ID
  and     COC.CAD_PAC_ID_PACIENTE   = CCP.CAD_PAC_ID_PACIENTE
  AND     COC.ATD_ATE_ID            = CCP.ATD_ATE_ID
  JOIN    TB_CAD_PAC_PACIENTE         PAC
  ON      PAC.CAD_PAC_ID_PACIENTE   = CCP.CAD_PAC_ID_PACIENTE
  JOIN    TB_CAD_CNV_CONVENIO         CNV
  ON      PAC.CAD_CNV_ID_CONVENIO   = CNV.CAD_CNV_ID_CONVENIO
  JOIN    TB_CAD_PES_PESSOA           PES
  ON      PAC.CAD_PES_ID_PESSOA     = PES.CAD_PES_ID_PESSOA
  LEFT JOIN TB_FAT_NOF_NOTA_FISCAL    NOF
  ON      NOF.FAT_NOF_ID            = CCP.FAT_NOF_ID
  LEFT JOIN TB_ATD_INA_INT_ALTA INA ON INA.ATD_ATE_ID = CCP.ATD_ATE_ID
  WHERE  (CCP.FAT_CCP_FL_STATUS = 'A')
  AND    (COC.FAT_COC_FL_STATUS = 'A')
  AND    (pFATURADO IS NOT NULL AND CCP.FAT_NOF_ID IS NOT NULL
        OR pLOTEGERADO IS NOT NULL AND CCP.FAT_CCP_FL_FATURADA = 'S' AND CCP.FAT_NOF_ID IS NULL)
  AND    (pCAD_UNI_ID_UNIDADE IS NULL OR ATE.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
  AND    (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
  AND    (pCAD_SET_ID IS NULL OR ATE.CAD_SET_ID = pCAD_SET_ID)
  AND    (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
  AND    (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)
  AND    (pATD_ATE_TP_PACIENTE_I IS not NULL and ATE.atd_ate_tp_paciente = 'I'
   OR    pATD_ATE_TP_PACIENTE_E IS NOT NULL AND ATE.atd_ate_tp_paciente = 'E'
   OR    pATD_ATE_TP_PACIENTE_A IS NOT NULL AND ATE.atd_ate_tp_paciente = 'A'
   OR    pATD_ATE_TP_PACIENTE_U IS NOT NULL AND ATE.atd_ate_tp_paciente = 'U')
  AND    (pFAT_CCP_MES_FAT IS NULL OR CCP.FAT_CCP_MES_FAT = pFAT_CCP_MES_FAT)
  AND    (pFAT_CCP_ANO_FAT IS NULL OR CCP.FAT_CCP_ANO_FAT = pFAT_CCP_ANO_FAT)
 AND (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and CNV.CAD_TPE_CD_CODIGO = 'ACS'
   OR pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'PA'
   OR pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'SP'
   OR pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'FU'
   OR pCAD_PLA_CD_TIPOPLANO_NP IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = 'NP')
  ORDER   BY ATE.ATD_ATE_DT_ATENDIMENTO, PES.CAD_PES_NM_PESSOA;
  io_cursor := v_cursor;
END PRC_FAT_REL_PAC_FAT_CONV_ANAL;
