create or replace procedure sgs.PRC_INT_REL_FAIXA_ETARIA
  (
pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
pATD_ATE_HR_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pFAIXA_ETARIA_INI varchar2 default null,
pFAIXA_ETARIA_FIM varchar2 default null,
pPERMANENCIA_INI varchar2 default null,
pPERMANENCIA_FIM varchar2 default null,
pEVOLUCAO varchar2 default null,
pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE ,
pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE ,
pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
pCAD_SET_NR_ANDAR IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pCAD_QLE_TP_QUARTO_LEITO IN TB_CAD_QLE_QUARTO_LEITO.CAD_QLE_TP_QUARTO_LEITO%TYPE DEFAULT NULL,
pTIS_TIN_CD_INTER IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
pTIS_TRI_CD_TP_REGINT IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
pCAD_CID_CD_CID10 IN TB_CAD_CID_CID10.CAD_CID_CD_CID10%TYPE DEFAULT NULL,
pTIS_TAC_CD_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%TYPE DEFAULT NULL,
pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
pCAD_PES_TP_SEXO IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
   io_cursor              OUT PKG_CURSOR.t_cursor) is
  /********************************************************************
  *    Procedure: PRC_INT_REL_FAIXA_ETARIA
  *
  *    Data Criacao:  22/06/2010   Por: pedro
  *    Data Alteracao:           Por:
  *
  *    Funcao: Popula o Relatorio de  Pacientes Internados POR FAIXA ETARIA
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
begin
  OPEN v_cursor FOR
     select
              SETOR.CAD_SET_DS_SETOR,
              NVL(FNC_INT_QTD_UTI(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, null, 14,pPERMANENCIA_INI,pPERMANENCIA_FIM,pEVOLUCAO,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, SETOR.CAD_SET_ID, pCAD_SET_NR_ANDAR, pATD_AIC_TP_SITUACAO_PAC, null,
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO ),0) total_idade_15_menos,
              NVL( FNC_INT_QTD_UTI(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 15, 29,pPERMANENCIA_INI,pPERMANENCIA_FIM,pEVOLUCAO,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, SETOR.CAD_SET_ID, pCAD_SET_NR_ANDAR, pATD_AIC_TP_SITUACAO_PAC, null,
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO ),0) total_idade_15_29,
              NVL( FNC_INT_QTD_UTI(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 30, 44,pPERMANENCIA_INI,pPERMANENCIA_FIM,pEVOLUCAO,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, SETOR.CAD_SET_ID, pCAD_SET_NR_ANDAR, pATD_AIC_TP_SITUACAO_PAC, null,
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO ),0) total_idade_30_44,
              NVL( FNC_INT_QTD_UTI(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 45, 59,pPERMANENCIA_INI,pPERMANENCIA_FIM,pEVOLUCAO,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, SETOR.CAD_SET_ID, pCAD_SET_NR_ANDAR, pATD_AIC_TP_SITUACAO_PAC, null,
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO ),0) total_idade_45_59,
              NVL(FNC_INT_QTD_UTI(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 60, 74,pPERMANENCIA_INI,pPERMANENCIA_FIM,pEVOLUCAO,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, SETOR.CAD_SET_ID, pCAD_SET_NR_ANDAR, pATD_AIC_TP_SITUACAO_PAC, null,
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO ),0) total_idade_60_74,
              NVL(FNC_INT_QTD_UTI(pATD_ATE_DT_ATENDIMENTO_INI, pATD_ATE_DT_ATENDIMENTO_FIM, pATD_ATE_HR_ATENDIMENTO_INI,
              pATD_ATE_HR_ATENDIMENTO_FIM, pATD_ATE_FL_CARATER_SOLIC_U, pATD_ATE_FL_CARATER_SOLIC_E, 75, null,pPERMANENCIA_INI,pPERMANENCIA_FIM,pEVOLUCAO,
              pCAD_UNI_ID_UNIDADE, pCAD_LAT_ID_LOCAL_ATENDIMENTO, SETOR.CAD_SET_ID, pCAD_SET_NR_ANDAR, pATD_AIC_TP_SITUACAO_PAC, null,
              pCAD_QLE_TP_QUARTO_LEITO, pTIS_TIN_CD_INTER, pTIS_TRI_CD_TP_REGINT, pCAD_PLA_CD_TIPOPLANO_GB, pCAD_PLA_CD_TIPOPLANO_PL,
              pCAD_PLA_CD_TIPOPLANO_FU, pCAD_PLA_CD_TIPOPLANO_NP, pCAD_PLA_CD_TIPOPLANO_PA, pCAD_PLA_CD_TIPOPLANO_SP, pCAD_PRD_ID,pCAD_CID_CD_CID10,
              pTIS_TAC_CD_TIPO_ACOMODACAO, pTIS_CBO_CD_CBOS, pCAD_PRO_ID_PROF_EXEC, pCAD_PES_TP_SEXO, pCAD_CNV_ID_CONVENIO,
              pCAD_PLA_ID_PLANO ),0) total_idade_75_mais
  FROM      TB_CAD_SET_SETOR                   SETOR
  JOIN      TB_CAD_UNI_UNIDADE                 UNI
  ON        UNI.CAD_UNI_ID_UNIDADE           = SETOR.CAD_UNI_ID_UNIDADE
  JOIN      TB_CAD_LAT_LOCAL_ATENDIMENTO       LAT
  ON        LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
  WHERE     UNI.CAD_UNI_ID_UNIDADE           = pCAD_UNI_ID_UNIDADE
  AND       LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
  AND       (pCAD_SET_ID IS NULL OR SETOR.CAD_SET_ID = pCAD_SET_ID)
  AND       SETOR.CAD_SET_FL_PERMITEINTERN_OK = 'S'
  ;
  io_cursor := v_cursor;
end PRC_INT_REL_FAIXA_ETARIA;
/
