create or replace procedure sgs.PRC_MTMD_MOV_ESTOQUE_MES_UNI_S
(
     pMTMD_MOV_MES IN TB_MTMD_MOV_ESTOQUE_MES.MTMD_MOV_MES%type DEFAULT NULL,
     pMTMD_MOV_ANO IN TB_MTMD_MOV_ESTOQUE_MES.MTMD_MOV_ANO%type DEFAULT NULL,
     pCAD_MTMD_FILIAL_ID IN TB_MTMD_MOV_ESTOQUE_MES.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
     pRETIRAR_SANTOS IN NUMBER DEFAULT NULL, -- 0 ou 1 (Retira Unidades Santos e Amb Santos da query)
     io_cursor OUT PKG_CURSOR.t_cursor
) is
/********************************************************************
*    Procedure: PRC_MTMD_MOV_ESTOQUE_MES_UNI_S
*
*    Data Criacao: 	 01/2011     Por: RICARDO COSTA  
*    Data Alteração: 24/03/2011  Por: André Souza Monaco
*         Alteração: Adição do parâmetro pRETIRAR_SANTOS
*
*    Funcao: Relatorio de fechamento 29 de consumo  (por grupo/unidade)
*******************************************************************/
  dDataIni DATE;
  dDataFim DATE;
  sMes     VARCHAR2(2);
  v_cursor PKG_CURSOR.t_cursor;
begin
  IF (  LENGTH(TO_CHAR(pMTMD_MOV_MES)) = 1 ) THEN
     sMes := '0'||TO_CHAR(pMTMD_MOV_MES);  
  ELSE
     sMes := TO_CHAR(pMTMD_MOV_MES);     
  END IF;
  dDataIni := TO_DATE( '01'||TO_CHAR(sMes)||TO_CHAR(pMTMD_MOV_ANO)||' 0000','DDMMYYYY HH24MI');
  dDatafIM := TO_DATE( TO_CHAR(LAST_DAY(dDataIni),'DDMMYYYY')||' 0000','DDMMYYYY HH24MI');
  OPEN v_cursor FOR
  SELECT EST_DIA.MTMD_MOV_DATA,
       EST_DIA.CAD_UNI_ID_UNIDADE,
       UNI.CAD_UNI_DS_UNIDADE,
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,1,EST_DIA.VLR_SAIDA,0))   DROG_MED,    --1 
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,61,EST_DIA.VLR_SAIDA,0))  PROTESE,     --61
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,4,EST_DIA.VLR_SAIDA,0))   ALIMENTO,    --4
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,11,EST_DIA.VLR_SAIDA,0))  COPA,        --11
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,5,EST_DIA.VLR_SAIDA,0))   IMPRES,      --5 
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,6,EST_DIA.VLR_SAIDA,0))   MAT_MED_HOSP,--6   
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,12,EST_DIA.VLR_SAIDA,0))   HIGIE,      -- 12
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,8,EST_DIA.VLR_SAIDA,0))    MANUTEN,    -- 8
       SUM(DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,9,EST_DIA.VLR_SAIDA,0))    OLEO,       -- 9         
       --SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,2,DIA.MTMD_VALOR_SAIDA,0))  SANGUE,   --2
       SUM(
            CASE 
               WHEN EST_DIA.CAD_MTMD_GRUPO_ID NOT IN (1,61,4,11,5,6,12,8,9) THEN
                  EST_DIA.VLR_SAIDA
               ELSE
                  0
            END
          ) OUTROS,
       SUM(
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,1,EST_DIA.VLR_SAIDA,0))+ 
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,61,EST_DIA.VLR_SAIDA,0))+          
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,4,EST_DIA.VLR_SAIDA,0))+
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,11,EST_DIA.VLR_SAIDA,0))+
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,5,EST_DIA.VLR_SAIDA,0))+
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,6,EST_DIA.VLR_SAIDA,0))+
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,12,EST_DIA.VLR_SAIDA,0))+
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,8,EST_DIA.VLR_SAIDA,0))+
          (DECODE(EST_DIA.CAD_MTMD_GRUPO_ID,9,EST_DIA.VLR_SAIDA,0))+
          --(DECODE(DIA.CAD_MTMD_GRUPO_ID,2,DIA.MTMD_VALOR_SAIDA,0))+
          (
               CASE 
                  WHEN EST_DIA.CAD_MTMD_GRUPO_ID NOT IN (1,61,4,11,5,6,12,8,9) THEN
                     EST_DIA.VLR_SAIDA
                  ELSE
                     0
               END
          )                 
       ) TOTAL
  FROM
  (    
  SELECT EST_DIA.MTMD_MOV_DATA, 
         EST_DIA.CAD_UNI_ID_UNIDADE,
         EST_DIA.CAD_MTMD_GRUPO_ID,
         SUM(EST_DIA.MTMD_VALOR_SAIDA)    VLR_SAIDA
  FROM
  (SELECT DIAP.MTMD_MOV_DATA,         
          DIAP.CAD_UNI_ID_UNIDADE, 
          DIAP.CAD_MTMD_GRUPO_ID,
          MTMD.CAD_MTMD_ID,        
          MTMD.CAD_MTMD_NOMEFANTASIA DESCRICAO,         
          SUM(
              (CASE
               WHEN DIAP.CAD_MTMD_SUBTP_ID NOT IN (15) THEN DIAP.MTMD_VALOR_SAIDA
               ELSE 0
               END )              
             ) MTMD_VALOR_SAIDA
  FROM TB_CAD_MTMD_MAT_MED MTMD,
       TB_MTMD_MOV_ESTOQUE_DIA DIAP,
       (
         SELECT *
         FROM TB_MTMD_MOV_ESTOQUE_DIA
         WHERE MTMD_MOV_DATA                = dDataIni
         AND   (pCAD_MTMD_FILIAL_ID IS NULL OR CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID)
         AND   CAD_LAT_ID_LOCAL_ATENDIMENTO = 33
         AND   CAD_UNI_ID_UNIDADE           = 244
         AND   CAD_SET_ID                   = 29       
         AND   CAD_MTMD_TPMOV_ID            = 0
         AND   CAD_MTMD_SUBTP_ID            = 0
       ) LINHA_ZERO,
       (
         SELECT *
         FROM TB_MTMD_MOV_ESTOQUE_DIA
         WHERE CAD_MTMD_TPMOV_ID            = 1
         AND   CAD_MTMD_SUBTP_ID            = 1
         AND   MTMD_MOV_DATA >= dDataIni
         AND   MTMD_MOV_DATA <= dDatafIM
         AND   (pCAD_MTMD_FILIAL_ID IS NULL OR CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID)
         --AND   MTMD_VALOR_ENTRADA != 0
         --AND   MTMD_QTDE_ENTRADA > 0
       ) NOTAS                
  WHERE DIAP.MTMD_MOV_DATA >= dDataIni
  AND   DIAP.MTMD_MOV_DATA <= dDatafIM
  AND   DIAP.CAD_MTMD_FILIAL_ID             = pCAD_MTMD_FILIAL_ID
  AND  MTMD.CAD_MTMD_ID                    = DIAP.CAD_MTMD_ID
  AND  LINHA_ZERO.CAD_MTMD_ID(+)            = DIAP.CAD_MTMD_ID
  AND  LINHA_ZERO.CAD_MTMD_FILIAL_ID(+)     = DIAP.CAD_MTMD_FILIAL_ID
  AND  LINHA_ZERO.CAD_MTMD_GRUPO_ID(+)      = DIAP.CAD_MTMD_GRUPO_ID
  --AND  LINHA_ZERO.CAD_MTMD_SUBGRUPO_ID(+)         = DIAP.CAD_MTMD_SUBGRUPO_ID
  AND  NOTAS.MTMD_MOV_DATA(+)       = DIAP.MTMD_MOV_DATA
  AND  NOTAS.CAD_MTMD_ID(+)         = DIAP.CAD_MTMD_ID
  AND  NOTAS.CAD_MTMD_FILIAL_ID(+)  = DIAP.CAD_MTMD_FILIAL_ID
  AND  NOTAS.CAD_MTMD_GRUPO_ID(+)   = DIAP.CAD_MTMD_GRUPO_ID
  AND  NOTAS.CAD_MTMD_SUBGRUPO_ID(+) = DIAP.CAD_MTMD_SUBGRUPO_ID
  AND  NOTAS.CAD_MTMD_TPMOV_ID(+)       = DIAP.CAD_MTMD_TPMOV_ID
  AND  DIAP.CAD_MTMD_GRUPO_ID NOT IN (40,42) 
  AND  (NVL(pRETIRAR_SANTOS,0) = 0 OR DIAP.CAD_UNI_ID_UNIDADE NOT IN(244,248))--SANTOS E AMB SANTOS
  GROUP BY DIAP.MTMD_MOV_DATA,
           DIAP.CAD_UNI_ID_UNIDADE,
           DIAP.CAD_MTMD_GRUPO_ID,
           MTMD.CAD_MTMD_ID,   
           DIAP.CAD_MTMD_FILIAL_ID,  
           MTMD.CAD_MTMD_NOMEFANTASIA,
           LINHA_ZERO.MTMD_CUSTO_MEDIO_ANTERIOR,
           LINHA_ZERO.MTMD_SALDO_ATUAL,       
           LINHA_ZERO.MTMD_CUSTO_MEDIO_ATUAL,
           LINHA_ZERO.MTMD_VALOR_ATUAL,       
           LINHA_ZERO.MTMD_SALDO_ANTERIOR,
           LINHA_ZERO.MTMD_VALOR_ANTERIOR
  --HAVING SUM(NVL(DIAP.MTMD_SALDO_ANTERIOR,0)+NVL(DIAP.MTMD_SALDO_ATUAL,0)+ NVL(DIAP.MTMD_QTDE_ENTRADA,0)+ NVL(DIAP.MTMD_QTDE_SAIDA,0) + NVL(LINHA_ZERO.MTMD_VALOR_ANTERIOR,0) + NVL(DIAP.MTMD_VALOR_SAIDA,0) ) > 0
  ) EST_DIA
  GROUP BY EST_DIA.MTMD_MOV_DATA, 
           EST_DIA.CAD_UNI_ID_UNIDADE, 
           EST_DIA.CAD_MTMD_GRUPO_ID         
  ) EST_DIA,
  TB_CAD_UNI_UNIDADE UNI
  WHERE UNI.CAD_UNI_ID_UNIDADE = EST_DIA.CAD_UNI_ID_UNIDADE
  GROUP BY EST_DIA.MTMD_MOV_DATA, 
           EST_DIA.CAD_UNI_ID_UNIDADE,         
           UNI.CAD_UNI_DS_UNIDADE
  ORDER BY  UNI.CAD_UNI_DS_UNIDADE, EST_DIA.MTMD_MOV_DATA;
 /* 
SELECT DIA.MTMD_MOV_DATA,
       UNIDADE.CAD_UNI_DS_UNIDADE, 
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,1,DIA.MTMD_VALOR_SAIDA,0))  DROG_MED, --1 
--       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,2,DIA.MTMD_VALOR_SAIDA,0))  SANGUE,   --2
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,4,DIA.MTMD_VALOR_SAIDA,0))  ALIMENTO, -- 4
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,5,DIA.MTMD_VALOR_SAIDA,0))  IMPRES,   -- 5 
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,6,DIA.MTMD_VALOR_SAIDA,0))  MAT_MED_HOSP, --6       
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,8,DIA.MTMD_VALOR_SAIDA,0))  MANUTEN,    -- 8
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,9,DIA.MTMD_VALOR_SAIDA,0))  OLEO,       -- 9
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,11,DIA.MTMD_VALOR_SAIDA,0)) COPA,       -- 11
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,12,DIA.MTMD_VALOR_SAIDA,0)) HIGIE,      -- 12
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,61,DIA.MTMD_VALOR_SAIDA,0)) PROTESE,    -- 61
       SUM(
            CASE 
               WHEN DIA.CAD_MTMD_GRUPO_ID NOT IN (1,4,5,6,8,9,11,12,61) THEN
                  DIA.MTMD_VALOR_SAIDA
               ELSE
                  0
            END
          ) OUTROS,
       SUM(
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,1,DIA.MTMD_VALOR_SAIDA,0))+ 
--          (DECODE(DIA.CAD_MTMD_GRUPO_ID,2,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,4,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,5,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,6,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,8,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,9,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,11,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,12,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,61,DIA.MTMD_VALOR_SAIDA,0))+
          (
               CASE 
                  WHEN DIA.CAD_MTMD_GRUPO_ID NOT IN (1,4,5,6,8,9,11,12,61) THEN
                     DIA.MTMD_VALOR_SAIDA
                  ELSE
                     0
               END
          )                 
       ) TOTAL
FROM TB_MTMD_MOV_ESTOQUE_DIA      DIA,
     TB_CAD_SET_SETOR             SETOR,
     TB_CAD_LAT_LOCAL_ATENDIMENTO LOCA,
     TB_CAD_UNI_UNIDADE           UNIDADE
WHERE DIA.MTMD_MOV_DATA BETWEEN dDataIni AND dDatafIM
-- AND  ( ( pMTMD_MOV_TIPO = 2 AND DIA.CAD_UNI_ID_UNIDADE NOT IN (244,248) ) 
--     OR ( pMTMD_MOV_TIPO = 1 AND DIA.CAD_UNI_ID_UNIDADE IN (244,248) ) )
-- AND   DIA.MTMD_MOV_DATA BETWEEN TO_DATE('01112010 0000','DDMMYYYY HH24MI') AND TO_DATE('30112010 2359','DDMMYYYY HH24MI')
AND   DIA.CAD_MTMD_FILIAL_ID             = pCAD_MTMD_FILIAL_ID
AND   DIA.cad_mtmd_grupo_id              IN (1,4,5,6,8,9,11,12,61 )
AND   DIA.CAD_MTMD_TPMOV_ID              = 2 -- SO BAIXAS
AND   SETOR.CAD_SET_ID                   = DIA.CAD_SET_ID
AND   SETOR.CAD_UNI_ID_UNIDADE           = DIA.CAD_UNI_ID_UNIDADE
AND   SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO = DIA.CAD_LAT_ID_LOCAL_ATENDIMENTO
-- AND   SETOR.CAD_SET_ALMOX_CENTRAL        = 0
AND   UNIDADE.CAD_UNI_ID_UNIDADE         = SETOR.CAD_UNI_ID_UNIDADE  
AND   LOCA.CAD_LAT_ID_LOCAL_ATENDIMENTO  = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
GROUP BY DIA.MTMD_MOV_DATA, UNIDADE.CAD_UNI_DS_UNIDADE
ORDER BY  UNIDADE.CAD_UNI_DS_UNIDADE, DIA.MTMD_MOV_DATA;  
SELECT DIA.MTMD_MOV_DATA,
       UNIDADE.CAD_UNI_DS_UNIDADE, 
       DROGA.SAIDA TOT_DROGA,
       ALIM.SAIDA TOT_ALIM,
       IMP.SAIDA TOT_IMP,
       MATMED.SAIDA TOT_MATMED,
       MANU.SAIDA TOT_MANU,
       OLEO.SAIDA TOT_OLEO,
       COPACOZ.SAIDA TOT_COPA,
       HIG.SAIDA TOT_HIG,
       PROT.SAIDA TOT_PROT,
       ( NVL(DROGA.SAIDA,0) +  NVL(ALIM.SAIDA,0) + NVL(IMP.SAIDA,0) + NVL(MATMED.SAIDA,0) +  NVL(MANU.SAIDA,0) +
         NVL(OLEO.SAIDA,0)  +  NVL(COPACOZ.SAIDA,0) + NVL(HIG.SAIDA,0) + NVL(PROT.SAIDA,0)
       ) TO_GER,
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,1,DIA.MTMD_VALOR_SAIDA,0))  DROG_MED, --1 
--       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,2,DIA.MTMD_VALOR_SAIDA,0))  SANGUE,   --2
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,4,DIA.MTMD_VALOR_SAIDA,0))  ALIMENTO, -- 4
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,5,DIA.MTMD_VALOR_SAIDA,0))  IMPRES,   -- 5 
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,6,DIA.MTMD_VALOR_SAIDA,0))  MAT_MED_HOSP, --6       
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,8,DIA.MTMD_VALOR_SAIDA,0))  MANUTEN,    -- 8
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,9,DIA.MTMD_VALOR_SAIDA,0))  OLEO,       -- 9
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,11,DIA.MTMD_VALOR_SAIDA,0)) COPA,       -- 11
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,12,DIA.MTMD_VALOR_SAIDA,0)) HIGIE,      -- 12
       SUM(DECODE(DIA.CAD_MTMD_GRUPO_ID,61,DIA.MTMD_VALOR_SAIDA,0)) PROTESE,    -- 61
       SUM(0 ) OUTROS,
       SUM(
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,1,DIA.MTMD_VALOR_SAIDA,0))+ 
--          (DECODE(DIA.CAD_MTMD_GRUPO_ID,2,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,4,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,5,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,6,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,8,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,9,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,11,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,12,DIA.MTMD_VALOR_SAIDA,0))+
          (DECODE(DIA.CAD_MTMD_GRUPO_ID,61,DIA.MTMD_VALOR_SAIDA,0))+
          (
               CASE 
                  WHEN DIA.CAD_MTMD_GRUPO_ID NOT IN (1,4,5,6,8,9,11,12,61) THEN
                     DIA.MTMD_VALOR_SAIDA
                  ELSE
                     0
               END
          )                 
       ) TOTAL
FROM TB_MTMD_MOV_ESTOQUE_DIA      DIA,
     TB_CAD_SET_SETOR             SETOR,
     TB_CAD_LAT_LOCAL_ATENDIMENTO LOCA,
     TB_CAD_UNI_UNIDADE           UNIDADE,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 1 ) DROGA,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 4 ) ALIM,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 5 ) IMP,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 6 ) MATMED,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 8 ) MANU,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 9 ) OLEO,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 11 ) COPACOZ,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 12 ) HIG,
     ( SELECT SUM(MES.MTMD_VALOR_TOTAL_MES_SAIDA) SAIDA
              FROM SGS.TB_MTMD_MOV_ESTOQUE_MES MES
              WHERE MES.MTMD_MOV_MES           = pMTMD_MOV_MES
              AND   MES.MTMD_MOV_ANO           = pMTMD_MOV_ANO
              AND   MES.CAD_MTMD_FILIAL_ID     = pCAD_MTMD_FILIAL_ID
              AND   MES.CAD_MTMD_GRUPO_ID      = 61 ) PROT            
WHERE DIA.MTMD_MOV_DATA BETWEEN dDataIni AND dDatafIM
-- AND  ( ( pMTMD_MOV_TIPO = 2 AND DIA.CAD_UNI_ID_UNIDADE NOT IN (244,248) ) 
-- OR ( pMTMD_MOV_TIPO = 1 AND DIA.CAD_UNI_ID_UNIDADE IN (244,248) ) )
-- AND   DIA.MTMD_MOV_DATA BETWEEN TO_DATE('01112010 0000','DDMMYYYY HH24MI') AND TO_DATE('30112010 2359','DDMMYYYY HH24MI')
AND   DIA.CAD_MTMD_FILIAL_ID             = pCAD_MTMD_FILIAL_ID
AND   DIA.cad_mtmd_grupo_id              IN (1,2,4,5,6,8,9,11,12,61 )
AND   DIA.CAD_MTMD_TPMOV_ID              = 2 -- SO BAIXAS
AND   SETOR.CAD_SET_ID                   = DIA.CAD_SET_ID
AND   SETOR.CAD_UNI_ID_UNIDADE           = DIA.CAD_UNI_ID_UNIDADE
AND   SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO = DIA.CAD_LAT_ID_LOCAL_ATENDIMENTO
-- AND   SETOR.CAD_SET_ALMOX_CENTRAL        = 0
AND   UNIDADE.CAD_UNI_ID_UNIDADE         = SETOR.CAD_UNI_ID_UNIDADE  
AND   LOCA.CAD_LAT_ID_LOCAL_ATENDIMENTO  = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
GROUP BY DIA.MTMD_MOV_DATA, UNIDADE.CAD_UNI_DS_UNIDADE,
         DROGA.SAIDA,
         ALIM.SAIDA,
         IMP.SAIDA,
         MATMED.SAIDA,
         MANU.SAIDA,
         OLEO.SAIDA,
         COPACOZ.SAIDA,
         HIG.SAIDA,
         PROT.SAIDA
ORDER BY  UNIDADE.CAD_UNI_DS_UNIDADE, DIA.MTMD_MOV_DATA;
*/
      io_cursor := v_cursor;
end PRC_MTMD_MOV_ESTOQUE_MES_UNI_S;
