CREATE OR REPLACE PROCEDURE PRC_FAT_USC_CEC_CAC_S
(
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_USC_CEC_CAC_S
*    DATA ALTERACAO: 11/06/2010  POR: CAIO H. B. CHAGAS
*    ALTERAÇÃO:
*    DATA ALTERACAO: 06/09/2010  POR: André S. Monaco
*    ALTERAÇÃO: Adição do campo FAT_TCO_ID
*
*    DATA ALTERACAO: 27/09/2010  POR: Rafael Coimbra
*    ALTERAÇÃO: Adição do campo CAD_PRD_ID
*******************************************************************/
V_CURSOR PKG_CURSOR.T_CURSOR;
BEGIN
  OPEN V_CURSOR FOR

  SELECT  USC.ASS_USC_ID,
          UNI.CAD_UNI_ID_UNIDADE,
          UNI.CAD_UNI_DS_UNIDADE,
          LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO,
          LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
          SETOR.CAD_SET_ID,
          SETOR.CAD_SET_DS_SETOR,
          CBO.TIS_CBO_CD_CBOS,
          CBO.TIS_CBO_DS_CBOS || ' - ' || CBO.TIS_CBO_DS_CBOS_HAC AS TIS_CBO_DS_CBOS,
          EPP.AUX_EPP_CD_ESPECPROC,
          EPP.AUX_EPP_DS_DESCRICAO,
          MED.TIS_MED_CD_TABELAMEDICA,
          MED.TIS_MED_DS_TABELAMEDICA,
          USC.ASS_USC_DT_INICIO_VIGENCIA,
          USC.ASS_USC_DT_FIM_VIGENCIA,
          CEC.CAD_CEC_ID_CCUSTO,
          CEC.CAD_CEC_CD_CCUSTO || ' - ' || CEC.CAD_CEC_DS_CCUSTO CAD_CEC_DS_CCUSTO,
          CAC.CAD_CAC_ID_CLASSCONTABIL,
          CAC.CAD_CAC_CD_CLASSCONTABIL || ' - ' || CAC.CAD_CAC_DS_CLASSCONTABIL CAD_CAC_DS_CLASSCONTABIL,
          TAP.CAD_TAP_TP_ATRIBUTO,
          TAP.CAD_TAP_DS_ATRIBUTO,
          CAC.CAD_CAC_CD_RM_NUCLEUS,
          CAC.CAD_CAC_DS_RM_NUCLEUS,
          USC.ASS_USC_FL_STATUS,
          USC.FAT_TCO_ID,
          TCO.FAT_TCO_DS_COMANDA,
          USC.CAD_PRD_ID
  FROM    TB_ASS_USC_UNI_SET_CCUS_CLA USC
  JOIN    TB_CAD_UNI_UNIDADE UNI
  ON      USC.CAD_UNI_ID_UNIDADE = UNI.CAD_UNI_ID_UNIDADE
  JOIN    TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
  ON      USC.CAD_LAT_ID_LOCAL_ATENDIMENTO = LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO
  JOIN    TB_CAD_SET_SETOR SETOR
  ON      USC.CAD_SET_ID = SETOR.CAD_SET_ID
  LEFT    JOIN TB_TIS_CBO_CBOS CBO
  ON      USC.TIS_CBO_CD_CBOS = CBO.TIS_CBO_CD_CBOS
  LEFT    JOIN TB_AUX_EPP_ESPECPROC EPP
  ON      USC.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC
  AND     USC.TIS_MED_CD_TABELAMEDICA = EPP.TIS_MED_CD_TABELAMEDICA
  LEFT    JOIN TB_TIS_MED_TABELAMEDICA MED
  ON      USC.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA
  LEFT    JOIN  TB_CAD_CEC_CENTRO_CUSTO CEC
  ON      USC.CAD_CEC_ID_CCUSTO = CEC.CAD_CEC_ID_CCUSTO
  LEFT    JOIN  TB_CAD_CAC_CLASSIF_CONTAB CAC
  ON      USC.CAD_CAC_ID_CLASSCONTABIL = CAC.CAD_CAC_ID_CLASSCONTABIL
  LEFT    JOIN TB_CAD_TAP_TP_ATRIB_PRODUTO TAP
  ON      USC.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
  LEFT    JOIN TB_FAT_TCO_TIPO_COMANDA TCO
  ON      USC.FAT_TCO_ID = TCO.FAT_TCO_ID
  WHERE   (pCAD_UNI_ID_UNIDADE IS NULL OR USC.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
  AND     (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR USC.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
  AND     (pCAD_SET_ID IS NULL OR USC.CAD_SET_ID = pCAD_SET_ID);

io_cursor := v_cursor;
end PRC_FAT_USC_CEC_CAC_S;
