create or replace procedure PRC_CAD_SET_SETOR_ALMOX_S
  (
     pCAD_SET_SETOR_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_SETOR_ALMOX%type,
     pCAD_SET_UNIDADE_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_UNIDADE_ALMOX%type,
     pCAD_SET_LOCAL_ALMOX IN TB_CAD_SET_SETOR.CAD_SET_LOCAL_ALMOX%type,
     io_cursor OUT PKG_CURSOR.t_cursor
  ) 
  is
  v_cursor PKG_CURSOR.t_cursor;
  -- Seleciona todos os setores que são abastecidos pelo centro de dispensação
  begin
    OPEN v_cursor FOR
    SELECT	
       SETOR.CAD_SET_ID,
       SETOR.CAD_UNI_ID_UNIDADE,
       SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO,
       UNIDADE.CAD_UNI_DS_UNIDADE,
       LOC.CAD_LAT_DS_LOCAL_ATENDIMENTO,
       SETOR.CAD_SET_DS_SETOR
    FROM TB_CAD_SET_SETOR SETOR LEFT JOIN         
         TB_CAD_UNI_UNIDADE UNIDADE ON UNIDADE.CAD_UNI_ID_UNIDADE = SETOR.CAD_UNI_ID_UNIDADE LEFT JOIN
         TB_CAD_LAT_LOCAL_ATENDIMENTO LOC ON LOC.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
    WHERE SETOR.CAD_SET_SETOR_ALMOX = pCAD_SET_SETOR_ALMOX
    AND SETOR.CAD_SET_UNIDADE_ALMOX = pCAD_SET_UNIDADE_ALMOX
    AND SETOR.CAD_SET_LOCAL_ALMOX = pCAD_SET_LOCAL_ALMOX    

    ORDER BY UNIDADE.CAD_UNI_DS_UNIDADE, LOC.CAD_LAT_DS_LOCAL_ATENDIMENTO, SETOR.CAD_SET_DS_SETOR;
    io_cursor := v_cursor;
  end PRC_CAD_SET_SETOR_ALMOX_S;
 