CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_REC_CENTRO_CUSTO"
(
    pCAD_UNI_ID_UNIDADE IN TB_FAT_CCP_CONTA_CONS_PARC.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_FAT_CCP_CONTA_CONS_PARC.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE DEFAULT NULL,
    pFAT_CCP_MES_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_COMPET%TYPE DEFAULT NULL,
    pFAT_CCP_ANO_COMPET IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_COMPET%TYPE DEFAULT NULL,
    pCAD_CEC_ID_CCUSTO IN TB_CAD_CEC_CENTRO_CUSTO.CAD_CEC_ID_CCUSTO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I IN TB_FAT_CCP_CONTA_CONS_PARC.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_E IN TB_FAT_CCP_CONTA_CONS_PARC.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_A IN TB_FAT_CCP_CONTA_CONS_PARC.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_U IN TB_FAT_CCP_CONTA_CONS_PARC.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_TAX IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_DIA IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_MAT IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_MED IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_HM  IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_EXA IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_GAS IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    pCAD_TAP_TP_ATRIBUTO_PAC IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_REC_CENTRO_CUSTO
*
*    Data Alteracao: 05/09/2013  Por: Pedro
*
*    Alteração: CUSTO
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
BEGIN
  OPEN v_cursor FOR
    SELECT  CEC.CAD_CEC_ID_CCUSTO,
            CEC.CAD_CEC_CD_CCUSTO,
            CEC.CAD_CEC_DS_CCUSTO,
            PRD.CAD_PRD_CD_CODIGO,
            PRD.CAD_PRD_DS_DESCRICAO,
            SUM(CCI.FAT_CCI_QT_CONSUMO) QT_CONSUMO,
            SUM(CCI.FAT_CCI_VL_FATURADO) VALOR_TOTAL
    FROM    TB_FAT_CCI_CONTA_CONSU_ITEM  CCI
    JOIN    TB_CAD_CEC_CENTRO_CUSTO      CEC
    ON      CEC.CAD_CEC_ID_CCUSTO      = CCI.CAD_CEC_ID_CCUSTO
    JOIN    TB_CAD_PRD_PRODUTO           PRD
    ON      CCI.CAD_PRD_ID             = PRD.CAD_PRD_ID
   -- JOIN    TB_ATD_ATE_ATENDIMENTO       ATE
   -- ON      ATE.ATD_ATE_ID             = CCI.ATD_ATE_ID
    JOIN    TB_FAT_CCP_CONTA_CONS_PARC   CCP
    ON      CCI.FAT_CCP_ID             = CCP.FAT_CCP_ID
    AND     CCI.ATD_ATE_ID             = CCP.ATD_ATE_ID
    AND     CCI.CAD_PAC_ID_PACIENTE    = CCP.CAD_PAC_ID_PACIENTE
    AND     CCI.FAT_COC_ID             = CCP.FAT_COC_ID
    WHERE   (CCI.FAT_CCI_FL_STATUS = 'A')
    AND     (CCI.FAT_CCI_FL_PACOTE = 'N' OR CCI.FAT_CCI_FL_PACOTE IS NULL)
    AND     (CCP.FAT_CCP_FL_STATUS = 'A')
    AND     (pCAD_UNI_ID_UNIDADE IS NULL OR CCP.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
    AND     (pCAD_LAT_ID_LOCAL_ATENDIMENTO IS NULL OR CCP.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
   -- AND     (pCAD_SET_ID IS NULL OR ATE.CAD_SET_ID = pCAD_SET_ID)
    AND     (CCP.FAT_CCP_MES_FAT = pFAT_CCP_MES_FAT)
    AND     (CCP.FAT_CCP_ANO_FAT = pFAT_CCP_ANO_FAT)
    AND     (pFAT_CCP_MES_COMPET IS NULL OR CCP.FAT_CCP_MES_COMPET = pFAT_CCP_MES_COMPET)
    AND     (pFAT_CCP_ANO_COMPET IS NULL OR CCP.FAT_CCP_ANO_COMPET = pFAT_CCP_ANO_COMPET)
    AND     (pCAD_CEC_ID_CCUSTO IS NULL OR CEC.CAD_CEC_ID_CCUSTO = pCAD_CEC_ID_CCUSTO)
    AND     (pATD_ATE_TP_PACIENTE_I IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = 'I'
         OR pATD_ATE_TP_PACIENTE_A IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = 'A'
         OR pATD_ATE_TP_PACIENTE_U IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = 'U'
         OR pATD_ATE_TP_PACIENTE_E IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = 'E')
    and     (pCAD_TAP_TP_ATRIBUTO_TAX IS not NULL and cci.cad_tap_tp_atributo = 'TAX'
        OR pCAD_TAP_TP_ATRIBUTO_DIA IS NOT NULL AND cci.cad_tap_tp_atributo = 'DIA'
        OR pCAD_TAP_TP_ATRIBUTO_MAT IS NOT NULL AND cci.cad_tap_tp_atributo = 'MAT'
        OR pCAD_TAP_TP_ATRIBUTO_MED IS NOT NULL AND cci.cad_tap_tp_atributo = 'MED'
        OR pCAD_TAP_TP_ATRIBUTO_HM IS NOT NULL AND cci.cad_tap_tp_atributo = 'HM'
        OR pCAD_TAP_TP_ATRIBUTO_EXA IS NOT NULL AND cci.cad_tap_tp_atributo = 'EXA'
        OR pCAD_TAP_TP_ATRIBUTO_GAS IS NOT NULL AND cci.cad_tap_tp_atributo = 'GAS'
        OR pCAD_TAP_TP_ATRIBUTO_PAC IS NOT NULL AND cci.cad_tap_tp_atributo = 'PAC')     
    GROUP   BY CEC.CAD_CEC_ID_CCUSTO,
            CEC.CAD_CEC_CD_CCUSTO,
            CEC.CAD_CEC_DS_CCUSTO,
            PRD.CAD_PRD_CD_CODIGO,
            PRD.CAD_PRD_DS_DESCRICAO
    ORDER   BY PRD.CAD_PRD_DS_DESCRICAO;
  io_cursor := v_cursor;
END PRC_FAT_REL_REC_CENTRO_CUSTO;
 