CREATE OR REPLACE PROCEDURE "PRC_TIS_TP_ACOMOD_RMT_S"
  (
     pTIS_TAC_CD_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%type DEFAULT NULL,
     pTIS_TAC_DS_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_DS_TIPO_ACOMODACAO%type DEFAULT NULL,
     pTIS_TAC_PC_ACOMODACAO_HM IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_PC_ACOMODACAO_HM%type DEFAULT NULL,
     pTIS_TAC_DT_ULTIMA_ATUALIZACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_TIS_TAC_TIPO_ACOMODACAO.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pTIS_TAC_FL_PERM_DIF_CLASSE IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_FL_PERM_DIF_CLASSE%type DEFAULT NULL,
     pTIS_TAC_FL_UTILIZA_REPASSE IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_FL_UTILIZA_REPASSE%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_TIS_TP_ACOMOD_RMT_S
  *
  *    Data Criacao:  data da  criação   Por: Nome do Analista
  *    Data Alteracao: data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT
       TIS_TAC_CD_TIPO_ACOMODACAO,
       TIS_TAC_DS_TIPO_ACOMODACAO,
       TIS_TAC_PC_ACOMODACAO_HM,
       TIS_TAC_DT_ULTIMA_ATUALIZACAO,
       SEG_USU_ID_USUARIO,
       TIS_TAC_FL_PERM_DIF_CLASSE,
       TIS_TAC_FL_UTILIZA_REPASSE
    FROM TB_TIS_TAC_TIPO_ACOMODACAO
    WHERE
        (pTIS_TAC_CD_TIPO_ACOMODACAO is null OR TIS_TAC_CD_TIPO_ACOMODACAO = pTIS_TAC_CD_TIPO_ACOMODACAO) AND
        (pTIS_TAC_DS_TIPO_ACOMODACAO is null OR TIS_TAC_DS_TIPO_ACOMODACAO = pTIS_TAC_DS_TIPO_ACOMODACAO) AND
        (pTIS_TAC_PC_ACOMODACAO_HM is null OR TIS_TAC_PC_ACOMODACAO_HM = pTIS_TAC_PC_ACOMODACAO_HM) AND
        (pTIS_TAC_DT_ULTIMA_ATUALIZACAO is null OR TIS_TAC_DT_ULTIMA_ATUALIZACAO = pTIS_TAC_DT_ULTIMA_ATUALIZACAO) AND
        (pSEG_USU_ID_USUARIO is null OR SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND
        (pTIS_TAC_FL_PERM_DIF_CLASSE is null OR TIS_TAC_FL_PERM_DIF_CLASSE = pTIS_TAC_FL_PERM_DIF_CLASSE) AND
        (pTIS_TAC_FL_UTILIZA_REPASSE is null OR TIS_TAC_FL_UTILIZA_REPASSE = pTIS_TAC_FL_UTILIZA_REPASSE);
    io_cursor := v_cursor;
  end PRC_TIS_TP_ACOMOD_RMT_S;
 