CREATE OR REPLACE PROCEDURE "PRC_CAD_MTMD_INDICE_ROTA_R" (
   pCAD_MTMD_FILIAL_ID           IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_FILIAL_ID%type DEFAULT NULL,
   pCAD_MTMD_GRUPO_ID            IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_GRUPO_ID%type DEFAULT NULL,
   pCAD_MTMD_SUBGRUPO_ID         IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_SUBGRUPO_ID%type DEFAULT NULL,
   pCAD_MTMD_ID                  IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_ID%type DEFAULT NULL,
   pDATA_DE                      IN DATE,
   pDATA_ATE                     IN DATE,
   io_cursor                     OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_CAD_MTMD_GRUPO_S
*
*    Data Criacao:  07/01/2009   Por: Andre Souza Monaco
*    Data Alterac?o:30/03/2015   Por: Andre S. Monaco
*         Alterac?o:Busca do campo CAD_MTMD_PRIATI_ID na TB_CAD_MTMD_MAT_MED,
*                   ref. a coluna PA_MOV_ID da query
*
*    Funcao: Query para relatorio de indice de rotatividade de produtos
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
BEGIN
  OPEN v_cursor FOR
  SELECT PRODUTO.CAD_MTMD_ID,
         --FNC_MTMD_PRINCIPIO_ATIVO (PRODUTO.CAD_MTMD_ID) PA_ID,
         (SELECT NVL(MAX(CAD_MTMD_PRIATI_ID), 0)
             FROM TB_CAD_MTMD_SIMILAR SIMILAR
            WHERE CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                  CAD_FL_ATIVO = 1 AND
                 (SELECT COUNT(S.CAD_MTMD_PRIATI_ID)
                   FROM TB_CAD_MTMD_SIMILAR S
                  WHERE S.CAD_MTMD_PRIATI_ID = SIMILAR.CAD_MTMD_PRIATI_ID AND
                        CAD_FL_ATIVO = 1) > 1) PA_ID,
         DECODE(NVL(pCAD_MTMD_GRUPO_ID, 0), 1, -- QUANDO FILTRAR MEDICAMENTOS, BUSCAR SIMILARES COM MAIS DE 1 REGISTRO PARA AGRUPAR RELATORIO
                 (SELECT NVL(MAX(CAD_MTMD_PRIATI_ID), 0)
                   FROM TB_CAD_MTMD_SIMILAR SIMILAR
                  WHERE CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                        CAD_FL_ATIVO = 1 AND
                       (SELECT COUNT(MOV.CAD_MTMD_ID)
                         FROM TB_MTMD_MOV_MES MOV JOIN TB_CAD_MTMD_MAT_MED M ON M.CAD_MTMD_ID = MOV.CAD_MTMD_ID
                        WHERE MOV.MTMD_MOV_MES = TO_NUMBER(TO_CHAR(pDATA_DE,'MM'))  AND
                              MOV.MTMD_MOV_ANO = TO_NUMBER(TO_CHAR(pDATA_DE,'YYYY'))  AND
                              MOV.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID AND
                              M.CAD_MTMD_GRUPO_ID = 1 AND M.TIS_MED_CD_TABELAMEDICA = '96' AND
                              M.CAD_MTMD_PRIATI_ID = SIMILAR.CAD_MTMD_PRIATI_ID) > 1),
                              --FNC_MTMD_PRINCIPIO_ATIVO(M.CAD_MTMD_ID) = SIMILAR.CAD_MTMD_PRIATI_ID) > 1),
                   0) PA_MOV_ID,
         PRODUTO.CAD_MTMD_CODMNE,
         FNC_MTMD_SOUNDALIKE(PRODUTO.CAD_MTMD_NOMEFANTASIA,PRODUTO.CAD_MTMD_GRUPO_ID) CAD_MTMD_NOMEFANTASIA,
         PRODUTO.CAD_MTMD_GRUPO_ID,
         PRODUTO.CAD_MTMD_UNID_COMPRA_DS UNIDADE_MEDIDA,
         ROUND(SUM(MOV.MTMD_QTDE_ENTRADA) / TO_NUMBER(TO_CHAR(pDATA_ATE,'DD')),2) QTDE_ENTRADA_DIA,
         SUM(MOV.MTMD_QTDE_ENTRADA) QTDE_ENTRADA,
         ROUND(SUM(MOV.MTMD_QTDE_SAIDA) / TO_NUMBER(TO_CHAR(pDATA_ATE,'DD')),2) QTDE_SAIDA_DIA,
         SUM(MOV.MTMD_QTDE_SAIDA) QTDE_SAIDA,
         --FNC_MTMD_ESTOQUE_CONTABIL(PRODUTO.CAD_MTMD_ID, MOV.CAD_MTMD_FILIAL_ID) ESTOQUE_CONTABIL_ATUAL,
         SUM(MOV.MTMD_MOV_SALDO) ESTOQUE_CONTABIL_ATUAL,
         TRUNC(FNC_MTMD_CALCULA_ROTATIVIDADE(PRODUTO.CAD_MTMD_ID,
                                             null,null,null,
                                             MOV.CAD_MTMD_FILIAL_ID,
                                             pDATA_DE, null), 2) INDICE_ROTATIVIDADE,
         CASE WHEN (MOV.CAD_MTMD_FILIAL_ID = 2 AND PRODUTO.CAD_MTMD_GRUPO_ID IN (6,61)) THEN
            (SELECT C.MTMD_CUSTO_MEDIO FROM TB_MTMD_ESTOQUE_CONTABIL C
              WHERE C.CAD_MTMD_FILIAL_ID = 2 AND C.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID)
         ELSE
             FNC_MTMD_PRECO_PERIODO(PRODUTO.CAD_MTMD_ID,
                                    MOV.CAD_MTMD_FILIAL_ID,
                                    pDATA_DE,
                                    pDATA_ATE)
         END CUSTO_MEDIO,
         /*FNC_MTMD_PRECO_PERIODO(PRODUTO.CAD_MTMD_ID,
                                MOV.CAD_MTMD_FILIAL_ID,
                                pDATA_DE,
                                pDATA_ATE) CUSTO_MEDIO,*/
         FLOOR((((SELECT NVL(SUM(M.MTMD_QTDE_SAIDA), 0)
              FROM TB_MTMD_MOV_MES M
             WHERE M.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID AND
                   M.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                   M.MTMD_MOV_MES = TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -1),'MM')) AND
                   M.MTMD_MOV_ANO = TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -1),'YYYY'))) +
            (SELECT NVL(SUM(M.MTMD_QTDE_SAIDA), 0)
               FROM TB_MTMD_MOV_MES M
              WHERE M.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID AND
                    M.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                    M.MTMD_MOV_MES = TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -2),'MM')) AND
                    M.MTMD_MOV_ANO = TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -2),'YYYY'))) +
            (SELECT NVL(SUM(M.MTMD_QTDE_SAIDA), 0)
               FROM TB_MTMD_MOV_MES M
              WHERE M.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID AND
                    M.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                    M.MTMD_MOV_MES = TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -3),'MM')) AND
                    M.MTMD_MOV_ANO = TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE, -3),'YYYY'))))/3)) MEDIA_TRES_MESES,
         (SELECT NVL(SUM(L.MTMD_ESTLOC_QTDE),0)
          FROM TB_MTMD_ESTOQUE_LOCAL L, TB_CAD_SET_SETOR S
          WHERE S.CAD_SET_ID = L.CAD_SET_ID
          AND   S.CAD_LAT_ID_LOCAL_ATENDIMENTO = L.CAD_LAT_ID_LOCAL_ATENDIMENTO
          AND   S.CAD_UNI_ID_UNIDADE = L.CAD_UNI_ID_UNIDADE
          AND   S.CAD_SET_ALMOX_CENTRAL = 1
          AND   L.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID
          AND   L.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID) SALDO_ALMOX_CENTRAL,
          PRODUTO.CAD_MTMD_UNIDADE_COMPRA
        FROM TB_MTMD_MOV_MES   MOV,
             TB_CAD_MTMD_MAT_MED   PRODUTO
        WHERE  MOV.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID
        --AND    PRODUTO.CAD_MTMD_GRUPO_ID != 4 -- N?o trazer SND
        AND    (PRODUTO.CAD_MTMD_GRUPO_ID != 4 AND PRODUTO.CAD_MTMD_SUBGRUPO_ID != 942) -- ALIMENTOS NAO ESTOCAVEIS
        AND   (pCAD_MTMD_ID is null OR MOV.CAD_MTMD_ID = pCAD_MTMD_ID)
        AND   (pCAD_MTMD_FILIAL_ID is null OR MOV.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID)
        AND   (pCAD_MTMD_GRUPO_ID is null OR PRODUTO.CAD_MTMD_GRUPO_ID = pCAD_MTMD_GRUPO_ID)
        AND   (pCAD_MTMD_SUBGRUPO_ID is null OR PRODUTO.CAD_MTMD_SUBGRUPO_ID = pCAD_MTMD_SUBGRUPO_ID)
        AND   MOV.MTMD_MOV_MES = TO_NUMBER(TO_CHAR(pDATA_DE,'MM'))
        AND   MOV.MTMD_MOV_ANO = TO_NUMBER(TO_CHAR(pDATA_DE,'YYYY'))
        GROUP BY PRODUTO.CAD_MTMD_ID,
                 PRODUTO.CAD_MTMD_NOMEFANTASIA,
                 PRODUTO.CAD_MTMD_GRUPO_ID,
                 PRODUTO.CAD_MTMD_CODMNE,
                 PRODUTO.CAD_MTMD_UNID_COMPRA_DS,
                 MOV.CAD_MTMD_FILIAL_ID,
                 PRODUTO.CAD_MTMD_UNIDADE_COMPRA
        ORDER BY PA_MOV_ID, PRODUTO.CAD_MTMD_NOMEFANTASIA;
  /*IF ( TO_CHAR(SYSDATE,'MM') = to_char(pDATA_DE,'MM') ) THEN
      OPEN v_cursor FOR
      SELECT PRODUTO.CAD_MTMD_ID,
             PRODUTO.CAD_MTMD_CODMNE,
             PRODUTO.CAD_MTMD_NOMEFANTASIA,
             PRODUTO.CAD_MTMD_UNID_CONTROLE_DS UNIDADE_MEDIDA,
             ROUND(SUM(MOV.MTMD_QTDE_ENTRADA) / TO_NUMBER(TO_CHAR(SYSDATE,'DD')),2) QTDE_ENTRADA_DIA,
             SUM(MOV.MTMD_QTDE_ENTRADA) QTDE_ENTRADA,
             ROUND(SUM(MOV.MTMD_QTDE_SAIDA) / TO_NUMBER(TO_CHAR(SYSDATE,'DD')),2) QTDE_SAIDA_DIA,
             SUM(MOV.MTMD_QTDE_SAIDA) QTDE_SAIDA,
             FNC_MTMD_ESTOQUE_CONTABIL(PRODUTO.CAD_MTMD_ID, MOV.CAD_MTMD_FILIAL_ID) ESTOQUE_CONTABIL_ATUAL,
             TRUNC(FNC_MTMD_CALCULA_ROTATIVIDADE(PRODUTO.CAD_MTMD_ID,
                                                 null,null,null,
                                                 MOV.CAD_MTMD_FILIAL_ID,
                                                 pDATA_DE, null), 2) INDICE_ROTATIVIDADE
        FROM SGS.TB_MTMD_MOV_MES   MOV,
             TB_CAD_MTMD_MAT_MED   PRODUTO
        WHERE  MOV.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID
        AND   (pCAD_MTMD_ID is null OR MOV.CAD_MTMD_ID = pCAD_MTMD_ID)
        AND   (pCAD_MTMD_FILIAL_ID is null OR MOV.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID)
        AND   (pCAD_MTMD_GRUPO_ID is null OR PRODUTO.CAD_MTMD_GRUPO_ID = pCAD_MTMD_GRUPO_ID)
        AND   (pCAD_MTMD_SUBGRUPO_ID is null OR PRODUTO.CAD_MTMD_SUBGRUPO_ID = pCAD_MTMD_SUBGRUPO_ID)
        AND   MOV.MTMD_MOV_MES = TO_NUMBER(TO_CHAR(pDATA_DE,'MM')) AND MOV.MTMD_MOV_ANO = TO_NUMBER(TO_CHAR(pDATA_DE,'YYYY'))
        GROUP BY PRODUTO.CAD_MTMD_ID,
                 PRODUTO.CAD_MTMD_NOMEFANTASIA,
                 PRODUTO.CAD_MTMD_CODMNE,
                 PRODUTO.CAD_MTMD_UNID_CONTROLE_DS,
                 MOV.CAD_MTMD_FILIAL_ID
        ORDER BY PRODUTO.CAD_MTMD_NOMEFANTASIA;
  ELSE
      OPEN v_cursor FOR
      SELECT PRODUTO.CAD_MTMD_ID,
             PRODUTO.CAD_MTMD_CODMNE,
             PRODUTO.CAD_MTMD_NOMEFANTASIA,
             PRODUTO.CAD_MTMD_UNID_CONTROLE_DS UNIDADE_MEDIDA,
             ROUND(SUM(MOV.MTMD_QTDE_ENTRADA) / TO_NUMBER(TO_CHAR(Last_day(pDATA_DE),'DD')),2) QTDE_ENTRADA_DIA,
             SUM(MOV.MTMD_QTDE_ENTRADA) QTDE_ENTRADA,
             ROUND(SUM(MOV.MTMD_QTDE_SAIDA) / TO_NUMBER(TO_CHAR(Last_day(pDATA_DE),'DD')),2) QTDE_SAIDA_DIA,
             SUM(MOV.MTMD_QTDE_SAIDA) QTDE_SAIDA,
             NVL((SELECT E.MTMD_SALDO_ATUAL FROM TB_MTMD_MOV_ESTOQUE_DIA E
               WHERE E.MTMD_MOV_DATA = pDATA_DE AND
                     E.CAD_MTMD_FILIAL_ID = MOV.CAD_MTMD_FILIAL_ID AND
                     E.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                     E.CAD_MTMD_TPMOV_ID = 0 AND E.CAD_MTMD_SUBTP_ID = 0),0) ESTOQUE_CONTABIL_ATUAL,
             \*NVL((SELECT E.MTMD_CUSTO_MEDIO_ATUAL FROM TB_MTMD_MOV_ESTOQUE_DIA E
               WHERE E.MTMD_MOV_DATA = pDATA_DE AND
                     E.CAD_MTMD_FILIAL_ID = MOV.CAD_MTMD_FILIAL_ID AND
                     E.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID AND
                     E.CAD_MTMD_TPMOV_ID = 0 AND E.CAD_MTMD_SUBTP_ID = 0),0) PRECO_MEDIO_ATUAL,*\
             TRUNC(FNC_MTMD_CALCULA_ROTATIVIDADE(PRODUTO.CAD_MTMD_ID,
                                                 null,null,null,
                                                 MOV.CAD_MTMD_FILIAL_ID,
                                                 pDATA_DE, null), 2) INDICE_ROTATIVIDADE
        FROM TB_MTMD_MOV_ESTOQUE_DIA   MOV,
             TB_CAD_MTMD_MAT_MED       PRODUTO
        WHERE  MOV.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID
        AND   (pCAD_MTMD_ID is null OR MOV.CAD_MTMD_ID = pCAD_MTMD_ID)
        AND   (pCAD_MTMD_FILIAL_ID is null OR MOV.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID)
        AND   (pCAD_MTMD_GRUPO_ID is null OR PRODUTO.CAD_MTMD_GRUPO_ID = pCAD_MTMD_GRUPO_ID)
        AND   (pCAD_MTMD_SUBGRUPO_ID is null OR PRODUTO.CAD_MTMD_SUBGRUPO_ID = pCAD_MTMD_SUBGRUPO_ID)
        AND   MOV.MTMD_MOV_DATA >= pDATA_DE AND MOV.MTMD_MOV_DATA <= pDATA_ATE
        GROUP BY PRODUTO.CAD_MTMD_ID,
                 PRODUTO.CAD_MTMD_NOMEFANTASIA,
                 PRODUTO.CAD_MTMD_CODMNE,
                 PRODUTO.CAD_MTMD_UNID_CONTROLE_DS,
                 MOV.CAD_MTMD_FILIAL_ID
        ORDER BY PRODUTO.CAD_MTMD_NOMEFANTASIA;
  END IF;*/
  io_cursor := v_cursor;
  /*SELECT PRODUTO.CAD_MTMD_CODMNE,
         PRODUTO.CAD_MTMD_NOMEFANTASIA,
         FNC_MTMD_ESTOQUE_CONTABIL (MOV.CAD_MTMD_ID, MOV.CAD_MTMD_FILIAL_ID) ESTOQUE_CONTABIL_ATUAL,
         FNC_MTMD_PRECO_MEDIO (MOV.CAD_MTMD_ID, MOV.CAD_MTMD_FILIAL_ID)      PRECO_MEDIO_ATUAL,
         TRUNC(FNC_MTMD_CALCULA_ROTATIVIDADE(MOV.CAD_MTMD_ID,
                                             null,null,null,
                                             MOV.CAD_MTMD_FILIAL_ID,
                                             pDATA_DE, pDATA_ATE), 2)        INDICE_ROTATIVIDADE
  FROM TB_MTMD_MOV_MES           MOV,
       TB_CAD_MTMD_MAT_MED       PRODUTO
  WHERE  MOV.CAD_MTMD_ID = PRODUTO.CAD_MTMD_ID
  AND   (pCAD_MTMD_ID is null OR MOV.CAD_MTMD_ID = pCAD_MTMD_ID)
  AND   (pCAD_MTMD_FILIAL_ID is null OR MOV.CAD_MTMD_FILIAL_ID = pCAD_MTMD_FILIAL_ID)
  AND   (pCAD_MTMD_GRUPO_ID is null OR PRODUTO.CAD_MTMD_GRUPO_ID = pCAD_MTMD_GRUPO_ID)
  AND   (pCAD_MTMD_SUBGRUPO_ID is null OR PRODUTO.CAD_MTMD_SUBGRUPO_ID = pCAD_MTMD_SUBGRUPO_ID)
  AND   MOV.MTMD_MOV_DATA BETWEEN pDATA_DE AND pDATA_ATE
  GROUP BY PRODUTO.CAD_MTMD_ID,
           PRODUTO.CAD_MTMD_NOMEFANTASIA,
           PRODUTO.CAD_MTMD_CODMNE,
           MOV.CAD_MTMD_FILIAL_ID
  ORDER BY PRODUTO.CAD_MTMD_NOMEFANTASIA;*/
END PRC_CAD_MTMD_INDICE_ROTA_R;