create or replace PROCEDURE PRC_INT_REL_QTD_POR_SETOR
  (
pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_HR_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_HR_ATENDIMENTO%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_U IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pATD_ATE_FL_CARATER_SOLIC_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_FL_CARATER_SOLIC%TYPE DEFAULT NULL,
pFAIXA_ETARIA_INI varchar2 default null,
pFAIXA_ETARIA_FIM varchar2 default null,
pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE,
pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE,
pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
pCAD_SET_NR_ANDAR IN TB_CAD_SET_SETOR.CAD_SET_NR_ANDAR%TYPE DEFAULT NULL,
pATD_AIC_TP_SITUACAO_PAC IN TB_ATD_AIC_ATE_INT_COMPL.ATD_AIC_TP_SITUACAO_PAC%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_I IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pATD_ATE_TP_PACIENTE_E IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_TP_PACIENTE%TYPE DEFAULT NULL,
pCAD_QLE_TP_QUARTO_LEITO IN TB_CAD_QLE_QUARTO_LEITO.CAD_QLE_TP_QUARTO_LEITO%TYPE DEFAULT NULL,
pTIS_TIN_CD_INTER IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TIN_CD_INTERNACAO%TYPE DEFAULT NULL,
pTIS_TRI_CD_TP_REGINT IN TB_ATD_AIC_ATE_INT_COMPL.TIS_TRI_CD_REGINTENNACAO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
pCAD_PRD_ID IN TB_CAD_PRD_PRODUTO.CAD_PRD_ID%TYPE DEFAULT NULL,
pTIS_TAC_CD_TIPO_ACOMODACAO IN TB_TIS_TAC_TIPO_ACOMODACAO.TIS_TAC_CD_TIPO_ACOMODACAO%TYPE DEFAULT NULL,
pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
pCAD_PRO_ID_PROF_EXEC IN TB_CAD_PRO_PROFISSIONAL.CAD_PRO_ID_PROFISSIONAL%TYPE DEFAULT NULL,
pCAD_PES_TP_SEXO IN TB_CAD_PES_PESSOA.CAD_PES_TP_SEXO%TYPE DEFAULT NULL,
pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
pCAD_UNI_ID_UNID_PROC    IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNID_PROC%TYPE DEFAULT NULL,
   io_cursor              OUT PKG_CURSOR.t_cursor) is
  /********************************************************************
  *    Procedure: PRC_INT_REL_QTD_POR_SETOR
  *
  *    Data Criacao:    23/06/2010    Por: Pedro
  *    Data Alteracao:  10/09/2010    Por: Fabiola
  *    Data Alteracao:03/11/2011   Por:Eduardo Hyppolito
  *    Alterai??i??o: Campo Instituto Geriatria (LEFT JOIN BENEFICIARIO)
  *    Funcao: Popula o Relatorio de Censo de Ala ( Rel de pac. internados por Setor)
  *    Alteracao: Alterei a forma de recuperar a ultima movimentacao ativa
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
begin
  OPEN v_cursor FOR
  SELECT 
               UNI.CAD_UNI_DS_UNIDADE UNIDADE,
               LAT.CAD_LAT_DS_LOCAL_ATENDIMENTO,
               SETOR.CAD_SET_DS_SETOR,
               IML_QLE.CAD_QLE_NR_QUARTO,
               IML_QLE.CAD_QLE_NR_LEITO,
               TAC.TIS_TAC_DS_TIPO_ACOMODACAO,
               TAC_AUT.TIS_TAC_DS_TIPO_ACOMODACAO TIS_TAC_DS_TIPO_ACOMODACAO_AUT,
               ATD.ATD_ATE_ID,
               PAC.CAD_PAC_NR_PRONTUARIO,
               PES.CAD_PES_NM_PESSOA PACIENTE,
               PES.CAD_PES_DT_NASCIMENTO,
               PES.CAD_PES_TP_SEXO,
               (SELECT TO_CHAR(MAX(CCP.FAT_CCP_DT_PARCELA),'dd/MM/yyyy') FROM TB_FAT_CCP_CONTA_CONS_PARC  CCP 
                WHERE CCP.CAD_PAC_ID_PACIENTE   = PAC.CAD_PAC_ID_PACIENTE--fnc_buscar_paciente_atual(PAT.ATD_ATE_ID)
                  AND CCP.ATD_ATE_ID            = ATD.ATD_ATE_ID) FAT_CCP_DT_PARCELA,
               CNV.CAD_CNV_CD_HAC_PRESTADOR,
               PLA.CAD_PLA_CD_PLANO_HAC,
               TO_CHAR(ATD.ATD_ATE_DT_ATENDIMENTO,'dd/MM/yyyy') ATD_ATE_DT_ATENDIMENTO,
               ATD.ATD_ATE_HR_ATENDIMENTO,
               NVL(ROUND(SYSDATE-ATD.ATD_ATE_DT_ATENDIMENTO),0)  PERMANENCIA,
               PRO.CAD_PRO_NM_NOME PROFISSIONAL,
               PRO.CAD_PRO_NR_CONSELHO,
               PRO.CAD_PRO_SG_UF_CONSELHO,
               FLOOR(FLOOR(MONTHS_BETWEEN(SYSDATE, PES.CAD_PES_DT_NASCIMENTO)) / 12) IDADE,
               INC.ATD_INC_DS_CORTESIA,
               IGE_BNF.GER,
               IDF.ATD_IDF_DS_DIF_CLASSE
  FROM
                TB_ATD_ATE_ATENDIMENTO    ATD

  JOIN          TB_CAD_PAC_PACIENTE       PAC  ON            PAC.CAD_PAC_ID_PACIENTE = FNC_BUSCAR_PACIENTE_ATUAL(ATD.ATD_ATE_ID)
  JOIN          TB_CAD_PES_PESSOA         PES  ON            PES.CAD_PES_ID_PESSOA   = PAC.CAD_PES_ID_PESSOA
  JOIN          TB_CAD_CNV_CONVENIO       CNV  ON            CNV.CAD_CNV_ID_CONVENIO = PAC.CAD_CNV_ID_CONVENIO
  JOIN          TB_CAD_PLA_PLANO          PLA  ON            PLA.CAD_PLA_ID_PLANO    = PAC.CAD_PLA_ID_PLANO
  JOIN          TB_ATD_AIC_ATE_INT_COMPL  AIC  ON            AIC.ATD_ATE_ID          = ATD.ATD_ATE_ID
  LEFT JOIN    (SELECT BNF_SIT.DESSITBEN, BNF.DATINGCONBEN, BNF.DATSITBEN, BNF.DATALTBEN,PAC.CAD_PAC_ID_PACIENTE,
                DECODE       (FNC_VERIFICA_INSGER(BNF.CODCON, BNF.CODEST, BNF.CODBEN, BNF.CODSEQBEN),0,'',1,'I.GER',2,'I.GER',4,'A.ALTA') GER
                FROM          TB_CAD_PAC_PACIENTE       PAC
                JOIN          TB_CAD_PLA_PLANO          PLA  ON            PAC.CAD_PLA_ID_PLANO    = PLA.CAD_PLA_ID_PLANO
                JOIN          BNF_BENEFICIARIO          BNF
                ON            TO_CHAR(BNF.CODCON)     = TO_CHAR(PLA.CAD_PLA_CD_PLANO_HAC)
                AND           BNF.CODEST              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,0,3))
                AND           BNF.CODBEN              = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,4,7))
                AND           BNF.CODSEQBEN           = TO_NUMBER(SUBSTR(PAC.CAD_PAC_CD_CREDENCIAL,11,2))
                JOIN          BNF_SITUACAO_BENEF        BNF_SIT  ON            BNF_SIT.CODSITBEN       = BNF.CODSITBEN
                WHERE         pac.CAD_CNV_ID_CONVENIO = 281
                ) IGE_BNF
  ON           IGE_BNF.CAD_PAC_ID_PACIENTE = PAC.CAD_PAC_ID_PACIENTE
  JOIN  (  SELECT QLE.CAD_QLE_ID, QLE.CAD_SET_ID , QLE.CAD_QLE_NR_QUARTO, QLE.CAD_QLE_NR_LEITO,
                       IML.ATD_ATE_ID, IML.TIS_TAC_CD_TIPO_ACOMODACAO, QLE.CAD_QLE_TP_QUARTO_LEITO ,
                       IML.ATD_IML_DT_ENTRADA, IML.ATD_IML_HR_ENTRADA, IML.ATD_IML_DT_SAIDA, IML.ATD_IML_ID,
                       IML.TIS_TAC_CD_TIPO_ACOMOD_AUT
                  FROM TB_ATD_IML_INT_MOV_LEITO IML
                  JOIN TB_CAD_QLE_QUARTO_LEITO QLE ON QLE.CAD_QLE_ID = IML.CAD_CAD_QLE_ID
                  JOIN TB_ATD_ATE_ATENDIMENTO ATD2 ON ATD2.ATD_ATE_ID = IML.ATD_ATE_ID
                 WHERE (ATD2.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
                  AND  (ATD2.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
                  AND  (IML.ATD_IML_DT_SAIDA IS NULL)  
                  AND  FNC_JUNTAR_DATA_HORA(IML.ATD_IML_DT_ENTRADA,IML.ATD_IML_HR_ENTRADA) =
                                         (SELECT MAX(FNC_JUNTAR_DATA_HORA(IML3.ATD_IML_DT_ENTRADA,IML3.ATD_IML_HR_ENTRADA)) FROM TB_ATD_IML_INT_MOV_LEITO IML3
                                                       WHERE IML3.ATD_ATE_ID = ATD2.ATD_ATE_ID AND IML3.ATD_IML_FL_STATUS = 'A') )  IML_QLE
  ON            IML_QLE.ATD_ATE_ID = ATD.ATD_ATE_ID
  JOIN          TB_CAD_SET_SETOR            SETOR ON SETOR.CAD_SET_ID          = IML_QLE.CAD_SET_ID
  LEFT JOIN     TB_TIS_TAC_TIPO_ACOMODACAO  TAC ON TAC.TIS_TAC_CD_TIPO_ACOMODACAO = IML_QLE.TIS_TAC_CD_TIPO_ACOMODACAO
  LEFT JOIN     TB_TIS_TAC_TIPO_ACOMODACAO  TAC_AUT ON TAC_AUT.TIS_TAC_CD_TIPO_ACOMODACAO = IML_QLE.TIS_TAC_CD_TIPO_ACOMOD_AUT
  JOIN          TB_CAD_UNI_UNIDADE          UNI ON UNI.CAD_UNI_ID_UNIDADE    = SETOR.CAD_UNI_ID_UNIDADE
  JOIN          TB_CAD_LAT_LOCAL_ATENDIMENTO LAT ON LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = SETOR.CAD_LAT_ID_LOCAL_ATENDIMENTO
  JOIN          TB_CAD_PRO_PROFISSIONAL     PRO ON PRO.CAD_PRO_ID_PROFISSIONAL = ATD.CAD_PRO_ID_PROF_EXEC
  LEFT JOIN     TB_ATD_INC_INT_CORTESIA     INC ON INC.ATD_IML_ID            = IML_QLE.ATD_IML_ID
  LEFT JOIN     TB_ATD_IDF_INT_DIF_CLASSE   IDF ON IDF.ATD_IML_ID            = IML_QLE.ATD_IML_ID
      WHERE    (ATD.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
        AND    (ATD.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
        AND    (pCAD_SET_ID IS NULL OR IML_QLE.CAD_SET_ID = pCAD_SET_ID)
        AND    (AIC.ATD_AIC_TP_SITUACAO_PAC = 'I')
        AND    (ATD.ATD_ATE_FL_STATUS = 'A')
        AND    (ATD.ATD_ATE_TP_PACIENTE = 'I')
 ORDER BY      SETOR.CAD_SET_DS_SETOR,
               IML_QLE.CAD_QLE_NR_QUARTO,
               IML_QLE.CAD_QLE_NR_LEITO;
  io_cursor := v_cursor;
end PRC_INT_REL_QTD_POR_SETOR;