create or replace procedure PRC_ATS_ATE_ATEND_EXAME_SADT_S
  (
     pATS_ATE_CD_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_CD_INTLIB%type DEFAULT NULL,
     pATS_ATE_IN_INTLIB IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_IN_INTLIB%type DEFAULT NULL,
     pATS_ATE_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_ID%type DEFAULT NULL,
     pCAD_PRD_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRD_ID%type DEFAULT NULL,
     pATS_ATE_QT_PESO IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_QT_PESO%type DEFAULT NULL,
     pATS_ATE_QT_ALTURA IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_QT_ALTURA%type DEFAULT NULL,
     pCAD_SET_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_SET_ID%type DEFAULT NULL,
     pATS_ATE_TP_PROCED IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_TP_PROCED%type DEFAULT NULL,
     pATS_ATE_DS_OBSERVACAO IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DS_OBSERVACAO%type DEFAULT NULL,
     pATS_ATE_DT_ULTIMA_ATUALIZACAO IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DT_ULTIMA_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_ATS_ATE_ATENDIMENTO_SADT.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pATS_ATE_FL_EQUIP_INT_EXT IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_EQUIP_INT_EXT%type DEFAULT NULL,
     pAGE_SAU_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.AGE_SAU_ID%type DEFAULT NULL,
     pCAD_CLC_ID IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_CLC_ID%type DEFAULT NULL,
     pATS_ATE_FL_RN IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_RN%type DEFAULT NULL,
     pATS_ATE_FL_RESULT_INTERNET IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_RESULT_INTERNET%type DEFAULT NULL,
     pATS_ATE_CD_ACESSO_INTERNET IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_CD_ACESSO_INTERNET%type DEFAULT NULL,
     pATS_ATE_CD_SENHA_INTERNET IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_CD_SENHA_INTERNET%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_ATS_ATE_ATENDIMENTO_SADT.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pATS_ATE_SG_UF_CONSELHO_SOLIC IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_SG_UF_CONSELHO_SOLIC%type DEFAULT NULL,
     pATS_ATE_TP_CONSELHO_SOLIC IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_TP_CONSELHO_SOLIC%type DEFAULT NULL,
     pATS_ATE_NR_CONSELHO_SOLIC IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_NR_CONSELHO_SOLIC%type DEFAULT NULL,
     pCAD_PRO_ID_PROF_EXECUTANTE IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRO_ID_PROF_EXECUTANTE%type DEFAULT NULL,
     pATS_ATE_DT_REALIZ_PROCED IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_DT_REALIZ_PROCED%type DEFAULT NULL,
     pATS_ATE_HR_REALIZ_PROCED IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_HR_REALIZ_PROCED%type DEFAULT NULL,
     pATS_ATE_FL_STATUS IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_STATUS%type DEFAULT NULL,
     pCAD_UNI_ID_UNIDADE_LIBERACAO IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_UNI_ID_UNIDADE_LIBERACAO%TYPE DEFAULT NULL,
     pCAD_UNI_ID_LOCAL_LIBERACAO IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_UNI_ID_LOCAL_LIBERACAO%TYPE DEFAULT NULL,
      pATS_ATE_FL_ANESTESIA IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_ANESTESIA%type default NULL,
     pCAD_PRO_ID_PROF_ANEST IN TB_ATS_ATE_ATENDIMENTO_SADT.CAD_PRO_ID_PROF_ANEST%type default NULL,
     pATS_ATE_FL_PROC_JUSTIFICADO IN TB_ATS_ATE_ATENDIMENTO_SADT.ATS_ATE_FL_PROC_JUSTIFICADO%type default NULL	,
     pTIS_MED_CD_TABELAMEDICA IN TB_ATS_APS_ATEN_PROC_SEGMENTO.TIS_MED_CD_TABELAMEDICA%type	DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_ATS_ATE_ATEND_EXAME_SADT_S
  * 
  *      Data Alteracao:	27/07/2009  Por: Pedro
  *    Alteracao: correção da proc, nao estava mostrando o ats 14873540, foram colocados LEFT Joins
  *
  *      Data Alteracao:	04/02/2010  Por: Pedro
  *    Alteracao: 3 campos novos
  *
  *    Data Alteracao:	27/03/2010  Por: Pedro
  *    Alteração: pTIS_MED_CD_TABELAMEDICA
  *
  *    Funcao: Recupera os dados do Atendimento SADT
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT
         ATS.ATS_ATE_CD_INTLIB LIB_PRD_ID,
         ATS.ATS_ATE_IN_INTLIB,
         ATS.ATS_ATE_ID,
         ATS.CAD_PRD_ID,
         ATS.ATS_ATE_QT_PESO,
         ATS.ATS_ATE_QT_ALTURA,
         ATS.CAD_SET_ID,
         ATS.ATS_ATE_TP_PROCED,
         ATS.ATS_ATE_DS_OBSERVACAO,
         ATS.ATS_ATE_DT_ULTIMA_ATUALIZACAO,
         ATS.SEG_USU_ID_USUARIO,
         ATS.ATS_ATE_FL_EQUIP_INT_EXT,
         ATS.AGE_SAU_ID,
         ATS.CAD_CLC_ID,
         ATS.ATS_ATE_FL_RN,
         ATS.ATS_ATE_FL_RESULT_INTERNET,
         ATS.ATS_ATE_CD_ACESSO_INTERNET,
         ATS.ATS_ATE_CD_SENHA_INTERNET,
         ATS.AUX_EPP_CD_ESPECPROC,
         ATS.ATS_ATE_SG_UF_CONSELHO_SOLIC,
         ATS.ATS_ATE_TP_CONSELHO_SOLIC,
         ATS.ATS_ATE_NR_CONSELHO_SOLIC,
         ATS.CAD_PRO_ID_PROF_EXECUTANTE,
         ATS.ATS_ATE_DT_REALIZ_PROCED,
         ATS.ATS_ATE_HR_REALIZ_PROCED,
         ATS.ATS_ATE_FL_STATUS,
         ATS.CAD_UNI_ID_UNIDADE_LIBERACAO,
         ATS.CAD_UNI_ID_LOCAL_LIBERACAO,
         
         ARP.ATS_ARP_DT_RESULTADO,
         ARP.CAD_SET_ID_SETOR,
         ARP.ATS_APR_FL_STATUS,
         ARP.ATS_APR_DT_ENTREGA_RESP,
         ARP.ATS_APR_HR_ENTREGA_RESP,
         ARP.ATS_APR_NM_NOME_RESP_RECEB,
         ARP.ATS_APR_DT_ULTIMA_ATUALIZACAO,
         ARP.SEG_USU_ID_USUARIO,
         ARP.ATS_ATE_CD_INTLIB,
         ARP.ATS_ATE_IN_INTLIB,
         ARP.ATS_EPP_CD_ESPECPROC,
         ARP.ATS_ATE_ID,
         ARP.CAD_PRD_ID,
         ARP.CAD_UNI_ID_UNIDADE,
         ARP.ATS_APR_DT_PROTOCOLO,
         ARP.ATS_APR_HR_PROTOCOLO,
         ARP.SEG_USU_ID_PROTOCOLO,
         CFM.NOMMED NOME_PROFISSIONAL_SOLICITANTE,
         PES_EXEC.CAD_PES_NM_PESSOA NOME_PROFISSIONAL_EXECUTANTE,
         PES_CLI.CAD_PES_NM_PESSOA NOME_CLINICA,
         CLC.CAD_CLC_ID,
         CLC.CAD_CLC_DS_RESUMIDA,
         PRO.CAD_PRO_NR_CONSELHO,
         ATS.ATS_ATE_NR_QUARTO,
         ATS.ATS_ATE_NR_LEITO,
         ATS.CAD_PAC_ID_PACIENTE_INT,
         ATS.ATS_ATE_FL_ANESTESIA,
         ATS.CAD_PRO_ID_PROF_ANEST,
         ATS.ATS_ATE_FL_PROC_JUSTIFICADO,
         ATS.TIS_MED_CD_TABELAMEDICA
         
  FROM   TB_ATS_ATE_ATENDIMENTO_SADT    ATS
    LEFT JOIN TB_ATS_ARP_ATEN_RESULT_PROCED  ARP
     ON     ATS.ATS_ATE_ID  = ARP.ATS_ATE_ID  
     AND    ATS.CAD_PRD_ID  = ARP.CAD_PRD_ID  
     AND    ATS.ATS_ATE_CD_INTLIB  = ARP.ATS_ATE_CD_INTLIB  
     AND    ATS.ATS_ATE_IN_INTLIB  = ARP.ATS_ATE_IN_INTLIB  
     AND    ATS.AUX_EPP_CD_ESPECPROC  = ARP.ATS_EPP_CD_ESPECPROC 
     AND    ATS.TIS_MED_CD_TABELAMEDICA = ARP.TIS_MED_CD_TABELAMEDICA
     LEFT JOIN TB_ATS_APL_ATEN_PROCED_LAUDO  APL
     ON     ATS.ATS_ATE_ID  = APL.ATS_ATE_ID  
     AND    ATS.CAD_PRD_ID  = APL.CAD_PRD_ID  
     AND    ATS.ATS_ATE_CD_INTLIB  = APL.ATS_ATE_CD_INTLIB  
     AND    ATS.ATS_ATE_IN_INTLIB  = APL.ATS_ATE_IN_INTLIB  
     AND    ATS.AUX_EPP_CD_ESPECPROC  = APL.AUX_EPP_CD_ESPECPROC
     AND    ATS.TIS_MED_CD_TABELAMEDICA = APL.TIS_MED_CD_TABELAMEDICA
    LEFT JOIN TB_MEDICO_CFM                  CFM
     ON     ATS.ATS_ATE_NR_CONSELHO_SOLIC = CFM.CODMED  
     AND    ATS.ATS_ATE_SG_UF_CONSELHO_SOLIC = CFM.UF
    LEFT JOIN TB_CAD_PRO_PROFISSIONAL        PRO
     ON     ATS.CAD_PRO_ID_PROF_EXECUTANTE  = PRO.CAD_PRO_ID_PROFISSIONAL
    LEFT JOIN TB_CAD_PES_PESSOA              PES_EXEC
     ON     PES_EXEC.CAD_PES_ID_PESSOA = PRO.CAD_PES_ID_PESSOA
    LEFT JOIN TB_CAD_CLC_CLINICA_CREDENCIADA CLC
     ON     CLC.CAD_CLC_ID = ATS.CAD_CLC_ID
    LEFT JOIN TB_CAD_PES_PESSOA              PES_CLI 
     ON     CLC.CAD_PES_ID_PESSOA = PES_CLI.CAD_PES_ID_PESSOA
    WHERE
        (pATS_ATE_CD_INTLIB is null OR ATS.ATS_ATE_CD_INTLIB = pATS_ATE_CD_INTLIB) AND
        (pATS_ATE_IN_INTLIB is null OR ATS.ATS_ATE_IN_INTLIB = pATS_ATE_IN_INTLIB) AND
        (pATS_ATE_ID is null OR ATS.ATS_ATE_ID = pATS_ATE_ID) AND
        (pCAD_PRD_ID is null OR ATS.CAD_PRD_ID = pCAD_PRD_ID) AND
        (pATS_ATE_QT_PESO is null OR ATS.ATS_ATE_QT_PESO = pATS_ATE_QT_PESO) AND
        (pATS_ATE_QT_ALTURA is null OR ATS.ATS_ATE_QT_ALTURA = pATS_ATE_QT_ALTURA) AND
        (pCAD_SET_ID is null OR ATS.CAD_SET_ID = pCAD_SET_ID) AND
        (pATS_ATE_TP_PROCED is null OR ATS.ATS_ATE_TP_PROCED = pATS_ATE_TP_PROCED) AND
        (pATS_ATE_DS_OBSERVACAO is null OR ATS.ATS_ATE_DS_OBSERVACAO = pATS_ATE_DS_OBSERVACAO) AND
        (pATS_ATE_DT_ULTIMA_ATUALIZACAO is null OR ATS.ATS_ATE_DT_ULTIMA_ATUALIZACAO = pATS_ATE_DT_ULTIMA_ATUALIZACAO) AND
        (pSEG_USU_ID_USUARIO is null OR ATS.SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND
        (pATS_ATE_FL_EQUIP_INT_EXT is null OR ATS.ATS_ATE_FL_EQUIP_INT_EXT = pATS_ATE_FL_EQUIP_INT_EXT) AND
        (pAGE_SAU_ID is null OR ATS.AGE_SAU_ID = pAGE_SAU_ID) AND
        (pCAD_CLC_ID is null OR ATS.CAD_CLC_ID = pCAD_CLC_ID) AND
        (pATS_ATE_FL_RN is null OR ATS.ATS_ATE_FL_RN = pATS_ATE_FL_RN) AND
        (pATS_ATE_FL_RESULT_INTERNET is null OR ATS.ATS_ATE_FL_RESULT_INTERNET = pATS_ATE_FL_RESULT_INTERNET) AND
        (pATS_ATE_CD_ACESSO_INTERNET is null OR ATS.ATS_ATE_CD_ACESSO_INTERNET = pATS_ATE_CD_ACESSO_INTERNET) AND
        (pATS_ATE_CD_SENHA_INTERNET is null OR ATS.ATS_ATE_CD_SENHA_INTERNET = pATS_ATE_CD_SENHA_INTERNET) AND
        (pAUX_EPP_CD_ESPECPROC is null OR ATS.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC) AND
        (pATS_ATE_SG_UF_CONSELHO_SOLIC is null OR ATS.ATS_ATE_SG_UF_CONSELHO_SOLIC = pATS_ATE_SG_UF_CONSELHO_SOLIC) AND
        (pATS_ATE_TP_CONSELHO_SOLIC is null OR ATS.ATS_ATE_TP_CONSELHO_SOLIC = pATS_ATE_TP_CONSELHO_SOLIC) AND
        (pATS_ATE_NR_CONSELHO_SOLIC is null OR ATS.ATS_ATE_NR_CONSELHO_SOLIC = pATS_ATE_NR_CONSELHO_SOLIC) AND
        (pCAD_PRO_ID_PROF_EXECUTANTE is null OR ATS.CAD_PRO_ID_PROF_EXECUTANTE = pCAD_PRO_ID_PROF_EXECUTANTE) AND
        (pATS_ATE_DT_REALIZ_PROCED is null OR ATS.ATS_ATE_DT_REALIZ_PROCED = pATS_ATE_DT_REALIZ_PROCED) AND
        (pATS_ATE_HR_REALIZ_PROCED is null OR ATS.ATS_ATE_HR_REALIZ_PROCED = pATS_ATE_HR_REALIZ_PROCED) AND
        (pATS_ATE_FL_STATUS is null OR ATS.ATS_ATE_FL_STATUS = pATS_ATE_FL_STATUS) AND
        (pCAD_UNI_ID_UNIDADE_LIBERACAO is null OR ATS.CAD_UNI_ID_UNIDADE_LIBERACAO = pCAD_UNI_ID_UNIDADE_LIBERACAO) AND
        (pCAD_UNI_ID_LOCAL_LIBERACAO is null OR ATS.CAD_UNI_ID_LOCAL_LIBERACAO = pCAD_UNI_ID_LOCAL_LIBERACAO) AND
        (pATS_ATE_FL_ANESTESIA IS NULL OR ATS.ATS_ATE_FL_ANESTESIA = pATS_ATE_FL_ANESTESIA) AND
        (pCAD_PRO_ID_PROF_ANEST IS NULL OR ATS.CAD_PRO_ID_PROF_ANEST = pCAD_PRO_ID_PROF_ANEST ) AND
        (pATS_ATE_FL_PROC_JUSTIFICADO IS NULL OR ATS.ATS_ATE_FL_PROC_JUSTIFICADO = pATS_ATE_FL_PROC_JUSTIFICADO) AND
        (pTIS_MED_CD_TABELAMEDICA IS NULL OR ATS.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA)
    
        
        order by 24 desc,25 desc
        ;
    io_cursor := v_cursor;
  end PRC_ATS_ATE_ATEND_EXAME_SADT_S;
  
/
