create or replace procedure PRC_ASS_LISTAR_PRODUTO_VALOR
  (     
     pCAD_CNV_ID_CONVENIO IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_CNV_ID_CONVENIO%type,
     pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ASS_CVP_CONV_VLR_PRODUTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%type,
     pTIS_MED_CD_TABELAMEDICA IN TB_CAD_PRD_PRODUTO.TIS_MED_CD_TABELAMEDICA%type DEFAULT NULL,
     pCAD_TAP_TP_ATRIBUTO IN TB_CAD_PRD_PRODUTO.CAD_TAP_TP_ATRIBUTO%type DEFAULT NULL,
     pAUX_EPP_CD_ESPECPROC IN TB_CAD_PRD_PRODUTO.AUX_EPP_CD_ESPECPROC%type DEFAULT NULL,
     pAUX_GPC_CD_GRUPOPROC IN TB_CAD_PRD_PRODUTO.AUX_GPC_CD_GRUPOPROC%type DEFAULT NULL,
     pTIPO_ASSOCIACAO IN NUMBER, -- (0: Todos) (-1: Não Associados) (-2: Associados)    
     io_cursor OUT PKG_CURSOR.t_cursor
  ) 
  is
  /********************************************************************
  *    Procedure: PRC_ASS_LISTAR_PRODUTO_VALOR
  * 
  *    Data Criacao:   data da  criação   Por: Nome do Analista
  *    Data Alteracao:  data da alteração  Por: Nome do Analista
  *
  *    Funcao: Descrição da funcionalidade da Stored Procedure
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  
  begin
  
    --  0: Todos
    -- -1: Não Associados
    -- -2: Associados
  
   --Associados
   IF pTIPO_ASSOCIACAO = -2 THEN
       
      OPEN v_cursor FOR
      SELECT 
         CVP.ASS_CVP_ID,
         PRD.CAD_PRD_ID,
         PRD.CAD_PRD_DS_DESCRICAO,
         PRD.CAD_TIH_TP_INDICE_HOSP,
         TIH.CAD_TIH_DS_INDICE_HOSP,
         MED.TIS_MED_DS_TABELAMEDICA,
         TAP.CAD_TAP_DS_ATRIBUTO,
         EPP.AUX_EPP_DS_DESCRICAO,
         GPC.AUX_GPC_DS_DESCRICAO,
         CVP.ASS_CVP_QT_INDICE_HOSP,
         CVP.ASS_CVP_VL_INDICE_HOSP,
         CVP.ASS_CVP_TP_PORTE,
         CVP.CAD_TAP_TP_ATRIBUTO,
         CVP.ASS_CVP_PC_DESCONTO,
         CVP.ASS_CVP_FL_PC_ACRESCIMOHR,
         CVP.ASS_CVP_PC_TAXAADM,
         CVP.ASS_CVP_VL_PRODUTO,
         CVP.ASS_CVP_VL_ACRESCIMO,
         CVP.ASS_CVP_VL_DESCONTO,
         CVP.TIS_CDE_CD_CODIGO_DESPESA,
         CVP.ASS_CVP_PC_DOPPLER,     
         CVP.ASS_CVP_QT_MINIMA_PERM,
         CVP.ASS_CVP_QT_MAXIMA_PERM,
         CVP.ASS_CVP_FL_PC_ACRESCIMOHR  
    FROM TB_CAD_PRD_PRODUTO PRD,
         TB_ASS_CVP_CONV_VLR_PRODUTO CVP,
         TB_TIS_MED_TABELAMEDICA MED,
         TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
         TB_AUX_EPP_ESPECPROC EPP,
         TB_AUX_GPC_GRUPOPROC GPC,
         TB_CAD_TIH_TP_INDICE_HOSP TIH
   WHERE PRD.CAD_PRD_ID = CVP.CAD_PRD_ID 
     AND PRD.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA
     AND PRD.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
     AND PRD.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC
     AND PRD.AUX_GPC_CD_GRUPOPROC = GPC.AUX_GPC_CD_GRUPOPROC
     AND PRD.CAD_TIH_TP_INDICE_HOSP = TIH.CAD_TIH_TP_INDICE_HOSP
     AND EPP.AUX_EPP_CD_ESPECPROC = GPC.AUX_EPP_CD_ESPECPROC
     AND CVP.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
     AND CVP.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
     AND (pTIS_MED_CD_TABELAMEDICA IS NULL OR PRD.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA)
     AND (pCAD_TAP_TP_ATRIBUTO IS NULL OR PRD.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO)     
     AND (pAUX_EPP_CD_ESPECPROC IS NULL OR PRD.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC)
     AND (pAUX_GPC_CD_GRUPOPROC IS NULL OR PRD.AUX_GPC_CD_GRUPOPROC = pAUX_GPC_CD_GRUPOPROC);
       
   ELSE
       
     --Não Associados
     IF pTIPO_ASSOCIACAO = -1 THEN
            
        OPEN v_cursor FOR
        SELECT 
               NULL AS ASS_CVP_ID,
               PRD.CAD_PRD_ID,
               PRD.CAD_PRD_DS_DESCRICAO,
               PRD.CAD_TIH_TP_INDICE_HOSP,
               TIH.CAD_TIH_DS_INDICE_HOSP,
               MED.TIS_MED_DS_TABELAMEDICA,
               TAP.CAD_TAP_DS_ATRIBUTO,
               EPP.AUX_EPP_DS_DESCRICAO,
               GPC.AUX_GPC_DS_DESCRICAO,
               PRD.CAD_PRD_QT_INDICE_HOSP AS ASS_CVP_QT_INDICE_HOSP,
               VMH.CAD_VMH_VL_MOEDA_HOSPITALAR AS ASS_CVP_VL_INDICE_HOSP,
               PRD.CAD_PRD_TP_PORTE AS ASS_CVP_TP_PORTE,
               PRD.CAD_TAP_TP_ATRIBUTO AS CAD_TAP_TP_ATRIBUTO,
               NULL AS ASS_CVP_PC_DESCONTO,
               NULL AS ASS_CVP_FL_PC_ACRESCIMOHR,
               NULL AS ASS_CVP_PC_TAXAADM,
               PRD.CAD_PRD_VL_PRODUTO AS ASS_CVP_VL_PRODUTO,
               NULL AS ASS_CVP_VL_ACRESCIMO,
               NULL AS ASS_CVP_VL_DESCONTO,
               PRD.CAD_PRD_CD_NAT_DESPESA_TISS AS TIS_CDE_CD_CODIGO_DESPESA,
               PRD.CAD_PRD_PC_DOPPLER AS ASS_CVP_PC_DOPPLER,     
               NULL AS ASS_CVP_QT_MINIMA_PERM,
               NULL AS ASS_CVP_QT_MAXIMA_PERM,
               NULL AS ASS_CVP_FL_PC_ACRESCIMOHR      
          FROM TB_CAD_PRD_PRODUTO PRD,
               TB_TIS_MED_TABELAMEDICA MED,
               TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
               TB_AUX_EPP_ESPECPROC EPP,
               TB_AUX_GPC_GRUPOPROC GPC,
               TB_CAD_TIH_TP_INDICE_HOSP TIH,
               TB_CAD_VMH_VALOR_MOEDA_HOSP VMH
         WHERE PRD.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA
           AND PRD.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
           AND PRD.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC
           AND PRD.AUX_GPC_CD_GRUPOPROC = GPC.AUX_GPC_CD_GRUPOPROC
           AND PRD.CAD_TIH_TP_INDICE_HOSP = TIH.CAD_TIH_TP_INDICE_HOSP               
           AND TIH.CAD_TIH_TP_INDICE_HOSP = VMH.CAD_TIH_TP_INDICE_HOSP(+)
           AND (pTIS_MED_CD_TABELAMEDICA IS NULL OR PRD.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA)
           AND (pCAD_TAP_TP_ATRIBUTO IS NULL OR PRD.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO)     
           AND (pAUX_EPP_CD_ESPECPROC IS NULL OR PRD.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC)
           AND (pAUX_GPC_CD_GRUPOPROC IS NULL OR PRD.AUX_GPC_CD_GRUPOPROC = pAUX_GPC_CD_GRUPOPROC)         
           AND PRD.CAD_PRD_ID NOT IN (SELECT CVP.CAD_PRD_ID                                                        
                                        FROM TB_ASS_CVP_CONV_VLR_PRODUTO CVP                                                 
                                       WHERE CVP.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
                                         AND CVP.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO);
         
     ELSE
                                       
        OPEN v_cursor FOR
        SELECT 
           CVP.ASS_CVP_ID,
           PRD.CAD_PRD_ID,
           PRD.CAD_PRD_DS_DESCRICAO,
           PRD.CAD_TIH_TP_INDICE_HOSP,           
           TIH.CAD_TIH_DS_INDICE_HOSP,
           MED.TIS_MED_DS_TABELAMEDICA,
           TAP.CAD_TAP_DS_ATRIBUTO,
           EPP.AUX_EPP_DS_DESCRICAO,
           GPC.AUX_GPC_DS_DESCRICAO,
           CVP.ASS_CVP_QT_INDICE_HOSP,
           CVP.ASS_CVP_VL_INDICE_HOSP,
           CVP.ASS_CVP_TP_PORTE,
           CVP.CAD_TAP_TP_ATRIBUTO,
           CVP.ASS_CVP_PC_DESCONTO,
           CVP.ASS_CVP_FL_PC_ACRESCIMOHR,
           CVP.ASS_CVP_PC_TAXAADM,
           CVP.ASS_CVP_VL_PRODUTO,
           CVP.ASS_CVP_VL_ACRESCIMO,
           CVP.ASS_CVP_VL_DESCONTO,
           CVP.TIS_CDE_CD_CODIGO_DESPESA,
           CVP.ASS_CVP_PC_DOPPLER,     
           CVP.ASS_CVP_QT_MINIMA_PERM,
           CVP.ASS_CVP_QT_MAXIMA_PERM,
           CVP.ASS_CVP_FL_PC_ACRESCIMOHR      
      FROM TB_CAD_PRD_PRODUTO PRD,
           TB_ASS_CVP_CONV_VLR_PRODUTO CVP,
           TB_TIS_MED_TABELAMEDICA MED,
           TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
           TB_AUX_EPP_ESPECPROC EPP,
           TB_AUX_GPC_GRUPOPROC GPC,
           TB_CAD_TIH_TP_INDICE_HOSP TIH
     WHERE PRD.CAD_PRD_ID = CVP.CAD_PRD_ID 
       AND PRD.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA
       AND PRD.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
       AND PRD.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC
       AND PRD.AUX_GPC_CD_GRUPOPROC = GPC.AUX_GPC_CD_GRUPOPROC
       AND PRD.CAD_TIH_TP_INDICE_HOSP = TIH.CAD_TIH_TP_INDICE_HOSP
       AND EPP.AUX_EPP_CD_ESPECPROC = GPC.AUX_EPP_CD_ESPECPROC
       AND CVP.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
       AND CVP.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO
       AND (pTIS_MED_CD_TABELAMEDICA IS NULL OR PRD.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA)
       AND (pCAD_TAP_TP_ATRIBUTO IS NULL OR PRD.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO)     
       AND (pAUX_EPP_CD_ESPECPROC IS NULL OR PRD.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC)
       AND (pAUX_GPC_CD_GRUPOPROC IS NULL OR PRD.AUX_GPC_CD_GRUPOPROC = pAUX_GPC_CD_GRUPOPROC)
           
       UNION
         
       SELECT    NULL AS ASS_CVP_ID,
                 PRD.CAD_PRD_ID,
                 PRD.CAD_PRD_DS_DESCRICAO,
                 PRD.CAD_TIH_TP_INDICE_HOSP,                 
                 TIH.CAD_TIH_DS_INDICE_HOSP,
                 MED.TIS_MED_DS_TABELAMEDICA,
                 TAP.CAD_TAP_DS_ATRIBUTO,
                 EPP.AUX_EPP_DS_DESCRICAO,
                 GPC.AUX_GPC_DS_DESCRICAO,
                 NULL AS ASS_CVP_QT_INDICE_HOSP,
                 NULL AS ASS_CVP_VL_INDICE_HOSP,
                 NULL AS ASS_CVP_TP_PORTE,
                 NULL AS CAD_TAP_TP_ATRIBUTO,
                 NULL AS ASS_CVP_PC_DESCONTO,
                 NULL AS ASS_CVP_FL_PC_ACRESCIMOHR,
                 NULL AS ASS_CVP_PC_TAXAADM,
                 NULL AS ASS_CVP_VL_PRODUTO,
                 NULL AS ASS_CVP_VL_ACRESCIMO,
                 NULL AS ASS_CVP_VL_DESCONTO,
                 NULL AS TIS_CDE_CD_CODIGO_DESPESA,
                 NULL AS ASS_CVP_PC_DOPPLER,     
                 NULL AS ASS_CVP_QT_MINIMA_PERM,
                 NULL AS ASS_CVP_QT_MAXIMA_PERM,
                 NULL AS ASS_CVP_FL_PC_ACRESCIMOHR             
            FROM TB_CAD_PRD_PRODUTO PRD,
                 TB_TIS_MED_TABELAMEDICA MED,
                 TB_CAD_TAP_TP_ATRIB_PRODUTO TAP,
                 TB_AUX_EPP_ESPECPROC EPP,
                 TB_AUX_GPC_GRUPOPROC GPC,
                 TB_CAD_TIH_TP_INDICE_HOSP TIH
           WHERE PRD.TIS_MED_CD_TABELAMEDICA = MED.TIS_MED_CD_TABELAMEDICA
             AND PRD.CAD_TAP_TP_ATRIBUTO = TAP.CAD_TAP_TP_ATRIBUTO
             AND PRD.AUX_EPP_CD_ESPECPROC = EPP.AUX_EPP_CD_ESPECPROC
             AND PRD.AUX_GPC_CD_GRUPOPROC = GPC.AUX_GPC_CD_GRUPOPROC
             AND PRD.CAD_TIH_TP_INDICE_HOSP = TIH.CAD_TIH_TP_INDICE_HOSP               
             AND (pTIS_MED_CD_TABELAMEDICA IS NULL OR PRD.TIS_MED_CD_TABELAMEDICA = pTIS_MED_CD_TABELAMEDICA)
             AND (pCAD_TAP_TP_ATRIBUTO IS NULL OR PRD.CAD_TAP_TP_ATRIBUTO = pCAD_TAP_TP_ATRIBUTO)     
             AND (pAUX_EPP_CD_ESPECPROC IS NULL OR PRD.AUX_EPP_CD_ESPECPROC = pAUX_EPP_CD_ESPECPROC)
             AND (pAUX_GPC_CD_GRUPOPROC IS NULL OR PRD.AUX_GPC_CD_GRUPOPROC = pAUX_GPC_CD_GRUPOPROC)         
             AND PRD.CAD_PRD_ID NOT IN (SELECT CVP.CAD_PRD_ID                                                        
                                          FROM TB_ASS_CVP_CONV_VLR_PRODUTO CVP                                                 
                                         WHERE CVP.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
                                           AND CVP.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO);  
      
                    
     END IF;
       
   END IF;
    
    
        
   io_cursor := v_cursor;
    
  end PRC_ASS_LISTAR_PRODUTO_VALOR;
