 CREATE OR REPLACE PROCEDURE PRC_CAD_CTP_TPA_S
(
   pDT_INTERNACAO IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE,
   pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE,
   pCAD_UNI_ID_UNIDADE IN TB_CAD_UNI_UNIDADE.CAD_UNI_ID_UNIDADE%TYPE,
   pCAD_PLA_ID_PLANO IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE,
   IO_CURSOR OUT PKG_CURSOR.T_CURSOR
) 
IS
/***************************************************************************
*    Procedure: PRC_CAD_CTP_TPA_S
* 
*    Data Criacao:   20/08/2009   Por: Caio Chagas
*    Data Alteracao:              Por: 
*
*    Funcao: Listar os tipos de acomodação por unidade, convênio e plano
*
****************************************************************************/
V_CURSOR PKG_CURSOR.T_CURSOR;
BEGIN
  OPEN V_CURSOR FOR
    SELECT  TAC.TIS_TAC_CD_TIPO_ACOMODACAO, TAC.TIS_TAC_DS_TIPO_ACOMODACAO
    FROM    TB_ASS_CTP_CNV_UN_TPACOM_PLA CTP
    JOIN    TB_ASS_CUT_CONV_UNI_TPACOMOD CUT
    ON      CUT.ASS_CUT_ID = CTP.ASS_CUT_ID
    JOIN    TB_CAD_PLA_PLANO PLA
    ON      PLA.CAD_PLA_ID_PLANO = CTP.CAD_PLA_ID_PLANO
    JOIN    TB_ASS_CNU_CONVENIO_UNIDADE CNU 
    ON      CNU.ASS_CNU_ID = CUT.ASS_CNU_ID
    JOIN    TB_ASS_UTA_UNID_TPACOMOD UTA
    ON      UTA.ASS_UTA_ID_UNID_TPACOMOD = CUT.ASS_UTA_ID_UNID_TPACOMOD
    JOIN    TB_CAD_CNV_CONVENIO CNV
    ON      CNV.CAD_CNV_ID_CONVENIO = CNU.CAD_CNV_ID_CONVENIO
    JOIN    TB_TIS_TAC_TIPO_ACOMODACAO TAC
    ON      TAC.TIS_TAC_CD_TIPO_ACOMODACAO = UTA.TIS_TAC_CD_TIPO_ACOMODACAO
    JOIN    TB_CAD_UNI_UNIDADE UNI
    ON      UNI.CAD_UNI_ID_UNIDADE = CNU.CAD_UNI_ID_UNIDADE
    AND     UNI.CAD_UNI_ID_UNIDADE = UTA.CAD_UNI_ID_UNIDADE     
    WHERE   UTA.ASS_UTA_FL_ATIVO_OK = 'S'  
    AND     ((pDT_INTERNACAO > = CTP.ASS_CTP_DT_INI_VIGENCIA AND CTP.ASS_CTP_DT_FIM_VIGENCIA IS NULL)
            OR (pDT_INTERNACAO BETWEEN CTP.ASS_CTP_DT_INI_VIGENCIA AND CTP.ASS_CTP_DT_FIM_VIGENCIA))
    AND     (( pDT_INTERNACAO > = CUT.ASS_CUT_DT_INI_VIGENCIA AND CUT.ASS_CUT_DT_FIM_VIGENCIA IS NULL)
            OR (pDT_INTERNACAO BETWEEN CUT.ASS_CUT_DT_INI_VIGENCIA AND CUT.ASS_CUT_DT_FIM_VIGENCIA))
    AND     CNV.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO
    AND     UNI.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE
    AND     PLA.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO;
    IO_CURSOR := V_CURSOR;
END PRC_CAD_CTP_TPA_S;

    