CREATE OR REPLACE PROCEDURE PRC_BNF_VALIDA_CARENCIA
(
       pCODCON IN BNF_CARENCIA_BENEFICIARIO.CODCON%TYPE,
       pCODEST IN BNF_CARENCIA_BENEFICIARIO.CODEST%TYPE,
       pCODBEN IN BNF_CARENCIA_BENEFICIARIO.CODBEN%TYPE,
       pCODSEQBEN IN BNF_CARENCIA_BENEFICIARIO.CODSEQBEN%TYPE,
       pDTATENDIMENTO IN BNF_CARENCIA_BENEFICIARIO.DATINICAR%TYPE,
       pCAD_PRD_CD_CODIGO IN TB_CAD_PRD_PRODUTO.CAD_PRD_CD_CODIGO%TYPE,
       io_cursor OUT PKG_CURSOR.t_cursor
)

IS
v_cursor PKG_CURSOR.t_cursor;

BEGIN
   
   OPEN v_cursor FOR
   SELECT MAX(DATFIMCAR) AS DATFIMCAR
   FROM BNF_CARENCIA_BENEFICIARIO BNF
   WHERE BNF.CODSER IN (SELECT SPA.CODSER FROM TB_AUT_PROCED_CARENCIA SPA WHERE SPA.CODATOMED = pCAD_PRD_CD_CODIGO)
     AND BNF.CODCON = (pCODCON)
     AND BNF.CODEST = (pCODEST)
     AND BNF.CODBEN = (pCODBEN)
     AND BNF.CODSEQBEN = (pCODSEQBEN)
     AND TRUNC(pDTATENDIMENTO) BETWEEN TRUNC(BNF.DATINICAR) AND TRUNC(BNF.DATFIMCAR);

   io_cursor := v_cursor;
END PRC_BNF_VALIDA_CARENCIA;
