CREATE OR REPLACE PROCEDURE "PRC_FAT_REL_FATURAS_EMI"
(
    pCAD_UNI_ID_UNIDADE      IN TB_FAT_NOF_NOTA_FISCAL.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    PFAT_CCP_MES_FAT IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_MES_FAT%TYPE DEFAULT NULL,
    PFAT_CCP_ANO_FAT IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_ANO_FAT%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_CNV_CONVENIO.CAD_TPE_CD_CODIGO%TYPE DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_E in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_A in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_TP_PACIENTE_U in tb_atd_ate_atendimento.atd_ate_tp_paciente%type default null,
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    io_cursor OUT PKG_CURSOR.t_cursor
    -- TESTE OUT LONG
)
IS
/********************************************************************
*    Procedure: PRC_FAT_REL_FATURAS_EMI
*
*    Data Cria??o: 02/03/2012  Por: Eduardo
*
*******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(2000);
  V_SELECT  varchar2(20000);
  begin
    V_WHERE := NULL;
  
    IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE := V_WHERE || ' AND NOF.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
    IF pFAT_CCP_MES_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND NOF.FAT_NOF_MES_FAT = ' || pFAT_CCP_MES_FAT;    END IF;
    IF pFAT_CCP_ANO_FAT IS NOT NULL THEN V_WHERE := V_WHERE || ' AND NOF.FAT_NOF_ANO_FAT = ' || pFAT_CCP_ANO_FAT;    END IF;
    IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE := V_WHERE || ' AND CNV.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO; END IF;

    IF pATD_ATE_DT_ATENDIMENTO_INI IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRUNC(NOF.FAT_NFO_DT_EMISSAO) >= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_INI ||CHR(39);    END IF;
    IF pATD_ATE_DT_ATENDIMENTO_FIM IS NOT NULL THEN V_WHERE := V_WHERE || ' AND TRUNC(NOF.FAT_NFO_DT_EMISSAO) <= ' ||CHR(39)|| pATD_ATE_DT_ATENDIMENTO_FIM ||CHR(39);    END IF;
    
   V_SELECT := '
  SELECT DISTINCT CNV.CAD_CNV_CD_HAC_PRESTADOR,
          CNV.CAD_CNV_DS_RAZAOSOCIAL,
          NOF.FAT_NOF_NR_NOTAFISCAL,
          NOF.FAT_NFO_VL_LIQUIDO,
          NOF.FAT_NOF_TP_SERIEFISCAL,
          NOF.FAT_NFO_DT_EMISSAO,
          NOF.FAT_NFO_DT_VENCIMENTO,
          NOF.FAT_NFO_VL_RETENCAO,
          NOF.FAT_NOF_VL_ISS,
          NOF.FAT_NOF_FL_STATUS,
          NOF.FAT_NFO_VL_FATURADO,
          NOF.FAT_NOF_MES_FAT,
          NOF.FAT_NOF_ANO_FAT,
          UNI.CAD_UNI_DS_UNIDADE,
          NOF.CAD_UNI_DS_MUNICIPIO AS AUX_MUN_NM_MUNICIPIO,
          NOF.FAT_NOF_ID
  FROM    TB_FAT_NOF_NOTA_FISCAL NOF
  JOIN    TB_CAD_CNV_CONVENIO  CNV  ON      CNV.CAD_CNV_ID_CONVENIO   = NOF.CAD_CNV_ID_CONVENIO
  JOIN    TB_CAD_UNI_UNIDADE UNI  ON      UNI.CAD_UNI_ID_UNIDADE = NOF.CAD_UNI_ID_UNIDADE  
  JOIN    TB_FAT_CCP_CONTA_CONS_PARC CCP  ON      CCP.FAT_NOF_ID = NOF.FAT_NOF_ID 
											AND CCP.FAT_CCP_MES_FAT = NOF.FAT_NOF_MES_FAT 
											AND CCP.FAT_CCP_ANO_FAT = NOF.FAT_NOF_ANO_FAT

  WHERE    ENDE.AUX_TTE_CD_TP_TEL_END = 2
  AND          (' ||CHR(39)||  pATD_ATE_TP_PACIENTE_I  ||CHR(39)|| ' IS not NULL and CCP.ATD_ATE_TP_PACIENTE = ''I''
   OR          ' ||CHR(39)||  pATD_ATE_TP_PACIENTE_E  ||CHR(39)|| ' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = ''E''
   OR          ' ||CHR(39)||  pATD_ATE_TP_PACIENTE_A  ||CHR(39)|| ' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = ''A''
   OR          ' ||CHR(39)||  pATD_ATE_TP_PACIENTE_U  ||CHR(39)|| ' IS NOT NULL AND CCP.ATD_ATE_TP_PACIENTE = ''U''   )
  
  AND (' ||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_GB  ||CHR(39)|| ' IS not NULL and CNV.CAD_TPE_CD_CODIGO = ''ACS''
   OR '  ||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_PA  ||CHR(39)|| ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ''PA''
   OR '  ||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_SP  ||CHR(39)|| ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ''SP''
   OR '  ||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_FU  ||CHR(39)|| ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ''FU''
   OR '  ||CHR(39)|| pCAD_PLA_CD_TIPOPLANO_NP  ||CHR(39)|| ' IS NOT NULL AND CNV.CAD_TPE_CD_CODIGO = ''NP'')
  ' || V_WHERE || '  
  ORDER BY NOF.FAT_NOF_NR_NOTAFISCAL';
  
  --AND NOF.FAT_NFO_DT_EMISSAO > ''01/03/2012'' (valor reten?ao nao era preenchido antes de mar?o)
   -- TESTE :=  V_SELECT ;
OPEN v_cursor FOR
   V_SELECT ;
  --select 1 from dual;
    io_cursor := v_cursor;
END PRC_FAT_REL_FATURAS_EMI;


