CREATE OR REPLACE PROCEDURE "PRC_COB_REL_02_MOV_FAT_GUIA"
  (
    pCAD_UNI_ID_UNIDADE  IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pDATA_EMISSAO_INI    IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pDATA_EMISSAO_FIM    IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_EMISSAO%TYPE DEFAULT NULL,
    pDATA_VENCIMENTO_INI IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
    pDATA_VENCIMENTO_FIM IN TB_FAT_NOF_NOTA_FISCAL.FAT_NFO_DT_VENCIMENTO%TYPE DEFAULT NULL,
    pDATA_PAGTO_INI      IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pDATA_PAGTO_FIM      IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pDATA_CONTAB_INI     IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_LIBERACAO_CONTAB%TYPE DEFAULT NULL,
    pDATA_CONTAB_FIM     IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_LIBERACAO_CONTAB%TYPE DEFAULT NULL,
    pDATA_MOVIMENTO_FIM  IN TB_COB_MGC_MOV_GUIA_COBRANCA.COB_MGC_DT_MOVIMENTO%TYPE DEFAULT NULL,
    pCAD_BAN_ID          IN TB_CAD_BAN_BANCO.CAD_BAN_ID%TYPE DEFAULT NULL,
    pASS_BCT_ID          IN TB_COB_MGC_MOV_GUIA_COBRANCA.ASS_BCT_ID%TYPE DEFAULT NULL,
    pPENDETE_CONTABILIDADE   VARCHAR2 DEFAULT NULL,
    pENVIADO_CONTABILIDADE   VARCHAR2 DEFAULT NULL,
    pAMBULATORIO             VARCHAR2 DEFAULT NULL,
    pINTERNADO               VARCHAR2 DEFAULT NULL,
    pCOM_PAGAMENTO           VARCHAR2 DEFAULT NULL,
    pSEM_PAGAMENTO           VARCHAR2 DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_A   VARCHAR2 DEFAULT NULL,
    pATD_ATE_TP_PACIENTE_I   VARCHAR2 DEFAULT NULL,
    PDESCONSIDERAR_QUITADOS  VARCHAR2 DEFAULT NULL,
    PDESCONSIDERAR_QUITADOS_VALOR VARCHAR2 DEFAULT NULL,
    pFAT_NOF_NR_NOTAFISCAL   IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_NR_NOTAFISCAL%TYPE DEFAULT NULL,
    pFAT_NOF_TP_SERIEFISCAL  IN TB_FAT_NOF_NOTA_FISCAL.FAT_NOF_TP_SERIEFISCAL%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_ACS   IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_FU    IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_PA    IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_SP    IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_TPE_CD_CODIGO_NP    IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
   --  ,TESTE OUT LONG
  )
  is
  /********************************************************************
  *    Procedure: PRC_COB_REL_02_MOV_FAT_GUIA
  *
  *    Data Criac?o: 15/08/2012  Por: PEDRO
  *    Alteracao:
  *
  *    UTILIZADO NOS RELATORIOS 02  03  04
  *******************************************************************/
v_cursor PKG_CURSOR.t_cursor;
  V_WHERE_NOTA  varchar2(3000);
  V_WHERE_MGC  varchar2(3000);
  V_SELECT  varchar2(30000);
begin
  V_WHERE_NOTA := NULL;
IF pCAD_UNI_ID_UNIDADE IS NOT NULL THEN V_WHERE_NOTA:= V_WHERE_NOTA || ' AND NOF.CAD_UNI_ID_UNIDADE = ' || pCAD_UNI_ID_UNIDADE; END IF;
IF pCAD_CNV_ID_CONVENIO IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND NOF.CAD_CNV_ID_CONVENIO = ' || pCAD_CNV_ID_CONVENIO;    END IF;
IF pFAT_NOF_NR_NOTAFISCAL IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND NOF.FAT_NOF_NR_NOTAFISCAL = ' ||CHR(39)|| pFAT_NOF_NR_NOTAFISCAL ||CHR(39);    END IF;
IF pFAT_NOF_TP_SERIEFISCAL IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND NOF.FAT_NOF_TP_SERIEFISCAL = ' ||CHR(39)|| pFAT_NOF_TP_SERIEFISCAL ||CHR(39);    END IF;
IF pDATA_EMISSAO_INI IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_EMISSAO) >= ' ||CHR(39)|| pDATA_EMISSAO_INI ||CHR(39);    END IF;
IF pDATA_EMISSAO_FIM IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_EMISSAO) <= ' ||CHR(39)|| pDATA_EMISSAO_FIM ||CHR(39);    END IF;
IF pDATA_VENCIMENTO_INI IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_VENCIMENTO) >= ' ||CHR(39)|| pDATA_VENCIMENTO_INI ||CHR(39);    END IF;
IF pDATA_VENCIMENTO_FIM IS NOT NULL THEN V_WHERE_NOTA := V_WHERE_NOTA || ' AND TRUNC(NOF.FAT_NFO_DT_VENCIMENTO) <= ' ||CHR(39)|| pDATA_VENCIMENTO_FIM ||CHR(39);    END IF;
V_WHERE_MGC := NULL;
IF pDATA_CONTAB_INI IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_LIBERACAO_CONTAB >= ' ||CHR(39)|| pDATA_CONTAB_INI ||CHR(39);    END IF;
IF pDATA_CONTAB_FIM IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_LIBERACAO_CONTAB <= ' ||CHR(39)|| pDATA_CONTAB_FIM ||CHR(39);    END IF;
IF pDATA_PAGTO_INI IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_MOVIMENTO >= ' ||CHR(39)|| pDATA_PAGTO_INI ||CHR(39);    END IF;
IF pDATA_PAGTO_FIM IS NOT NULL THEN V_WHERE_MGC := V_WHERE_MGC || ' AND MGC.COB_MGC_DT_MOVIMENTO <= ' ||CHR(39)|| pDATA_PAGTO_FIM ||CHR(39);    END IF;
IF pASS_BCT_ID IS NOT NULL THEN V_WHERE_MGC:= V_WHERE_MGC || ' AND MGC.ASS_BCT_ID = ' || pASS_BCT_ID; END IF; 
V_SELECT:=
'
SELECT --DISTINCT
       2 ORDEM,
       NULL CAD_BAN_NM_BANCO,
       NULL ASS_BCT_NR_CONTA, --DUPLICA LINHA E NAO USA NESSES RELATORIOS
       CNV.CAD_CNV_CD_HAC_PRESTADOR, --4
       CNV.CAD_CNV_NM_FANTASIA,
       CCP.CAD_PES_NM_PESSOA, --6
       CCP.CAD_PAC_CD_CREDENCIAL,
       CCP.ATD_ATE_DT_ATENDIMENTO,
       UNI.CAD_UNI_DS_UNIDADE, --9
       TRUNC(NOF.FAT_NFO_DT_EMISSAO) FAT_NFO_DT_EMISSAO,
       TRUNC(NOF.FAT_NFO_DT_VENCIMENTO) FAT_NFO_DT_VENCIMENTO, --11
       ULTIMO_PGTO.COB_MGC_DT_MOVIMENTO,
       NOF.FAT_NOF_ID,
       NOF.FAT_NOF_NR_NOTAFISCAL, --14
       NOF.FAT_NOF_TP_SERIEFISCAL, --15
       NOF.FAT_NFO_VL_FATURADO,
       NOF.FAT_NOF_VL_ISS,                 
       NOF.FAT_NOF_VL_IR,                 
       NOF.FAT_NOF_VL_CSLL,                 
       NOF.FAT_NOF_VL_PIS,                 
       NOF.FAT_NOF_VL_COFINS,       
       NOF.FAT_NOF_VL_DESCONTO,                 
       NOF.FAT_NFO_VL_RETENCAO,
       NOF.FAT_NFO_VL_LIQUIDO,
       CCP.COB_CCP_VL_ISS_FATURADO,
       CCP.COB_CCP_VL_IR_FATURADO,
       CCP.COB_CCP_VL_CSLL_FATURADO,
       CCP.COB_CCP_VL_PIS_FATURADO,
       CCP.COB_CCP_VL_COFINS_FATURADO,
       CCP.COB_CCP_VL_TOT_CONTA,
       CCP.COB_CCP_VL_TOT_CONTA - NVL(CCP.COB_CCP_VL_ISS_FATURADO,0) - NVL(CCP.COB_CCP_VL_IR_FATURADO,0) -
          NVL(CCP.COB_CCP_VL_CSLL_FATURADO,0) - NVL(CCP.COB_CCP_VL_PIS_FATURADO,0) -
          NVL(CCP.COB_CCP_VL_COFINS_FATURADO,0)    VALOR_LIQUIDO_PARCELA,
       SUM( NVL(MGC.COB_MGC_VL_ISS,0))  COB_MGC_VL_ISS,
       SUM( NVL(MGC.COB_MGC_VL_IR,0))  COB_MGC_VL_IR,
       SUM( NVL(MGC.COB_MGC_VL_CSLL,0))  COB_MGC_VL_CSLL,
       SUM( NVL(MGC.COB_MGC_VL_PIS,0))  COB_MGC_VL_PIS,
       SUM( NVL(MGC.COB_MGC_VL_COFINS,0))  COB_MGC_VL_COFINS,
       NVL(GLOSA.GLOSA,0) GLOSA,
       0 DESCONTO, 
       SUM( NVL(MGC.COB_MGC_VL_MOVIMENTO,0))  COB_MGC_VL_MOVIMENTO,
       SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
           NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0))  VALOR_DIGITADO, --vl calculado na tela
       SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                                       NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0))
                                      -  NVL(SUM(MGC.COB_MGC_VL_MOVIMENTO),0)  TOTAL_RETENCOES,
       NULL COB_MGC_DT_LIBERACAO_CONTAB,
       CCP.ATD_GUI_CD_CODIGO,
       CCP.ATD_ATE_ID,
       CCP.COB_CCP_ID,
       CCP.COB_COC_ID,
       CCP.CAD_PAC_ID_PACIENTE,
       CCP.ATD_GUI_DT_VALIDADE
FROM      TB_FAT_NOF_NOTA_FISCAL       NOF
JOIN      TB_COB_CCP_CONTA_CONS_PARC   CCP  ON  CCP.FAT_NOF_ID          = NOF.FAT_NOF_ID
JOIN      TB_CAD_CNV_CONVENIO          CNV  ON  CNV.CAD_CNV_ID_CONVENIO = NOF.CAD_CNV_ID_CONVENIO
LEFT JOIN TB_COB_MGC_MOV_GUIA_COBRANCA MGC  ON  MGC.FAT_NOF_ID          = CCP.FAT_NOF_ID
                                           AND  MGC.ATD_ATE_ID          = CCP.ATD_ATE_ID
                                           AND  MGC.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
                                           AND  MGC.COB_COC_ID          = CCP.COB_COC_ID
                                           AND  MGC.COB_CCP_ID          = CCP.COB_CCP_ID
                                           AND  MGC.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
                                           AND  MGC.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE
                                           AND  MGC.CAD_TMC_ID          NOT IN (7,8)
                                         ' || V_WHERE_MGC || '
LEFT JOIN  (SELECT MIN(TRUNC(MGC.COB_MGC_DT_MOVIMENTO)) COB_MGC_DT_MOVIMENTO,
                   MGC.FAT_NOF_ID, MGC.ATD_ATE_ID, MGC.CAD_PAC_ID_PACIENTE, MGC.COB_COC_ID,
                   MGC.COB_CCP_ID, MGC.ATD_GUI_CD_CODIGO, MGC.ATD_GUI_DT_VALIDADE
            FROM TB_COB_MGC_MOV_GUIA_COBRANCA MGC
            JOIN TB_FAT_NOF_NOTA_FISCAL NOF ON NOF.FAT_NOF_ID = MGC.FAT_NOF_ID
                WHERE   MGC.CAD_TMC_ID          NOT IN (7,8)
             '  || V_WHERE_NOTA || ' 
             '  || V_WHERE_MGC || '
                 AND (('||chr(39)||pCOM_PAGAMENTO ||chr(39)||' IS NOT NULL AND NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                                            NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0) != 0) OR
                      ('||chr(39)||pSEM_PAGAMENTO ||chr(39)||' IS NOT NULL AND NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                                            NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0) = 0))
               GROUP BY  MGC.FAT_NOF_ID, MGC.ATD_ATE_ID, MGC.CAD_PAC_ID_PACIENTE, MGC.COB_COC_ID,
                   MGC.COB_CCP_ID, MGC.ATD_GUI_CD_CODIGO, MGC.ATD_GUI_DT_VALIDADE
          ) ULTIMO_PGTO
          ON  ULTIMO_PGTO.FAT_NOF_ID          = CCP.FAT_NOF_ID
         AND  ULTIMO_PGTO.ATD_ATE_ID          = CCP.ATD_ATE_ID
         AND  ULTIMO_PGTO.CAD_PAC_ID_PACIENTE = CCP.CAD_PAC_ID_PACIENTE
         AND  ULTIMO_PGTO.COB_COC_ID          = CCP.COB_COC_ID
         AND  ULTIMO_PGTO.COB_CCP_ID          = CCP.COB_CCP_ID
         AND  ULTIMO_PGTO.ATD_GUI_CD_CODIGO   = CCP.ATD_GUI_CD_CODIGO
         AND  ULTIMO_PGTO.ATD_GUI_DT_VALIDADE = CCP.ATD_GUI_DT_VALIDADE 
LEFT JOIN  (SELECT  SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0)) GLOSA, MGC.ATD_ATE_ID , MGC.CAD_PAC_ID_PACIENTE ,MGC.COB_CCP_ID ,MGC.COB_COC_ID,
                    MGC.ATD_GUI_CD_CODIGO ,MGC.ATD_GUI_DT_VALIDADE, MGC.FAT_NOF_ID
               FROM TB_COB_MGC_MOV_GUIA_COBRANCA MGC
               JOIN TB_FAT_NOF_NOTA_FISCAL NOF ON NOF.FAT_NOF_ID = MGC.FAT_NOF_ID
            WHERE   MGC.CAD_TMC_ID          = 2
         ' || V_WHERE_NOTA || '
         ' || V_WHERE_MGC || '
            AND (('||chr(39)||pCOM_PAGAMENTO ||chr(39)||' IS NOT NULL AND NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                             NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0) != 0) OR
              ('||chr(39)||pSEM_PAGAMENTO ||chr(39)||' IS NOT NULL AND NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
                             NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0) = 0))
           GROUP BY MGC.ATD_ATE_ID ,MGC.CAD_PAC_ID_PACIENTE ,MGC.COB_CCP_ID , MGC.COB_COC_ID,MGC.ATD_GUI_CD_CODIGO ,
                    MGC.ATD_GUI_DT_VALIDADE, MGC.FAT_NOF_ID
         ) GLOSA --N.C. 
         ON   GLOSA.ATD_ATE_ID          = MGC.ATD_ATE_ID 
        AND   GLOSA.CAD_PAC_ID_PACIENTE = MGC.CAD_PAC_ID_PACIENTE 
        AND   GLOSA.COB_CCP_ID          = MGC.COB_CCP_ID  
        AND   GLOSA.COB_COC_ID          = MGC.COB_COC_ID
        AND   GLOSA.ATD_GUI_CD_CODIGO   = MGC.ATD_GUI_CD_CODIGO 
        AND   GLOSA.ATD_GUI_DT_VALIDADE = MGC.ATD_GUI_DT_VALIDADE
        AND   GLOSA.FAT_NOF_ID          = MGC.FAT_NOF_ID
JOIN      TB_CAD_UNI_UNIDADE           UNI  ON  UNI.CAD_UNI_ID_UNIDADE  = NOF.CAD_UNI_ID_UNIDADE
LEFT JOIN TB_CAD_TMC_TIPO_MOV_COBRANCA TMC  ON  TMC.CAD_TMC_ID          = MGC.CAD_TMC_ID
LEFT JOIN TB_ASS_BCT_BANCO_CONTA       BCT  ON  BCT.ASS_BCT_ID          = MGC.ASS_BCT_ID
                                            AND    ('||chr(39)|| pCAD_BAN_ID ||chr(39)||' is null or BCT.CAD_BAN_ID = '||chr(39)|| pCAD_BAN_ID ||chr(39)||')
LEFT JOIN TB_CAD_BAN_BANCO             BAN  ON  BAN.CAD_BAN_ID          = BCT.CAD_BAN_ID
 WHERE 1 = 1
 ' || V_WHERE_NOTA || '
  AND    CNV.CAD_CNV_CD_OPCAO_PAGTO = 1
  /*AND (( '||chr(39)||pAMBULATORIO ||chr(39)||' IS NOT NULL AND CCP.CAD_LAT_ID_LOCAL_ATENDIMENTO != 29) OR
      ( '||chr(39)||pINTERNADO ||chr(39)||' IS NOT NULL AND CCP.CAD_LAT_ID_LOCAL_ATENDIMENTO = 29))*/
GROUP BY 
       null,
       NULL,
       CNV.CAD_CNV_CD_HAC_PRESTADOR,
       CNV.CAD_CNV_NM_FANTASIA,
       CCP.CAD_PES_NM_PESSOA,
       CCP.CAD_PAC_CD_CREDENCIAL,
       CCP.ATD_ATE_DT_ATENDIMENTO,
       UNI.CAD_UNI_DS_UNIDADE,
       TRUNC(NOF.FAT_NFO_DT_EMISSAO) ,
       TRUNC(NOF.FAT_NFO_DT_VENCIMENTO) ,
       ULTIMO_PGTO.COB_MGC_DT_MOVIMENTO,
       NOF.FAT_NOF_ID,
       NOF.FAT_NOF_NR_NOTAFISCAL,
       NOF.FAT_NOF_TP_SERIEFISCAL,
       NOF.FAT_NFO_VL_FATURADO,
       NOF.FAT_NOF_VL_ISS,                 
       NOF.FAT_NOF_VL_IR,                 
       NOF.FAT_NOF_VL_CSLL,                 
       NOF.FAT_NOF_VL_PIS,                 
       NOF.FAT_NOF_VL_COFINS,       
       NOF.FAT_NOF_VL_DESCONTO,                 
       NOF.FAT_NFO_VL_RETENCAO,
       NOF.FAT_NFO_VL_LIQUIDO,
       CCP.COB_CCP_VL_ISS_FATURADO,
       CCP.COB_CCP_VL_IR_FATURADO,
       CCP.COB_CCP_VL_CSLL_FATURADO,
       CCP.COB_CCP_VL_PIS_FATURADO,
       CCP.COB_CCP_VL_COFINS_FATURADO,
       CCP.COB_CCP_VL_TOT_CONTA,
       CCP.COB_CCP_VL_TOT_CONTA - CCP.COB_CCP_VL_ISS_FATURADO - CCP.COB_CCP_VL_IR_FATURADO - CCP.COB_CCP_VL_CSLL_FATURADO -
       CCP.COB_CCP_VL_PIS_FATURADO - CCP.COB_CCP_VL_COFINS_FATURADO,
       NVL(GLOSA.GLOSA,0),
       0,
       NULL,
       CCP.ATD_GUI_CD_CODIGO,
       CCP.ATD_ATE_ID,
       CCP.COB_CCP_ID,
       CCP.COB_COC_ID,
       CCP.CAD_PAC_ID_PACIENTE,
       CCP.ATD_GUI_DT_VALIDADE
HAVING (( '||chr(39)||PDESCONSIDERAR_QUITADOS ||chr(39)||' IS NOT NULL AND (SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
       NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) + TO_Number('||chr(39)|| PDESCONSIDERAR_QUITADOS_VALOR ||chr(39)||','||chr(39)||'999999.99'||chr(39)||')) < CCP.COB_CCP_VL_TOT_CONTA) OR '||chr(39)|| PDESCONSIDERAR_QUITADOS ||chr(39)||' IS NULL)
       AND (( '||chr(39)||pCOM_PAGAMENTO ||chr(39)||' IS NOT NULL AND SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
               NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) != 0) OR
           ( '||chr(39)||pSEM_PAGAMENTO ||chr(39)||' IS NOT NULL AND SUM(NVL(MGC.COB_MGC_VL_MOVIMENTO,0) + NVL(MGC.COB_MGC_VL_ISS,0) + NVL(MGC.COB_MGC_VL_IR,0) + NVL(MGC.COB_MGC_VL_CSLL,0) +
           NVL(MGC.COB_MGC_VL_PIS,0) + NVL(MGC.COB_MGC_VL_COFINS,0)) = 0))
ORDER BY 4,--CNV.CAD_CNV_CD_HAC_PRESTADOR,
         11,--NOF.FAT_NFO_DT_VENCIMENTO,
         9,--CAD_UNI_DS_UNIDADE
         14,--NOF.FAT_NOF_NR_NOTAFISCAL,
         15,--NOF.FAT_NOF_TP_SERIEFISCAL,
         6--CCP.CAD_PES_NM_PESSOA
 ' ;
  --  TESTE :=  V_SELECT ;
   --dbms_output.put_line(V_SELECT);
  OPEN v_cursor FOR
 -- SELECT 1 FROM DUAL;
   V_SELECT ;
    io_cursor := v_cursor;
  end PRC_COB_REL_02_MOV_FAT_GUIA;
