CREATE OR REPLACE PROCEDURE PRC_SEG_LOGIN
   ( 
      pSEG_USU_DS_LOGIN    IN  TB_SEG_USU_USUARIO.SEG_USU_DS_LOGIN%TYPE,
      pSEG_USU_CD_PASSWORD IN  TB_SEG_USU_USUARIO.SEG_USU_CD_PASSWORD%TYPE,
      io_cursor            OUT PKG_CURSOR.t_cursor
   )
   IS
  v_cursor PKG_CURSOR.t_cursor;   
  /*
  0 FLAG STATUS ESTA SENDO CONVERTIDO PARA NUMBER PARA MANTER COMPATIBILIDADE COM ENUM DENTRO DO SISTEMA
  0 = INATIVO
  1 = ATIVO
  2 = BLOQUEADO
  */
BEGIN
   if ( pSEG_USU_CD_PASSWORD IS NULL ) THEN
      RAISE_APPLICATION_ERROR(-20000,'SENHA EM BRANCO');
   END IF;
   OPEN v_cursor FOR
   SELECT SEG_USU_ID_USUARIO, 
          SEG_USU_DS_NOME, 
          DECODE(SEG_USU_FL_STATUS, 'I', 0,  
                                    'A', 1, 
                                    'B', 2) SEG_USU_FL_STATUS
   FROM TB_SEG_USU_USUARIO USUARIO
   WHERE SEG_USU_DS_LOGIN    = UPPER(pSEG_USU_DS_LOGIN)
   AND   SEG_USU_CD_PASSWORD = SGS.MD5(pSEG_USU_CD_PASSWORD);
   io_cursor := v_cursor;

END; -- Procedure 