 create or replace procedure PRC_CAD_MTMD_CCONTAB_GRUPO_L
(
     pCAD_MTMD_TIPO_MOV IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_MTMD_TIPO_MOV%type DEFAULT NULL,
     pCAD_MTMD_GRUPO_ID IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_MTMD_GRUPO_ID%type DEFAULT NULL,
     pCAD_MTMD_DT_INI_VIG IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_MTMD_DT_INI_VIG%type DEFAULT NULL,
     pCAD_MTMD_DT_FIM_VIG IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_MTMD_DT_FIM_VIG%type DEFAULT NULL,
     pCAD_MTMD_COD_COLIGADA IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_MTMD_COD_COLIGADA%type DEFAULT NULL,
     pCAD_SET_ID IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_SET_ID%type DEFAULT NULL,
     pCAD_COD_CONTA_CRED IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_COD_CONTA_CRED%type DEFAULT NULL,
     pCAD_COD_CONTA_CRED_DESCRICAO IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_COD_CONTA_CRED_DESCRICAO%type DEFAULT NULL,
     pCAD_COD_CONTA_DEB IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_COD_CONTA_DEB%type DEFAULT NULL,
     pCAD_COD_CONTA_DEB_DESCRICAO IN TB_CAD_MTMD_CCONTAB_GRUPO.CAD_COD_CONTA_DEB_DESCRICAO%type DEFAULT NULL,
     pSEG_DT_ATUALIZACAO IN TB_CAD_MTMD_CCONTAB_GRUPO.SEG_DT_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_CAD_MTMD_CCONTAB_GRUPO.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pTRAZER_TODOS_GRUPOS NUMBER, --0 ou 1 (para montar grid) 
     io_cursor OUT PKG_CURSOR.t_cursor
)
is
/********************************************************************
*    Procedure: PRC_CAD_MTMD_CCONTAB_GRUPO_L
*
*    Data Criacao: 	31/01/2012   Por: André S. Monaco
*
*    Funcao: Selecionar conta do grupo
*
*******************************************************************/
 v_cursor PKG_CURSOR.t_cursor;
  V_WHERE  varchar2(5000);
  V_SELECT varchar2(5000);
  V_NOT_IN_GRUPO varchar2(5000);
begin
  V_WHERE := NULL;
  
  IF pCAD_MTMD_TIPO_MOV IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_MTMD_TIPO_MOV = ' || CHR(39) || pCAD_MTMD_TIPO_MOV || CHR(39); END IF;
  IF pCAD_MTMD_GRUPO_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_MTMD_GRUPO_ID = ' || pCAD_MTMD_GRUPO_ID; END IF;
  IF pCAD_MTMD_DT_INI_VIG IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_MTMD_DT_INI_VIG = ' || CHR(39) || pCAD_MTMD_DT_INI_VIG || CHR(39); END IF;
  IF pCAD_MTMD_DT_FIM_VIG IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_MTMD_DT_FIM_VIG = ' || CHR(39) || pCAD_MTMD_DT_FIM_VIG || CHR(39); END IF;
  IF pCAD_MTMD_COD_COLIGADA IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_MTMD_COD_COLIGADA = ' || pCAD_MTMD_COD_COLIGADA; END IF;
  IF pCAD_SET_ID IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_SET_ID = ' || pCAD_SET_ID; END IF;
  IF pCAD_COD_CONTA_CRED IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_COD_CONTA_CRED = ' || CHR(39) || pCAD_COD_CONTA_CRED || CHR(39); END IF;
  IF pCAD_COD_CONTA_CRED_DESCRICAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_COD_CONTA_CRED_DESCRICAO = ' || CHR(39) || pCAD_COD_CONTA_CRED_DESCRICAO || CHR(39); END IF;
  IF pCAD_COD_CONTA_DEB IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_COD_CONTA_DEB = ' || CHR(39) || pCAD_COD_CONTA_DEB || CHR(39); END IF;
  IF pCAD_COD_CONTA_DEB_DESCRICAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.CAD_COD_CONTA_DEB_DESCRICAO = ' || CHR(39) || pCAD_COD_CONTA_DEB_DESCRICAO || CHR(39); END IF;
  IF pSEG_DT_ATUALIZACAO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.SEG_DT_ATUALIZACAO = ' || CHR(39) || pSEG_DT_ATUALIZACAO || CHR(39); END IF;
  IF pSEG_USU_ID_USUARIO IS NOT NULL THEN V_WHERE:= V_WHERE || ' AND CCG.SEG_USU_ID_USUARIO = ' || pSEG_USU_ID_USUARIO; END IF;
  
  V_NOT_IN_GRUPO:= 'SELECT CAD_MTMD_GRUPO_ID FROM TB_CAD_MTMD_CCONTAB_GRUPO CCG WHERE NULL IS NULL ' || V_WHERE;
  
  IF (pTRAZER_TODOS_GRUPOS = 1) THEN
    V_SELECT := '
    SELECT CAD_MTMD_GRUPO_ID,
           CAD_MTMD_GRUPO_DESCRICAO,
           NULL CAD_MTMD_TIPO_MOV,
           NULL CAD_MTMD_DT_INI_VIG,
           NULL CAD_MTMD_DT_FIM_VIG,
           NULL CAD_MTMD_COD_COLIGADA,
           NULL CAD_SET_ID,
           NULL CAD_COD_CONTA_CRED,
           NULL CAD_COD_CONTA_CRED_DESCRICAO,
           NULL CAD_COD_CONTA_DEB,
           NULL CAD_COD_CONTA_DEB_DESCRICAO,
           NULL SEG_DT_ATUALIZACAO,
           NULL SEG_USU_ID_USUARIO,
           NULL CAD_SET_DS_SETOR
    FROM TB_CAD_MTMD_GRUPO
    WHERE CAD_MTMD_GRUPO_ID NOT IN (' || V_NOT_IN_GRUPO || ') 
    UNION ';
  END IF;
  
  V_WHERE:= V_WHERE || ' ORDER BY 8, 1, 4 DESC';
  
  V_SELECT := V_SELECT || '
  SELECT G.CAD_MTMD_GRUPO_ID,
         G.CAD_MTMD_GRUPO_DESCRICAO,
         CCG.CAD_MTMD_TIPO_MOV,
         CCG.CAD_MTMD_DT_INI_VIG,
         CCG.CAD_MTMD_DT_FIM_VIG,
         CCG.CAD_MTMD_COD_COLIGADA,
         CCG.CAD_SET_ID,
         CCG.CAD_COD_CONTA_CRED,
         CCG.CAD_COD_CONTA_CRED_DESCRICAO,
         CCG.CAD_COD_CONTA_DEB,
         CCG.CAD_COD_CONTA_DEB_DESCRICAO,
         CCG.SEG_DT_ATUALIZACAO,
         CCG.SEG_USU_ID_USUARIO,
         DECODE(S.CAD_SET_ID, NULL, NULL,U.CAD_UNI_DS_UNIDADE || '' / '' || S.CAD_SET_DS_SETOR) CAD_SET_DS_SETOR
  FROM TB_CAD_MTMD_CCONTAB_GRUPO CCG,
       TB_CAD_MTMD_GRUPO G,
       TB_CAD_SET_SETOR S,
       TB_CAD_UNI_UNIDADE U
  WHERE G.CAD_MTMD_GRUPO_ID = CCG.CAD_MTMD_GRUPO_ID AND
        S.CAD_SET_ID (+)= CCG.CAD_SET_ID AND
        U.CAD_UNI_ID_UNIDADE (+)= S.CAD_UNI_ID_UNIDADE ';

  OPEN v_cursor FOR
  V_SELECT || V_WHERE ;
  io_cursor := v_cursor;
  
end PRC_CAD_MTMD_CCONTAB_GRUPO_L;
