create or replace procedure PRC_MTMD_MATMED_FUNC_S
  (
     pSEG_FUN_ID_FUNCIONALIDADE IN TB_MTMD_MATMED_FUNC.SEG_FUN_ID_FUNCIONALIDADE%type DEFAULT NULL,
     pCAD_MTMD_ID IN TB_MTMD_MATMED_FUNC.CAD_MTMD_ID%type DEFAULT NULL,
     pMTMD_DT_ATUALIZACAO IN TB_MTMD_MATMED_FUNC.MTMD_DT_ATUALIZACAO%type DEFAULT NULL,
     pSEG_USU_ID_USUARIO IN TB_MTMD_MATMED_FUNC.SEG_USU_ID_USUARIO%type DEFAULT NULL,
     pCAD_MTMD_NOMEFANTASIA IN TB_CAD_MTMD_MAT_MED.CAD_MTMD_NOMEFANTASIA%type DEFAULT NULL,
     io_cursor OUT PKG_CURSOR.t_cursor
  )
  is
  /********************************************************************
  *    Procedure: PRC_MTMD_MATMED_FUNC_S
  *
  *    Data Criacao:   10/5/2010   Por: Andre Souza Monaco
  *    Data Alteracao:            Por:
  *
  *    Funcao: Lista registros da TB_MTMD_MATMED_FUNC
  *
  *******************************************************************/
  v_cursor PKG_CURSOR.t_cursor;
  begin
    OPEN v_cursor FOR
    SELECT
       MMF.SEG_FUN_ID_FUNCIONALIDADE,
       MMF.CAD_MTMD_ID,
       MMF.MTMD_DT_ATUALIZACAO,
       MMF.SEG_USU_ID_USUARIO,
       MMM.CAD_MTMD_NOMEFANTASIA,
       MMM.CAD_MTMD_GRUPO_ID,
       MMM.CAD_MTMD_FL_FRACIONA,
       MMM.CAD_MTMD_UNID_VENDA_DS,
       MMM.CAD_MTMD_FL_MAV,
       MMF.QTDE_MAXIMA_PEDIDO,
       MMM.CAD_MTMD_PRIATI_ID
    FROM TB_MTMD_MATMED_FUNC MMF,
         TB_CAD_MTMD_MAT_MED MMM
    WHERE
         MMF.CAD_MTMD_ID = MMM.CAD_MTMD_ID AND
        (pSEG_FUN_ID_FUNCIONALIDADE is null OR MMF.SEG_FUN_ID_FUNCIONALIDADE = pSEG_FUN_ID_FUNCIONALIDADE) AND
        (pCAD_MTMD_ID is null OR MMF.CAD_MTMD_ID = pCAD_MTMD_ID) AND
        (pMTMD_DT_ATUALIZACAO is null OR MMF.MTMD_DT_ATUALIZACAO = pMTMD_DT_ATUALIZACAO) AND
        (pSEG_USU_ID_USUARIO is null OR MMF.SEG_USU_ID_USUARIO = pSEG_USU_ID_USUARIO) AND
        (pCAD_MTMD_NOMEFANTASIA is null OR MMM.CAD_MTMD_NOMEFANTASIA like pCAD_MTMD_NOMEFANTASIA)
    ORDER BY MMM.CAD_MTMD_NOMEFANTASIA;
    io_cursor := v_cursor;
  end PRC_MTMD_MATMED_FUNC_S;