CREATE OR REPLACE PROCEDURE PRC_FAT_REL_CIRUR_EXEC
(
    pATD_ATE_DT_ATENDIMENTO_INI IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pATD_ATE_DT_ATENDIMENTO_FIM IN TB_ATD_ATE_ATENDIMENTO.ATD_ATE_DT_ATENDIMENTO%TYPE DEFAULT NULL,
    pCAD_UNI_ID_UNIDADE IN TB_ATD_ATE_ATENDIMENTO.CAD_UNI_ID_UNIDADE%TYPE,
    pCAD_LAT_ID_LOCAL_ATENDIMENTO IN TB_ATD_ATE_ATENDIMENTO.CAD_LAT_ID_LOCAL_ATENDIMENTO%TYPE,
    pCAD_SET_ID IN TB_CAD_SET_SETOR.CAD_SET_ID%TYPE DEFAULT NULL,
    pCAD_CNV_ID_CONVENIO     IN TB_CAD_CNV_CONVENIO.CAD_CNV_ID_CONVENIO%TYPE DEFAULT NULL,
    pCAD_PLA_ID_PLANO        IN TB_CAD_PLA_PLANO.CAD_PLA_ID_PLANO%TYPE DEFAULT NULL,
    pTIS_TAT_CD_TPATENDIMENTO IN TB_TIS_TAT_TP_ATENDIMENTO.TIS_TAT_CD_TPATENDIMENTO%TYPE DEFAULT NULL,
    pTIS_CBO_CD_CBOS IN TB_TIS_CBO_CBOS.TIS_CBO_CD_CBOS%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_GB IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_PL IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL, --ACS
    pCAD_PLA_CD_TIPOPLANO_FU IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_NP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_PA IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pCAD_PLA_CD_TIPOPLANO_SP IN TB_CAD_PLA_PLANO.CAD_PLA_CD_TIPOPLANO%TYPE DEFAULT NULL,
    pFAT_CCP_MES_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_MES_FAT%TYPE,
    pFAT_CCP_ANO_FAT IN TB_FAT_CCP_CONTA_CONS_PARC.FAT_CCP_ANO_FAT%TYPE,
    
    IO_CURSOR OUT PKG_CURSOR.T_CURSOR
)
IS
/********************************************************************
*    PROCEDURE: PRC_FAT_REL_CIRUR_EXEC
*    DATA ALTERACAO: 02/07/2010  POR: CAIO H. B. CHAGAS
*    ALTERAÇÃO:
*******************************************************************/
V_CURSOR PKG_CURSOR.T_CURSOR;
BEGIN
  OPEN V_CURSOR FOR

 SELECT   DISTINCT
              PRD.CAD_PRD_DS_DESCRICAO,
              PRO.CAD_PRO_NM_NOME,
              CCI.TIS_GPP_CD_GRAU_PART_PROF,
              GPP.TIS_GPP_DS_GRAU_PART_PROF,
              CCI.FAT_CCI_PC_GRAU_PART_PROF,
              CASE WHEN  CCI.FAT_CCI_TP_PORTEANESTESICO IN (0,1,2) THEN 'PORTE PEQUENO'
                   WHEN  CCI.FAT_CCI_TP_PORTEANESTESICO IN (3,4) THEN 'PORTE MEDIO'
                   WHEN  CCI.FAT_CCI_TP_PORTEANESTESICO IN (5,6,7) THEN 'PORTE GRANDE'
              END DS_PORTE,
          --    CASE WHEN CCI.FAT_CCI_ID_PRINCIPAL IS NOT NULL THEN CCI.FAT_CCI_VL_FATURADO
           --        ELSE 0
           --   END FAT_CCI_VL_FATURADO,
              CCI.FAT_CCI_DT_INICIO_CONSUMO,
              CCI.FAT_CCI_HR_INICIO_CONSUMO,
              CNV.CAD_CNV_CD_HAC_PRESTADOR,
              CNV.CAD_CNV_NM_FANTASIA,
              PLA.CAD_PLA_CD_PLANO_HAC,
              PLA.CAD_PLA_NM_NOME_PLANO,
              PAC.CAD_PAC_NR_PRONTUARIO,
              PES.CAD_PES_NM_PESSOA,
              UNI.CAD_UNI_DS_UNIDADE,
              LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO,
              SET_QLE.CAD_SET_DS_SETOR,
              QLE.CAD_QLE_NR_QUARTO,
              QLE.CAD_QLE_NR_LEITO,
              CCI.CAD_TAP_TP_ATRIBUTO,
              CCI.ATD_ATE_ID,
              CCI.FAT_CCP_ID,
              CCI.FAT_COC_ID,
              CCI.CAD_PAC_ID_PACIENTE,
              COUNT(DECODE(CCI.TIS_GPP_CD_GRAU_PART_PROF,0,'0')) OVER () TOTAL

              FROM    TB_FAT_CCI_CONTA_CONSU_ITEM  CCI
              JOIN    TB_FAT_COC_CONTA_CONSUMO     COC
              ON      COC.ATD_ATE_ID             = CCI.ATD_ATE_ID
              AND     COC.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE
              AND     COC.FAT_COC_ID             = CCI.FAT_COC_ID
              JOIN    TB_FAT_CCP_CONTA_CONS_PARC   CCP
              ON      CCP.FAT_CCP_ID             = CCI.FAT_CCP_ID
              AND     CCP.ATD_ATE_ID             = CCI.ATD_ATE_ID
              AND     CCP.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE
              AND     CCP.FAT_COC_ID             = CCI.FAT_COC_ID
              JOIN    TB_CAD_PRD_PRODUTO           PRD
              ON      PRD.CAD_PRD_ID             = CCI.CAD_PRD_ID
              JOIN    TB_ATD_ATE_ATENDIMENTO       ATE
              ON      CCI.ATD_ATE_ID             = ATE.ATD_ATE_ID
              JOIN    TB_CAD_UNI_UNIDADE           UNI
              ON      UNI.CAD_UNI_ID_UNIDADE     = ATE.CAD_UNI_ID_UNIDADE
              JOIN    TB_CAD_LAT_LOCAL_ATENDIMENTO LAT
              ON      LAT.CAD_LAT_ID_LOCAL_ATENDIMENTO = ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO
              JOIN    TB_CAD_PAC_PACIENTE          PAC
              ON      PAC.CAD_PAC_ID_PACIENTE    = CCI.CAD_PAC_ID_PACIENTE --fnc_buscar_paciente_atual(PAT.ATD_ATE_ID)
              JOIN    TB_CAD_PLA_PLANO             PLA
              ON      PLA.CAD_PLA_ID_PLANO       = PAC.CAD_PLA_ID_PLANO
              JOIN    TB_CAD_CNV_CONVENIO          CNV
              ON      CNV.CAD_CNV_ID_CONVENIO    = PAC.CAD_CNV_ID_CONVENIO
              JOIN    TB_CAD_PES_PESSOA            PES
              ON      PES.CAD_PES_ID_PESSOA      = PAC.CAD_PES_ID_PESSOA
              JOIN    TB_CAD_PRO_PROFISSIONAL      PRO
              ON      PRO.CAD_PRO_ID_PROFISSIONAL = CCI.CAD_PRO_ID_PROFISSIONAL
              JOIN    TB_TIS_GPP_GRAU_PART_PROF    GPP
              ON      GPP.TIS_GPP_CD_GRAU_PART_PROF = CCI.TIS_GPP_CD_GRAU_PART_PROF
              JOIN    TB_FAT_MCC_MOV_COM_CONSUMO MCC
              ON      MCC.ATD_ATE_ID             = CCI.ATD_ATE_ID
              AND     MCC.FAT_MCC_ID             = CCI.FAT_MCC_ID
              JOIN    TB_CAD_SET_SETOR             SETOR
              ON      SETOR.CAD_SET_ID           = MCC.CAD_SET_ID
              JOIN    TB_ATD_IML_INT_MOV_LEITO     IML
              ON      IML.ATD_ATE_ID             = CCI.ATD_ATE_ID
              AND     TO_DATE(TO_CHAR(CCI.FAT_CCI_DT_INICIO_CONSUMO,'dd-MM-yyyy')||TO_CHAR(CCI.FAT_CCI_HR_INICIO_CONSUMO,'0000'),'dd-MM-yyyy HH24MI')
                      BETWEEN TO_DATE(TO_CHAR(IML.ATD_IML_DT_ENTRADA,'dd-MM-yyyy')||TO_CHAR(IML.ATD_IML_HR_ENTRADA,'0000'),'dd-MM-yyyy HH24MI')
                      AND TO_DATE(TO_CHAR(IML.ATD_IML_DT_SAIDA,'dd-MM-yyyy')||TO_CHAR(IML.ATD_IML_HR_SAIDA,'0000'),'dd-MM-yyyy HH24MI')
              JOIN    TB_CAD_QLE_QUARTO_LEITO      QLE
              ON      QLE.CAD_QLE_ID             = IML.CAD_CAD_QLE_ID
              JOIN    TB_CAD_SET_SETOR             SET_QLE
              ON      SET_QLE.CAD_SET_ID         = QLE.CAD_SET_ID
              WHERE   (CCP.FAT_CCP_FL_FATURADA = 'S')
              AND     (ATE.ATD_ATE_FL_STATUS = 'A')
              AND     (ATE.ATD_ATE_TP_PACIENTE IN ('I','E'))
              AND     (CCP.FAT_CCP_FL_STATUS = 'A')
              AND     (COC.FAT_COC_FL_STATUS = 'A')
              AND     (CCI.FAT_CCI_FL_STATUS = 'A')
              AND     (MCC.FAT_MCC_FL_STATUS = 'A')
              AND     (SETOR.CAD_SET_CD_SETOR = 'CECI')
              AND     (CCI.FAT_CCI_TP_PORTEANESTESICO IS NOT NULL)
              AND     (CCI.CAD_TAP_TP_ATRIBUTO = 'HM')
              AND     (CCI.TIS_GPP_CD_GRAU_PART_PROF IN (0,6))
              AND     (IML.ATD_IML_FL_STATUS = 'A')
              AND     (ATE.CAD_UNI_ID_UNIDADE = pCAD_UNI_ID_UNIDADE)
              AND     (ATE.CAD_LAT_ID_LOCAL_ATENDIMENTO = pCAD_LAT_ID_LOCAL_ATENDIMENTO)
              AND     (pCAD_SET_ID IS NULL OR ATE.CAD_SET_ID = pCAD_SET_ID)
              AND     (CCP.FAT_CCP_MES_FAT = pFAT_CCP_MES_FAT)
              AND     (CCP.FAT_CCP_ANO_FAT = pFAT_CCP_ANO_FAT)
              AND     (pTIS_TAT_CD_TPATENDIMENTO IS NULL OR ATE.TIS_TAT_CD_TPATENDIMENTO = pTIS_TAT_CD_TPATENDIMENTO)
              AND     (pTIS_CBO_CD_CBOS IS NULL OR ATE.TIS_CBO_CD_CBOS = pTIS_CBO_CD_CBOS)
              AND     (pCAD_CNV_ID_CONVENIO IS NULL OR PAC.CAD_CNV_ID_CONVENIO = pCAD_CNV_ID_CONVENIO)
              AND     (pCAD_PLA_ID_PLANO IS NULL OR PAC.CAD_PLA_ID_PLANO = pCAD_PLA_ID_PLANO)

              AND (pCAD_PLA_CD_TIPOPLANO_GB IS not NULL and PLA.CAD_PLA_CD_TIPOPLANO = 'GB'
               OR pCAD_PLA_CD_TIPOPLANO_PL IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PL'
               OR pCAD_PLA_CD_TIPOPLANO_PA IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'PA'
               OR pCAD_PLA_CD_TIPOPLANO_SP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'SP'
               OR pCAD_PLA_CD_TIPOPLANO_NP IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'NP'
               OR pCAD_PLA_CD_TIPOPLANO_FU IS NOT NULL AND PLA.CAD_PLA_CD_TIPOPLANO = 'FU')
  ;
  IO_CURSOR := V_CURSOR;
END PRC_FAT_REL_CIRUR_EXEC;
/
